import { q } from "../quiz";
import type { TriviaQ } from "../types";

export const CELEBRITY_BANK: TriviaQ[] = [
  q("The Oscars honor work in…", ["movies", "television only", "pop music only", "sports"], "movies", 1),
  q("The Grammy Awards honor…", ["music", "film only", "television only", "theater only"], "music", 1),
  q("The Emmy Awards honor…", ["television", "film only", "novels", "video games only"], "television", 1),
  q("Hollywood, the film industry's nickname, is in…", ["Los Angeles", "New York", "London", "Chicago"], "Los Angeles", 1),
  q("Broadway theater is centered in…", ["New York", "Los Angeles", "Nashville", "London"], "New York", 1),
  q("Elvis Presley is widely called the king of…", ["rock and roll", "pop only after 1990", "country only", "soul"], "rock and roll", 1),
  q("The Beatles were from…", ["Liverpool", "London", "Manchester", "Dublin"], "Liverpool", 1),
  q("Michael Jackson was often called the king of…", ["pop", "rock and roll", "country", "punk"], "pop", 1),
  q("Mickey Mouse is a character from…", ["Disney", "Warner Bros", "Nickelodeon", "Pixar"], "Disney", 1),
  q("Bruce Wayne is the civilian name of…", ["Batman", "Superman", "Spider-Man", "Iron Man"], "Batman", 1),
  q("Peter Parker is the civilian name of…", ["Spider-Man", "Batman", "Superman", "Wolverine"], "Spider-Man", 1),
  q("The Simpsons live in a town called…", ["Springfield", "Quahog", "South Park", "Bikini Bottom"], "Springfield", 1),
  q("SpongeBob SquarePants lives in…", ["Bikini Bottom", "Springfield", "Bedrock", "Atlantis, Florida"], "Bikini Bottom", 1),
  q("A sitcom is a…", ["situation comedy", "late-night news desk", "concert film", "sports highlight"], "situation comedy", 1),
  q("Marilyn Monroe was famous as a…", ["movie star", "news anchor", "opera composer", "silent-film director only"], "movie star", 1),
  q("Charlie Chaplin was a star of…", ["silent film", "television sitcoms", "radio sports", "music videos"], "silent film", 1),
  q("The four Beatles were John, Paul, George, and…", ["Ringo", "Brian", "Mick", "Pete"], "Ringo", 1),
  q("Han Solo and Indiana Jones were both played by…", ["Harrison Ford", "Mark Hamill", "Tom Hanks", "Sean Connery"], "Harrison Ford", 1),
  q("Princess Leia in Star Wars was played by…", ["Carrie Fisher", "Natalie Portman", "Sigourney Weaver", "Linda Hamilton"], "Carrie Fisher", 1),
  q("Rocky Balboa was played by…", ["Sylvester Stallone", "Arnold Schwarzenegger", "Bruce Willis", "Carl Weathers"], "Sylvester Stallone", 1),
  q("The Terminator made a movie star of…", ["Arnold Schwarzenegger", "Sylvester Stallone", "Jean-Claude Van Damme", "Dolph Lundgren"], "Arnold Schwarzenegger", 1),
  q("Aretha Franklin was called the queen of…", ["soul", "country", "punk", "disco only"], "soul", 1),
  q("Oprah Winfrey became famous as a…", ["talk-show host", "film director only", "pop singer", "news cartoonist"], "talk-show host", 1),
  q("The first Bond film, Dr. No, starred…", ["Sean Connery", "Roger Moore", "Pierce Brosnan", "Daniel Craig"], "Sean Connery", 2),
  q("Dr. No, the first James Bond film, came out in…", ["1962", "1954", "1973", "1985"], "1962", 2),
  q("The Beatles appeared on The Ed Sullivan Show in…", ["1964", "1960", "1969", "1972"], "1964", 2),
  q("Michael Jackson's album Thriller was released in…", ["1982", "1979", "1987", "1975"], "1982", 2),
  q("MTV's first video, in 1981, was…", ["Video Killed the Radio Star", "Thriller", "Billie Jean", "Like a Virgin"], "Video Killed the Radio Star", 2),
  q("Woodstock, the famous music festival, was in…", ["1969", "1967", "1975", "1979"], "1969", 2),
  q("Lady Gaga's given name is…", ["Stefani Germanotta", "Alecia Moore", "Robyn Fenty", "Onika Maraj"], "Stefani Germanotta", 2),
  q("Eminem's given name is…", ["Marshall Mathers", "Shawn Carter", "Andre Young", "Calvin Broadus"], "Marshall Mathers", 2),
  q("Rihanna was born in…", ["Barbados", "Jamaica", "Trinidad", "Puerto Rico"], "Barbados", 2),
  q("Beyoncé rose to fame in the group…", ["Destiny's Child", "TLC", "En Vogue", "The Supremes"], "Destiny's Child", 2),
  q("Freddie Mercury was the lead singer of…", ["Queen", "The Who", "Led Zeppelin", "The Rolling Stones"], "Queen", 2),
  q("David Bowie's alien stage persona was…", ["Ziggy Stardust", "The Thin White Duke only as a real name", "Aladdin Sane as his birth name", "Major Tom"], "Ziggy Stardust", 2),
  q("The Godfather was directed by…", ["Francis Ford Coppola", "Martin Scorsese", "Steven Spielberg", "Alfred Hitchcock"], "Francis Ford Coppola", 2),
  q("Star Wars was created by…", ["George Lucas", "Steven Spielberg", "James Cameron", "Ridley Scott"], "George Lucas", 2),
  q("Titanic and Avatar were both directed by…", ["James Cameron", "George Lucas", "Peter Jackson", "Christopher Nolan"], "James Cameron", 2),
  q("The Lord of the Rings films were directed by…", ["Peter Jackson", "James Cameron", "George Lucas", "Guillermo del Toro"], "Peter Jackson", 2),
  q("Ian McKellen played both Gandalf and…", ["Magneto", "Dumbledore", "Saruman", "Professor X"], "Magneto", 2),
  q("Hugh Jackman is best known on screen as…", ["Wolverine", "Batman", "Superman", "Iron Man"], "Wolverine", 2),
  q("Robert Downey Jr. played Marvel's…", ["Iron Man", "Captain America", "Thor", "Hulk"], "Iron Man", 2),
  q("Breaking Bad's Walter White was played by…", ["Bryan Cranston", "Aaron Paul", "Bob Odenkirk", "Jon Hamm"], "Bryan Cranston", 2),
  q("The Sopranos star James Gandolfini played…", ["Tony Soprano", "Walter White", "Don Draper", "Stringer Bell"], "Tony Soprano", 2),
  q("Dolly Parton is a star of…", ["country music", "opera", "hip-hop", "punk"], "country music", 2),
  q("Prince's 1984 album and film is titled…", ["Purple Rain", "Thriller", "Born in the U.S.A.", "Like a Virgin"], "Purple Rain", 2),
  q("The first Academy Awards ceremony was held in…", ["1929", "1939", "1915", "1948"], "1929", 3),
  q("Wings won the first Academy Award for Outstanding Picture for films of…", ["1927–28", "1939", "1915", "1942"], "1927–28", 3),
  q("Hattie McDaniel, the first Black performer to win an Oscar, was in…", ["Gone with the Wind", "Casablanca", "The Wizard of Oz", "Citizen Kane"], "Gone with the Wind", 3),
  q("Sidney Poitier won Best Actor for…", ["Lilies of the Field", "In the Heat of the Night", "Guess Who's Coming to Dinner", "A Raisin in the Sun"], "Lilies of the Field", 3),
  q("Katharine Hepburn won how many Academy Awards for Best Actress?", ["4", "2", "3", "5"], "4", 3),
  q("Daniel Day-Lewis has won Best Actor how many times?", ["3", "1", "2", "4"], "3", 3),
  q("Marilyn Monroe's birth name was…", ["Norma Jeane Mortenson", "Norma Jean Baker", "Marilyn Baker", "Jean Harlow"], "Norma Jeane Mortenson", 3),
  q("Cary Grant was born with the name…", ["Archibald Alec Leach", "Archibald Cary Grant", "Alec Cary Leach", "Bernard Schwartz"], "Archibald Alec Leach", 3),
  q("Casablanca premiered in…", ["1942", "1939", "1946", "1951"], "1942", 3),
  q("The line \"Here's looking at you, kid\" is from…", ["Casablanca", "Gone with the Wind", "Citizen Kane", "The Maltese Falcon"], "Casablanca", 3),
  q("Citizen Kane was directed by…", ["Orson Welles", "Alfred Hitchcock", "John Ford", "Howard Hawks"], "Orson Welles", 3),
  q("Judy Garland starred as Dorothy in The Wizard of Oz in…", ["1939", "1933", "1946", "1929"], "1939", 3),
  q("Parasite, the first non-English Best Picture winner, was directed by…", ["Bong Joon-ho", "Park Chan-wook", "Hirokazu Kore-eda", "Ang Lee"], "Bong Joon-ho", 3),
  q("The Hollywood Walk of Fame began in…", ["1960", "1950", "1970", "1940"], "1960", 3),
  q("Rita Moreno is one of the few performers to have won an…", ["EGOT", "Olympic medal and an Oscar", "Oscar before age 10", "Emmy for a silent film"], "EGOT", 3),
  q("The Buggles' \"Video Killed the Radio Star\" was the first video played on…", ["MTV", "VH1", "BBC One", "American Bandstand"], "MTV", 3),
  q("Live Aid, the 1985 benefit concerts, was organized by Bob Geldof and…", ["Midge Ure", "Bono", "Freddie Mercury", "George Harrison"], "Midge Ure", 3),
];
