import { q } from "../quiz";
import type { TriviaQ } from "../types";

export const CELEBRITY_BANK: TriviaQ[] = [
  q("The Oscars honor work in…", ["movies", "television only", "pop music only", "sports"], "movies", 1),
  q("The Grammy Awards honor…", ["music", "film only", "television only", "theater only"], "music", 1),
  q("The Emmy Awards honor…", ["television", "film only", "novels", "video games only"], "television", 1),
  q("Hollywood, the film industry's nickname, is in…", ["Los Angeles", "New York", "London", "Chicago"], "Los Angeles", 1),
  q("Broadway theater is centered in…", ["New York", "Los Angeles", "Nashville", "London"], "New York", 1),
  q("Elvis Presley is widely called the king of…", ["rock and roll", "pop only after 1990", "country only", "soul"], "rock and roll", 1),
  q("The Beatles were from…", ["Liverpool", "London", "Manchester", "Dublin"], "Liverpool", 1),
  q("Michael Jackson was often called the king of…", ["pop", "rock and roll", "country", "punk"], "pop", 1),
  q("Mickey Mouse is a character from…", ["Disney", "Warner Bros", "Nickelodeon", "Pixar"], "Disney", 1),
  q("Bruce Wayne is the civilian name of…", ["Batman", "Superman", "Spider-Man", "Iron Man"], "Batman", 1),
  q("Peter Parker is the civilian name of…", ["Spider-Man", "Batman", "Superman", "Wolverine"], "Spider-Man", 1),
  q("The Simpsons live in a town called…", ["Springfield", "Quahog", "South Park", "Bikini Bottom"], "Springfield", 1),
  q("SpongeBob SquarePants lives in…", ["Bikini Bottom", "Springfield", "Bedrock", "Atlantis, Florida"], "Bikini Bottom", 1),
  q("A sitcom is a…", ["situation comedy", "late-night news desk", "concert film", "sports highlight"], "situation comedy", 1),
  q("Marilyn Monroe was famous as a…", ["movie star", "news anchor", "opera composer", "silent-film director only"], "movie star", 1),
  q("Charlie Chaplin was a star of…", ["silent film", "television sitcoms", "radio sports", "music videos"], "silent film", 1),
  q("The four Beatles were John, Paul, George, and…", ["Ringo", "Brian", "Mick", "Pete"], "Ringo", 1),
  q("Han Solo and Indiana Jones were both played by…", ["Harrison Ford", "Mark Hamill", "Tom Hanks", "Sean Connery"], "Harrison Ford", 1),
  q("Princess Leia in Star Wars was played by…", ["Carrie Fisher", "Natalie Portman", "Sigourney Weaver", "Linda Hamilton"], "Carrie Fisher", 1),
  q("Rocky Balboa was played by…", ["Sylvester Stallone", "Arnold Schwarzenegger", "Bruce Willis", "Carl Weathers"], "Sylvester Stallone", 1),
  q("The Terminator made a movie star of…", ["Arnold Schwarzenegger", "Sylvester Stallone", "Jean-Claude Van Damme", "Dolph Lundgren"], "Arnold Schwarzenegger", 1),
  q("Aretha Franklin was called the queen of…", ["soul", "country", "punk", "disco only"], "soul", 1),
  q("Oprah Winfrey became famous as a…", ["talk-show host", "film director only", "pop singer", "news cartoonist"], "talk-show host", 1),
  q("The first Bond film, Dr. No, starred…", ["Sean Connery", "Roger Moore", "Pierce Brosnan", "Daniel Craig"], "Sean Connery", 2),
  q("Dr. No, the first James Bond film, came out in…", ["1962", "1954", "1973", "1985"], "1962", 2),
  q("The Beatles appeared on The Ed Sullivan Show in…", ["1964", "1960", "1969", "1972"], "1964", 2),
  q("Michael Jackson's album Thriller was released in…", ["1982", "1979", "1987", "1975"], "1982", 2),
  q("MTV's first video, in 1981, was…", ["Video Killed the Radio Star", "Thriller", "Billie Jean", "Like a Virgin"], "Video Killed the Radio Star", 2),
  q("Woodstock, the famous music festival, was in…", ["1969", "1967", "1975", "1979"], "1969", 2),
  q("Lady Gaga's given name is…", ["Stefani Germanotta", "Alecia Moore", "Robyn Fenty", "Onika Maraj"], "Stefani Germanotta", 2),
  q("Eminem's given name is…", ["Marshall Mathers", "Shawn Carter", "Andre Young", "Calvin Broadus"], "Marshall Mathers", 2),
  q("Rihanna was born in…", ["Barbados", "Jamaica", "Trinidad", "Puerto Rico"], "Barbados", 2),
  q("Beyoncé rose to fame in the group…", ["Destiny's Child", "TLC", "En Vogue", "The Supremes"], "Destiny's Child", 2),
  q("Freddie Mercury was the lead singer of…", ["Queen", "The Who", "Led Zeppelin", "The Rolling Stones"], "Queen", 2),
  q("David Bowie's alien stage persona was…", ["Ziggy Stardust", "The Thin White Duke only as a real name", "Aladdin Sane as his birth name", "Major Tom"], "Ziggy Stardust", 2),
  q("The Godfather was directed by…", ["Francis Ford Coppola", "Martin Scorsese", "Steven Spielberg", "Alfred Hitchcock"], "Francis Ford Coppola", 2),
  q("Star Wars was created by…", ["George Lucas", "Steven Spielberg", "James Cameron", "Ridley Scott"], "George Lucas", 2),
  q("Titanic and Avatar were both directed by…", ["James Cameron", "George Lucas", "Peter Jackson", "Christopher Nolan"], "James Cameron", 2),
  q("The Lord of the Rings films were directed by…", ["Peter Jackson", "James Cameron", "George Lucas", "Guillermo del Toro"], "Peter Jackson", 2),
  q("Ian McKellen played both Gandalf and…", ["Magneto", "Dumbledore", "Saruman", "Professor X"], "Magneto", 2),
  q("Hugh Jackman is best known on screen as…", ["Wolverine", "Batman", "Superman", "Iron Man"], "Wolverine", 2),
  q("Robert Downey Jr. played Marvel's…", ["Iron Man", "Captain America", "Thor", "Hulk"], "Iron Man", 2),
  q("Breaking Bad's Walter White was played by…", ["Bryan Cranston", "Aaron Paul", "Bob Odenkirk", "Jon Hamm"], "Bryan Cranston", 2),
  q("The Sopranos star James Gandolfini played…", ["Tony Soprano", "Walter White", "Don Draper", "Stringer Bell"], "Tony Soprano", 2),
  q("Dolly Parton is a star of…", ["country music", "opera", "hip-hop", "punk"], "country music", 2),
  q("Prince's 1984 album and film is titled…", ["Purple Rain", "Thriller", "Born in the U.S.A.", "Like a Virgin"], "Purple Rain", 2),
  q("The first Academy Awards ceremony was held in…", ["1929", "1939", "1915", "1948"], "1929", 3),
  q("Wings won the first Academy Award for Outstanding Picture for films of…", ["1927–28", "1939", "1915", "1942"], "1927–28", 3),
  q("Hattie McDaniel, the first Black performer to win an Oscar, was in…", ["Gone with the Wind", "Casablanca", "The Wizard of Oz", "Citizen Kane"], "Gone with the Wind", 3),
  q("Sidney Poitier won Best Actor for…", ["Lilies of the Field", "In the Heat of the Night", "Guess Who's Coming to Dinner", "A Raisin in the Sun"], "Lilies of the Field", 3),
  q("Katharine Hepburn won how many Academy Awards for Best Actress?", ["4", "2", "3", "5"], "4", 3),
  q("Daniel Day-Lewis has won Best Actor how many times?", ["3", "1", "2", "4"], "3", 3),
  q("Marilyn Monroe's birth name was…", ["Norma Jeane Mortenson", "Norma Jean Baker", "Marilyn Baker", "Jean Harlow"], "Norma Jeane Mortenson", 3),
  q("Cary Grant was born with the name…", ["Archibald Alec Leach", "Archibald Cary Grant", "Alec Cary Leach", "Bernard Schwartz"], "Archibald Alec Leach", 3),
  q("Casablanca premiered in…", ["1942", "1939", "1946", "1951"], "1942", 3),
  q("The line \"Here's looking at you, kid\" is from…", ["Casablanca", "Gone with the Wind", "Citizen Kane", "The Maltese Falcon"], "Casablanca", 3),
  q("Citizen Kane was directed by…", ["Orson Welles", "Alfred Hitchcock", "John Ford", "Howard Hawks"], "Orson Welles", 3),
  q("Judy Garland starred as Dorothy in The Wizard of Oz in…", ["1939", "1933", "1946", "1929"], "1939", 3),
  q("Parasite, the first non-English Best Picture winner, was directed by…", ["Bong Joon-ho", "Park Chan-wook", "Hirokazu Kore-eda", "Ang Lee"], "Bong Joon-ho", 3),
  q("The Hollywood Walk of Fame began in…", ["1960", "1950", "1970", "1940"], "1960", 3),
  q("Rita Moreno is one of the few performers to have won an…", ["EGOT", "Olympic medal and an Oscar", "Oscar before age 10", "Emmy for a silent film"], "EGOT", 3),
  q("The Buggles' \"Video Killed the Radio Star\" was the first video played on…", ["MTV", "VH1", "BBC One", "American Bandstand"], "MTV", 3),
  q("Live Aid, the 1985 benefit concerts, was organized by Bob Geldof and…", ["Midge Ure", "Bono", "Freddie Mercury", "George Harrison"], "Midge Ure", 3),
  // v0.0.28: +celebrity trivia cards (stable career facts only)
  q("Jack Sparrow in Pirates of the Caribbean was played by…", ["Johnny Depp", "Orlando Bloom", "Brad Pitt", "Jude Law"], "Johnny Depp", 1),
  q("Forrest Gump was played on screen by…", ["Tom Hanks", "Tom Cruise", "Kevin Costner", "Bill Murray"], "Tom Hanks", 1),
  q("Hermione Granger in the Harry Potter films was played by…", ["Emma Watson", "Emma Stone", "Keira Knightley", "Kristen Stewart"], "Emma Watson", 1),
  q("The boy wizard in the Harry Potter film series was played by…", ["Daniel Radcliffe", "Rupert Grint", "Elijah Wood", "Tom Felton"], "Daniel Radcliffe", 1),
  q("Frodo Baggins in The Lord of the Rings films was played by…", ["Elijah Wood", "Sean Astin", "Daniel Radcliffe", "Orlando Bloom"], "Elijah Wood", 1),
  q("Neo in The Matrix was played by…", ["Keanu Reeves", "Brad Pitt", "Will Smith", "Tom Cruise"], "Keanu Reeves", 1),
  q("Ethan Hunt in the Mission: Impossible films is played by…", ["Tom Cruise", "Matt Damon", "Brad Pitt", "Ben Affleck"], "Tom Cruise", 1),
  q("Jason Bourne in the 2002 film The Bourne Identity was played by…", ["Matt Damon", "Ben Affleck", "Mark Wahlberg", "Chris Pine"], "Matt Damon", 1),
  q("T'Challa in the 2018 film Black Panther was played by…", ["Chadwick Boseman", "Michael B. Jordan", "Idris Elba", "John Boyega"], "Chadwick Boseman", 1),
  q("Thor in the Marvel films is played by…", ["Chris Hemsworth", "Chris Evans", "Chris Pratt", "Chris Pine"], "Chris Hemsworth", 1),
  q("Diana Prince in the 2017 Wonder Woman film was played by…", ["Gal Gadot", "Margot Robbie", "Zoe Saldaña", "Brie Larson"], "Gal Gadot", 1),
  q("Katniss Everdeen in The Hunger Games films was played by…", ["Jennifer Lawrence", "Shailene Woodley", "Emma Stone", "Kristen Stewart"], "Jennifer Lawrence", 1),
  q("Rose in James Cameron's Titanic was played by…", ["Kate Winslet", "Kate Hudson", "Gwyneth Paltrow", "Claire Danes"], "Kate Winslet", 1),
  q("Mrs. Doubtfire and Good Will Hunting both starred…", ["Robin Williams", "Steve Martin", "Jim Carrey", "Billy Crystal"], "Robin Williams", 1),
  q("The Mask and Ace Ventura: Pet Detective both starred…", ["Jim Carrey", "Mike Myers", "Adam Sandler", "Eddie Murphy"], "Jim Carrey", 1),
  q("The ogre Shrek is voiced in English by…", ["Mike Myers", "Eddie Murphy", "Jim Carrey", "Adam Sandler"], "Mike Myers", 1),
  q("Woody the cowboy in Toy Story is voiced by…", ["Tom Hanks", "Tim Allen", "Billy Crystal", "Robin Williams"], "Tom Hanks", 1),
  q("Buzz Lightyear in the original Toy Story films was voiced by…", ["Tim Allen", "Tom Hanks", "Billy Crystal", "Jim Carrey"], "Tim Allen", 1),
  q("The Genie in the 1992 animated Aladdin was voiced by…", ["Robin Williams", "Eddie Murphy", "Jim Carrey", "Steve Martin"], "Robin Williams", 1),
  q("Taylor Swift began her recording career in which genre?", ["country", "heavy metal", "jazz", "reggae"], "country", 1),
  q("Bob Marley is the most famous star of…", ["reggae", "country", "punk rock", "opera"], "reggae", 1),
  q("Elton John usually performs seated at a…", ["piano", "drum kit", "harp", "cello"], "piano", 1),
  q("Mick Jagger is the lead singer of…", ["the Rolling Stones", "the Who", "Led Zeppelin", "the Kinks"], "the Rolling Stones", 1),
  q("Bono is the lead singer of the Irish band…", ["U2", "Coldplay", "Muse", "Oasis"], "U2", 1),
  q("Kurt Cobain was the frontman of…", ["Nirvana", "Pearl Jam", "Soundgarden", "Green Day"], "Nirvana", 1),
  q("Mr. Bean, the nearly silent comic character, was played by…", ["Rowan Atkinson", "Hugh Laurie", "John Cleese", "Stephen Fry"], "Rowan Atkinson", 1),
  q("Michael Scott in the U.S. version of The Office was played by…", ["Steve Carell", "Will Ferrell", "Paul Rudd", "John Krasinski"], "Steve Carell", 1),
  q("Ross, Rachel, and Monica are characters on the sitcom…", ["Friends", "Seinfeld", "Frasier", "Cheers"], "Friends", 1),
  q("Sheldon Cooper is a physicist on the sitcom…", ["The Big Bang Theory", "Modern Family", "How I Met Your Mother", "Two and a Half Men"], "The Big Bang Theory", 1),
  q("Will Smith first became a TV star on…", ["The Fresh Prince of Bel-Air", "Family Matters", "Saved by the Bell", "Full House"], "The Fresh Prince of Bel-Air", 1),
  q("Dwayne Johnson is widely known by the nickname…", ["The Rock", "The Stone", "The Brick", "The Boulder"], "The Rock", 1),
  q("Before acting, Dwayne Johnson was famous as a…", ["pro wrestler", "race car driver", "boxer", "chef"], "pro wrestler", 1),
  q("Stan Lee is best known for co-creating characters for…", ["Marvel Comics", "DC Comics", "Image Comics", "Dark Horse"], "Marvel Comics", 1),
  q("Jim Henson created…", ["the Muppets", "the Smurfs", "the Flintstones", "the Jetsons"], "the Muppets", 1),
  q("Alfred Hitchcock was known as the master of…", ["suspense", "slapstick", "musicals", "westerns"], "suspense", 1),
  q("Adele, the Hello singer, is from…", ["England", "Ireland", "Australia", "Canada"], "England", 1),
  q("Justin Bieber was born in…", ["Canada", "Australia", "Ireland", "England"], "Canada", 1),
  q("Shakira, the Hips Don't Lie singer, is from…", ["Colombia", "Mexico", "Spain", "Argentina"], "Colombia", 1),
  q("ABBA, the Dancing Queen pop group, came from…", ["Sweden", "Norway", "Denmark", "Finland"], "Sweden", 1),
  q("Celine Dion sang My Heart Will Go On for the film…", ["Titanic", "The Bodyguard", "Ghost", "Armageddon"], "Titanic", 1),
  q("In Frozen, Idina Menzel sings Let It Go as…", ["Elsa", "Anna", "Moana", "Rapunzel"], "Elsa", 1),
  q("Bruce Lee was a star of…", ["martial arts films", "westerns", "musicals", "horror films"], "martial arts films", 1),
  q("Jackie Chan is famous for performing his own…", ["stunts", "music", "makeup", "scripts"], "stunts", 1),
  q("Po in Kung Fu Panda is voiced by…", ["Jack Black", "Seth Rogen", "Jonah Hill", "Ben Stiller"], "Jack Black", 1),
  q("Bob Ross became famous on TV for teaching…", ["painting", "cooking", "gardening", "woodworking"], "painting", 1),
  q("Steve Irwin was famous as the…", ["Crocodile Hunter", "Shark Whisperer", "Snake Charmer", "Bear Tracker"], "Crocodile Hunter", 1),
  q("Harry Houdini was famous as an…", ["escape artist", "opera singer", "aviator", "acrobat"], "escape artist", 1),
  q("Lucille Ball starred in the classic sitcom…", ["I Love Lucy", "The Honeymooners", "Bewitched", "Gilligan's Island"], "I Love Lucy", 1),
  q("The Jackson 5 featured a young…", ["Michael Jackson", "Prince", "Stevie Wonder", "Lionel Richie"], "Michael Jackson", 1),
  q("Elvis Presley's Memphis mansion is called…", ["Graceland", "Neverland", "Paisley Park", "Xanadu"], "Graceland", 1),
  q("Michael Jackson's signature backward-gliding dance move is the…", ["moonwalk", "twist", "robot", "floss"], "moonwalk", 1),
  q("Madonna is often called the queen of…", ["pop", "soul", "country", "jazz"], "pop", 1),
  q("Bruce Springsteen is nicknamed…", ["The Boss", "The King", "The Chief", "The Duke"], "The Boss", 1),
  q("Ringo Starr played which role in the Beatles?", ["drummer", "bassist", "keyboardist", "lead guitarist"], "drummer", 1),
  q("Audrey Hepburn starred in Breakfast at…", ["Tiffany's", "Cartier's", "Macy's", "Harrods"], "Tiffany's", 1),
  q("Marlon Brando played Vito Corleone in…", ["The Godfather", "Scarface", "Goodfellas", "The Untouchables"], "The Godfather", 1),
  q("Charlie Chaplin's famous bowler-hatted character was…", ["the Tramp", "the Clown", "the Sheik", "the Drifter"], "the Tramp", 1),
  q("Shirley Temple was famous in the 1930s as a child…", ["actress", "chess champion", "senator", "pilot"], "actress", 1),
  q("Julie Andrews played Maria in…", ["The Sound of Music", "Mary Poppins", "My Fair Lady", "The King and I"], "The Sound of Music", 1),
  q("The Beach Boys are famous for songs about…", ["surfing", "trains", "farming", "outer space"], "surfing", 1),
  q("Johnny Cash was known as the Man in…", ["Black", "White", "Blue", "Red"], "Black", 1),
  q("Yo-Yo Ma is a world-famous…", ["cellist", "pianist", "violinist", "harpist"], "cellist", 1),
  q("Luciano Pavarotti was a famous…", ["opera tenor", "jazz drummer", "film director", "ballet dancer"], "opera tenor", 1),
  q("Keanu Reeves's character John Wick is a retired…", ["hitman", "boxer", "pilot", "cop"], "hitman", 1),
  q("Bruce Willis played John McClane in…", ["Die Hard", "Lethal Weapon", "Speed", "Cliffhanger"], "Die Hard", 1),
  q("Marty McFly in Back to the Future was played by…", ["Michael J. Fox", "Matthew Broderick", "Tom Cruise", "Rob Lowe"], "Michael J. Fox", 1),
  q("Basil Fawlty in Fawlty Towers was played by…", ["John Cleese", "Eric Idle", "Michael Palin", "Rowan Atkinson"], "John Cleese", 2),
  q("Dr. Gregory House on the medical drama House was played by…", ["Hugh Laurie", "Hugh Grant", "Colin Firth", "Jude Law"], "Hugh Laurie", 2),
  q("Mickey Mouse was co-created by Walt Disney and…", ["Ub Iwerks", "Chuck Jones", "Max Fleischer", "Tex Avery"], "Ub Iwerks", 3),
  q("Matt Groening created…", ["The Simpsons", "Family Guy", "South Park", "King of the Hill"], "The Simpsons", 2),
  q("Christopher Nolan directed Inception and…", ["Interstellar", "Avatar", "Gravity", "Arrival"], "Interstellar", 2),
  q("U2 formed in the city of…", ["Dublin", "Belfast", "Glasgow", "Liverpool"], "Dublin", 2),
  q("Whitney Houston's I Will Always Love You was on the soundtrack of…", ["The Bodyguard", "Titanic", "Ghost", "Dirty Dancing"], "The Bodyguard", 2),
  q("Pat Sajak was the longtime host of…", ["Wheel of Fortune", "The Price Is Right", "Family Feud", "Match Game"], "Wheel of Fortune", 2),
  q("Julia Child taught American TV audiences to cook…", ["French food", "Italian food", "Chinese food", "Mexican food"], "French food", 2),
  q("Johnny Carson spent three decades hosting…", ["The Tonight Show", "Late Night", "The Today Show", "Saturday Night Live"], "The Tonight Show", 2),
  q("Frank Sinatra was nicknamed Ol'…", ["Blue Eyes", "Green Eyes", "Brown Eyes", "Gray Eyes"], "Blue Eyes", 2),
  q("John Wayne was nicknamed…", ["the Duke", "the Boss", "the King", "the Kid"], "the Duke", 2),
  q("Frank Sinatra, Dean Martin, and Sammy Davis Jr. were part of the…", ["Rat Pack", "Brat Pack", "Wolf Pack", "Jet Set"], "Rat Pack", 2),
  q("Paul McCartney mainly played which instrument in the Beatles?", ["bass guitar", "drums", "saxophone", "harmonica"], "bass guitar", 2),
  q("Andrew Lloyd Webber composed the musical…", ["Cats", "Hamilton", "Rent", "Chicago"], "Cats", 2),
  q("John Williams composed the music for…", ["Star Wars", "The Godfather", "Titanic", "Gladiator"], "Star Wars", 2),
  q("Hans Zimmer composed the score for the 1994 animated…", ["The Lion King", "Aladdin", "Pocahontas", "Mulan"], "The Lion King", 2),
  q("Scarlett O'Hara in Gone with the Wind was played by…", ["Vivien Leigh", "Olivia de Havilland", "Bette Davis", "Joan Crawford"], "Vivien Leigh", 2),
  q("Rhett Butler in Gone with the Wind was played by…", ["Clark Gable", "Cary Grant", "Errol Flynn", "Gary Cooper"], "Clark Gable", 2),
  q("James Dean starred in Rebel Without a…", ["Cause", "Clue", "Name", "Home"], "Cause", 2),
  q("In Scarface (1983), Al Pacino played…", ["Tony Montana", "Travis Bickle", "Frank Lucas", "Henry Hill"], "Tony Montana", 2),
  q("Robert De Niro's character in Taxi Driver is…", ["Travis Bickle", "Tony Montana", "Jake LaMotta", "Henry Hill"], "Travis Bickle", 3),
  q("Darth Vader's deep voice was provided by…", ["James Earl Jones", "Morgan Freeman", "Danny Glover", "Laurence Fishburne"], "James Earl Jones", 2),
  q("Morgan Freeman narrated the documentary March of the…", ["Penguins", "Elephants", "Wolves", "Monarchs"], "Penguins", 2),
  q("Gollum in The Lord of the Rings films was performed by…", ["Andy Serkis", "Elijah Wood", "Sean Astin", "Ian Holm"], "Andy Serkis", 2),
  q("Heath Ledger won a posthumous Oscar for playing…", ["the Joker", "Batman", "Two-Face", "the Riddler"], "the Joker", 2),
  q("Meryl Streep played Margaret Thatcher in…", ["The Iron Lady", "The Queen", "The Crown", "Victoria"], "The Iron Lady", 2),
  q("Helen Mirren won Best Actress for playing Queen…", ["Elizabeth II", "Victoria", "Anne", "Mary I"], "Elizabeth II", 2),
  q("Tom Hanks won back-to-back Best Actor Oscars for Philadelphia and…", ["Forrest Gump", "Cast Away", "Big", "Saving Private Ryan"], "Forrest Gump", 2),
  q("Leonardo DiCaprio won his first Best Actor Oscar for…", ["The Revenant", "Titanic", "Inception", "The Aviator"], "The Revenant", 2),
  q("Fred Astaire often danced on film with…", ["Ginger Rogers", "Judy Garland", "Doris Day", "Grace Kelly"], "Ginger Rogers", 2),
  q("Grace Kelly left Hollywood to become princess of…", ["Monaco", "Luxembourg", "Liechtenstein", "Andorra"], "Monaco", 2),
  q("Gene Kelly danced through a downpour in…", ["Singin' in the Rain", "An American in Paris", "On the Town", "Top Hat"], "Singin' in the Rain", 2),
  q("Mary Poppins (1964) starred Julie Andrews and…", ["Dick Van Dyke", "Gene Kelly", "Danny Kaye", "Bob Hope"], "Dick Van Dyke", 2),
  q("Bob Hope was famous for decades of USO shows entertaining…", ["American troops", "prison inmates", "royal families", "astronauts"], "American troops", 2),
  q("Bob Dylan was awarded the 2016 Nobel Prize in…", ["Literature", "Peace", "Physics", "Economics"], "Literature", 2),
  q("The Rolling Stones' famous logo shows…", ["lips and a tongue", "a lightning bolt", "a burning heart", "a skull and roses"], "lips and a tongue", 2),
  q("The hard rock band AC/DC formed in…", ["Australia", "Canada", "Scotland", "New Zealand"], "Australia", 2),
  q("Ozzy Osbourne was the original singer of…", ["Black Sabbath", "Iron Maiden", "Judas Priest", "Deep Purple"], "Black Sabbath", 2),
  q("Hayao Miyazaki co-founded the animation studio…", ["Studio Ghibli", "Toei Animation", "Pixar", "Madhouse"], "Studio Ghibli", 2),
  q("Shah Rukh Khan is a film superstar from…", ["India", "Pakistan", "Bangladesh", "Sri Lanka"], "India", 2),
  q("Édith Piaf, the La Vie en rose singer, was from…", ["France", "Belgium", "Italy", "Canada"], "France", 2),
  q("Sean Connery was born in…", ["Scotland", "Ireland", "Wales", "England"], "Scotland", 2),
  q("Anthony Hopkins was born in…", ["Wales", "Scotland", "Ireland", "England"], "Wales", 2),
  q("Hannibal Lecter in The Silence of the Lambs was played by…", ["Anthony Hopkins", "Jack Nicholson", "Gary Oldman", "Ralph Fiennes"], "Anthony Hopkins", 2),
  q("Jack Nicholson growls Here's Johnny! through a broken door in…", ["The Shining", "Batman", "Chinatown", "Misery"], "The Shining", 2),
  q("Mel Brooks directed the western spoof…", ["Blazing Saddles", "Animal House", "Stripes", "Caddyshack"], "Blazing Saddles", 2),
  q("Groucho, Harpo, and Chico were the…", ["Marx Brothers", "Warner Brothers", "Ringling Brothers", "Wright Brothers"], "Marx Brothers", 2),
  q("The Three Stooges included Moe, Larry, and…", ["Curly", "Shorty", "Chuck", "Ernie"], "Curly", 2),
  q("Henry Winkler played the Fonz on…", ["Happy Days", "Laverne & Shirley", "The Brady Bunch", "Taxi"], "Happy Days", 2),
  q("The party game Six Degrees is famously tied to actor…", ["Kevin Bacon", "Kevin Costner", "Kevin Hart", "Kevin Kline"], "Kevin Bacon", 2),
  q("Julia Roberts played Vivian Ward in…", ["Pretty Woman", "Notting Hill", "Erin Brockovich", "Runaway Bride"], "Pretty Woman", 2),
  q("Ghostbusters (1984) starred Bill Murray and…", ["Dan Aykroyd", "Chevy Chase", "John Candy", "Steve Martin"], "Dan Aykroyd", 2),
  q("Buster Keaton was nicknamed The Great…", ["Stone Face", "Pratfall", "Mimic", "Clown"], "Stone Face", 3),
  q("Abbott and Costello's famous baseball routine is…", ["Who's on First", "What's Up Next", "Where's the Ball", "Why Not Third"], "Who's on First", 3),
  q("Halle Berry became the first Black woman to win Best Actress for…", ["Monster's Ball", "Catwoman", "Swordfish", "Gothika"], "Monster's Ball", 3),
  q("Denzel Washington won Best Actor for…", ["Training Day", "Glory", "Malcolm X", "Philadelphia"], "Training Day", 3),
  q("Whoopi Goldberg won her Oscar for the film…", ["Ghost", "Sister Act", "The Color Purple", "Corrina, Corrina"], "Ghost", 3),
  q("Bob Dylan was born Robert…", ["Zimmerman", "Dillon", "Bernstein", "Zimmer"], "Zimmerman", 3),
  q("Elton John was born Reginald…", ["Dwight", "Davies", "Watts", "Mercury"], "Dwight", 3),
  q("Freddie Mercury was born on the island of…", ["Zanzibar", "Madagascar", "Mauritius", "Sri Lanka"], "Zanzibar", 3),
  q("John Wayne's birth name was…", ["Marion Morrison", "Wayne Morrison", "John Marion", "Morris Wayne"], "Marion Morrison", 3),
  q("Alfred Hitchcock's only Best Picture winner was…", ["Rebecca", "Psycho", "Vertigo", "Rear Window"], "Rebecca", 3),
  q("Orson Welles's famous 1938 radio broadcast adapted…", ["The War of the Worlds", "The Time Machine", "Dracula", "Frankenstein"], "The War of the Worlds", 3),
  q("The Beatles' manager through most of the 1960s was…", ["Brian Epstein", "George Martin", "Allen Klein", "Pete Best"], "Brian Epstein", 3),
  q("Johnny Cash recorded famous live albums at Folsom and…", ["San Quentin", "Alcatraz", "Sing Sing", "Leavenworth"], "San Quentin", 3),
  q("Before his acting breakthrough, Harrison Ford worked as a…", ["carpenter", "mail carrier", "bartender", "lifeguard"], "carpenter", 3),
  q("Satyajit Ray was a celebrated filmmaker from…", ["India", "Japan", "Iran", "Egypt"], "India", 3),
  q("Marlene Dietrich was born in…", ["Germany", "Austria", "Sweden", "Hungary"], "Germany", 3),
  q("Greta Garbo was born in…", ["Sweden", "Norway", "Germany", "Denmark"], "Sweden", 3),
  q("Kelsey Grammer's Frasier Crane first appeared on…", ["Cheers", "Wings", "Seinfeld", "Taxi"], "Cheers", 3),
  q("Alan Alda played Hawkeye Pierce on…", ["M*A*S*H", "Taxi", "Barney Miller", "Cheers"], "M*A*S*H", 3),
  q("Carroll O'Connor played Archie Bunker on…", ["All in the Family", "The Jeffersons", "Sanford and Son", "Good Times"], "All in the Family", 3),
  q("Steve Martin is also an accomplished player of the…", ["banjo", "harp", "oboe", "tuba"], "banjo", 3),
];
