import { q } from "../quiz";
import type { CityId, TriviaCat, TriviaQ } from "../types";

/**
 * Local trivia cards, batch 4 (v0.0.48 / k48a): Seattle, Denver and Nashville, the three new cities.
 * Every fact was checked against the source listed for it in docs/trivia-sources-cities-0.0.48.md.
 * Easy cards are difficulty 1 so they band white/blue; city cards above that step up one tier.
 * Merged into CITY_EXTRA by cities.ts (rarity stamped there with the city nudge).
 */
export const CITY_EXTRA_PART_G: Partial<Record<CityId, Partial<Record<TriviaCat, TriviaQ[]>>>> = {
  seattle: {
    local: [
      q("How tall is the Space Needle?", ["605 feet", "455 feet", "725 feet", "1,020 feet"], "605 feet", 2),
      q("The Space Needle's design was a compromise between Edward E. Carlson and…", ["John Graham", "Minoru Yamasaki", "Paul Thiry", "Rem Koolhaas"], "John Graham", 3),
      q("Seattle's best-known nickname is the…", ["Emerald City", "Rose City", "Mile High City", "Magic City"], "Emerald City", 1),
      q("Seattle lies between Puget Sound and which lake to its east?", ["Lake Washington", "Lake Chelan", "Lake Sammamish", "Lake Crescent"], "Lake Washington", 1),
      q("Seattle is the county seat of…", ["King County", "Pierce County", "Snohomish County", "Kitsap County"], "King County", 1),
      q("Seattle's King County now officially honors…", ["Dr. Martin Luther King", "William Rufus DeVane King", "Rodney King", "Coretta Scott King"], "Dr. Martin Luther King", 2),
      q("King County was first named in 1852 for vice president-elect…", ["William R. King", "John C. Calhoun", "George M. Dallas", "Richard M. Johnson"], "William R. King", 2),
      q("Seattle takes its name from…", ["Chief Seattle", "Arthur Denny", "Henry Yesler", "Doc Maynard"], "Chief Seattle", 1),
      q("Chief Seattle was a leader of the Duwamish and the…", ["Suquamish", "Makah", "Yakama", "Spokane"], "Suquamish", 2),
      q("The Denny Party landed at Alki Point in…", ["1851", "1869", "1889", "1832"], "1851", 2),
      q("Seattle's founding settlers first built cabins at which point?", ["Alki Point", "Point Defiance", "Duwamish Head", "Magnolia Bluff"], "Alki Point", 2),
      q("The name of the first settlement, Alki, is Chinook Jargon for…", ["by and by", "big water", "new home", "fair wind"], "by and by", 3),
      q("Seattle's original 'Skid Road' is said to be today's…", ["Yesler Way", "Pike Street", "Denny Way", "Madison Street"], "Yesler Way", 2),
      q("Smith Tower in Pioneer Square opened in…", ["1914", "1902", "1929", "1936"], "1914", 2),
      q("Until 2016, Smith Tower's 35th-floor observatory was called the…", ["Chinese Room", "Crystal Room", "Sky Lounge", "Totem Room"], "Chinese Room", 3),
      q("How many stories is Columbia Center, Seattle's tallest building?", ["76", "58", "62", "101"], "76", 2),
      q("Columbia Center's public observation deck is the…", ["Sky View Observatory", "Space Needle Loupe", "Crow's Nest", "Summit Room"], "Sky View Observatory", 2),
      q("Seattle Central Library's glass-and-steel building opened in…", ["2004", "1996", "2010", "2015"], "2004", 2),
      q("King Street Station's clock tower was modeled on a campanile in which Italian city?", ["Venice", "Florence", "Pisa", "Siena"], "Venice", 2),
      q("King Street Station opened in…", ["1906", "1889", "1923", "1911"], "1906", 2),
      q("Seattle's Union Station was built for the Union Pacific and the…", ["Milwaukee Road", "Great Northern", "Northern Pacific", "Santa Fe"], "Milwaukee Road", 3),
      q("The Seattle Center Monorail runs between Seattle Center and…", ["Westlake Center", "Pike Place Market", "King Street Station", "the ferry terminal"], "Westlake Center", 1),
      q("At Pike Place Market's best-known fish stand, workers famously…", ["throw the fish", "sing the prices", "ring a brass bell", "race the carts"], "throw the fish", 1),
      q("Pike Place Market's bronze piggy bank mascot is named…", ["Rachel", "Penny", "Wilbur", "Daisy"], "Rachel", 2),
      q("The Gum Wall is in Post Alley beneath…", ["Pike Place Market", "Smith Tower", "the Space Needle", "Pioneer Square"], "Pike Place Market", 1),
      q("The Gum Wall was fully steam-cleaned for the first time in two decades in…", ["2015", "2005", "1999", "2021"], "2015", 3),
      q("The Gum Wall is beside the box office of which theater?", ["Market Theater", "Moore Theatre", "Paramount Theatre", "5th Avenue Theatre"], "Market Theater", 2),
      q("The Seattle Great Wheel stands at the end of which pier?", ["Pier 57", "Pier 66", "Pier 70", "Pier 91"], "Pier 57", 2),
      q("When it opened in 2012, the Seattle Great Wheel was the tallest Ferris wheel on the…", ["West Coast", "Gulf Coast", "Great Lakes", "East Coast"], "West Coast", 2),
      q("The Seattle Aquarium sits on which waterfront pier?", ["Pier 59", "Pier 57", "Pier 52", "Pier 69"], "Pier 59", 2),
      q("From Colman Dock, state ferries sail to Bainbridge Island and…", ["Bremerton", "Victoria", "Port Angeles", "Everett"], "Bremerton", 2),
      q("Pacific Science Center's white arches were designed by…", ["Minoru Yamasaki", "I. M. Pei", "Paul Thiry", "Eero Saarinen"], "Minoru Yamasaki", 2),
      q("Seattle's oldest park, given to the city by a pioneer in 1861 as a cemetery, is…", ["Denny Park", "Volunteer Park", "Kinnear Park", "Cal Anderson Park"], "Denny Park", 2),
      q("Freeway Park, built as a lid over Interstate 5, was designed by…", ["Lawrence Halprin", "Frederick Law Olmsted", "Dan Kiley", "Isamu Noguchi"], "Lawrence Halprin", 2),
      q("Freeway Park opened on which date in 1976?", ["July 4", "Labor Day", "Memorial Day", "Thanksgiving"], "July 4", 3),
      q("Occidental Park sits in which historic neighborhood?", ["Pioneer Square", "Belltown", "Capitol Hill", "Fremont"], "Pioneer Square", 1),
      q("Hing Hay Park is in Seattle's…", ["International District", "University District", "Central District", "Rainier Valley"], "International District", 1),
      q("Hing Hay Park's ornate pavilion came from…", ["Taipei", "Beijing", "Kobe", "Busan"], "Taipei", 3),
      q("The Arctic Building is ringed with terra-cotta heads of…", ["walruses", "bears", "eagles", "whales"], "walruses", 2),
      q("Seattle Center's International Fountain was first built for…", ["the 1962 World's Fair", "the 1990 Goodwill Games", "the 1909 exposition", "the city's centennial"], "the 1962 World's Fair", 2),
      q("The Seattle Center Armory was built in 1939 as a…", ["National Guard armory", "streetcar repair barn", "salmon cannery", "rail freight depot"], "National Guard armory", 2),
      q("The Fremont Troll crouches under which bridge?", ["Aurora Bridge", "Ballard Bridge", "Fremont Bridge", "University Bridge"], "Aurora Bridge", 2),
      q("The Fremont Troll clutches a real…", ["Volkswagen Beetle", "Ford Model T", "Harley-Davidson", "rowboat"], "Volkswagen Beetle", 2),
      q("The Ballard Locks are officially named for…", ["Hiram M. Chittenden", "Arthur Denny", "George Vancouver", "Henry Yesler"], "Hiram M. Chittenden", 2),
      q("Gas Works Park sits on the north shore of…", ["Lake Union", "Lake Washington", "Green Lake", "Elliott Bay"], "Lake Union", 1),
      q("Kerry Park's famous skyline view is from which hill?", ["Queen Anne Hill", "Capitol Hill", "Beacon Hill", "First Hill"], "Queen Anne Hill", 2),
      q("Like Rome, Seattle is said to be built on how many hills?", ["seven", "five", "nine", "twelve"], "seven", 2),
      q("Downtown Seattle's waterfront faces which bay?", ["Elliott Bay", "Commencement Bay", "Bellingham Bay", "Shilshole Bay"], "Elliott Bay", 1),
      q("The State Route 99 tunnel under downtown opened in…", ["2019", "2011", "2015", "2023"], "2019", 2),
      q("The machine that bored the SR 99 tunnel was nicknamed…", ["Bertha", "Big Ben", "Molly", "Rosie"], "Bertha", 2),
      q("The SR 99 tunnel replaced which double-decked waterfront highway?", ["Alaskan Way Viaduct", "Aurora Bridge", "Mercer Street Ramp", "Elliott Avenue Overpass"], "Alaskan Way Viaduct", 2),
      q("When completed in 1914, Smith Tower was among the tallest skyscrapers outside…", ["New York City", "Chicago", "Philadelphia", "Pittsburgh"], "New York City", 2),
      q("Seattle's summer festival with hydroplane races and the Blue Angels is…", ["Seafair", "Bumbershoot", "Folklife", "Hempfest"], "Seafair", 1),
      q("The Seattle Aquarium on the waterfront opened in…", ["1977", "1962", "1989", "1998"], "1977", 2),
    ],
    history: [
      q("Who ran the steam sawmill at the heart of early Seattle's waterfront?", ["Henry Yesler", "Arthur Denny", "Doc Maynard", "Thomas Mercer"], "Henry Yesler", 2),
      q("The Great Seattle Fire of 1889 began in a…", ["cabinet shop", "hotel kitchen", "saloon", "ship's hold"], "cabinet shop", 3),
      q("After the 1889 fire, streets were raised a story, burying old storefronts now toured as the…", ["Seattle Underground", "Klondike Vault", "Yesler Cellars", "Elliott Tunnel"], "Seattle Underground", 2),
      q("Bill Speidel's walking tour, begun in 1965, takes visitors…", ["below Pioneer Square", "up the Space Needle", "around Lake Union", "through the ferry docks"], "below Pioneer Square", 2),
      q("The steamer Portland's 1897 arrival with 'a ton of gold' set off which rush through Seattle?", ["Klondike Gold Rush", "California Gold Rush", "Pikes Peak Gold Rush", "Fraser Canyon Gold Rush"], "Klondike Gold Rush", 1),
      q("The Klondike gold fields that Seattle outfitted stampeders for were in…", ["Yukon", "Alaska", "Montana", "Idaho"], "Yukon", 1),
      q("The 1962 Seattle World's Fair was officially called the…", ["Century 21 Exposition", "Expo 62", "Pacific Exposition", "Space Age Fair"], "Century 21 Exposition", 2),
      q("Seattle hosted which world's fair in 1909?", ["Alaska–Yukon–Pacific Exposition", "Lewis and Clark Exposition", "Panama–Pacific Exposition", "Trans-Mississippi Exposition"], "Alaska–Yukon–Pacific Exposition", 3),
      q("Architect Victor Steinbrueck led a 1971 citizens' vote to save…", ["Pike Place Market", "Smith Tower", "the Moore Theatre", "Union Station"], "Pike Place Market", 2),
      q("Waterfall Garden Park was built at the original building of which company?", ["UPS", "Boeing", "Nordstrom", "Starbucks"], "UPS", 2),
      q("Wing Luke, namesake of the Wing Luke Museum, was elected to Seattle's…", ["city council", "state senate", "school board", "port commission"], "city council", 2),
      q("Seattle-based Amazon was founded in 1994 by…", ["Jeff Bezos", "Bill Gates", "Howard Schultz", "Paul Allen"], "Jeff Bezos", 1),
      q("Boeing was founded in Seattle in…", ["1916", "1903", "1927", "1934"], "1916", 2),
      q("In 1942, many Japanese Americans from Seattle were first held at 'Camp Harmony' in…", ["Puyallup", "Yakima", "Spokane", "Bellingham"], "Puyallup", 2),
      q("Seattle was incorporated as a city in…", ["1869", "1851", "1889", "1853"], "1869", 3),
    ],
    sports: [
      q("Climate Pledge Arena's naming rights belong to…", ["Amazon", "Microsoft", "Boeing", "Starbucks"], "Amazon", 1),
      q("In Super Bowl XLVIII, the Seahawks beat the…", ["Denver Broncos", "New England Patriots", "Pittsburgh Steelers", "Carolina Panthers"], "Denver Broncos", 1),
      q("Seahawks fans call themselves the…", ["12th Man", "Dawg Pound", "Black Hole", "Cheeseheads"], "12th Man", 1),
      q("Lumen Field, home of the Seahawks, opened in…", ["2002", "1995", "2008", "1976"], "2002", 2),
      q("The domed stadium that stood where Lumen Field is now was the…", ["Kingdome", "Astrodome", "Metrodome", "Silverdome"], "Kingdome", 1),
      q("Lumen Field fans set a Guinness crowd-noise record in 2013 of…", ["137.6 decibels", "118.2 decibels", "126.4 decibels", "142.2 decibels"], "137.6 decibels", 3),
      q("The Mariners' ballpark opened in 1999 under the name…", ["Safeco Field", "Kingdome Park", "Sicks' Stadium", "Mariner Field"], "Safeco Field", 1),
      q("T-Mobile Park sits in which Seattle neighborhood?", ["SoDo", "Belltown", "Ballard", "Fremont"], "SoDo", 2),
      q("Ken Griffey Jr. finished his career with how many home runs?", ["630", "600", "660", "714"], "630", 3),
      q("Ichiro Suzuki set the MLB single-season hits record in…", ["2004", "2001", "2007", "1998"], "2004", 3),
      q("The 2001 Mariners tied the MLB record for regular-season wins with…", ["116", "108", "112", "104"], "116", 3),
      q("Mariners Hall of Famer Edgar Martínez is best known as a…", ["designated hitter", "closing pitcher", "shortstop", "catcher"], "designated hitter", 1),
      q("The Seattle Sounders won MLS Cup in 2016 and again in…", ["2019", "2014", "2021", "2010"], "2019", 2),
      q("The Sounders became the first MLS club to win the CONCACAF Champions League in…", ["2022", "2016", "2019", "2024"], "2022", 2),
      q("The Seattle Kraken's first NHL season was…", ["2021–22", "2018–19", "2023–24", "2015–16"], "2021–22", 2),
      q("The Seattle Storm play in the…", ["WNBA", "NWSL", "NBA G League", "PWHL"], "WNBA", 1),
      q("The SuperSonics left Seattle in 2008 and became the…", ["Oklahoma City Thunder", "Memphis Grizzlies", "New Orleans Pelicans", "Sacramento Kings"], "Oklahoma City Thunder", 1),
      q("The SuperSonics won their only NBA championship in…", ["1979", "1972", "1996", "1984"], "1979", 2),
      q("Seattle's one-season MLB team of 1969 was the…", ["Pilots", "Rainiers", "Angels", "Indians"], "Pilots", 3),
      q("After one season, the Seattle Pilots moved and became the…", ["Milwaukee Brewers", "Texas Rangers", "Kansas City Royals", "San Diego Padres"], "Milwaukee Brewers", 2),
      q("Washington Huskies football is played at…", ["Husky Stadium", "Lumen Field", "Martin Stadium", "Autzen Stadium"], "Husky Stadium", 1),
      q("Seattle Reign FC plays in the…", ["NWSL", "WNBA", "MLS", "USL"], "NWSL", 1),
      q("In 1917 the Seattle Metropolitans became the first U.S. team to win the…", ["Stanley Cup", "World Series", "Grey Cup", "Davis Cup"], "Stanley Cup", 3),
    ],
    arts: [
      q("Seattle Central Library was designed by Rem Koolhaas and…", ["Joshua Prince-Ramus", "Diller Scofidio", "Herzog & de Meuron", "Bjarke Ingels"], "Joshua Prince-Ramus", 3),
      q("Olympic Sculpture Park is run by the…", ["Seattle Art Museum", "Frye Art Museum", "Henry Art Gallery", "Wing Luke Museum"], "Seattle Art Museum", 1),
      q("Olympic Sculpture Park opened in…", ["2007", "1998", "2012", "2001"], "2007", 2),
      q("Alexander Calder's red steel sculpture at Olympic Sculpture Park is…", ["Eagle", "Flamingo", "Red Sun", "Phoenix"], "Eagle", 2),
      q("The giant moving sculpture outside the Seattle Art Museum is…", ["Hammering Man", "Walking Man", "Waving Girl", "Running Fence"], "Hammering Man", 1),
      q("Hammering Man at the Seattle Art Museum is the work of…", ["Jonathan Borofsky", "Claes Oldenburg", "Richard Serra", "Henry Moore"], "Jonathan Borofsky", 2),
      q("Benaroya Hall is the home of the…", ["Seattle Symphony", "Seattle Opera", "Pacific NW Ballet", "Seattle Men's Chorus"], "Seattle Symphony", 1),
      q("Benaroya Hall opened in…", ["1998", "1987", "2004", "1962"], "1998", 2),
      q("The Museum of Pop Culture was founded by Microsoft co-founder…", ["Paul Allen", "Bill Gates", "Steve Ballmer", "Nathan Myhrvold"], "Paul Allen", 1),
      q("MoPOP opened in 2000 under what original name?", ["Experience Music Project", "Seattle Music Hall", "Science Fiction Museum", "Northwest Rock Museum"], "Experience Music Project", 2),
      q("Chihuly Garden and Glass opened at Seattle Center in…", ["2012", "2004", "1998", "2016"], "2012", 2),
      q("Glass artist Dale Chihuly was born in…", ["Tacoma", "Spokane", "Portland", "Olympia"], "Tacoma", 2),
      q("The Moore Theatre, opened in 1907, is Seattle's…", ["oldest active theater", "largest concert hall", "only opera house", "first movie palace"], "oldest active theater", 2),
      q("The 5th Avenue Theatre's interior was modeled on…", ["Beijing's Forbidden City", "the Paris Opera", "a Venetian palazzo", "an Egyptian temple"], "Beijing's Forbidden City", 2),
      q("The Paramount Theatre on Pine Street opened in…", ["1928", "1914", "1939", "1950"], "1928", 2),
      q("Seattle's Sub Pop label released which band's debut album, Bleach?", ["Nirvana", "Pearl Jam", "Soundgarden", "Alice in Chains"], "Nirvana", 2),
      q("Pearl Jam's 1991 debut album is titled…", ["Ten", "Backspacer", "Yield", "Vitalogy"], "Ten", 2),
      q("Soundgarden's lead singer was…", ["Chris Cornell", "Eddie Vedder", "Layne Staley", "Kurt Cobain"], "Chris Cornell", 1),
      q("Jimi Hendrix was born in Seattle in…", ["1942", "1938", "1947", "1951"], "1942", 2),
      q("Jimi Hendrix is buried in which city just south of Seattle?", ["Renton", "Bellevue", "Tacoma", "Everett"], "Renton", 3),
      q("Before Seattle, Kurt Cobain grew up in…", ["Aberdeen", "Tacoma", "Olympia", "Spokane"], "Aberdeen", 2),
      q("Alice in Chains singer Layne Staley was born in…", ["Bellevue", "Spokane", "Everett", "Yakima"], "Bellevue", 2),
      q("Quincy Jones went to which Seattle high school?", ["Garfield", "Roosevelt", "Franklin", "Ballard"], "Garfield", 2),
      q("Sir Mix-a-Lot's 1992 No. 1 hit was…", ["Baby Got Back", "Ice Ice Baby", "Jump Around", "Rump Shaker"], "Baby Got Back", 1),
      q("Macklemore's 2012 breakout hit with Ryan Lewis was…", ["Thrift Shop", "Hotline Bling", "Uptown Funk", "Royals"], "Thrift Shop", 1),
      q("Psychiatrist Frasier Crane hosts his radio show in…", ["Seattle", "Boston", "Portland", "Denver"], "Seattle", 1),
      q("The 1993 film Sleepless in Seattle starred Tom Hanks and…", ["Meg Ryan", "Julia Roberts", "Sandra Bullock", "Sally Field"], "Meg Ryan", 1),
      q("Bumbershoot, held every Labor Day weekend, is a festival of…", ["music and arts", "hydroplane racing", "silent film", "craft brewing"], "music and arts", 1),
      q("Seattle Opera performs at…", ["McCaw Hall", "Benaroya Hall", "the Moore Theatre", "the Paramount"], "McCaw Hall", 2),
      q("Pacific Northwest Ballet shares McCaw Hall with the…", ["Seattle Opera", "Seattle Symphony", "Seattle Rep", "5th Avenue Theatre"], "Seattle Opera", 2),
      q("Seattle Repertory Theatre performs at…", ["Seattle Center", "Pioneer Square", "Westlake Center", "Pike Place Market"], "Seattle Center", 2),
      q("Northwest Folklife Festival takes over Seattle Center every…", ["Memorial Day weekend", "Labor Day weekend", "Fourth of July", "Thanksgiving weekend"], "Memorial Day weekend", 2),
      q("The Seattle Art Museum's Asian art collection is shown in which park?", ["Volunteer Park", "Discovery Park", "Gas Works Park", "Denny Park"], "Volunteer Park", 2),
    ],
    food: [
      q("The first Starbucks was founded by Gordon Bowker, Jerry Baldwin and…", ["Zev Siegl", "Howard Schultz", "Dave Olsen", "Paul Allen"], "Zev Siegl", 3),
      q("Starbucks opened its first store in Seattle in…", ["1971", "1966", "1979", "1985"], "1971", 2),
      q("Starbucks takes its name from a character in…", ["Moby-Dick", "Treasure Island", "Peter Pan", "The Odyssey"], "Moby-Dick", 1),
      q("Uwajimaya's founder first sold goods from a truck in…", ["Tacoma", "Spokane", "Bellingham", "Yakima"], "Tacoma", 3),
      q("Dick's Drive-In opened its first stand in Wallingford in…", ["1954", "1962", "1948", "1971"], "1954", 2),
      q("A Seattle-style hot dog is topped with…", ["cream cheese", "peanut butter", "pineapple", "coleslaw"], "cream cheese", 1),
      q("Ivar's seafood restaurants were founded by folk singer…", ["Ivar Haglund", "Ivar Lindqvist", "Ole Bardahl", "Eddie Bauer"], "Ivar Haglund", 2),
      q("Beecher's Handmade Cheese makes its cheese in view of shoppers at…", ["Pike Place Market", "Westlake Center", "Pioneer Square", "Seattle Center"], "Pike Place Market", 2),
      q("A giant red letter atop the old Rainier brewery was the letter…", ["R", "S", "B", "W"], "R", 2),
      q("Top Pot Doughnuts got its name from a neon sign salvaged from a…", ["Chinese restaurant", "bowling alley", "gas station", "motel"], "Chinese restaurant", 2),
      q("Theo Chocolate, in Fremont, was the first U.S. maker of chocolate that was organic and…", ["Fair Trade", "kosher", "sugar-free", "dairy-free"], "Fair Trade", 2),
      q("Washington leads the United States in growing…", ["apples", "oranges", "peaches", "pecans"], "apples", 1),
    ],
    political: [
      q("Seattle's current City Hall opened in…", ["2003", "1994", "2009", "1978"], "2003", 2),
      q("Bertha Knight Landes, elected in 1926, was the first woman mayor of…", ["a major U.S. city", "a U.S. state", "the U.S. Senate", "a U.S. port"], "a major U.S. city", 2),
      q("The Seattle General Strike of 1919 lasted about…", ["five days", "three weeks", "one day", "two months"], "five days", 3),
      q("The 1999 protests in Seattle targeted a meeting of the…", ["WTO", "G8", "IMF", "NATO"], "WTO", 1),
      q("Seattle's City Council has how many members?", ["nine", "seven", "eleven", "fifteen"], "nine", 2),
      q("Washington's state capital is…", ["Olympia", "Tacoma", "Spokane", "Seattle"], "Olympia", 1),
      q("Who was Seattle's first elected African American mayor?", ["Norm Rice", "Greg Nickels", "Charles Royer", "Paul Schell"], "Norm Rice", 2),
      q("The Port of Seattle was created by a public vote in…", ["1911", "1889", "1934", "1950"], "1911", 3),
      q("Which Seattle daily went online-only in 2009?", ["the Post-Intelligencer", "the Seattle Times", "The Stranger", "Seattle Weekly"], "the Post-Intelligencer", 2),
      q("Washington became a U.S. state in…", ["1889", "1876", "1859", "1912"], "1889", 2),
    ],
    nature: [
      q("Mount Rainier, seen from Seattle on clear days, is a…", ["stratovolcano", "shield volcano", "granite dome", "glacial moraine"], "stratovolcano", 1),
      q("Mount Rainier rises to about…", ["14,410 feet", "12,280 feet", "10,780 feet", "16,050 feet"], "14,410 feet", 2),
      q("Puget Sound reaches the Pacific through the Strait of…", ["Juan de Fuca", "Georgia", "Magellan", "Belle Isle"], "Juan de Fuca", 1),
      q("Salmon get past the Ballard Locks by way of a…", ["fish ladder", "fish elevator", "fish wheel", "trap net"], "fish ladder", 1),
      q("The SR 520 bridge across Lake Washington is the world's longest…", ["floating bridge", "suspension bridge", "cable-stayed span", "covered bridge"], "floating bridge", 2),
      q("Discovery Park, Seattle's largest city park, sits on which peninsula neighborhood?", ["Magnolia", "Ballard", "West Seattle", "Rainier Beach"], "Magnolia", 2),
      q("Washington's state tree, seen across Seattle's parks, is the…", ["western hemlock", "Douglas fir", "Sitka spruce", "bigleaf maple"], "western hemlock", 2),
      q("The king salmon sold at Seattle's fish stalls is also called…", ["Chinook", "Coho", "Sockeye", "Chum"], "Chinook", 2),
      q("The geoducks sold at Pike Place Market are giant…", ["clams", "crabs", "oysters", "snails"], "clams", 1),
      q("The 2001 earthquake that damaged the Alaskan Way Viaduct is named for…", ["Nisqually", "Cascadia", "Olympia", "Tacoma"], "Nisqually", 2),
    ],
  },
};
