import { q } from "../quiz";
import type { CityId, TriviaCat, TriviaQ } from "../types";

/**
 * Local trivia card backlog, batch 1 (v0.0.26): Chicago, New York City, San Francisco.
 * Easy, checkable landmark / neighborhood / transit / history / food / team cards.
 * Merged into CITY_EXTRA by cities.ts (rarity stamped there with the city nudge).
 */
export const CITY_EXTRA_PART_D: Partial<Record<CityId, Partial<Record<TriviaCat, TriviaQ[]>>>> = {
  chicago: {
    local: [
      q("Chicago's best-known nickname is…", ["the Windy City", "the Big Apple", "the Emerald City", "the Mile High City"], "the Windy City", 1),
      q("Chicago's 'City of the Big Shoulders' line comes from a poem by…", ["Carl Sandburg", "Robert Frost", "Walt Whitman", "Langston Hughes"], "Carl Sandburg", 2),
      q("Legend blames the Great Chicago Fire on…", ["Mrs. O'Leary's cow", "a lightning strike", "a steamboat boiler", "a fireworks show"], "Mrs. O'Leary's cow", 1),
      q("Which Chicago landmark survived the Great Fire of 1871?", ["the Water Tower", "the Rookery", "the Wrigley Building", "Tribune Tower"], "the Water Tower", 1),
      q("The giant Picasso sculpture downtown stands in…", ["Daley Plaza", "Grant Park", "Pioneer Court", "Federal Plaza"], "Daley Plaza", 1),
      q("Alexander Calder's red 'Flamingo' stands in…", ["Federal Plaza", "Daley Plaza", "Millennium Park", "Navy Pier"], "Federal Plaza", 2),
      q("Buckingham Fountain is in…", ["Grant Park", "Lincoln Park", "Humboldt Park", "Jackson Park"], "Grant Park", 1),
      q("Millennium Park's Crown Fountain shows…", ["video faces of Chicagoans", "a giant floral clock", "jets from bronze lions", "a timed steam geyser"], "video faces of Chicagoans", 1),
      q("Jay Pritzker Pavilion in Millennium Park was designed by…", ["Frank Gehry", "I. M. Pei", "Zaha Hadid", "Renzo Piano"], "Frank Gehry", 2),
      q("The lions outside the Art Institute are made of…", ["bronze", "marble", "granite", "limestone"], "bronze", 1),
      q("Sue, the famous T. rex skeleton, is displayed at…", ["the Field Museum", "the Shedd Aquarium", "the Adler Planetarium", "the Art Institute"], "the Field Museum", 1),
      q("The Shedd on Chicago's lakefront is an…", ["aquarium", "art museum", "opera house", "observatory"], "aquarium", 1),
      q("The Adler on Chicago's lakefront is a…", ["planetarium", "zoo", "concert hall", "botanic garden"], "planetarium", 1),
      q("The Field Museum, Shedd, and Adler together form the…", ["Museum Campus", "Magnificent Mile", "Gold Coast", "Riverwalk"], "Museum Campus", 1),
      q("A captured German U-boat, U-505, is on display at…", ["the Museum of Science and Industry", "the Field Museum of Natural History", "the Chicago History Museum", "the Shedd Aquarium"], "the Museum of Science and Industry", 2),
      q("The Museum of Science and Industry's building survives from the…", ["1893 World's Fair", "1933 World's Fair", "1904 World's Fair", "1915 World's Fair"], "1893 World's Fair", 2),
      q("The original Ferris wheel debuted at Chicago's World's Fair in…", ["1893", "1871", "1933", "1916"], "1893", 2),
      q("Chicago's 1893 World's Fair was held mainly in…", ["Jackson Park", "Grant Park", "Lincoln Park", "Garfield Park"], "Jackson Park", 2),
      q("Chicago's 1893 World's Fair was nicknamed…", ["the White City", "the Emerald City", "the Iron City", "the Crystal City"], "the White City", 2),
      q("Chicago's 'L' trains and city buses are run by the…", ["CTA", "Metra", "MTA", "SEPTA"], "CTA", 1),
      q("Metra is the Chicago area's…", ["commuter rail", "subway", "ferry line", "bike share"], "commuter rail", 1),
      q("Which 'L' line runs to O'Hare Airport?", ["Blue Line", "Red Line", "Green Line", "Orange Line"], "Blue Line", 1),
      q("Which 'L' line runs to Midway Airport?", ["Orange Line", "Blue Line", "Brown Line", "Pink Line"], "Orange Line", 2),
      q("Chicago's first elevated 'L' line opened in…", ["1892", "1904", "1871", "1925"], "1892", 2),
      q("Wrigley Field's outfield walls are covered in…", ["ivy", "murals", "billboards", "mirrors"], "ivy", 1),
      q("After a Cubs win, Wrigley Field flies a white flag with a blue…", ["W", "C", "star", "bear"], "W", 1),
      q("Wrigley Field opened in…", ["1914", "1926", "1908", "1932"], "1914", 2),
      q("Bleacher fans at Wrigley famously throw back…", ["opponents' homers", "foul pop-ups", "broken bats", "rally towels"], "opponents' homers", 1),
      q("Soldier Field was named as a memorial to…", ["fallen U.S. soldiers", "a Civil War general", "a Bears founder", "a fire chief"], "fallen U.S. soldiers", 1),
      q("Navy Pier's best-known ride is its…", ["Ferris wheel", "roller coaster", "log flume", "drop tower"], "Ferris wheel", 1),
      q("For St. Patrick's Day, Chicago dyes its river…", ["green", "orange", "blue", "gold"], "green", 1),
      q("In 2021, Chicago renamed outer Lake Shore Drive to honor…", ["Jean Baptiste Point DuSable", "Harold Washington", "Richard J. Daley", "Ida B. Wells"], "Jean Baptiste Point DuSable", 2),
      q("Chicago was incorporated as a city in…", ["1837", "1803", "1871", "1818"], "1837", 2),
      q("Fort Dearborn stood at the mouth of the…", ["Chicago River", "Calumet River", "Des Plaines River", "Fox River"], "Chicago River", 2),
      q("The name 'Chicago' comes from a Native word for…", ["wild onion", "great water", "red earth", "tall grass"], "wild onion", 2),
      q("How many red stars are on Chicago's city flag?", ["four", "two", "three", "six"], "four", 1),
      q("The two blue stripes on Chicago's flag stand for…", ["bodies of water", "police and fire", "rail lines", "two founding forts"], "bodies of water", 1),
      q("One star on Chicago's flag honors…", ["Fort Dearborn", "the Bulls dynasty", "the first skyscraper", "Lincoln's election"], "Fort Dearborn", 1),
      q("The Robie House, a Prairie-style home in Hyde Park, was designed by…", ["Frank Lloyd Wright", "Louis Sullivan", "Daniel Burnham", "Mies van der Rohe"], "Frank Lloyd Wright", 2),
      q("The 1909 Plan of Chicago was led by…", ["Daniel Burnham", "Louis Sullivan", "Frederick Law Olmsted", "Potter Palmer"], "Daniel Burnham", 2),
      q("Chicago is often called the birthplace of the…", ["skyscraper", "subway", "streetcar", "suspension bridge"], "skyscraper", 1),
      q("Willis Tower's glass boxes that jut out from the Skydeck are called…", ["The Ledge", "The Edge", "TILT", "Sky Box"], "The Ledge", 1),
      q("The former John Hancock Center now goes by its address…", ["875 North Michigan Avenue", "233 South Wacker Drive", "401 North Wabash Avenue", "100 East Randolph Street"], "875 North Michigan Avenue", 2),
      q("Wacker Drive is famous for being…", ["a two-level street", "a riverside beach", "a pedestrian mall", "a toll tunnel"], "a two-level street", 1),
      q("Marina City's twin towers are often compared to…", ["corncobs", "rockets", "pinecones", "beehives"], "corncobs", 1),
      q("The big vertical sign of the famous State Street theater spells…", ["CHICAGO", "ORIENTAL", "PALACE", "REGAL"], "CHICAGO", 1),
      q("Chicago's address grid starts at State Street and…", ["Madison Street", "Monroe Street", "Lake Street", "Wacker Drive"], "Madison Street", 2),
      q("Which Chicago neighborhood is known for Mexican heritage and murals?", ["Pilsen", "Andersonville", "Bridgeport", "Ukrainian Village"], "Pilsen", 1),
      q("Pilsen was named by immigrants from…", ["Bohemia", "Mexico", "Poland", "Ireland"], "Bohemia", 2),
      q("Which North Side neighborhood has Swedish roots and a Swedish museum?", ["Andersonville", "Pilsen", "Bucktown", "Bronzeville"], "Andersonville", 2),
      q("Bronzeville grew into a center of Chicago's…", ["Black arts and business", "Polish community", "meatpacking plants", "steel mills"], "Black arts and business", 2),
      q("Chicago's Greektown is along…", ["Halsted Street", "Devon Avenue", "Argyle Street", "Clark Street"], "Halsted Street", 2),
      q("Devon Avenue on the North Side is known for…", ["South Asian shops and food", "Greek tavernas", "art galleries", "German beer halls"], "South Asian shops and food", 2),
      q("Chicago's Chinatown gate stands on…", ["Wentworth Avenue", "Michigan Avenue", "Western Avenue", "Ashland Avenue"], "Wentworth Avenue", 2),
      q("Chicago's Little Italy centers on…", ["Taylor Street", "Devon Avenue", "Division Street", "Belmont Avenue"], "Taylor Street", 2),
      q("Chicago's Gold Coast neighborhood is on the…", ["Near North Side", "Southwest Side", "West Side", "Far South Side"], "Near North Side", 1),
      q("Bridgeport is the South Side neighborhood tied to which political family?", ["the Daleys", "the Kennedys", "the Pritzkers", "the Emanuels"], "the Daleys", 1),
      q("Richard J. Daley and Richard M. Daley were both Chicago…", ["mayors", "governors", "senators", "police chiefs"], "mayors", 1),
      q("Chicago's first Black mayor was…", ["Harold Washington", "Eugene Sawyer", "Bobby Rush", "Roland Burris"], "Harold Washington", 2),
      q("Chicago's first woman mayor was…", ["Jane Byrne", "Lori Lightfoot", "Toni Preckwinkle", "Lisa Madigan"], "Jane Byrne", 2),
      q("The Harold Washington Library Center is Chicago's…", ["main public library", "city hall", "main post office", "convention center"], "main public library", 1),
      q("Jane Addams co-founded which Chicago settlement house?", ["Hull House", "Henry Street", "Toynbee Hall", "Bethel House"], "Hull House", 2),
      q("McCormick Place is Chicago's huge…", ["convention center", "sports arena", "rail yard", "airport terminal"], "convention center", 1),
      q("Chicago's Union Stock Yards were famous for…", ["meatpacking", "steelmaking", "shipbuilding", "auto assembly"], "meatpacking", 1),
      q("Lincoln Park Zoo is notable for being…", ["free to enter", "the world's oldest", "in the Loop", "on an island"], "free to enter", 1),
      q("Chicago's largest public park is…", ["Lincoln Park", "Grant Park", "Jackson Park", "Washington Park"], "Lincoln Park", 2),
      q("Grant Park is often called Chicago's…", ["front yard", "back porch", "green heart", "living room"], "front yard", 1),
      q("Garfield Park on the West Side is famous for its…", ["huge conservatory", "big-cat zoo house", "rowing lagoon", "science museum"], "huge conservatory", 1),
      q("The 606 in Chicago is a…", ["trail on an old rail line", "new 'L' subway branch", "lakefront concert lawn", "indoor food market hall"], "trail on an old rail line", 1),
      q("Chicago's Pedway is a network of…", ["underground walkways", "bike lanes", "bus lanes", "rooftop gardens"], "underground walkways", 1),
      q("Chicago's Lakefront Trail is about how long?", ["18 miles", "5 miles", "40 miles", "2 miles"], "18 miles", 2),
      q("Chicago's lakefront is mostly…", ["public parkland", "private estates", "industrial docks", "naval bases"], "public parkland", 1),
      q("Northerly Island was once home to which airport?", ["Meigs Field", "Midway", "Orchard Field", "Pal-Waukee"], "Meigs Field", 2),
      q("Midway Airport is named for…", ["a WWII naval battle", "a carnival midway", "a former mayor", "its distance from O'Hare"], "a WWII naval battle", 1),
      q("O'Hare Airport is named for…", ["a WWII Navy pilot", "a Chicago mayor", "an Irish poet", "a railroad baron"], "a WWII Navy pilot", 2),
      q("Which of Chicago's big airports is closer to downtown?", ["Midway", "O'Hare", "Gary", "Rockford"], "Midway", 1),
      q("Union Station's grand staircase is famous from a shootout in…", ["The Untouchables", "The Blues Brothers", "The Fugitive", "Home Alone"], "The Untouchables", 2),
      q("The Chicago Cultural Center is famous for its…", ["Tiffany glass dome", "rooftop garden", "spiral ramp", "glass floor"], "Tiffany glass dome", 2),
      q("The Magnificent Mile runs north from the river to…", ["Oak Street", "Division Street", "Ohio Street", "Grand Avenue"], "Oak Street", 2),
      q("Most bridges over the Chicago River are…", ["bascule bridges", "suspension bridges", "covered bridges", "pontoon bridges"], "bascule bridges", 2),
      q("Chicago's famous architecture boat tours cruise the…", ["Chicago River", "Lake Calumet", "Des Plaines River", "Fox River"], "Chicago River", 1),
      q("Chicago's 1886 Haymarket affair is tied to the fight for…", ["the eight-hour workday", "women's suffrage", "the abolition of slavery", "Prohibition"], "the eight-hour workday", 2),
      q("Gangster Al Capone ruled Chicago's underworld during…", ["Prohibition", "the Gilded Age", "the Civil War", "the Space Race"], "Prohibition", 1),
      q("The Great Migration brought many Black Chicagoans from…", ["the Deep South", "New England", "the Pacific Northwest", "the Mountain West"], "the Deep South", 2),
      q("The Chicago Defender was a famous…", ["Black newspaper", "football team", "fireboat", "radio tower"], "Black newspaper", 1),
      q("Ida B. Wells, honored by a downtown Chicago drive, crusaded against…", ["lynching", "child labor", "Prohibition", "smallpox"], "lynching", 2),
      q("Chicago's Pullman neighborhood was built as a…", ["company town", "army fort", "Olympic village", "mining camp"], "company town", 2),
      q("The statue atop the Chicago Board of Trade Building depicts…", ["Ceres", "Athena", "Mercury", "Liberty"], "Ceres", 2),
      q("Chicago's financial district centers on…", ["LaSalle Street", "Halsted Street", "Clark Street", "Ashland Avenue"], "LaSalle Street", 2),
      q("Which Chicago street is famously 'that great street'?", ["State Street", "Rush Street", "Wells Street", "Lake Street"], "State Street", 1),
      q("The landmark State Street store with the Great Clock was built for…", ["Marshall Field's", "Sears, Roebuck", "Montgomery Ward", "Carson Pirie Scott"], "Marshall Field's", 2),
      q("Chicago's Christkindlmarket is a holiday market in the style of…", ["Germany", "Italy", "Mexico", "Sweden"], "Germany", 1),
      q("Cloud Gate, 'the Bean,' is made of…", ["stainless steel", "polished silver", "chrome glass", "aluminum"], "stainless steel", 1),
      q("Chicago's Puerto Rican community is centered in…", ["Humboldt Park", "Pilsen", "Bridgeport", "Lakeview"], "Humboldt Park", 2),
      q("The Second City comedy theater is in which neighborhood?", ["Old Town", "Pilsen", "Bucktown", "Bridgeport"], "Old Town", 2),
      q("Lake Michigan is the only Great Lake entirely within…", ["the United States", "Canada", "Michigan", "Illinois"], "the United States", 1),
    ],
    food: [
      q("Ordering an Italian beef 'hot' means adding…", ["giardiniera", "extra jus", "hot sauce", "pepper jack"], "giardiniera", 1),
      q("A Chicago-style hot dog's relish is a bright…", ["neon green", "dark red", "mustard yellow", "deep brown"], "neon green", 1),
      q("A Chicago-style hot dog gets a final dash of…", ["celery salt", "garlic salt", "paprika", "cumin"], "celery salt", 1),
      q("A Maxwell Street Polish is a grilled sausage topped with…", ["grilled onions and mustard", "sauerkraut and ketchup", "chili and cheese", "coleslaw and relish"], "grilled onions and mustard", 2),
      q("Chicago tavern-style thin-crust pizza is cut into…", ["squares", "wedges", "strips", "rings"], "squares", 1),
      q("In a Chicago deep-dish pizza, the tomato sauce goes…", ["on top of the cheese", "under the cheese", "baked into the crust", "on the side"], "on top of the cheese", 1),
      q("The jibarito sandwich swaps the bread for…", ["fried plantains", "waffles", "lettuce leaves", "tortillas"], "fried plantains", 2),
      q("Chicago's Original Rainbow Cone stacks how many flavors?", ["five", "three", "seven", "four"], "five", 2),
      q("The chocolate brownie is said to have been created at which Chicago hotel?", ["the Palmer House", "the Drake", "the Blackstone", "the Congress"], "the Palmer House", 2),
      q("Portillo's is a Chicago chain best known for…", ["hot dogs and Italian beef", "deep-dish pizza", "fried chicken", "pierogi"], "hot dogs and Italian beef", 1),
    ],
    sports: [
      q("The Cubs' 2016 World Series title ended a drought dating to…", ["1908", "1918", "1945", "1969"], "1908", 2),
      q("The White Sox won the World Series in…", ["2005", "2016", "1998", "2010"], "2005", 2),
      q("The Bulls won six NBA titles in the…", ["1990s", "1980s", "2000s", "1970s"], "1990s", 1),
      q("The Bulls' 1990s dynasty was led by…", ["Michael Jordan", "Magic Johnson", "Larry Bird", "Kobe Bryant"], "Michael Jordan", 1),
      q("The 1985 Chicago Bears won…", ["Super Bowl XX", "Super Bowl X", "Super Bowl XXX", "Super Bowl V"], "Super Bowl XX", 2),
      q("The 'Monsters of the Midway' are the…", ["Bears", "Cubs", "Bulls", "White Sox"], "Bears", 1),
      q("'Papa Bear' George Halas founded and coached the…", ["Bears", "Cubs", "Bulls", "Blackhawks"], "Bears", 1),
      q("Cubs legend Ernie Banks was nicknamed…", ["Mr. Cub", "Mr. October", "The Kid", "Hammerin' Hank"], "Mr. Cub", 1),
      q("At Wrigley, broadcaster Harry Caray led fans in singing…", ["Take Me Out to the Ball Game", "Sweet Home Chicago", "God Bless America", "Sweet Caroline"], "Take Me Out to the Ball Game", 1),
      q("Chicago's WNBA team is the…", ["Sky", "Fire", "Sparks", "Storm"], "Sky", 1),
      q("The Blackhawks are one of the NHL's…", ["Original Six", "Expansion Six", "Founding Four", "Big Eight"], "Original Six", 1),
    ],
    arts: [
      q("Georges Seurat's 'A Sunday on La Grande Jatte' hangs at…", ["the Art Institute of Chicago", "the Museum of Modern Art", "the Metropolitan Museum", "the National Gallery"], "the Art Institute of Chicago", 2),
      q("Edward Hopper's 'Nighthawks' hangs at…", ["the Art Institute of Chicago", "the Whitney Museum", "the Guggenheim", "the Getty Center"], "the Art Institute of Chicago", 2),
      q("In 'Ferris Bueller's Day Off,' the friends visit…", ["the Art Institute", "the Field Museum", "the Shedd Aquarium", "the Adler Planetarium"], "the Art Institute", 2),
      q("Steppenwolf is a famous Chicago…", ["theater company", "jazz club", "comedy club", "dance troupe"], "theater company", 2),
      q("House music takes its name from a Chicago club called…", ["the Warehouse", "CBGB", "Studio 54", "the Fillmore"], "the Warehouse", 2),
      q("Chess Records in Chicago was a famous label for…", ["blues", "polka", "country", "grunge"], "blues", 1),
    ],
  },
  nyc: {
    local: [
      q("New York City's best-known nickname is…", ["the Big Apple", "the Windy City", "the Big Easy", "the Emerald City"], "the Big Apple", 1),
      q("Before it was New York, the colony was called New Amsterdam by the…", ["Dutch", "English", "Spanish", "French"], "Dutch", 1),
      q("New Amsterdam was renamed New York in honor of…", ["the Duke of York", "a Dutch governor", "a York Street merchant", "King George III"], "the Duke of York", 1),
      q("The name 'Manhattan' comes from the language of the…", ["Lenape", "Iroquois", "Cherokee", "Shawnee"], "Lenape", 2),
      q("The Statue of Liberty was a gift from…", ["France", "Britain", "Spain", "the Netherlands"], "France", 1),
      q("The Statue of Liberty was sculpted by…", ["Frédéric Bartholdi", "Auguste Rodin", "Augustus Saint-Gaudens", "Daniel Chester French"], "Frédéric Bartholdi", 2),
      q("Lady Liberty's copper skin is green because of…", ["a natural patina", "green paint", "algae growth", "a vinyl wrap"], "a natural patina", 1),
      q("Ellis Island was the main U.S. immigration station from…", ["1892 to 1954", "1820 to 1880", "1900 to 1990", "1776 to 1820"], "1892 to 1954", 2),
      q("Times Square's New Year's Eve tradition is the…", ["ball drop", "fireworks barge", "lantern parade", "bell ringing"], "ball drop", 1),
      q("Times Square is named after…", ["The New York Times", "Father Time", "a clock tower", "Times Bank"], "The New York Times", 1),
      q("The New Year's Eve ball drops from the roof of…", ["One Times Square", "the Empire State Building", "Rockefeller Center", "the Paramount Building"], "One Times Square", 2),
      q("Macy's flagship store is on…", ["Herald Square", "Union Square", "Times Square", "Washington Square"], "Herald Square", 2),
      q("The Macy's Thanksgiving Day Parade is famous for its…", ["giant balloons", "fireworks", "lanterns", "horse races"], "giant balloons", 1),
      q("The Rockefeller Center Christmas tree towers over an…", ["ice-skating rink", "reflecting pool", "outdoor café", "subway entrance"], "ice-skating rink", 1),
      q("Radio City Music Hall is home to the…", ["Rockettes", "Rockefellers", "Radio Kings", "Starlettes"], "Rockettes", 1),
      q("The observation deck atop 30 Rockefeller Plaza is called…", ["Top of the Rock", "the Edge", "Summit", "the Skydeck"], "Top of the Rock", 1),
      q("The Empire State Building opened in…", ["1931", "1905", "1950", "1969"], "1931", 2),
      q("The Empire State Building's mast was meant for docking…", ["airships", "helicopters", "seaplanes", "hot-air balloons"], "airships", 1),
      q("In the 1933 film, King Kong climbs the…", ["Empire State Building", "Chrysler Building", "Woolworth Building", "Flatiron Building"], "Empire State Building", 1),
      q("The Chrysler Building's gleaming spire is a classic of…", ["Art Deco", "Gothic Revival", "Brutalism", "Beaux-Arts"], "Art Deco", 1),
      q("The Flatiron Building is famous for its…", ["triangular shape", "spiral ramp", "glass dome", "twin spires"], "triangular shape", 1),
      q("The Woolworth Building was nicknamed the…", ["Cathedral of Commerce", "Palace of Trade", "Temple of Thrift", "Tower of Babel"], "Cathedral of Commerce", 2),
      q("Before 2009, One World Trade Center was known as the…", ["Freedom Tower", "Liberty Tower", "Unity Tower", "Hope Tower"], "Freedom Tower", 1),
      q("The 9/11 Memorial's two pools sit in the…", ["Twin Towers' footprints", "old Hudson piers", "Battery Park lawns", "Fulton Street plaza"], "Twin Towers' footprints", 1),
      q("The Charging Bull sculpture stands near…", ["Bowling Green", "Union Square", "Foley Square", "Columbus Circle"], "Bowling Green", 2),
      q("Wall Street is named for a…", ["Dutch settlers' wall", "bank vault wall", "riverside seawall", "prison wall"], "Dutch settlers' wall", 1),
      q("Trading at the New York Stock Exchange starts with the…", ["opening bell", "ship's horn", "noon cannon", "church chime"], "opening bell", 1),
      q("George Washington took the oath as first president at…", ["Federal Hall", "City Hall", "Fraunces Tavern", "Trinity Church"], "Federal Hall", 2),
      q("Alexander Hamilton is buried at…", ["Trinity Church", "St. Paul's Chapel", "Green-Wood Cemetery", "Grant's Tomb"], "Trinity Church", 2),
      q("Battery Park is at Manhattan's…", ["southern tip", "northern tip", "east side", "center"], "southern tip", 1),
      q("Gracie Mansion is the official residence of New York's…", ["mayor", "governor", "police commissioner", "cardinal"], "mayor", 1),
      q("The Verrazzano-Narrows Bridge links Brooklyn and…", ["Staten Island", "Manhattan", "Queens", "New Jersey"], "Staten Island", 1),
      q("The George Washington Bridge links Manhattan to…", ["New Jersey", "the Bronx", "Queens", "Staten Island"], "New Jersey", 1),
      q("The Holland and Lincoln Tunnels run under the…", ["Hudson River", "East River", "Harlem River", "Long Island Sound"], "Hudson River", 1),
      q("John A. Roebling designed which New York bridge?", ["Brooklyn Bridge", "Manhattan Bridge", "Williamsburg Bridge", "Queensboro Bridge"], "Brooklyn Bridge", 2),
      q("The East River separates Manhattan from…", ["Brooklyn and Queens", "New Jersey", "Staten Island", "Westchester"], "Brooklyn and Queens", 1),
      q("Which NYC borough is on the U.S. mainland?", ["the Bronx", "Manhattan", "Brooklyn", "Staten Island"], "the Bronx", 2),
      q("The least populous NYC borough is…", ["Staten Island", "the Bronx", "Queens", "Manhattan"], "Staten Island", 1),
      q("The most populous NYC borough is…", ["Brooklyn", "Manhattan", "the Bronx", "Staten Island"], "Brooklyn", 1),
      q("The largest NYC borough by land area is…", ["Queens", "Brooklyn", "Manhattan", "the Bronx"], "Queens", 2),
      q("Brooklyn was an independent city until…", ["1898", "1854", "1925", "1871"], "1898", 2),
      q("The Bronx takes its name from settler…", ["Jonas Bronck", "Peter Stuyvesant", "Henry Hudson", "John Jay"], "Jonas Bronck", 1),
      q("Roosevelt Island is linked to Manhattan by an aerial…", ["tramway", "zip line", "funicular", "monorail"], "tramway", 1),
      q("Coney Island's famous wooden roller coaster is the…", ["Cyclone", "Thunderbolt", "Beast", "Comet"], "Cyclone", 1),
      q("Nathan's Famous at Coney Island hosts a July 4th…", ["hot dog eating contest", "fireworks regatta", "sandcastle contest", "boardwalk parade"], "hot dog eating contest", 1),
      q("Brighton Beach is nicknamed 'Little Odessa' for its…", ["Russian-speaking residents", "Greek tavernas", "Italian bakeries", "Polish delis"], "Russian-speaking residents", 1),
      q("Astoria, Queens, is known for its large…", ["Greek community", "Swedish community", "Polish community", "Irish community"], "Greek community", 2),
      q("The giant steel Unisphere in Queens was built for the…", ["1964 World's Fair", "1939 World's Fair", "1976 Bicentennial", "1986 Liberty Weekend"], "1964 World's Fair", 2),
      q("Central Park's Strawberry Fields memorial honors…", ["John Lennon", "Bob Dylan", "Frank Sinatra", "Paul Simon"], "John Lennon", 1),
      q("Central Park's big reservoir is named for…", ["Jacqueline Kennedy Onassis", "Eleanor Roosevelt", "Fiorello La Guardia", "Robert Moses"], "Jacqueline Kennedy Onassis", 2),
      q("Central Park stretches from 59th Street up to…", ["110th Street", "96th Street", "125th Street", "155th Street"], "110th Street", 2),
      q("The NYC Marathon finishes in…", ["Central Park", "Times Square", "Battery Park", "Prospect Park"], "Central Park", 1),
      q("Brooklyn's Prospect Park was designed by…", ["Olmsted and Vaux", "Robert Moses", "Daniel Burnham", "Burnham and Root"], "Olmsted and Vaux", 1),
      q("The Brooklyn Botanic Garden is famous for its spring…", ["cherry blossoms", "tulip maze", "sunflower field", "lavender rows"], "cherry blossoms", 1),
      q("DUMBO in Brooklyn stands for…", ["Down Under the Manhattan Bridge Overpass", "Docks Under the Main Brooklyn Overpass", "District Under the Metro Bridge Outlet", "Downtown Union of Merchants by Overpass"], "Down Under the Manhattan Bridge Overpass", 1),
      q("SoHo stands for…", ["South of Houston Street", "South of Hudson Street", "South of Howard Street", "South of Harlem"], "South of Houston Street", 1),
      q("TriBeCa stands for…", ["Triangle Below Canal Street", "Tri-Borough Center", "Trinity Bend on Canal", "Tribune Block Center"], "Triangle Below Canal Street", 1),
      q("New Yorkers pronounce Houston Street as…", ["HOUSE-ton", "HYOO-ston", "HOO-ston", "HUSS-ton"], "HOUSE-ton", 2),
      q("Little Italy's big September festival honors…", ["San Gennaro", "St. Patrick", "San Juan", "St. Anthony"], "San Gennaro", 2),
      q("Washington Square Park is known for its marble…", ["arch", "obelisk", "fountain lions", "clock tower"], "arch", 1),
      q("Which university's campus surrounds Washington Square Park?", ["NYU", "Columbia", "Fordham", "CUNY"], "NYU", 1),
      q("The Stonewall Inn is in…", ["Greenwich Village", "Harlem", "the Upper East Side", "Williamsburg"], "Greenwich Village", 1),
      q("Harlem's 125th Street is also named for…", ["Dr. Martin Luther King", "Malcolm X", "Adam Clayton Powell", "Frederick Douglass"], "Dr. Martin Luther King", 2),
      q("The Harlem Renaissance of the 1920s was a flowering of…", ["Black arts and letters", "Dutch architecture", "Irish theater", "Italian opera"], "Black arts and letters", 1),
      q("The Cotton Club was a famous jazz nightclub in…", ["Harlem", "SoHo", "Brooklyn Heights", "the Bronx"], "Harlem", 1),
      q("Hip-hop is widely traced to a 1973 party in…", ["the Bronx", "Brooklyn", "Queens", "Harlem"], "the Bronx", 1),
      q("The New York Botanical Garden is in…", ["the Bronx", "Brooklyn", "Queens", "Manhattan"], "the Bronx", 1),
      q("Freshkills Park on Staten Island was once a…", ["landfill", "naval base", "racetrack", "airport"], "landfill", 2),
      q("New York's public library lions are named…", ["Patience and Fortitude", "Liberty and Justice", "Faith and Hope", "Truth and Honor"], "Patience and Fortitude", 1),
      q("Bryant Park sits right behind the…", ["main public library", "Empire State Building", "Port Authority", "Chrysler Building"], "main public library", 1),
      q("Union Square is home to a famous…", ["farmers market", "flower clock", "fish market", "car show"], "farmers market", 1),
      q("Chelsea Market occupies a former…", ["Nabisco factory", "Navy shipyard", "rail depot", "meat locker"], "Nabisco factory", 2),
      q("St. Patrick's Cathedral faces…", ["Fifth Avenue", "Park Avenue", "Broadway", "Madison Avenue"], "Fifth Avenue", 1),
      q("In Manhattan's grid, numbered streets run…", ["east–west", "north–south", "diagonally", "in circles"], "east–west", 1),
      q("About how many north–south Manhattan blocks make a mile?", ["20", "10", "5", "40"], "20", 2),
      q("'Manhattanhenge' happens when the sunset…", ["lines up with the street grid", "turns the rivers red", "hits the Statue's torch", "sets behind the Empire State"], "lines up with the street grid", 1),
      q("Grand Central's famous four-faced clock sits atop the…", ["information booth", "ticket windows", "main staircase", "track 1 gate"], "information booth", 1),
      q("Grand Central's Whispering Gallery is just outside the…", ["Oyster Bar", "Apple Store", "Vanderbilt Hall", "Dining Concourse"], "Oyster Bar", 2),
      q("The PATH trains link Manhattan with…", ["New Jersey", "Long Island", "Westchester", "Connecticut"], "New Jersey", 1),
      q("The 1963 demolition of the old Penn Station spurred NYC's…", ["landmarks law", "first subway", "Port Authority", "zoning grid"], "landmarks law", 2),
      q("The train hall across Eighth Avenue from Penn Station honors…", ["Daniel Patrick Moynihan", "Fiorello La Guardia", "Alexander Hamilton", "Robert F. Wagner"], "Daniel Patrick Moynihan", 2),
      q("LaGuardia Airport is named for a former New York…", ["mayor", "governor", "aviator", "general"], "mayor", 1),
      q("Before 1963, JFK Airport was popularly known as…", ["Idlewild", "Floyd Bennett", "Newark", "Mitchel Field"], "Idlewild", 2),
      q("New York's subway famously runs…", ["around the clock", "dawn to midnight", "until 1 in the morning", "weekdays and Saturdays"], "around the clock", 1),
      q("A New York 'bodega' is a…", ["corner store", "rooftop bar", "subway kiosk", "street vendor"], "corner store", 1),
      q("A New York 'stoop' is a building's…", ["front steps", "rooftop garden", "fire escape", "basement flat"], "front steps", 1),
      q("New York's iconic medallion taxis are painted…", ["yellow", "red", "black", "white"], "yellow", 1),
      q("The Tenement Museum on the Lower East Side tells the story of…", ["immigrant families", "Wall Street bankers", "Dutch governors", "Broadway stars"], "immigrant families", 1),
      q("The 1911 Triangle Shirtwaist Factory fire led to new…", ["workplace safety laws", "subway lines", "fire hydrants", "skyscraper limits"], "workplace safety laws", 1),
      q("Robert Moses was famous as New York's master builder of…", ["parks and highways", "subway cars", "skyscrapers", "Broadway theaters"], "parks and highways", 1),
      q("Mayor Ed Koch's famous catchphrase was…", ["How'm I doin'?", "Fuhgeddaboudit!", "Start spreading the news", "I'm walkin' here!"], "How'm I doin'?", 2),
      q("South Street Seaport sits on the…", ["East River", "Hudson River", "Harlem River", "Gowanus Canal"], "East River", 1),
      q("The Intrepid Museum is housed on a former…", ["aircraft carrier", "ocean liner", "submarine", "lighthouse"], "aircraft carrier", 1),
      q("The 'Great White Way' is a nickname for…", ["Broadway", "Fifth Avenue", "Wall Street", "the Bowery"], "Broadway", 1),
    ],
    food: [
      q("A black-and-white cookie is iced in…", ["chocolate and vanilla", "lemon and lime", "mint and cocoa", "cherry and cream"], "chocolate and vanilla", 1),
      q("Despite its name, a New York egg cream contains no…", ["eggs", "milk", "seltzer", "syrup"], "eggs", 1),
      q("Manhattan clam chowder has a broth based on…", ["tomatoes", "cream", "butter", "cheese"], "tomatoes", 1),
      q("A knish is a…", ["potato-filled pastry", "rye-bread sandwich", "sesame bagel", "noodle pudding"], "potato-filled pastry", 1),
      q("The lox on a New York bagel is…", ["cured salmon", "smoked trout", "pickled herring", "seared tuna"], "cured salmon", 1),
      q("Katz's Delicatessen, famed for pastrami, is on…", ["Houston Street", "Mott Street", "Canal Street", "Mulberry Street"], "Houston Street", 2),
      q("The Oreo cookie was first made in a Nabisco plant now known as…", ["Chelsea Market", "Essex Market", "Smorgasburg", "the Seaport"], "Chelsea Market", 2),
      q("Lombardi's in Little Italy is often called America's first…", ["licensed pizzeria", "bagel bakery", "hot dog stand", "Jewish deli"], "licensed pizzeria", 2),
      q("New York halal-cart platters come drizzled with…", ["white sauce", "maple syrup", "gravy", "honey mustard"], "white sauce", 1),
      q("Smorgasburg in Brooklyn is a…", ["weekend food market", "Swedish museum", "subway line", "jazz club"], "weekend food market", 1),
    ],
    sports: [
      q("Flushing Meadows hosts which tennis Grand Slam?", ["US Open", "Wimbledon", "French Open", "Australian Open"], "US Open", 1),
      q("The US Open's main tennis court is…", ["Arthur Ashe Stadium", "Louis Armstrong Stadium", "Billie Jean King Court", "Rod Laver Arena"], "Arthur Ashe Stadium", 1),
      q("The Mets' Citi Field replaced…", ["Shea Stadium", "Ebbets Field", "the Polo Grounds", "Yankee Stadium"], "Shea Stadium", 2),
      q("Ebbets Field was home to the…", ["Brooklyn Dodgers", "New York Giants", "New York Yankees", "Brooklyn Nets"], "Brooklyn Dodgers", 1),
      q("'The House That Ruth Built' was the nickname of the original…", ["Yankee Stadium", "Polo Grounds", "Ebbets Field", "Shea Stadium"], "Yankee Stadium", 1),
      q("Which MLB team has won the most World Series titles?", ["New York Yankees", "St. Louis Cardinals", "Boston Red Sox", "Los Angeles Dodgers"], "New York Yankees", 1),
      q("The 1969 champion Mets are remembered as the…", ["Miracle Mets", "Amazin' Aces", "Big Blue Mets", "Lucky Mets"], "Miracle Mets", 1),
      q("Which NHL team plays at Madison Square Garden?", ["New York Rangers", "New York Islanders", "New Jersey Devils", "Buffalo Sabres"], "New York Rangers", 1),
    ],
    arts: [
      q("Duke Ellington's theme song tells you to take the…", ["A Train", "D Train", "L Train", "Q Train"], "A Train", 1),
      q("The old joke asks how to get to Carnegie Hall. The answer?", ["Practice", "Take a cab", "Ask a cop", "Follow the music"], "Practice", 1),
      q("The Apollo Theater's famous talent show is…", ["Amateur Night", "Open Mic Monday", "Star Search", "Showtime Sunday"], "Amateur Night", 1),
      q("The Met Gala raises money for the Met's…", ["Costume Institute", "Egyptian wing", "rooftop garden", "opera house"], "Costume Institute", 1),
      q("The Met's Temple of Dendur comes from…", ["Egypt", "Greece", "Mexico", "India"], "Egypt", 1),
      q("The Whitney Museum focuses on…", ["American art", "Asian art", "ancient art", "African art"], "American art", 1),
      q("In the children's books, Eloise lives at…", ["the Plaza Hotel", "the Waldorf", "the Chelsea Hotel", "the Dakota"], "the Plaza Hotel", 1),
      q("Saturday Night Live is broadcast from…", ["30 Rockefeller Plaza", "the Ed Sullivan Theater", "Radio City", "Lincoln Center"], "30 Rockefeller Plaza", 1),
      q("Andy Warhol's New York studio was called…", ["the Factory", "the Studio", "the Loft", "the Workshop"], "the Factory", 1),
      q("CBGB on the Bowery was a famous club for…", ["punk rock", "swing jazz", "opera", "disco"], "punk rock", 1),
    ],
  },
  sf: {
    local: [
      q("San Francisco's summer fog has a popular nickname…", ["Karl", "Fred", "Gus", "Hank"], "Karl", 2),
      q("San Francisco is named for…", ["St. Francis of Assisi", "Sir Francis Drake", "Pope Francis I", "Francis Scott Key"], "St. Francis of Assisi", 1),
      q("Before 1847, San Francisco was called…", ["Yerba Buena", "Monterey", "Alta Mesa", "Santa Clara"], "Yerba Buena", 2),
      q("The Spanish founded a mission and presidio at San Francisco in…", ["1776", "1849", "1906", "1700"], "1776", 1),
      q("Many San Franciscans dislike which nickname for their city?", ["Frisco", "the City", "Fog City", "the City by the Bay"], "Frisco", 1),
      q("Columnist Herb Caen dubbed San Francisco…", ["Baghdad by the Bay", "Paris of the West", "Gotham by the Sea", "Athens of the Coast"], "Baghdad by the Bay", 2),
      q("San Francisco's city flag shows a…", ["phoenix rising from flames", "grizzly bear and star", "golden bridge at dusk", "cable car on a hill"], "phoenix rising from flames", 1),
      q("San Francisco's motto 'Oro en paz, fierro en guerra' means…", ["Gold in peace, iron in war", "Gold for all, iron for none", "Peace by gold, war by iron", "Gold and iron in harmony"], "Gold in peace, iron in war", 3),
      q("San Francisco sits at the tip of a…", ["peninsula", "volcanic island", "river delta", "desert mesa"], "peninsula", 1),
      q("San Francisco's great earthquake and fire struck in…", ["1906", "1989", "1868", "1925"], "1906", 1),
      q("Lotta's Fountain became a meeting point after the…", ["1906 earthquake", "1989 earthquake", "Gold Rush", "1915 World's Fair"], "1906 earthquake", 2),
      q("The 1989 Bay Area earthquake is known as the…", ["Loma Prieta earthquake", "Napa Valley earthquake", "Hayward earthquake", "Northridge earthquake"], "Loma Prieta earthquake", 2),
      q("Damage from the 1989 quake led San Francisco to tear down the…", ["Embarcadero Freeway", "Bay Bridge", "Ferry Building", "Transamerica Pyramid"], "Embarcadero Freeway", 2),
      q("The Marina District's 1989 quake damage was worsened by…", ["soil liquefaction", "a tsunami", "a dam failure", "wildfire"], "soil liquefaction", 2),
      q("Gold was discovered in California, booming San Francisco, in…", ["1848", "1776", "1906", "1869"], "1848", 2),
      q("Levi Strauss came to San Francisco to sell dry goods during the…", ["Gold Rush", "Civil War", "Great Depression", "Dot-com boom"], "Gold Rush", 1),
      q("The Golden Gate Bridge opened in…", ["1937", "1906", "1959", "1971"], "1937", 2),
      q("The Golden Gate Bridge links San Francisco to…", ["Marin County", "Oakland", "Alameda", "San Mateo"], "Marin County", 1),
      q("The 'Golden Gate' itself is the name of the…", ["strait at the bay's mouth", "park's main entrance", "old Gold Rush customs gate", "city's main ferry dock"], "strait at the bay's mouth", 1),
      q("The Golden Gate Bridge's chief engineer was…", ["Joseph Strauss", "John Roebling", "Othmar Ammann", "Levi Strauss"], "Joseph Strauss", 2),
      q("When it opened, the Golden Gate Bridge had the world's…", ["longest suspension span", "tallest tower of any kind", "widest roadway", "first steel deck"], "longest suspension span", 1),
      q("Fort Point sits beneath the southern end of the…", ["Golden Gate Bridge", "Bay Bridge", "San Mateo Bridge", "Richmond Bridge"], "Golden Gate Bridge", 1),
      q("The Bay Bridge links San Francisco with…", ["Oakland", "Sausalito", "San Jose", "Marin County"], "Oakland", 1),
      q("The Bay Bridge tunnels through which island?", ["Yerba Buena Island", "Alcatraz", "Angel Island", "Treasure Island"], "Yerba Buena Island", 2),
      q("Treasure Island was built for a…", ["1939 world's fair", "railroad terminal", "Gold Rush port", "1915 world's fair"], "1939 world's fair", 2),
      q("The Palace of Fine Arts was built for the…", ["1915 world's fair", "1939 world's fair", "1894 Midwinter Fair", "1906 rebuilding"], "1915 world's fair", 2),
      q("Alcatraz is nicknamed…", ["The Rock", "The Island", "The Cage", "The Fortress"], "The Rock", 1),
      q("Which gangster was famously imprisoned on Alcatraz?", ["Al Capone", "John Dillinger", "Bugsy Siegel", "Lucky Luciano"], "Al Capone", 1),
      q("Alcatraz closed as a federal prison in…", ["1963", "1934", "1975", "1946"], "1963", 2),
      q("From 1969 to 1971, Alcatraz was occupied by…", ["Native American activists", "striking dockworkers", "Navy cadets", "student protesters"], "Native American activists", 1),
      q("Angel Island in the bay was a West Coast…", ["immigration station", "naval shipyard", "lighthouse colony", "gold mint"], "immigration station", 2),
      q("Golden Gate Park keeps a small herd of…", ["bison", "elk", "camels", "llamas"], "bison", 1),
      q("Golden Gate Park's Japanese Tea Garden is the oldest public Japanese garden in…", ["the U.S.", "Asia", "Europe", "Canada"], "the U.S.", 1),
      q("Two Dutch windmills stand at Golden Gate Park's…", ["ocean end", "eastern Panhandle", "Haight entrance", "central lake"], "ocean end", 1),
      q("The Conservatory of Flowers is a Victorian…", ["greenhouse", "opera house", "train station", "bandstand"], "greenhouse", 1),
      q("The de Young art museum stands in…", ["Golden Gate Park", "the Presidio", "Union Square", "Mission Bay"], "Golden Gate Park", 1),
      q("The California Academy of Sciences is known for its…", ["living roof", "glass pyramid", "spiral ramp", "copper dome"], "living roof", 2),
      q("The Legion of Honor art museum sits in…", ["Lincoln Park", "Dolores Park", "McLaren Park", "Washington Square"], "Lincoln Park", 2),
      q("The ruins of the Sutro Baths are at…", ["Lands End", "Fisherman's Wharf", "Hunters Point", "Mission Bay"], "Lands End", 2),
      q("Sutro Tower on the skyline is a…", ["TV and radio antenna", "water tower", "lighthouse", "fire lookout"], "TV and radio antenna", 1),
      q("San Francisco's highest point is…", ["Mount Davidson", "Twin Peaks", "Nob Hill", "Telegraph Hill"], "Mount Davidson", 2),
      q("Lombard Street's famous crooked block has how many hairpin turns?", ["eight", "four", "twelve", "six"], "eight", 2),
      q("Fisherman's Wharf's sea lions lounge on the docks at…", ["Pier 39", "Pier 1", "Pier 70", "Pier 15"], "Pier 39", 1),
      q("Ghirardelli Square was once a…", ["chocolate factory", "Army fort", "fish cannery", "rail yard"], "chocolate factory", 1),
      q("Hyde Street Pier is known for its…", ["historic ships", "roller coaster", "fish market", "ferry to Oakland"], "historic ships", 1),
      q("San Francisco's Chinatown is the oldest in…", ["North America", "Europe", "Australia", "South America"], "North America", 1),
      q("The Dragon Gate marks the entrance to…", ["Chinatown", "Japantown", "North Beach", "the Mission"], "Chinatown", 1),
      q("The Dragon Gate opens onto which Chinatown street?", ["Grant Avenue", "Market Street", "Lombard Street", "Van Ness Avenue"], "Grant Avenue", 2),
      q("North Beach is San Francisco's historic…", ["Little Italy", "Chinatown", "Japantown", "Irish quarter"], "Little Italy", 1),
      q("City Lights Bookstore in North Beach is tied to the…", ["Beat Generation", "Lost Generation", "Harlem Renaissance", "Hudson River School"], "Beat Generation", 1),
      q("The 1967 'Summer of Love' centered on…", ["Haight-Ashbury", "Nob Hill", "the Marina", "Pacific Heights"], "Haight-Ashbury", 1),
      q("Haight-Ashbury is named for…", ["two crossing streets", "two founding families", "two old ranches", "two hills"], "two crossing streets", 1),
      q("Harvey Milk was elected to San Francisco's…", ["Board of Supervisors", "state senate", "school board", "Congress"], "Board of Supervisors", 1),
      q("The rainbow Pride flag was first designed in San Francisco by…", ["Gilbert Baker", "Harvey Milk", "Cleve Jones", "Keith Haring"], "Gilbert Baker", 2),
      q("The Mission District takes its name from…", ["Mission Dolores", "a Navy mission", "Mission Bay", "a mission bell"], "Mission Dolores", 1),
      q("Mission Dolores is San Francisco's oldest…", ["intact building", "public park", "cable car line", "newspaper"], "intact building", 1),
      q("Japantown is anchored by a five-tiered…", ["Peace Pagoda", "Zen temple", "Torii gate", "bell tower"], "Peace Pagoda", 2),
      q("Union Square is named for rallies supporting…", ["the Union in the Civil War", "labor unions", "the 1906 rebuilding", "statehood in 1850"], "the Union in the Civil War", 1),
      q("Market Street ends at the waterfront at the…", ["Ferry Building", "Pier 39", "Coit Tower", "Oracle Park"], "Ferry Building", 1),
      q("The Ferry Building's clock tower was modeled on a tower in…", ["Seville", "Venice", "London", "Paris"], "Seville", 3),
      q("Today the Ferry Building is known for its…", ["food marketplace", "naval museum", "concert hall", "city archives"], "food marketplace", 1),
      q("The Transamerica Pyramid stands in the…", ["Financial District", "Mission District", "Sunset District", "Marina District"], "Financial District", 1),
      q("SoMa in San Francisco is short for…", ["South of Market", "South Mission", "Sonoma Main", "South of Marina"], "South of Market", 1),
      q("Nob Hill's name comes from…", ["'nabob,' a rich tycoon", "a Spanish chapel bell", "a local doorknob maker", "a Miwok word for hill"], "'nabob,' a rich tycoon", 2),
      q("Grace Cathedral stands atop…", ["Nob Hill", "Russian Hill", "Telegraph Hill", "Twin Peaks"], "Nob Hill", 2),
      q("Russian Hill is named for…", ["graves of Russian sailors", "a Russian fur fort", "a czar's 1860 visit", "a Russian church"], "graves of Russian sailors", 3),
      q("Telegraph Hill is named for an early…", ["signal station for ships", "telegraph company HQ", "newspaper office", "radio tower"], "signal station for ships", 1),
      q("Telegraph Hill is famous for a flock of wild…", ["parrots", "peacocks", "flamingos", "swans"], "parrots", 1),
      q("Coit Tower is named for…", ["Lillie Hitchcock Coit", "a fire chief named Coit", "Coit, a Gold Rush banker", "Mayor James Coit"], "Lillie Hitchcock Coit", 1),
      q("San Francisco's public transit agency is…", ["Muni", "BART", "Caltrain", "AC Transit"], "Muni", 1),
      q("Vintage streetcars along Market Street run on Muni's…", ["F line", "N line", "T line", "J line"], "F line", 2),
      q("How many cable car lines still run in San Francisco?", ["three", "one", "five", "eight"], "three", 1),
      q("Cable cars at Powell and Market are turned around on a…", ["turntable", "loop track", "ramp", "crane"], "turntable", 1),
      q("Andrew Hallidie launched San Francisco's first cable car line in…", ["1873", "1906", "1849", "1890"], "1873", 2),
      q("The Cable Car Museum doubles as the system's working…", ["powerhouse", "ticket office", "repair yard", "control tower"], "powerhouse", 2),
      q("BART crosses under the bay through the…", ["Transbay Tube", "Golden Gate Tunnel", "Bay Bore", "Oakland Tube"], "Transbay Tube", 1),
      q("Caltrain runs from San Francisco down the Peninsula to…", ["San Jose", "Sacramento", "Oakland", "Napa"], "San Jose", 1),
      q("San Francisco International Airport actually sits in…", ["San Mateo County", "San Francisco County", "Alameda County", "Marin County"], "San Mateo County", 2),
      q("Muir Woods, north of the city, is famous for…", ["coast redwoods", "giant sequoias", "desert palms", "Joshua trees"], "coast redwoods", 1),
      q("Crissy Field was once an Army…", ["airfield", "hospital", "prison", "cemetery"], "airfield", 2),
      q("The Exploratorium is a hands-on museum of…", ["science and perception", "modern painting", "maritime history", "Asian art"], "science and perception", 1),
      q("Bay to Breakers is a San Francisco…", ["costumed footrace", "sailing regatta", "bike tour", "swim race"], "costumed footrace", 1),
      q("San Francisco's Chinese New Year Parade ends with a giant…", ["golden dragon", "red phoenix", "jade tiger", "paper ox"], "golden dragon", 1),
      q("San Francisco's Fleet Week air show stars the…", ["Blue Angels", "Thunderbirds", "Red Arrows", "Snowbirds"], "Blue Angels", 1),
      q("Stern Grove is known for its free summer…", ["concerts", "rodeos", "film shoots", "car shows"], "concerts", 1),
      q("San Francisco gets much of its water from…", ["Hetch Hetchy", "Lake Tahoe", "the Colorado River", "Lake Shasta"], "Hetch Hetchy", 2),
      q("The Sunset and Richmond districts are on the city's…", ["west side", "east side", "north shore", "south border"], "west side", 1),
      q("San Francisco's numbered 'Avenues' run…", ["north–south", "east–west", "diagonally", "in a ring"], "north–south", 2),
      q("San Francisco City Hall's dome is taller than the dome of the…", ["U.S. Capitol", "St. Peter's Basilica", "St. Paul's Cathedral", "Duomo in Florence"], "U.S. Capitol", 2),
      q("Marilyn Monroe and Joe DiMaggio married at…", ["San Francisco City Hall", "Grace Cathedral", "Mission Dolores", "the Palace Hotel"], "San Francisco City Hall", 1),
      q("Oakland's Lake Merritt is a…", ["tidal lagoon", "volcanic crater", "reservoir dam", "glacial lake"], "tidal lagoon", 2),
    ],
    food: [
      q("Fisherman's Wharf is famous for which local crab?", ["Dungeness", "blue", "king", "snow"], "Dungeness", 1),
      q("Boudin on the wharf is a famous San Francisco…", ["sourdough bakery", "chocolate shop", "coffee roaster", "crab shack"], "sourdough bakery", 1),
      q("Irish coffee was popularized in the U.S. at…", ["the Buena Vista Cafe", "Tadich Grill", "the Cliff House", "Vesuvio Cafe"], "the Buena Vista Cafe", 2),
      q("An It's-It is ice cream sandwiched between…", ["oatmeal cookies", "chocolate wafers", "sugar cookies", "graham crackers"], "oatmeal cookies", 2),
      q("Rice-A-Roni was famously advertised as…", ["the San Francisco Treat", "the Golden Gate Grain", "the Cable Car Classic", "the Bay Area Bite"], "the San Francisco Treat", 1),
      q("Tadich Grill is often called California's oldest…", ["restaurant", "bakery", "coffee house", "brewery"], "restaurant", 2),
      q("Dutch Crunch, a Bay Area favorite, is a…", ["crackly-topped bread", "fried cookie dough", "salted caramel bar", "spiced apple cake"], "crackly-topped bread", 1),
      q("San Francisco's Chinatown is famous for which brunch of small plates?", ["dim sum", "tapas", "mezze", "smørrebrød"], "dim sum", 1),
      q("Ghirardelli, founded in San Francisco, is famous for…", ["chocolate", "sourdough", "coffee", "ice cream"], "chocolate", 1),
    ],
    sports: [
      q("The 49ers are named for…", ["Gold Rush prospectors", "a Navy ship", "a 1949 title team", "a city street"], "Gold Rush prospectors", 1),
      q("The 49ers' first home was Kezar Stadium in…", ["Golden Gate Park", "the Presidio", "Candlestick Point", "Mission Bay"], "Golden Gate Park", 2),
      q("The Giants and 49ers once shared…", ["Candlestick Park", "Kezar Pavilion", "the Cow Palace", "Seals Stadium"], "Candlestick Park", 1),
      q("The Giants moved to San Francisco in 1958 from…", ["New York", "Brooklyn", "Boston", "St. Louis"], "New York", 1),
      q("Giants legend Willie Mays was nicknamed…", ["the Say Hey Kid", "the Splendid Splinter", "the Iron Horse", "Mr. October"], "the Say Hey Kid", 1),
      q("The 1989 World Series interrupted by an earthquake pitted the Giants against the…", ["Oakland A's", "Los Angeles Dodgers", "San Diego Padres", "Anaheim Angels"], "Oakland A's", 1),
      q("Joe Montana's game-winning TD pass to Dwight Clark is called…", ["The Catch", "The Drive", "The Throw", "The Snap"], "The Catch", 1),
      q("The Warriors moved from Oakland to San Francisco in…", ["2019", "2012", "2004", "1997"], "2019", 2),
      q("The Warriors franchise was founded in…", ["Philadelphia", "Seattle", "Chicago", "Boston"], "Philadelphia", 2),
    ],
    arts: [
      q("A famous scene in Hitchcock's 'Vertigo' was filmed at…", ["Fort Point", "Coit Tower", "Pier 39", "Alcatraz"], "Fort Point", 2),
      q("Steve McQueen's famous San Francisco car chase is in…", ["Bullitt", "Dirty Harry", "The Rock", "Vertigo"], "Bullitt", 2),
      q("The Painted Ladies appear in the opening credits of…", ["Full House", "Friends", "Seinfeld", "Frasier"], "Full House", 1),
      q("Poet Lawrence Ferlinghetti co-founded…", ["City Lights", "Rolling Stone", "the Fillmore", "SFMOMA"], "City Lights", 1),
    ],
  },
};
