import { q } from "../quiz";
import type { CityId, TriviaCat, TriviaQ } from "../types";

/**
 * Local trivia cards, batch 4 (v0.0.48 / k48a): Seattle, Denver and Nashville, the three new cities.
 * Every fact was checked against the source listed for it in docs/trivia-sources-cities-0.0.48.md.
 * Easy cards are difficulty 1 so they band white/blue; city cards above that step up one tier.
 * Merged into CITY_EXTRA by cities.ts (rarity stamped there with the city nudge).
 */
export const CITY_EXTRA_PART_G: Partial<Record<CityId, Partial<Record<TriviaCat, TriviaQ[]>>>> = {
  seattle: {
    local: [
      q("How tall is the Space Needle?", ["605 feet", "455 feet", "725 feet", "1,020 feet"], "605 feet", 2),
      q("The Space Needle's design was a compromise between Edward E. Carlson and…", ["John Graham", "Minoru Yamasaki", "Paul Thiry", "Rem Koolhaas"], "John Graham", 3),
      q("Seattle's best-known nickname is the…", ["Emerald City", "Rose City", "Mile High City", "Magic City"], "Emerald City", 1),
      q("Seattle lies between Puget Sound and which lake to its east?", ["Lake Washington", "Lake Chelan", "Lake Sammamish", "Lake Crescent"], "Lake Washington", 1),
      q("Seattle is the county seat of…", ["King County", "Pierce County", "Snohomish County", "Kitsap County"], "King County", 1),
      q("Seattle's King County now officially honors…", ["Dr. Martin Luther King", "William Rufus DeVane King", "Rodney King", "Coretta Scott King"], "Dr. Martin Luther King", 2),
      q("King County was first named in 1852 for vice president-elect…", ["William R. King", "John C. Calhoun", "George M. Dallas", "Richard M. Johnson"], "William R. King", 2),
      q("Seattle takes its name from…", ["Chief Seattle", "Arthur Denny", "Henry Yesler", "Doc Maynard"], "Chief Seattle", 1),
      q("Chief Seattle was a leader of the Duwamish and the…", ["Suquamish", "Makah", "Yakama", "Spokane"], "Suquamish", 2),
      q("The Denny Party landed at Alki Point in…", ["1851", "1869", "1889", "1832"], "1851", 2),
      q("Seattle's founding settlers first built cabins at which point?", ["Alki Point", "Point Defiance", "Duwamish Head", "Magnolia Bluff"], "Alki Point", 2),
      q("The name of the first settlement, Alki, is Chinook Jargon for…", ["by and by", "big water", "new home", "fair wind"], "by and by", 3),
      q("Seattle's original 'Skid Road' is said to be today's…", ["Yesler Way", "Pike Street", "Denny Way", "Madison Street"], "Yesler Way", 2),
      q("Smith Tower in Pioneer Square opened in…", ["1914", "1902", "1929", "1936"], "1914", 2),
      q("Until 2016, Smith Tower's 35th-floor observatory was called the…", ["Chinese Room", "Crystal Room", "Sky Lounge", "Totem Room"], "Chinese Room", 3),
      q("How many stories is Columbia Center, Seattle's tallest building?", ["76", "58", "62", "101"], "76", 2),
      q("Columbia Center's public observation deck is the…", ["Sky View Observatory", "Space Needle Loupe", "Crow's Nest", "Summit Room"], "Sky View Observatory", 2),
      q("Seattle Central Library's glass-and-steel building opened in…", ["2004", "1996", "2010", "2015"], "2004", 2),
      q("King Street Station's clock tower was modeled on a campanile in which Italian city?", ["Venice", "Florence", "Pisa", "Siena"], "Venice", 2),
      q("King Street Station opened in…", ["1906", "1889", "1923", "1911"], "1906", 2),
      q("Seattle's Union Station was built for the Union Pacific and the…", ["Milwaukee Road", "Great Northern", "Northern Pacific", "Santa Fe"], "Milwaukee Road", 3),
      q("The Seattle Center Monorail runs between Seattle Center and…", ["Westlake Center", "Pike Place Market", "King Street Station", "the ferry terminal"], "Westlake Center", 1),
      q("At Pike Place Market's best-known fish stand, workers famously…", ["throw the fish", "sing the prices", "ring a brass bell", "race the carts"], "throw the fish", 1),
      q("Pike Place Market's bronze piggy bank mascot is named…", ["Rachel", "Penny", "Wilbur", "Daisy"], "Rachel", 2),
      q("The Gum Wall is in Post Alley beneath…", ["Pike Place Market", "Smith Tower", "the Space Needle", "Pioneer Square"], "Pike Place Market", 1),
      q("The Gum Wall was fully steam-cleaned for the first time in two decades in…", ["2015", "2005", "1999", "2021"], "2015", 3),
      q("The Gum Wall is beside the box office of which theater?", ["Market Theater", "Moore Theatre", "Paramount Theatre", "5th Avenue Theatre"], "Market Theater", 2),
      q("The Seattle Great Wheel stands at the end of which pier?", ["Pier 57", "Pier 66", "Pier 70", "Pier 91"], "Pier 57", 2),
      q("When it opened in 2012, the Seattle Great Wheel was the tallest Ferris wheel on the…", ["West Coast", "Gulf Coast", "Great Lakes", "East Coast"], "West Coast", 2),
      q("The Seattle Aquarium sits on which waterfront pier?", ["Pier 59", "Pier 57", "Pier 52", "Pier 69"], "Pier 59", 2),
      q("From Colman Dock, state ferries sail to Bainbridge Island and…", ["Bremerton", "Victoria", "Port Angeles", "Everett"], "Bremerton", 2),
      q("Pacific Science Center's white arches were designed by…", ["Minoru Yamasaki", "I. M. Pei", "Paul Thiry", "Eero Saarinen"], "Minoru Yamasaki", 2),
      q("Seattle's oldest park, given to the city by a pioneer in 1861 as a cemetery, is…", ["Denny Park", "Volunteer Park", "Kinnear Park", "Cal Anderson Park"], "Denny Park", 2),
      q("Freeway Park, built as a lid over Interstate 5, was designed by…", ["Lawrence Halprin", "Frederick Law Olmsted", "Dan Kiley", "Isamu Noguchi"], "Lawrence Halprin", 2),
      q("Freeway Park opened on which date in 1976?", ["July 4", "Labor Day", "Memorial Day", "Thanksgiving"], "July 4", 3),
      q("Occidental Park sits in which historic neighborhood?", ["Pioneer Square", "Belltown", "Capitol Hill", "Fremont"], "Pioneer Square", 1),
      q("Hing Hay Park is in Seattle's…", ["International District", "University District", "Central District", "Rainier Valley"], "International District", 1),
      q("Hing Hay Park's ornate pavilion came from…", ["Taipei", "Beijing", "Kobe", "Busan"], "Taipei", 3),
      q("The Arctic Building is ringed with terra-cotta heads of…", ["walruses", "bears", "eagles", "whales"], "walruses", 2),
      q("Seattle Center's International Fountain was first built for…", ["the 1962 World's Fair", "the 1990 Goodwill Games", "the 1909 exposition", "the city's centennial"], "the 1962 World's Fair", 2),
      q("The Seattle Center Armory was built in 1939 as a…", ["National Guard armory", "streetcar repair barn", "salmon cannery", "rail freight depot"], "National Guard armory", 2),
      q("The Fremont Troll crouches under which bridge?", ["Aurora Bridge", "Ballard Bridge", "Fremont Bridge", "University Bridge"], "Aurora Bridge", 2),
      q("The Fremont Troll clutches a real…", ["Volkswagen Beetle", "Ford Model T", "Harley-Davidson", "rowboat"], "Volkswagen Beetle", 2),
      q("The Ballard Locks are officially named for…", ["Hiram M. Chittenden", "Arthur Denny", "George Vancouver", "Henry Yesler"], "Hiram M. Chittenden", 2),
      q("Gas Works Park sits on the north shore of…", ["Lake Union", "Lake Washington", "Green Lake", "Elliott Bay"], "Lake Union", 1),
      q("Kerry Park's famous skyline view is from which hill?", ["Queen Anne Hill", "Capitol Hill", "Beacon Hill", "First Hill"], "Queen Anne Hill", 2),
      q("Like Rome, Seattle is said to be built on how many hills?", ["seven", "five", "nine", "twelve"], "seven", 2),
      q("Downtown Seattle's waterfront faces which bay?", ["Elliott Bay", "Commencement Bay", "Bellingham Bay", "Shilshole Bay"], "Elliott Bay", 1),
      q("The State Route 99 tunnel under downtown opened in…", ["2019", "2011", "2015", "2023"], "2019", 2),
      q("The machine that bored the SR 99 tunnel was nicknamed…", ["Bertha", "Big Ben", "Molly", "Rosie"], "Bertha", 2),
      q("The SR 99 tunnel replaced which double-decked waterfront highway?", ["Alaskan Way Viaduct", "Aurora Bridge", "Mercer Street Ramp", "Elliott Avenue Overpass"], "Alaskan Way Viaduct", 2),
      q("When completed in 1914, Smith Tower was among the tallest skyscrapers outside…", ["New York City", "Chicago", "Philadelphia", "Pittsburgh"], "New York City", 2),
      q("Seattle's summer festival with hydroplane races and the Blue Angels is…", ["Seafair", "Bumbershoot", "Folklife", "Hempfest"], "Seafair", 1),
      q("The Seattle Aquarium on the waterfront opened in…", ["1977", "1962", "1989", "1998"], "1977", 2),
    ],
    history: [
      q("Who ran the steam sawmill at the heart of early Seattle's waterfront?", ["Henry Yesler", "Arthur Denny", "Doc Maynard", "Thomas Mercer"], "Henry Yesler", 2),
      q("The Great Seattle Fire of 1889 began in a…", ["cabinet shop", "hotel kitchen", "saloon", "ship's hold"], "cabinet shop", 3),
      q("After the 1889 fire, streets were raised a story, burying old storefronts now toured as the…", ["Seattle Underground", "Klondike Vault", "Yesler Cellars", "Elliott Tunnel"], "Seattle Underground", 2),
      q("Bill Speidel's walking tour, begun in 1965, takes visitors…", ["below Pioneer Square", "up the Space Needle", "around Lake Union", "through the ferry docks"], "below Pioneer Square", 2),
      q("The steamer Portland's 1897 arrival with 'a ton of gold' set off which rush through Seattle?", ["Klondike Gold Rush", "California Gold Rush", "Pikes Peak Gold Rush", "Fraser Canyon Gold Rush"], "Klondike Gold Rush", 1),
      q("The Klondike gold fields that Seattle outfitted stampeders for were in…", ["Yukon", "Alaska", "Montana", "Idaho"], "Yukon", 1),
      q("The 1962 Seattle World's Fair was officially called the…", ["Century 21 Exposition", "Expo 62", "Pacific Exposition", "Space Age Fair"], "Century 21 Exposition", 2),
      q("Seattle hosted which world's fair in 1909?", ["Alaska–Yukon–Pacific Exposition", "Lewis and Clark Exposition", "Panama–Pacific Exposition", "Trans-Mississippi Exposition"], "Alaska–Yukon–Pacific Exposition", 3),
      q("Architect Victor Steinbrueck led a 1971 citizens' vote to save…", ["Pike Place Market", "Smith Tower", "the Moore Theatre", "Union Station"], "Pike Place Market", 2),
      q("Waterfall Garden Park was built at the original building of which company?", ["UPS", "Boeing", "Nordstrom", "Starbucks"], "UPS", 2),
      q("Wing Luke, namesake of the Wing Luke Museum, was elected to Seattle's…", ["city council", "state senate", "school board", "port commission"], "city council", 2),
      q("Seattle-based Amazon was founded in 1994 by…", ["Jeff Bezos", "Bill Gates", "Howard Schultz", "Paul Allen"], "Jeff Bezos", 1),
      q("Boeing was founded in Seattle in…", ["1916", "1903", "1927", "1934"], "1916", 2),
      q("In 1942, many Japanese Americans from Seattle were first held at 'Camp Harmony' in…", ["Puyallup", "Yakima", "Spokane", "Bellingham"], "Puyallup", 2),
      q("Seattle was incorporated as a city in…", ["1869", "1851", "1889", "1853"], "1869", 3),
    ],
    sports: [
      q("Climate Pledge Arena's naming rights belong to…", ["Amazon", "Microsoft", "Boeing", "Starbucks"], "Amazon", 1),
      q("In Super Bowl XLVIII, the Seahawks beat the…", ["Denver Broncos", "New England Patriots", "Pittsburgh Steelers", "Carolina Panthers"], "Denver Broncos", 1),
      q("Seahawks fans call themselves the…", ["12th Man", "Dawg Pound", "Black Hole", "Cheeseheads"], "12th Man", 1),
      q("Lumen Field, home of the Seahawks, opened in…", ["2002", "1995", "2008", "1976"], "2002", 2),
      q("The domed stadium that stood where Lumen Field is now was the…", ["Kingdome", "Astrodome", "Metrodome", "Silverdome"], "Kingdome", 1),
      q("Lumen Field fans set a Guinness crowd-noise record in 2013 of…", ["137.6 decibels", "118.2 decibels", "126.4 decibels", "142.2 decibels"], "137.6 decibels", 3),
      q("The Mariners' ballpark opened in 1999 under the name…", ["Safeco Field", "Kingdome Park", "Sicks' Stadium", "Mariner Field"], "Safeco Field", 1),
      q("T-Mobile Park sits in which Seattle neighborhood?", ["SoDo", "Belltown", "Ballard", "Fremont"], "SoDo", 2),
      q("Ken Griffey Jr. finished his career with how many home runs?", ["630", "600", "660", "714"], "630", 3),
      q("Ichiro Suzuki set the MLB single-season hits record in…", ["2004", "2001", "2007", "1998"], "2004", 3),
      q("The 2001 Mariners tied the MLB record for regular-season wins with…", ["116", "108", "112", "104"], "116", 3),
      q("Mariners Hall of Famer Edgar Martínez is best known as a…", ["designated hitter", "closing pitcher", "shortstop", "catcher"], "designated hitter", 1),
      q("The Seattle Sounders won MLS Cup in 2016 and again in…", ["2019", "2014", "2021", "2010"], "2019", 2),
      q("The Sounders became the first MLS club to win the CONCACAF Champions League in…", ["2022", "2016", "2019", "2024"], "2022", 2),
      q("The Seattle Kraken's first NHL season was…", ["2021–22", "2018–19", "2023–24", "2015–16"], "2021–22", 2),
      q("The Seattle Storm play in the…", ["WNBA", "NWSL", "NBA G League", "PWHL"], "WNBA", 1),
      q("The SuperSonics left Seattle in 2008 and became the…", ["Oklahoma City Thunder", "Memphis Grizzlies", "New Orleans Pelicans", "Sacramento Kings"], "Oklahoma City Thunder", 1),
      q("The SuperSonics won their only NBA championship in…", ["1979", "1972", "1996", "1984"], "1979", 2),
      q("Seattle's one-season MLB team of 1969 was the…", ["Pilots", "Rainiers", "Angels", "Indians"], "Pilots", 3),
      q("After one season, the Seattle Pilots moved and became the…", ["Milwaukee Brewers", "Texas Rangers", "Kansas City Royals", "San Diego Padres"], "Milwaukee Brewers", 2),
      q("Washington Huskies football is played at…", ["Husky Stadium", "Lumen Field", "Martin Stadium", "Autzen Stadium"], "Husky Stadium", 1),
      q("Seattle Reign FC plays in the…", ["NWSL", "WNBA", "MLS", "USL"], "NWSL", 1),
      q("In 1917 the Seattle Metropolitans became the first U.S. team to win the…", ["Stanley Cup", "World Series", "Grey Cup", "Davis Cup"], "Stanley Cup", 3),
    ],
    arts: [
      q("Seattle Central Library was designed by Rem Koolhaas and…", ["Joshua Prince-Ramus", "Diller Scofidio", "Herzog & de Meuron", "Bjarke Ingels"], "Joshua Prince-Ramus", 3),
      q("Olympic Sculpture Park is run by the…", ["Seattle Art Museum", "Frye Art Museum", "Henry Art Gallery", "Wing Luke Museum"], "Seattle Art Museum", 1),
      q("Olympic Sculpture Park opened in…", ["2007", "1998", "2012", "2001"], "2007", 2),
      q("Alexander Calder's red steel sculpture at Olympic Sculpture Park is…", ["Eagle", "Flamingo", "Red Sun", "Phoenix"], "Eagle", 2),
      q("The giant moving sculpture outside the Seattle Art Museum is…", ["Hammering Man", "Walking Man", "Waving Girl", "Running Fence"], "Hammering Man", 1),
      q("Hammering Man at the Seattle Art Museum is the work of…", ["Jonathan Borofsky", "Claes Oldenburg", "Richard Serra", "Henry Moore"], "Jonathan Borofsky", 2),
      q("Benaroya Hall is the home of the…", ["Seattle Symphony", "Seattle Opera", "Pacific NW Ballet", "Seattle Men's Chorus"], "Seattle Symphony", 1),
      q("Benaroya Hall opened in…", ["1998", "1987", "2004", "1962"], "1998", 2),
      q("The Museum of Pop Culture was founded by Microsoft co-founder…", ["Paul Allen", "Bill Gates", "Steve Ballmer", "Nathan Myhrvold"], "Paul Allen", 1),
      q("MoPOP opened in 2000 under what original name?", ["Experience Music Project", "Seattle Music Hall", "Science Fiction Museum", "Northwest Rock Museum"], "Experience Music Project", 2),
      q("Chihuly Garden and Glass opened at Seattle Center in…", ["2012", "2004", "1998", "2016"], "2012", 2),
      q("Glass artist Dale Chihuly was born in…", ["Tacoma", "Spokane", "Portland", "Olympia"], "Tacoma", 2),
      q("The Moore Theatre, opened in 1907, is Seattle's…", ["oldest active theater", "largest concert hall", "only opera house", "first movie palace"], "oldest active theater", 2),
      q("The 5th Avenue Theatre's interior was modeled on…", ["Beijing's Forbidden City", "the Paris Opera", "a Venetian palazzo", "an Egyptian temple"], "Beijing's Forbidden City", 2),
      q("The Paramount Theatre on Pine Street opened in…", ["1928", "1914", "1939", "1950"], "1928", 2),
      q("Seattle's Sub Pop label released which band's debut album, Bleach?", ["Nirvana", "Pearl Jam", "Soundgarden", "Alice in Chains"], "Nirvana", 2),
      q("Pearl Jam's 1991 debut album is titled…", ["Ten", "Backspacer", "Yield", "Vitalogy"], "Ten", 2),
      q("Soundgarden's lead singer was…", ["Chris Cornell", "Eddie Vedder", "Layne Staley", "Kurt Cobain"], "Chris Cornell", 1),
      q("Jimi Hendrix was born in Seattle in…", ["1942", "1938", "1947", "1951"], "1942", 2),
      q("Jimi Hendrix is buried in which city just south of Seattle?", ["Renton", "Bellevue", "Tacoma", "Everett"], "Renton", 3),
      q("Before Seattle, Kurt Cobain grew up in…", ["Aberdeen", "Tacoma", "Olympia", "Spokane"], "Aberdeen", 2),
      q("Alice in Chains singer Layne Staley was born in…", ["Bellevue", "Spokane", "Everett", "Yakima"], "Bellevue", 2),
      q("Quincy Jones went to which Seattle high school?", ["Garfield", "Roosevelt", "Franklin", "Ballard"], "Garfield", 2),
      q("Sir Mix-a-Lot's 1992 No. 1 hit was…", ["Baby Got Back", "Ice Ice Baby", "Jump Around", "Rump Shaker"], "Baby Got Back", 1),
      q("Macklemore's 2012 breakout hit with Ryan Lewis was…", ["Thrift Shop", "Hotline Bling", "Uptown Funk", "Royals"], "Thrift Shop", 1),
      q("Psychiatrist Frasier Crane hosts his radio show in…", ["Seattle", "Boston", "Portland", "Denver"], "Seattle", 1),
      q("The 1993 film Sleepless in Seattle starred Tom Hanks and…", ["Meg Ryan", "Julia Roberts", "Sandra Bullock", "Sally Field"], "Meg Ryan", 1),
      q("Bumbershoot, held every Labor Day weekend, is a festival of…", ["music and arts", "hydroplane racing", "silent film", "craft brewing"], "music and arts", 1),
      q("Seattle Opera performs at…", ["McCaw Hall", "Benaroya Hall", "the Moore Theatre", "the Paramount"], "McCaw Hall", 2),
      q("Pacific Northwest Ballet shares McCaw Hall with the…", ["Seattle Opera", "Seattle Symphony", "Seattle Rep", "5th Avenue Theatre"], "Seattle Opera", 2),
      q("Seattle Repertory Theatre performs at…", ["Seattle Center", "Pioneer Square", "Westlake Center", "Pike Place Market"], "Seattle Center", 2),
      q("Northwest Folklife Festival takes over Seattle Center every…", ["Memorial Day weekend", "Labor Day weekend", "Fourth of July", "Thanksgiving weekend"], "Memorial Day weekend", 2),
      q("The Seattle Art Museum's Asian art collection is shown in which park?", ["Volunteer Park", "Discovery Park", "Gas Works Park", "Denny Park"], "Volunteer Park", 2),
    ],
    food: [
      q("The first Starbucks was founded by Gordon Bowker, Jerry Baldwin and…", ["Zev Siegl", "Howard Schultz", "Dave Olsen", "Paul Allen"], "Zev Siegl", 3),
      q("Starbucks opened its first store in Seattle in…", ["1971", "1966", "1979", "1985"], "1971", 2),
      q("Starbucks takes its name from a character in…", ["Moby-Dick", "Treasure Island", "Peter Pan", "The Odyssey"], "Moby-Dick", 1),
      q("Uwajimaya's founder first sold goods from a truck in…", ["Tacoma", "Spokane", "Bellingham", "Yakima"], "Tacoma", 3),
      q("Dick's Drive-In opened its first stand in Wallingford in…", ["1954", "1962", "1948", "1971"], "1954", 2),
      q("A Seattle-style hot dog is topped with…", ["cream cheese", "peanut butter", "pineapple", "coleslaw"], "cream cheese", 1),
      q("Ivar's seafood restaurants were founded by folk singer…", ["Ivar Haglund", "Ivar Lindqvist", "Ole Bardahl", "Eddie Bauer"], "Ivar Haglund", 2),
      q("Beecher's Handmade Cheese makes its cheese in view of shoppers at…", ["Pike Place Market", "Westlake Center", "Pioneer Square", "Seattle Center"], "Pike Place Market", 2),
      q("A giant red letter atop the old Rainier brewery was the letter…", ["R", "S", "B", "W"], "R", 2),
      q("Top Pot Doughnuts got its name from a neon sign salvaged from a…", ["Chinese restaurant", "bowling alley", "gas station", "motel"], "Chinese restaurant", 2),
      q("Theo Chocolate, in Fremont, was the first U.S. maker of chocolate that was organic and…", ["Fair Trade", "kosher", "sugar-free", "dairy-free"], "Fair Trade", 2),
      q("Washington leads the United States in growing…", ["apples", "oranges", "peaches", "pecans"], "apples", 1),
    ],
    political: [
      q("Seattle's current City Hall opened in…", ["2003", "1994", "2009", "1978"], "2003", 2),
      q("Bertha Knight Landes, elected in 1926, was the first woman mayor of…", ["a major U.S. city", "a U.S. state", "the U.S. Senate", "a U.S. port"], "a major U.S. city", 2),
      q("The Seattle General Strike of 1919 lasted about…", ["five days", "three weeks", "one day", "two months"], "five days", 3),
      q("The 1999 protests in Seattle targeted a meeting of the…", ["WTO", "G8", "IMF", "NATO"], "WTO", 1),
      q("Seattle's City Council has how many members?", ["nine", "seven", "eleven", "fifteen"], "nine", 2),
      q("Washington's state capital is…", ["Olympia", "Tacoma", "Spokane", "Seattle"], "Olympia", 1),
      q("Who was Seattle's first elected African American mayor?", ["Norm Rice", "Greg Nickels", "Charles Royer", "Paul Schell"], "Norm Rice", 2),
      q("The Port of Seattle was created by a public vote in…", ["1911", "1889", "1934", "1950"], "1911", 3),
      q("Which Seattle daily went online-only in 2009?", ["the Post-Intelligencer", "the Seattle Times", "The Stranger", "Seattle Weekly"], "the Post-Intelligencer", 2),
      q("Washington became a U.S. state in…", ["1889", "1876", "1859", "1912"], "1889", 2),
    ],
    nature: [
      q("Mount Rainier, seen from Seattle on clear days, is a…", ["stratovolcano", "shield volcano", "granite dome", "glacial moraine"], "stratovolcano", 1),
      q("Mount Rainier rises to about…", ["14,410 feet", "12,280 feet", "10,780 feet", "16,050 feet"], "14,410 feet", 2),
      q("Puget Sound reaches the Pacific through the Strait of…", ["Juan de Fuca", "Georgia", "Magellan", "Belle Isle"], "Juan de Fuca", 1),
      q("Salmon get past the Ballard Locks by way of a…", ["fish ladder", "fish elevator", "fish wheel", "trap net"], "fish ladder", 1),
      q("The SR 520 bridge across Lake Washington is the world's longest…", ["floating bridge", "suspension bridge", "cable-stayed span", "covered bridge"], "floating bridge", 2),
      q("Discovery Park, Seattle's largest city park, sits on which peninsula neighborhood?", ["Magnolia", "Ballard", "West Seattle", "Rainier Beach"], "Magnolia", 2),
      q("Washington's state tree, seen across Seattle's parks, is the…", ["western hemlock", "Douglas fir", "Sitka spruce", "bigleaf maple"], "western hemlock", 2),
      q("The king salmon sold at Seattle's fish stalls is also called…", ["Chinook", "Coho", "Sockeye", "Chum"], "Chinook", 2),
      q("The geoducks sold at Pike Place Market are giant…", ["clams", "crabs", "oysters", "snails"], "clams", 1),
      q("The 2001 earthquake that damaged the Alaskan Way Viaduct is named for…", ["Nisqually", "Cascadia", "Olympia", "Tacoma"], "Nisqually", 2),
    ],
  },
  denver: {
    local: [
      q("Denver's best-known nickname is the…", ["Mile High City", "Emerald City", "Windy City", "Magic City"], "Mile High City", 1),
      q("Denver grew up where Cherry Creek meets the…", ["South Platte River", "Arkansas River", "Colorado River", "Rio Grande"], "South Platte River", 2),
      q("A step on the Colorado State Capitol's west side marks an elevation of exactly…", ["one mile", "two miles", "half a mile", "1,000 feet"], "one mile", 1),
      q("The Capitol's interior is lined with rare Colorado rose onyx quarried near…", ["Beulah", "Leadville", "Aspen", "Golden"], "Beulah", 3),
      q("Denver Union Station reopened after its renovation in…", ["2014", "2008", "2019", "2001"], "2014", 2),
      q("RTD's A Line commuter train runs from Union Station to…", ["Denver International Airport", "the Boulder Turnpike park-n-ride", "the Colorado School of Mines", "Red Rocks Amphitheatre"], "Denver International Airport", 1),
      q("Denver International Airport opened in…", ["1995", "1989", "2001", "1976"], "1995", 2),
      q("DIA's peaked white tent roof is meant to recall…", ["snowcapped mountains", "rolling ocean waves", "golden wheat fields", "circus big tops"], "snowcapped mountains", 2),
      q("The 16th Street Mall was designed by the firm of…", ["I. M. Pei", "Michael Graves", "Daniel Libeskind", "Gio Ponti"], "I. M. Pei", 2),
      q("The free buses that run the length of the 16th Street Mall are the…", ["MallRide", "FreeLine", "Mile Shuttle", "Denver Loop"], "MallRide", 2),
      q("When finished in 1910, the Daniels & Fisher Tower was the tallest building between the Mississippi River and…", ["California", "Nebraska", "Missouri", "Oklahoma"], "California", 2),
      q("The Brown Palace Hotel opened in…", ["1892", "1876", "1906", "1921"], "1892", 2),
      q("The Brown Palace Hotel is built in the shape of a…", ["triangle", "circle", "cross", "horseshoe"], "triangle", 1),
      q("The Central Library's 1995 expansion was designed by…", ["Michael Graves", "Frank Gehry", "Philip Johnson", "Robert Venturi"], "Michael Graves", 2),
      q("The Denver Mint struck its first coins in…", ["1906", "1876", "1892", "1921"], "1906", 2),
      q("How many schools share Denver's Auraria Campus?", ["three", "two", "four", "five"], "three", 2),
      q("In Denver, the 'Denver boot' is a…", ["wheel clamp", "cowboy boot", "ski binding", "snowshoe"], "wheel clamp", 1),
      q("The Oxford Hotel near Union Station opened in…", ["1891", "1876", "1906", "1921"], "1891", 2),
      q("The Equitable Building on 17th Street was completed in…", ["1892", "1876", "1910", "1925"], "1892", 3),
      q("The Molly Brown House Museum is also known as the House of…", ["Lions", "Eagles", "Bears", "Roses"], "Lions", 2),
      q("Denver's Civic Center became a National Historic Landmark in 2012 as a showcase of the…", ["City Beautiful movement", "Prairie School", "Arts and Crafts movement", "Art Deco era"], "City Beautiful movement", 3),
      q("Sakura Square sits at 19th Street and…", ["Larimer Street", "Blake Street", "Wazee Street", "Market Street"], "Larimer Street", 3),
      q("The Denver Firefighters Museum is housed in the former…", ["Fire Station No. 1", "City Hall Annex", "Union Depot", "Mint Annex"], "Fire Station No. 1", 2),
      q("Denver's Downtown Aquarium was originally called…", ["Colorado's Ocean Journey", "Platte River Aquarium", "Rocky Mountain Sea World", "Mile High Aquarium"], "Colorado's Ocean Journey", 2),
      q("The Denver Museum of Nature & Science is an affiliate of the…", ["Smithsonian Institution", "Field Museum", "American Museum of Natural History", "National Geographic Society"], "Smithsonian Institution", 2),
      q("Denver Union Station stands at 17th Street and…", ["Wynkoop Street", "Larimer Street", "Colfax Avenue", "Broadway"], "Wynkoop Street", 1),
      q("The first station on Union Station's site opened in 1881 and later…", ["burned down", "was flooded", "was moved", "was sold"], "burned down", 3),
      q("The hotel inside Denver Union Station's historic building is the…", ["Crawford Hotel", "Union Hotel", "Larimer Inn", "Wazee Lodge"], "Crawford Hotel", 2),
      q("Beneath Union Station's plaza lies an underground…", ["bus station", "shopping mall", "parking garage", "rail museum"], "bus station", 2),
      q("The Colorado Convention Center opened in…", ["1990", "1979", "2001", "1995"], "1990", 2),
      q("At the 2020 census, Denver's population was about…", ["715,000", "515,000", "915,000", "1.2 million"], "715,000", 2),
      q("Commons Park holds an AIDS memorial called…", ["The Grove", "The Garden", "The Circle", "The Path"], "The Grove", 2),
      q("The ten-county Denver metro area is home to about…", ["3.1 million people", "1.4 million people", "5.6 million people", "800,000 people"], "3.1 million people", 2),
      q("The Denver Firefighters Museum's home, Fire Station No. 1, was built in…", ["1909", "1889", "1931", "1952"], "1909", 3),
    ],
    history: [
      q("Denver is named for James W. Denver, governor of…", ["Kansas Territory", "Colorado Territory", "Nebraska Territory", "Missouri"], "Kansas Territory", 2),
      q("Denver was founded in 1858 during which gold rush?", ["Pikes Peak Gold Rush", "Klondike Gold Rush", "California Gold Rush", "Black Hills Gold Rush"], "Pikes Peak Gold Rush", 2),
      q("Denver City was laid out in 1858 by a party led by…", ["William Larimer", "Horace Tabor", "John Evans", "Kit Carson"], "William Larimer", 3),
      q("Larimer Square was saved from the wrecking ball in the 1960s by preservationist…", ["Dana Crawford", "Molly Brown", "Clara Brown", "Elizabeth Byers"], "Dana Crawford", 3),
      q("The Brown Palace Hotel was designed by architect…", ["Frank Edbrooke", "Frank Lloyd Wright", "Gio Ponti", "Henry Cobb"], "Frank Edbrooke", 3),
      q("Denver's Margaret 'Molly' Brown is remembered as a survivor of…", ["the Titanic", "the Lusitania", "the Andrea Doria", "the Johnstown Flood"], "the Titanic", 1),
      q("Auraria, the settlement on the west bank of Cherry Creek, was named for a town in…", ["Georgia", "Kansas", "Ohio", "Missouri"], "Georgia", 3),
      q("The 1864 Sand Creek massacre was led by U.S. Army colonel…", ["John Chivington", "George Custer", "Kit Carson", "Philip Sheridan"], "John Chivington", 3),
      q("When gold seekers founded Denver, which people's lands were they on?", ["Arapaho", "Navajo", "Hopi", "Seminole"], "Arapaho", 2),
      q("In 1870 the Denver Pacific Railway linked Denver to the transcontinental line at…", ["Cheyenne", "Kansas City", "Santa Fe", "Omaha"], "Cheyenne", 2),
      q("The Moffat Tunnel carries trains under the…", ["Continental Divide", "Rio Grande", "Pikes Peak", "Great Salt Lake"], "Continental Divide", 2),
      q("Denver's oldest standing church building, now Emmanuel Gallery, was later used as a…", ["synagogue", "firehouse", "library", "school"], "synagogue", 3),
      q("Denver's Cathedral of the Immaculate Conception was raised to a minor basilica in…", ["1979", "1912", "1993", "2001"], "1979", 2),
      q("The Byers–Evans House now holds History Colorado's center for the history of…", ["Colorado women", "silver mining", "the railroads", "ski resorts"], "Colorado women", 3),
      q("Sakura Square has a bust of Minoru Yasui, a Japanese American…", ["lawyer", "baseball star", "architect", "senator"], "lawyer", 2),
      q("Clara Brown, a Colorado gold rush pioneer, was called the Angel of the…", ["Rockies", "Plains", "Prairie", "Frontier"], "Rockies", 2),
      q("Clara Brown reached Denver working as a cook on a…", ["wagon train", "steamboat", "railroad crew", "cattle drive"], "wagon train", 3),
      q("Barney Ford argued Colorado shouldn't become a state until all men could…", ["vote", "own land", "serve on juries", "hold office"], "vote", 3),
      q("Barney Ford was especially keen on opening barbershops, restaurants and…", ["hotels", "banks", "saloons", "theaters"], "hotels", 2),
      q("Horace Tabor, the Silver King, made his fortune from mines in…", ["Leadville", "Cripple Creek", "Aspen", "Telluride"], "Leadville", 2),
      q("Horace Tabor's second wife, Elizabeth, was better known as…", ["Baby Doe", "Molly Brown", "Calamity Jane", "Silver Belle"], "Baby Doe", 2),
      q("Horace Tabor was ruined by the silver collapse in the Panic of…", ["1893", "1873", "1907", "1857"], "1893", 3),
      q("Baby Doe Tabor was born in…", ["Oshkosh, Wisconsin", "Dublin, Ireland", "St. Louis, Missouri", "Leadville, Colorado"], "Oshkosh, Wisconsin", 3),
      q("Which Colorado silver town is the highest incorporated city in the U.S.?", ["Leadville", "Aspen", "Telluride", "Breckenridge"], "Leadville", 2),
      q("In August 1993 Denver hosted the Catholic Church's…", ["World Youth Day", "Eucharistic Congress", "Synod of Bishops", "Jubilee Mass"], "World Youth Day", 2),
      q("In 1870 the Kansas Pacific Railway linked Denver by rail to…", ["Kansas City", "St. Louis", "Omaha", "Chicago"], "Kansas City", 2),
      q("About how many gold seekers took part in the Pikes Peak gold rush?", ["100,000", "10,000", "1 million", "25,000"], "100,000", 2),
    ],
    sports: [
      q("Coors Field opened in…", ["1995", "1993", "1999", "2001"], "1995", 2),
      q("Coors Field's mile-high line of purple seats is in row…", ["20", "5", "42", "1"], "20", 3),
      q("Coors Field sits in which Denver district?", ["LoDo", "RiNo", "Five Points", "Cherry Creek"], "LoDo", 1),
      q("The Colorado Rockies played their first season in…", ["1993", "1990", "1998", "1977"], "1993", 2),
      q("The Rockies' only World Series appearance came in…", ["2007", "1995", "2009", "2017"], "2007", 2),
      q("Todd Helton spent his whole MLB career with the Rockies as a…", ["first baseman", "catcher", "shortstop", "center fielder"], "first baseman", 1),
      q("The Broncos won Super Bowl 50 over the…", ["Carolina Panthers", "Seattle Seahawks", "Atlanta Falcons", "Green Bay Packers"], "Carolina Panthers", 1),
      q("Which quarterback led the Broncos to back-to-back Super Bowl wins after the 1997 and 1998 seasons?", ["John Elway", "Peyton Manning", "Craig Morton", "Jake Plummer"], "John Elway", 1),
      q("Old Mile High Stadium opened in 1948 under the name…", ["Bears Stadium", "Broncos Field", "Denver Coliseum", "Elway Field"], "Bears Stadium", 3),
      q("Empower Field at Mile High opened in…", ["2001", "1995", "2008", "1976"], "2001", 2),
      q("Nikola Jokić led the Nuggets to their first NBA title in…", ["2023", "2019", "2021", "2025"], "2023", 1),
      q("Nuggets star Nikola Jokić comes from…", ["Serbia", "Croatia", "Greece", "Slovenia"], "Serbia", 1),
      q("The Nuggets and the Avalanche share…", ["Ball Arena", "Coors Field", "Empower Field", "Dick's Sporting Goods Park"], "Ball Arena", 1),
      q("Before 2020, Ball Arena was named the…", ["Pepsi Center", "McNichols Arena", "Coors Center", "Mile High Arena"], "Pepsi Center", 2),
      q("The Colorado Avalanche moved to Denver in 1995 from…", ["Quebec City", "Hartford", "Winnipeg", "Atlanta"], "Quebec City", 2),
      q("The Avalanche won the Stanley Cup in 1996, 2001 and…", ["2022", "2008", "2014", "2018"], "2022", 2),
      q("The Colorado Rapids play in…", ["MLS", "NWSL", "the NHL", "the NBA"], "MLS", 1),
      q("The Colorado Mammoth play professional…", ["box lacrosse", "rugby league", "roller hockey", "indoor soccer"], "box lacrosse", 2),
      q("The University of Denver Pioneers have won many national titles in…", ["ice hockey", "football", "rowing", "baseball"], "ice hockey", 2),
      q("Ball Arena opened in…", ["1999", "1990", "2004", "1995"], "1999", 2),
      q("The Broncos began play in 1960 as a charter member of the…", ["American Football League", "All-America Football Conference", "World Football League", "United States Football League"], "American Football League", 2),
      q("Before becoming the Nuggets in 1974, Denver's ABA team was called the…", ["Rockets", "Pioneers", "Bears", "Miners"], "Rockets", 2),
      q("John Elway's famous 98-yard march known as The Drive came against the…", ["Cleveland Browns", "Pittsburgh Steelers", "Oakland Raiders", "Buffalo Bills"], "Cleveland Browns", 2),
      q("To tame the thin air, baseballs used at Coors Field are stored in a…", ["humidor", "freezer", "pressure tank", "vault"], "humidor", 2),
      q("Workers building Coors Field dug up fossils of…", ["dinosaurs", "mammoths", "sabre-toothed cats", "giant sloths"], "dinosaurs", 2),
      q("Coors Field's fences were pushed back, giving it the MLB's largest…", ["outfield", "scoreboard", "dugouts", "bullpen"], "outfield", 2),
      q("Broncos quarterback Peyton Manning was nicknamed…", ["the Sheriff", "the Gunslinger", "the Mailman", "the Bus"], "the Sheriff", 1),
      q("Before the NFL, Peyton Manning played college football for…", ["Tennessee", "Ole Miss", "LSU", "Alabama"], "Tennessee", 2),
    ],
    arts: [
      q("The fiery-eyed horse at DIA, nicknamed 'Blucifer', is officially titled…", ["Blue Mustang", "Big Blue Bear", "Bronco Buster", "Blue Stallion"], "Blue Mustang", 2),
      q("Blue Mustang's sculptor, Luis Jiménez, died in 2006 when part of it…", ["fell on him", "caught fire", "was struck by lightning", "tipped off a truck"], "fell on him", 3),
      q("The Big Blue Bear peering into the Colorado Convention Center is officially titled…", ["I See What You Mean", "Peek-a-Boo", "Blue Visitor", "Bear Necessities"], "I See What You Mean", 2),
      q("The Big Blue Bear was created by artist…", ["Lawrence Argent", "Luis Jiménez", "Jeff Koons", "Claes Oldenburg"], "Lawrence Argent", 3),
      q("The 1960 Broadway musical about Margaret Brown is…", ["The Unsinkable Molly Brown", "Titanic Molly", "Molly of the Mile High", "Brown Palace Nights"], "The Unsinkable Molly Brown", 2),
      q("The Clyfford Still Museum opened in…", ["2011", "2003", "1999", "2016"], "2011", 2),
      q("Clyfford Still was a leading painter of…", ["Abstract Expressionism", "Photorealism", "Post-Impressionism", "Synthetic Cubism"], "Abstract Expressionism", 2),
      q("The Denver Art Museum's 1971 North Building was designed by Italian architect…", ["Gio Ponti", "Renzo Piano", "Aldo Rossi", "Carlo Scarpa"], "Gio Ponti", 2),
      q("The Denver Art Museum's angular Hamilton Building opened in…", ["2006", "1999", "2012", "1995"], "2006", 2),
      q("The Hamilton Building's shards are clad in…", ["titanium", "copper", "glass brick", "limestone"], "titanium", 2),
      q("Red Rocks Amphitheatre stands in which town west of Denver?", ["Morrison", "Golden", "Boulder", "Aurora"], "Morrison", 2),
      q("Red Rocks Amphitheatre is owned by…", ["the City and County of Denver", "Jefferson County", "the State of Colorado", "the National Park Service"], "the City and County of Denver", 2),
      q("Within the Denver Performing Arts Complex, which venue is designed for amplified musicals?", ["Buell Theatre", "Boettcher Concert Hall", "Ellie Caulkins Opera House", "Space Theatre"], "Buell Theatre", 2),
      q("Boettcher Concert Hall was the first U.S. symphony hall built…", ["in the round", "underground", "outdoors", "on a pier"], "in the round", 2),
      q("Boettcher Concert Hall is home to the…", ["Colorado Symphony", "Colorado Ballet", "Opera Colorado", "Denver Center Theatre"], "Colorado Symphony", 2),
      q("Denver's Paramount Theatre is decorated in which style?", ["Art Deco", "Gothic Revival", "Beaux-Arts", "Brutalist"], "Art Deco", 1),
      q("The view from Pikes Peak inspired which song?", ["America the Beautiful", "Rocky Mountain High", "Home on the Range", "This Land Is Your Land"], "America the Beautiful", 2),
      q("Which Denver street was called 'the longest, wickedest street in America'?", ["Colfax Avenue", "Larimer Street", "Federal Boulevard", "Speer Boulevard"], "Colfax Avenue", 2),
      q("Denver's Tattered Cover is a well-known…", ["bookstore", "jazz club", "brewpub", "theater"], "bookstore", 1),
      q("Which Jack Kerouac novel has its characters passing through Denver?", ["On the Road", "The Dharma Bums", "Big Sur", "Desolation Angels"], "On the Road", 1),
      q("Jazz-era Five Points was nicknamed the Harlem of the…", ["West", "Rockies", "Plains", "Frontier"], "West", 2),
      q("John Denver's 1972 ode to Colorado is…", ["Rocky Mountain High", "Take Me Home, Country Roads", "Annie's Song", "Leaving on a Jet Plane"], "Rocky Mountain High", 1),
      q("The Museum of Contemporary Art Denver building was designed by…", ["David Adjaye", "Daniel Libeskind", "Frank Gehry", "Steven Holl"], "David Adjaye", 2),
      q("The History Colorado Center on Broadway opened in…", ["2012", "2004", "2017", "1999"], "2012", 2),
      q("The pond at the Voorhies Memorial holds a sculpture of a…", ["sea lion", "buffalo", "bear cub", "trout"], "sea lion", 2),
      q("The Voorhies Memorial's murals were painted by…", ["Allen Tupper True", "Thomas Moran", "Albert Bierstadt", "Vance Kirkland"], "Allen Tupper True", 3),
      q("Colfax Avenue's Ogden Theatre was built in…", ["1917", "1928", "1906", "1939"], "1917", 2),
      q("Colfax Avenue's Bluebird Theater was originally known as the…", ["Thompson Theater", "Isis Theater", "Orpheum", "Tabor Grand"], "Thompson Theater", 3),
      q("In 2024, Denver's Tattered Cover bookstore chain became part of…", ["Barnes & Noble", "Amazon", "Books-A-Million", "Powell's"], "Barnes & Noble", 2),
      q("The Denver Performing Arts Complex's ten venues are joined by a glass roof that is…", ["80 feet tall", "20 feet tall", "150 feet tall", "300 feet tall"], "80 feet tall", 2),
      q("The Denver Center for the Performing Arts was founded in 1972 by…", ["Donald Seawell", "Frederick Bonfils", "Temple Buell", "Ellie Caulkins"], "Donald Seawell", 3),
    ],
    food: [
      q("Wynkoop Brewing Company was co-founded by which future Denver mayor?", ["John Hickenlooper", "Federico Peña", "Wellington Webb", "Michael Hancock"], "John Hickenlooper", 1),
      q("Wynkoop Brewing Company opened in…", ["1988", "1976", "1995", "2002"], "1988", 2),
      q("Denver's Great American Beer Festival is put on by the…", ["Brewers Association", "Coors family", "Colorado legislature", "Denver Zoo"], "Brewers Association", 2),
      q("Coors beer is brewed in which town just west of Denver?", ["Golden", "Boulder", "Morrison", "Lakewood"], "Golden", 1),
      q("A Denver omelette is filled with ham, onions and…", ["green peppers", "mushrooms", "sweet corn", "tomatoes"], "green peppers", 1),
      q("Rocky Mountain oysters are actually…", ["bull testicles", "fried trout", "pickled onions", "quail eggs"], "bull testicles", 1),
      q("Casa Bonita, the pink palace in Lakewood, is famous for its indoor…", ["cliff divers", "ski slope", "roller rink", "rodeo arena"], "cliff divers", 1),
      q("Casa Bonita was bought in 2021 by the creators of…", ["South Park", "The Simpsons", "Family Guy", "Seinfeld"], "South Park", 1),
      q("The Downtown Aquarium and its restaurant are owned by…", ["Landry's", "Darden", "Sysco", "Yum! Brands"], "Landry's", 2),
    ],
    political: [
      q("Denver is the capital of…", ["Colorado", "Wyoming", "Utah", "Kansas"], "Colorado", 1),
      q("Colorado joined the Union a century after 1776, earning which nickname?", ["Centennial State", "Silver State", "Mountain State", "Pioneer State"], "Centennial State", 1),
      q("Denver's City and County Building was completed in…", ["1932", "1908", "1956", "1919"], "1932", 2),
      q("The Denver Post was founded in…", ["1892", "1859", "1920", "1946"], "1892", 3),
      q("The Rocky Mountain News, first printed in 1859, stopped publishing in…", ["2009", "1999", "2015", "1972"], "2009", 2),
      q("The Rocky Mountain News was founded by…", ["William Byers", "Horace Greeley", "William Larimer", "John Evans"], "William Byers", 2),
      q("Federico Peña, Denver's mayor from 1983, later became U.S. Secretary of…", ["Transportation", "Defense", "Labor", "the Interior"], "Transportation", 2),
      q("Who was Denver's first African American mayor?", ["Wellington Webb", "Federico Peña", "Michael Hancock", "John Hickenlooper"], "Wellington Webb", 2),
      q("After serving as Denver's mayor and Colorado's governor, John Hickenlooper became a…", ["U.S. senator", "Supreme Court justice", "cabinet secretary", "U.S. ambassador"], "U.S. senator", 2),
      q("At the 2008 Democratic convention in Denver, the presidential nominee was…", ["Barack Obama", "Hillary Clinton", "John Kerry", "Joe Biden"], "Barack Obama", 1),
      q("Denver's mayor serves a term of…", ["four years", "two years", "six years", "three years"], "four years", 2),
      q("Denver was awarded the 1976 Winter Olympics and then…", ["turned them down", "hosted them", "shared them with Utah", "moved them to Aspen"], "turned them down", 2),
      q("Colorado became a U.S. state in…", ["1876", "1861", "1889", "1912"], "1876", 2),
      q("Colorado Territory was organized in…", ["1861", "1876", "1858", "1848"], "1861", 3),
    ],
    nature: [
      q("The tilted red sandstone at Red Rocks belongs to the…", ["Fountain Formation", "Navajo Sandstone", "Coconino Sandstone", "Kayenta Formation"], "Fountain Formation", 3),
      q("The Denver Zoo is in…", ["City Park", "Washington Park", "Civic Center Park", "Cheesman Park"], "City Park", 1),
      q("Colorado's state flower is the…", ["Rocky Mountain columbine", "western pasqueflower", "prairie wild rose", "Indian paintbrush"], "Rocky Mountain columbine", 2),
      q("Colorado's highest peak is…", ["Mount Elbert", "Pikes Peak", "Longs Peak", "Mount Blue Sky"], "Mount Elbert", 2),
      q("Denver's official elevation is about…", ["5,280 feet", "4,280 feet", "6,280 feet", "7,280 feet"], "5,280 feet", 1),
      q("The South Platte joins the North Platte in which state?", ["Nebraska", "Kansas", "Wyoming", "Iowa"], "Nebraska", 2),
      q("The Denver Botanic Gardens sit in which neighborhood?", ["Cheesman Park", "Five Points", "Highland", "Baker"], "Cheesman Park", 2),
      q("Leadville sits between Colorado's two tallest peaks, Mount Elbert and…", ["Mount Massive", "Pikes Peak", "Longs Peak", "Mount Evans"], "Mount Massive", 3),
    ],
  },
  nashville: {
    local: [
      q("Nashville's best-known nickname is…", ["Music City", "Magnolia City", "River City", "Gem City"], "Music City", 1),
      q("Because of its many colleges, Nashville is sometimes called the Athens of the…", ["South", "West", "Plains", "Mississippi"], "South", 2),
      q("Nashville sits on which river?", ["Cumberland River", "Tennessee River", "Ohio River", "Duck River"], "Cumberland River", 1),
      q("At the 2020 census, Nashville's population was about…", ["689,000", "389,000", "989,000", "1.3 million"], "689,000", 2),
      q("The Ryman Auditorium is nicknamed the Mother Church of…", ["Country Music", "Bluegrass", "Rock and Roll", "Gospel Song"], "Country Music", 1),
      q("WSM's call letters come from the motto…", ["We Shield Millions", "We Sing Music", "World's Southern Music", "Wonderful South Melodies"], "We Shield Millions", 2),
      q("WSM radio was started in 1925 by a company that sold…", ["life insurance", "farm machinery", "radio sets", "sewing machines"], "life insurance", 3),
      q("WSM broadcasts at which AM frequency?", ["650 kHz", "1510 kHz", "880 kHz", "1070 kHz"], "650 kHz", 2),
      q("The Opryland USA theme park operated from 1972 until…", ["1997", "1985", "2004", "2010"], "1997", 2),
      q("Gaylord Opryland Resort was formerly called the…", ["Opryland Hotel", "Ryman Hotel", "Music City Inn", "Cumberland Lodge"], "Opryland Hotel", 2),
      q("Lower Broadway's historic district is nicknamed Honky Tonk…", ["Highway", "Heaven", "Avenue", "Central"], "Highway", 2),
      q("Tootsie's Orchid Lounge stands just behind the…", ["Ryman Auditorium", "Bridgestone Arena", "Country Music Hall of Fame", "Schermerhorn Symphony Center"], "Ryman Auditorium", 2),
      q("Music Row is centered on 16th and 17th Avenues…", ["South", "North", "East", "West"], "South", 2),
      q("Bicentennial Capitol Mall is modeled on the…", ["National Mall", "Champs-Élysées", "Boston Common", "Central Park"], "National Mall", 2),
      q("Bicentennial Mall is the most visited of Tennessee's…", ["state parks", "museums", "zoos", "colleges"], "state parks", 2),
      q("The Tennessee State Museum's new building opened in…", ["2018", "2006", "1996", "2012"], "2018", 2),
      q("Centennial Park sits across West End Avenue from…", ["Vanderbilt University", "Fisk University", "Belmont University", "Lipscomb University"], "Vanderbilt University", 2),
      q("Jefferson Street declined after which highway was built across it in 1968?", ["Interstate 40", "Interstate 65", "Interstate 24", "Briley Parkway"], "Interstate 40", 2),
      q("The Hermitage Hotel was named for…", ["Andrew Jackson's estate", "a Catholic monastery", "a Russian art museum", "an English country inn"], "Andrew Jackson's estate", 2),
      q("The Hermitage Hotel opened in…", ["1910", "1897", "1925", "1948"], "1910", 2),
      q("The Hermitage Hotel is Tennessee's only remaining commercial building in which style?", ["Beaux-Arts", "Art Deco", "Gothic Revival", "Prairie"], "Beaux-Arts", 3),
      q("The Batman Building is the tallest building in…", ["Tennessee", "the South", "the U.S.", "Kentucky"], "Tennessee", 1),
      q("The Batman Building was completed in…", ["1994", "1972", "2008", "1986"], "1994", 2),
      q("Nashville's Union Station opened in…", ["1900", "1880", "1925", "1912"], "1900", 2),
      q("Nashville's Union Station is built in which style?", ["Romanesque Revival", "Spanish Colonial Revival", "Beaux-Arts", "Art Deco"], "Romanesque Revival", 3),
      q("The John Seigenthaler Pedestrian Bridge was formerly the…", ["Shelby Street Bridge", "Woodland Street Bridge", "Victory Memorial Bridge", "Jefferson Street Bridge"], "Shelby Street Bridge", 2),
      q("Nashville International Airport's code BNA comes from its original name…", ["Berry Field", "Bell Meade Field", "Bordeaux Airport", "Broadway Airfield"], "Berry Field", 2),
      q("The Lane Motor Museum mostly collects cars from…", ["Europe", "Japan", "South America", "Australia"], "Europe", 3),
    ],
    history: [
      q("Nashville is named for Francis Nash, a general in the…", ["Continental Army", "Confederate Army", "War of 1812", "Mexican War"], "Continental Army", 2),
      q("Nashville was founded in 1779, when its land was still part of…", ["North Carolina", "South Carolina", "Virginia", "Kentucky"], "North Carolina", 2),
      q("In 1862 Nashville became the first Confederate state capital to be…", ["taken by Union forces", "burned to the ground", "moved to Memphis", "struck by an earthquake"], "taken by Union forces", 2),
      q("Nashville was incorporated as a city in…", ["1806", "1779", "1843", "1796"], "1806", 2),
      q("Fort Nashborough, the 1779 stockade, was founded by James Robertson and…", ["John Donelson", "Daniel Boone", "Davy Crockett", "John Sevier"], "John Donelson", 2),
      q("Fort Nashborough stood in a salt-spring area known as the…", ["French Lick", "Big Bone Lick", "Salt Bluff", "Indian Spring"], "French Lick", 3),
      q("Nashville co-founder James Robertson was an early companion of…", ["Daniel Boone", "Davy Crockett", "Kit Carson", "Meriwether Lewis"], "Daniel Boone", 2),
      q("Thomas Ryman, who built the tabernacle, owned saloons and a fleet of…", ["riverboats", "streetcars", "stagecoaches", "cotton gins"], "riverboats", 3),
      q("The Parthenon was first built for the Tennessee Centennial Exposition in…", ["1897", "1876", "1912", "1925"], "1897", 2),
      q("Before the 1897 exposition, the Centennial Park site was used as a…", ["racetrack", "cemetery", "rail yard", "Civil War fort"], "racetrack", 3),
      q("The Parthenon was rebuilt in steel and concrete between 1925 and…", ["1931", "1941", "1927", "1952"], "1931", 3),
      q("Vandy's founding $1 million gift came from shipping and railroad magnate…", ["Cornelius Vanderbilt", "John Jacob Astor", "Andrew Carnegie", "Leland Stanford"], "Cornelius Vanderbilt", 2),
      q("Vanderbilt University was founded in…", ["1873", "1836", "1901", "1911"], "1873", 2),
      q("Fisk University was founded in…", ["1866", "1901", "1837", "1888"], "1866", 2),
      q("Tennessee State University, a historically Black school, was founded in…", ["1912", "1866", "1950", "1890"], "1912", 2),
      q("Belmont University grew out of a women's college founded in…", ["1890", "1851", "1925", "1960"], "1890", 2),
      q("Diane Nash chaired which group during the 1960 sit-ins?", ["Nashville Student Movement", "Congress of Racial Equality", "Southern Christian Leadership Conference", "National Urban League"], "Nashville Student Movement", 2),
      q("The 1960 Nashville sit-ins targeted segregated…", ["lunch counters", "city buses", "public schools", "swimming pools"], "lunch counters", 2),
      q("During the sit-ins, whose home was bombed on April 19, 1960?", ["Z. Alexander Looby", "Kelly Miller Smith", "James Lawson", "C. T. Vivian"], "Z. Alexander Looby", 3),
      q("After a 1960 march to City Hall, which mayor agreed the lunch counters should be desegregated?", ["Ben West", "Beverly Briley", "Richard Fulton", "Bill Boner"], "Ben West", 2),
      q("The Hermitage was the home of which president?", ["Andrew Jackson", "James K. Polk", "Andrew Johnson", "Thomas Jefferson"], "Andrew Jackson", 1),
      q("Andrew Jackson was which U.S. president?", ["7th", "11th", "3rd", "16th"], "7th", 2),
      q("James K. Polk, buried in Nashville, was which U.S. president?", ["11th", "7th", "15th", "3rd"], "11th", 2),
      q("Polk Place, the Polks' Nashville home, was demolished in…", ["1901", "1865", "1931", "1950"], "1901", 3),
      q("Belle Meade Plantation became famous for breeding…", ["thoroughbred racehorses", "Tennessee walking horses", "prize Angus cattle", "Merino sheep"], "thoroughbred racehorses", 2),
      q("The name Belle Meade means…", ["beautiful meadow", "fair green valley", "pretty hillside", "good spring water"], "beautiful meadow", 3),
      q("Belle Meade's most celebrated stallion was…", ["Iroquois", "Secretariat", "Seabiscuit", "Man o' War"], "Iroquois", 3),
      q("The Battle of Nashville in December 1864 was won by Union general…", ["George H. Thomas", "Ulysses S. Grant", "William T. Sherman", "Don Carlos Buell"], "George H. Thomas", 2),
      q("Fort Negley was the largest inland fort built during the…", ["Civil War", "War of 1812", "Revolution", "Mexican War"], "Civil War", 2),
    ],
    sports: [
      q("The Nashville Sounds baseball team is named for…", ["the Nashville sound", "the city's bells", "a riverboat whistle", "a radio jingle"], "the Nashville sound", 2),
      q("Vanderbilt is the only private school in which athletic conference?", ["Southeastern Conference", "Atlantic Coast Conference", "Big Ten Conference", "Sun Belt Conference"], "Southeastern Conference", 2),
      q("The Tennessee Titans were originally the…", ["Houston Oilers", "Dallas Texans", "Memphis Showboats", "Kansas City Chiefs"], "Houston Oilers", 1),
      q("The Oilers became the Titans in…", ["1999", "1997", "2002", "1994"], "1999", 2),
      q("While their Nashville stadium was built, the Oilers' 1997 home games were played in…", ["Memphis", "Knoxville", "Chattanooga", "Clarksville"], "Memphis", 2),
      q("The Titans lost Super Bowl XXXIV to the…", ["St. Louis Rams", "Dallas Cowboys", "Buffalo Bills", "Green Bay Packers"], "St. Louis Rams", 1),
      q("In the Music City Miracle, Frank Wycheck lateraled to…", ["Kevin Dyson", "Eddie George", "Steve McNair", "Derrick Mason"], "Kevin Dyson", 2),
      q("The Music City Miracle beat which team?", ["Buffalo Bills", "Miami Dolphins", "Indianapolis Colts", "Jacksonville Jaguars"], "Buffalo Bills", 2),
      q("Nissan Stadium's first name was…", ["Adelphia Coliseum", "LP Field", "Titans Field", "Vanderbilt Stadium"], "Adelphia Coliseum", 2),
      q("Nissan Stadium sits on which bank of the Cumberland River?", ["east", "west", "north", "south"], "east", 2),
      q("Which college bowl game is played at Nissan Stadium each December?", ["Music City Bowl", "Holiday Bowl", "Birmingham Bowl", "Independence Bowl"], "Music City Bowl", 2),
      q("The Predators' logo is a…", ["saber-toothed cat", "prowling mountain lion", "leaping catfish", "snarling bobcat"], "saber-toothed cat", 2),
      q("The Smilodon skeleton behind the Predators' logo was found…", ["beneath downtown", "in a cave at Radnor Lake", "at the Hermitage", "in the Cumberland River"], "beneath downtown", 3),
      q("Predators fans sometimes throw what onto the ice?", ["a catfish", "an octopus", "a rubber chicken", "a cowboy hat"], "a catfish", 1),
      q("The Predators reached their first Stanley Cup Final in…", ["2017", "2008", "2011", "2023"], "2017", 2),
      q("The Predators play home games at…", ["Bridgestone Arena", "Nissan Stadium", "Geodis Park", "Municipal Auditorium"], "Bridgestone Arena", 1),
      q("Bridgestone Arena was completed in…", ["1996", "2001", "1988", "2008"], "1996", 2),
      q("Nashville SC's Geodis Park opened in…", ["2022", "2015", "2019", "2010"], "2022", 2),
      q("Geodis Park was built at the historic Nashville…", ["Fairgrounds", "Union Stockyards", "Rail Yard", "Naval Depot"], "Fairgrounds", 3),
      q("The Nashville Sounds are the Triple-A affiliate of the…", ["Milwaukee Brewers", "Chicago Cubs", "Atlanta Braves", "Cincinnati Reds"], "Milwaukee Brewers", 2),
      q("First Horizon Park was built on the site of which historic ballpark?", ["Sulphur Dell", "Greer Stadium", "Rickwood Field", "Engel Stadium"], "Sulphur Dell", 3),
      q("First Horizon Park opened in…", ["2015", "2005", "1998", "2020"], "2015", 2),
      q("Tennessee State University's Tigers play football at…", ["Nissan Stadium", "Geodis Park", "First Horizon Park", "Vanderbilt Stadium"], "Nissan Stadium", 2),
    ],
    arts: [
      q("The Grand Ole Opry called the Ryman home from 1943 until…", ["1974", "1962", "1985", "1999"], "1974", 2),
      q("In 2022 the Ryman was named a landmark by which hall of fame?", ["Rock & Roll Hall of Fame", "Country Music Hall of Fame", "Songwriters Hall of Fame", "Gospel Music Hall of Fame"], "Rock & Roll Hall of Fame", 2),
      q("The Grand Ole Opry is broadcast on which radio station?", ["WSM", "WLAC", "WKDA", "WNAH"], "WSM", 1),
      q("The Grand Ole Opry began in 1925 under the name…", ["WSM Barn Dance", "Saturday Jamboree", "Country Hour", "Hillbilly Hayride"], "WSM Barn Dance", 2),
      q("Announcer George D. Hay started the Grand Ole Opry in…", ["1925", "1938", "1912", "1946"], "1925", 2),
      q("The Grand Ole Opry is the longest-running what in U.S. history?", ["radio broadcast", "TV variety show", "music festival", "Broadway show"], "radio broadcast", 2),
      q("A six-foot circle cut from the Ryman's stage is set into the Opry House stage. It is made of…", ["oak", "maple", "cedar", "walnut"], "oak", 2),
      q("In May 2010 the Grand Ole Opry House was damaged by…", ["a flood", "a tornado", "a fire", "an earthquake"], "a flood", 2),
      q("From 1947 to 2022, the Ernest Tubb Record Shop sat on…", ["Broadway", "Music Row", "Church Street", "Jefferson Street"], "Broadway", 2),
      q("The Ernest Tubb Record Shop hosted which late-night show after the Opry?", ["Midnite Jamboree", "Hee Haw", "Country Countdown", "Ralph Emery Show"], "Midnite Jamboree", 3),
      q("Dolly Parton's 1973 song about the music business district is…", ["Down on Music Row", "Jolene", "Coat of Many Colors", "I Will Always Love You"], "Down on Music Row", 2),
      q("RCA Studio B was established in 1957 by Steve Sholes and…", ["Chet Atkins", "Owen Bradley", "Sam Phillips", "Fred Foster"], "Chet Atkins", 2),
      q("About how many songs did Elvis Presley record at RCA Studio B?", ["more than 200", "about 12", "about 50", "nearly 1,000"], "more than 200", 2),
      q("RCA Studio B helped create the polished country style called the…", ["Nashville Sound", "Bakersfield Sound", "Outlaw Sound", "Texas Swing"], "Nashville Sound", 2),
      q("The Nashville sound replaced rough honky-tonk with smooth…", ["strings and choruses", "banjos and fiddles", "drums and horns", "steel guitars"], "strings and choruses", 3),
      q("The Country Music Hall of Fame and Museum was chartered in…", ["1964", "1951", "1978", "1989"], "1964", 2),
      q("The Country Music Hall of Fame's front windows resemble…", ["piano keys", "guitar frets", "record grooves", "fiddle strings"], "piano keys", 2),
      q("Seen from above, the Country Music Hall of Fame building forms a…", ["bass clef", "guitar", "treble clef", "banjo"], "bass clef", 3),
      q("The arch of the Country Music Hall of Fame suggests the tailfin of a 1959…", ["Cadillac", "Chevrolet", "Thunderbird", "Studebaker"], "Cadillac", 3),
      q("Hatch Show Print was founded in…", ["1879", "1925", "1951", "1902"], "1879", 2),
      q("Hatch Show Print is known for concert posters made by…", ["letterpress", "screen printing", "lithography", "inkjet"], "letterpress", 2),
      q("Johnny Cash was often called the Man in…", ["Black", "White", "Blue", "Gray"], "Black", 1),
      q("The Johnny Cash Museum opened in…", ["2013", "1998", "2005", "2019"], "2013", 2),
      q("The Johnny Cash Museum shows a stone wall from Cash's lake house in…", ["Hendersonville", "Gallatin", "Franklin", "Murfreesboro"], "Hendersonville", 3),
      q("The Musicians Hall of Fame mostly honors…", ["session musicians", "country songwriters", "radio DJs", "concert promoters"], "session musicians", 2),
      q("The National Museum of African American Music opened in…", ["2021", "2008", "2015", "1996"], "2021", 2),
      q("NMAAM sits at Fifth and Broadway rather than on historically Black…", ["Jefferson Street", "Music Row", "Charlotte Avenue", "Church Street"], "Jefferson Street", 3),
      q("The Bluebird Cafe seats about…", ["90 people", "500 people", "1,200 people", "40 people"], "90 people", 2),
      q("In 2004 a label boss signed which 14-year-old after a Bluebird Cafe set?", ["Taylor Swift", "Kacey Musgraves", "Carrie Underwood", "Miranda Lambert"], "Taylor Swift", 1),
      q("Which star got a record deal in 1988 after filling in at the Bluebird Cafe?", ["Garth Brooks", "Alan Jackson", "Tim McGraw", "Kenny Chesney"], "Garth Brooks", 3),
      q("The Bluebird Cafe is in which neighborhood?", ["Green Hills", "The Gulch", "East Nashville", "Germantown"], "Green Hills", 3),
      q("The Station Inn near Music Row is best known for…", ["bluegrass", "jazz", "punk rock", "opera"], "bluegrass", 2),
      q("Nashville's Parthenon is a full-scale replica of a temple in…", ["Athens", "Rome", "Sparta", "Delphi"], "Athens", 1),
      q("The statue of Athena inside the Parthenon stands about…", ["42 feet tall", "12 feet tall", "90 feet tall", "20 feet tall"], "42 feet tall", 2),
      q("The Parthenon's Athena statue was re-created in 1990 by…", ["Alan LeQuire", "Daniel Chester French", "Gutzon Borglum", "Augustus Saint-Gaudens"], "Alan LeQuire", 3),
      q("The Fisk Jubilee Singers first toured in 1871 to raise money for…", ["their college", "a hospital", "a church", "the Union army"], "their college", 2),
      q("In 1873 the Fisk Jubilee Singers performed for…", ["Queen Victoria", "Napoleon III", "Tsar Alexander II", "Pope Pius IX"], "Queen Victoria", 3),
      q("The Library of Congress honored the Fisk Jubilee Singers' 1909 recording of…", ["Swing Low, Sweet Chariot", "Amazing Grace", "Go Tell It on the Mountain", "Wade in the Water"], "Swing Low, Sweet Chariot", 2),
      q("Cheekwood, the Cheek family estate, opened as a garden and art museum in…", ["1960", "1935", "1985", "1912"], "1960", 2),
      q("The Schermerhorn Symphony Center is home to the…", ["Nashville Symphony", "Fisk Jubilee Singers", "Nashville Opera", "Opry house band"], "Nashville Symphony", 2),
      q("Schermerhorn Symphony Center opened in…", ["2006", "1996", "2012", "1989"], "2006", 2),
      q("The Schermerhorn's main concert hall is named for…", ["Laura Turner", "Minnie Pearl", "Dolly Parton", "Adelicia Acklen"], "Laura Turner", 3),
      q("The Frist Art Museum is housed in a historic…", ["post office", "train station", "bank", "courthouse"], "post office", 2),
      q("The Country Music Association was founded in…", ["1958", "1972", "1939", "1985"], "1958", 2),
      q("Each June the Country Music Association throws a big festival called…", ["CMA Fest", "Bonnaroo", "Stagecoach", "Opry Days"], "CMA Fest", 2),
      q("Patti Page's 1950 hit about the state is…", ["Tennessee Waltz", "Rocky Top", "Tennessee Stud", "Jolene"], "Tennessee Waltz", 2),
    ],
    food: [
      q("Nashville hot chicken gets its heat mainly from…", ["cayenne pepper", "black pepper", "horseradish", "wasabi"], "cayenne pepper", 1),
      q("Nashville hot chicken is traditionally served on white bread with…", ["pickle chips", "coleslaw", "pimento cheese", "hot sauce"], "pickle chips", 1),
      q("Which restaurant is credited with popularizing hot chicken?", ["Prince's Hot Chicken Shack", "Hattie B's", "Loveless Cafe", "Arnold's Country Kitchen"], "Prince's Hot Chicken Shack", 2),
      q("Prince's Hot Chicken Shack was started in…", ["1945", "1972", "1990", "1928"], "1945", 2),
      q("Hattie B's Hot Chicken was founded by a father and son both named…", ["Nick Bishop", "Hattie Bishop", "Jack Daniel", "Tom Prince"], "Nick Bishop", 2),
      q("Nashville's Standard Candy Company created its famous cluster bar in…", ["1912", "1950", "1889", "1934"], "1912", 1),
      q("Howell Campbell's 1912 cluster bar is considered the first…", ["combination candy bar", "chocolate bar", "candy on a stick", "peanut brittle"], "combination candy bar", 2),
      q("Standard Candy's classic cluster bar holds marshmallow nougat, caramel and…", ["roasted peanuts", "toasted almonds", "candied pecans", "shredded coconut"], "roasted peanuts", 2),
      q("In a Southern meat and three, you choose one meat and three…", ["side dishes", "desserts", "sauces", "drinks"], "side dishes", 1),
      q("The Loveless Cafe is famous for its…", ["biscuits", "hot dogs", "pizza", "tamales"], "biscuits", 2),
      q("The Loveless Cafe sits near the northern end of the…", ["Natchez Trace Parkway", "Blue Ridge Parkway", "Cumberland Gap", "Great River Road"], "Natchez Trace Parkway", 3),
      q("Maxwell House coffee was named for a…", ["Nashville hotel", "Kentucky racehorse", "Civil War general", "riverboat"], "Nashville hotel", 2),
      q("Maxwell House coffee's slogan is…", ["Good to the last drop", "The best part of wakin' up", "America runs on it", "Rich and rare"], "Good to the last drop", 1),
      q("Maxwell House coffee was introduced in 1892 by grocer…", ["Joel Cheek", "Howell Campbell", "Thomas Ryman", "Jack Daniel"], "Joel Cheek", 3),
    ],
    political: [
      q("Since 1963 Nashville has shared a consolidated government with…", ["Davidson County", "Williamson County", "Rutherford County", "Sumner County"], "Davidson County", 2),
      q("How many members sit on Nashville's Metro Council?", ["40", "12", "25", "60"], "40", 2),
      q("Nashville became the capital of Tennessee in…", ["1843", "1796", "1812", "1870"], "1843", 2),
      q("Tennessee's nickname is the…", ["Volunteer State", "Mountain State", "Pelican State", "Bluegrass State"], "Volunteer State", 1),
      q("Tennessee joined the Union as the 16th state in…", ["1796", "1776", "1812", "1836"], "1796", 2),
      q("Tennessee's State Capitol was designed by architect…", ["William Strickland", "Benjamin Latrobe", "Robert Mills", "Thomas U. Walter"], "William Strickland", 2),
      q("Which president is buried on the Tennessee State Capitol grounds?", ["James K. Polk", "Andrew Jackson", "Andrew Johnson", "John Tyler"], "James K. Polk", 2),
      q("The Capitol's tower is modeled on the Choragic Monument of…", ["Lysicrates", "Pericles", "Augustus", "Hadrian"], "Lysicrates", 3),
      q("Tennessee's Capitol is one of 11 state capitols without a…", ["dome", "flagpole", "basement", "clock"], "dome", 2),
      q("The Tennessee State Capitol was built in which style?", ["Greek Revival", "Gothic Revival", "Art Deco", "Beaux-Arts"], "Greek Revival", 3),
      q("William Strickland trained as a student of…", ["Benjamin Latrobe", "Thomas Jefferson", "Charles Bulfinch", "Pierre L'Enfant"], "Benjamin Latrobe", 3),
      q("Diane Nash received the Presidential Medal of Freedom in…", ["2022", "2009", "1998", "2015"], "2022", 2),
      q("The Tennessean's first issue was printed in…", ["1907", "1849", "1931", "1886"], "1907", 2),
    ],
    nature: [
      q("The buried creek that runs through Bicentennial Mall is…", ["French Lick Creek", "Richland Creek", "Mill Creek", "Browns Creek"], "French Lick Creek", 3),
      q("The Cumberland River flows into the…", ["Ohio River", "Mississippi River", "Tennessee River", "Missouri River"], "Ohio River", 2),
      q("About how long is the Cumberland River?", ["688 miles", "250 miles", "1,200 miles", "2,300 miles"], "688 miles", 2),
      q("J. Percy Priest Lake is a reservoir on the…", ["Stones River", "Duck River", "Harpeth River", "Caney Fork"], "Stones River", 2),
      q("The Natchez Trace Parkway runs 444 miles from Natchez, Mississippi to…", ["Nashville", "Memphis", "Knoxville", "Chattanooga"], "Nashville", 1),
      q("The Schermerhorn's decor includes irises, Tennessee's state…", ["flower", "bird", "tree", "insect"], "flower", 2),
      q("In May 2010 Nashville flooded when torrential rain swelled the…", ["Cumberland River", "Tennessee River", "Mississippi River", "Duck River"], "Cumberland River", 2),
    ],
  },
};
