import { q } from "../quiz";
import type { CityId, TriviaCat, TriviaQ } from "../types";

/**
 * Local trivia card backlog, batch 1 (v0.0.26): Chicago, New York City, San Francisco.
 * Easy, checkable landmark / neighborhood / transit / history / food / team cards.
 * Merged into CITY_EXTRA by cities.ts (rarity stamped there with the city nudge).
 */
export const CITY_EXTRA_PART_D: Partial<Record<CityId, Partial<Record<TriviaCat, TriviaQ[]>>>> = {
  chicago: {
    local: [
      q("Chicago's best-known nickname is…", ["the Windy City", "the Big Apple", "the Emerald City", "the Mile High City"], "the Windy City", 1),
      q("Chicago's 'City of the Big Shoulders' line comes from a poem by…", ["Carl Sandburg", "Robert Frost", "Walt Whitman", "Langston Hughes"], "Carl Sandburg", 2),
      q("Legend blames the Great Chicago Fire on…", ["Mrs. O'Leary's cow", "a lightning strike", "a steamboat boiler", "a fireworks show"], "Mrs. O'Leary's cow", 1),
      q("Which Chicago landmark survived the Great Fire of 1871?", ["the Water Tower", "the Rookery", "the Wrigley Building", "Tribune Tower"], "the Water Tower", 1),
      q("The giant Picasso sculpture downtown stands in…", ["Daley Plaza", "Grant Park", "Pioneer Court", "Federal Plaza"], "Daley Plaza", 1),
      q("Alexander Calder's red 'Flamingo' stands in…", ["Federal Plaza", "Daley Plaza", "Millennium Park", "Navy Pier"], "Federal Plaza", 2),
      q("Buckingham Fountain is in…", ["Grant Park", "Lincoln Park", "Humboldt Park", "Jackson Park"], "Grant Park", 1),
      q("Millennium Park's Crown Fountain shows…", ["video faces of Chicagoans", "a giant floral clock", "jets from bronze lions", "a timed steam geyser"], "video faces of Chicagoans", 2),
      q("Jay Pritzker Pavilion in Millennium Park was designed by…", ["Frank Gehry", "I. M. Pei", "Zaha Hadid", "Renzo Piano"], "Frank Gehry", 2),
      q("The lions outside the Art Institute are made of…", ["bronze", "marble", "granite", "limestone"], "bronze", 1),
      q("Sue, the famous T. rex skeleton, is displayed at…", ["the Field Museum", "the Shedd Aquarium", "the Adler Planetarium", "the Art Institute"], "the Field Museum", 1),
      q("The Shedd on Chicago's lakefront is an…", ["aquarium", "art museum", "opera house", "observatory"], "aquarium", 1),
      q("The Adler on Chicago's lakefront is a…", ["planetarium", "zoo", "concert hall", "botanic garden"], "planetarium", 1),
      q("The Field Museum, Shedd, and Adler together form the…", ["Museum Campus", "Magnificent Mile", "Gold Coast", "Riverwalk"], "Museum Campus", 1),
      q("A captured German U-boat, U-505, is on display at…", ["the Museum of Science and Industry", "the Field Museum of Natural History", "the Chicago History Museum", "the Shedd Aquarium"], "the Museum of Science and Industry", 2),
      q("The Museum of Science and Industry's building survives from the…", ["1893 World's Fair", "1933 World's Fair", "1904 World's Fair", "1915 World's Fair"], "1893 World's Fair", 2),
      q("The original Ferris wheel debuted at Chicago's World's Fair in…", ["1893", "1871", "1933", "1916"], "1893", 2),
      q("Chicago's 1893 World's Fair was held mainly in…", ["Jackson Park", "Grant Park", "Lincoln Park", "Garfield Park"], "Jackson Park", 2),
      q("Chicago's 1893 World's Fair was nicknamed…", ["the White City", "the Emerald City", "the Iron City", "the Crystal City"], "the White City", 2),
      q("Chicago's 'L' trains and city buses are run by the…", ["CTA", "Metra", "MTA", "SEPTA"], "CTA", 1),
      q("Metra is the Chicago area's…", ["commuter rail", "subway", "ferry line", "bike share"], "commuter rail", 1),
      q("Which 'L' line runs to O'Hare Airport?", ["Blue Line", "Red Line", "Green Line", "Orange Line"], "Blue Line", 1),
      q("Which 'L' line runs to Midway Airport?", ["Orange Line", "Blue Line", "Brown Line", "Pink Line"], "Orange Line", 2),
      q("Chicago's first elevated 'L' line opened in…", ["1892", "1904", "1871", "1925"], "1892", 2),
      q("Wrigley Field's outfield walls are covered in…", ["ivy", "murals", "billboards", "mirrors"], "ivy", 1),
      q("After a Cubs win, Wrigley Field flies a white flag with a blue…", ["W", "C", "star", "bear"], "W", 1),
      q("Wrigley Field opened in…", ["1914", "1926", "1908", "1932"], "1914", 2),
      q("Bleacher fans at Wrigley famously throw back…", ["opponents' homers", "foul pop-ups", "broken bats", "rally towels"], "opponents' homers", 2),
      q("Soldier Field was named as a memorial to…", ["fallen U.S. soldiers", "a Civil War general", "a Bears founder", "a fire chief"], "fallen U.S. soldiers", 2),
      q("Navy Pier's best-known ride is its…", ["Ferris wheel", "roller coaster", "log flume", "drop tower"], "Ferris wheel", 1),
      q("For St. Patrick's Day, Chicago dyes its river…", ["green", "orange", "blue", "gold"], "green", 1),
      q("In 2021, Chicago renamed outer Lake Shore Drive to honor…", ["Jean Baptiste Point DuSable", "Harold Washington", "Richard J. Daley", "Ida B. Wells"], "Jean Baptiste Point DuSable", 2),
      q("Chicago was incorporated as a city in…", ["1837", "1803", "1871", "1818"], "1837", 2),
      q("Fort Dearborn stood at the mouth of the…", ["Chicago River", "Calumet River", "Des Plaines River", "Fox River"], "Chicago River", 2),
      q("The name 'Chicago' comes from a Native word for…", ["wild onion", "great water", "red earth", "tall grass"], "wild onion", 2),
      q("How many red stars are on Chicago's city flag?", ["four", "two", "three", "six"], "four", 1),
      q("The two blue stripes on Chicago's flag stand for…", ["bodies of water", "police and fire", "rail lines", "two founding forts"], "bodies of water", 2),
      q("One star on Chicago's flag honors…", ["Fort Dearborn", "the Bulls dynasty", "the first skyscraper", "Lincoln's election"], "Fort Dearborn", 2),
      q("The Robie House, a Prairie-style home in Hyde Park, was designed by…", ["Frank Lloyd Wright", "Louis Sullivan", "Daniel Burnham", "Mies van der Rohe"], "Frank Lloyd Wright", 2),
      q("The 1909 Plan of Chicago was led by…", ["Daniel Burnham", "Louis Sullivan", "Frederick Law Olmsted", "Potter Palmer"], "Daniel Burnham", 2),
      q("Chicago is often called the birthplace of the…", ["skyscraper", "subway", "streetcar", "suspension bridge"], "skyscraper", 1),
      q("Willis Tower's glass boxes that jut out from the Skydeck are called…", ["The Ledge", "The Edge", "TILT", "Sky Box"], "The Ledge", 1),
      q("The former John Hancock Center now goes by its address…", ["875 North Michigan Avenue", "233 South Wacker Drive", "401 North Wabash Avenue", "100 East Randolph Street"], "875 North Michigan Avenue", 2),
      q("Wacker Drive is famous for being…", ["a two-level street", "a riverside beach", "a pedestrian mall", "a toll tunnel"], "a two-level street", 2),
      q("Marina City's twin towers are often compared to…", ["corncobs", "rockets", "pinecones", "beehives"], "corncobs", 1),
      q("The big vertical sign of the famous State Street theater spells…", ["CHICAGO", "ORIENTAL", "PALACE", "REGAL"], "CHICAGO", 2),
      q("Chicago's address grid starts at State Street and…", ["Madison Street", "Monroe Street", "Lake Street", "Wacker Drive"], "Madison Street", 2),
      q("Which Chicago neighborhood is known for Mexican heritage and murals?", ["Pilsen", "Andersonville", "Bridgeport", "Ukrainian Village"], "Pilsen", 1),
      q("Pilsen was named by immigrants from…", ["Bohemia", "Mexico", "Poland", "Ireland"], "Bohemia", 2),
      q("Which North Side neighborhood has Swedish roots and a Swedish museum?", ["Andersonville", "Pilsen", "Bucktown", "Bronzeville"], "Andersonville", 2),
      q("Bronzeville grew into a center of Chicago's…", ["Black arts and business", "Polish community", "meatpacking plants", "steel mills"], "Black arts and business", 2),
      q("Chicago's Greektown is along…", ["Halsted Street", "Devon Avenue", "Argyle Street", "Clark Street"], "Halsted Street", 2),
      q("Devon Avenue on the North Side is known for…", ["South Asian shops and food", "Greek tavernas", "art galleries", "German beer halls"], "South Asian shops and food", 2),
      q("Chicago's Chinatown gate stands on…", ["Wentworth Avenue", "Michigan Avenue", "Western Avenue", "Ashland Avenue"], "Wentworth Avenue", 2),
      q("Chicago's Little Italy centers on…", ["Taylor Street", "Devon Avenue", "Division Street", "Belmont Avenue"], "Taylor Street", 2),
      q("Chicago's Gold Coast neighborhood is on the…", ["Near North Side", "Southwest Side", "West Side", "Far South Side"], "Near North Side", 1),
      q("Bridgeport is the South Side neighborhood tied to which political family?", ["the Daleys", "the Kennedys", "the Pritzkers", "the Emanuels"], "the Daleys", 2),
      q("Richard J. Daley and Richard M. Daley were both Chicago…", ["mayors", "governors", "senators", "police chiefs"], "mayors", 1),
      q("Chicago's first Black mayor was…", ["Harold Washington", "Eugene Sawyer", "Bobby Rush", "Roland Burris"], "Harold Washington", 2),
      q("Chicago's first woman mayor was…", ["Jane Byrne", "Lori Lightfoot", "Toni Preckwinkle", "Lisa Madigan"], "Jane Byrne", 2),
      q("The Harold Washington Library Center is Chicago's…", ["main public library", "city hall", "main post office", "convention center"], "main public library", 1),
      q("Jane Addams co-founded which Chicago settlement house?", ["Hull House", "Henry Street", "Toynbee Hall", "Bethel House"], "Hull House", 2),
      q("McCormick Place is Chicago's huge…", ["convention center", "sports arena", "rail yard", "airport terminal"], "convention center", 1),
      q("Chicago's Union Stock Yards were famous for…", ["meatpacking", "steelmaking", "shipbuilding", "auto assembly"], "meatpacking", 1),
      q("Lincoln Park Zoo is notable for being…", ["free to enter", "the world's oldest", "in the Loop", "on an island"], "free to enter", 1),
      q("Chicago's largest public park is…", ["Lincoln Park", "Grant Park", "Jackson Park", "Washington Park"], "Lincoln Park", 2),
      q("Grant Park is often called Chicago's…", ["front yard", "back porch", "green heart", "living room"], "front yard", 2),
      q("Garfield Park on the West Side is famous for its…", ["huge conservatory", "big-cat zoo house", "rowing lagoon", "science museum"], "huge conservatory", 2),
      q("The 606 in Chicago is a…", ["trail on an old rail line", "new 'L' subway branch", "lakefront concert lawn", "indoor food market hall"], "trail on an old rail line", 2),
      q("Chicago's Pedway is a network of…", ["underground walkways", "bike lanes", "bus lanes", "rooftop gardens"], "underground walkways", 2),
      q("Chicago's Lakefront Trail is about how long?", ["18 miles", "5 miles", "40 miles", "2 miles"], "18 miles", 2),
      q("Chicago's lakefront is mostly…", ["public parkland", "private estates", "industrial docks", "naval bases"], "public parkland", 1),
      q("Northerly Island was once home to which airport?", ["Meigs Field", "Midway", "Orchard Field", "Pal-Waukee"], "Meigs Field", 2),
      q("Midway Airport is named for…", ["a WWII naval battle", "a carnival midway", "a former mayor", "its distance from O'Hare"], "a WWII naval battle", 2),
      q("O'Hare Airport is named for…", ["a WWII Navy pilot", "a Chicago mayor", "an Irish poet", "a railroad baron"], "a WWII Navy pilot", 2),
      q("Which of Chicago's big airports is closer to downtown?", ["Midway", "O'Hare", "Gary", "Rockford"], "Midway", 1),
      q("Union Station's grand staircase is famous from a shootout in…", ["The Untouchables", "The Blues Brothers", "The Fugitive", "Home Alone"], "The Untouchables", 2),
      q("The Chicago Cultural Center is famous for its…", ["Tiffany glass dome", "rooftop garden", "spiral ramp", "glass floor"], "Tiffany glass dome", 2),
      q("The Magnificent Mile runs north from the river to…", ["Oak Street", "Division Street", "Ohio Street", "Grand Avenue"], "Oak Street", 2),
      q("Most bridges over the Chicago River are…", ["bascule bridges", "suspension bridges", "covered bridges", "pontoon bridges"], "bascule bridges", 2),
      q("Chicago's famous architecture boat tours cruise the…", ["Chicago River", "Lake Calumet", "Des Plaines River", "Fox River"], "Chicago River", 1),
      q("Chicago's 1886 Haymarket affair is tied to the fight for…", ["the eight-hour workday", "women's suffrage", "the abolition of slavery", "Prohibition"], "the eight-hour workday", 2),
      q("Gangster Al Capone ruled Chicago's underworld during…", ["Prohibition", "the Gilded Age", "the Civil War", "the Space Race"], "Prohibition", 1),
      q("The Great Migration brought many Black Chicagoans from…", ["the Deep South", "New England", "the Pacific Northwest", "the Mountain West"], "the Deep South", 2),
      q("The Chicago Defender was a famous…", ["Black newspaper", "football team", "fireboat", "radio tower"], "Black newspaper", 2),
      q("Ida B. Wells, honored by a downtown Chicago drive, crusaded against…", ["lynching", "child labor", "Prohibition", "smallpox"], "lynching", 2),
      q("Chicago's Pullman neighborhood was built as a…", ["company town", "army fort", "Olympic village", "mining camp"], "company town", 2),
      q("The statue atop the Chicago Board of Trade Building depicts…", ["Ceres", "Athena", "Mercury", "Liberty"], "Ceres", 2),
      q("Chicago's financial district centers on…", ["LaSalle Street", "Halsted Street", "Clark Street", "Ashland Avenue"], "LaSalle Street", 2),
      q("Which Chicago street is famously 'that great street'?", ["State Street", "Rush Street", "Wells Street", "Lake Street"], "State Street", 2),
      q("The landmark State Street store with the Great Clock was built for…", ["Marshall Field's", "Sears, Roebuck", "Montgomery Ward", "Carson Pirie Scott"], "Marshall Field's", 2),
      q("Chicago's Christkindlmarket is a holiday market in the style of…", ["Germany", "Italy", "Mexico", "Sweden"], "Germany", 1),
      q("Cloud Gate, 'the Bean,' is made of…", ["stainless steel", "polished silver", "chrome glass", "aluminum"], "stainless steel", 1),
      q("Chicago's Puerto Rican community is centered in…", ["Humboldt Park", "Pilsen", "Bridgeport", "Lakeview"], "Humboldt Park", 2),
      q("The Second City comedy theater is in which neighborhood?", ["Old Town", "Pilsen", "Bucktown", "Bridgeport"], "Old Town", 2),
      q("Lake Michigan is the only Great Lake entirely within…", ["the United States", "Canada", "Michigan", "Illinois"], "the United States", 1),
    ],
    food: [
      q("Ordering an Italian beef 'hot' means adding…", ["giardiniera", "extra jus", "hot sauce", "pepper jack"], "giardiniera", 1),
      q("A Chicago-style hot dog's relish is a bright…", ["neon green", "dark red", "mustard yellow", "deep brown"], "neon green", 1),
      q("A Chicago-style hot dog gets a final dash of…", ["celery salt", "garlic salt", "paprika", "cumin"], "celery salt", 2),
      q("A Maxwell Street Polish is a grilled sausage topped with…", ["grilled onions and mustard", "sauerkraut and ketchup", "chili and cheese", "coleslaw and relish"], "grilled onions and mustard", 2),
      q("Chicago tavern-style thin-crust pizza is cut into…", ["squares", "wedges", "strips", "rings"], "squares", 1),
      q("In a Chicago deep-dish pizza, the tomato sauce goes…", ["on top of the cheese", "under the cheese", "baked into the crust", "on the side"], "on top of the cheese", 1),
      q("The jibarito sandwich swaps the bread for…", ["fried plantains", "waffles", "lettuce leaves", "tortillas"], "fried plantains", 2),
      q("Chicago's Original Rainbow Cone stacks how many flavors?", ["five", "three", "seven", "four"], "five", 2),
      q("The chocolate brownie is said to have been created at which Chicago hotel?", ["the Palmer House", "the Drake", "the Blackstone", "the Congress"], "the Palmer House", 2),
      q("Portillo's is a Chicago chain best known for…", ["hot dogs and Italian beef", "deep-dish pizza", "fried chicken", "pierogi"], "hot dogs and Italian beef", 1),
    ],
    sports: [
      q("The Cubs' 2016 World Series title ended a drought dating to…", ["1908", "1918", "1945", "1969"], "1908", 2),
      q("The White Sox won the World Series in…", ["2005", "2016", "1998", "2010"], "2005", 2),
      q("The Bulls won six NBA titles in the…", ["1990s", "1980s", "2000s", "1970s"], "1990s", 1),
      q("The Bulls' 1990s dynasty was led by…", ["Michael Jordan", "Magic Johnson", "Larry Bird", "Kobe Bryant"], "Michael Jordan", 1),
      q("The 1985 Chicago Bears won…", ["Super Bowl XX", "Super Bowl X", "Super Bowl XXX", "Super Bowl V"], "Super Bowl XX", 2),
      q("The 'Monsters of the Midway' are the…", ["Bears", "Cubs", "Bulls", "White Sox"], "Bears", 1),
      q("'Papa Bear' George Halas founded and coached the…", ["Bears", "Cubs", "Bulls", "Blackhawks"], "Bears", 2),
      q("Cubs legend Ernie Banks was nicknamed…", ["Mr. Cub", "Mr. October", "The Kid", "Hammerin' Hank"], "Mr. Cub", 2),
      q("At Wrigley, broadcaster Harry Caray led fans in singing…", ["Take Me Out to the Ball Game", "Sweet Home Chicago", "God Bless America", "Sweet Caroline"], "Take Me Out to the Ball Game", 1),
      q("Chicago's WNBA team is the…", ["Sky", "Fire", "Sparks", "Storm"], "Sky", 1),
      q("The Blackhawks are one of the NHL's…", ["Original Six", "Expansion Six", "Founding Four", "Big Eight"], "Original Six", 1),
    ],
    arts: [
      q("Georges Seurat's 'A Sunday on La Grande Jatte' hangs at…", ["the Art Institute of Chicago", "the Museum of Modern Art", "the Metropolitan Museum", "the National Gallery"], "the Art Institute of Chicago", 2),
      q("Edward Hopper's 'Nighthawks' hangs at…", ["the Art Institute of Chicago", "the Whitney Museum", "the Guggenheim", "the Getty Center"], "the Art Institute of Chicago", 2),
      q("In 'Ferris Bueller's Day Off,' the friends visit…", ["the Art Institute", "the Field Museum", "the Shedd Aquarium", "the Adler Planetarium"], "the Art Institute", 2),
      q("Steppenwolf is a famous Chicago…", ["theater company", "jazz club", "comedy club", "dance troupe"], "theater company", 2),
      q("House music takes its name from a Chicago club called…", ["the Warehouse", "CBGB", "Studio 54", "the Fillmore"], "the Warehouse", 2),
      q("Chess Records in Chicago was a famous label for…", ["blues", "polka", "country", "grunge"], "blues", 2),
    ],
  },
};
