import { q } from "../quiz";
import type { CityId, TriviaCat, TriviaQ } from "../types";

/**
 * Local trivia card backlog, batch 2 (v0.0.27): Detroit, London, Austin, Temple, Tucson.
 * Thinnest cities first. Easy cards are difficulty 1 so they band white.
 * Merged into CITY_EXTRA by cities.ts (rarity stamped there with the city nudge).
 */
export const CITY_EXTRA_PART_E: Partial<Record<CityId, Partial<Record<TriviaCat, TriviaQ[]>>>> = {
  detroit: {
    local: [
      q("Detroit's best-known nickname is…", ["the Motor City", "the Steel City", "the Windy City", "the Big Easy"], "the Motor City", 1),
      q("The name 'Motown' is short for…", ["Motor Town", "Motor Tunes", "Model Town", "Mo' Town Sound"], "Motor Town", 1),
      q("Locals often shorten Detroit's name to…", ["the D", "the Big D", "the Lou", "the Nati"], "the D", 1),
      q("Detroit's original area code is…", ["313", "312", "216", "414"], "313", 1),
      q("Detroit was founded by the French in…", ["1701", "1776", "1805", "1650"], "1701", 2),
      q("Detroit's founder was…", ["Antoine de la Mothe Cadillac", "Jacques Marquette", "Samuel de Champlain", "Louis Jolliet"], "Antoine de la Mothe Cadillac", 2),
      q("The Cadillac car brand is named after…", ["Detroit's founder", "a French king", "a racehorse", "a Michigan lake"], "Detroit's founder", 1),
      q("The name 'Detroit' comes from a French word for…", ["strait", "riverbank", "red earth", "trading post"], "strait", 2),
      q("A fire nearly wiped out the town of Detroit in…", ["1805", "1871", "1763", "1837"], "1805", 2),
      q("Detroit's motto 'Resurget cineribus' means…", ["it will rise from the ashes", "it will build in steel", "it stands by the water", "it moves the world"], "it will rise from the ashes", 2),
      q("After the 1805 fire, Augustus Woodward's street plan was modeled on…", ["Washington, D.C.", "Paris", "London", "Philadelphia"], "Washington, D.C.", 3),
      q("Odawa leader Pontiac laid siege to Fort Detroit in…", ["1763", "1701", "1812", "1796"], "1763", 3),
      q("In 1812, General William Hull surrendered Detroit to the…", ["British", "French", "Spanish", "Dutch"], "British", 2),
      q("Until 1847, Michigan's state capital was…", ["Detroit", "Lansing", "Ann Arbor", "Grand Rapids"], "Detroit", 2),
      q("On the Underground Railroad, Detroit's code name was…", ["Midnight", "Canaan", "Jordan", "Daybreak"], "Midnight", 3),
      q("From downtown Detroit, Windsor, Canada, lies to the…", ["south", "north", "east", "west"], "south", 1),
      q("The Ambassador Bridge is unusual because it is…", ["privately owned", "made of wood", "a toll-free span", "a drawbridge"], "privately owned", 3),
      q("Beneath Detroit lies a huge underground mine of…", ["salt", "coal", "copper", "iron ore"], "salt", 2),
      q("The J.W. Westcott II on the Detroit River is a mail boat with its own…", ["ZIP code", "lighthouse", "post office bank", "customs flag"], "ZIP code", 3),
      q("Ford's Model T was first built at Detroit's…", ["Piquette Avenue Plant", "River Rouge Complex", "Willow Run plant", "Highland Park plant"], "Piquette Avenue Plant", 2),
      q("Ford's moving assembly line started in 1913 at its plant in…", ["Highland Park", "Dearborn", "Flint", "Pontiac"], "Highland Park", 2),
      q("In 1914 Ford stunned workers with a daily wage of…", ["$5", "$1", "$10", "$3"], "$5", 2),
      q("Detroit's traditional 'Big Three' automakers are GM, Ford, and…", ["Chrysler", "Toyota", "Studebaker", "Packard"], "Chrysler", 1),
      q("The Detroit architect famed for Ford's factories was…", ["Albert Kahn", "Louis Kahn", "Eero Saarinen", "Minoru Yamasaki"], "Albert Kahn", 2),
      q("In World War II, Detroit's factories earned it the nickname…", ["the Arsenal of Democracy", "the Forge of Freedom", "the Engine of Victory", "the Workshop of War"], "the Arsenal of Democracy", 1),
      q("Ford's Willow Run plant near Detroit built which WWII bomber?", ["B-24 Liberator", "B-17 Flying Fortress", "B-29 Superfortress", "B-25 Mitchell"], "B-24 Liberator", 3),
      q("The UAW, based in Detroit, is a…", ["labor union", "racing league", "safety agency", "dealer group"], "labor union", 1),
      q("Which leader headed the UAW from 1946 to 1970?", ["Walter Reuther", "John L. Lewis", "Jimmy Hoffa", "Eugene Debs"], "Walter Reuther", 2),
      q("Detroit's population peaked around 1950 at nearly…", ["1.85 million", "3 million", "900,000", "5 million"], "1.85 million", 3),
      q("In 2013 Detroit made history with the largest U.S. city…", ["bankruptcy", "blackout", "strike", "flood"], "bankruptcy", 2),
      q("Detroit's 1967 uprising began after a police raid on…", ["12th Street", "8 Mile Road", "Woodward Avenue", "Gratiot Avenue"], "12th Street", 3),
      q("Woodward Avenue is also the state highway numbered…", ["M-1", "I-75", "US-12", "M-10"], "M-1", 2),
      q("In 1909, the first mile of concrete road in the U.S. was laid on Detroit's…", ["Woodward Avenue", "Michigan Avenue", "Jefferson Avenue", "Grand River Avenue"], "Woodward Avenue", 3),
      q("Detroit police officer William Potts is credited with the first…", ["three-color traffic light", "police radio car", "parking meter", "stop sign"], "three-color traffic light", 3),
      q("The Woodward Dream Cruise celebrates…", ["classic cars", "jazz bands", "speedboats", "hot-air balloons"], "classic cars", 1),
      q("The People Mover is Detroit's…", ["elevated downtown loop", "underground subway", "river ferry line", "hillside cable car"], "elevated downtown loop", 1),
      q("Eastern Market in Detroit is a big historic…", ["public market", "car museum", "jazz club", "sports arena"], "public market", 1),
      q("Which downtown Detroit district is known for Greek restaurants and a casino?", ["Greektown", "Corktown", "Mexicantown", "Midtown"], "Greektown", 1),
      q("Corktown was named for Irish immigrants from…", ["County Cork", "County Kerry", "Dublin", "Galway"], "County Cork", 1),
      q("Detroit's oldest surviving neighborhood is…", ["Corktown", "Brush Park", "Midtown", "Indian Village"], "Corktown", 2),
      q("Which automaker restored Michigan Central Station?", ["Ford", "GM", "Chrysler", "Tesla"], "Ford", 1),
      q("Which university anchors Detroit's Midtown?", ["Wayne State", "Michigan State", "Eastern Michigan", "Oakland University"], "Wayne State", 1),
      q("The Dequindre Cut is a greenway built on an old…", ["rail line", "canal", "highway", "streetcar barn"], "rail line", 2),
      q("Detroit's riverfront trail is called the…", ["RiverWalk", "Lakeshore Path", "Strait Trail", "Harbor Line"], "RiverWalk", 1),
      q("Belle Isle's park plan was drawn by Central Park's co-designer…", ["Frederick Law Olmsted", "Daniel Burnham", "Pierre L'Enfant", "Jens Jensen"], "Frederick Law Olmsted", 3),
      q("Belle Isle's grand marble fountain is the…", ["James Scott Memorial Fountain", "Buckingham Fountain", "Dodge Fountain", "Bethesda Fountain"], "James Scott Memorial Fountain", 2),
      q("Hart Plaza's ring-shaped Dodge Fountain was designed by…", ["Isamu Noguchi", "Alexander Calder", "Henry Moore", "Louise Nevelson"], "Isamu Noguchi", 3),
      q("Hart Plaza hosts which electronic music festival each May?", ["Movement", "Ultra", "Coachella", "Lollapalooza"], "Movement", 2),
      q("Detroit's free Labor Day weekend festival is devoted to…", ["jazz", "techno", "blues", "folk"], "jazz", 2),
      q("Detroit's big late-November holiday parade is called…", ["America's Thanksgiving Parade", "the Motor City Parade", "the Great Lakes Parade", "the Turkey Trot Parade"], "America's Thanksgiving Parade", 2),
      q("The Spirit of Detroit statue stands outside the…", ["municipal center", "train station", "art museum", "auto plant"], "municipal center", 2),
      q("The Spirit of Detroit statue was sculpted by…", ["Marshall Fredericks", "Augustus Saint-Gaudens", "Daniel Chester French", "Robert Graham"], "Marshall Fredericks", 3),
      q("Michigan's tallest building is the central tower of the…", ["Renaissance Center", "Guardian Building", "Penobscot Building", "Fisher Building"], "Renaissance Center", 2),
      q("The Guardian Building is nicknamed the…", ["Cathedral of Finance", "Tower of Power", "Jewel of Woodward", "Temple of Trade"], "Cathedral of Finance", 2),
      q("The golden-roofed Art Deco tower in New Center is the…", ["Fisher Building", "Guardian Building", "Book Tower", "Buhl Building"], "Fisher Building", 2),
      q("Detroit's Masonic Temple is famous as the world's…", ["largest Masonic temple", "oldest opera house", "tallest church", "first movie palace"], "largest Masonic temple", 2),
      q("Lafayette Park holds the world's largest collection of buildings by…", ["Mies van der Rohe", "Frank Lloyd Wright", "Le Corbusier", "Walter Gropius"], "Mies van der Rohe", 3),
      q("Downtown Hudson's, demolished in 1998, was once the world's tallest…", ["department store", "parking garage", "hotel", "office tower"], "department store", 3),
      q("Ford Field was built around an old warehouse of…", ["Hudson's", "Ford", "Stroh's", "Kresge"], "Hudson's", 3),
      q("Outside the Detroit Institute of Arts sits a cast of Rodin's…", ["The Thinker", "The Kiss", "The Gates of Hell", "Balzac"], "The Thinker", 2),
      q("Detroit's Charles H. Wright Museum focuses on…", ["African American history", "auto design", "Great Lakes ships", "modern art"], "African American history", 1),
      q("Pewabic, founded in Detroit in 1903, is famous for…", ["art pottery and tiles", "stained glass", "car horns", "leather saddles"], "art pottery and tiles", 2),
      q("Rosa Parks spent most of her later life in…", ["Detroit", "Atlanta", "Chicago", "Memphis"], "Detroit", 2),
      q("The bus from Rosa Parks's protest is displayed at…", ["The Henry Ford", "the DIA", "the Smithsonian", "the Wright Museum"], "The Henry Ford", 1),
      q("Greenfield Village in Dearborn is an outdoor…", ["history museum", "car factory", "golf resort", "zoo"], "history museum", 1),
      q("The Arab American National Museum is in…", ["Dearborn", "Hamtramck", "Royal Oak", "Southfield"], "Dearborn", 2),
      q("Which two cities sit almost entirely inside Detroit?", ["Hamtramck and Highland Park", "Dearborn and Warren", "Ferndale and Troy", "Livonia and Novi"], "Hamtramck and Highland Park", 3),
      q("On Fat Tuesday, Hamtramck lines up for which Polish pastry?", ["paczki", "kolaches", "pierogi", "babka"], "paczki", 1),
      q("The Detroit Zoo is actually located in…", ["Royal Oak", "Dearborn", "Ferndale", "Grosse Pointe"], "Royal Oak", 2),
      q("Motown's Studio A at Hitsville was nicknamed…", ["the Snakepit", "the Fishbowl", "the Engine Room", "the Hit Factory"], "the Snakepit", 3),
      q("In 1972 Motown moved its headquarters to…", ["Los Angeles", "New York", "Chicago", "Nashville"], "Los Angeles", 2),
      q("Diana Ross first rose to fame with which Motown group?", ["the Supremes", "the Marvelettes", "the Vandellas", "the Shirelles"], "the Supremes", 1),
      q("Smokey Robinson led which Motown group?", ["the Miracles", "the Temptations", "the Four Tops", "the Contours"], "the Miracles", 1),
      q("'Dancing in the Street' was a Motown hit for…", ["Martha and the Vandellas", "the Supremes", "Gladys Knight & the Pips", "the Four Tops"], "Martha and the Vandellas", 2),
      q("Aretha Franklin's father pastored which Detroit church?", ["New Bethel Baptist", "Second Baptist", "Hartford Memorial", "Greater Grace Temple"], "New Bethel Baptist", 3),
      q("Detroit techno's 'Belleville Three' included…", ["Juan Atkins", "Frankie Knuckles", "Afrika Bambaataa", "Larry Levan"], "Juan Atkins", 3),
      q("Eminem's semi-autobiographical Detroit film is titled…", ["8 Mile", "Purple Rain", "Hustle & Flow", "Straight Outta Compton"], "8 Mile", 1),
      q("Jack and Meg White's Detroit rock duo was…", ["the White Stripes", "the Black Keys", "the Strokes", "the Kills"], "the White Stripes", 1),
      q("'Kick Out the Jams' was a 1969 anthem by Detroit-area band…", ["MC5", "the Stooges", "Grand Funk", "Bob Seger"], "MC5", 3),
      q("Gordon Lightfoot's song that mentions a Detroit church is about…", ["the Edmund Fitzgerald", "the Titanic", "the Lusitania", "the Andrea Doria"], "the Edmund Fitzgerald", 2),
      q("Thanks to the Red Wings, Detroit calls itself…", ["Hockeytown", "Puckville", "Ice City", "Rinktown"], "Hockeytown", 1),
      q("The Red Wings' logo is a…", ["winged wheel", "red hawk", "flying puck", "winged star"], "winged wheel", 1),
      q("Red Wings fans famously toss which animal onto the ice?", ["octopus", "rat", "catfish", "squid"], "octopus", 1),
      q("The Red Wings octopus's eight arms first stood for…", ["eight playoff wins", "eight players", "eight goals", "eight decades"], "eight playoff wins", 2),
      q("Gordie Howe, the Red Wings legend, was nicknamed…", ["Mr. Hockey", "the Great One", "Super Mario", "the Rocket"], "Mr. Hockey", 1),
      q("The late-1980s Pistons were nicknamed the…", ["Bad Boys", "Showtime", "Fab Five", "Big Three"], "Bad Boys", 1),
      q("The Bad Boys Pistons were led by point guard…", ["Isiah Thomas", "Magic Johnson", "John Stockton", "Mark Price"], "Isiah Thomas", 2),
      q("The Pistons won back-to-back NBA titles in…", ["1989 and 1990", "1985 and 1986", "1991 and 1992", "1995 and 1996"], "1989 and 1990", 2),
      q("Before Detroit, the Pistons franchise played in…", ["Fort Wayne", "Indianapolis", "Toledo", "Grand Rapids"], "Fort Wayne", 2),
      q("Before moving downtown in 2017, the Pistons played at the Palace of…", ["Auburn Hills", "Royal Oak", "Southfield", "Troy"], "Auburn Hills", 2),
      q("Little Caesars Arena is home to the Red Wings and the…", ["Pistons", "Lions", "Tigers", "Shock"], "Pistons", 1),
      q("The Ilitch family behind the Tigers and Red Wings founded…", ["Little Caesars", "Domino's", "Better Made", "Faygo"], "Little Caesars", 2),
      q("Old Tiger Stadium stood at the corner of Michigan and…", ["Trumbull", "Woodward", "Gratiot", "Grand River"], "Trumbull", 2),
      q("Which batting legend played 22 seasons for the Tigers?", ["Ty Cobb", "Babe Ruth", "Honus Wagner", "Cy Young"], "Ty Cobb", 2),
      q("The 1984 champion Tigers were managed by…", ["Sparky Anderson", "Tommy Lasorda", "Earl Weaver", "Billy Martin"], "Sparky Anderson", 3),
      q("Ernie Harwell was the longtime radio voice of the…", ["Tigers", "Lions", "Pistons", "Red Wings"], "Tigers", 2),
      q("The Lions famously host a game every year on…", ["Thanksgiving", "Christmas", "New Year's Day", "Labor Day"], "Thanksgiving", 1),
      q("Which running back starred for the Lions in the 1990s?", ["Barry Sanders", "Emmitt Smith", "Walter Payton", "Eric Dickerson"], "Barry Sanders", 1),
      q("Before Ford Field, the Lions played in the…", ["Pontiac Silverdome", "Astrodome", "Metrodome", "Kingdome"], "Pontiac Silverdome", 2),
      q("Boxer Joe Louis, who grew up in Detroit, was nicknamed…", ["the Brown Bomber", "the Greatest", "Iron Mike", "Sugar Ray"], "the Brown Bomber", 2),
      q("Detroit-style pizza was born in 1946 at…", ["Buddy's", "Shield's", "Jet's", "Loui's"], "Buddy's", 2),
      q("Detroit-style pizza was first baked in pans meant for…", ["auto parts", "bread loaves", "cake sheets", "roasting meat"], "auto parts", 2),
      q("Two rival Coney spots sit side by side downtown: American and…", ["Lafayette", "National", "Duly's", "Leo's"], "Lafayette", 2),
      q("Detroit's Sanders brand is best known for its…", ["hot fudge", "potato chips", "ginger ale", "coney sauce"], "hot fudge", 2),
      q("'Detroit vs. Everybody' is a popular local…", ["slogan apparel line", "rap battle show", "football rivalry", "radio station"], "slogan apparel line", 1),
    ],
  },
  london: {
    local: [
      q("The Romans founded London under the name…", ["Londinium", "Lugdunum", "Eboracum", "Camulodunum"], "Londinium", 1),
      q("Which warrior queen burned Roman London around AD 60?", ["Boudica", "Cleopatra", "Zenobia", "Matilda"], "Boudica", 2),
      q("The Great Fire of London broke out in…", ["1666", "1066", "1605", "1750"], "1666", 1),
      q("The Great Fire of London started in a bakery on…", ["Pudding Lane", "Fleet Street", "Baker Street", "Drury Lane"], "Pudding Lane", 1),
      q("The Monument near London Bridge commemorates…", ["the Great Fire", "the Battle of Hastings", "the Blitz", "Waterloo"], "the Great Fire", 1),
      q("How many steps climb to the top of the Monument?", ["311", "205", "530", "128"], "311", 3),
      q("St Paul's Cathedral was rebuilt after the Great Fire by…", ["Christopher Wren", "Inigo Jones", "John Nash", "Charles Barry"], "Christopher Wren", 1),
      q("St Paul's dome gallery famous for carrying quiet voices is the…", ["Whispering Gallery", "Echo Chamber", "Golden Gallery", "Stone Gallery"], "Whispering Gallery", 1),
      q("Prince Charles and Lady Diana married in 1981 at…", ["St Paul's Cathedral", "Westminster Abbey", "Windsor Castle", "St George's Chapel"], "St Paul's Cathedral", 2),
      q("Guy Fawkes tried to blow up Parliament in…", ["1605", "1666", "1588", "1215"], "1605", 1),
      q("Bonfire Night in Britain falls on…", ["5 November", "31 October", "1 May", "23 April"], "5 November", 1),
      q("The German bombing of London in 1940–41 is known as…", ["the Blitz", "the Siege", "the Storm", "the Raid"], "the Blitz", 1),
      q("Churchill's secret WWII bunker is now the…", ["Churchill War Rooms", "Cabinet Vault", "Admiralty Cellar", "Whitehall Bunker"], "Churchill War Rooms", 1),
      q("London has hosted the Summer Olympics how many times?", ["three", "two", "four", "one"], "three", 2),
      q("The 2012 Olympic Park was built in which part of London?", ["Stratford", "Wembley", "Greenwich", "Battersea"], "Stratford", 2),
      q("Buckingham Palace is best known for which ceremony out front?", ["Changing of the Guard", "Ceremony of the Keys", "Beating Retreat", "Lord Mayor's Show"], "Changing of the Guard", 1),
      q("Trooping the Colour marks the monarch's…", ["official birthday", "coronation day", "wedding day", "first speech"], "official birthday", 1),
      q("The Mall runs from Trafalgar Square through Admiralty Arch to…", ["Buckingham Palace", "St Paul's", "Hyde Park Corner", "the Tower"], "Buckingham Palace", 2),
      q("The Tower of London's ceremonial guards are nicknamed…", ["Beefeaters", "Redcoats", "Grenadiers", "Bobbies"], "Beefeaters", 1),
      q("The Tower of London's water gate for prisoners is called…", ["Traitors' Gate", "Kings' Gate", "Bloody Gate", "Execution Arch"], "Traitors' Gate", 2),
      q("Tower Bridge opened in…", ["1894", "1825", "1936", "1851"], "1894", 2),
      q("Tower Bridge's roadway lifts because it is a…", ["bascule bridge", "swing bridge", "suspension bridge", "pontoon bridge"], "bascule bridge", 2),
      q("An old London Bridge was sold and rebuilt in…", ["Arizona", "Texas", "Florida", "Nevada"], "Arizona", 2),
      q("The Millennium Bridge earned which nickname when it opened?", ["the Wobbly Bridge", "the Glass Bridge", "the Silver Ribbon", "the Shaky Span"], "the Wobbly Bridge", 1),
      q("Piccadilly Circus is famous for its…", ["giant lit billboards", "Roman ruins", "royal stables", "riverboat pier"], "giant lit billboards", 1),
      q("Piccadilly Circus's winged statue is popularly called…", ["Eros", "Mercury", "Cupid's Arrow", "Victory"], "Eros", 2),
      q("Hyde Park's famous spot for open-air public speeches is…", ["Speakers' Corner", "Orators' Row", "Soapbox Hill", "Debate Lawn"], "Speakers' Corner", 1),
      q("The lake in Hyde Park is called the…", ["Serpentine", "Long Water", "Round Pond", "Mere"], "Serpentine", 1),
      q("A famous statue of Peter Pan stands in…", ["Kensington Gardens", "Regent's Park", "Hampstead Heath", "St James's Park"], "Kensington Gardens", 2),
      q("London Zoo is in…", ["Regent's Park", "Hyde Park", "Green Park", "Victoria Park"], "Regent's Park", 1),
      q("Kew Gardens in southwest London is a famous…", ["botanic garden", "royal palace", "racecourse", "cricket ground"], "botanic garden", 1),
      q("Hampton Court Palace is most associated with…", ["Henry VIII", "Queen Victoria", "Richard III", "George III"], "Henry VIII", 1),
      q("Hampton Court Palace's gardens are famous for a hedge…", ["maze", "tunnel", "castle", "zoo"], "maze", 2),
      q("Lambeth Palace is the London home of the…", ["Archbishop of Canterbury", "Prime Minister", "Lord Mayor", "Prince of Wales"], "Archbishop of Canterbury", 2),
      q("Westminster Abbey's section honoring writers is…", ["Poets' Corner", "Authors' Aisle", "Writers' Chapel", "Bards' Nave"], "Poets' Corner", 1),
      q("Karl Marx is buried in London's…", ["Highgate Cemetery", "Kensal Green", "Brompton Cemetery", "Abney Park"], "Highgate Cemetery", 2),
      q("Cleopatra's Needle on the Victoria Embankment is an ancient…", ["Egyptian obelisk", "Roman column", "Greek statue", "Celtic stone"], "Egyptian obelisk", 2),
      q("The Wimbledon Championships are played on…", ["grass", "clay", "hard court", "carpet"], "grass", 1),
      q("The classic snack at Wimbledon is strawberries and…", ["cream", "custard", "chocolate", "scones"], "cream", 1),
      q("Arsenal play their home matches at the…", ["Emirates Stadium", "Stamford Bridge", "Craven Cottage", "Selhurst Park"], "Emirates Stadium", 2),
      q("Chelsea play their home matches at…", ["Stamford Bridge", "White Hart Lane", "Loftus Road", "The Valley"], "Stamford Bridge", 2),
      q("Tottenham Hotspur's nickname is…", ["Spurs", "the Gunners", "the Hammers", "the Blues"], "Spurs", 1),
      q("West Ham United's nickname is…", ["the Hammers", "the Eagles", "the Cottagers", "the Bees"], "the Hammers", 2),
      q("The world's first underground railway opened in London in…", ["1863", "1890", "1900", "1837"], "1863", 2),
      q("The Tube's famous warning to passengers is…", ["Mind the gap", "Stand clear", "Watch your step", "Doors closing"], "Mind the gap", 1),
      q("The classic London Tube map was designed by…", ["Harry Beck", "Frank Pick", "Edward Johnston", "Isambard Brunel"], "Harry Beck", 2),
      q("London's blue contactless travel card is the…", ["Oyster card", "Octopus card", "Charlie Card", "Clipper card"], "Oyster card", 1),
      q("On the Tube map, the Central line is colored…", ["red", "yellow", "green", "brown"], "red", 2),
      q("The Crossrail project opened in 2022 as the…", ["Elizabeth line", "Victoria line", "Jubilee line", "Overground"], "Elizabeth line", 2),
      q("London black-cab drivers must pass a famous street test called…", ["the Knowledge", "the Map", "the Ring", "the Grid"], "the Knowledge", 1),
      q("London's classic open-platform double-decker bus is the…", ["Routemaster", "Roadrunner", "Metrobus", "Trolleyliner"], "Routemaster", 2),
      q("London's busiest airport is…", ["Heathrow", "Gatwick", "Stansted", "Luton"], "Heathrow", 1),
      q("Eurostar trains to Paris leave London from…", ["St Pancras", "Waterloo", "Victoria", "Paddington"], "St Pancras", 1),
      q("Harry Potter's Platform 9¾ is at which London station?", ["King's Cross", "Euston", "Paddington", "Liverpool Street"], "King's Cross", 1),
      q("Sherlock Holmes's fictional address is 221B…", ["Baker Street", "Fleet Street", "Oxford Street", "Downing Street"], "Baker Street", 1),
      q("A true Cockney is said to be born within earshot of the bells of…", ["St Mary-le-Bow", "St Paul's", "Westminster Abbey", "Southwark Cathedral"], "St Mary-le-Bow", 2),
      q("In Cockney rhyming slang, 'apples and pears' means…", ["stairs", "hair", "shoes", "money"], "stairs", 1),
      q("Jack the Ripper's 1888 murders took place in…", ["Whitechapel", "Mayfair", "Chelsea", "Hampstead"], "Whitechapel", 2),
      q("Which London street is famous for bespoke tailoring?", ["Savile Row", "Carnaby Street", "Bond Street", "Jermyn Street"], "Savile Row", 1),
      q("Fleet Street was long the home of Britain's…", ["newspapers", "banks", "theatres", "law courts"], "newspapers", 1),
      q("Harley Street is famous for its…", ["private doctors", "antique shops", "jazz clubs", "tailors"], "private doctors", 2),
      q("Carnaby Street was the heart of 1960s…", ["fashion", "banking", "publishing", "boxing"], "fashion", 2),
      q("The Beatles' most famous zebra crossing is on…", ["Abbey Road", "Penny Lane", "Carnaby Street", "Baker Street"], "Abbey Road", 1),
      q("Brick Lane in east London is known for curry houses and…", ["bagel shops", "car dealers", "ski stores", "toy makers"], "bagel shops", 2),
      q("London's Chinatown sits in…", ["Soho", "Shoreditch", "Brixton", "Camden"], "Soho", 1),
      q("Brixton's Electric Avenue inspired a hit song by…", ["Eddy Grant", "Bob Marley", "Billy Ocean", "UB40"], "Eddy Grant", 2),
      q("Portobello Road's famous street market is in…", ["Notting Hill", "Islington", "Hackney", "Brixton"], "Notting Hill", 1),
      q("Harrods department store is in…", ["Knightsbridge", "Mayfair", "Soho", "Holborn"], "Knightsbridge", 1),
      q("Hamleys, one of the world's oldest toy shops, is on…", ["Regent Street", "Oxford Street", "the Strand", "Kensington High Street"], "Regent Street", 2),
      q("The tea company trading on the Strand since 1706 is…", ["Twinings", "Whittard", "Tetley", "Lipton"], "Twinings", 3),
      q("Film premieres in London are often held in…", ["Leicester Square", "Sloane Square", "Russell Square", "Parliament Square"], "Leicester Square", 1),
      q("Agatha Christie's play that opened in London in 1952 is…", ["The Mousetrap", "Witness for the Prosecution", "Black Coffee", "The Hollow"], "The Mousetrap", 1),
      q("Canary Wharf is a business district on the…", ["Isle of Dogs", "Isle of Sheppey", "Eel Pie Island", "Isle of Wight"], "Isle of Dogs", 2),
      q("Which London tower is nicknamed the Gherkin?", ["30 St Mary Axe", "20 Fenchurch Street", "122 Leadenhall Street", "1 Undershaft"], "30 St Mary Axe", 2),
      q("20 Fenchurch Street is nicknamed the…", ["Walkie-Talkie", "Cheesegrater", "Gherkin", "Scalpel"], "Walkie-Talkie", 2),
      q("122 Leadenhall Street is nicknamed the…", ["Cheesegrater", "Walkie-Talkie", "Shard", "Can of Ham"], "Cheesegrater", 2),
      q("The Shard was designed by architect…", ["Renzo Piano", "Norman Foster", "Zaha Hadid", "Richard Rogers"], "Renzo Piano", 2),
      q("The Gherkin was designed by architect…", ["Norman Foster", "Renzo Piano", "Richard Rogers", "David Adjaye"], "Norman Foster", 2),
      q("Which architect designed the 'inside-out' Lloyd's building?", ["Richard Rogers", "Norman Foster", "Renzo Piano", "Denys Lasdun"], "Richard Rogers", 3),
      q("The BBC Proms summer concerts are held mainly at the…", ["Royal Albert Hall", "Barbican", "Royal Festival Hall", "Wigmore Hall"], "Royal Albert Hall", 1),
      q("The Natural History Museum's blue whale skeleton is named…", ["Hope", "Dippy", "Moby", "Grace"], "Hope", 2),
      q("The V&A museum is named for Queen Victoria and…", ["Prince Albert", "King Edward", "Lord Melbourne", "Prince George"], "Prince Albert", 1),
      q("Madame Tussauds in London is famous for its…", ["wax figures", "crown jewels", "dinosaur bones", "royal coaches"], "wax figures", 1),
      q("The Cutty Sark docked at Greenwich is a former…", ["tea clipper", "warship", "ocean liner", "royal yacht"], "tea clipper", 1),
      q("HMS Belfast, moored on the Thames, is a WWII…", ["cruiser", "submarine", "aircraft carrier", "battleship"], "cruiser", 2),
      q("The O2 arena was originally built as the…", ["Millennium Dome", "Festival Hall", "Crystal Palace", "Olympic Arena"], "Millennium Dome", 1),
      q("Battersea Power Station appears on the cover of Pink Floyd's…", ["Animals", "The Wall", "Meddle", "Wish You Were Here"], "Animals", 2),
      q("Who designed both Battersea Power Station and the red phone box?", ["Giles Gilbert Scott", "Edwin Lutyens", "John Soane", "George Gilbert Scott"], "Giles Gilbert Scott", 3),
      q("Blue plaques on London buildings mark where…", ["famous people lived", "bombs once fell", "plague pits lie", "rivers run below"], "famous people lived", 1),
      q("The last frost fair on the frozen Thames was held in…", ["1814", "1683", "1895", "1739"], "1814", 3),
      q("The 'Great Stink' of 1858 led Joseph Bazalgette to build London's…", ["sewers", "Tube", "bridges", "docks"], "sewers", 3),
      q("Little Venice is a London spot known for its…", ["canals", "gondolas", "glass domes", "island fort"], "canals", 2),
      q("Which East End dish is chopped eels set in their own stock?", ["jellied eels", "eel pie", "stargazy pie", "potted eels"], "jellied eels", 1),
      q("In 'bangers and mash', the bangers are…", ["sausages", "pork chops", "fish cakes", "meatballs"], "sausages", 1),
      q("Smithfield in the City of London is a centuries-old…", ["meat market", "fish market", "flower market", "horse fair"], "meat market", 2),
      q("On the London Monopoly board, the priciest square is…", ["Mayfair", "Park Lane", "Bond Street", "Piccadilly"], "Mayfair", 1),
      q("On the London Monopoly board, the cheapest square is…", ["Old Kent Road", "Whitechapel Road", "the Angel Islington", "Euston Road"], "Old Kent Road", 2),
      q("Greater London is split into the City of London plus how many boroughs?", ["32", "24", "28", "48"], "32", 2),
      q("The Lord Mayor's Show is a historic parade in the…", ["City of London", "West End", "Westminster", "East End"], "City of London", 2),
    ],
  },
};
