import { q } from "../quiz";
import { stampCityRecord } from "../rarity";
import type { CityId, TriviaCat, TriviaQ } from "../types";

export const CITY_EXTRA: Record<CityId, Partial<Record<TriviaCat, TriviaQ[]>>> = {
  austin: {
    local: [
      q("Sixth Street is Austin's famous…", ["river dam", "entertainment strip", "airport runway", "capitol lawn"], "entertainment strip", 1),
      q("The Drag in Austin is along…", ["Congress Avenue only", "Guadalupe Street by UT", "MoPac only", "Burnet Road only"], "Guadalupe Street by UT", 2),
      q("Rainey Street is a…", ["museum campus", "bungalow-bar district", "airport", "cemetery"], "bungalow-bar district", 2),
      q("Zilker Park hosts…", ["SXSW's only indoor halls", "the Austin City Limits Music Festival (among other things)", "the Texas State Fair as its main home", "the Houston Rodeo"], "the Austin City Limits Music Festival (among other things)", 2),
      q("Mount Bonnell looks over…", ["the Gulf", "Lake Austin / the western hills", "the Red River", "Caddo Lake"], "Lake Austin / the western hills", 1),
      q("The University of Texas tower is a…", ["capitol dome", "main-building landmark on campus", "church steeple of a parish", "lighthouse"], "main-building landmark on campus", 1),
      q("I-35 through Austin roughly splits…", ["north from the river only", "east and west", "the lakes from the hills as a beltway", "the airport from the capitol as a river"], "east and west", 2),
      q("Barton Creek feeds…", ["Lady Bird Lake from the east only", "Barton Springs", "Lake Travis as a dam", "the Pedernales only"], "Barton Springs", 2),
      q("The Pennybacker is a…", ["rail depot", "through-arch bridge on Loop 360", "capitol gate", "dam"], "through-arch bridge on Loop 360", 2),
      q("Mueller is a…", ["west-lake canyon", "redeveloped airport site on the east side", "UT dorm only", "state cemetery"], "redeveloped airport site on the east side", 3),
      q("East Austin's historic core includes…", ["Westlake hills only", "the 11th and 12th Street corridors", "Lakeway", "Bee Cave"], "the 11th and 12th Street corridors", 3),
      q("The Violet Crown is a nickname tied to Austin's…", ["capitol granite", "evening sky", "bat species", "football team"], "evening sky", 3),
    ],
    food: [
      q("Franklin Barbecue's line is famous for…", ["kolaches only", "brisket", "sushi", "cioppino"], "brisket", 1),
      q("A breakfast taco in Austin is often on a…", ["bagel only", "flour tortilla", "baguette", "lettuce wrap only"], "flour tortilla", 1),
      q("Torchy's is a local chain of…", ["brisket pits only", "taco shops", "donut shops only", "crawfish stands"], "taco shops", 2),
    ],
    arts: [
      q("ACL Live is a…", ["football stadium", "studio and theater on Willie Nelson Boulevard", "library", "courthouse"], "studio and theater on Willie Nelson Boulevard", 2),
      q("Willie Nelson is closely tied to which Texas city as a home base?", ["Amarillo", "Austin", "El Paso", "Beaumont"], "Austin", 1),
    ],
  },
  temple: {
    local: [
      q("Temple, Texas, sits in which county?", ["Travis", "Bell", "McLennan", "Williamson"], "Bell", 1),
      q("Temple grew as a…", ["port", "railroad town", "mining camp of silver", "whaling station"], "railroad town", 1),
      q("Temple is named for a…", ["Spanish missionary only", "railroad engineer, Bernard Moore Temple", "U.S. president", "Comanche chief"], "railroad engineer, Bernard Moore Temple", 2),
      q("Scott & White began as a…", ["fort", "railroad hospital", "university of music", "cotton gin only"], "railroad hospital", 2),
      q("Temple lies along which interstate between Austin and Waco?", ["I-10", "I-35", "I-45", "I-20"], "I-35", 1),
      q("Belton is Temple's…", ["port on the Gulf", "county-seat neighbor", "mountain suburb in the Rockies", "border crossing"], "county-seat neighbor", 2),
      q("Stillhouse Hollow and Belton Lake are…", ["Gulf bays", "reservoirs near Temple", "Great Lakes", "oxbows of the Mississippi only"], "reservoirs near Temple", 2),
      q("Temple College is a…", ["Ivy League university", "community college in town", "service academy", "conservatory in New York"], "community college in town", 1),
      q("The Santa Fe depot in Temple is a…", ["airport tower", "rail landmark downtown", "capitol", "lighthouse"], "rail landmark downtown", 1),
      q("Killeen and Fort Cavazos (Fort Hood) sit…", ["on the Gulf", "west of Temple in the same region", "in the Panhandle only", "in the Big Bend"], "west of Temple in the same region", 2),
    ],
    food: [
      q("Central Texas towns like Temple sit in the…", ["cioppino belt", "barbecue and kolache belt", "lobster-roll belt", "gumbo-only belt"], "barbecue and kolache belt", 1),
    ],
    sports: [
      q("Temple's high-school teams are the…", ["Longhorns", "Wildcats", "Bears of Baylor", "Aggies"], "Wildcats", 2),
    ],
  },
  nyc: {
    local: [
      q("New York City has how many boroughs?", ["4", "5", "6", "12"], "5", 1),
      q("The Staten Island Ferry is famous for being…", ["a toll tunnel only", "free", "a subway line under the harbor as its name", "a helipad"], "free", 1),
      q("The High Line is a…", ["subway line", "park on an old rail viaduct", "bridge to New Jersey", "airport"], "park on an old rail viaduct", 1),
      q("One World Trade Center's height in feet nods to…", ["1492", "1776", "1865", "2001"], "1776", 2),
      q("Central Park was designed by…", ["L'Enfant", "Olmsted and Vaux", "Burnham only", "Moses"], "Olmsted and Vaux", 2),
      q("The Brooklyn Bridge opened in…", ["1776", "1811", "1883", "1931"], "1883", 2),
      q("The subway's first IRT line opened in…", ["1863", "1904", "1932", "1950"], "1904", 3),
      q("Broadway as a street runs the length of…", ["only the Theater District as a three-block street", "Manhattan (and beyond)", "only Brooklyn", "only Staten Island"], "Manhattan (and beyond)", 2),
      q("Ellis Island is in…", ["the Hudson at Albany", "New York Harbor (shared jurisdiction lore with New Jersey)", "Long Island Sound only", "Jamaica Bay only"], "New York Harbor (shared jurisdiction lore with New Jersey)", 2),
      q("The Apollo Theater is in…", ["Greenwich Village", "Harlem", "DUMBO", "Riverdale"], "Harlem", 1),
      q("Wall Street is in…", ["Midtown only", "Lower Manhattan", "the Bronx", "Queens"], "Lower Manhattan", 1),
      q("Grand Central is in…", ["Downtown Brooklyn", "Midtown", "Harlem", "Staten Island"], "Midtown", 1),
      q("The Cloisters museum is in…", ["Coney Island", "Fort Tryon Park / northern Manhattan", "JFK", "Red Hook"], "Fort Tryon Park / northern Manhattan", 3),
      q("Rockefeller Center is in…", ["Battery Park", "Midtown", "Astoria", "Park Slope"], "Midtown", 1),
    ],
    arts: [
      q("Broadway theatre is concentrated around…", ["Wall Street", "Times Square / Midtown", "Coney Island", "the Cloisters"], "Times Square / Midtown", 1),
      q("MoMA is in…", ["Brooklyn Heights", "Midtown Manhattan", "Staten Island", "the Bronx Zoo grounds"], "Midtown Manhattan", 1),
    ],
    food: [
      q("A New York slice is typically…", ["deep-dish only", "wide, foldable, thin-crust pizza", "Detroit pan only", "a bagel"], "wide, foldable, thin-crust pizza", 1),
      q("A chopped cheese is a sandwich of…", ["only Staten Island diners", "Upper Manhattan / the Bronx bodegas", "only Long Island diners", "only New Jersey diners"], "Upper Manhattan / the Bronx bodegas", 3),
    ],
  },
  sf: {
    local: [
      q("The Golden Gate Bridge's color is officially…", ["gold leaf", "international orange", "navy blue", "forest green"], "international orange", 2),
      q("Alcatraz is in…", ["the Pacific a mile west of the Farallones", "San Francisco Bay", "Tahoe", "the Delta only"], "San Francisco Bay", 1),
      q("Lombard Street's crooked block is on…", ["Twin Peaks only", "Russian Hill", "Bayview only", "the Sunset only"], "Russian Hill", 2),
      q("The Castro is a historic…", ["financial district only", "LGBTQ+ neighborhood", "naval yard", "airport"], "LGBTQ+ neighborhood", 1),
      q("Mission District murals are concentrated on…", ["the Golden Gate's towers", "Balmy and Clarion alleys (among others)", "Alcatraz's rec yard only", "the Presidio golf greens only"], "Balmy and Clarion alleys (among others)", 3),
      q("The Presidio is a…", ["baseball park only", "former Army post, now a park", "university only", "subway yard"], "former Army post, now a park", 2),
      q("Coit Tower stands on…", ["Twin Peaks", "Telegraph Hill", "Mount Davidson", "Bernal Heights"], "Telegraph Hill", 2),
      q("The Embarcadero faces…", ["the ocean beach only", "the Bay", "the Santa Cruz mountains only", "Tahoe"], "the Bay", 1),
      q("Ocean Beach faces the…", ["Bay Bridge anchorage only", "Pacific", "Delta", "Carquinez"], "Pacific", 1),
      q("BART is the region's…", ["only cable-car company", "rapid-transit rail", "ferry-only system", "airport code"], "rapid-transit rail", 1),
      q("A San Francisco cable car is a…", ["subway", "moving-cable street railway", "monorail", "maglev"], "moving-cable street railway", 1),
      q("The Painted Ladies of Postcard Row face…", ["Oracle Park", "Alamo Square", "Fort Point", "Lands End only"], "Alamo Square", 2),
    ],
    food: [
      q("A Mission burrito is associated with…", ["the Castro", "San Francisco's Mission District", "North Beach", "Fisherman's Wharf"], "San Francisco's Mission District", 1),
      q("Cioppino on the wharf is a…", ["Mission burrito", "San Francisco seafood stew", "sourdough starter only", "Irish coffee only"], "San Francisco seafood stew", 2),
      q("Sourdough in San Francisco is famed for its…", ["absence of yeast of any kind as a legal definition", "wild starter and tang", "use of only baking powder", "corn masa"], "wild starter and tang", 1),
    ],
    arts: [
      q("City Lights Bookstore is in…", ["the Sunset", "North Beach", "Bayview", "Hunter's Point shipyard"], "North Beach", 2),
      q("The Fillmore is a…", ["baseball park", "historic music hall", "courthouse", "ferry"], "historic music hall", 2),
    ],
  },
  london: {
    local: [
      q("The Thames is tidal through…", ["Manchester", "London", "Birmingham", "Edinburgh"], "London", 1),
      q("The Tube is London's…", ["bus only", "underground railway", "airport", "river taxi"], "underground railway", 1),
      q("Big Ben is properly the…", ["whole Houses of Parliament", "Great Bell (the Elizabeth Tower holds it)", "Tower Bridge", "a palace at Kew"], "Great Bell (the Elizabeth Tower holds it)", 2),
      q("Tower Bridge is not the same as the…", ["Shard", "Tower of London", "London Eye", "Gherkin"], "Tower of London", 1),
      q("The Tower of London has long housed the…", ["Bank of England gold only", "Crown Jewels (among other uses)", "BBC archives only", "Wimbledon trophies only"], "Crown Jewels (among other uses)", 1),
      q("Westminster Abbey is a…", ["palace of the PM", "church of coronations and burials", "football ground", "market"], "church of coronations and burials", 1),
      q("The London Eye stands on the…", ["in Hyde Park", "South Bank", "at Greenwich", "in the City's square mile as a parish wheel"], "South Bank", 2),
      q("Greenwich is famed for the…", ["Tower ravens", "Prime Meridian and the old Royal Observatory", "Wembley only", "Heathrow only"], "Prime Meridian and the old Royal Observatory", 1),
      q("The City of London, legally, is…", ["all of Greater London as a legal identity of this name", "the historic square mile of finance", "only Westminster", "only Southwark"], "the historic square mile of finance", 2),
      q("Camden Market is in…", ["Greenwich", "north London", "Croydon only", "Heathrow"], "north London", 2),
      q("Notting Hill is famed for a…", ["hogmanay", "Carnival", "Hogwarts fan park", "highland games"], "Carnival", 2),
      q("The Shard is a…", ["bridge", "skyscraper", "market", "palace"], "skyscraper", 1),
    ],
    arts: [
      q("The West End is London's…", ["finance square mile only", "theatre district", "docklands only", "airport"], "theatre district", 1),
      q("Tate Modern is in a former…", ["palace", "power station", "cathedral", "prison only"], "power station", 2),
      q("The British Museum is in…", ["Greenwich", "Bloomsbury", "South Kensington only", "the City's guildhall"], "Bloomsbury", 2),
    ],
    food: [
      q("A full English breakfast often includes…", ["only croissants", "eggs, bacon, sausage, beans, tomato, toast (and more)", "only sushi", "only porridge as a legal definition"], "eggs, bacon, sausage, beans, tomato, toast (and more)", 1),
      q("Pie and mash is a…", ["Scots breakfast", "London working-class plate (eel liquor in the old shops)", "Welsh rarebit", "Irish stew"], "London working-class plate (eel liquor in the old shops)", 3),
    ],
  },
  chicago: {
    local: [
      q("The Loop is Chicago's…", ["lakefront beach only", "downtown core, named for the 'L'", "airport", "stockyard still operating"], "downtown core, named for the 'L'", 1),
      q("The 'L' is Chicago's…", ["commuter ferry", "elevated (and subway) rapid transit", "highway only", "riverwalk only"], "elevated (and subway) rapid transit", 1),
      q("Lake Michigan is to Chicago's…", ["west", "east", "only south", "only north as a river"], "east", 1),
      q("The Chicago River was famously reversed to flow…", ["into Lake Superior", "away from the lake (toward the Mississippi system)", "into the Ohio", "into the Gulf at Chicago"], "away from the lake (toward the Mississippi system)", 2),
      q("Millennium Park's Cloud Gate is nicknamed…", ["the Spike", "the Bean", "the Arch", "the Onion"], "the Bean", 1),
      q("The Willis Tower was long called the…", ["Hancock only", "Sears Tower", "Tribune Tower only", "Marina City"], "Sears Tower", 1),
      q("Wrigley Field is in…", ["the Loop only", "the North Side", "Hyde Park only", "Midway"], "the North Side", 1),
      q("Guaranteed Rate / Sox Park is on the…", ["North Side", "South Side", "in Evanston", "in Gary"], "South Side", 2),
      q("Navy Pier juts into…", ["the Chicago River", "Lake Michigan", "the Sanitary Canal only", "Lake Superior"], "Lake Michigan", 1),
      q("The Magnificent Mile is along…", ["State Street only", "Michigan Avenue", "Lake Shore Drive's whole length as a shopping mall", "Halsted only"], "Michigan Avenue", 2),
      q("Hyde Park is home to the…", ["only O'Hare", "University of Chicago (and the Museum of Science and Industry nearby)", "only Wrigley", "only Midway's terminals"], "University of Chicago (and the Museum of Science and Industry nearby)", 2),
      q("The Art Institute sits on…", ["the far South Side only", "Michigan Avenue downtown", "O'Hare", "Navy Pier"], "Michigan Avenue downtown", 1),
    ],
    food: [
      q("Chicago deep-dish is a…", ["thin New York slice", "tall, buttery-crust pizza", "Detroit pan", "a hot dog"], "tall, buttery-crust pizza", 1),
      q("A Chicago hot dog is not to be…", ["put in a bun", "ketchup'd (in the local commandment)", "given sport peppers", "given pickle"], "ketchup'd (in the local commandment)", 2),
      q("Italian beef is a Chicago…", ["deep-dish topping only", "thin-sliced roast-beef sandwich, often dipped", "hot dog", "rib tip only"], "thin-sliced roast-beef sandwich, often dipped", 1),
    ],
    arts: [
      q("Second City is a…", ["opera house only", "comedy theater / school", "football club", "newspaper only"], "comedy theater / school", 2),
      q("The Chicago Symphony plays in…", ["Wrigley", "Orchestra Hall", "the Bean as a hall", "O'Hare Terminal 5"], "Orchestra Hall", 2),
    ],
  },
  detroit: {
    local: [
      q("Windsor, Ontario faces Detroit across the…", ["the Rouge only", "the Detroit River", "the St. Clair", "the Hudson"], "the Detroit River", 1),
      q("Motown Records was founded in…", ["Chicago", "Detroit", "Cleveland", "Memphis"], "Detroit", 1),
      q("The Renaissance Center is a…", ["auto plant only in Dearborn", "riverfront tower cluster (GM's headquarters among tenants)", "baseball park", "airport"], "riverfront tower cluster (GM's headquarters among tenants)", 2),
      q("Belle Isle is a…", ["suburb in Ohio", "park island in the Detroit River", "factory in Flint", "lake in Michigan's U.P. only"], "park island in the Detroit River", 2),
      q("The Guardian Building is a…", ["auto plant", "Art Deco skyscraper downtown", "stadium", "bridge to Canada only"], "Art Deco skyscraper downtown", 3),
      q("Campus Martius is a…", ["Ford's Rouge plant", "downtown park / square", "airport", "cemetery of the auto barons only"], "downtown park / square", 2),
      q("The Ambassador Bridge links Detroit to…", ["Toledo", "Windsor, Ontario", "Cleveland", "Chicago"], "Windsor, Ontario", 1),
      q("A tunnel also links Detroit to…", ["Toronto", "Windsor", "Buffalo", "Montreal"], "Windsor", 2),
      q("Dearborn is home to…", ["GM's only plant", "Ford's historic Rouge and The Henry Ford", "Motown's Hitsville", "the Lions' original Tiger Stadium"], "Ford's historic Rouge and The Henry Ford", 2),
      q("Hitsville U.S.A. is the…", ["Renaissance Center", "original Motown house on West Grand", "Tiger Stadium", "the Guardian Building"], "original Motown house on West Grand", 2),
      q("The QLine is a…", ["people-mover in the suburbs only", "streetcar on Woodward", "ferry to Belle Isle", "highway"], "streetcar on Woodward", 3),
      q("Woodward Avenue is Detroit's famous…", ["international border crossing to Ohio", "north-south corridor toward the suburbs", "only airport runway", "only a freeway with no street name"], "north-south corridor toward the suburbs", 2),
    ],
    food: [
      q("Detroit-style pizza is…", ["a New York fold", "square, airy, and baked in a pan", "Chicago deep-dish", "a cone"], "square, airy, and baked in a pan", 1),
      q("A Coney dog in Detroit is a…", ["lobster roll", "chili dog in the local Greek-diner tradition", "Italian beef", "hot chicken"], "chili dog in the local Greek-diner tradition", 1),
    ],
    arts: [
      q("The Motown sound is built on…", ["only techno as Hitsville", "pop, soul, and a house band (the Funk Brothers)", "only punk of the Grande", "only gospel of the South"], "pop, soul, and a house band (the Funk Brothers)", 2),
      q("Detroit techno's early geography is…", ["only Berlin", "the city and its Black electronic musicians of the 1980s", "only Chicago house", "only Kraftwerk's studio in Düsseldorf as Detroit"], "the city and its Black electronic musicians of the 1980s", 3),
    ],
    sports: [
      q("The Lions play downtown at…", ["Comerica as football", "Ford Field", "Little Caesars as football only", "the old Silverdome still"], "Ford Field", 1),
      q("The Tigers play at…", ["Ford Field", "Comerica Park", "Joe Louis Arena still", "the Palace of Auburn Hills still"], "Comerica Park", 1),
    ],
  },
  tucson: {
    local: [
      q("Tucson sits in which desert?", ["the Mojave", "the Sonoran", "the Great Basin only", "the Chihuahuan"], "the Sonoran", 1),
      q("Saguaro National Park flanks Tucson on the…", ["only the north as a single unit", "east and west", "only the south as a park of organ pipe", "only the city center"], "east and west", 2),
      q("The University of Arizona is in…", ["Phoenix", "Tucson", "Flagstaff", "Yuma"], "Tucson", 1),
      q("Tucson's historic core includes…", ["only the airport", "the Presidio and downtown", "only Kitt Peak as downtown", "only Nogales"], "the Presidio and downtown", 2),
      q("Fourth Avenue is a…", ["interstate", "district of shops and the street fair", "dry river only", "mine"], "district of shops and the street fair", 2),
      q("The Santa Cruz River through Tucson is often…", ["a year-round barge canal", "dry at the surface", "a Great Lake", "tidal"], "dry at the surface", 2),
      q("Mount Lemmon is in the…", ["Grand Canyon", "Santa Catalinas", "White Mountains of N.H.", "Rockies of Colorado only"], "Santa Catalinas", 2),
      q("Kitt Peak is a…", ["ballpark", "observatory west of town", "capitol", "presidio of Spain still garrisoned"], "observatory west of town", 2),
      q("Tucson is in which county?", ["Maricopa", "Pima", "Coconino", "Yavapai"], "Pima", 2),
      q("The Tohono O'odham Nation borders Tucson to the…", ["only the Utah line", "west and south (among other lands)", "only New Mexico", "only California"], "west and south (among other lands)", 3),
      q("Old Tucson is a…", ["university", "movie-studio / park west of the city", "capitol", "airport"], "movie-studio / park west of the city", 3),
      q("Davis-Monthan is an…", ["naval yard", "Air Force base famed for the boneyard", "Army fort of cavalry only", "civilian only airport of Phoenix"], "Air Force base famed for the boneyard", 2),
    ],
    food: [
      q("Tucson is a UNESCO City of…", ["Music only", "Gastronomy", "Literature only", "Film only"], "Gastronomy", 2),
      q("Sonoran hot dogs are wrapped in…", ["only sauerkraut", "bacon and piled with beans, onion, tomato, mayo, mustard, jalapeño (the local stack)", "only chili of Cincinnati", "only ketchup"], "bacon and piled with beans, onion, tomato, mayo, mustard, jalapeño (the local stack)", 2),
      q("White Sonora wheat and mesquite are part of…", ["New England baking only", "the Borderlands food story", "Pacific Northwest salmon only", "Cajun roux only"], "the Borderlands food story", 3),
    ],
    nature: [
      q("A saguaro is a…", ["tree of the taiga", "tall columnar cactus of the Sonoran Desert", "kelp", "mangrove"], "tall columnar cactus of the Sonoran Desert", 1),
      q("The monsoon in southern Arizona is a…", ["winter only snow", "summer thunderstorm season", "year-round drizzle of Seattle", "hurricane of the Gulf as Tucson's weather"], "summer thunderstorm season", 2),
    ],
  },
  toronto: {
    local: [
      q("The CN Tower was built as a…", ["only a stadium", "communications and observation tower", "only a mall", "parliament"], "communications and observation tower", 1),
      q("Toronto sits on which Great Lake?", ["Superior", "Michigan", "Huron", "Ontario"], "Ontario", 1),
      q("The PATH is Toronto's…", ["subway", "downtown underground walkway", "airport code", "ferry to Niagara"], "downtown underground walkway", 2),
      q("Yonge Street is a…", ["only a subway yard", "long north–south artery (and a historic length boast)", "only a lake shore of Muskoka", "only a highway in Ottawa"], "long north–south artery (and a historic length boast)", 2),
      q("Queen's Park is the site of…", ["Parliament in Ottawa", "Ontario's legislature", "the CN Tower", "Casa Loma only"], "Ontario's legislature", 2),
      q("Casa Loma is a…", ["subway station only", "hilltop mansion / castle folly", "ballpark", "island airport terminal"], "hilltop mansion / castle folly", 2),
      q("The Distillery District is a…", ["financial tower cluster only", "Victorian industrial precinct turned arts and shops", "university campus of Waterloo", "port of Hamilton"], "Victorian industrial precinct turned arts and shops", 2),
      q("Toronto Islands lie in…", ["Lake Superior", "Lake Ontario, south of downtown", "Georgian Bay only", "the Ottawa River"], "Lake Ontario, south of downtown", 1),
      q("Billy Bishop is an…", ["only Pearson", "island airport downtown", "union station", "ferry to Rochester"], "island airport downtown", 2),
      q("Pearson is Toronto's…", ["island downtown strip", "main international airport", "union station", "CN Tower elevator"], "main international airport", 1),
      q("Union Station is the…", ["city hall", "main intercity and GO rail hub downtown", "CN Tower", "aquarium only"], "main intercity and GO rail hub downtown", 1),
      q("St. Lawrence Market is a…", ["stadium", "historic market downtown", "university", "island"], "historic market downtown", 2),
    ],
    food: [
      q("A peameal bacon sandwich is a…", ["Montreal smoked meat", "Toronto St. Lawrence classic", "poutine of Quebec", "beaver tail"], "Toronto St. Lawrence classic", 2),
      q("Toronto's Chinatown and Kensington are…", ["only suburbs of Mississauga as these names", "adjacent downtown food and shop districts", "only Ottawa", "only Niagara"], "adjacent downtown food and shop districts", 2),
    ],
    sports: [
      q("The Maple Leafs play hockey at…", ["Rogers Centre as hockey only", "Scotiabank Arena", "BMO Field", "the Gardens still"], "Scotiabank Arena", 1),
      q("The Blue Jays play at…", ["Scotiabank Arena", "Rogers Centre", "BMO Field", "Tim Hortons Field in Hamilton"], "Rogers Centre", 1),
    ],
    arts: [
      q("TIFF is a…", ["fashion week only", "film festival", "food fair only", "marathon"], "film festival", 1),
    ],
  },
  la: {
    local: [
      q("Los Angeles is in which county of the same name, plus it sprawls into…", ["the Bay Area as its county", "a basin and valleys of Southern California", "the Central Valley", "the Mojave as downtown"], "a basin and valleys of Southern California", 1),
      q("Hollywood is a…", ["separate city of Orange County", "district of Los Angeles", "neighborhood of Burbank", "part of Santa Monica only"], "district of Los Angeles", 1),
      q("The Hollywood Sign is mounted on…", ["Palos Verdes", "Mount Lee / the Hollywood Hills", "Catalina", "downtown's Bunker Hill only"], "Mount Lee / the Hollywood Hills", 2),
      q("Griffith Observatory looks over…", ["only Catalina as its view", "the basin and the Hollywood Sign", "only Palm Springs", "only San Diego"], "the basin and the Hollywood Sign", 1),
      q("Wilshire Boulevard runs…", ["only along the 405 as a loop", "from downtown toward the sea (the Miracle Mile among stretches)", "only in Orange County", "only in the Valley as a north–south"], "from downtown toward the sea (the Miracle Mile among stretches)", 2),
      q("Sunset Boulevard runs…", ["only in Long Beach", "from downtown through Hollywood toward the coast", "only in Pasadena as a freeway", "only to Palm Springs"], "from downtown through Hollywood toward the coast", 2),
      q("The 405 is a…", ["subway", "freeway through the Westside and Valley approaches", "river", "runway"], "freeway through the Westside and Valley approaches", 1),
      q("Union Station is in…", ["Santa Monica", "downtown L.A.", "LAX's terminals", "Pasadena only"], "downtown L.A.", 1),
      q("LAX is Los Angeles's…", ["only port", "main airport", "city hall", "subway yard"], "main airport", 1),
      q("The Port of Los Angeles is at…", ["Santa Monica Pier", "San Pedro / Wilmington", "Malibu", "Burbank"], "San Pedro / Wilmington", 2),
      q("Venice Beach is known for a…", ["container port", "boardwalk and muscle beach", "observatory", "studio backlot only"], "boardwalk and muscle beach", 1),
      q("Angels Flight downtown is a…", ["airport tram of LAX", "tiny funicular on Bunker Hill", "subway to Long Beach", "ferry to Catalina"], "tiny funicular on Bunker Hill", 3),
      q("Bunker Hill downtown was reshaped by…", ["only oil derricks still", "redevelopment towers and cultural buildings", "only a mission", "only a harbor"], "redevelopment towers and cultural buildings", 3),
      q("The L.A. River is a…", ["year-round barge canal to the Midwest", "mostly channelized watercourse through the basin", "Great Lake", "tidal fjord"], "mostly channelized watercourse through the basin", 2),
    ],
    food: [
      q("The French Dip's origin story is fought over by…", ["two stands in Austin", "Philippe's and Cole's in L.A.", "two shacks in New Orleans", "two carts in Portland"], "Philippe's and Cole's in L.A.", 3),
      q("A California burrito often includes…", ["only rice as a Mission clone", "fries", "only spaghetti", "only cole slaw"], "fries", 2),
      q("In-N-Out Burger was born in…", ["San Francisco", "the Los Angeles area (Baldwin Park)", "San Diego", "Sacramento"], "the Los Angeles area (Baldwin Park)", 2),
    ],
    arts: [
      q("The Getty Center campus sits in the…", ["downtown's river channel", "Santa Monica Mountains foothills / Brentwood side", "Long Beach port", "LAX"], "Santa Monica Mountains foothills / Brentwood side", 2),
      q("LACMA is on…", ["the Venice boardwalk", "Wilshire's Miracle Mile", "Catalina", "Pasadena's Rose Bowl"], "Wilshire's Miracle Mile", 2),
    ],
    sports: [
      q("Dodger Stadium sits in…", ["Inglewood", "Chavez Ravine", "Pasadena", "Long Beach"], "Chavez Ravine", 2),
      q("SoFi Stadium is in…", ["downtown L.A.", "Inglewood", "Pasadena", "Anaheim"], "Inglewood", 2),
    ],
  },
  boston: {
    local: [
      q("The Freedom Trail is a…", ["subway only", "walking line of Revolutionary sites", "highway to New York", "ferry to Provincetown only"], "walking line of Revolutionary sites", 1),
      q("Beacon Hill is known especially for…", ["the airport", "brick rows and the State House", "Fenway", "the harbor islands only"], "brick rows and the State House", 1),
      q("The Charles River in Boston faces…", ["Salem", "Cambridge (and others)", "Providence", "Worcester downtown"], "Cambridge (and others)", 1),
      q("The T is Boston's…", ["baseball team", "transit system (MBTA)", "university", "newspaper"], "transit system (MBTA)", 1),
      q("The Green Monster is a…", ["subway line", "left-field wall at Fenway", "harbor fort", "hill in Brookline only"], "left-field wall at Fenway", 1),
      q("Faneuil Hall is a…", ["ballpark", "meeting hall and market landmark", "university chapel only", "airport"], "meeting hall and market landmark", 1),
      q("The North End is Boston's historic…", ["Chinatown", "Italian district (among older layers)", "only the Seaport", "only Back Bay"], "Italian district (among older layers)", 2),
      q("Back Bay's streets are…", ["numbered like Manhattan only", "alphabetical from the Public Garden out (Arlington, Berkeley…)", "only alleys of the North End", "a cow-path with no plan"], "alphabetical from the Public Garden out (Arlington, Berkeley…)", 3),
      q("The Public Garden is next to the…", ["Fenway Park as a garden", "Boston Common", "Logan terminals", "Harvard Yard as a Boston park of this name"], "Boston Common", 1),
      q("Logan Airport sits in…", ["Cambridge", "East Boston", "Brookline", "Somerville"], "East Boston", 2),
      q("The Ted Williams Tunnel is part of the…", ["Green Monster", "Big Dig", "Freedom Trail as a tunnel", "T's Red Line"], "Big Dig", 2),
      q("Harvard is in…", ["Boston proper", "Cambridge", "Somerville", "Brookline"], "Cambridge", 1),
      q("MIT is in…", ["Boston's Back Bay", "Cambridge", "Quincy", "Salem"], "Cambridge", 1),
      q("The State House's dome is famously…", ["granite raw", "gilded", "glass", "thatch"], "gilded", 2),
    ],
    food: [
      q("Boston cream pie is a…", ["apple pie", "custard cake with chocolate glaze", "whoopie pie", "cannoli"], "custard cake with chocolate glaze", 1),
      q("A lobster roll in New England is often…", ["a deep-dish pizza", "warm butter or mayo on a split-top bun", "a Coney dog", "a po' boy of roast beef only"], "warm butter or mayo on a split-top bun", 1),
      q("Clam chowder in Boston is typically…", ["red Manhattan", "cream-based (New England)", "clear Rhode Island", "tomato only"], "cream-based (New England)", 1),
    ],
    arts: [
      q("The Boston Symphony plays in…", ["Fenway", "Symphony Hall", "Faneuil as a concert hall of this name", "the State House"], "Symphony Hall", 1),
      q("The MFA is the…", ["only Isabella Stewart Gardner", "Museum of Fine Arts, Boston", "only Harvard's Fogg", "only the ICA"], "Museum of Fine Arts, Boston", 2),
    ],
    sports: [
      q("The Celtics play at…", ["Fenway", "TD Garden", "Gillette", "Harvard Stadium"], "TD Garden", 1),
      q("The Bruins play at…", ["Fenway", "TD Garden", "Gillette", "Agganis Arena"], "TD Garden", 1),
    ],
  },
  nola: {
    local: [
      q("The French Quarter is also called the…", ["Garden District", "Vieux Carré", "Bywater", "Marigny"], "Vieux Carré", 2),
      q("Bourbon Street runs through the…", ["Garden District", "French Quarter", "Audubon Park only", "Metairie cemetery only"], "French Quarter", 1),
      q("Jackson Square faces…", ["only the lake", "the cathedral and the river", "only the airport", "only the Superdome"], "the cathedral and the river", 1),
      q("The Garden District is famed for…", ["the Quarter's balconies only", "antebellum houses and streetcars", "oil platforms", "only warehouses of the Bywater"], "antebellum houses and streetcars", 2),
      q("St. Charles Avenue is a…", ["interstate spur only", "streetcar line under oaks", "levee of the lake only", "runway"], "streetcar line under oaks", 1),
      q("The Mississippi at New Orleans is held by…", ["no banks", "levees", "only dunes", "fjords"], "levees", 1),
      q("Lake Pontchartrain is north of…", ["the Gulf as a lake of the Quarter", "the city", "Baton Rouge", "Houston"], "the city", 1),
      q("The Garden District's neighbor toward downtown includes the…", ["only the Rigolets", "Central Business District / Warehouse District", "only Chalmette as downtown", "only Kenner downtown"], "Central Business District / Warehouse District", 2),
      q("Congo Square is in…", ["the Garden District", "Louis Armstrong Park / Treme", "Metairie", "the West Bank"], "Louis Armstrong Park / Treme", 3),
      q("Treme is a historic…", ["only a suburb of Baton Rouge", "African American neighborhood next to the Quarter", "only the East as a new landfill", "only the river batture of Algiers"], "African American neighborhood next to the Quarter", 2),
      q("The West Bank is…", ["north of the lake only", "across the Mississippi from downtown", "the French Quarter's other name", "Baton Rouge"], "across the Mississippi from downtown", 2),
      q("Mardi Gras Indians are…", ["a tourist krewe from Dallas only", "Black masking traditions of the city", "a Carnival of Mobile", "a jazz funeral's only name"], "Black masking traditions of the city", 3),
      q("A jazz funeral often includes a…", ["ski jump", "second line", "ice palace", "tea ceremony"], "second line", 1),
      q("Above-ground tombs in New Orleans are a response in part to…", ["only fashion of Paris", "a high water table", "permafrost", "bedrock deeper than the Grand Canyon as a must"], "a high water table", 2),
    ],
    food: [
      q("A po' boy is a…", ["Chicago beef", "New Orleans sandwich on French bread", "lobster roll", "cheesesteak"], "New Orleans sandwich on French bread", 1),
      q("A muffuletta is stacked with…", ["only roast beef debris", "Italian meats, cheese, and olive salad", "only fried shrimp", "only white gravy"], "Italian meats, cheese, and olive salad", 2),
      q("Beignets at the Café du Monde are served with…", ["gravy", "powdered sugar", "chili", "syrup of cane"], "powdered sugar", 1),
      q("Gumbo is often thickened with…", ["only cornstarch", "roux, okra, and/or filé", "only gelatin", "only cream"], "roux, okra, and/or filé", 2),
      q("Jambalaya is a…", ["only a pastry", "rice dish of meat and the trinity", "only a cocktail", "only a salad of greens"], "rice dish of meat and the trinity", 1),
    ],
    arts: [
      q("Preservation Hall presents…", ["opera in Latin", "traditional New Orleans jazz", "only brass of marching D.C.", "only country of the Opry"], "traditional New Orleans jazz", 1),
      q("Congo Square is a historic site of…", ["only British musters", "African and Afro-Caribbean music and gathering", "only opera", "only film studios of Hollywood"], "African and Afro-Caribbean music and gathering", 2),
    ],
    sports: [
      q("The Saints play at the…", ["Smoothie King as football only", "Caesars Superdome", "Tad Gormley", "Tulane's old home"], "Caesars Superdome", 1),
    ],
  },
};

stampCityRecord(CITY_EXTRA);

