import { q } from "../quiz";
import type { CityId, TriviaCat, TriviaQ } from "../types";

/**
 * Local trivia card backlog, batch 2 (v0.0.27): Detroit, London, Austin, Temple, Tucson.
 * Thinnest cities first. Easy cards are difficulty 1 so they band white.
 * Merged into CITY_EXTRA by cities.ts (rarity stamped there with the city nudge).
 */
export const CITY_EXTRA_PART_E: Partial<Record<CityId, Partial<Record<TriviaCat, TriviaQ[]>>>> = {
  detroit: {
    local: [
      q("Detroit's best-known nickname is…", ["the Motor City", "the Steel City", "the Windy City", "the Big Easy"], "the Motor City", 1),
      q("The name 'Motown' is short for…", ["Motor Town", "Motor Tunes", "Model Town", "Mo' Town Sound"], "Motor Town", 1),
      q("Locals often shorten Detroit's name to…", ["the D", "the Big D", "the Lou", "the Nati"], "the D", 1),
      q("Detroit's original area code is…", ["313", "312", "216", "414"], "313", 1),
      q("Detroit was founded by the French in…", ["1701", "1776", "1805", "1650"], "1701", 2),
      q("Detroit's founder was…", ["Antoine de la Mothe Cadillac", "Jacques Marquette", "Samuel de Champlain", "Louis Jolliet"], "Antoine de la Mothe Cadillac", 2),
      q("The Cadillac car brand is named after…", ["Detroit's founder", "a French king", "a racehorse", "a Michigan lake"], "Detroit's founder", 1),
      q("The name 'Detroit' comes from a French word for…", ["strait", "riverbank", "red earth", "trading post"], "strait", 2),
      q("A fire nearly wiped out the town of Detroit in…", ["1805", "1871", "1763", "1837"], "1805", 2),
      q("Detroit's motto 'Resurget cineribus' means…", ["it will rise from the ashes", "it will build in steel", "it stands by the water", "it moves the world"], "it will rise from the ashes", 2),
      q("After the 1805 fire, Augustus Woodward's street plan was modeled on…", ["Washington, D.C.", "Paris", "London", "Philadelphia"], "Washington, D.C.", 3),
      q("Odawa leader Pontiac laid siege to Fort Detroit in…", ["1763", "1701", "1812", "1796"], "1763", 3),
      q("In 1812, General William Hull surrendered Detroit to the…", ["British", "French", "Spanish", "Dutch"], "British", 2),
      q("Until 1847, Michigan's state capital was…", ["Detroit", "Lansing", "Ann Arbor", "Grand Rapids"], "Detroit", 2),
      q("On the Underground Railroad, Detroit's code name was…", ["Midnight", "Canaan", "Jordan", "Daybreak"], "Midnight", 3),
      q("From downtown Detroit, Windsor, Canada, lies to the…", ["south", "north", "east", "west"], "south", 1),
      q("The Ambassador Bridge is unusual because it is…", ["privately owned", "made of wood", "a toll-free span", "a drawbridge"], "privately owned", 3),
      q("Beneath Detroit lies a huge underground mine of…", ["salt", "coal", "copper", "iron ore"], "salt", 2),
      q("The J.W. Westcott II on the Detroit River is a mail boat with its own…", ["ZIP code", "lighthouse", "post office bank", "customs flag"], "ZIP code", 3),
      q("Ford's Model T was first built at Detroit's…", ["Piquette Avenue Plant", "River Rouge Complex", "Willow Run plant", "Highland Park plant"], "Piquette Avenue Plant", 2),
      q("Ford's moving assembly line started in 1913 at its plant in…", ["Highland Park", "Dearborn", "Flint", "Pontiac"], "Highland Park", 2),
      q("In 1914 Ford stunned workers with a daily wage of…", ["$5", "$1", "$10", "$3"], "$5", 2),
      q("Detroit's traditional 'Big Three' automakers are GM, Ford, and…", ["Chrysler", "Toyota", "Studebaker", "Packard"], "Chrysler", 1),
      q("The Detroit architect famed for Ford's factories was…", ["Albert Kahn", "Louis Kahn", "Eero Saarinen", "Minoru Yamasaki"], "Albert Kahn", 2),
      q("In World War II, Detroit's factories earned it the nickname…", ["the Arsenal of Democracy", "the Forge of Freedom", "the Engine of Victory", "the Workshop of War"], "the Arsenal of Democracy", 1),
      q("Ford's Willow Run plant near Detroit built which WWII bomber?", ["B-24 Liberator", "B-17 Flying Fortress", "B-29 Superfortress", "B-25 Mitchell"], "B-24 Liberator", 3),
      q("The UAW, based in Detroit, is a…", ["labor union", "racing league", "safety agency", "dealer group"], "labor union", 1),
      q("Which leader headed the UAW from 1946 to 1970?", ["Walter Reuther", "John L. Lewis", "Jimmy Hoffa", "Eugene Debs"], "Walter Reuther", 2),
      q("Detroit's population peaked around 1950 at nearly…", ["1.85 million", "3 million", "900,000", "5 million"], "1.85 million", 3),
      q("In 2013 Detroit made history with the largest U.S. city…", ["bankruptcy", "blackout", "strike", "flood"], "bankruptcy", 2),
      q("Detroit's 1967 uprising began after a police raid on…", ["12th Street", "8 Mile Road", "Woodward Avenue", "Gratiot Avenue"], "12th Street", 3),
      q("Woodward Avenue is also the state highway numbered…", ["M-1", "I-75", "US-12", "M-10"], "M-1", 2),
      q("In 1909, the first mile of concrete road in the U.S. was laid on Detroit's…", ["Woodward Avenue", "Michigan Avenue", "Jefferson Avenue", "Grand River Avenue"], "Woodward Avenue", 3),
      q("Detroit police officer William Potts is credited with the first…", ["three-color traffic light", "police radio car", "parking meter", "stop sign"], "three-color traffic light", 3),
      q("The Woodward Dream Cruise celebrates…", ["classic cars", "jazz bands", "speedboats", "hot-air balloons"], "classic cars", 1),
      q("The People Mover is Detroit's…", ["elevated downtown loop", "underground subway", "river ferry line", "hillside cable car"], "elevated downtown loop", 1),
      q("Eastern Market in Detroit is a big historic…", ["public market", "car museum", "jazz club", "sports arena"], "public market", 1),
      q("Which downtown Detroit district is known for Greek restaurants and a casino?", ["Greektown", "Corktown", "Mexicantown", "Midtown"], "Greektown", 1),
      q("Corktown was named for Irish immigrants from…", ["County Cork", "County Kerry", "Dublin", "Galway"], "County Cork", 1),
      q("Detroit's oldest surviving neighborhood is…", ["Corktown", "Brush Park", "Midtown", "Indian Village"], "Corktown", 2),
      q("Which automaker restored Michigan Central Station?", ["Ford", "GM", "Chrysler", "Tesla"], "Ford", 1),
      q("Which university anchors Detroit's Midtown?", ["Wayne State", "Michigan State", "Eastern Michigan", "Oakland University"], "Wayne State", 1),
      q("The Dequindre Cut is a greenway built on an old…", ["rail line", "canal", "highway", "streetcar barn"], "rail line", 2),
      q("Detroit's riverfront trail is called the…", ["RiverWalk", "Lakeshore Path", "Strait Trail", "Harbor Line"], "RiverWalk", 1),
      q("Belle Isle's park plan was drawn by Central Park's co-designer…", ["Frederick Law Olmsted", "Daniel Burnham", "Pierre L'Enfant", "Jens Jensen"], "Frederick Law Olmsted", 3),
      q("Belle Isle's grand marble fountain is the…", ["James Scott Memorial Fountain", "Buckingham Fountain", "Dodge Fountain", "Bethesda Fountain"], "James Scott Memorial Fountain", 2),
      q("Hart Plaza's ring-shaped Dodge Fountain was designed by…", ["Isamu Noguchi", "Alexander Calder", "Henry Moore", "Louise Nevelson"], "Isamu Noguchi", 3),
      q("Hart Plaza hosts which electronic music festival each May?", ["Movement", "Ultra", "Coachella", "Lollapalooza"], "Movement", 2),
      q("Detroit's free Labor Day weekend festival is devoted to…", ["jazz", "techno", "blues", "folk"], "jazz", 2),
      q("Detroit's big late-November holiday parade is called…", ["America's Thanksgiving Parade", "the Motor City Parade", "the Great Lakes Parade", "the Turkey Trot Parade"], "America's Thanksgiving Parade", 2),
      q("The Spirit of Detroit statue stands outside the…", ["municipal center", "train station", "art museum", "auto plant"], "municipal center", 2),
      q("The Spirit of Detroit statue was sculpted by…", ["Marshall Fredericks", "Augustus Saint-Gaudens", "Daniel Chester French", "Robert Graham"], "Marshall Fredericks", 3),
      q("Michigan's tallest building is the central tower of the…", ["Renaissance Center", "Guardian Building", "Penobscot Building", "Fisher Building"], "Renaissance Center", 2),
      q("The Guardian Building is nicknamed the…", ["Cathedral of Finance", "Tower of Power", "Jewel of Woodward", "Temple of Trade"], "Cathedral of Finance", 2),
      q("The golden-roofed Art Deco tower in New Center is the…", ["Fisher Building", "Guardian Building", "Book Tower", "Buhl Building"], "Fisher Building", 2),
      q("Detroit's Masonic Temple is famous as the world's…", ["largest Masonic temple", "oldest opera house", "tallest church", "first movie palace"], "largest Masonic temple", 2),
      q("Lafayette Park holds the world's largest collection of buildings by…", ["Mies van der Rohe", "Frank Lloyd Wright", "Le Corbusier", "Walter Gropius"], "Mies van der Rohe", 3),
      q("Downtown Hudson's, demolished in 1998, was once the world's tallest…", ["department store", "parking garage", "hotel", "office tower"], "department store", 3),
      q("Ford Field was built around an old warehouse of…", ["Hudson's", "Ford", "Stroh's", "Kresge"], "Hudson's", 3),
      q("Outside the Detroit Institute of Arts sits a cast of Rodin's…", ["The Thinker", "The Kiss", "The Gates of Hell", "Balzac"], "The Thinker", 2),
      q("Detroit's Charles H. Wright Museum focuses on…", ["African American history", "auto design", "Great Lakes ships", "modern art"], "African American history", 1),
      q("Pewabic, founded in Detroit in 1903, is famous for…", ["art pottery and tiles", "stained glass", "car horns", "leather saddles"], "art pottery and tiles", 2),
      q("Rosa Parks spent most of her later life in…", ["Detroit", "Atlanta", "Chicago", "Memphis"], "Detroit", 2),
      q("The bus from Rosa Parks's protest is displayed at…", ["The Henry Ford", "the DIA", "the Smithsonian", "the Wright Museum"], "The Henry Ford", 1),
      q("Greenfield Village in Dearborn is an outdoor…", ["history museum", "car factory", "golf resort", "zoo"], "history museum", 1),
      q("The Arab American National Museum is in…", ["Dearborn", "Hamtramck", "Royal Oak", "Southfield"], "Dearborn", 2),
      q("Which two cities sit almost entirely inside Detroit?", ["Hamtramck and Highland Park", "Dearborn and Warren", "Ferndale and Troy", "Livonia and Novi"], "Hamtramck and Highland Park", 3),
      q("On Fat Tuesday, Hamtramck lines up for which Polish pastry?", ["paczki", "kolaches", "pierogi", "babka"], "paczki", 1),
      q("The Detroit Zoo is actually located in…", ["Royal Oak", "Dearborn", "Ferndale", "Grosse Pointe"], "Royal Oak", 2),
      q("Motown's Studio A at Hitsville was nicknamed…", ["the Snakepit", "the Fishbowl", "the Engine Room", "the Hit Factory"], "the Snakepit", 3),
      q("In 1972 Motown moved its headquarters to…", ["Los Angeles", "New York", "Chicago", "Nashville"], "Los Angeles", 2),
      q("Diana Ross first rose to fame with which Motown group?", ["the Supremes", "the Marvelettes", "the Vandellas", "the Shirelles"], "the Supremes", 1),
      q("Smokey Robinson led which Motown group?", ["the Miracles", "the Temptations", "the Four Tops", "the Contours"], "the Miracles", 1),
      q("'Dancing in the Street' was a Motown hit for…", ["Martha and the Vandellas", "the Supremes", "Gladys Knight & the Pips", "the Four Tops"], "Martha and the Vandellas", 2),
      q("Aretha Franklin's father pastored which Detroit church?", ["New Bethel Baptist", "Second Baptist", "Hartford Memorial", "Greater Grace Temple"], "New Bethel Baptist", 3),
      q("Detroit techno's 'Belleville Three' included…", ["Juan Atkins", "Frankie Knuckles", "Afrika Bambaataa", "Larry Levan"], "Juan Atkins", 3),
      q("Eminem's semi-autobiographical Detroit film is titled…", ["8 Mile", "Purple Rain", "Hustle & Flow", "Straight Outta Compton"], "8 Mile", 1),
      q("Jack and Meg White's Detroit rock duo was…", ["the White Stripes", "the Black Keys", "the Strokes", "the Kills"], "the White Stripes", 1),
      q("'Kick Out the Jams' was a 1969 anthem by Detroit-area band…", ["MC5", "the Stooges", "Grand Funk", "Bob Seger"], "MC5", 3),
      q("Gordon Lightfoot's song that mentions a Detroit church is about…", ["the Edmund Fitzgerald", "the Titanic", "the Lusitania", "the Andrea Doria"], "the Edmund Fitzgerald", 2),
      q("Thanks to the Red Wings, Detroit calls itself…", ["Hockeytown", "Puckville", "Ice City", "Rinktown"], "Hockeytown", 1),
      q("The Red Wings' logo is a…", ["winged wheel", "red hawk", "flying puck", "winged star"], "winged wheel", 1),
      q("Red Wings fans famously toss which animal onto the ice?", ["octopus", "rat", "catfish", "squid"], "octopus", 1),
      q("The Red Wings octopus's eight arms first stood for…", ["eight playoff wins", "eight players", "eight goals", "eight decades"], "eight playoff wins", 2),
      q("Gordie Howe, the Red Wings legend, was nicknamed…", ["Mr. Hockey", "the Great One", "Super Mario", "the Rocket"], "Mr. Hockey", 1),
      q("The late-1980s Pistons were nicknamed the…", ["Bad Boys", "Showtime", "Fab Five", "Big Three"], "Bad Boys", 1),
      q("The Bad Boys Pistons were led by point guard…", ["Isiah Thomas", "Magic Johnson", "John Stockton", "Mark Price"], "Isiah Thomas", 2),
      q("The Pistons won back-to-back NBA titles in…", ["1989 and 1990", "1985 and 1986", "1991 and 1992", "1995 and 1996"], "1989 and 1990", 2),
      q("Before Detroit, the Pistons franchise played in…", ["Fort Wayne", "Indianapolis", "Toledo", "Grand Rapids"], "Fort Wayne", 2),
      q("Before moving downtown in 2017, the Pistons played at the Palace of…", ["Auburn Hills", "Royal Oak", "Southfield", "Troy"], "Auburn Hills", 2),
      q("Little Caesars Arena is home to the Red Wings and the…", ["Pistons", "Lions", "Tigers", "Shock"], "Pistons", 1),
      q("The Ilitch family behind the Tigers and Red Wings founded…", ["Little Caesars", "Domino's", "Better Made", "Faygo"], "Little Caesars", 2),
      q("Old Tiger Stadium stood at the corner of Michigan and…", ["Trumbull", "Woodward", "Gratiot", "Grand River"], "Trumbull", 2),
      q("Which batting legend played 22 seasons for the Tigers?", ["Ty Cobb", "Babe Ruth", "Honus Wagner", "Cy Young"], "Ty Cobb", 2),
      q("The 1984 champion Tigers were managed by…", ["Sparky Anderson", "Tommy Lasorda", "Earl Weaver", "Billy Martin"], "Sparky Anderson", 3),
      q("Ernie Harwell was the longtime radio voice of the…", ["Tigers", "Lions", "Pistons", "Red Wings"], "Tigers", 2),
      q("The Lions famously host a game every year on…", ["Thanksgiving", "Christmas", "New Year's Day", "Labor Day"], "Thanksgiving", 1),
      q("Which running back starred for the Lions in the 1990s?", ["Barry Sanders", "Emmitt Smith", "Walter Payton", "Eric Dickerson"], "Barry Sanders", 1),
      q("Before Ford Field, the Lions played in the…", ["Pontiac Silverdome", "Astrodome", "Metrodome", "Kingdome"], "Pontiac Silverdome", 2),
      q("Boxer Joe Louis, who grew up in Detroit, was nicknamed…", ["the Brown Bomber", "the Greatest", "Iron Mike", "Sugar Ray"], "the Brown Bomber", 2),
      q("Detroit-style pizza was born in 1946 at…", ["Buddy's", "Shield's", "Jet's", "Loui's"], "Buddy's", 2),
      q("Detroit-style pizza was first baked in pans meant for…", ["auto parts", "bread loaves", "cake sheets", "roasting meat"], "auto parts", 2),
      q("Two rival Coney spots sit side by side downtown: American and…", ["Lafayette", "National", "Duly's", "Leo's"], "Lafayette", 2),
      q("Detroit's Sanders brand is best known for its…", ["hot fudge", "potato chips", "ginger ale", "coney sauce"], "hot fudge", 2),
      q("'Detroit vs. Everybody' is a popular local…", ["slogan apparel line", "rap battle show", "football rivalry", "radio station"], "slogan apparel line", 1),
    ],
  },
  london: {
    local: [
      q("The Romans founded London under the name…", ["Londinium", "Lugdunum", "Eboracum", "Camulodunum"], "Londinium", 1),
      q("Which warrior queen burned Roman London around AD 60?", ["Boudica", "Cleopatra", "Zenobia", "Matilda"], "Boudica", 2),
      q("The Great Fire of London broke out in…", ["1666", "1066", "1605", "1750"], "1666", 1),
      q("The Great Fire of London started in a bakery on…", ["Pudding Lane", "Fleet Street", "Baker Street", "Drury Lane"], "Pudding Lane", 1),
      q("The Monument near London Bridge commemorates…", ["the Great Fire", "the Battle of Hastings", "the Blitz", "Waterloo"], "the Great Fire", 1),
      q("How many steps climb to the top of the Monument?", ["311", "205", "530", "128"], "311", 3),
      q("St Paul's Cathedral was rebuilt after the Great Fire by…", ["Christopher Wren", "Inigo Jones", "John Nash", "Charles Barry"], "Christopher Wren", 1),
      q("St Paul's dome gallery famous for carrying quiet voices is the…", ["Whispering Gallery", "Echo Chamber", "Golden Gallery", "Stone Gallery"], "Whispering Gallery", 1),
      q("Prince Charles and Lady Diana married in 1981 at…", ["St Paul's Cathedral", "Westminster Abbey", "Windsor Castle", "St George's Chapel"], "St Paul's Cathedral", 2),
      q("Guy Fawkes tried to blow up Parliament in…", ["1605", "1666", "1588", "1215"], "1605", 1),
      q("Bonfire Night in Britain falls on…", ["5 November", "31 October", "1 May", "23 April"], "5 November", 1),
      q("The German bombing of London in 1940–41 is known as…", ["the Blitz", "the Siege", "the Storm", "the Raid"], "the Blitz", 1),
      q("Churchill's secret WWII bunker is now the…", ["Churchill War Rooms", "Cabinet Vault", "Admiralty Cellar", "Whitehall Bunker"], "Churchill War Rooms", 1),
      q("London has hosted the Summer Olympics how many times?", ["three", "two", "four", "one"], "three", 2),
      q("The 2012 Olympic Park was built in which part of London?", ["Stratford", "Wembley", "Greenwich", "Battersea"], "Stratford", 2),
      q("Buckingham Palace is best known for which ceremony out front?", ["Changing of the Guard", "Ceremony of the Keys", "Beating Retreat", "Lord Mayor's Show"], "Changing of the Guard", 1),
      q("Trooping the Colour marks the monarch's…", ["official birthday", "coronation day", "wedding day", "first speech"], "official birthday", 1),
      q("The Mall runs from Trafalgar Square through Admiralty Arch to…", ["Buckingham Palace", "St Paul's", "Hyde Park Corner", "the Tower"], "Buckingham Palace", 2),
      q("The Tower of London's ceremonial guards are nicknamed…", ["Beefeaters", "Redcoats", "Grenadiers", "Bobbies"], "Beefeaters", 1),
      q("The Tower of London's water gate for prisoners is called…", ["Traitors' Gate", "Kings' Gate", "Bloody Gate", "Execution Arch"], "Traitors' Gate", 2),
      q("Tower Bridge opened in…", ["1894", "1825", "1936", "1851"], "1894", 2),
      q("Tower Bridge's roadway lifts because it is a…", ["bascule bridge", "swing bridge", "suspension bridge", "pontoon bridge"], "bascule bridge", 2),
      q("An old London Bridge was sold and rebuilt in…", ["Arizona", "Texas", "Florida", "Nevada"], "Arizona", 2),
      q("The Millennium Bridge earned which nickname when it opened?", ["the Wobbly Bridge", "the Glass Bridge", "the Silver Ribbon", "the Shaky Span"], "the Wobbly Bridge", 1),
      q("Piccadilly Circus is famous for its…", ["giant lit billboards", "Roman ruins", "royal stables", "riverboat pier"], "giant lit billboards", 1),
      q("Piccadilly Circus's winged statue is popularly called…", ["Eros", "Mercury", "Cupid's Arrow", "Victory"], "Eros", 2),
      q("Hyde Park's famous spot for open-air public speeches is…", ["Speakers' Corner", "Orators' Row", "Soapbox Hill", "Debate Lawn"], "Speakers' Corner", 1),
      q("The lake in Hyde Park is called the…", ["Serpentine", "Long Water", "Round Pond", "Mere"], "Serpentine", 1),
      q("A famous statue of Peter Pan stands in…", ["Kensington Gardens", "Regent's Park", "Hampstead Heath", "St James's Park"], "Kensington Gardens", 2),
      q("London Zoo is in…", ["Regent's Park", "Hyde Park", "Green Park", "Victoria Park"], "Regent's Park", 1),
      q("Kew Gardens in southwest London is a famous…", ["botanic garden", "royal palace", "racecourse", "cricket ground"], "botanic garden", 1),
      q("Hampton Court Palace is most associated with…", ["Henry VIII", "Queen Victoria", "Richard III", "George III"], "Henry VIII", 1),
      q("Hampton Court Palace's gardens are famous for a hedge…", ["maze", "tunnel", "castle", "zoo"], "maze", 2),
      q("Lambeth Palace is the London home of the…", ["Archbishop of Canterbury", "Prime Minister", "Lord Mayor", "Prince of Wales"], "Archbishop of Canterbury", 2),
      q("Westminster Abbey's section honoring writers is…", ["Poets' Corner", "Authors' Aisle", "Writers' Chapel", "Bards' Nave"], "Poets' Corner", 1),
      q("Karl Marx is buried in London's…", ["Highgate Cemetery", "Kensal Green", "Brompton Cemetery", "Abney Park"], "Highgate Cemetery", 2),
      q("Cleopatra's Needle on the Victoria Embankment is an ancient…", ["Egyptian obelisk", "Roman column", "Greek statue", "Celtic stone"], "Egyptian obelisk", 2),
      q("The Wimbledon Championships are played on…", ["grass", "clay", "hard court", "carpet"], "grass", 1),
      q("The classic snack at Wimbledon is strawberries and…", ["cream", "custard", "chocolate", "scones"], "cream", 1),
      q("Arsenal play their home matches at the…", ["Emirates Stadium", "Stamford Bridge", "Craven Cottage", "Selhurst Park"], "Emirates Stadium", 2),
      q("Chelsea play their home matches at…", ["Stamford Bridge", "White Hart Lane", "Loftus Road", "The Valley"], "Stamford Bridge", 2),
      q("Tottenham Hotspur's nickname is…", ["Spurs", "the Gunners", "the Hammers", "the Blues"], "Spurs", 1),
      q("West Ham United's nickname is…", ["the Hammers", "the Eagles", "the Cottagers", "the Bees"], "the Hammers", 2),
      q("The world's first underground railway opened in London in…", ["1863", "1890", "1900", "1837"], "1863", 2),
      q("The Tube's famous warning to passengers is…", ["Mind the gap", "Stand clear", "Watch your step", "Doors closing"], "Mind the gap", 1),
      q("The classic London Tube map was designed by…", ["Harry Beck", "Frank Pick", "Edward Johnston", "Isambard Brunel"], "Harry Beck", 2),
      q("London's blue contactless travel card is the…", ["Oyster card", "Octopus card", "Charlie Card", "Clipper card"], "Oyster card", 1),
      q("On the Tube map, the Central line is colored…", ["red", "yellow", "green", "brown"], "red", 2),
      q("The Crossrail project opened in 2022 as the…", ["Elizabeth line", "Victoria line", "Jubilee line", "Overground"], "Elizabeth line", 2),
      q("London black-cab drivers must pass a famous street test called…", ["the Knowledge", "the Map", "the Ring", "the Grid"], "the Knowledge", 1),
      q("London's classic open-platform double-decker bus is the…", ["Routemaster", "Roadrunner", "Metrobus", "Trolleyliner"], "Routemaster", 2),
      q("London's busiest airport is…", ["Heathrow", "Gatwick", "Stansted", "Luton"], "Heathrow", 1),
      q("Eurostar trains to Paris leave London from…", ["St Pancras", "Waterloo", "Victoria", "Paddington"], "St Pancras", 1),
      q("Harry Potter's Platform 9¾ is at which London station?", ["King's Cross", "Euston", "Paddington", "Liverpool Street"], "King's Cross", 1),
      q("Sherlock Holmes's fictional address is 221B…", ["Baker Street", "Fleet Street", "Oxford Street", "Downing Street"], "Baker Street", 1),
      q("A true Cockney is said to be born within earshot of the bells of…", ["St Mary-le-Bow", "St Paul's", "Westminster Abbey", "Southwark Cathedral"], "St Mary-le-Bow", 2),
      q("In Cockney rhyming slang, 'apples and pears' means…", ["stairs", "hair", "shoes", "money"], "stairs", 1),
      q("Jack the Ripper's 1888 murders took place in…", ["Whitechapel", "Mayfair", "Chelsea", "Hampstead"], "Whitechapel", 2),
      q("Which London street is famous for bespoke tailoring?", ["Savile Row", "Carnaby Street", "Bond Street", "Jermyn Street"], "Savile Row", 1),
      q("Fleet Street was long the home of Britain's…", ["newspapers", "banks", "theatres", "law courts"], "newspapers", 1),
      q("Harley Street is famous for its…", ["private doctors", "antique shops", "jazz clubs", "tailors"], "private doctors", 2),
      q("Carnaby Street was the heart of 1960s…", ["fashion", "banking", "publishing", "boxing"], "fashion", 2),
      q("The Beatles' most famous zebra crossing is on…", ["Abbey Road", "Penny Lane", "Carnaby Street", "Baker Street"], "Abbey Road", 1),
      q("Brick Lane in east London is known for curry houses and…", ["bagel shops", "car dealers", "ski stores", "toy makers"], "bagel shops", 2),
      q("London's Chinatown sits in…", ["Soho", "Shoreditch", "Brixton", "Camden"], "Soho", 1),
      q("Brixton's Electric Avenue inspired a hit song by…", ["Eddy Grant", "Bob Marley", "Billy Ocean", "UB40"], "Eddy Grant", 2),
      q("Portobello Road's famous street market is in…", ["Notting Hill", "Islington", "Hackney", "Brixton"], "Notting Hill", 1),
      q("Harrods department store is in…", ["Knightsbridge", "Mayfair", "Soho", "Holborn"], "Knightsbridge", 1),
      q("Hamleys, one of the world's oldest toy shops, is on…", ["Regent Street", "Oxford Street", "the Strand", "Kensington High Street"], "Regent Street", 2),
      q("The tea company trading on the Strand since 1706 is…", ["Twinings", "Whittard", "Tetley", "Lipton"], "Twinings", 3),
      q("Film premieres in London are often held in…", ["Leicester Square", "Sloane Square", "Russell Square", "Parliament Square"], "Leicester Square", 1),
      q("Agatha Christie's play that opened in London in 1952 is…", ["The Mousetrap", "Witness for the Prosecution", "Black Coffee", "The Hollow"], "The Mousetrap", 1),
      q("Canary Wharf is a business district on the…", ["Isle of Dogs", "Isle of Sheppey", "Eel Pie Island", "Isle of Wight"], "Isle of Dogs", 2),
      q("Which London tower is nicknamed the Gherkin?", ["30 St Mary Axe", "20 Fenchurch Street", "122 Leadenhall Street", "1 Undershaft"], "30 St Mary Axe", 2),
      q("20 Fenchurch Street is nicknamed the…", ["Walkie-Talkie", "Cheesegrater", "Gherkin", "Scalpel"], "Walkie-Talkie", 2),
      q("122 Leadenhall Street is nicknamed the…", ["Cheesegrater", "Walkie-Talkie", "Shard", "Can of Ham"], "Cheesegrater", 2),
      q("The Shard was designed by architect…", ["Renzo Piano", "Norman Foster", "Zaha Hadid", "Richard Rogers"], "Renzo Piano", 2),
      q("The Gherkin was designed by architect…", ["Norman Foster", "Renzo Piano", "Richard Rogers", "David Adjaye"], "Norman Foster", 2),
      q("Which architect designed the 'inside-out' Lloyd's building?", ["Richard Rogers", "Norman Foster", "Renzo Piano", "Denys Lasdun"], "Richard Rogers", 3),
      q("The BBC Proms summer concerts are held mainly at the…", ["Royal Albert Hall", "Barbican", "Royal Festival Hall", "Wigmore Hall"], "Royal Albert Hall", 1),
      q("The Natural History Museum's blue whale skeleton is named…", ["Hope", "Dippy", "Moby", "Grace"], "Hope", 2),
      q("The V&A museum is named for Queen Victoria and…", ["Prince Albert", "King Edward", "Lord Melbourne", "Prince George"], "Prince Albert", 1),
      q("Madame Tussauds in London is famous for its…", ["wax figures", "crown jewels", "dinosaur bones", "royal coaches"], "wax figures", 1),
      q("The Cutty Sark docked at Greenwich is a former…", ["tea clipper", "warship", "ocean liner", "royal yacht"], "tea clipper", 1),
      q("HMS Belfast, moored on the Thames, is a WWII…", ["cruiser", "submarine", "aircraft carrier", "battleship"], "cruiser", 2),
      q("The O2 arena was originally built as the…", ["Millennium Dome", "Festival Hall", "Crystal Palace", "Olympic Arena"], "Millennium Dome", 1),
      q("Battersea Power Station appears on the cover of Pink Floyd's…", ["Animals", "The Wall", "Meddle", "Wish You Were Here"], "Animals", 2),
      q("Who designed both Battersea Power Station and the red phone box?", ["Giles Gilbert Scott", "Edwin Lutyens", "John Soane", "George Gilbert Scott"], "Giles Gilbert Scott", 3),
      q("Blue plaques on London buildings mark where…", ["famous people lived", "bombs once fell", "plague pits lie", "rivers run below"], "famous people lived", 1),
      q("The last frost fair on the frozen Thames was held in…", ["1814", "1683", "1895", "1739"], "1814", 3),
      q("The 'Great Stink' of 1858 led Joseph Bazalgette to build London's…", ["sewers", "Tube", "bridges", "docks"], "sewers", 3),
      q("Little Venice is a London spot known for its…", ["canals", "gondolas", "glass domes", "island fort"], "canals", 2),
      q("Which East End dish is chopped eels set in their own stock?", ["jellied eels", "eel pie", "stargazy pie", "potted eels"], "jellied eels", 1),
      q("In 'bangers and mash', the bangers are…", ["sausages", "pork chops", "fish cakes", "meatballs"], "sausages", 1),
      q("Smithfield in the City of London is a centuries-old…", ["meat market", "fish market", "flower market", "horse fair"], "meat market", 2),
      q("On the London Monopoly board, the priciest square is…", ["Mayfair", "Park Lane", "Bond Street", "Piccadilly"], "Mayfair", 1),
      q("On the London Monopoly board, the cheapest square is…", ["Old Kent Road", "Whitechapel Road", "the Angel Islington", "Euston Road"], "Old Kent Road", 2),
      q("Greater London is split into the City of London plus how many boroughs?", ["32", "24", "28", "48"], "32", 2),
      q("The Lord Mayor's Show is a historic parade in the…", ["City of London", "West End", "Westminster", "East End"], "City of London", 2),
    ],
  },
  austin: {
    local: [
      q("Austin is named for the 'Father of Texas'…", ["Stephen F. Austin", "Sam Houston", "Davy Crockett", "Mirabeau Lamar"], "Stephen F. Austin", 1),
      q("Before it became Austin, the frontier village was called…", ["Waterloo", "Riverside", "Bluebonnet", "New Braunfels"], "Waterloo", 2),
      q("Austin became the capital of the Republic of Texas in…", ["1839", "1845", "1821", "1861"], "1839", 2),
      q("Which Texas president picked the site for Austin?", ["Mirabeau B. Lamar", "Sam Houston", "Anson Jones", "David G. Burnet"], "Mirabeau B. Lamar", 3),
      q("Austin's original 1839 street grid was laid out by…", ["Edwin Waller", "Stephen F. Austin", "Elisabet Ney", "Jesse Driskill"], "Edwin Waller", 3),
      q("In Austin's original plan, the north-south streets were named for Texas…", ["rivers", "heroes", "battles", "counties"], "rivers", 3),
      q("Austin's Sixth Street was originally called…", ["Pecan Street", "Oak Street", "Cedar Street", "Elm Street"], "Pecan Street", 2),
      q("In the 1842 Archive War, Angelina Eberly fired a cannon to keep…", ["the state records", "the governor", "the treasury gold", "the Alamo flag"], "the state records", 3),
      q("The Texas Capitol is famous for standing taller than…", ["the U.S. Capitol", "the Alamo chapel", "Willis Tower", "the Washington Monument"], "the U.S. Capitol", 1),
      q("The statue on top of the Texas Capitol dome is the…", ["Goddess of Liberty", "Spirit of Texas", "Lady Justice", "Lone Star Ranger"], "Goddess of Liberty", 2),
      q("Austin protects sightlines to the Capitol with special…", ["view corridors", "height domes", "skyline zones", "sun easements"], "view corridors", 2),
      q("The big Texas history museum near the Capitol is named for…", ["Bob Bullock", "Ann Richards", "Sam Houston", "LBJ"], "Bob Bullock", 2),
      q("Austin's 165-foot 19th-century street lights are called…", ["moonlight towers", "star poles", "lamp spires", "night beacons"], "moonlight towers", 2),
      q("Which 1993 Richard Linklater film features a party under an Austin moonlight tower?", ["Dazed and Confused", "Slacker", "Boyhood", "School of Rock"], "Dazed and Confused", 2),
      q("Zilker Park's holiday tree is built from a…", ["moonlight tower", "radio mast", "water tower", "flagpole"], "moonlight tower", 2),
      q("Austin's unofficial slogan urges people to keep the city…", ["weird", "green", "loud", "small"], "weird", 1),
      q("SXSW stands for…", ["South by Southwest", "Sound by Southwest", "South by Six Street", "Southern Exhibition"], "South by Southwest", 1),
      q("SXSW is held in Austin every…", ["March", "July", "October", "December"], "March", 1),
      q("Austin City Limits began in 1974 as a…", ["TV concert series", "radio talk show", "football league", "film festival"], "TV concert series", 2),
      q("Armadillo World Headquarters was a legendary 1970s Austin…", ["music hall", "pet store", "rodeo ring", "barbecue pit"], "music hall", 2),
      q("A bronze statue of which guitarist stands at Auditorium Shores?", ["Stevie Ray Vaughan", "Willie Nelson", "Buddy Holly", "Janis Joplin"], "Stevie Ray Vaughan", 2),
      q("Antone's is an Austin club famous as a home of the…", ["blues", "punk", "polka", "opera"], "blues", 2),
      q("The Continental Club is a classic music venue on…", ["South Congress", "East Sixth", "Rainey Street", "Red River"], "South Congress", 2),
      q("Janis Joplin sang early gigs at which Austin spot?", ["Threadgill's", "Antone's", "the Broken Spoke", "Stubb's"], "Threadgill's", 3),
      q("Austin's nickname for South Congress Avenue is…", ["SoCo", "SoCa", "SouthCo", "the Strip"], "SoCo", 1),
      q("The 'i love you so much' mural is on the wall of…", ["Jo's Coffee", "Torchy's Tacos", "Waterloo Records", "BookPeople"], "Jo's Coffee", 2),
      q("The 'Greetings from Austin' mural is painted like a giant…", ["postcard", "stamp", "road map", "license plate"], "postcard", 1),
      q("Waterloo Records is a famous Austin…", ["record store", "music hall", "radio station", "guitar shop"], "record store", 1),
      q("BookPeople in Austin is Texas's largest independent…", ["bookstore", "music store", "toy store", "comic shop"], "bookstore", 1),
      q("The Cathedral of Junk in south Austin is a…", ["backyard sculpture", "flea market", "salvage yard", "punk club"], "backyard sculpture", 2),
      q("Esther's Follies on Sixth Street is a long-running…", ["comedy revue", "dance hall", "magic museum", "food hall"], "comedy revue", 3),
      q("The Elisabet Ney Museum was the studio of a famous…", ["sculptor", "painter", "composer", "photographer"], "sculptor", 3),
      q("The Harry Ransom Center at UT holds a Gutenberg Bible and the world's first…", ["photograph", "telephone", "phonograph", "typewriter"], "photograph", 3),
      q("The Lady Bird Johnson Wildflower Center is part of…", ["UT Austin", "Texas A&M", "Baylor", "Texas State"], "UT Austin", 2),
      q("The Umlauf in Austin is a garden full of…", ["sculptures", "roses", "cactus", "bonsai"], "sculptures", 2),
      q("Which river runs through downtown Austin?", ["Colorado", "Brazos", "Guadalupe", "Pedernales"], "Colorado", 2),
      q("The loop trail around Lady Bird Lake is a…", ["hike-and-bike trail", "go-kart track", "horse path", "rail line"], "hike-and-bike trail", 1),
      q("Lady Bird Lake is mostly closed to…", ["motorboats", "kayaks", "rowing shells", "paddleboards"], "motorboats", 2),
      q("Lake Travis was formed by which dam?", ["Mansfield Dam", "Tom Miller Dam", "Longhorn Dam", "Buchanan Dam"], "Mansfield Dam", 3),
      q("Lake Travis belongs to the Colorado River chain of reservoirs called the…", ["Highland Lakes", "Hill Lakes", "Balcones Lakes", "Pecan Lakes"], "Highland Lakes", 2),
      q("The Oasis on Lake Travis bills itself the Sunset Capital of…", ["Texas", "the World", "the Lakes", "the Hills"], "Texas", 1),
      q("Deep Eddy Pool in Austin is the oldest…", ["swimming pool in Texas", "dam in Texas", "zoo in Texas", "bridge in Texas"], "swimming pool in Texas", 1),
      q("Hamilton Pool, west of Austin, is a swimming hole under a…", ["collapsed grotto", "highway bridge", "sea cliff", "glacier"], "collapsed grotto", 2),
      q("Which state park with waterfalls sits inside Austin's city limits?", ["McKinney Falls", "Pedernales Falls", "Inks Lake", "Enchanted Rock"], "McKinney Falls", 1),
      q("The tiny endangered animal of Barton Springs is a…", ["salamander", "minnow", "turtle", "crayfish"], "salamander", 2),
      q("Austin's Treaty Oak survived a deliberate 1989…", ["poisoning", "lightning strike", "tornado", "flood"], "poisoning", 3),
      q("Austin sits on the edge of the Hill Country along the…", ["Balcones Escarpment", "Caprock Escarpment", "Edwards Plateau Rim", "Llano Uplift"], "Balcones Escarpment", 3),
      q("Austin's airport occupies a former…", ["Air Force base", "cattle ranch", "cotton farm", "rail yard"], "Air Force base", 2),
      q("Capital MetroRail's commuter line is called the…", ["Red Line", "Blue Line", "Silver Line", "Orange Line"], "Red Line", 3),
      q("Which downtown tower is said to look like an owl?", ["Frost Bank Tower", "the Austonian", "the Independent", "One Congress Plaza"], "Frost Bank Tower", 2),
      q("Which stacked Austin skyscraper is nicknamed the 'Jenga' tower?", ["the Independent", "the Austonian", "Frost Bank Tower", "the Monarch"], "the Independent", 2),
      q("The Driskill, opened in 1886, is Austin's grand historic…", ["hotel", "theater", "church", "courthouse"], "hotel", 1),
      q("The Driskill Hotel was built by a…", ["cattle baron", "railroad tycoon", "cotton broker", "oilman"], "cattle baron", 2),
      q("Writer O. Henry once lived in Austin; the city's yearly contest in his name is a…", ["pun-off", "chili cook-off", "spelling bee", "poetry slam"], "pun-off", 3),
      q("The UT Tower glows which color after big Longhorns wins?", ["burnt orange", "maroon", "crimson", "gold"], "burnt orange", 1),
      q("The Longhorns' hand sign is called…", ["Hook 'em Horns", "Horns Up", "Gig 'em", "Wreck 'em"], "Hook 'em Horns", 1),
      q("The Longhorn Band's giant bass drum is named…", ["Big Bertha", "Big Tex", "Old Smokey", "Thunder"], "Big Bertha", 2),
      q("The Texas–OU 'Red River Rivalry' game is played in…", ["Dallas", "Austin", "Norman", "Houston"], "Dallas", 2),
      q("Circuit of the Americas hosts Formula 1's…", ["United States Grand Prix", "Texas 500", "Austin 24 Hours", "Lone Star Rally"], "United States Grand Prix", 1),
      q("Austin FC's main team color is…", ["verde", "burnt orange", "navy", "crimson"], "verde", 2),
      q("Michael Dell started his company in a dorm room at…", ["UT Austin", "Texas A&M", "Rice", "Baylor"], "UT Austin", 2),
      q("In 2021 Tesla moved its headquarters to…", ["Austin", "Houston", "Dallas", "San Antonio"], "Austin", 2),
      q("Austin's tech scene earned the nickname…", ["Silicon Hills", "Silicon Prairie", "Tech Canyon", "Chip City"], "Silicon Hills", 2),
      q("Which dating app was founded in Austin in 2014?", ["Bumble", "Tinder", "Hinge", "OkCupid"], "Bumble", 2),
      q("Tito's Handmade, born in Austin, makes…", ["vodka", "tequila", "bourbon", "gin"], "vodka", 1),
      q("Chuy's, founded in Austin in 1982, serves…", ["Tex-Mex", "barbecue", "pizza", "sushi"], "Tex-Mex", 2),
      q("Austin's ubiquitous melted-cheese dip is called…", ["queso", "salsa", "crema", "mole"], "queso", 1),
      q("Many of Austin's famous eats are served from…", ["food trailers", "street carts", "dinner trains", "riverboats"], "food trailers", 1),
      q("Amy's Ice Creams is an Austin chain famous for…", ["ice cream", "tacos", "barbecue", "doughnuts"], "ice cream", 1),
      q("The Salt Lick barbecue, near Austin, is in…", ["Driftwood", "Lockhart", "Luling", "Taylor"], "Driftwood", 2),
      q("Eeyore's Birthday Party is a quirky spring festival held in…", ["Pease Park", "Zilker Park", "Republic Square", "Mueller Lake Park"], "Pease Park", 3),
      q("Zilker Park's spring festival fills the sky with…", ["kites", "balloons", "fireworks", "drones"], "kites", 1),
      q("Zilker's December light display is the…", ["Trail of Lights", "Festival of Stars", "Glow Walk", "Lone Star Lights"], "Trail of Lights", 2),
      q("The Alamo is about 80 miles southwest of Austin in…", ["San Antonio", "Houston", "Waco", "Laredo"], "San Antonio", 1),
      q("UT Austin's sports teams are the…", ["Longhorns", "Aggies", "Bears", "Mustangs"], "Longhorns", 1),
      q("The Broken Spoke is a classic Austin…", ["honky-tonk dance hall", "taco truck park", "guitar museum", "rodeo arena"], "honky-tonk dance hall", 2),
      q("Stubb's in Austin is both a music venue and a…", ["barbecue joint", "record label", "taco stand", "brewery"], "barbecue joint", 2),
      q("Mexic-Arte Museum on Congress Avenue showcases…", ["Mexican and Latino art", "Texas oil history", "rock 'n' roll gear", "Western saddles"], "Mexican and Latino art", 3),
      q("Austin's long-running free alt-weekly paper is the…", ["Austin Chronicle", "Austin Observer", "Capitol Courier", "Hill Country Voice"], "Austin Chronicle", 2),
      q("Laguna Gloria, an Italianate villa on Lake Austin, is now an…", ["art museum", "inn", "embassy", "music school"], "art museum", 3),
      q("The Austin Film Society was founded by director…", ["Richard Linklater", "Robert Rodriguez", "Wes Anderson", "Terrence Malick"], "Richard Linklater", 3),
      q("Lake Austin is held back by which dam?", ["Tom Miller Dam", "Mansfield Dam", "Longhorn Dam", "Wirtz Dam"], "Tom Miller Dam", 3),
      q("Austin's Clarksville neighborhood was founded in 1871 by…", ["freed slaves", "German farmers", "railroad workers", "Czech settlers"], "freed slaves", 3),
      q("The Longhorns' oldest in-state football rival is…", ["Texas A&M", "Baylor", "TCU", "Rice"], "Texas A&M", 1),
    ],
  },
  temple: {
    local: [
      q("Temple's town lots were first auctioned at a big barbecue in…", ["1881", "1836", "1901", "1865"], "1881", 2),
      q("Before it got its name, the railroad called the Temple site…", ["Temple Junction", "Bell Station", "Santa Fe Camp", "Moore's Crossing"], "Temple Junction", 1),
      q("Early Temple's rough, muddy streets earned it the nickname…", ["Tanglefoot", "Dust Bowl", "Slick Rock", "Boomtown"], "Tanglefoot", 2),
      q("Besides Tanglefoot, early Temple was also called…", ["Mud Town", "Rail Town", "Tent City", "Cow Town"], "Mud Town", 2),
      q("The farmer who sold the land for Temple was…", ["Jonathan E. Moore", "Bernard M. Temple", "Peter H. Bell", "Arthur C. Scott"], "Jonathan E. Moore", 3),
      q("Temple was incorporated as a city in…", ["1882", "1876", "1895", "1910"], "1882", 3),
      q("In 1882 which second railroad, the 'Katy,' reached Temple?", ["Missouri, Kansas and Texas", "Texas and Pacific", "Southern Pacific", "Fort Worth and Denver"], "Missouri, Kansas and Texas", 3),
      q("Temple's grand Santa Fe depot was designed by Chicago architect…", ["Jarvis Hunt", "Daniel Burnham", "Louis Sullivan", "Henry Hobson Richardson"], "Jarvis Hunt", 3),
      q("Temple's Santa Fe depot was completed in…", ["1911", "1881", "1936", "1955"], "1911", 3),
      q("Which Amtrak train stops at Temple's depot?", ["Texas Eagle", "Sunset Limited", "Southwest Chief", "Heartland Flyer"], "Texas Eagle", 2),
      q("Temple's railroad museum has a big collection of memorabilia from…", ["Harvey Houses", "Pullman cars", "Pony Express", "Wells Fargo"], "Harvey Houses", 3),
      q("Today, two big freight railroads run through Temple: BNSF and…", ["Union Pacific", "CSX", "Norfolk Southern", "Amtrak"], "Union Pacific", 2),
      q("Which river separates Temple from neighboring Belton?", ["Leon River", "Brazos River", "Lampasas River", "San Gabriel River"], "Leon River", 2),
      q("Bell County is named for Texas governor…", ["Peter Hansborough Bell", "Sam Bell Maxey", "John Bell Hood", "James Bell"], "Peter Hansborough Bell", 3),
      q("Temple is about how far north of Austin?", ["67 miles", "20 miles", "150 miles", "240 miles"], "67 miles", 2),
      q("Temple is about how far south of Waco?", ["36 miles", "5 miles", "110 miles", "200 miles"], "36 miles", 2),
      q("Temple's area code is…", ["254", "512", "214", "713"], "254", 2),
      q("Temple sits on a rich band of Texas farm soil called the…", ["Blackland Prairie", "Llano Estacado", "Piney Woods", "Cross Timbers"], "Blackland Prairie", 2),
      q("Temple's local bus service is nicknamed…", ["The HOP", "The Loop", "The Dash", "The Link"], "The HOP", 3),
      q("Temple's general-aviation field is Draughon-Miller Central Texas…", ["Regional Airport", "Air Force Base", "Heliport", "Spaceport"], "Regional Airport", 1),
      q("The doctors behind Temple's Scott & White were Arthur Scott and…", ["Raleigh White", "William Mayo", "Charles Baylor", "Edward Temple"], "Raleigh White", 2),
      q("Scott and White opened the Temple Sanitarium in…", ["1904", "1881", "1936", "1950"], "1904", 3),
      q("Temple's children's hospital is named for the…", ["McLane family", "Scott family", "Bell family", "Mayborn family"], "McLane family", 2),
      q("Temple's VA hospital is named for congressman…", ["Olin E. Teague", "Sam Rayburn", "Lyndon Johnson", "W. R. Poage"], "Olin E. Teague", 3),
      q("Which university runs a medical school campus in Temple?", ["Texas A&M", "Rice", "Texas Tech", "SMU"], "Texas A&M", 2),
      q("Temple-based McLane Company is a big…", ["grocery distributor", "oil refiner", "home builder", "trucking school"], "grocery distributor", 2),
      q("Drayton McLane Jr. of Temple once owned which MLB team?", ["Houston Astros", "Texas Rangers", "Kansas City Royals", "San Diego Padres"], "Houston Astros", 2),
      q("Temple-based Wilsonart is known for making…", ["decorative laminates", "cowboy boots", "pickup trucks", "pecan candy"], "decorative laminates", 2),
      q("Dr Pepper was invented about 35 miles north of Temple, in…", ["Waco", "Dallas", "Austin", "Fort Worth"], "Waco", 1),
      q("Temple's daily newspaper is the Temple Daily…", ["Telegram", "Herald", "Courier", "Sentinel"], "Telegram", 1),
      q("Temple College, founded in 1926, calls its teams the…", ["Leopards", "Wildcats", "Rangers", "Crusaders"], "Leopards", 2),
      q("Temple College's school colors are…", ["orange and black", "maroon and white", "blue and gold", "green and white"], "orange and black", 3),
      q("Temple's Czech Heritage Museum is run by the foundation of…", ["SPJST", "the Sons of Hermann", "the KJT", "the Czech Club"], "SPJST", 3),
      q("Downtown Temple's Hawn Tower opened in 1928 as the…", ["Doering Hotel", "Santa Fe Hotel", "Bell Hotel", "Katy Hotel"], "Doering Hotel", 3),
      q("Which historic theater sits beside downtown Temple's Hawn Tower?", ["the Arcadia", "the Paramount", "the Majestic", "the Rialto"], "the Arcadia", 3),
      q("Pittsburgh Steelers legend 'Mean' Joe Greene grew up in…", ["Temple", "Waco", "Killeen", "Belton"], "Temple", 1),
      q("Hall of Fame quarterback Sammy Baugh was born in…", ["Temple", "Austin", "Abilene", "Tyler"], "Temple", 3),
      q("Oscar-nominated actor Rip Torn was born in…", ["Temple", "Houston", "Dallas", "Lubbock"], "Temple", 1),
      q("Astronaut Bernard Harris Jr., born in Temple, was the first African American to…", ["walk in space", "orbit Earth", "fly the shuttle", "visit the ISS"], "walk in space", 3),
      q("Forrest Fenn, born in Temple, is famous for a hidden…", ["treasure chest", "time capsule", "gold mine", "lost painting"], "treasure chest", 1),
      q("Britt Daniel, born in Temple, fronts which Austin band?", ["Spoon", "Okkervil River", "Explosions in the Sky", "The Black Angels"], "Spoon", 3),
      q("Tejano star 'Little Joe' Hernández, of Temple, leads…", ["Little Joe y La Familia", "Los Lonely Boys", "La Mafia", "Los Tigres del Norte"], "Little Joe y La Familia", 3),
      q("Temple's Bell County neighbor Belton is home to the…", ["Bell County Museum", "Texas Ranger Museum", "Dr Pepper Museum", "Bob Bullock Museum"], "Bell County Museum", 1),
    ],
  },
  tucson: {
    local: [
      q("Tucson's long-standing nickname is…", ["the Old Pueblo", "the Valley of the Sun", "the Copper City", "the Sky Island"], "the Old Pueblo", 1),
      q("Tucson's Spanish presidio was founded in 1775 by Irish-born officer…", ["Hugo O'Conor", "Juan Bautista de Anza", "Eusebio Kino", "Pedro de Anza"], "Hugo O'Conor", 3),
      q("Tucson became part of the U.S. through the…", ["Gadsden Purchase", "Louisiana Purchase", "Adams–Onís Treaty", "Oregon Treaty"], "Gadsden Purchase", 2),
      q("From 1867 to 1877, Tucson served as the capital of…", ["Arizona Territory", "New Mexico Territory", "the Confederacy", "Sonora"], "Arizona Territory", 3),
      q("The Pima Air & Space Museum in Tucson is famous for its huge collection of…", ["aircraft", "rockets", "satellites", "race cars"], "aircraft", 1),
      q("The Titan Missile Museum south of Tucson is a former…", ["nuclear missile silo", "Army fort", "copper mine", "rocket test range"], "nuclear missile silo", 1),
      q("Biosphere 2, run by the University of Arizona, is near…", ["Oracle", "Bisbee", "Nogales", "Sierra Vista"], "Oracle", 2),
      q("Sabino Canyon in Tucson is known for its…", ["shuttle tram rides", "cliff dwellings", "hot springs", "ski lifts"], "shuttle tram rides", 2),
      q("Mount Lemmon is named for a 19th-century…", ["botanist", "general", "miner", "priest"], "botanist", 3),
      q("The University of Arizona grinds giant telescope mirrors in a lab under its…", ["football stadium", "basketball arena", "library", "student union"], "football stadium", 3),
      q("UA's Lunar and Planetary Lab led which asteroid sample mission?", ["OSIRIS-REx", "Hayabusa", "Rosetta", "Dawn"], "OSIRIS-REx", 3),
      q("Tucson limits outdoor lighting to protect…", ["dark skies", "bat colonies", "radio signals", "desert tortoises"], "dark skies", 1),
      q("Artist Ted DeGrazia's Tucson studio is called the Gallery in the…", ["Sun", "Sand", "Sky", "Hills"], "Sun", 2),
      q("El Tiradito in Barrio Viejo is a…", ["wishing shrine", "dance hall", "market plaza", "rail depot"], "wishing shrine", 3),
      q("Tucson's winter rodeo is called La Fiesta de los…", ["Vaqueros", "Charros", "Caballos", "Toros"], "Vaqueros", 2),
      q("Tucson's rodeo parade is famous for being entirely…", ["non-motorized", "at night", "on the river", "in costume"], "non-motorized", 3),
      q("The All Souls Procession in Tucson is held each…", ["November", "March", "July", "January"], "November", 2),
      q("The Tucson Festival of Books is held on the campus of…", ["the University of Arizona", "Arizona State", "Pima College", "Northern Arizona"], "the University of Arizona", 2),
      q("The saguaro blossom is Arizona's state…", ["flower", "tree", "bird", "gem"], "flower", 1),
      q("Tucson's El Charro Café claims to have invented the…", ["chimichanga", "burrito", "nacho", "fajita"], "chimichanga", 2),
      q("El Charro famously dries beef on its roof to make…", ["carne seca", "barbacoa", "chorizo", "cecina"], "carne seca", 2),
      q("Eegee's is a Tucson chain famous for its…", ["frozen fruit drinks", "breakfast tacos", "hot dogs", "pizza"], "frozen fruit drinks", 2),
      q("Tucson's modern streetcar is called…", ["Sun Link", "Sun Rail", "Desert Line", "Valley Metro"], "Sun Link", 2),
      q("Tucson's 130-plus-mile ring of paved paths is called…", ["the Loop", "the Ring", "the Circuit", "the Belt"], "the Loop", 2),
      q("Gates Pass west of Tucson is a favorite spot to watch…", ["sunsets", "rodeos", "air shows", "trains"], "sunsets", 1),
      q("Tumacácori, south of Tucson, preserves one of the oldest mission sites in…", ["Arizona", "California", "Texas", "Utah"], "Arizona", 3),
      q("Tombstone, home of the O.K. Corral, is roughly how far from Tucson?", ["70 miles", "10 miles", "200 miles", "350 miles"], "70 miles", 2),
      q("Colossal Cave, east of Tucson, is a…", ["dry limestone cave", "lava tube", "flooded mine", "salt cavern"], "dry limestone cave", 3),
      q("Lute Olson coached Arizona to its NCAA basketball title in…", ["1997", "1988", "2001", "1993"], "1997", 2),
      q("The Arizona Wildcats' mascot is…", ["Wilbur", "Sparky", "Bucky", "Willie"], "Wilbur", 2),
      q("Tucson's Diamondback Bridge is shaped like a…", ["rattlesnake", "saguaro", "roadrunner", "lizard"], "rattlesnake", 1),
      q("In Tucson, the smell of desert rain mostly comes from…", ["creosote bush", "mesquite trees", "sagebrush", "palo verde"], "creosote bush", 2),
      q("The pig-like animal often seen in Tucson neighborhoods is the…", ["javelina", "coati", "badger", "armadillo"], "javelina", 1),
      q("Which bird often nests in holes in Tucson's saguaros?", ["Gila woodpecker", "roadrunner", "cactus wren", "Gambel's quail"], "Gila woodpecker", 2),
      q("The venomous beaded lizard of the Tucson desert is the…", ["Gila monster", "chuckwalla", "horned lizard", "whiptail"], "Gila monster", 1),
      q("Singer Linda Ronstadt grew up in…", ["Tucson", "Phoenix", "El Paso", "Albuquerque"], "Tucson", 1),
      q("Tucson's spring festival of mariachi music is the Tucson International…", ["Mariachi Conference", "Mariachi Olympics", "Ranchera Fair", "Guitar Summit"], "Mariachi Conference", 2),
      q("Interstate 19 from Tucson to Nogales posts its distances in…", ["kilometers", "miles", "leagues", "minutes"], "kilometers", 2),
      q("The Desert Laboratory on Tucson's Tumamoc Hill studies…", ["desert plants", "meteorites", "mining", "dinosaurs"], "desert plants", 3),
      q("The Rillito in north Tucson is a mostly dry…", ["river", "canyon", "lake bed", "canal"], "river", 2),
      q("Reid Park in Tucson is home to the city's…", ["zoo", "airport", "ballpark", "observatory"], "zoo", 2),
      q("Tucson's tiled-dome Pima County Courthouse is built in which style?", ["Spanish Colonial Revival", "Romanesque Revival", "Beaux-Arts Classical", "Victorian Gothic"], "Spanish Colonial Revival", 3),
      q("Interstate 10 links Tucson to Phoenix and continues west to…", ["Los Angeles", "San Diego", "Las Vegas", "Sacramento"], "Los Angeles", 2),
    ],
  },
  toronto: {
    local: [
      q("Before 1834, Toronto was called…", ["York", "Kingston", "Newark", "Bytown"], "York", 1),
      q("Toronto was incorporated as a city in…", ["1834", "1867", "1793", "1901"], "1834", 2),
      q("Which colonial governor founded the town of York in 1793?", ["John Graves Simcoe", "Isaac Brock", "Guy Carleton", "John A. Macdonald"], "John Graves Simcoe", 3),
      q("In April 1813, the town of York was captured by…", ["American troops", "French troops", "Fenian raiders", "Spanish troops"], "American troops", 2),
      q("Toronto's first mayor, later a rebel leader, was…", ["William Lyon Mackenzie", "John A. Macdonald", "George Brown", "Egerton Ryerson"], "William Lyon Mackenzie", 2),
      q("Toronto's 1837 rebels gathered at…", ["Montgomery's Tavern", "Fort York", "Queen's Park", "St. Lawrence Hall"], "Montgomery's Tavern", 3),
      q("A great fire leveled much of downtown Toronto in…", ["1904", "1871", "1849", "1934"], "1904", 3),
      q("Toronto merged with five neighbors into one 'megacity' in…", ["1998", "1967", "1954", "2010"], "1998", 2),
      q("Toronto's old nickname 'Hogtown' comes from its…", ["pork-packing plants", "muddy streets", "farm fairs", "rude drivers"], "pork-packing plants", 2),
      q("The city's strict Victorian morals once earned it the nickname…", ["Toronto the Good", "Toronto the Pure", "Saintly City", "Sunday Town"], "Toronto the Good", 3),
      q("Toronto's original area code is…", ["416", "905", "613", "514"], "416", 1),
      q("The 'CN' in CN Tower originally stood for…", ["Canadian National", "Central North", "Canada Network", "City of Niagara"], "Canadian National", 2),
      q("The CN Tower stands about how tall?", ["553 m", "350 m", "828 m", "442 m"], "553 m", 2),
      q("The CN Tower lost its title as the world's tallest free-standing structure to…", ["Burj Khalifa", "Shanghai Tower", "Taipei 101", "Willis Tower"], "Burj Khalifa", 2),
      q("The CN Tower's hands-free walk around the outside ledge is called…", ["EdgeWalk", "SkyWalk", "The Ledge", "Halo Walk"], "EdgeWalk", 1),
      q("The big aquarium at the foot of the CN Tower is run by…", ["Ripley's", "SeaWorld", "Shedd", "Monterey Bay"], "Ripley's", 1),
      q("Rogers Centre was originally called the…", ["SkyDome", "Toronto Dome", "Maple Dome", "Exhibition Stadium"], "SkyDome", 1),
      q("When it opened in 1989, the SkyDome was famous for its…", ["retractable roof", "grass infield", "lakeside moat", "glass walls"], "retractable roof", 1),
      q("The Blue Jays won back-to-back World Series in…", ["1992 and 1993", "1985 and 1986", "2015 and 2016", "1977 and 1978"], "1992 and 1993", 1),
      q("Who hit the walk-off homer that won the Blue Jays the 1993 World Series?", ["Joe Carter", "Roberto Alomar", "Jose Bautista", "Paul Molitor"], "Joe Carter", 2),
      q("The Raptors' rallying slogan is…", ["We the North", "North Strong", "True North", "Raptors Rise"], "We the North", 1),
      q("The Raptors' 1995 name was inspired by the hit film…", ["Jurassic Park", "Godzilla", "Top Gun", "Star Wars"], "Jurassic Park", 2),
      q("Maple Leaf Gardens, the Leafs' old arena, now houses a…", ["grocery store", "casino", "concert hall", "museum"], "grocery store", 3),
      q("The Argonauts, founded in 1873, play which sport?", ["Canadian football", "lacrosse", "rowing", "rugby"], "Canadian football", 2),
      q("Toronto FC plays its home matches at…", ["BMO Field", "Rogers Centre", "Scotiabank Arena", "Varsity Stadium"], "BMO Field", 2),
      q("Toronto hosted which multi-sport games in 2015?", ["Pan American Games", "Commonwealth Games", "Winter Olympics", "World University Games"], "Pan American Games", 2),
      q("Canada's first subway line opened in Toronto in…", ["1954", "1931", "1967", "1976"], "1954", 2),
      q("Toronto's U-shaped Line 1 subway is named Yonge–…", ["University", "Bloor", "Spadina", "Sheppard"], "University", 2),
      q("Toronto's red TTC vehicles earned the nickname…", ["the Red Rocket", "the Red Devil", "the Ruby Line", "the Fire Truck"], "the Red Rocket", 2),
      q("Toronto's tap-on transit fare card is called…", ["Presto", "Oyster", "Compass", "Opus"], "Presto", 1),
      q("GO Transit runs the Toronto area's…", ["regional trains and buses", "harbour ferries", "airport taxis", "bike share"], "regional trains and buses", 1),
      q("The UP Express train links Union Station with…", ["Pearson Airport", "Niagara Falls", "Scarborough", "Hamilton"], "Pearson Airport", 1),
      q("Highway 401 through Toronto is known as one of North America's…", ["busiest highways", "oldest toll roads", "longest bridges", "curviest roads"], "busiest highways", 2),
      q("Drivers joke that the Don Valley Parkway is the Don Valley…", ["Parking Lot", "Racetrack", "Crawlway", "Snail Trail"], "Parking Lot", 2),
      q("Centreville, on the Toronto Islands, is an…", ["amusement park", "airport", "art school", "army base"], "amusement park", 2),
      q("The Gibraltar Point Lighthouse, on the Toronto Islands, dates to…", ["1808", "1867", "1913", "1950"], "1808", 3),
      q("The Toronto Islands were a peninsula until a storm cut through in…", ["1858", "1812", "1904", "1954"], "1858", 3),
      q("Tommy Thompson Park on the Leslie Street Spit is a man-made…", ["headland", "island", "canal", "beach"], "headland", 3),
      q("Toronto is famous for its huge network of wooded…", ["ravines", "canals", "hills", "islands"], "ravines", 1),
      q("Evergreen Brick Works is a former…", ["brick factory", "rail yard", "power plant", "brewery"], "brick factory", 1),
      q("Rouge Park in east Toronto is Canada's first national…", ["urban park", "marine park", "wildlife zoo", "forest reserve"], "urban park", 2),
      q("The Bata Museum in Toronto is devoted to…", ["shoes", "hats", "clocks", "toys"], "shoes", 1),
      q("Toronto's Aga Khan Museum showcases…", ["Islamic art", "hockey history", "Inuit carvings", "modern design"], "Islamic art", 2),
      q("The Toronto Zoo is in which part of the city?", ["Scarborough", "Etobicoke", "North York", "East York"], "Scarborough", 2),
      q("Toronto's Greektown runs along…", ["the Danforth", "Queen West", "Bloor West", "King East"], "the Danforth", 1),
      q("Toronto's late-summer fair at Exhibition Place is the…", ["CNE", "PNE", "Stampede", "Royal Fair"], "CNE", 1),
      q("The Toronto Caribbean Carnival was long known as…", ["Caribana", "Carnivale", "Island Fest", "Soca Week"], "Caribana", 1),
      q("Nuit Blanche in Toronto is an all-night…", ["art festival", "food market", "marathon", "film fest"], "art festival", 2),
      q("Hot Docs in Toronto is a festival of…", ["documentaries", "jazz", "hot sauce", "comedy"], "documentaries", 2),
      q("Roy Thomson Hall is home to the Toronto…", ["Symphony Orchestra", "Maple Leafs", "Opera Company", "Ballet School"], "Symphony Orchestra", 2),
      q("In winter, Nathan Phillips Square's reflecting pool becomes a…", ["skating rink", "snow maze", "curling sheet", "toboggan run"], "skating rink", 1),
      q("Which Toronto rapper popularized the nickname 'the 6ix'?", ["Drake", "The Weeknd", "Tory Lanez", "Nav"], "Drake", 1),
      q("Which Toronto-born singer released 'Blinding Lights'?", ["The Weeknd", "Drake", "Shawn Mendes", "Justin Bieber"], "The Weeknd", 1),
      q("Which Toronto rock trio recorded 'Tom Sawyer'?", ["Rush", "Triumph", "April Wine", "Max Webster"], "Rush", 2),
      q("Which band, formed in Scarborough, sang 'One Week'?", ["Barenaked Ladies", "The Tragically Hip", "Our Lady Peace", "Sloan"], "Barenaked Ladies", 2),
      q("Insulin was discovered in 1921 at the University of…", ["Toronto", "McGill", "Ottawa", "Western Ontario"], "Toronto", 1),
      q("Canada's financial industry is nicknamed after Toronto's…", ["Bay Street", "King Street", "Front Street", "Wall Street"], "Bay Street", 1),
      q("The black towers of the Toronto-Dominion Centre were designed by…", ["Mies van der Rohe", "Frank Gehry", "I. M. Pei", "Arthur Erickson"], "Mies van der Rohe", 3),
      q("Toronto's wedge-shaped Gooderham Building is often called the…", ["Flatiron Building", "Wedge Tower", "Prow House", "Iron Block"], "Flatiron Building", 2),
      q("Next door to Casa Loma stands the historic estate…", ["Spadina House", "Grange House", "Colborne Lodge", "Montgomery Inn"], "Spadina House", 3),
      q("Sugar Beach on Toronto's waterfront is known for its…", ["pink umbrellas", "black sand", "palm trees", "sand castles"], "pink umbrellas", 2),
      q("Toronto's east-end lakeside neighborhood is called…", ["The Beaches", "The Shores", "The Dunes", "The Bluffs"], "The Beaches", 1),
      q("Church and Wellesley is the heart of Toronto's…", ["LGBTQ village", "Chinatown", "theatre district", "fashion district"], "LGBTQ village", 1),
      q("Canada's Wonderland theme park is just north of Toronto in…", ["Vaughan", "Markham", "Oakville", "Pickering"], "Vaughan", 2),
      q("Toronto street-cart hot dogs are fondly called…", ["street meat", "cart dogs", "Leaf dogs", "red hots"], "street meat", 2),
      q("The name 'Toronto' is thought to come from a Mohawk phrase about…", ["trees standing in water", "a great meeting place", "the windy shore", "the beaver lodge"], "trees standing in water", 3),
      q("The Hockey Hall of Fame's Great Hall was once a…", ["bank", "church", "train shed", "theatre"], "bank", 3),
      q("Toronto's Graffiti Alley runs just south of…", ["Queen Street West", "Bloor Street", "the Danforth", "Eglinton Avenue"], "Queen Street West", 2),
      q("Hanlan's Point on the Toronto Islands is named for a champion…", ["rower", "boxer", "sprinter", "skater"], "rower", 3),
      q("Ferries to the Toronto Islands leave from a terminal named for…", ["Jack Layton", "Pierre Trudeau", "Rob Ford", "Mel Lastman"], "Jack Layton", 3),
      q("Toronto's yearly Doors Open weekend lets people…", ["tour closed buildings", "ride free transit", "skate on the lake", "visit film sets"], "tour closed buildings", 2),
      q("Toronto's Santa Claus Parade, one of the oldest, began in…", ["1905", "1950", "1867", "1975"], "1905", 3),
      q("Ontario Place's white geodesic dome theatre is the…", ["Cinesphere", "Skydome", "Omnimax", "Biosphere"], "Cinesphere", 2),
      q("Yorkville in Toronto is best known as an upscale…", ["shopping district", "industrial park", "farm market", "student quarter"], "shopping district", 1),
      q("High Park draws crowds every spring for its…", ["cherry blossoms", "maple syrup", "tulip maze", "lilac fair"], "cherry blossoms", 1),
    ],
  },
  nola: {
    local: [
      q("New Orleans was named for a French…", ["duke", "king", "saint", "general"], "duke", 2),
      q("Much of the French Quarter's old architecture is actually…", ["Spanish", "English", "Dutch", "Italian"], "Spanish", 2),
      q("Two great fires swept the old city under Spanish rule in 1788 and…", ["1794", "1812", "1765", "1803"], "1794", 3),
      q("The Old Ursuline Convent is called the oldest building in the…", ["Mississippi Valley", "Southern states", "Gulf states", "whole of Texas"], "Mississippi Valley", 3),
      q("The pirate who helped Andrew Jackson defend the city in 1815 was…", ["Jean Lafitte", "Blackbeard", "Henry Morgan", "William Kidd"], "Jean Lafitte", 2),
      q("The Battle of New Orleans was fought on the plains of…", ["Chalmette", "Metairie", "Gretna", "Kenner"], "Chalmette", 2),
      q("The 1890s case Plessy v. Ferguson began with an arrest on a…", ["train", "streetcar", "steamboat", "ferry"], "train", 3),
      q("In 1960, six-year-old Ruby Bridges integrated a New Orleans…", ["elementary school", "lunch counter", "city bus", "public pool"], "elementary school", 2),
      q("Andrew Higgins's New Orleans factories built WWII…", ["landing craft", "fighter planes", "tanks", "submarines"], "landing craft", 2),
      q("Storyville was New Orleans's legal red-light district from 1897 to…", ["1917", "1929", "1945", "1903"], "1917", 3),
      q("The cathedral facing Jackson Square is…", ["St. Louis Cathedral", "St. Patrick's", "Our Lady of Guadalupe", "St. Mary's"], "St. Louis Cathedral", 1),
      q("The statue in the middle of Jackson Square shows Andrew Jackson…", ["on horseback", "with a cannon", "reading a scroll", "raising a flag"], "on horseback", 1),
      q("The Presbytère on Jackson Square houses a museum about…", ["Mardi Gras", "jazz", "voodoo", "hurricanes"], "Mardi Gras", 3),
      q("The Pontalba Buildings flank Jackson Square and are famed as early…", ["apartment buildings", "hotels", "bank halls", "opera houses"], "apartment buildings", 3),
      q("Lafitte's Blacksmith Shop on Bourbon Street is now a…", ["bar", "museum", "forge", "hotel"], "bar", 2),
      q("Which French Quarter mansion is notorious for ghost stories?", ["LaLaurie Mansion", "Gallier House", "Hermann-Grima House", "Beauregard-Keyes House"], "LaLaurie Mansion", 3),
      q("Frenchmen Street, famous for live music, is in the…", ["Marigny", "Garden District", "Bywater", "Mid-City"], "Marigny", 1),
      q("Many New Orleans streets change names when they cross…", ["Canal Street", "Rampart Street", "Esplanade Avenue", "Poydras Street"], "Canal Street", 2),
      q("Instead of north and south, New Orleanians often say 'lakeside' and…", ["riverside", "gulfside", "bayside", "swampside"], "riverside", 2),
      q("New Orleans's narrow one-room-wide homes are called…", ["shotgun houses", "dogtrot houses", "railroad flats", "saltbox houses"], "shotgun houses", 1),
      q("Much of New Orleans sits…", ["below sea level", "on a plateau", "on an island", "on bedrock"], "below sea level", 1),
      q("The twin bridges from downtown over the Mississippi are the…", ["Crescent City Connection", "Huey P. Long Bridge", "Lake Pontchartrain Causeway", "Twin Span"], "Crescent City Connection", 2),
      q("The paddlewheeler cruising from the French Quarter is the Steamboat…", ["Natchez", "Delta Queen", "Mark Twain", "Memphis Belle"], "Natchez", 1),
      q("Tulane and Loyola universities sit side by side on…", ["St. Charles Avenue", "Canal Street", "Magazine Street", "Esplanade Avenue"], "St. Charles Avenue", 1),
      q("Magazine Street is best known for its…", ["shops and cafés", "riverboat docks", "car dealers", "rail yards"], "shops and cafés", 2),
      q("The New Orleans Museum of Art sits in…", ["City Park", "Audubon Park", "Armstrong Park", "Lafayette Square"], "City Park", 2),
      q("Which uptown park across from Tulane holds the city zoo?", ["Audubon Park", "City Park", "Crescent Park", "Louis Armstrong Park"], "Audubon Park", 1),
      q("New Orleans's airport is named for…", ["Louis Armstrong", "Fats Domino", "Huey Long", "Jean Lafitte"], "Louis Armstrong", 1),
      q("Louis Armstrong's famous nickname was…", ["Satchmo", "Bird", "Duke", "Count"], "Satchmo", 1),
      q("Fats Domino lived for decades in New Orleans's…", ["Lower Ninth Ward", "Garden District", "Treme", "Gentilly"], "Lower Ninth Ward", 2),
      q("Which New Orleans pianist billed himself the inventor of jazz?", ["Jelly Roll Morton", "Fats Waller", "Scott Joplin", "James P. Johnson"], "Jelly Roll Morton", 2),
      q("Gospel queen Mahalia Jackson was born in…", ["New Orleans", "Memphis", "Chicago", "Atlanta"], "New Orleans", 1),
      q("Tipitina's music club is named after a song by…", ["Professor Longhair", "Dr. John", "Allen Toussaint", "Irma Thomas"], "Professor Longhair", 3),
      q("Rapper Lil Wayne grew up in New Orleans's…", ["Hollygrove", "Treme", "Algiers", "Marigny"], "Hollygrove", 2),
      q("Which New Orleans trumpeter co-founded Jazz at Lincoln Center?", ["Wynton Marsalis", "Terence Blanchard", "Kermit Ruffins", "Nicholas Payton"], "Wynton Marsalis", 2),
      q("Troy Andrews, the New Orleans trombonist, goes by…", ["Trombone Shorty", "Big Horn", "Slide Man", "Kid Trombone"], "Trombone Shorty", 1),
      q("The Rebirth is a famous New Orleans…", ["brass band", "riverboat", "church choir", "radio station"], "brass band", 2),
      q("Jazz Fest is held each spring at the…", ["Fair Grounds", "Superdome", "City Park", "Riverfront"], "Fair Grounds", 2),
      q("Mardi Gras means…", ["Fat Tuesday", "Grand Parade", "Mask Day", "Last Feast"], "Fat Tuesday", 1),
      q("Mardi Gras falls the day before…", ["Ash Wednesday", "Easter Sunday", "Palm Sunday", "Good Friday"], "Ash Wednesday", 1),
      q("The official colors of Mardi Gras are purple, green, and…", ["gold", "red", "silver", "white"], "gold", 1),
      q("In Mardi Gras colors, purple stands for…", ["justice", "faith", "power", "joy"], "justice", 2),
      q("Which krewe's riders hand out prized painted coconuts?", ["Zulu", "Rex", "Bacchus", "Endymion"], "Zulu", 1),
      q("The krewe whose monarch reigns as 'King of Carnival' is…", ["Rex", "Comus", "Zulu", "Proteus"], "Rex", 2),
      q("Besides beads, Mardi Gras riders toss aluminum coins called…", ["doubloons", "pieces of eight", "tokens", "medallions"], "doubloons", 2),
      q("Whoever finds the tiny plastic baby in a king cake must…", ["buy the next cake", "lead the parade", "sing a song", "wear a crown all day"], "buy the next cake", 1),
      q("The Superdome opened in…", ["1975", "1967", "1985", "1994"], "1975", 2),
      q("Saints fans' famous chant is…", ["Who Dat", "Geaux Saints", "Laissez les bons", "Fleur Power"], "Who Dat", 1),
      q("The Saints' logo is a…", ["fleur-de-lis", "pelican", "crescent moon", "halo"], "fleur-de-lis", 1),
      q("Which quarterback led the Saints to their first Super Bowl win?", ["Drew Brees", "Archie Manning", "Peyton Manning", "Aaron Brooks"], "Drew Brees", 1),
      q("Before 2013, the Pelicans were called the…", ["Hornets", "Bayou", "Buccaneers", "Pirates"], "Hornets", 2),
      q("The Pelicans play home games at the…", ["Smoothie King Center", "Superdome", "Fair Grounds", "Lakefront Arena"], "Smoothie King Center", 2),
      q("Café du Monde's coffee is blended with roasted…", ["chicory", "pecans", "cocoa", "barley"], "chicory", 2),
      q("Oysters Rockefeller were invented at…", ["Antoine's", "Galatoire's", "Commander's Palace", "Arnaud's"], "Antoine's", 2),
      q("Bananas Foster, flambéed tableside, was created at…", ["Brennan's", "Antoine's", "Galatoire's", "Arnaud's"], "Brennan's", 2),
      q("The turquoise-and-white Garden District restaurant is…", ["Commander's Palace", "Antoine's", "Galatoire's", "Dooky Chase"], "Commander's Palace", 2),
      q("Leah Chase was the celebrated chef of…", ["Dooky Chase's", "Willie Mae's", "Mother's", "Brigtsen's"], "Dooky Chase's", 2),
      q("Willie Mae's Scotch House is famous for its…", ["fried chicken", "oysters", "beignets", "gumbo"], "fried chicken", 3),
      q("The Hurricane cocktail was popularized at…", ["Pat O'Brien's", "Napoleon House", "the Carousel Bar", "Lafitte's"], "Pat O'Brien's", 2),
      q("The frothy egg-white gin drink born in New Orleans is the…", ["Ramos Gin Fizz", "Tom Collins", "Gin Rickey", "French 75"], "Ramos Gin Fizz", 3),
      q("A New Orleans snowball is…", ["shaved ice with syrup", "a coconut cake", "a frozen daiquiri", "a powdered doughnut"], "shaved ice with syrup", 1),
      q("A praline in New Orleans is a candy made with…", ["pecans", "peanuts", "almonds", "walnuts"], "pecans", 1),
      q("The word 'étouffée' means…", ["smothered", "stewed", "blackened", "spicy"], "smothered", 2),
      q("Yakamein, a beef noodle soup, is nicknamed…", ["Old Sober", "Hangover Bowl", "Second Line Soup", "Morning Glory"], "Old Sober", 3),
      q("Hubig's is a New Orleans brand of…", ["fried hand pies", "hot sauce", "potato chips", "root beer"], "fried hand pies", 3),
      q("In New Orleans, to 'make groceries' means to…", ["go grocery shopping", "cook dinner", "open a store", "plant a garden"], "go grocery shopping", 1),
      q("The local word 'lagniappe' means…", ["a little something extra", "a crowded party", "a muddy road", "a rainy day"], "a little something extra", 1),
      q("Locals greet each other with 'Where y'at?', giving the city's accent the name…", ["Yat", "Cajun", "Creole", "Gumbo"], "Yat", 2),
      q("Anne Rice's 'Interview with the Vampire' is set largely in…", ["New Orleans", "Savannah", "Charleston", "Natchez"], "New Orleans", 1),
      q("Lafayette Cemetery No. 1 is in the…", ["Garden District", "French Quarter", "Treme", "Bywater"], "Garden District", 2),
      q("Bourbon Street is named for France's…", ["royal family", "whiskey trade", "first governor", "favorite saint"], "royal family", 2),
      q("By law, Mardi Gras float riders must wear…", ["masks", "beads", "capes", "crowns"], "masks", 3),
      q("The French Quarter's original street grid was laid out by engineer…", ["Adrien de Pauger", "Pierre L'Enfant", "Benjamin Latrobe", "Jean-Baptiste de Bienville"], "Adrien de Pauger", 3),
      q("Abita beer is brewed across Lake Pontchartrain in…", ["Abita Springs", "Slidell", "Covington", "Mandeville"], "Abita Springs", 1),
      q("Crescent Park runs along the Mississippi through the…", ["Bywater", "Garden District", "Lakeview", "Gentilly"], "Bywater", 3),
      q("Mardi Gras Indian suits are hand-sewn from…", ["beads and feathers", "silk and lace", "leather and fur", "sequins and denim"], "beads and feathers", 2),
    ],
  },
  boston: {
    local: [
      q("Boston was founded by Puritan colonists in…", ["1630", "1607", "1676", "1700"], "1630", 1),
      q("Which Puritan leader preached that the colony should be 'a city upon a hill'?", ["John Winthrop", "John Hancock", "Cotton Mather", "William Bradford"], "John Winthrop", 2),
      q("Boston's food nickname is…", ["Beantown", "Chowder City", "Lobster Town", "Codville"], "Beantown", 1),
      q("Oliver Wendell Holmes joked that Boston's State House was the hub of the…", ["Solar System", "New World", "Atlantic", "Railroads"], "Solar System", 3),
      q("Boston baked beans are traditionally sweetened with…", ["molasses", "maple syrup", "honey", "brown sugar"], "molasses", 1),
      q("Boston Latin, founded in 1635, is America's oldest…", ["public school", "college", "newspaper", "library"], "public school", 2),
      q("The Boston Public Library was the first big free library run by a…", ["U.S. city", "church", "university", "state"], "U.S. city", 2),
      q("America's first subway opened in Boston in…", ["1897", "1863", "1904", "1925"], "1897", 2),
      q("Boston's tap-on transit card is the…", ["CharlieCard", "Oyster card", "MetroCard", "Clipper card"], "CharlieCard", 1),
      q("The CharlieCard is named for a man stuck on the T in a song by…", ["the Kingston Trio", "the Beach Boys", "Simon & Garfunkel", "the Byrds"], "the Kingston Trio", 2),
      q("TD Garden is built on top of…", ["North Station", "South Station", "Back Bay Station", "Park Street"], "North Station", 2),
      q("The bronze ducklings in the Public Garden honor the book…", ["Make Way for Ducklings", "The Ugly Duckling", "Duck for President", "Little Quack"], "Make Way for Ducklings", 1),
      q("The bar that inspired the TV show 'Cheers' is on…", ["Beacon Street", "Boylston Street", "Newbury Street", "Hanover Street"], "Beacon Street", 2),
      q("The oldest building in downtown Boston is the home of…", ["Paul Revere", "John Hancock", "Samuel Adams", "Ben Franklin"], "Paul Revere", 2),
      q("Colonists met at the Old South Meeting House just before the…", ["Boston Tea Party", "Boston Massacre", "Battle of Bunker Hill", "Stamp Act riots"], "Boston Tea Party", 2),
      q("The Boston Massacre took place in…", ["1770", "1773", "1775", "1765"], "1770", 1),
      q("The first man killed in the Boston Massacre was…", ["Crispus Attucks", "Christopher Seider", "Samuel Gray", "James Caldwell"], "Crispus Attucks", 2),
      q("The Bunker Hill Monument is a tall granite…", ["obelisk", "arch", "column", "statue"], "obelisk", 1),
      q("Boston celebrates the British army's 1776 departure on…", ["Evacuation Day", "Liberty Day", "Patriots' Day", "Harbor Day"], "Evacuation Day", 2),
      q("The Boston Marathon starts in the town of…", ["Hopkinton", "Framingham", "Wellesley", "Natick"], "Hopkinton", 2),
      q("The Boston Marathon's toughest climb, in Newton, is…", ["Heartbreak Hill", "Breakneck Hill", "Agony Rise", "Bunker Hill"], "Heartbreak Hill", 1),
      q("Fenway fans sing which Neil Diamond song in the eighth inning?", ["Sweet Caroline", "Cracklin' Rosie", "America", "Song Sung Blue"], "Sweet Caroline", 1),
      q("Fans blamed the Red Sox's long title drought on the Curse of the…", ["Bambino", "Billy Goat", "Green Monster", "Colonel"], "Bambino", 1),
      q("The Red Sox ended their 86-year World Series drought in…", ["2004", "1986", "2007", "2013"], "2004", 1),
      q("Fenway's right-field foul pole is nicknamed…", ["Pesky's Pole", "Fisk's Pole", "Ted's Pole", "Yaz's Pole"], "Pesky's Pole", 2),
      q("A lone red seat in Fenway's bleachers marks a record home run by…", ["Ted Williams", "David Ortiz", "Carl Yastrzemski", "Babe Ruth"], "Ted Williams", 2),
      q("Ted Williams was the last big-leaguer to bat four hundred for a season, in…", ["1941", "1927", "1956", "1968"], "1941", 2),
      q("Celtics legend Bill Russell won how many NBA titles as a player?", ["11", "6", "8", "13"], "11", 2),
      q("Celtics coach Red Auerbach celebrated wins by lighting a…", ["cigar", "candle", "pipe", "sparkler"], "cigar", 2),
      q("The Celtics' mascot is a leprechaun named…", ["Lucky", "Paddy", "Clover", "Shamrock"], "Lucky", 2),
      q("Bobby Orr's famous 1970 'flying goal' won the Stanley Cup for the…", ["Bruins", "Canadiens", "Rangers", "Blackhawks"], "Bruins", 1),
      q("The Patriots play home games at…", ["Gillette Stadium", "Fenway Park", "Harvard Stadium", "TD Garden"], "Gillette Stadium", 1),
      q("Boston's amphibious sightseeing tours, also used for title parades, ride…", ["Duck Boats", "Swan Boats", "Hovercraft", "Trolleys"], "Duck Boats", 1),
      q("The cable-stayed bridge over the Charles built for the Big Dig is the…", ["Zakim Bridge", "Longfellow Bridge", "Tobin Bridge", "Mass Ave Bridge"], "Zakim Bridge", 2),
      q("The park built where the old elevated highway stood is the Rose Kennedy…", ["Greenway", "Esplanade", "Commons", "Parkway"], "Greenway", 2),
      q("New England's tallest building, 200 Clarendon, was long called the…", ["John Hancock Tower", "Prudential Tower", "State Street Tower", "Custom House Tower"], "John Hancock Tower", 2),
      q("The big red-and-blue sign glowing over Kenmore Square advertises…", ["Citgo", "Shell", "Mobil", "Gulf"], "Citgo", 1),
      q("The long food hall beside Faneuil Hall is…", ["Quincy Market", "Haymarket", "Boston Market", "Bulfinch Market"], "Quincy Market", 1),
      q("The Union Oyster House is America's oldest continuously operating…", ["restaurant", "hotel", "fish market", "tavern"], "restaurant", 2),
      q("Two rival North End bakeries famous for cannoli are Modern and…", ["Mike's", "Tony's", "Sal's", "Joe's"], "Mike's", 1),
      q("Dunkin' served its first doughnuts in 1950 in…", ["Quincy", "Cambridge", "Worcester", "Lowell"], "Quincy", 2),
      q("Marshmallow Fluff was invented in Boston's neighbor…", ["Somerville", "Brookline", "Newton", "Medford"], "Somerville", 2),
      q("A Fluff-and-peanut-butter sandwich is called a…", ["Fluffernutter", "Nutterfluff", "Peanut Puff", "Marshmallowich"], "Fluffernutter", 1),
      q("In Boston, a milkshake made with ice cream is a…", ["frappe", "cabinet", "malted", "float"], "frappe", 2),
      q("Bostonians call a liquor store a…", ["packie", "bodega", "offie", "party store"], "packie", 2),
      q("A Bostonian asking for the 'bubbler' wants a…", ["water fountain", "soda", "hot tub", "bubble tea"], "water fountain", 2),
      q("In Boston, a roundabout is usually called a…", ["rotary", "circle", "loop", "carousel"], "rotary", 2),
      q("Sprinkles on Boston ice cream are called…", ["jimmies", "nonpareils", "hundreds", "dots"], "jimmies", 2),
      q("Bostonians use 'wicked' to mean…", ["very", "evil", "strange", "cold"], "very", 1),
      q("Ether was first publicly demonstrated in surgery in 1846 at…", ["Mass General", "Boston City Hospital", "Brigham and Women's", "Tufts Medical"], "Mass General", 3),
      q("Alexander Graham Bell made his first telephone call in Boston in…", ["1876", "1888", "1859", "1901"], "1876", 2),
      q("In 1919, a burst tank flooded Boston's North End with…", ["molasses", "beer", "oil", "milk"], "molasses", 2),
      q("The New England Aquarium is famous for its…", ["Giant Ocean Tank", "Shark Tunnel", "Kelp Forest", "Penguin Dome"], "Giant Ocean Tank", 2),
      q("The giant wooden landmark outside the Boston Children's Museum is a…", ["milk bottle", "rocking horse", "teddy bear", "lighthouse"], "milk bottle", 2),
      q("The JFK Presidential Library on Columbia Point was designed by…", ["I. M. Pei", "Philip Johnson", "Frank Gehry", "Eero Saarinen"], "I. M. Pei", 2),
      q("The Mapparium lets visitors walk inside a giant…", ["stained-glass globe", "whale skeleton", "ship's hull", "pipe organ"], "stained-glass globe", 2),
      q("Boston's Emerald Necklace chain of parks was designed by…", ["Frederick Law Olmsted", "Charles Bulfinch", "Calvert Vaux", "Daniel Burnham"], "Frederick Law Olmsted", 2),
      q("The Arnold Arboretum is run by…", ["Harvard", "MIT", "Boston University", "Tufts"], "Harvard", 2),
      q("Boston's largest neighborhood by area is…", ["Dorchester", "Roxbury", "Back Bay", "Charlestown"], "Dorchester", 3),
      q("South Boston, home of a big St. Patrick's Day parade, is nicknamed…", ["Southie", "SoBo", "Dot", "the South End"], "Southie", 1),
      q("Acorn Street, often called the most photographed street in America, is on…", ["Beacon Hill", "Back Bay", "the North End", "Charlestown"], "Beacon Hill", 2),
      q("Boston's famous music college is…", ["Berklee", "Juilliard", "Eastman", "Curtis"], "Berklee", 1),
      q("Arthur Fiedler led which orchestra for nearly 50 years?", ["Boston Pops", "Boston Symphony", "Handel and Haydn", "Cambridge Philharmonic"], "Boston Pops", 2),
      q("Which rock band, formed in Boston in 1970, sang 'Dream On'?", ["Aerosmith", "Boston", "The Cars", "J. Geils Band"], "Aerosmith", 1),
      q("The boy band New Kids on the Block came from…", ["Dorchester", "Quincy", "Salem", "Newton"], "Dorchester", 2),
      q("'I'm Shipping Up to Boston' is a hit by…", ["Dropkick Murphys", "The Pogues", "Flogging Molly", "Mighty Mighty Bosstones"], "Dropkick Murphys", 1),
      q("Matt Damon and Ben Affleck won an Oscar for writing which Boston film?", ["Good Will Hunting", "The Departed", "Mystic River", "The Town"], "Good Will Hunting", 1),
      q("Founding Father Benjamin Franklin was born in…", ["Boston", "Philadelphia", "New York", "Providence"], "Boston", 1),
      q("Writer Edgar Allan Poe was born in…", ["Boston", "Baltimore", "Richmond", "Philadelphia"], "Boston", 2),
      q("John F. Kennedy was born in Boston's neighbor…", ["Brookline", "Cambridge", "Quincy", "Hyannis"], "Brookline", 2),
      q("Harvard, founded in 1636, is America's oldest…", ["university", "hospital", "newspaper", "bank"], "university", 1),
      q("Faneuil Hall's famous copper weathervane is shaped like a…", ["grasshopper", "codfish", "rooster", "whale"], "grasshopper", 2),
      q("In winter, the Frog Pond on Boston Common becomes a…", ["skating rink", "sledding hill", "snow fort", "curling sheet"], "skating rink", 1),
      q("Newbury Street in Back Bay is best known for…", ["shops and galleries", "shipyards", "breweries", "car dealers"], "shops and galleries", 1),
      q("Hanover Street is the main drag of Boston's…", ["North End", "South End", "Seaport", "Fenway"], "North End", 1),
      q("Christian Science Plaza in Boston is known for its long…", ["reflecting pool", "rose garden", "glass bridge", "clock tower"], "reflecting pool", 2),
    ],
  },
};
