import { q } from "../quiz";
import type { TriviaQ } from "../types";

export const GAMES_BANK: TriviaQ[] = [
  q("Mario's brother is named…", ["Luigi", "Wario", "Waluigi", "Toad"], "Luigi", 1),
  q("The Switch console is made by…", ["Sony", "Nintendo", "Microsoft", "Sega"], "Nintendo", 1),
  q("PlayStation consoles are made by…", ["Sony", "Nintendo", "Microsoft", "Atari"], "Sony", 1),
  q("Xbox consoles are made by…", ["Microsoft", "Sony", "Nintendo", "Sega"], "Microsoft", 1),
  q("Pac-Man is famous for eating…", ["dots", "bricks", "rings", "coins"], "dots", 1),
  q("Pikachu is a…", ["Pokémon", "Digimon", "Kirby enemy", "Chao"], "Pokémon", 1),
  q("The hero of The Legend of Zelda is…", ["Link", "Zelda", "Ganon", "Mario"], "Link", 1),
  q("Master Chief is the armored hero of…", ["Halo", "Metroid", "Doom", "Half-Life"], "Halo", 1),
  q("Minecraft is built out of…", ["blocks", "cards", "marbles", "pixels of sand"], "blocks", 1),
  q("Sonic is a blue…", ["hedgehog", "fox", "turtle", "bear"], "hedgehog", 1),
  q("In Tetris, the pieces fall from the…", ["top", "left", "bottom", "right"], "top", 1),
  q("Mario is usually described as a…", ["plumber", "chef", "pilot", "librarian"], "plumber", 1),
  q("The princess Mario often rescues is…", ["Peach", "Zelda", "Samus", "Rosalina"], "Peach", 1),
  q("Bowser is the main villain of…", ["Mario games", "Pokémon", "Halo", "Minecraft"], "Mario games", 1),
  q("An NPC in a game is a…", ["non-player character", "new power crystal", "network ping check", "nintendo power card"], "non-player character", 1),
  q("FPS, as a game genre, means…", ["first-person shooter", "final player score", "fast puzzle set", "four-player sport"], "first-person shooter", 1),
  q("A 1-up gives you…", ["an extra life", "a new console", "a bonus coin", "a power boost"], "an extra life", 1),
  q("Steam, the PC game shop, is run by…", ["Valve", "Nintendo", "Sony", "Epic Games"], "Valve", 1),
  q("Yoshi is Mario's dinosaur friend and is classically…", ["green", "red", "purple", "orange"], "green", 1),
  q("Princess Zelda's kingdom is…", ["Hyrule", "Mushroom Kingdom", "Midgar", "Lordran"], "Hyrule", 1),
  q("Tetris was designed by…", ["Alexey Pajitnov", "Shigeru Miyamoto", "Hideo Kojima", "Sid Meier"], "Alexey Pajitnov", 2),
  q("Super Mario Bros. first came out for the NES in…", ["1985", "1977", "1991", "1996"], "1985", 2),
  q("Shigeru Miyamoto is the Nintendo designer behind Mario and…", ["The Legend of Zelda", "Halo: Combat Evolved", "Tetris", "Sonic the Hedgehog"], "The Legend of Zelda", 2),
  q("Pac-Man was released in arcades in…", ["1980", "1972", "1989", "1995"], "1980", 2),
  q("The original Pokémon games included how many species?", ["151", "100", "251", "50"], "151", 2),
  q("The Nintendo Game Boy launched in…", ["1989", "1983", "1996", "2001"], "1989", 2),
  q("The first PlayStation console launched in Japan in…", ["1994", "1989", "1998", "2001"], "1994", 2),
  q("The Nintendo 64 launched in…", ["1996", "1991", "2001", "1985"], "1996", 2),
  q("The original Halo was developed by…", ["Bungie", "id Software", "Rare", "Capcom"], "Bungie", 2),
  q("The Last of Us was developed by…", ["Naughty Dog", "Valve", "Nintendo", "Blizzard"], "Naughty Dog", 2),
  q("Portal was developed by…", ["Valve", "Bungie", "FromSoftware", "Sega"], "Valve", 2),
  q("World of Warcraft was developed by…", ["Blizzard", "Riot Games", "Epic Games", "Square"], "Blizzard", 2),
  q("Fortnite was developed by…", ["Epic Games", "Valve", "Nintendo", "Rockstar"], "Epic Games", 2),
  q("The Witcher 3 was developed by…", ["CD Projekt Red", "BioWare", "Bethesda Game Studios", "Ubisoft Montreal"], "CD Projekt Red", 2),
  q("Stardew Valley was made primarily by…", ["Eric Barone", "Toby Fox", "Hideo Kojima", "Will Wright"], "Eric Barone", 2),
  q("Undertale was created by…", ["Toby Fox", "Eric Barone", "Edmund McMillen", "Markus Persson"], "Toby Fox", 2),
  q("The Konami code begins…", ["up, up, down, down", "left, right, left, right", "B, A, start", "down, down, up, up"], "up, up, down, down", 2),
  q("The 1993 game Doom was made by…", ["id Software", "Valve Corporation", "Bungie Studios", "Rare"], "id Software", 2),
  q("The hero of Final Fantasy VII is…", ["Cloud Strife", "Sephiroth", "Link", "Geralt"], "Cloud Strife", 2),
  q("Samus Aran is the bounty hunter of…", ["Metroid", "Halo", "Mega Man", "Star Fox"], "Metroid", 2),
  q("Lara Croft is the star of…", ["Tomb Raider", "Uncharted", "Resident Evil", "Assassin's Creed"], "Tomb Raider", 2),
  q("Kratos is the protagonist of…", ["God of War", "Hades", "Diablo", "Asura's Wrath"], "God of War", 2),
  q("Geralt of Rivia is the monster hunter in…", ["The Witcher", "Dragon Age", "Skyrim", "Dark Souls"], "The Witcher", 2),
  q("GoldenEye 007 on the Nintendo 64 was developed by…", ["Rare", "id Software", "DMA Design", "Rockstar"], "Rare", 2),
  q("Sonic the Hedgehog games come from…", ["Sega", "Nintendo", "Atari", "Capcom"], "Sega", 2),
  q("Space Invaders was released in…", ["1978", "1972", "1985", "1962"], "1978", 3),
  q("Pong, the early paddle game, came from Atari in…", ["1972", "1965", "1980", "1985"], "1972", 3),
  q("In the arcade game Donkey Kong, Mario was first called…", ["Jumpman", "Luigi", "Foreman Spike", "Mario Mario"], "Jumpman", 3),
  q("Nintendo began in 1889 as a company that made…", ["playing cards", "radios", "bicycles", "film cameras"], "playing cards", 3),
  q("Pac-Man's four ghosts are Blinky, Pinky, Inky, and…", ["Clyde", "Sue", "Winky", "Pokey"], "Clyde", 3),
  q("The full classic Konami code is up, up, down, down, left, right, left, right, then…", ["B, A", "A, B", "start", "select, start"], "B, A", 3),
  q("Final Fantasy was created by…", ["Hironobu Sakaguchi", "Hideo Kojima", "Shigeru Miyamoto", "Yu Suzuki"], "Hironobu Sakaguchi", 3),
  q("Metal Gear Solid was directed by…", ["Hideo Kojima", "Hironobu Sakaguchi", "Shinji Mikami", "Suda51"], "Hideo Kojima", 3),
  q("John Carmack was the lead programmer of…", ["Doom", "Minecraft", "Pac-Man", "The Sims"], "Doom", 3),
  q("Minecraft was first created by…", ["Markus Persson", "Jens Bergensten", "Gabe Newell", "Tim Sweeney"], "Markus Persson", 3),
  q("Pokémon was created by…", ["Satoshi Tajiri", "Shigeru Miyamoto", "Ken Sugimori", "Junichi Masuda"], "Satoshi Tajiri", 3),
  q("The first Legend of Zelda was released in…", ["1986", "1983", "1991", "1998"], "1986", 3),
  q("The Legend of Zelda: Ocarina of Time came out in…", ["1998", "1996", "2000", "1991"], "1998", 3),
  q("Standard Tetris uses how many tetromino shapes?", ["7", "5", "6", "8"], "7", 3),
  q("The original Metroid ends by revealing that Samus is…", ["a woman", "a robot", "Link's sister", "a Metroid"], "a woman", 3),
  q("The original Xbox launched in North America in…", ["2001", "1998", "2005", "1994"], "2001", 3),
  q("The Legend of Zelda: Breath of the Wild launched in…", ["2017", "2011", "2015", "2022"], "2017", 3),
  q("Elden Ring was directed by Hidetaka Miyazaki at…", ["FromSoftware", "Capcom", "Square Enix", "Bandai Namco"], "FromSoftware", 3),
  // v0.0.28: +games batch (mostly easy; a handful of deep-history cards).
  q("Ash Ketchum's first Pokémon partner is…", ["Pikachu", "Charmander", "Squirtle", "Bulbasaur"], "Pikachu", 1),
  q("Pokémon's famous slogan is Gotta catch 'em…", ["all", "now", "fast", "first"], "all", 1),
  q("Charmander evolves into…", ["Charmeleon", "Charizard", "Wartortle", "Ivysaur"], "Charmeleon", 1),
  q("Which balloon-shaped Pokémon sings foes to sleep?", ["Jigglypuff", "Clefairy", "Togepi", "Snorlax"], "Jigglypuff", 1),
  q("Pokémon trainers catch wild Pokémon in a…", ["Poké Ball", "Poké Box", "Master Cage", "Trainer Net"], "Poké Ball", 1),
  q("In Pokémon, which type is strong against Fire?", ["Water", "Grass", "Bug", "Ice"], "Water", 1),
  q("In Pokémon Red and Blue, your first Pokémon comes from…", ["Professor Oak", "Professor Elm", "Nurse Joy", "Gary Oak"], "Professor Oak", 1),
  q("Team Rocket's trio is Jessie, James, and…", ["Meowth", "Psyduck", "Ekans", "Koffing"], "Meowth", 1),
  q("Pokémon Go has players catch Pokémon by…", ["walking around outside", "trading cards by mail", "drawing on a tablet", "singing to the phone"], "walking around outside", 1),
  q("Donkey Kong is a giant…", ["gorilla", "bear", "dinosaur", "lion"], "gorilla", 1),
  q("Donkey Kong's cap-wearing monkey sidekick is…", ["Diddy Kong", "Funky Kong", "Cranky Kong", "Dixie Kong"], "Diddy Kong", 1),
  q("Kirby copies enemies' powers by…", ["inhaling them", "high-fiving them", "stomping them", "painting them"], "inhaling them", 1),
  q("Wario's tall, purple-clad partner in mischief is…", ["Waluigi", "Dry Bones", "King Boo", "Shy Guy"], "Waluigi", 1),
  q("In Mario Kart, the item that hunts down the race leader is the…", ["Spiny Shell", "Red Shell", "Bullet Bill", "Banana"], "Spiny Shell", 1),
  q("A Super Mushroom makes Mario…", ["grow bigger", "fly", "turn invisible", "shrink"], "grow bigger", 1),
  q("A Fire Flower lets Mario throw…", ["fireballs", "hammers", "ice cubes", "boomerangs"], "fireballs", 1),
  q("Grabbing a Super Star makes Mario briefly…", ["invincible", "giant", "invisible", "frozen"], "invincible", 1),
  q("In Super Mario Bros., collecting 100 coins earns…", ["an extra life", "a new world", "a free continue", "a star"], "an extra life", 1),
  q("The red letter on Mario's cap is…", ["M", "N", "S", "L"], "M", 1),
  q("Luigi's Mansion has Luigi catching ghosts with a…", ["vacuum", "net", "lantern", "jar"], "vacuum", 1),
  q("Link's legendary blade is the…", ["Master Sword", "Buster Sword", "Keyblade", "Soul Edge"], "Master Sword", 1),
  q("Zelda's Triforce is made of three golden…", ["triangles", "circles", "squares", "stars"], "triangles", 1),
  q("The recurring villain of The Legend of Zelda is…", ["Ganon", "Bowser", "Ridley", "Dr. Wily"], "Ganon", 1),
  q("Sonic collects golden…", ["rings", "coins", "stars", "bananas"], "rings", 1),
  q("Sonic's two-tailed fox friend is…", ["Tails", "Knuckles", "Shadow", "Amy"], "Tails", 1),
  q("Sonic's mustached archenemy is…", ["Dr. Eggman", "Dr. Wily", "Dr. Mario", "Dr. Light"], "Dr. Eggman", 1),
  q("Minecraft's green mob that sneaks up and explodes is the…", ["Creeper", "Zombie", "Enderman", "Slime"], "Creeper", 1),
  q("Minecraft's default player character is named…", ["Steve", "Alex", "Herobrine", "Notch"], "Steve", 1),
  q("In the falling-block classic, clearing four lines at once is called a…", ["Tetris", "Quad", "Combo", "Sweep"], "Tetris", 1),
  q("Eating a power pellet lets Pac-Man chase…", ["ghosts", "fruit", "dots", "keys"], "ghosts", 1),
  q("Fortnite's last-player-standing mode is called…", ["Battle Royale", "Capture the Flag", "Deathmatch", "King of the Hill"], "Battle Royale", 1),
  q("Fortnite players can quickly build…", ["walls and ramps", "cars and boats", "farms and mills", "rails and trains"], "walls and ramps", 1),
  q("In Among Us, the hidden saboteur is the…", ["Impostor", "Traitor", "Spy", "Mole"], "Impostor", 1),
  q("Animal Crossing's shopkeeper and home-loan lender is…", ["Tom Nook", "Isabelle", "K.K. Slider", "Blathers"], "Tom Nook", 1),
  q("Angry Birds players fling birds at…", ["pigs", "cats", "snakes", "foxes"], "pigs", 1),
  q("Candy Crush Saga is a…", ["match-three puzzle", "kart racing game", "collectible card battler", "word search puzzle"], "match-three puzzle", 1),
  q("Call of Duty is a long-running series of…", ["military shooters", "street racing games", "football sports sims", "block puzzle games"], "military shooters", 1),
  q("In Street Fighter, Ryu's fireball move is the…", ["Hadouken", "Shoryuken", "Kamehameha", "Sonic Boom"], "Hadouken", 1),
  q("Mortal Kombat's gruesome finishing move is a…", ["Fatality", "Knockout", "Takedown", "Finale"], "Fatality", 1),
  q("Frogger has a frog trying to cross a road and a…", ["river", "bridge", "rooftop", "maze"], "river", 1),
  q("The NES game Duck Hunt was played with a…", ["light gun", "steering wheel", "dance mat", "microphone"], "light gun", 1),
  q("The Wii's motion-sensing controller is the…", ["Wii Remote", "Joy-Con", "DualShock", "Wavebird"], "Wii Remote", 1),
  q("PlayStation's face buttons are triangle, circle, cross, and…", ["square", "star", "diamond", "heart"], "square", 1),
  q("The Nintendo DS is famous for having…", ["two screens", "no buttons", "a keyboard", "a camera arm"], "two screens", 1),
  q("The Nintendo Switch's detachable controllers are called…", ["Joy-Con", "Wiimotes", "Nunchuks", "Gamepads"], "Joy-Con", 1),
  q("In Halo, Master Chief's AI companion is…", ["Cortana", "GLaDOS", "EDI", "Siri"], "Cortana", 1),
  q("Portal's famous running joke is that the cake is a…", ["lie", "trap", "bomb", "prize"], "lie", 1),
  q("Roblox is best known for games made by…", ["its own players", "Nintendo", "movie studios", "TV networks"], "its own players", 1),
  q("Pong is a simple video version of…", ["table tennis", "air hockey", "miniature golf", "tenpin bowling"], "table tennis", 1),
  q("Super Smash Bros. belongs to which game genre?", ["fighting", "racing", "puzzle", "rhythm"], "fighting", 1),
  q("Crash Bandicoot first starred on the…", ["PlayStation", "Nintendo 64", "Sega Saturn", "Xbox"], "PlayStation", 1),
  q("Spyro is a small purple…", ["dragon", "dinosaur", "lizard", "bat"], "dragon", 1),
  q("Red Dead Redemption is set in the…", ["American Old West", "Roman Empire's frontier", "far-future space colony", "last Ice Age"], "American Old West", 1),
  q("Guitar Hero is played with a plastic…", ["guitar controller", "drum pad controller", "keyboard controller", "USB microphone"], "guitar controller", 1),
  q("The arcade hit DDR is played by stepping on a…", ["dance pad", "balance board", "treadmill", "pogo stick"], "dance pad", 1),
  q("In Splatoon, players battle by spraying…", ["ink", "water", "paint balls", "foam"], "ink", 1),
  q("Rocket League is basically soccer played with…", ["cars", "robots", "horses", "jetpacks"], "cars", 1),
  q("Twitch is best known for live-streaming…", ["video games", "news", "cooking", "concerts"], "video games", 1),
  q("Speedrunners try to finish a game…", ["as fast as possible", "without a controller", "blindfolded only", "in a single life"], "as fast as possible", 1),
  q("In games, a 'boss' is usually a…", ["powerful enemy", "level editor", "save point", "shop owner"], "powerful enemy", 1),
  q("To 'respawn' in a game means to…", ["come back to life", "save the game", "change teams", "pause the match"], "come back to life", 1),
  q("Gamers type 'GG' at the end of a match to say…", ["good game", "go go", "get going", "great goal"], "good game", 1),
  q("A hidden joke or secret tucked inside a game is an…", ["Easter egg", "Easter basket", "inside job", "add-on"], "Easter egg", 1),
  q("A brand-new, inexperienced player is often called a…", ["noob", "pro", "mod", "dev"], "noob", 1),
  q("RPG, as a game genre, stands for…", ["role-playing game", "rapid puzzle game", "real player grid", "racing pursuit game"], "role-playing game", 1),
  q("In many games, 'HP' stands for…", ["hit points", "high power", "hero points", "health pack"], "hit points", 1),
  q("Extra content you download for a game is called…", ["DLC", "RAM", "LAN", "NPC"], "DLC", 1),
  q("The game label MMO stands for massively multiplayer…", ["online", "operation", "overdrive", "open-world"], "online", 1),
  q("A player who is 'AFK' is…", ["away from the keyboard", "about to quit", "on a winning streak", "playing a new map"], "away from the keyboard", 1),
  q("NES stands for Nintendo Entertainment…", ["System", "Station", "Studio", "Set"], "System", 1),
  q("In Ocarina of Time, Link's fairy who shouts 'Hey, listen!' is…", ["Navi", "Tatl", "Midna", "Fi"], "Navi", 2),
  q("Knuckles in the Sonic games is an…", ["echidna", "armadillo", "anteater", "aardvark"], "echidna", 2),
  q("Minecraft's fiery underworld dimension is the…", ["Nether", "End", "Abyss", "Void"], "Nether", 2),
  q("Minecraft's final boss is the…", ["Ender Dragon", "Wither King", "Nether Wyrm", "Creeper Queen"], "Ender Dragon", 2),
  q("The made-up language spoken in The Sims is…", ["Simlish", "Simspeak", "Plumbese", "Sim-Speak Lite"], "Simlish", 2),
  q("The green diamond floating over a Sim's head is the…", ["plumbob", "mood gem", "sim crystal", "life jewel"], "plumbob", 2),
  q("Grand Theft Auto V was made by…", ["Rockstar", "Ubisoft", "Bethesda", "Treyarch"], "Rockstar", 2),
  q("Points earned from Xbox achievements add up to a player's…", ["Gamerscore", "Trophy Level", "XP Bank", "Star Rank"], "Gamerscore", 2),
  q("Portal's sarcastic AI villain is…", ["GLaDOS", "SHODAN", "HAL", "Cortana"], "GLaDOS", 2),
  q("Half-Life's crowbar-wielding scientist hero is…", ["Gordon Freeman", "Isaac Clarke", "Adam Jensen", "Alyx Vance"], "Gordon Freeman", 2),
  q("League of Legends was made by…", ["Riot Games", "Blizzard", "Valve", "Epic Games"], "Riot Games", 2),
  q("Mega Man's arm cannon is the…", ["Mega Buster", "Power Glove", "Arm Blaster", "Proton Pack"], "Mega Buster", 2),
  q("In Assassin's Creed, diving from a height into a haystack is the…", ["Leap of Faith", "Eagle Drop", "Hay Dive", "Death Jump"], "Leap of Faith", 2),
  q("In Skyrim, the hero who can absorb dragon souls is the…", ["Dragonborn", "Dragon Knight", "Dragon Priest", "Wyrmslayer"], "Dragonborn", 2),
  q("The original Game Boy's screen showed shades of…", ["green", "blue", "red", "purple"], "green", 2),
  q("Luigi's ghost-catching vacuum is called the…", ["Poltergust", "Ghostbuster", "Spooksucker", "Boo Vac"], "Poltergust", 2),
  q("Kirby's home in his games is…", ["Dream Land", "Toad Town", "Hyrule", "Green Hill"], "Dream Land", 2),
  q("Star Fox hero Fox McCloud flies a starfighter called the…", ["Arwing", "X-Wing", "Viper", "Blue Falcon"], "Arwing", 2),
  q("F-Zero's helmeted hero is…", ["Captain Falcon", "Captain Olimar", "Captain Toad", "Captain Price"], "Captain Falcon", 2),
  q("In North America, Sega's 16-bit Mega Drive was sold as the…", ["Genesis", "Saturn", "Master System", "Nomad"], "Genesis", 2),
  q("Sega's final home console was the…", ["Dreamcast", "Saturn", "Genesis", "Game Gear"], "Dreamcast", 2),
  q("The Atari 2600 game E.T. is infamous as a…", ["huge flop", "surprise hit", "banned game", "lost prototype"], "huge flop", 2),
  q("Nintendo's 1995 Virtual Boy showed its 3D images in…", ["red", "green", "blue", "white"], "red", 2),
  q("The Steam Deck handheld PC is made by…", ["Valve", "Sony", "Nintendo", "Razer"], "Valve", 2),
  q("The Sims was created by…", ["Will Wright", "Sid Meier", "Peter Molyneux", "John Romero"], "Will Wright", 2),
  q("The Civilization strategy series is named for its creator…", ["Sid Meier", "Will Wright", "Richard Garriott", "Brian Reynolds"], "Sid Meier", 2),
  q("The Legend of Zelda: A Link to the Past came out on the…", ["Super Nintendo", "NES", "Nintendo 64", "Game Boy"], "Super Nintendo", 2),
  q("The arcade shooter Galaga was made by…", ["Namco", "Atari", "Taito", "Konami"], "Namco", 2),
  q("In North America, the original Game Boy came bundled with…", ["Tetris", "Super Mario Land", "Pokémon Red", "Kirby's Dream Land"], "Tetris", 2),
  q("Hollow Knight was made by the small Australian studio…", ["Team Cherry", "Supergiant", "Motion Twin", "Moon Studios"], "Team Cherry", 2),
  q("Cuphead's art style imitates…", ["1930s cartoons", "Japanese woodblocks", "comic-book ink", "stained glass"], "1930s cartoons", 2),
  q("In Hades, Zagreus fights to escape from…", ["the Underworld", "Mount Olympus", "Atlantis", "the Labyrinth"], "the Underworld", 2),
  q("The money in Animal Crossing is called…", ["Bells", "Rupees", "Gil", "Zenny"], "Bells", 2),
  q("The money in The Legend of Zelda is called…", ["Rupees", "Bells", "Gil", "Munny"], "Rupees", 2),
  q("Final Fantasy's yellow riding mount, the chocobo, is a…", ["bird", "horse", "lizard", "wolf"], "bird", 2),
  q("Kingdom Hearts mixes Final Fantasy characters with…", ["Disney characters", "Marvel heroes", "Pokémon", "Looney Tunes"], "Disney characters", 2),
  q("Metal Gear Solid's stealthy hero is…", ["Solid Snake", "Sam Fisher", "Agent 47", "Max Payne"], "Solid Snake", 2),
  q("Resident Evil's sinister drug company is…", ["Umbrella Corporation", "Aperture Science", "Abstergo", "Shinra"], "Umbrella Corporation", 2),
  q("In Pokémon, Mewtwo was created as a clone of…", ["Mew", "Ditto", "Eevee", "Lugia"], "Mew", 2),
  q("BioShock takes place in an underwater city called…", ["Rapture", "Atlantis", "Columbia", "Aquaria"], "Rapture", 2),
  q("Mass Effect's hero is Commander…", ["Shepard", "Keeler", "Price", "Hawke"], "Shepard", 2),
  q("Uncharted's treasure-hunting hero is…", ["Nathan Drake", "Lara Croft", "Indiana Jones", "Sam Fisher"], "Nathan Drake", 2),
  q("Atari was co-founded by Nolan Bushnell and…", ["Ted Dabney", "Ralph Baer", "Steve Jobs", "Al Alcorn"], "Ted Dabney", 3),
  q("The first home video game console, the Magnavox Odyssey, came out in…", ["1972", "1967", "1977", "1980"], "1972", 3),
  q("Ralph Baer is often called the father of the…", ["home video game console", "coin-op arcade cabinet", "analog joystick controller", "personal computer game"], "home video game console", 3),
  q("The early computer game Spacewar! was created in 1962 at…", ["MIT", "Stanford", "Bell Labs", "IBM"], "MIT", 3),
  q("Tennis for Two, a 1958 game, was displayed on an…", ["oscilloscope", "arcade screen", "TV set", "printer"], "oscilloscope", 3),
  q("Nintendo's Famicom launched in Japan in…", ["1983", "1979", "1986", "1989"], "1983", 3),
  q("The great North American video game crash hit in…", ["1983", "1977", "1989", "1995"], "1983", 3),
  q("Sonic the Hedgehog debuted in…", ["1991", "1987", "1994", "1989"], "1991", 3),
  q("Street Fighter II hit arcades in…", ["1991", "1985", "1995", "1988"], "1991", 3),
  q("The ESRB game-rating board was founded in…", ["1994", "1985", "2000", "1990"], "1994", 3),
  q("The 1993 puzzle adventure Myst was made by…", ["Cyan", "Sierra", "LucasArts", "Infocom"], "Cyan", 3),
  q("Valve's first game, Half-Life, came out in…", ["1998", "1994", "2001", "2004"], "1998", 3),
  q("Shigeru Miyamoto's first big arcade hit was…", ["Donkey Kong", "Pac-Man", "Space Invaders", "Galaxian"], "Donkey Kong", 3),
  q("Who composed the classic Super Mario Bros. and Zelda themes?", ["Koji Kondo", "Nobuo Uematsu", "Yoko Shimomura", "Yasunori Mitsuda"], "Koji Kondo", 3),
  q("Nobuo Uematsu is famous for composing the music of…", ["Final Fantasy", "Super Mario", "Sonic", "Metroid"], "Final Fantasy", 3),
  q("Final Fantasy VII first came out in…", ["1997", "1994", "2000", "1991"], "1997", 3),
  q("The original Resident Evil was directed by…", ["Shinji Mikami", "Hideo Kojima", "Keiji Inafune", "Yuji Naka"], "Shinji Mikami", 3),
  q("Pokémon Red and Green first came out in Japan in…", ["1996", "1993", "1999", "1990"], "1996", 3),
  q("The Game Boy was designed by Nintendo's…", ["Gunpei Yokoi", "Satoru Iwata", "Masahiro Sakurai", "Hiroshi Yamauchi"], "Gunpei Yokoi", 3),
  q("Grand Theft Auto began at DMA Design, a studio in…", ["Scotland", "Canada", "Ireland", "Wales"], "Scotland", 3),
  q("Banjo-Kazooie's developer, Rare, is based in…", ["England", "Japan", "Canada", "Sweden"], "England", 3),
  q("Valve was co-founded by Gabe Newell and…", ["Mike Harrington", "John Carmack", "Tim Sweeney", "Cliff Bleszinski"], "Mike Harrington", 3),
  q("Chrono Trigger's characters were drawn by Dragon Ball creator…", ["Akira Toriyama", "Yoshitaka Amano", "Tetsuya Nomura", "Eiichiro Oda"], "Akira Toriyama", 3),
  q("The Dragon Quest series was created by…", ["Yuji Horii", "Hironobu Sakaguchi", "Koichi Sugiyama", "Shinji Mikami"], "Yuji Horii", 3),
  q("Tetris was created in the Soviet Union in…", ["1984", "1979", "1989", "1975"], "1984", 3),
  q("Pac-Man was designed by Namco's…", ["Toru Iwatani", "Tomohiro Nishikado", "Yu Suzuki", "Gunpei Yokoi"], "Toru Iwatani", 3),
  q("Space Invaders was created by…", ["Tomohiro Nishikado", "Toru Iwatani", "Nolan Bushnell", "Eugene Jarvis"], "Tomohiro Nishikado", 3),
  q("One of the first famous video game Easter eggs hid a designer's name in the Atari game…", ["Adventure", "Pitfall!", "Combat", "Yars' Revenge"], "Adventure", 3),
];
