import { q } from "../quiz";
import type { TriviaQ } from "../types";

export const GAMES_BANK: TriviaQ[] = [
  q("Mario's brother is named…", ["Luigi", "Wario", "Waluigi", "Toad"], "Luigi", 1),
  q("The Switch console is made by…", ["Sony", "Nintendo", "Microsoft", "Sega"], "Nintendo", 1),
  q("PlayStation consoles are made by…", ["Sony", "Nintendo", "Microsoft", "Atari"], "Sony", 1),
  q("Xbox consoles are made by…", ["Microsoft", "Sony", "Nintendo", "Sega"], "Microsoft", 1),
  q("Pac-Man is famous for eating…", ["dots", "bricks", "rings", "coins"], "dots", 1),
  q("Pikachu is a…", ["Pokémon", "Mario brother", "Zelda fairy", "Halo marine"], "Pokémon", 1),
  q("The hero of The Legend of Zelda is…", ["Link", "Zelda", "Ganon", "Mario"], "Link", 1),
  q("Master Chief is the armored hero of…", ["Halo", "Metroid", "Doom", "Half-Life"], "Halo", 1),
  q("Minecraft is built out of…", ["blocks", "cards", "dice only", "vinyl records"], "blocks", 1),
  q("Sonic is a blue…", ["hedgehog", "fox", "turtle", "bear"], "hedgehog", 1),
  q("In Tetris, the pieces fall from the…", ["top", "left only", "bottom", "corners only"], "top", 1),
  q("Mario is usually described as a…", ["plumber", "chef", "pilot", "librarian"], "plumber", 1),
  q("The princess Mario often rescues is…", ["Peach", "Zelda", "Samus", "Daisy only in every game"], "Peach", 1),
  q("Bowser is the main villain of…", ["Mario games", "Pokémon", "Halo", "Minecraft"], "Mario games", 1),
  q("An NPC in a game is a…", ["non-player character", "new power crystal", "network ping check", "nintendo power card"], "non-player character", 1),
  q("FPS, as a game genre, means…", ["first-person shooter", "final player score", "fast puzzle set", "four-player sport"], "first-person shooter", 1),
  q("A 1-up gives you…", ["an extra life", "a new console", "a refund", "a harder boss only"], "an extra life", 1),
  q("Steam, the PC game shop, is run by…", ["Valve", "Nintendo", "Sony", "Epic only"], "Valve", 1),
  q("Yoshi is Mario's dinosaur friend and is classically…", ["green", "pink only", "made of metal", "a ghost"], "green", 1),
  q("Princess Zelda's kingdom is…", ["Hyrule", "Mushroom Kingdom", "Midgar", "Lordran"], "Hyrule", 1),
  q("Tetris was designed by…", ["Alexey Pajitnov", "Shigeru Miyamoto", "Hideo Kojima", "Sid Meier"], "Alexey Pajitnov", 2),
  q("Super Mario Bros. first came out for the NES in…", ["1985", "1977", "1991", "1996"], "1985", 2),
  q("Shigeru Miyamoto is the Nintendo designer behind Mario and…", ["The Legend of Zelda", "Halo", "Tetris", "Sonic"], "The Legend of Zelda", 2),
  q("Pac-Man was released in arcades in…", ["1980", "1972", "1989", "1995"], "1980", 2),
  q("The original Pokémon games included how many species?", ["151", "100", "251", "50"], "151", 2),
  q("The Nintendo Game Boy launched in…", ["1989", "1983", "1996", "2001"], "1989", 2),
  q("The first PlayStation console launched in Japan in…", ["1994", "1989", "1998", "2001"], "1994", 2),
  q("The Nintendo 64 launched in…", ["1996", "1991", "2001", "1985"], "1996", 2),
  q("The original Halo was developed by…", ["Bungie", "id Software", "Rare", "Capcom"], "Bungie", 2),
  q("The Last of Us was developed by…", ["Naughty Dog", "Valve", "Nintendo", "Blizzard"], "Naughty Dog", 2),
  q("Portal was developed by…", ["Valve", "Bungie", "FromSoftware", "Sega"], "Valve", 2),
  q("World of Warcraft was developed by…", ["Blizzard", "Riot Games", "Epic Games", "Square"], "Blizzard", 2),
  q("Fortnite was developed by…", ["Epic Games", "Valve", "Nintendo", "Rockstar"], "Epic Games", 2),
  q("The Witcher 3 was developed by…", ["CD Projekt Red", "BioWare", "Bethesda", "Ubisoft"], "CD Projekt Red", 2),
  q("Stardew Valley was made primarily by…", ["Eric Barone", "Toby Fox", "Hideo Kojima", "Will Wright"], "Eric Barone", 2),
  q("Undertale was created by…", ["Toby Fox", "Eric Barone", "Edmund McMillen", "Markus Persson"], "Toby Fox", 2),
  q("The Konami code begins…", ["up, up, down, down", "left, right, left, right", "B, A, start", "down, down, up, up"], "up, up, down, down", 2),
  q("The 1993 game Doom was made by…", ["id Software", "Valve", "Bungie", "Rare"], "id Software", 2),
  q("The hero of Final Fantasy VII is…", ["Cloud Strife", "Sephiroth", "Link", "Geralt"], "Cloud Strife", 2),
  q("Samus Aran is the bounty hunter of…", ["Metroid", "Halo", "Mega Man", "Star Fox"], "Metroid", 2),
  q("Lara Croft is the star of…", ["Tomb Raider", "Uncharted", "Resident Evil", "Assassin's Creed"], "Tomb Raider", 2),
  q("Kratos is the protagonist of…", ["God of War", "Hades", "Diablo", "Asura's Wrath"], "God of War", 2),
  q("Geralt of Rivia is the monster hunter in…", ["The Witcher", "Dragon Age", "Skyrim", "Dark Souls"], "The Witcher", 2),
  q("GoldenEye 007 on the Nintendo 64 was developed by…", ["Rare", "id Software", "DMA Design", "Rockstar"], "Rare", 2),
  q("Sonic the Hedgehog games come from…", ["Sega", "Nintendo", "Atari", "Capcom"], "Sega", 2),
  q("Space Invaders was released in…", ["1978", "1972", "1985", "1962"], "1978", 3),
  q("Pong, the early paddle game, came from Atari in…", ["1972", "1965", "1980", "1985"], "1972", 3),
  q("In the arcade game Donkey Kong, Mario was first called…", ["Jumpman", "Luigi", "Foreman Spike", "Mario Mario"], "Jumpman", 3),
  q("Nintendo began in 1889 as a company that made…", ["playing cards", "radios", "bicycles", "film cameras"], "playing cards", 3),
  q("Pac-Man's four ghosts are Blinky, Pinky, Inky, and…", ["Clyde", "Sue", "Blinky Jr", "Pokey"], "Clyde", 3),
  q("The full classic Konami code is up, up, down, down, left, right, left, right, then…", ["B, A", "A, B", "start", "select, start"], "B, A", 3),
  q("Final Fantasy was created by…", ["Hironobu Sakaguchi", "Hideo Kojima", "Shigeru Miyamoto", "Yu Suzuki"], "Hironobu Sakaguchi", 3),
  q("Metal Gear Solid was directed by…", ["Hideo Kojima", "Hironobu Sakaguchi", "Shinji Mikami", "Suda51"], "Hideo Kojima", 3),
  q("John Carmack was the lead programmer of…", ["Doom", "Minecraft", "Pac-Man", "The Sims"], "Doom", 3),
  q("Minecraft was first created by…", ["Markus Persson", "Jens Bergensten", "Gabe Newell", "Tim Sweeney"], "Markus Persson", 3),
  q("Pokémon was created by…", ["Satoshi Tajiri", "Shigeru Miyamoto", "Ken Sugimori", "Junichi Masuda"], "Satoshi Tajiri", 3),
  q("The first Legend of Zelda was released in…", ["1986", "1983", "1991", "1998"], "1986", 3),
  q("The Legend of Zelda: Ocarina of Time came out in…", ["1998", "1996", "2000", "1991"], "1998", 3),
  q("Standard Tetris uses how many tetromino shapes?", ["7", "5", "6", "8"], "7", 3),
  q("The original Metroid ends by revealing that Samus is…", ["a woman", "a robot", "Link's sister", "a Metroid"], "a woman", 3),
  q("The original Xbox launched in North America in…", ["2001", "1998", "2005", "1994"], "2001", 3),
  q("The Legend of Zelda: Breath of the Wild launched in…", ["2017", "2011", "2015", "2022"], "2017", 3),
  q("Elden Ring was directed by Hidetaka Miyazaki at…", ["FromSoftware", "Capcom", "Square Enix", "Bandai only"], "FromSoftware", 3),
];
