import { q } from "../quiz";
import type { TriviaQ } from "../types";

export const HISTORY_MORE: TriviaQ[] = [
  q("The Code of Hammurabi is from ancient…", ["Rome", "Babylon / Mesopotamia", "China of Qin", "Mali"], "Babylon / Mesopotamia", 2),
  q("Cuneiform writing began in…", ["Egypt", "Mesopotamia", "China", "Mesoamerica"], "Mesopotamia", 2),
  q("Egyptian hieroglyphs were deciphered using the…", ["Dead Sea Scrolls", "Rosetta Stone", "Behistun", "Phaistos disc"], "Rosetta Stone", 2),
  q("The Old Kingdom of Egypt is the age of the great…", ["Alexandrian library", "pyramids at Giza (chiefly)", "Ptolemaic navy", "Fatimid Cairo"], "pyramids at Giza (chiefly)", 2),
  q("Hatshepsut was a…", ["Roman empress", "pharaoh of Egypt", "Chinese empress of Tang", "Mughal princess"], "pharaoh of Egypt", 2),
  q("Akhenaten is associated with…", ["the first pyramid", "a religious reform toward the Aten", "Alexander's conquest", "the Ptolemies"], "a religious reform toward the Aten", 3),
  q("Tutankhamun's tomb was opened in the 1920s by…", ["Schliemann", "Howard Carter", "Layard", "Petrie"], "Howard Carter", 2),
  q("The Epic of Gilgamesh is from…", ["Greece", "Mesopotamia", "India", "Norse myth"], "Mesopotamia", 2),
  q("The Iliad is set around a war at…", ["Thebes in Egypt", "Troy", "Babylon", "Rome"], "Troy", 1),
  q("The city archaeologists identify with Troy is in…", ["Greece's Peloponnese", "Anatolia (Turkey)", "Crete", "Sicily"], "Anatolia (Turkey)", 2),
  q("The Olympic Games of antiquity were held at…", ["Athens", "Olympia", "Sparta", "Delphi"], "Olympia", 2),
  q("Sparta was a…", ["Persian capital", "militarized Greek city-state", "Egyptian nome", "Phoenician colony"], "militarized Greek city-state", 1),
  q("Athens in the 5th century BCE is associated with…", ["the first pharaohs", "democracy (for male citizens) and the arts", "the Mongol khans", "the caliphate"], "democracy (for male citizens) and the arts", 1),
  q("Pericles was a leader of…", ["Sparta", "Athens", "Persia", "Macedon"], "Athens", 2),
  q("Socrates taught in…", ["Rome", "Athens", "Alexandria", "Babylon"], "Athens", 1),
  q("Plato was a student of…", ["Aristotle", "Socrates", "Alexander", "Cicero"], "Socrates", 2),
  q("Aristotle taught…", ["Julius Caesar", "Alexander the Great (among others)", "Charlemagne", "Washington"], "Alexander the Great (among others)", 2),
  q("Alexander the Great was from…", ["Sparta", "Macedon", "Rome", "Persia"], "Macedon", 1),
  q("Alexander's empire reached from Greece to…", ["Sicily", "the Indus / northwest India", "Gaul", "China's Yellow River"], "the Indus / northwest India", 2),
  q("The Hellenistic age follows the conquests of…", ["Augustus", "Alexander", "Charlemagne", "Genghis Khan"], "Alexander", 2),
  q("Rome was traditionally founded in…", ["509 BCE", "753 BCE", "44 BCE", "27 BCE"], "753 BCE", 3),
  q("The Roman Republic traditionally begins in…", ["753 BCE", "509 BCE", "44 BCE", "476 CE"], "509 BCE", 3),
  q("Julius Caesar was assassinated in…", ["49 BCE", "44 BCE", "27 BCE", "14 CE"], "44 BCE", 2),
  q("Augustus was the first…", ["king of Rome", "Roman emperor", "pope", "Holy Roman Emperor"], "Roman emperor", 2),
  q("Pax Romana refers to a long…", ["Roman peace", "Roman civil war", "Gallic siege", "Byzantine schism"], "Roman peace", 2),
  q("Pompeii was buried by…", ["Etna in 79 CE", "Vesuvius in 79 CE", "a flood of the Tiber", "an earthquake in 62"], "Vesuvius in 79 CE", 2),
  q("Constantine is associated with…", ["banning all religion", "tolerating and favoring Christianity in the empire", "founding Rome", "the Twelve Tables"], "tolerating and favoring Christianity in the empire", 2),
  q("Constantinople was founded on the site of…", ["Troy", "Byzantium", "Carthage", "Alexandria"], "Byzantium", 2),
  q("The Western Roman Empire's traditional end is…", ["410", "476 CE", "1453", "800"], "476 CE", 2),
  q("The Byzantine Empire ended in…", ["476", "1453, with the fall of Constantinople", "800", "1204"], "1453, with the fall of Constantinople", 2),
  q("Justinian is remembered for a…", ["the first pyramid", "code of Roman law", "the Magna Carta", "the U.S. Constitution"], "code of Roman law", 2),
  q("The Hagia Sophia in Istanbul was built as a…", ["Greek temple of Athena", "church (later a mosque)", "ziggurat", "synagogue of antiquity"], "church (later a mosque)", 2),
  q("Muhammad was born in…", ["Medina", "Mecca", "Damascus", "Baghdad"], "Mecca", 1),
  q("The Hijra, start of the Islamic calendar, is the move to…", ["Mecca", "Medina", "Jerusalem", "Cairo"], "Medina", 2),
  q("The Abbasid capital was…", ["Mecca", "Baghdad", "Córdoba", "Istanbul in the 8th century"], "Baghdad", 2),
  q("Al-Andalus refers to Muslim…", ["Sicily", "Iberia", "Egypt", "Persia"], "Iberia", 2),
  q("The Battle of Tours (Poitiers, 732) is associated with…", ["Charlemagne", "Charles Martel", "William of Normandy", "Richard I"], "Charles Martel", 3),
  q("Charlemagne was crowned emperor in…", ["732", "800", "1066", "1215"], "800", 2),
  q("The Holy Roman Empire was centered in…", ["Spain", "German-speaking Europe (among other lands)", "England", "Russia"], "German-speaking Europe (among other lands)", 2),
  q("The Domesday Book is a survey of…", ["France under Louis XIV", "England under William I", "Spain under Philip II", "Russia under Peter"], "England under William I", 3),
  q("In 1215, King John sealed the Magna Carta at…", ["Runnymede", "Hastings", "Agincourt", "Windsor Castle"], "Runnymede", 2),
  q("The Hundred Years' War was between…", ["Spain and Portugal", "England and France", "Ottomans and Hungary", "Genoa and Venice"], "England and France", 2),
  q("Joan of Arc fought in…", ["the Hundred Years' War", "the Reconquista", "the First Crusade", "the Wars of the Roses"], "the Hundred Years' War", 2),
  q("The Wars of the Roses were English civil wars of the…", ["11th century", "15th century", "17th century", "19th century"], "15th century", 3),
  q("Henry VIII broke with Rome over…", ["the Spanish Armada", "his marriage and the English church", "the Glorious Revolution", "American independence"], "his marriage and the English church", 2),
  q("Elizabeth I's reign saw the defeat of the…", ["French at Agincourt", "Spanish Armada (1588)", "Dutch at Trafalgar", "Ottomans at Lepanto"], "Spanish Armada (1588)", 2),
  q("The printing press in Europe is dated to the…", ["1350s", "1450s", "1550s", "1650s"], "1450s", 2),
  q("Martin Luther's 95 Theses are dated…", ["1415", "1517", "1618", "1648"], "1517", 2),
  q("The Thirty Years' War ended in…", ["1517", "1588", "1648 (Peace of Westphalia)", "1688"], "1648 (Peace of Westphalia)", 3),
  q("The Peace of Westphalia is a landmark of…", ["the Crusades", "state sovereignty in Europe", "decolonization of Africa", "the EU"], "state sovereignty in Europe", 3),
  q("The Scientific Revolution is associated with…", ["Aquinas", "Copernicus, Galileo, Newton (among others)", "Homer", "Hammurabi"], "Copernicus, Galileo, Newton (among others)", 1),
  q("The Enlightenment is associated with…", ["Gothic cathedrals", "reason, rights, and criticism of old authority", "feudal dues", "icon painting"], "reason, rights, and criticism of old authority", 1),
  q("John Locke argued for…", ["the divine right of kings", "natural rights and government by consent", "mercantilism", "absolute serfdom"], "natural rights and government by consent", 2),
  q("Adam Smith's Wealth of Nations appeared in…", ["1688", "1776", "1789", "1848"], "1776", 3),
  q("The American Revolution's fighting is often dated 1775 to…", ["1776", "1783", "1789", "1812"], "1783", 2),
  q("Yorktown (1781) was a decisive…", ["Franco-American victory", "British victory", "Spanish victory", "Hessian victory"], "Franco-American victory", 2),
  q("The French Revolution's Tennis Court Oath is…", ["1776", "1789", "1793", "1815"], "1789", 2),
  q("The Reign of Terror is associated with…", ["Robespierre", "Napoleon", "Louis XIV", "de Gaulle"], "Robespierre", 2),
  q("Napoleon crowned himself (in effect) in…", ["1789", "1799", "1804", "1815"], "1804", 2),
  q("The Battle of Trafalgar (1805) was a victory of…", ["Napoleon", "Nelson / Britain", "the U.S.", "Russia"], "Nelson / Britain", 2),
  q("The Battle of Waterloo (1815) ended…", ["the American Revolution", "Napoleon's rule", "the Crimean War", "WWI"], "Napoleon's rule", 1),
  q("The Congress of Vienna (1814–15) tried to…", ["restore Europe's balance of power", "found the United Nations", "end the Second World War", "partition Africa among powers"], "restore Europe's balance of power", 2),
  q("Simón Bolívar is associated with independence in…", ["Brazil", "Spanish South America", "Mexico", "Haiti"], "Spanish South America", 2),
  q("Haitian independence (1804) followed a revolution of…", ["creole planters against Spain", "enslaved and free people of color against France", "British occupation", "U.S. invasion"], "enslaved and free people of color against France", 2),
  q("The Opium Wars were between Britain (and later others) and…", ["Japan", "Qing China", "Siam", "Korea"], "Qing China", 2),
  q("The Meiji Restoration transformed…", ["China", "Japan", "Korea", "Vietnam"], "Japan", 2),
  q("The Indian Rebellion of 1857 is also called the…", ["Boxer Rebellion", "Sepoy Mutiny / First War of Independence", "Taiping Rebellion", "Mau Mau"], "Sepoy Mutiny / First War of Independence", 3),
  q("The Taiping Rebellion was in…", ["India", "China", "Japan", "Vietnam"], "China", 3),
  q("The scramble for Africa is dated chiefly to the…", ["16th century", "late 19th century", "21st century", "11th century"], "late 19th century", 2),
  q("The Berlin Conference (1884–85) concerned…", ["the UN", "European claims in Africa", "the League of Nations", "NATO"], "European claims in Africa", 2),
  q("World War I's spark is often given as the assassination at…", ["Berlin", "Sarajevo", "Vienna", "Paris"], "Sarajevo", 2),
  q("The assassin of Archduke Franz Ferdinand was…", ["Black Hand", "Gavrilo Princip", "Leon Czolgosz", "Raoul Villain"], "Gavrilo Princip", 3),
  q("The Treaty of Versailles is dated…", ["1918", "1919", "1920", "1923"], "1919", 2),
  q("The League of Nations was founded after…", ["WWII", "WWI", "the Napoleonic wars", "the Cold War"], "WWI", 1),
  q("The Russian Revolutions of 1917 ended…", ["the Soviet Union", "the Romanov monarchy (and then brought the Bolsheviks)", "the Mongol yoke in 1917", "Peter the Great"], "the Romanov monarchy (and then brought the Bolsheviks)", 2),
  q("Lenin led the…", ["Mensheviks", "Bolsheviks", "Kadets", "Whites"], "Bolsheviks", 2),
  q("Stalin's rule of the USSR is associated with…", ["the New Economic Policy", "collectivization, famine, and the Terror", "glasnost", "the space race of the 1960s"], "collectivization, famine, and the Terror", 2),
  q("The Holodomor was a famine in…", ["Ireland of the 1840s", "Ukraine (1932–33)", "China of 1959", "Bengal of 1943"], "Ukraine (1932–33)", 3),
  q("The Long March was a retreat of Chinese…", ["Nationalists", "Communists", "Japanese occupiers", "Mongols"], "Communists", 2),
  q("Mao Zedong proclaimed the People's Republic in…", ["1911", "1927", "1949", "1966"], "1949", 2),
  q("The 1911 Revolution in China ended the…", ["Ming", "Qing dynasty", "Yuan", "Han"], "Qing dynasty", 2),
  q("Pearl Harbor was attacked on…", ["June 6, 1944", "December 7, 1941", "May 8, 1945", "August 6, 1945"], "December 7, 1941", 1),
  q("D-Day was…", ["December 7, 1941", "June 6, 1944", "May 8, 1945", "September 1, 1939"], "June 6, 1944", 1),
  q("VE Day in Europe was…", ["June 1944", "May 1945", "August 1945", "December 1941"], "May 1945", 2),
  q("VJ Day / Japan's surrender was…", ["May 1945", "August 1945", "December 1941", "June 1944"], "August 1945", 2),
  q("The atomic bombings of 1945 were of…", ["Tokyo and Kyoto", "Hiroshima and Nagasaki", "Osaka and Kobe", "tests in Nevada"], "Hiroshima and Nagasaki", 1),
  q("The Holocaust was the genocide of…", ["Jews by Nazi Germany", "POWs in one battle", "victims of a famine", "civilians in Spain's war"], "Jews by Nazi Germany", 1),
  q("Auschwitz was a…", ["Soviet gulag in Siberia", "Nazi camp complex in occupied Poland", "Japanese camp in Manchuria", "U.S. internment camp"], "Nazi camp complex in occupied Poland", 1),
  q("The Nuremberg Trials prosecuted…", ["Japanese leaders", "Nazi leaders", "Italian leaders", "collaborators in France"], "Nazi leaders", 2),
  q("The Marshall Plan rebuilt…", ["the USSR", "Western Europe after WWII", "Japan", "China"], "Western Europe after WWII", 2),
  q("The Warsaw Pact was founded in…", ["1949", "1955", "1961", "1968"], "1955", 3),
  q("The Korean War is dated…", ["1945–1948", "1950–1953", "1959–1975", "1964–1973"], "1950–1953", 2),
  q("The Vietnam War's U.S. combat phase is often closed in…", ["1950", "1964", "1973/1975", "1989"], "1973/1975", 2),
  q("The Berlin Wall went up in…", ["1949", "1953", "1961", "1989"], "1961", 2),
  q("The Civil Rights Act in the U.S. is dated…", ["1954", "1964", "1965", "1968"], "1964", 2),
  q("The Voting Rights Act in the U.S. is dated…", ["1964", "1965", "1968", "1954"], "1965", 2),
  q("Brown v. Board of Education is dated…", ["1896", "1954", "1964", "1965"], "1954", 2),
  q("Rosa Parks's bus protest was in…", ["Selma, 1965", "Montgomery, 1955", "Birmingham", "Washington, 1963"], "Montgomery, 1955", 2),
  q("The March on Washington (1963) is remembered for…", ["the bus boycott", "King's 'I Have a Dream'", "the Selma bridge", "Malcolm X's speech"], "King's 'I Have a Dream'", 1),
  q("Stonewall (1969) is a landmark of…", ["labor in Chicago 1886", "LGBTQ+ rights protest in New York", "antiwar in Kent State", "farmworkers in Delano"], "LGBTQ+ rights protest in New York", 2),
  q("Sputnik was launched in…", ["1945", "1957", "1961", "1969"], "1957", 2),
  q("Yuri Gagarin orbited Earth in…", ["1957", "1961", "1969", "1975"], "1961", 2),
  q("The Iranian Revolution was in…", ["1953", "1979", "1989", "2001"], "1979", 2),
  q("The Soviet invasion of Afghanistan began in…", ["1968", "1979", "1989", "2001"], "1979", 2),
  q("Solidarity in Poland is associated with…", ["Lech Wałęsa", "Václav Havel", "Imre Nagy", "Josip Broz Tito"], "Lech Wałęsa", 3),
  q("The Tiananmen Square protests were in…", ["1976", "1989", "1991", "1997"], "1989", 2),
  q("German reunification is dated…", ["1989", "1990", "1991", "1992"], "1990", 2),
  q("The Maastricht Treaty is a founding text of the…", ["UN", "European Union", "NATO", "WTO"], "European Union", 2),
  q("Apartheid in South Africa ended in the…", ["1960s", "1970s", "1990s (first majority elections 1994)", "2000s"], "1990s (first majority elections 1994)", 2),
  q("The Dayton Accords concerned peace in…", ["Kosovo", "Bosnia", "Rwanda", "Northern Ireland"], "Bosnia", 3),
  q("September 11 attacks were in…", ["1998", "2001", "2003", "2011"], "2001", 1),
  q("The euro notes and coins entered circulation in…", ["1992", "1999", "2002", "2009"], "2002", 3),
  q("The Arab Spring is dated chiefly…", ["2001", "2003", "2010–2012", "2020"], "2010–2012", 2),
  q("COVID-19 was declared a pandemic in…", ["2012", "2016", "2019", "2020"], "2020", 1),
  q("The U.S. Civil War began with firing on…", ["Fort McHenry", "Fort Sumter", "the Alamo", "Harpers Ferry"], "Fort Sumter", 2),
  q("Gettysburg was fought in…", ["1861", "1862", "1863", "1865"], "1863", 2),
  q("The Emancipation Proclamation took effect…", ["1861", "January 1, 1863", "1865", "1870"], "January 1, 1863", 2),
  q("Appomattox Court House is where…", ["Lincoln was shot", "Lee surrendered to Grant", "the Emancipation was signed", "Sherman began his march"], "Lee surrendered to Grant", 2),
  q("Reconstruction in the U.S. followed the…", ["Revolution", "Civil War", "War of 1812", "Spanish-American War"], "Civil War", 1),
  q("The 13th, 14th, and 15th Amendments are the…", ["Bill of Rights", "Reconstruction Amendments", "Progressive Amendments", "New Deal amendments"], "Reconstruction Amendments", 2),
  q("Plessy v. Ferguson (1896) upheld…", ["racial segregation", "school integration", "the end of slavery", "women's suffrage"], "racial segregation", 2),
  q("The 19th Amendment (U.S.) concerned…", ["Prohibition", "women's suffrage", "income tax", "two-term limit"], "women's suffrage", 1),
  q("The New Deal was the program of…", ["Hoover", "Franklin D. Roosevelt", "Truman", "Eisenhower"], "Franklin D. Roosevelt", 1),
  q("Pearl Harbor brought the U.S. into…", ["World War I", "World War II", "Korea", "Vietnam"], "World War II", 1),
  q("The G.I. Bill after WWII aided…", ["Japanese Americans in camps", "veterans (education, housing, etc.)", "railroads", "banks"], "veterans (education, housing, etc.)", 2),
  q("McCarthyism is associated with…", ["the New Deal", "anti-communist hunts in the U.S.", "civil rights sit-ins", "isolationism of 1940"], "anti-communist hunts in the U.S.", 2),
  q("The Voting Rights march in Selma is associated with…", ["1955 Montgomery", "1965 and the Edmund Pettus Bridge", "1963 Birmingham church", "1968 Memphis"], "1965 and the Edmund Pettus Bridge", 2),
  q("Watergate led to the resignation of…", ["Johnson", "Richard Nixon", "Ford", "Carter"], "Richard Nixon", 1),
  q("The Iran hostage crisis began in…", ["1968", "1973", "1979", "1986"], "1979", 2),
  q("The first Gulf War to expel Iraq from Kuwait was in…", ["1980", "1991", "2003", "2011"], "1991", 2),
  q("The 2003 Iraq War toppled…", ["Nasser", "Saddam Hussein", "the Shah", "Gaddafi"], "Saddam Hussein", 2),
  q("Nelson Mandela was released from prison in…", ["1976", "1985", "1990", "1999"], "1990", 2),
  q("The first human on the Moon was…", ["Yuri Gagarin", "Neil Armstrong", "John Glenn", "Buzz Aldrin"], "Neil Armstrong", 1),
  q("The second human on the Moon (same landing) was…", ["Michael Collins", "Buzz Aldrin", "Alan Shepard", "Jim Lovell"], "Buzz Aldrin", 2),
  q("Michael Collins on Apollo 11…", ["walked first", "orbited in the command module", "stayed on Earth", "piloted a Shuttle"], "orbited in the command module", 2),
  q("The Library of Alexandria is a wonder of…", ["Rome of the Republic", "Hellenistic Egypt", "Athens of Pericles", "Baghdad"], "Hellenistic Egypt", 2),
  q("The Colossus of Rhodes was a…", ["lighthouse of Alexandria", "statue at a harbor", "tomb of Mausolus", "hanging garden"], "statue at a harbor", 2),
  q("The Terracotta Army was buried with…", ["Kublai Khan", "Qin Shi Huang", "Mao", "Yongle"], "Qin Shi Huang", 2),
  q("Angkor Wat was built as a…", ["Japanese castle", "Khmer temple (later Buddhist as well)", "Mughal tomb", "Inca palace"], "Khmer temple (later Buddhist as well)", 2),
  q("Machu Picchu is associated with the…", ["Aztec", "Maya", "Inca", "Olmec"], "Inca", 1),
  q("Tenochtitlan was the capital of the…", ["Inca", "Maya", "Aztec", "Moche"], "Aztec", 1),
  q("Chichen Itza is a city of the…", ["Aztec", "Maya", "Inca", "Mississippian"], "Maya", 1),
  q("Cahokia was a city of the…", ["Ancestral Pueblo", "Mississippian culture", "Iroquois", "Norse"], "Mississippian culture", 3),
  q("The Iroquois (Haudenosaunee) Confederacy is in…", ["the Pacific Northwest", "the Northeast woodlands", "the Andes", "the Plains"], "the Northeast woodlands", 2),
  q("The Silk Road linked…", ["Peru and Mexico", "East Asia and the Mediterranean world (among other routes)", "Australia and New Zealand", "the Great Lakes"], "East Asia and the Mediterranean world (among other routes)", 1),
  q("Zheng He led treasure voyages for…", ["the Ottomans", "Ming China", "Portugal", "Spain"], "Ming China", 3),
  q("Ibn Battuta was a…", ["Ming admiral", "traveler of the 14th-century Islamic world", "Portuguese captain of 1498", "Viking of 1000"], "traveler of the 14th-century Islamic world", 3),
  q("Marco Polo's Travels describe…", ["a Portuguese in Japan", "a Venetian in Yuan China (as the book has it)", "a Spaniard in Peru", "a Dutchman in New York"], "a Venetian in Yuan China (as the book has it)", 2),
  q("Vasco da Gama reached India by sea in…", ["1488", "1492", "1498", "1521"], "1498", 3),
  q("Magellan's expedition is the first to…", ["reach America", "circumnavigate the globe (he died en route)", "reach India by the Cape", "map Australia"], "circumnavigate the globe (he died en route)", 2),
  q("Cortés led the Spanish war against the…", ["Inca", "Aztec", "Maya", "Mapuche"], "Aztec", 2),
  q("Pizarro led the Spanish war against the…", ["Aztec", "Inca", "Maya", "Taíno"], "Inca", 2),
  q("The Middle Passage was the…", ["forced crossing of enslaved Africans", "route of the Oregon Trail", "eastern leg of the Silk Road", "Arctic Northwest Passage"], "forced crossing of enslaved Africans", 1),
  q("Britain abolished its slave trade in…", ["1807", "1776", "1865", "1888"], "1807", 3),
  q("Brazil abolished slavery in…", ["1807", "1833", "1865", "1888"], "1888", 3),
  q("The Haitian Revolution is a landmark of…", ["creole tax protest", "the destruction of slavery by the enslaved", "a Napoleonic parade", "U.S. occupation"], "the destruction of slavery by the enslaved", 2),
];

