import { q } from "../quiz";
import type { TriviaQ } from "../types";

export const HISTORY_MORE: TriviaQ[] = [
  q("The Code of Hammurabi is from ancient…", ["Rome", "Babylon / Mesopotamia", "China of Qin", "Mali"], "Babylon / Mesopotamia", 2),
  q("Cuneiform writing began in…", ["Egypt only as the first", "Mesopotamia", "China only as the first", "Mesoamerica only as the first"], "Mesopotamia", 2),
  q("Egyptian hieroglyphs were deciphered using the…", ["Dead Sea Scrolls", "Rosetta Stone", "Behistun only as Egyptian", "Phaistos disc"], "Rosetta Stone", 2),
  q("The Old Kingdom of Egypt is the age of the great…", ["Alexandrian library only", "pyramids at Giza (chiefly)", "Ptolemaic navy only", "Fatimid Cairo only"], "pyramids at Giza (chiefly)", 2),
  q("Hatshepsut was a…", ["Roman empress", "pharaoh of Egypt", "Chinese empress of Tang only", "Mughal princess"], "pharaoh of Egypt", 2),
  q("Akhenaten is associated with…", ["the first pyramid", "a religious reform toward the Aten", "Alexander's conquest", "the Ptolemies only"], "a religious reform toward the Aten", 3),
  q("Tutankhamun's tomb was opened in the 1920s by…", ["Schliemann", "Howard Carter", "Layard", "Petrie as the only name"], "Howard Carter", 2),
  q("The Epic of Gilgamesh is from…", ["Greece", "Mesopotamia", "India as the Mahabharata", "Norse myth"], "Mesopotamia", 2),
  q("The Iliad is set around a war at…", ["Thebes in Egypt", "Troy", "Babylon", "Rome"], "Troy", 1),
  q("The city archaeologists identify with Troy is in…", ["Greece's Peloponnese only", "Anatolia (Turkey)", "Crete only", "Sicily"], "Anatolia (Turkey)", 2),
  q("The Olympic Games of antiquity were held at…", ["Athens only", "Olympia", "Sparta", "Delphi as the games' only site"], "Olympia", 2),
  q("Sparta was a…", ["Persian capital", "militarized Greek city-state", "Egyptian nome", "Phoenician colony only"], "militarized Greek city-state", 1),
  q("Athens in the 5th century BCE is associated with…", ["the first pharaohs", "democracy (for male citizens) and the arts", "the Mongol khans", "the caliphate"], "democracy (for male citizens) and the arts", 1),
  q("Pericles was a leader of…", ["Sparta", "Athens", "Persia", "Macedon"], "Athens", 2),
  q("Socrates taught in…", ["Rome", "Athens", "Alexandria as his home", "Babylon"], "Athens", 1),
  q("Plato was a student of…", ["Aristotle as his teacher", "Socrates", "Alexander", "Cicero"], "Socrates", 2),
  q("Aristotle taught…", ["Julius Caesar", "Alexander the Great (among others)", "Charlemagne as a boy", "Washington"], "Alexander the Great (among others)", 2),
  q("Alexander the Great was from…", ["Sparta", "Macedon", "Rome", "Persia"], "Macedon", 1),
  q("Alexander's empire reached from Greece to…", ["only Sicily", "the Indus / northwest India", "only Gaul", "China's Yellow River"], "the Indus / northwest India", 2),
  q("The Hellenistic age follows the conquests of…", ["Augustus", "Alexander", "Charlemagne", "Genghis Khan"], "Alexander", 2),
  q("Rome was traditionally founded in…", ["509 BCE as founding of the city", "753 BCE", "44 BCE", "27 BCE"], "753 BCE", 3),
  q("The Roman Republic traditionally begins in…", ["753 BCE", "509 BCE", "44 BCE", "476 CE"], "509 BCE", 3),
  q("Julius Caesar was assassinated in…", ["49 BCE", "44 BCE", "27 BCE", "14 CE"], "44 BCE", 2),
  q("Augustus was the first…", ["king of Rome in the stories of Romulus as emperor", "Roman emperor", "pope", "Holy Roman Emperor"], "Roman emperor", 2),
  q("Pax Romana refers to a long…", ["civil war of Marius", "Roman peace / order in the early empire", "sack of Rome by Gauls only", "Byzantine iconoclasm"], "Roman peace / order in the early empire", 2),
  q("Pompeii was buried by…", ["Etna in 79 CE", "Vesuvius in 79 CE", "a flood of the Tiber as the only story", "an earthquake in 62 as the burial"], "Vesuvius in 79 CE", 2),
  q("Constantine is associated with…", ["banning all religion", "tolerating and favoring Christianity in the empire", "founding Rome", "the Twelve Tables"], "tolerating and favoring Christianity in the empire", 2),
  q("Constantinople was founded on the site of…", ["Troy", "Byzantium", "Carthage", "Alexandria"], "Byzantium", 2),
  q("The Western Roman Empire's traditional end is…", ["410 as the only date", "476 CE", "1453", "800"], "476 CE", 2),
  q("The Byzantine Empire ended in…", ["476", "1453, with the fall of Constantinople", "800", "1204 as the final end"], "1453, with the fall of Constantinople", 2),
  q("Justinian is remembered for a…", ["the first pyramid", "code of Roman law", "the Magna Carta", "the U.S. Constitution"], "code of Roman law", 2),
  q("The Hagia Sophia in Istanbul was built as a…", ["Greek temple of Athena", "church (later a mosque)", "ziggurat", "synagogue of antiquity"], "church (later a mosque)", 2),
  q("Muhammad was born in…", ["Medina as birth", "Mecca", "Damascus", "Baghdad"], "Mecca", 1),
  q("The Hijra, start of the Islamic calendar, is the move to…", ["Mecca as a leaving of Medina", "Medina", "Jerusalem", "Cairo"], "Medina", 2),
  q("The Abbasid capital was…", ["Mecca as the political capital", "Baghdad", "Córdoba as the only capital", "Istanbul in the 8th century"], "Baghdad", 2),
  q("Al-Andalus refers to Muslim…", ["Sicily only", "Iberia", "Egypt only", "Persia"], "Iberia", 2),
  q("The Battle of Tours (Poitiers, 732) is associated with…", ["Charlemagne as the only name", "Charles Martel", "William of Normandy", "Richard I"], "Charles Martel", 3),
  q("Charlemagne was crowned emperor in…", ["732", "800", "1066", "1215"], "800", 2),
  q("The Holy Roman Empire was centered in…", ["only Spain", "German-speaking Europe (among other lands)", "only England", "only Russia"], "German-speaking Europe (among other lands)", 2),
  q("1066 is the year of the…", ["Magna Carta", "Norman Conquest of England", "Fall of Constantinople", "Spanish Armada"], "Norman Conquest of England", 1),
  q("The Domesday Book is a survey of…", ["France under Louis XIV", "England under William I", "Spain under Philip II", "Russia under Peter"], "England under William I", 3),
  q("The Magna Carta was sealed at…", ["Hastings, 1066", "Runnymede, 1215", "Agincourt, 1415", "Runnymede, 1776"], "Runnymede, 1215", 2),
  q("The Black Death peaked in Europe in the…", ["1240s", "1340s", "1540s", "1640s"], "1340s", 2),
  q("The Hundred Years' War was between…", ["Spain and Portugal", "England and France", "Ottomans and Hungary only", "Genoa and Venice only"], "England and France", 2),
  q("Joan of Arc fought in…", ["the Reconquista of Spain as a French captain", "the French cause in the Hundred Years' War", "the Crusade of 1095 as a leader", "the Armada"], "the French cause in the Hundred Years' War", 2),
  q("The Wars of the Roses were English civil wars of the…", ["11th century", "15th century", "17th century only as the Civil War of Cromwell", "19th century"], "15th century", 3),
  q("Henry VIII broke with Rome over…", ["the Spanish Armada", "his marriage and the English church", "the Glorious Revolution", "American independence"], "his marriage and the English church", 2),
  q("Elizabeth I's reign saw the defeat of the…", ["French at Agincourt", "Spanish Armada (1588)", "Dutch at Trafalgar as her battle", "Ottomans at Lepanto as an English fleet"], "Spanish Armada (1588)", 2),
  q("The printing press in Europe is dated to the…", ["1350s", "1450s", "1550s as the first press", "1650s"], "1450s", 2),
  q("Martin Luther's 95 Theses are dated…", ["1415", "1517", "1618", "1648"], "1517", 2),
  q("The Thirty Years' War ended in…", ["1517", "1588", "1648 (Peace of Westphalia)", "1688"], "1648 (Peace of Westphalia)", 3),
  q("The Peace of Westphalia is a landmark of…", ["the Crusades", "state sovereignty in Europe", "decolonization of Africa", "the EU"], "state sovereignty in Europe", 3),
  q("The Scientific Revolution is associated with…", ["only Aquinas", "Copernicus, Galileo, Newton (among others)", "only Homer", "only Hammurabi"], "Copernicus, Galileo, Newton (among others)", 1),
  q("The Enlightenment is associated with…", ["only Gothic cathedrals", "reason, rights, and criticism of old authority", "only feudal dues", "only icon painting"], "reason, rights, and criticism of old authority", 1),
  q("John Locke argued for…", ["the divine right of kings as his main thesis", "natural rights and government by consent", "only mercantilism", "absolute serfdom"], "natural rights and government by consent", 2),
  q("Adam Smith's Wealth of Nations appeared in…", ["1688", "1776", "1789 as his only year", "1848"], "1776", 3),
  q("The American Revolution's fighting is often dated 1775 to…", ["1776 only", "1783", "1789", "1812 as the end of the Revolution"], "1783", 2),
  q("Yorktown (1781) was a decisive…", ["British victory", "Franco-American victory over the British", "Spanish loss of Mexico", "French loss of Quebec as 1781"], "Franco-American victory over the British", 2),
  q("The French Revolution's Tennis Court Oath is…", ["1776", "1789", "1793 only", "1815"], "1789", 2),
  q("The Reign of Terror is associated with…", ["Napoleon as first consul only", "Robespierre / the Jacobins", "Louis XIV", "de Gaulle"], "Robespierre / the Jacobins", 2),
  q("Napoleon crowned himself (in effect) in…", ["1789", "1799 as emperor", "1804", "1815"], "1804", 2),
  q("The Battle of Trafalgar (1805) was a victory of…", ["Napoleon", "Nelson / Britain", "the U.S.", "Russia"], "Nelson / Britain", 2),
  q("The Battle of Waterloo (1815) ended…", ["the American Revolution", "Napoleon's rule", "the Crimean War", "WWI"], "Napoleon's rule", 1),
  q("The Congress of Vienna (1814–15) tried to…", ["found the UN", "restore a balance of power after Napoleon", "end WWII", "partition Africa as its only act"], "restore a balance of power after Napoleon", 2),
  q("Simón Bolívar is associated with independence in…", ["Brazil only as a Portuguese prince", "Spanish South America", "Mexico only as Hidalgo's only rival", "Haiti only as Toussaint"], "Spanish South America", 2),
  q("Haitian independence (1804) followed a revolution of…", ["only creole planters against Spain", "enslaved and free people of color against France", "only British occupation", "only U.S. invasion"], "enslaved and free people of color against France", 2),
  q("The Opium Wars were between Britain (and later others) and…", ["Japan", "Qing China", "Siam", "Korea"], "Qing China", 2),
  q("The Meiji Restoration transformed…", ["China as the name of 1868", "Japan", "Korea as 1868", "Vietnam"], "Japan", 2),
  q("The Indian Rebellion of 1857 is also called the…", ["Boxer Rebellion", "Sepoy Mutiny / First War of Independence", "Taiping Rebellion", "Mau Mau"], "Sepoy Mutiny / First War of Independence", 3),
  q("The Taiping Rebellion was in…", ["India", "China", "Japan", "Vietnam"], "China", 3),
  q("The scramble for Africa is dated chiefly to the…", ["16th century only", "late 19th century", "21st century", "11th century"], "late 19th century", 2),
  q("The Berlin Conference (1884–85) concerned…", ["the UN", "European claims in Africa", "the League of Nations", "NATO"], "European claims in Africa", 2),
  q("World War I's spark is often given as the assassination at…", ["Berlin", "Sarajevo", "Vienna as the shot", "Paris"], "Sarajevo", 2),
  q("The assassin of Archduke Franz Ferdinand was…", ["Black Hand as a person's name", "Gavrilo Princip", "Princip as a German colonel", "a French anarchist of 1914 fame"], "Gavrilo Princip", 3),
  q("The U.S. entered World War I in…", ["1914", "1915", "1917", "1918 as the declaration"], "1917", 2),
  q("The Treaty of Versailles is dated…", ["1918 as the treaty", "1919", "1920 as the only year", "1923"], "1919", 2),
  q("The League of Nations was founded after…", ["WWII as the League", "WWI", "the Napoleonic wars", "the Cold War"], "WWI", 1),
  q("The Russian Revolutions of 1917 ended…", ["the Soviet Union", "the Romanov monarchy (and then brought the Bolsheviks)", "the Mongol yoke in 1917", "Peter the Great"], "the Romanov monarchy (and then brought the Bolsheviks)", 2),
  q("Lenin led the…", ["Mensheviks as his party name", "Bolsheviks", "Kadets", "Whites as his color"], "Bolsheviks", 2),
  q("Stalin's rule of the USSR is associated with…", ["only the New Economic Policy as his whole story", "collectivization, famine, and the Terror", "only glasnost", "only the space race of the 1960s as his years"], "collectivization, famine, and the Terror", 2),
  q("The Holodomor was a famine in…", ["Ireland of the 1840s", "Ukraine (1932–33)", "China of 1959", "Bengal of 1943"], "Ukraine (1932–33)", 3),
  q("The Long March was a retreat of Chinese…", ["Nationalists as the Long Marchers", "Communists", "Japanese occupiers", "Mongols"], "Communists", 2),
  q("Mao Zedong proclaimed the People's Republic in…", ["1911", "1927", "1949", "1966 as founding"], "1949", 2),
  q("The 1911 Revolution in China ended the…", ["Ming", "Qing dynasty", "Yuan", "Han"], "Qing dynasty", 2),
  q("Pearl Harbor was attacked on…", ["June 6, 1944", "December 7, 1941", "May 8, 1945", "August 6, 1945"], "December 7, 1941", 1),
  q("D-Day was…", ["December 7, 1941", "June 6, 1944", "May 8, 1945", "September 1, 1939"], "June 6, 1944", 1),
  q("VE Day in Europe was…", ["June 1944", "May 1945", "August 1945 as Europe", "December 1941"], "May 1945", 2),
  q("VJ Day / Japan's surrender was…", ["May 1945", "August 1945", "December 1941", "June 1944"], "August 1945", 2),
  q("The atomic bombings of 1945 were of…", ["Tokyo and Kyoto", "Hiroshima and Nagasaki", "Osaka and Kobe", "only tests in Nevada"], "Hiroshima and Nagasaki", 1),
  q("The Holocaust was the genocide of…", ["only POWs of one battle", "Jews (and other groups) by Nazi Germany", "only a famine", "only a civil war of Spain"], "Jews (and other groups) by Nazi Germany", 1),
  q("Auschwitz was a…", ["Soviet gulag in Siberia", "Nazi camp complex in occupied Poland", "Japanese camp in Manchuria only", "U.S. internment camp"], "Nazi camp complex in occupied Poland", 1),
  q("The Nuremberg Trials prosecuted…", ["only Japanese leaders", "Nazi leaders", "only Italian leaders", "only collaborators in France"], "Nazi leaders", 2),
  q("The Marshall Plan rebuilt…", ["the USSR as the main recipient", "Western Europe after WWII", "only Japan", "only China"], "Western Europe after WWII", 2),
  q("NATO was founded in…", ["1919", "1945 as NATO", "1949", "1955 as NATO's founding"], "1949", 2),
  q("The Warsaw Pact was founded in…", ["1949", "1955", "1961", "1968 as founding"], "1955", 3),
  q("The Korean War is dated…", ["1945–1948", "1950–1953", "1959–1975", "1964–1973"], "1950–1953", 2),
  q("The Vietnam War's U.S. combat phase is often closed in…", ["1950", "1964 only as the end", "1973/1975", "1989"], "1973/1975", 2),
  q("The Cuban Missile Crisis was in…", ["1959 as the missiles", "1961 as the only year", "1962", "1968"], "1962", 2),
  q("The Berlin Wall went up in…", ["1949", "1953", "1961", "1989 as building"], "1961", 2),
  q("The Civil Rights Act in the U.S. is dated…", ["1954 as the Act", "1964", "1965 as the Act of this name", "1968 as this Act's only year"], "1964", 2),
  q("The Voting Rights Act in the U.S. is dated…", ["1964 as this Act's name", "1965", "1968", "1954"], "1965", 2),
  q("Brown v. Board of Education is dated…", ["1896", "1954", "1964", "1965"], "1954", 2),
  q("Rosa Parks's bus protest was in…", ["Selma, 1965 as the bus", "Montgomery, 1955", "Birmingham as the only bus", "Washington in 1963 as a bus"], "Montgomery, 1955", 2),
  q("The March on Washington (1963) is remembered for…", ["the bus boycott as that day's speech", "King's 'I Have a Dream'", "the Selma bridge as that day's speech", "Malcolm X's only speech that day as the March's keynote"], "King's 'I Have a Dream'", 1),
  q("Stonewall (1969) is a landmark of…", ["labor in Chicago 1886", "LGBTQ+ rights protest in New York", "antiwar in Kent State", "farmworkers in Delano"], "LGBTQ+ rights protest in New York", 2),
  q("The moon landing of Apollo 11 was…", ["1961", "1965", "1969", "1975"], "1969", 1),
  q("Sputnik was launched in…", ["1945", "1957", "1961", "1969"], "1957", 2),
  q("Yuri Gagarin orbited Earth in…", ["1957", "1961", "1969", "1975"], "1961", 2),
  q("The Iranian Revolution was in…", ["1953", "1979", "1989", "2001"], "1979", 2),
  q("The Soviet invasion of Afghanistan began in…", ["1968", "1979", "1989", "2001 as Soviet"], "1979", 2),
  q("Solidarity in Poland is associated with…", ["only the Prague Spring", "Lech Wałęsa and the Gdansk strikes", "only 1956 Hungary", "only Tito"], "Lech Wałęsa and the Gdansk strikes", 3),
  q("The Tiananmen Square protests were in…", ["1976", "1989", "1991", "1997"], "1989", 2),
  q("German reunification is dated…", ["1989 as the treaty year only", "1990", "1991 as Germany", "1992"], "1990", 2),
  q("The Soviet Union dissolved in…", ["1989", "1990", "1991", "1993"], "1991", 1),
  q("The Maastricht Treaty is a founding text of the…", ["UN", "European Union", "NATO", "WTO as the only name"], "European Union", 2),
  q("Apartheid in South Africa ended in the…", ["1960s as the end", "1970s as the end", "1990s (first majority elections 1994)", "2000s as the first election"], "1990s (first majority elections 1994)", 2),
  q("The Rwandan genocide was in…", ["1975", "1984", "1994", "2004"], "1994", 2),
  q("The Dayton Accords concerned peace in…", ["Kosovo only as Dayton", "Bosnia", "Rwanda", "Northern Ireland as Dayton"], "Bosnia", 3),
  q("The Good Friday Agreement is dated…", ["1972", "1985", "1998", "2007"], "1998", 3),
  q("September 11 attacks were in…", ["1998", "2001", "2003", "2011"], "2001", 1),
  q("The euro notes and coins entered circulation in…", ["1992", "1999 as notes in wallets", "2002", "2009"], "2002", 3),
  q("The Arab Spring is dated chiefly…", ["2001", "2003", "2010–2012", "2020"], "2010–2012", 2),
  q("COVID-19 was declared a pandemic in…", ["2012", "2016", "2019 as the WHO pandemic declaration year", "2020"], "2020", 1),
  q("The U.S. Civil War began with firing on…", ["Fort McHenry", "Fort Sumter", "the Alamo as 1861", "Harpers Ferry as the war's first battle"], "Fort Sumter", 2),
  q("Gettysburg was fought in…", ["1861", "1862", "1863", "1865"], "1863", 2),
  q("The Emancipation Proclamation took effect…", ["1861", "January 1, 1863", "1865 as this text", "1870"], "January 1, 1863", 2),
  q("Appomattox Court House is where…", ["Lincoln was shot", "Lee surrendered to Grant", "the Emancipation was signed", "Sherman began his march as a signing"], "Lee surrendered to Grant", 2),
  q("Reconstruction in the U.S. followed the…", ["Revolution", "Civil War", "War of 1812", "Spanish-American War"], "Civil War", 1),
  q("The 13th, 14th, and 15th Amendments are the…", ["Bill of Rights", "Reconstruction Amendments", "Progressive-era only", "New Deal amendments"], "Reconstruction Amendments", 2),
  q("Plessy v. Ferguson (1896) upheld…", ["school integration", "racial segregation ('separate but equal')", "the end of slavery as a holding", "women's suffrage"], "racial segregation ('separate but equal')", 2),
  q("The 19th Amendment (U.S.) concerned…", ["Prohibition", "women's suffrage", "income tax", "two-term limit"], "women's suffrage", 1),
  q("The New Deal was the program of…", ["Hoover as the New Deal name", "Franklin D. Roosevelt", "Truman as the New Deal", "Eisenhower"], "Franklin D. Roosevelt", 1),
  q("Pearl Harbor brought the U.S. into…", ["World War I", "World War II", "Korea", "Vietnam as the trigger"], "World War II", 1),
  q("The G.I. Bill after WWII aided…", ["only Japanese Americans in camps as this bill", "veterans (education, housing, etc.)", "only railroads", "only banks as 1933"], "veterans (education, housing, etc.)", 2),
  q("McCarthyism is associated with…", ["only the New Deal", "anti-communist hunts in the U.S.", "only civil rights sit-ins", "only isolationism of 1940"], "anti-communist hunts in the U.S.", 2),
  q("The Voting Rights march in Selma is associated with…", ["1955 Montgomery as this bridge", "1965 and the Edmund Pettus Bridge", "1963 Birmingham church as this march's name", "1968 Memphis"], "1965 and the Edmund Pettus Bridge", 2),
  q("Watergate led to the resignation of…", ["Johnson", "Richard Nixon", "Ford as the scandal's president", "Carter"], "Richard Nixon", 1),
  q("The Iran hostage crisis began in…", ["1968", "1973", "1979", "1986 as the start"], "1979", 2),
  q("The first Gulf War to expel Iraq from Kuwait was in…", ["1980 as Desert Storm", "1991", "2003 as this expulsion war's name", "2011"], "1991", 2),
  q("The 2003 Iraq War toppled…", ["Nasser", "Saddam Hussein", "the Shah as 2003", "Gaddafi as 2003"], "Saddam Hussein", 2),
  q("Nelson Mandela was released from prison in…", ["1976", "1985", "1990", "1999"], "1990", 2),
  q("The first human on the Moon was…", ["Yuri Gagarin as the Moon", "Neil Armstrong", "John Glenn as the Moon", "Buzz Aldrin as first out"], "Neil Armstrong", 1),
  q("The second human on the Moon (same landing) was…", ["Michael Collins as the walker", "Buzz Aldrin", "Alan Shepard as Apollo 11", "Jim Lovell"], "Buzz Aldrin", 2),
  q("Michael Collins on Apollo 11…", ["walked first", "orbited in the command module", "stayed on Earth", "piloted a Shuttle"], "orbited in the command module", 2),
  q("The Library of Alexandria is a wonder of…", ["Rome of the Republic as its site", "Hellenistic Egypt", "Athens of Pericles as its site", "Baghdad only"], "Hellenistic Egypt", 2),
  q("The Colossus of Rhodes was a…", ["lighthouse of Alexandria", "statue at a harbor", "tomb of Mausolus", "hanging garden"], "statue at a harbor", 2),
  q("The Terracotta Army was buried with…", ["Kublai Khan", "Qin Shi Huang", "Mao", "Yongle only"], "Qin Shi Huang", 2),
  q("Angkor Wat was built as a…", ["Japanese castle", "Khmer temple (later Buddhist as well)", "Mughal tomb", "Inca palace"], "Khmer temple (later Buddhist as well)", 2),
  q("Machu Picchu is associated with the…", ["Aztec", "Maya as the only name", "Inca", "Olmec"], "Inca", 1),
  q("Tenochtitlan was the capital of the…", ["Inca", "Maya as the only imperial capital of this name", "Aztec", "Moche"], "Aztec", 1),
  q("Chichen Itza is a city of the…", ["Aztec as the only name", "Maya", "Inca", "Mississippian"], "Maya", 1),
  q("Cahokia was a city of the…", ["Ancestral Pueblo only", "Mississippian culture", "Iroquois as a stone city of pyramids", "Norse"], "Mississippian culture", 3),
  q("The Iroquois (Haudenosaunee) Confederacy is in…", ["the Pacific Northwest only", "the Northeast woodlands", "the Andes", "the Plains as a stone confederacy only"], "the Northeast woodlands", 2),
  q("The Silk Road linked…", ["only Peru and Mexico", "East Asia and the Mediterranean world (among other routes)", "only Australia and New Zealand", "only the Great Lakes"], "East Asia and the Mediterranean world (among other routes)", 1),
  q("Zheng He led treasure voyages for…", ["the Ottomans", "Ming China", "Portugal as his flag", "Spain"], "Ming China", 3),
  q("Ibn Battuta was a…", ["Ming admiral", "traveler of the 14th-century Islamic world", "Portuguese captain of 1498", "Viking of 1000"], "traveler of the 14th-century Islamic world", 3),
  q("Marco Polo's Travels describe…", ["a Portuguese in Japan", "a Venetian in Yuan China (as the book has it)", "a Spaniard in Peru as this book", "a Dutchman in New York"], "a Venetian in Yuan China (as the book has it)", 2),
  q("Vasco da Gama reached India by sea in…", ["1488 as India", "1492 as India", "1498", "1521"], "1498", 3),
  q("Magellan's expedition is the first to…", ["reach America", "circumnavigate the globe (he died en route)", "reach India by the Cape as the first of da Gama's rivals", "map Australia"], "circumnavigate the globe (he died en route)", 2),
  q("Cortés led the Spanish war against the…", ["Inca as his theater", "Aztec", "Maya as his only war", "Mapuche as 1519"], "Aztec", 2),
  q("Pizarro led the Spanish war against the…", ["Aztec", "Inca", "Maya as 1532", "Taíno as his Andes war"], "Inca", 2),
  q("The Middle Passage was the…", ["Oregon Trail", "forced Atlantic crossing of enslaved Africans", "Silk Road", "Northwest Passage as a slave route name"], "forced Atlantic crossing of enslaved Africans", 1),
  q("Abolition of the British slave trade is dated…", ["1776 as British abolition", "1807 (trade); 1833 emancipation act", "1865 as British", "1888 as British"], "1807 (trade); 1833 emancipation act", 3),
  q("Brazil abolished slavery in…", ["1807", "1833 as Brazil", "1865 as Brazil", "1888"], "1888", 3),
  q("The Haitian Revolution is a landmark of…", ["only creole tax protest", "the destruction of slavery by the enslaved", "only a Napoleonic parade", "only U.S. occupation"], "the destruction of slavery by the enslaved", 2),
];

