import { q } from "../quiz";
import type { TriviaQ } from "../types";

export const HISTORY_BANK: TriviaQ[] = [
  q("The Declaration of Independence was adopted in\u2026", ["1770", "1776", "1787", "1812"], "1776", 1),
  q("The U.S. Constitution was written in\u2026", ["1776", "1787", "1803", "1865"], "1787", 1),
  q("Who was the first President of the United States?", ["Jefferson", "Washington", "Adams", "Madison"], "Washington", 1),
  q("The Civil War ended in\u2026", ["1850", "1861", "1865", "1877"], "1865", 1),
  q("Abraham Lincoln issued the Emancipation Proclamation during\u2026", ["the Revolution", "the Civil War", "World War I", "the New Deal"], "the Civil War", 1),
  q("World War II in Europe ended in\u2026", ["1943", "1945", "1948", "1950"], "1945", 1),
  q("The attack on Pearl Harbor was in\u2026", ["1939", "1941", "1944", "1945"], "1941", 1),
  q("The moon landing of Apollo 11 was in\u2026", ["1965", "1969", "1972", "1975"], "1969", 1),
  q("The Berlin Wall fell in\u2026", ["1979", "1985", "1989", "1991"], "1989", 1),
  q("The Soviet Union dissolved in\u2026", ["1985", "1989", "1991", "1995"], "1991", 2),
  q("Julius Caesar was a leader of\u2026", ["Greece", "Rome", "Persia", "Egypt"], "Rome", 1),
  q("The pyramids of Giza were built in\u2026", ["ancient Rome", "ancient Egypt", "ancient Babylon", "ancient China"], "ancient Egypt", 1),
  q("The Great Wall is associated with\u2026", ["Japan", "China", "Korea", "Mongolia"], "China", 1),
  q("The Magna Carta was sealed in\u2026", ["1066", "1215", "1492", "1688"], "1215", 2),
  q("1066 is the year of the\u2026", ["Spanish Armada's defeat", "Norman Conquest of England", "Boston Tea Party protest", "Fall of the Western Roman Empire"], "Norman Conquest of England", 2),
  q("Columbus crossed the Atlantic in\u2026", ["1400", "1492", "1519", "1588"], "1492", 1),
  q("The French Revolution began in\u2026", ["1776", "1789", "1812", "1848"], "1789", 2),
  q("Napoleon was defeated at Waterloo in\u2026", ["1805", "1812", "1815", "1821"], "1815", 2),
  q("The Industrial Revolution began in which country?", ["France", "the United States", "Britain", "Germany"], "Britain", 2),
  q("World War I began in\u2026", ["1905", "1914", "1918", "1929"], "1914", 1),
  q("The Armistice that ended WWI fighting was in\u2026", ["1914", "1917", "1918", "1920"], "1918", 2),
  q("The Treaty of Versailles is associated with the end of\u2026", ["WWII", "WWI", "the Civil War", "the Cold War"], "WWI", 2),
  q("The stock market crash that opened the Great Depression was in\u2026", ["1918", "1929", "1933", "1939"], "1929", 2),
  q("D-Day, the Normandy landings, was in\u2026", ["1942", "1943", "1944", "1945"], "1944", 2),
  q("The United Nations was founded in\u2026", ["1919", "1945", "1955", "1961"], "1945", 2),
  q("Martin Luther King Jr. gave the 'I Have a Dream' speech in\u2026", ["1955", "1963", "1968", "1974"], "1963", 2),
  q("The Civil Rights Act in the U.S. that banned segregation in public accommodations was in\u2026", ["1954", "1964", "1968", "1972"], "1964", 2),
  q("Brown v. Board of Education was decided in\u2026", ["1948", "1954", "1964", "1971"], "1954", 2),
  q("The Louisiana Purchase was in\u2026", ["1776", "1803", "1812", "1848"], "1803", 2),
  q("The Lewis and Clark expedition followed the\u2026", ["Louisiana Purchase", "Civil War", "Gold Rush of 1849", "Mexican War's end"], "Louisiana Purchase", 2),
  q("Texas independence from Mexico is tied to\u2026", ["1836", "1848", "1861", "1876"], "1836", 2),
  q("The Alamo fell in\u2026", ["1812", "1836", "1845", "1861"], "1836", 1),
  q("Hawaii became a U.S. state in\u2026", ["1898", "1941", "1959", "1965"], "1959", 2),
  q("Alaska became a U.S. state in\u2026", ["1867", "1945", "1959", "1963"], "1959", 2),
  q("Prohibition in the U.S. was the\u2026", ["16th Amendment era", "18th Amendment era", "19th Amendment era", "14th Amendment era"], "18th Amendment era", 2),
  q("The 13th Amendment abolished\u2026", ["alcohol", "slavery", "poll taxes", "the draft"], "slavery", 1),
  q("The Renaissance is associated first with\u2026", ["England", "Italy", "Russia", "Japan"], "Italy", 1),
  q("The printing press in Europe is tied to\u2026", ["Newton", "Gutenberg", "Galileo", "Watt"], "Gutenberg", 2),
  q("Martin Luther's 95 Theses are a start of the\u2026", ["Crusades", "Reformation", "Enlightenment", "Industrial Revolution"], "Reformation", 2),
  q("The Black Death in Europe peaked in the\u2026", ["1100s", "1340s", "1500s", "1700s"], "1340s", 2),
  q("The Roman Empire in the west is traditionally said to have fallen in\u2026", ["44 BCE", "476 CE", "800", "1453"], "476 CE", 3),
  q("Constantinople fell to the Ottomans in\u2026", ["1204", "1453", "1492", "1526"], "1453", 3),
  q("The Spanish Armada sailed against England in\u2026", ["1492", "1588", "1666", "1707"], "1588", 3),
  q("Elizabeth I of England was a monarch of the\u2026", ["15th century", "Tudor era", "Victorian era", "Plantagenets"], "Tudor era", 2),
  q("The American president during most of WWII was\u2026", ["Hoover", "FDR", "Truman", "Eisenhower"], "FDR", 2),
  q("Harry Truman ordered\u2026", ["Pearl Harbor", "the atomic bombings of Japan", "D-Day", "the League of Nations"], "the atomic bombings of Japan", 2),
  q("The Cold War was chiefly a rivalry of the U.S. and\u2026", ["Great Britain", "the Soviet Union", "Nazi Germany", "Imperial Japan"], "the Soviet Union", 1),
  q("The Cuban Missile Crisis was in\u2026", ["1957", "1962", "1968", "1973"], "1962", 2),
  q("Neil Armstrong was the first person to\u2026", ["orbit the Earth", "walk on the Moon", "walk in open space", "land on Mars"], "walk on the Moon", 1),
  q("Yuri Gagarin was the first person to\u2026", ["walk on the Moon", "orbit Earth", "fly a jet", "map Antarctica"], "orbit Earth", 2),
  q("The Wright brothers flew in\u2026", ["1892", "1903", "1914", "1927"], "1903", 2),
  q("The Titanic sank in\u2026", ["1905", "1912", "1918", "1922"], "1912", 1),
  q("The Great Fire of London was in\u2026", ["1588", "1666", "1755", "1812"], "1666", 3),
  q("The Battle of Hastings was in\u2026", ["1066", "1215", "1415", "1588"], "1066", 2),
  q("Joan of Arc is associated with\u2026", ["Spain", "France", "Italy", "England"], "France", 2),
  q("Genghis Khan led the\u2026", ["Ottomans", "Mongols", "Vikings", "Aztecs"], "Mongols", 1),
  q("The Aztec capital was at\u2026", ["Cuzco", "Tenochtitlan", "Teotihuacan", "Chichen Itza"], "Tenochtitlan", 2),
  q("The Silk Road linked China with\u2026", ["Japan / the Pacific islands", "the West / Mediterranean world", "Australia / New Zealand", "the Arctic / Siberian north"], "the West / Mediterranean world", 2),
  q("The Crusades were wars over\u2026", ["the Americas", "the Holy Land", "China", "Australia"], "the Holy Land", 2),
  q("The Ottoman Empire's last centuries were centered on\u2026", ["Rome / the Vatican", "Istanbul / Constantinople", "Baghdad / Mesopotamia", "Cairo / Alexandria"], "Istanbul / Constantinople", 2),
  q("India's independence from Britain is dated\u2026", ["1939", "1947", "1950", "1962"], "1947", 2),
  q("The U.S. entered World War I in\u2026", ["1914", "1915", "1917", "1918"], "1917", 2),
  q("The 22nd Amendment limited U.S. presidents to\u2026", ["one term", "two elected terms", "four terms", "six years total"], "two elected terms", 2),
  q("The Louisiana city named for a French king is\u2026", ["Baton Rouge", "New Orleans", "Lafayette", "Shreveport"], "New Orleans", 2),
  q("Jamestown was founded in\u2026", ["1492", "1607", "1620", "1776"], "1607", 2),
  q("The Mayflower Compact is tied to\u2026", ["Jamestown", "Plymouth / 1620", "Philadelphia 1776", "Boston 1773"], "Plymouth / 1620", 2),
  q("The Boston Tea Party was in\u2026", ["1765", "1770", "1773", "1776"], "1773", 2),
  q("Gettysburg was a battle of the\u2026", ["Revolution", "Civil War", "War of 1812", "WWI"], "Civil War", 1),
  q("The War of 1812 included the burning of\u2026", ["Philadelphia", "Washington, D.C.", "Boston", "New York"], "Washington, D.C.", 2),
  q("The Marshall Plan was U.S. aid to\u2026", ["postwar Japan and Korea", "postwar Western Europe", "South America", "the defeated Confederacy"], "postwar Western Europe", 3),
  q("NATO was founded in\u2026", ["1945", "1949", "1955", "1961"], "1949", 3),
  q("The Korean War began in\u2026", ["1945", "1950", "1953", "1960"], "1950", 2),
  q("The Vietnam War's U.S. combat role wound down with withdrawals in the\u2026", ["early 1950s", "early 1960s", "early 1970s", "early 1990s"], "early 1970s", 2),
  q("The 19th-century 'Scramble for Africa' was\u2026", ["African unification", "European colonization", "a civil rights march", "a spice-trade pact"], "European colonization", 3),
  q("The Meiji Restoration was in\u2026", ["China", "Japan", "Korea", "Vietnam"], "Japan", 3),
  q("The Opium Wars involved Britain and\u2026", ["Japan", "China", "India", "Persia"], "China", 3),
  q("The partition of India created India and\u2026", ["Bangladesh immediately", "Pakistan", "Sri Lanka", "Nepal"], "Pakistan", 2),
  q("The Hagia Sophia was built as a\u2026", ["mosque for the Ottoman sultans", "church in Constantinople", "temple to the Greek gods", "synagogue for the city's Jews"], "church in Constantinople", 3),
  q("The Hundred Years' War was mainly between\u2026", ["Spain and Portugal", "England and France", "Rome and Carthage", "Russia and Sweden"], "England and France", 2),
  // v0.0.28: +history trivia cards (white/blue-leaning)
  q("Rulers of ancient Egypt were called…", ["pharaohs", "emperors", "czars", "shoguns"], "pharaohs", 1),
  q("Tutankhamun was a boy king of ancient…", ["Egypt", "Greece", "Persia", "Rome"], "Egypt", 1),
  q("Egyptian mummies were made to preserve…", ["bodies", "grain", "scrolls", "jewels"], "bodies", 1),
  q("Cleopatra was a famous queen of…", ["Egypt", "Greece", "Persia", "Carthage"], "Egypt", 1),
  q("Gladiators fought before huge crowds in ancient…", ["Rome", "China", "Egypt", "Peru"], "Rome", 1),
  q("Latin was the language of ancient…", ["Rome", "Greece", "Egypt", "Persia"], "Rome", 1),
  q("Long straight roads and aqueducts were hallmarks of the…", ["Romans", "Vikings", "Aztecs", "Mongols"], "Romans", 1),
  q("Socrates and Aristotle were philosophers of ancient…", ["Greece", "Rome", "Egypt", "China"], "Greece", 1),
  q("Confucius was a teacher and thinker from ancient…", ["China", "India", "Greece", "Persia"], "China", 1),
  q("Buddhism began in ancient…", ["India", "China", "Japan", "Tibet"], "India", 1),
  q("Mesopotamia lay between the Tigris and the…", ["Euphrates", "Nile", "Indus", "Jordan"], "Euphrates", 1),
  q("Ancient Egypt grew up along the banks of the…", ["Nile", "Tigris", "Indus", "Jordan"], "Nile", 1),
  q("Hannibal of Carthage famously crossed the Alps with…", ["elephants", "camels", "oxen", "bears"], "elephants", 1),
  q("The Bronze Age came just before the…", ["Iron Age", "Stone Age", "Copper Age", "Ice Age"], "Iron Age", 1),
  q("Vikings came from…", ["Scandinavia", "Spain", "Greece", "North Africa"], "Scandinavia", 1),
  q("Viking raiders crossed the seas in…", ["longships", "galleons", "junks", "steamships"], "longships", 1),
  q("Medieval knights went into battle wearing…", ["armor", "togas", "kimonos", "tuxedos"], "armor", 1),
  q("A castle's water-filled defensive ditch is a…", ["moat", "keep", "turret", "rampart"], "moat", 1),
  q("Japan's sword-carrying warrior class was the…", ["samurai", "knights", "Spartans", "Cossacks"], "samurai", 1),
  q("Russia's emperors were called…", ["czars", "shoguns", "pharaohs", "caliphs"], "czars", 1),
  q("Marco Polo traveled from Venice all the way to…", ["China", "Brazil", "Australia", "Canada"], "China", 1),
  q("The Inca built roads and terraces high in the…", ["Andes", "Alps", "Rockies", "Himalayas"], "Andes", 1),
  q("The ancient Maya built pyramids in…", ["Mesoamerica", "Scandinavia", "Australia", "Siberia"], "Mesoamerica", 1),
  q("Beijing's Forbidden City was the palace of China's…", ["emperors", "presidents", "monks", "generals"], "emperors", 1),
  q("The Pilgrims sailed to America aboard the…", ["Mayflower", "Santa María", "Endeavour", "Beagle"], "Mayflower", 1),
  q("Columbus's ships were the Niña, the Pinta, and the…", ["Santa María", "Mayflower", "Victoria", "Golden Hind"], "Santa María", 1),
  q("Paul Revere is famous for his midnight…", ["ride", "speech", "duel", "swim"], "ride", 1),
  q("The 13 stripes on the U.S. flag stand for the original…", ["colonies", "presidents", "battles", "generals"], "colonies", 1),
  q("George Washington commanded the Continental Army during the…", ["American Revolution", "American Civil War", "War of 1812", "Mexican–American War"], "American Revolution", 1),
  q("Lincoln's short, famous speech at a Pennsylvania battlefield was the…", ["Gettysburg Address", "Farewell Address", "Cross of Gold", "Fireside Chat"], "Gettysburg Address", 1),
  q("Harriet Tubman led people to freedom on the…", ["Underground Railroad", "Oregon Trail", "Transcontinental Railroad", "Santa Fe Trail"], "Underground Railroad", 1),
  q("Frederick Douglass was a famous…", ["abolitionist", "general", "inventor", "astronaut"], "abolitionist", 1),
  q("Susan B. Anthony campaigned for women's…", ["right to vote", "right to drive", "military service", "jury pay"], "right to vote", 1),
  q("Pioneers on the Oregon Trail headed for the…", ["Pacific Northwest", "Texas Gulf Coast", "Great Lakes region", "New England coast"], "Pacific Northwest", 1),
  q("Forty-niners rushed to California hoping to find…", ["gold", "oil", "silver", "furs"], "gold", 1),
  q("Pony Express riders carried…", ["mail", "gold", "cattle", "passengers"], "mail", 1),
  q("The Salem witch trials took place in colonial…", ["Massachusetts", "Pennsylvania", "New York", "Rhode Island"], "Massachusetts", 1),
  q("Benjamin Franklin's famous kite experiment explored…", ["electricity", "magnetism", "gravity", "weather"], "electricity", 1),
  q("Teddy bears are named after President…", ["Theodore Roosevelt", "Franklin Roosevelt", "William Taft", "Woodrow Wilson"], "Theodore Roosevelt", 1),
  q("Women in World War II factories were symbolized by…", ["Rosie the Riveter", "Betty Crocker", "Lady Liberty", "Molly Pitcher"], "Rosie the Riveter", 1),
  q("Anne Frank kept her famous diary while hiding in…", ["Amsterdam", "Berlin", "Paris", "Vienna"], "Amsterdam", 1),
  q("Amelia Earhart was a famous…", ["aviator", "astronaut", "sailor", "race car driver"], "aviator", 1),
  q("Charles Lindbergh made the first solo nonstop flight across the…", ["Atlantic", "Pacific", "Sahara", "Andes"], "Atlantic", 1),
  q("Florence Nightingale became famous as a…", ["nurse", "queen", "pilot", "sculptor"], "nurse", 1),
  q("Queen Victoria reigned over the…", ["United Kingdom", "Netherlands", "Spain", "Russia"], "United Kingdom", 1),
  q("Henry VIII of England married how many times?", ["six", "four", "eight", "three"], "six", 1),
  q("Winston Churchill led Britain as prime minister during…", ["World War II", "the Crimean War", "the Boer War", "the Napoleonic Wars"], "World War II", 1),
  q("Mahatma Gandhi's main method of resisting British rule was…", ["nonviolent protest", "armed revolt", "naval blockade", "royal decree"], "nonviolent protest", 1),
  q("Mao Zedong led the Communist revolution in…", ["China", "Vietnam", "Korea", "Cuba"], "China", 1),
  q("Fidel Castro led a revolution in…", ["Cuba", "Mexico", "Chile", "Panama"], "Cuba", 1),
  q("Benito Mussolini was the fascist dictator of…", ["Italy", "Spain", "Portugal", "Greece"], "Italy", 1),
  q("The Berlin Wall split the city of Berlin into…", ["East and West", "North and South", "four quarters", "old and new"], "East and West", 1),
  q("The Iron Curtain divided Europe during the…", ["Cold War", "Crusades", "Renaissance", "Bronze Age"], "Cold War", 1),
  q("Ronald Reagan urged Mr. Gorbachev to tear down…", ["this wall", "that gate", "the fence", "your guns"], "this wall", 1),
  q("The Titanic sank after striking an…", ["iceberg", "reef", "whale", "U-boat"], "iceberg", 1),
  q("The Hindenburg, destroyed in a famous fire, was an…", ["airship", "ocean liner", "express train", "submarine"], "airship", 1),
  q("The Wright brothers made their first powered flights near…", ["Kitty Hawk", "Dayton", "Cape Canaveral", "Detroit"], "Kitty Hawk", 1),
  q("Marie Antoinette was queen of…", ["France", "Austria", "Spain", "England"], "France", 1),
  q("The Terracotta Army guards the tomb of China's first…", ["emperor", "poet", "general", "monk"], "emperor", 1),
  q("Lewis and Clark were helped on their journey by the Shoshone interpreter…", ["Sacagawea", "Pocahontas", "Squanto", "Tecumseh"], "Sacagawea", 1),
  q("Clara Barton founded the…", ["American Red Cross", "Girl Scouts", "YMCA", "Salvation Army"], "American Red Cross", 1),
  q("Juliette Gordon Low founded America's…", ["Girl Scouts", "Red Cross", "4-H Club", "Camp Fire Girls"], "Girl Scouts", 2),
  q("Medieval peasants bound to a lord's land were called…", ["serfs", "senators", "samurai", "squires"], "serfs", 1),
  q("A young knight-in-training was called a…", ["squire", "serf", "friar", "jester"], "squire", 1),
  q("King Tut's treasures were found in Egypt's Valley of the…", ["Kings", "Queens", "Gods", "Pharaohs"], "Kings", 1),
  q("Ancient Egyptians wrote on paper made from…", ["papyrus", "bamboo", "silk", "birch bark"], "papyrus", 1),
  q("The Great Wall of China was built mainly to keep out…", ["northern invaders", "river floods", "wild tigers", "Japanese sea pirates"], "northern invaders", 1),
  q("The Liberty Bell is displayed in…", ["Philadelphia", "Boston", "New York", "Baltimore"], "Philadelphia", 1),
  q("Thomas Jefferson's Virginia home is called…", ["Monticello", "Mount Vernon", "Montpelier", "Hermitage"], "Monticello", 2),
  q("George Washington's Virginia estate is called…", ["Mount Vernon", "Monticello", "Montpelier", "Hermitage"], "Mount Vernon", 1),
  q("The first president to live in the White House was…", ["John Adams", "George Washington", "Thomas Jefferson", "James Madison"], "John Adams", 2),
  q("Pocahontas is linked to the English colony of…", ["Jamestown", "Plymouth", "Roanoke", "Boston"], "Jamestown", 1),
  q("The Pilgrims' harvest feast is often linked to their neighbors, the…", ["Wampanoag", "Cherokee", "Sioux", "Navajo"], "Wampanoag", 2),
  q("Mount Rushmore's carved faces are of U.S.…", ["presidents", "generals", "astronauts", "inventors"], "presidents", 1),
  q("Theodore Roosevelt led a volunteer cavalry unit nicknamed the…", ["Rough Riders", "Green Berets", "Minutemen", "Buffalo Soldiers"], "Rough Riders", 2),
  q("Colonial militia ready to fight on short notice were called…", ["Minutemen", "Redcoats", "Rough Riders", "Hessians"], "Minutemen", 1),
  q("British soldiers in the American Revolution were nicknamed…", ["Redcoats", "Bluecoats", "Minutemen", "Greenjackets"], "Redcoats", 1),
  q("Hessians who fought for Britain in the Revolution came from…", ["Germany", "Ireland", "Spain", "Sweden"], "Germany", 2),
  q("The Allied leaders at Yalta were Roosevelt, Stalin, and…", ["Churchill", "de Gaulle", "Truman", "Chamberlain"], "Churchill", 2),
  q("Toussaint Louverture led a revolution in…", ["Haiti", "Cuba", "Jamaica", "Brazil"], "Haiti", 2),
  q("Peter the Great founded the Russian city of…", ["St. Petersburg", "Moscow", "Vladivostok", "Nizhny Novgorod"], "St. Petersburg", 2),
  q("Catherine the Great was empress of…", ["Russia", "Austria", "Prussia", "Sweden"], "Russia", 1),
  q("Captain James Cook is famous for exploring the…", ["Pacific Ocean", "Amazon River", "Sahara Desert", "Gobi Desert"], "Pacific Ocean", 2),
  q("Roald Amundsen led the first expedition to reach the…", ["South Pole", "top of Everest", "Mariana Trench", "Nile's source"], "South Pole", 2),
  q("Edmund Hillary and Tenzing Norgay were first to summit…", ["Mount Everest", "K2", "Kilimanjaro", "Denali"], "Mount Everest", 1),
  q("Elizabeth I of England was the daughter of…", ["Henry VIII", "Edward VI", "James I", "Richard III"], "Henry VIII", 2),
  q("Mary, Queen of Scots, was executed on the orders of…", ["Elizabeth I", "Henry VIII", "James I", "Mary I"], "Elizabeth I", 2),
  q("Napoleon Bonaparte was born on the island of…", ["Corsica", "Sicily", "Sardinia", "Malta"], "Corsica", 2),
  q("After Waterloo, Napoleon spent his last years exiled on…", ["Saint Helena", "Corsica", "Isle of Man", "Sardinia"], "Saint Helena", 2),
  q("Otto von Bismarck was the statesman who unified…", ["Germany", "Italy", "Austria", "Poland"], "Germany", 2),
  q("Giuseppe Garibaldi was a hero of the unification of…", ["Italy", "Germany", "Spain", "Greece"], "Italy", 2),
  q("The Boxer Rebellion took place in…", ["China", "India", "Japan", "Korea"], "China", 2),
  q("Shah Jahan built the Taj Mahal as a…", ["tomb for his wife", "royal palace", "army fortress", "Hindu temple"], "tomb for his wife", 1),
  q("The Taj Mahal was built during the rule of the…", ["Mughal Empire", "Ottoman Empire", "Persian Empire", "British Raj"], "Mughal Empire", 2),
  q("Kublai Khan founded China's…", ["Yuan dynasty", "Ming dynasty", "Qing dynasty", "Han dynasty"], "Yuan dynasty", 2),
  q("Japan's military rulers for centuries were the…", ["shoguns", "pharaohs", "sultans", "czars"], "shoguns", 2),
  q("Francisco Franco ruled Spain after winning the…", ["Spanish Civil War", "Peninsular War", "Thirty Years' War", "Carlist War"], "Spanish Civil War", 2),
  q("Nelson Mandela spent most of his prison years on…", ["Robben Island", "Alcatraz", "Devil's Island", "Elba"], "Robben Island", 2),
  q("Czechoslovakia's peaceful anti-communist revolution was the…", ["Velvet Revolution", "Orange Revolution", "Rose Revolution", "Carnation Revolution"], "Velvet Revolution", 2),
  q("Gorbachev's policy of openness in the USSR was called…", ["glasnost", "perestroika", "détente", "samizdat"], "glasnost", 2),
  q("Gorbachev's policy of economic restructuring was called…", ["perestroika", "glasnost", "détente", "samizdat"], "perestroika", 2),
  q("JFK's line ask not what your country can do for you came from his…", ["inaugural address", "Berlin speech", "farewell address", "Moon speech"], "inaugural address", 2),
  q("The Peace Corps was created under President…", ["Kennedy", "Eisenhower", "Johnson", "Truman"], "Kennedy", 2),
  q("Lyndon Johnson's sweeping domestic program was called the…", ["Great Society", "Fair Deal", "New Frontier", "Square Deal"], "Great Society", 2),
  q("Richard Nixon resigned the presidency over the…", ["Watergate scandal", "Teapot Dome scandal", "Iran-Contra affair", "Pentagon Papers"], "Watergate scandal", 1),
  q("The Phoenicians were famous ancient…", ["sea traders", "desert nomads", "mountain herders", "horse archers"], "sea traders", 2),
  q("Emperor Hadrian built a famous wall across northern…", ["Britain", "Gaul", "Spain", "Germany"], "Britain", 2),
  q("Leif Erikson was a Norse explorer who reached…", ["North America", "Australia", "India", "South Africa"], "North America", 2),
  q("The gunfight at the O.K. Corral took place in…", ["Tombstone", "Dodge City", "Deadwood", "Abilene"], "Tombstone", 2),
  q("Sitting Bull and Crazy Horse defeated Custer at the Battle of the…", ["Little Bighorn", "Wounded Knee", "Bull Run", "Alamo"], "Little Bighorn", 2),
  q("The Trail of Tears was the forced removal of the…", ["Cherokee", "Inuit", "Hopi", "Aleut"], "Cherokee", 2),
  q("The Spanish Armada was sent to invade…", ["England", "France", "Portugal", "Holland"], "England", 1),
  q("The Crusaders who fought for the Holy Land were mostly from…", ["Europe", "China", "India", "Africa"], "Europe", 1),
  q("Joan of Arc led French troops against the…", ["English", "Spanish", "Germans", "Romans"], "English", 1),
  q("William the Conqueror came to England from…", ["Normandy", "Scotland", "Denmark", "Castile"], "Normandy", 2),
  q("Richard the Lionheart was a king of…", ["England", "France", "Scotland", "Spain"], "England", 2),
  q("The Black Death was a deadly outbreak of…", ["plague", "smallpox", "measles", "cholera"], "plague", 1),
  q("Gutenberg's famous printed book was the…", ["Bible", "Odyssey", "Quran", "Iliad"], "Bible", 2),
  q("The Ottoman Empire's rulers were called…", ["sultans", "czars", "shoguns", "pharaohs"], "sultans", 1),
  q("Suleiman the Magnificent was a sultan of the…", ["Ottoman Empire", "Mughal Empire", "Persian Empire", "Mongol Empire"], "Ottoman Empire", 2),
  q("The ancient city of Troy was in what is now…", ["Turkey", "Greece", "Italy", "Egypt"], "Turkey", 2),
  q("The ancient city of Carthage was in what is now…", ["Tunisia", "Egypt", "Morocco", "Libya"], "Tunisia", 2),
  q("The Aztecs built their capital on an island in a…", ["lake", "desert", "jungle", "mountain"], "lake", 2),
  q("The ancient Olympic Games honored the Greek god…", ["Zeus", "Apollo", "Ares", "Poseidon"], "Zeus", 2),
  q("Rome's legendary founders were the twins Romulus and…", ["Remus", "Romeo", "Julius", "Marcus"], "Remus", 1),
  q("The Wild West sharpshooter who starred in Buffalo Bill's show was…", ["Annie Oakley", "Calamity Jane", "Belle Starr", "Pearl Hart"], "Annie Oakley", 2),
  q("Sitting Bull was a leader of the…", ["Lakota Sioux", "Eastern Cherokee", "Chiricahua Apache", "Navajo"], "Lakota Sioux", 2),
  q("Geronimo was a famous leader of the…", ["Apache", "Cherokee", "Iroquois", "Seminole"], "Apache", 2),
  q("Lewis and Clark's journey finally reached the…", ["Pacific Ocean", "Gulf of Mexico", "Great Lakes", "Hudson Bay"], "Pacific Ocean", 2),
  q("The Great Depression began with a crash on…", ["Wall Street", "Main Street", "Fleet Street", "Broadway"], "Wall Street", 1),
  q("Dust Bowl storms of the 1930s struck the U.S.…", ["Great Plains", "East Coast", "Pacific Northwest", "Deep South"], "Great Plains", 2),
  q("The Hanging Gardens, an ancient wonder, were said to be in…", ["Babylon", "Athens", "Rome", "Memphis"], "Babylon", 2),
  q("Sir Francis Drake was a famous English…", ["sea captain", "court painter", "poet laureate", "bishop"], "sea captain", 1),
  q("Magna Carta limited the power of England's…", ["king", "army", "church", "parliament"], "king", 1),
  q("Pharaoh Khufu is linked to the building of the…", ["Great Pyramid", "Valley of the Kings", "Abu Simbel", "Karnak Temple"], "Great Pyramid", 2),
  q("Ramesses II carved giant rock temples at…", ["Abu Simbel", "Giza", "Saqqara", "Alexandria"], "Abu Simbel", 2),
  q("Before airplanes, the Wright brothers built and sold…", ["bicycles", "clocks", "wagons", "radios"], "bicycles", 1),
  q("A small Spartan-led force made a legendary stand against Persia at…", ["Thermopylae", "Marathon", "Troy", "Actium"], "Thermopylae", 2),
  q("The famous mutiny on HMS Bounty was led by…", ["Fletcher Christian", "William Bligh", "James Cook", "Horatio Nelson"], "Fletcher Christian", 2),
  q("Admiral Nelson was killed while winning the Battle of…", ["Trafalgar", "Waterloo", "Hastings", "Agincourt"], "Trafalgar", 2),
  q("Charles Darwin sailed around the world aboard HMS…", ["Beagle", "Victory", "Bounty", "Endeavour"], "Beagle", 2),
];
