import { q } from "../quiz";
import type { TriviaQ } from "../types";

/** Deep-cut nature trivia cards (tarantulas, sharks, deep-sea fish). v0.0.16 k16a. Wired via weekly_20260922. */
export const NATURE_LIFE_PART_A: TriviaQ[] = [
  q("Adult male Theraphosa blondi are unusual because they lack…", ["pedipalps", "tibial spurs (mating hooks)", "book lungs", "urticating hairs"], "tibial spurs (mating hooks)", 3),
  q("Monocentropus balfouri stands out among tarantulas for…", ["being venomless", "communal living, with mothers tolerating young", "living only in caves", "ballooning on silk as adults"], "communal living, with mothers tolerating young", 3),
  q("Sexing a tarantula from its molt means checking for spermathecae near the…", ["spinnerets", "epigastric furrow", "chelicerae", "eye tubercle"], "epigastric furrow", 3),
  q("Harpactirinae, the 'baboon' tarantula subfamily, is native to…", ["South America", "Africa", "Southeast Asia", "Australia"], "Africa", 3),
  q("The tarantula subfamily Theraphosinae is native to the…", ["Old World tropics", "Americas", "Australia", "Indian subcontinent"], "Americas", 3),
  q("Stromatopelma calceatum is the hobby's…", ["featherleg baboon", "king baboon", "horned baboon", "cobalt blue"], "featherleg baboon", 3),
  q("Omothymus violaceopes is sold in the hobby as the…", ["Singapore blue", "cobalt blue", "Socotra Island blue", "green bottle blue"], "Singapore blue", 3),
  q("Xenesthis immanis is often called the…", ["Colombian giant redleg", "Brazilian black", "purple bloom birdeater", "Chaco golden knee"], "purple bloom birdeater", 3),
  q("Frilled-shark gestation may last up to about…", ["9 months", "18 months", "2 years", "3.5 years"], "3.5 years", 3),
  q("A 2016 study estimated the oldest sampled Greenland shark at roughly…", ["100 years", "180 years", "392 years", "1 000 years"], "392 years", 3),
  q("Greenland shark ages were estimated by radiocarbon-dating the…", ["vertebral rings", "eye-lens nucleus", "fin spines", "teeth"], "eye-lens nucleus", 3),
  q("The first megamouth shark was found in 1976 off…", ["Japan", "Hawaii", "South Africa", "California"], "Hawaii", 3),
  q("Sand tiger embryos eating their siblings in the uterus is called…", ["oophagy", "adelphophagy", "placentotrophy", "ovoviviparity"], "adelphophagy", 3),
  q("In oophagy, lamniform shark embryos feed on…", ["their siblings", "unfertilized eggs the mother keeps producing", "a yolk-sac placenta", "uterine milk only"], "unfertilized eggs the mother keeps producing", 3),
  q("The first confirmed shark virgin birth (reported 2007) was in a captive…", ["bonnethead", "zebra shark", "blacktip reef shark", "whitespotted bamboo shark"], "bonnethead", 3),
  q("The Indonesian coelacanth species is…", ["Latimeria chalumnae", "Latimeria menadoensis", "Neoceratodus forsteri", "Protopterus annectens"], "Latimeria menadoensis", 3),
  q("The 1938 coelacanth rediscovery came from a trawler catch off…", ["Madagascar", "East London, South Africa", "Sulawesi", "the Comoros"], "East London, South Africa", 3),
  q("The Australian lungfish is…", ["Protopterus annectens", "Lepidosiren paradoxa", "Neoceratodus forsteri", "Latimeria chalumnae"], "Neoceratodus forsteri", 3),
  q("A sawfish's rostral 'teeth' are actually modified…", ["true jaw teeth", "dermal denticles", "fin rays", "gill rakers"], "dermal denticles", 3),
  q("Electrophorus voltai, described in 2019, can discharge up to about…", ["60 V", "220 V", "860 V", "5 000 V"], "860 V", 3),
  q("The deepest fish yet filmed (8 336 m, Izu–Ogasawara Trench) was a…", ["anglerfish", "snailfish", "cusk-eel", "grenadier"], "snailfish", 3),
  q("The Mariana snailfish is…", ["Pseudoliparis swirei", "Abyssobrotula galatheae", "Bathysaurus ferox", "Coryphaenoides armatus"], "Pseudoliparis swirei", 3),
  q("In many deep-sea anglerfishes, dwarf males…", ["guard the eggs in a nest", "fuse to females and share their blood supply", "carry the young in a pouch", "hunt with a larger lure than females"], "fuse to females and share their blood supply", 3),
  q("Chimaeras sit with sharks and rays in Chondrichthyes as the subclass…", ["Elasmobranchii", "Holocephali", "Actinopterygii", "Sarcopterygii"], "Holocephali", 3),
  q("A pregnant whale shark caught off Taiwan in the mid-1990s carried about…", ["30 pups", "100 pups", "300 pups", "3 000 pups"], "300 pups", 3),
  q("Frilled, sixgill, and sevengill sharks belong to the order…", ["Lamniformes", "Hexanchiformes", "Orectolobiformes", "Squaliformes"], "Hexanchiformes", 3),
  q("Whale sharks and nurse sharks belong to the order…", ["Carcharhiniformes", "Orectolobiformes", "Lamniformes", "Hexanchiformes"], "Orectolobiformes", 3),
  q("Tiger, bull, and hammerhead sharks belong to the order…", ["Carcharhiniformes", "Lamniformes", "Squaliformes", "Orectolobiformes"], "Carcharhiniformes", 3),
  q("The shortfin mako's scientific name is…", ["Isurus oxyrinchus", "Lamna nasus", "Carcharias taurus", "Alopias vulpinus"], "Isurus oxyrinchus", 3),
  q("The tiger shark's scientific name is…", ["Galeocerdo cuvier", "Carcharhinus leucas", "Negaprion brevirostris", "Sphyrna mokarran"], "Galeocerdo cuvier", 3),
  q("The bull shark's scientific name is…", ["Carcharhinus leucas", "Carcharhinus longimanus", "Prionace glauca", "Galeocerdo cuvier"], "Carcharhinus leucas", 3),
  q("Australian funnel-web spiders are, like tarantulas,…", ["araneomorphs", "mygalomorphs", "harvestmen", "solifuges"], "mygalomorphs", 3),
  q("Tarantula hawks are spider wasps of the genus…", ["Vespa", "Pepsis", "Sphex", "Polistes"], "Pepsis", 3),
  q("The tarantula hawk wasp is the official state insect of…", ["Arizona", "New Mexico", "Texas", "Nevada"], "New Mexico", 3),
  q("The bonnethead's scientific name is…", ["Sphyrna tiburo", "Sphyrna mokarran", "Sphyrna zygaena", "Sphyrna lewini"], "Sphyrna tiburo", 3),
  q("The scalloped hammerhead's scientific name is…", ["Sphyrna lewini", "Sphyrna mokarran", "Sphyrna tiburo", "Sphyrna zygaena"], "Sphyrna lewini", 3),
  q("The oceanic whitetip's scientific name is…", ["Carcharhinus longimanus", "Carcharhinus leucas", "Carcharhinus limbatus", "Triaenodon obesus"], "Carcharhinus longimanus", 3),
  q("The sand tiger shark's scientific name is…", ["Carcharias taurus", "Carcharodon carcharias", "Galeocerdo cuvier", "Odontaspis ferox"], "Carcharias taurus", 3),
  q("Lemon sharks belong to the genus…", ["Negaprion", "Prionace", "Triaenodon", "Ginglymostoma"], "Negaprion", 3),
  q("The smalltooth sawfish's scientific name is…", ["Pristis pectinata", "Pristis pristis", "Anoxypristis cuspidata", "Pristiophorus cirratus"], "Pristis pectinata", 3),
  q("The Port Jackson shark belongs to the order…", ["Heterodontiformes", "Orectolobiformes", "Lamniformes", "Squatiniformes"], "Heterodontiformes", 3),
  q("Angel sharks belong to the order…", ["Squatiniformes", "Pristiophoriformes", "Rajiformes", "Hexanchiformes"], "Squatiniformes", 3),
];
