import { q } from "../quiz";
import type { TriviaQ } from "../types";

export const NATURE_MORE: TriviaQ[] = [
  q("A young cat is called a…", ["kitten", "chick", "lamb", "tadpole (then froglet)"], "kitten", 1),
  q("A young dog is called a…", ["duckling", "pup", "owlet", "puppy"], "puppy", 1),
  q("A young horse is called a…", ["cub", "tadpole (then froglet)", "foal", "cygnet"], "foal", 1),
  q("A young cow is called a…", ["kit", "caterpillar (then chrysalis)", "calf", "joey"], "calf", 1),
  q("A young sheep is called a…", ["fawn", "foal", "lamb", "kid"], "lamb", 1),
  q("A young goat is called a…", ["kid", "gosling", "foal", "kit"], "kid", 1),
  q("A young pig is called a…", ["kit", "piglet", "tadpole (then froglet)", "cygnet"], "piglet", 1),
  q("A young bear is called a…", ["cub", "pup", "owlet", "fry / parr / smolt (stages)"], "cub", 1),
  q("A young lion is called a…", ["piglet", "cub", "pup", "kit"], "cub", 1),
  q("A young tiger is called a…", ["gosling", "cub", "pup", "elver (after leptocephalus)"], "cub", 1),
  q("A young wolf is called a…", ["caterpillar (then chrysalis)", "puppy", "piglet", "pup"], "pup", 1),
  q("A young fox is called a…", ["chick", "kit", "elver (after leptocephalus)", "tadpole (then froglet)"], "kit", 1),
  q("A young deer is called a…", ["joey", "chick", "caterpillar (then chrysalis)", "fawn"], "fawn", 1),
  q("A young kangaroo is called a…", ["joey", "chick", "pup", "kitten"], "joey", 1),
  q("A young swan is called a…", ["joey", "elver (after leptocephalus)", "foal", "cygnet"], "cygnet", 1),
  q("A young goose is called a…", ["foal", "cygnet", "calf", "gosling"], "gosling", 1),
  q("A young duck is called a…", ["kit", "duckling", "elver (after leptocephalus)", "gosling"], "duckling", 1),
  q("A young hen is called a…", ["eaglet", "kid", "chick", "owlet"], "chick", 1),
  q("A young owl is called a…", ["fry / parr / smolt (stages)", "foal", "fawn", "owlet"], "owlet", 1),
  q("A young eagle is called a…", ["puppy", "duckling", "lamb", "eaglet"], "eaglet", 1),
  q("A young frog is called a…", ["tadpole (then froglet)", "kit", "cub", "chick"], "tadpole (then froglet)", 1),
  q("A young butterfly is called a…", ["tadpole (then froglet)", "lamb", "foal", "caterpillar (then chrysalis)"], "caterpillar (then chrysalis)", 1),
  q("A young eel is called a…", ["elver (after leptocephalus)", "foal", "cub", "tadpole (then froglet)"], "elver (after leptocephalus)", 1),
  q("A young salmon is called a…", ["fry / parr / smolt (stages)", "calf", "cub", "elver (after leptocephalus)"], "fry / parr / smolt (stages)", 1),
  q("A group of lions is called a…", ["pack", "pride", "smack", "pod"], "pride", 2),
  q("A group of wolves is called a…", ["pack", "pod", "smack", "skein / wedge"], "pack", 2),
  q("A group of crows is called a…", ["herd", "school / shoal", "murder", "flock"], "murder", 2),
  q("A group of geese (on the ground) is called a…", ["gaggle", "swarm / hive", "colony", "mob / troop"], "gaggle", 2),
  q("A group of geese (in flight) is called a…", ["skein / wedge", "flock", "smack", "herd"], "skein / wedge", 2),
  q("A group of fish is called a…", ["herd", "pod", "flock", "school / shoal"], "school / shoal", 2),
  q("A group of whales is called a…", ["herd", "flock", "gaggle", "pod"], "pod", 2),
  q("A group of bees is called a…", ["flock", "parliament", "swarm / hive", "ostentation"], "swarm / hive", 2),
  q("A group of ants is called a…", ["flock", "pod", "pack", "colony"], "colony", 2),
  q("A group of cows is called a…", ["pod", "herd", "ostentation", "parliament"], "herd", 2),
  q("A group of sheep is called a…", ["ostentation", "pride", "flock", "parliament"], "flock", 2),
  q("A group of birds (general) is called a…", ["herd", "mob / troop", "murder", "flock"], "flock", 2),
  q("A group of ravens is called a…", ["pack", "herd", "pod", "unkindness"], "unkindness", 2),
  q("A group of peacocks is called a…", ["ostentation", "herd", "flock", "romp / raft"], "ostentation", 2),
  q("A group of porpoises is called a…", ["swarm / hive", "unkindness", "flock", "pod"], "pod", 2),
  q("A group of kangaroos is called a…", ["mob / troop", "smack", "skein / wedge", "school / shoal"], "mob / troop", 2),
  q("A group of baboons is called a…", ["pride", "troop", "swarm / hive", "mob / troop"], "troop", 2),
  q("A group of otters is called a…", ["swarm / hive", "romp / raft", "pod", "skein / wedge"], "romp / raft", 2),
  q("A group of jellyfish is called a…", ["colony", "pack", "smack", "flock"], "smack", 2),
  q("The coast redwood is native chiefly to…", ["China (wild remnant)", "tropical coasts", "southeastern U.S. wetlands", "California"], "California", 2),
  q("The giant sequoia is native chiefly to…", ["the U.S. South / live-oak belt", "California (Sierra)", "Australia", "African savanna"], "California (Sierra)", 2),
  q("The baobab (African) is native chiefly to…", ["African savanna", "China (wild remnant)", "the U.S. South / live-oak belt", "the Great Basin / western U.S."], "African savanna", 2),
  q("The kauri is native chiefly to…", ["northeastern North America", "New Zealand", "western North America", "the Mediterranean"], "New Zealand", 2),
  q("The banyan is native chiefly to…", ["northern forests", "southeastern U.S. wetlands", "South Asia", "Pacific Northwest"], "South Asia", 2),
  q("The bristlecone pine is native chiefly to…", ["tropical coasts", "New Zealand", "the Great Basin / western U.S.", "northeastern North America"], "the Great Basin / western U.S.", 2),
  q("The Douglas fir is native chiefly to…", ["China", "Pacific Northwest", "western North America", "northeastern North America"], "western North America", 2),
  q("The Sitka spruce is native chiefly to…", ["China (wild remnant)", "Australia", "Pacific Northwest", "South Asia"], "Pacific Northwest", 2),
  q("The white birch is native chiefly to…", ["Pacific Northwest", "northern forests", "the U.S. South / live-oak belt", "southeastern U.S. wetlands"], "northern forests", 2),
  q("The sugar maple is native chiefly to…", ["California", "Australia", "the Mediterranean", "northeastern North America"], "northeastern North America", 2),
  q("The live oak is native chiefly to…", ["northeastern North America", "China", "the U.S. South / live-oak belt", "southeastern U.S. wetlands"], "the U.S. South / live-oak belt", 2),
  q("The saguaro is native chiefly to…", ["the Sonoran Desert", "Pacific Northwest", "the U.S. South / live-oak belt", "northern forests"], "the Sonoran Desert", 2),
  q("The Joshua tree is native chiefly to…", ["western Mediterranean", "Australia", "the Mojave", "South Asia"], "the Mojave", 2),
  q("The mangrove (as a guild) is native chiefly to…", ["African savanna", "tropical coasts", "China (wild remnant)", "Australia"], "tropical coasts", 2),
  q("The cypress of the swamps is native chiefly to…", ["China (wild remnant)", "southeastern U.S. wetlands", "the Mediterranean", "Australia"], "southeastern U.S. wetlands", 2),
  q("The olive is native chiefly to…", ["China (wild remnant)", "Pacific Northwest", "western Mediterranean", "the Mediterranean"], "the Mediterranean", 2),
  q("The cork oak is native chiefly to…", ["western Mediterranean", "the Sonoran Desert", "Australia", "New Zealand"], "western Mediterranean", 2),
  q("The ginkgo is native chiefly to…", ["tropical coasts", "China (wild remnant)", "California (Sierra)", "northeastern North America"], "China (wild remnant)", 2),
  q("The dawn redwood is native chiefly to…", ["southeastern U.S. wetlands", "the Mojave", "China", "California"], "China", 2),
  q("The eucalyptus (many species) is native chiefly to…", ["western North America", "Australia", "the U.S. South / live-oak belt", "China (wild remnant)"], "Australia", 2),
  q("A carnivore eats…", ["only plants", "animals", "only wood", "only nectar"], "animals", 1),
  q("A herbivore eats…", ["only meat", "plants", "only fungi", "only clay"], "plants", 1),
  q("An omnivore eats…", ["only plants", "only meat", "plants and animals", "only insects"], "plants and animals", 1),
  q("A detritivore eats…", ["only live prey", "dead organic matter", "only sunlight", "only stone"], "dead organic matter", 2),
  q("A parasite lives…", ["only as a mutual friend", "on or in a host, at the host's expense", "only on rocks with no host", "only as a predator that always kills at once as the definition"], "on or in a host, at the host's expense", 2),
  q("Mutualism is a relation that…", ["hurts both", "helps both partners", "helps one and hurts the other as the name", "has no effect"], "helps both partners", 2),
  q("Commensalism helps one partner and…", ["kills the other as the name", "does not much affect the other", "helps the other equally as mutualism's name", "is always predation"], "does not much affect the other", 3),
  q("A keystone predator can…", ["never eat", "structure a whole community by what it eats", "only live in zoos", "only eat fruit"], "structure a whole community by what it eats", 3),
  q("An invasive species is…", ["always native", "non-native and harmful in its new range", "always extinct", "always a pet"], "non-native and harmful in its new range", 1),
  q("An endemic species lives…", ["everywhere on Earth", "only in a particular place", "only in labs", "only in the ocean as the word's meaning"], "only in a particular place", 2),
  q("Extinct means…", ["rare", "no living members", "only in zoos as the definition", "only nocturnal"], "no living members", 1),
  q("Endangered means…", ["already gone", "at high risk of extinction", "overabundant", "newly described only"], "at high risk of extinction", 1),
  q("A biome is a…", ["single organism", "large community type (forest, tundra, desert…)", "gene", "cloud"], "large community type (forest, tundra, desert…)", 1),
  q("Tundra is…", ["tropical rainforest", "cold, treeless, often with permafrost", "hot desert only as a synonym", "coral reef"], "cold, treeless, often with permafrost", 1),
  q("Taiga is…", ["tropical grassland", "boreal conifer forest", "mangrove", "chaparral only"], "boreal conifer forest", 2),
  q("Chaparral is a…", ["rainforest", "shrubland of Mediterranean climates", "ice cap", "mangrove swamp"], "shrubland of Mediterranean climates", 3),
  q("Temperate deciduous forest drops leaves in…", ["only the dry season of the tropics as a rule of this biome", "autumn", "every full moon", "never"], "autumn", 1),
  q("A rainforest has…", ["almost no rain", "high rainfall and typically high diversity", "only ice", "only grass and no trees as the name"], "high rainfall and typically high diversity", 1),
  q("The canopy is the…", ["soil only", "upper layer of a forest", "a river", "a cloud type only as ecology's word"], "upper layer of a forest", 1),
  q("The understory is…", ["outer space", "the layer under the canopy", "the ocean floor always", "a desert pavement"], "the layer under the canopy", 2),
  q("Epiphytes grow…", ["only as root parasites always", "on other plants, not as parasites necessarily", "only underwater as kelp", "only on ice"], "on other plants, not as parasites necessarily", 3),
  q("A succulent plant stores…", ["only salt", "water in thick tissues", "only air in wood", "only light as sugar in the name"], "water in thick tissues", 1),
  q("C4 and CAM photosynthesis are adaptations to…", ["only the deep sea", "hot / dry or intense-light climates (among uses)", "only polar night", "only caves"], "hot / dry or intense-light climates (among uses)", 3),
  q("Nitrogen-fixing bacteria often live with…", ["cacti only", "legumes", "conifers only as the famous nodules", "ferns only"], "legumes", 2),
  q("Mycorrhizae are…", ["virus–leaf diseases only", "fungus–root partnerships", "insect galls only", "lichen of rock only as this word"], "fungus–root partnerships", 3),
  q("A lichen is a partnership of…", ["two mammals", "fungus and alga (or cyanobacterium)", "two birds", "a fish and a shark only"], "fungus and alga (or cyanobacterium)", 2),
  q("Coral bleaching is often from…", ["too much extra coral growth as the name", "stress (especially heat) expelling algae", "only extra fish", "only moonlight"], "stress (especially heat) expelling algae", 2),
  q("Kelp forests grow in…", ["deserts", "cool coastal seas", "the high Himalaya", "freshwater ponds only"], "cool coastal seas", 2),
  q("Phytoplankton are…", ["whales", "tiny drifting photosynthesizers", "only corals", "only kelp as large trees"], "tiny drifting photosynthesizers", 2),
  q("Krill are…", ["tiny whales", "small crustaceans, key in polar seas", "seaweeds", "penguins"], "small crustaceans, key in polar seas", 2),
  q("Baleen whales feed with…", ["teeth only as all whales", "comb-like baleen plates", "beaks like birds", "hands"], "comb-like baleen plates", 2),
  q("Toothed whales include…", ["blue whales", "dolphins, orcas, sperm whales", "humpbacks as toothed", "right whales as toothed"], "dolphins, orcas, sperm whales", 2),
  q("Echolocation is used by…", ["only earthworms", "bats and toothed whales (among others)", "only birds of paradise", "only snakes as a rule"], "bats and toothed whales (among others)", 2),
  q("A nocturnal animal is active at…", ["noon only", "night", "only dawn as the word", "only winter"], "night", 1),
  q("A crepuscular animal is active at…", ["noon", "dawn and dusk", "midnight only", "only in hibernation"], "dawn and dusk", 2),
  q("Hibernation is a…", ["daily sleep of all mammals as this word", "seasonal torpor in winter (in the popular sense)", "migration", "molting only"], "seasonal torpor in winter (in the popular sense)", 1),
  q("Migration is a…", ["one afternoon nap", "seasonal long-distance movement", "changing color only", "growing a new shell only"], "seasonal long-distance movement", 1),
  q("Camouflage helps an animal…", ["stand out always as the word", "blend in", "sing", "hibernate as the word"], "blend in", 1),
  q("Mimicry is looking like…", ["your parent only as genetics", "something else, often dangerous or inedible", "the weather", "a biome"], "something else, often dangerous or inedible", 2),
  q("Aposematic colors often…", ["hide it in leaves", "warn that an animal is toxic or fierce", "are only for attracting mates as the word", "are always brown"], "warn that an animal is toxic or fierce", 3),
  q("The red-spotted newt's eft is…", ["a fish", "a toxic, brightly colored juvenile on land", "a bird", "a mushroom"], "a toxic, brightly colored juvenile on land", 3),
  q("Amphibians typically have…", ["feathers", "moist skin and a life tied to water", "hair and milk", "dry scales and eggs on land as the only story of frogs"], "moist skin and a life tied to water", 1),
  q("Reptile eggs on land are…", ["jelly masses only like frogs always", "amniotic", "never shelled in any reptile", "always laid in the sea"], "amniotic", 3),
  q("Monotremes lay eggs and include…", ["kangaroos", "the platypus and echidnas", "whales", "armadillos only"], "the platypus and echidnas", 2),
  q("Marsupials raise young in a…", ["nest of sticks only", "pouch (typically)", "hive", "shell"], "pouch (typically)", 1),
  q("The opossum is a…", ["monotreme", "marsupial of the Americas", "placental cat", "primate"], "marsupial of the Americas", 2),
  q("The koala eats…", ["bamboo only", "eucalyptus leaves (chiefly)", "fish", "nectar only"], "eucalyptus leaves (chiefly)", 1),
  q("The giant panda eats…", ["eucalyptus", "bamboo (chiefly)", "krill", "ants only"], "bamboo (chiefly)", 1),
  q("The sloth lives in…", ["the tundra", "Neotropical trees", "the Sahara", "Antarctica"], "Neotropical trees", 1),
  q("The capybara is the world's largest…", ["cat", "rodent", "bat", "marsupial"], "rodent", 2),
  q("The blue whale is the…", ["smallest cetacean", "largest animal known", "fastest fish", "tallest tree"], "largest animal known", 1),
  q("The cheetah is the…", ["slowest sloth as this title", "fastest land animal (sprint)", "largest cat always", "only nocturnal cat"], "fastest land animal (sprint)", 1),
  q("The peregrine falcon is famed as a…", ["flightless bird", "fast stooping bird", "largest eagle always", "penguin"], "fast stooping bird", 2),
  q("The ostrich is a…", ["flying hawk", "flightless bird of Africa", "penguin of the Arctic", "parrot of New Zealand only"], "flightless bird of Africa", 1),
  q("The kiwi is a…", ["parrot of Australia", "flightless bird of New Zealand", "eagle of North America", "penguin of Africa"], "flightless bird of New Zealand", 2),
  q("The dodo was a…", ["living eagle of Europe", "extinct flightless bird of Mauritius", "penguin of Antarctica", "parrot of New Zealand still living"], "extinct flightless bird of Mauritius", 1),
  q("Passenger pigeons were…", ["European garden birds still common", "once-abundant North American birds, now extinct", "Antarctic penguins", "African ostriches"], "once-abundant North American birds, now extinct", 2),
  q("The ivory-billed woodpecker is…", ["a common backyard feeder bird of cities worldwide", "critically endangered or extinct (status debated)", "a penguin", "a European robin"], "critically endangered or extinct (status debated)", 3),
  q("Rachel Carson's Silent Spring warned about…", ["only nuclear war", "pesticides (especially DDT) and wildlife", "only overfishing of whales as the book's sole topic", "only climate models of the 2000s"], "pesticides (especially DDT) and wildlife", 2),
  q("DDT thinned the eggshells of…", ["only worms", "birds of prey (among others)", "only sharks", "only kelp"], "birds of prey (among others)", 2),
  q("The Endangered Species Act is a law of the…", ["UN only as a treaty of this name", "United States", "EU only as this Act's name", "Brazil only"], "United States", 2),
  q("CITES regulates…", ["only local zoning", "international trade in wildlife", "only weather", "only mining of coal"], "international trade in wildlife", 3),
  q("A watershed is the land that…", ["only sits above treeline", "drains to a river or lake", "is always a desert", "is the ocean floor"], "drains to a river or lake", 2),
  q("An aquifer is…", ["a cloud", "underground water-bearing rock or sediment", "a glacier on a peak always as this word", "a tide"], "underground water-bearing rock or sediment", 2),
  q("Permafrost is…", ["seasonal snow only", "ground frozen for years", "a kind of cloud", "warm sand"], "ground frozen for years", 1),
  q("A glacier is…", ["a frozen lake that never moves as the definition", "ice that moves under its weight", "only sea ice", "only frost on a window"], "ice that moves under its weight", 1),
  q("Calving of a glacier is…", ["growing trees on ice", "breaking off icebergs", "melting into rain only", "turning to permafrost"], "breaking off icebergs", 2),
  q("An iceberg is…", ["sea ice as the only name", "floating glacier ice", "a cloud", "a salt dome"], "floating glacier ice", 1),
  q("Pack ice is…", ["glacier ice on a mountain", "sea ice", "river ice only", "frost"], "sea ice", 2),
  q("The timberline is…", ["the ocean shore always", "the elevation or latitude beyond which trees do not grow", "a political border", "a river"], "the elevation or latitude beyond which trees do not grow", 2),
  q("A riparian zone is…", ["on a glacier", "along a river", "in a desert far from water as the word", "on a peak"], "along a river", 1),
  q("An estuary mixes…", ["only two glaciers", "fresh water and the sea", "only two deserts", "magma and air"], "fresh water and the sea", 1),
  q("A wetland might be a…", ["only a dune", "marsh, swamp, bog, or fen", "only a cliff", "only a lava field"], "marsh, swamp, bog, or fen", 1),
  q("A bog is often…", ["a salt lagoon always", "acid, peat-forming, fed by rain", "a coral atoll", "a geyser basin only"], "acid, peat-forming, fed by rain", 3),
  q("A fen is a peatland that is…", ["always a salt marsh", "less acid, fed by groundwater", "a desert pavement", "a lava tube"], "less acid, fed by groundwater", 3),
  q("A swamp has…", ["only grass and no trees as the swamp's definition", "trees in standing water (typically)", "only ice", "only dunes"], "trees in standing water (typically)", 2),
  q("A marsh has…", ["a closed canopy of mahogany as the name", "grasses and reeds, few trees", "only cacti", "only moss on peaks"], "grasses and reeds, few trees", 2),
  q("Peat is…", ["pure coal always as a synonym at the surface", "partly decayed plant matter", "lava", "pure sand"], "partly decayed plant matter", 2),
  q("Coal formed from…", ["only dinosaur bones", "ancient plant matter under heat and pressure", "only evaporating seas as salt", "only volcanic glass"], "ancient plant matter under heat and pressure", 2),
  q("Petroleum formed chiefly from…", ["only dinosaur flesh as the schoolyard story", "ancient plankton and organic muds", "only granite", "only rain"], "ancient plankton and organic muds", 2),
  q("Natural gas is often found with…", ["only glaciers", "oil", "only the ozone layer", "only granite plutons"], "oil", 1),
  q("The carbon cycle includes…", ["only the water cycle as a synonym", "photosynthesis, respiration, ocean uptake, and fossil fuels", "only the rock cycle of granite", "only tides"], "photosynthesis, respiration, ocean uptake, and fossil fuels", 2),
  q("The nitrogen cycle depends on…", ["only lightning as the whole cycle", "microbes that fix, nitrify, and denitrify", "only birds", "only granite weathering as the whole cycle"], "microbes that fix, nitrify, and denitrify", 3),
  q("Eutrophication is…", ["a kind of drought", "over-enrichment of water, often causing algal blooms", "a kind of earthquake", "a kind of cloud"], "over-enrichment of water, often causing algal blooms", 3),
  q("A dead zone in the sea is often from…", ["too many coral as the name", "low oxygen after nutrient pollution", "too much ice", "too many whales"], "low oxygen after nutrient pollution", 3),
  q("Bycatch is…", ["a kind of bait", "unwanted catch in fishing gear", "a kind of seaweed farm", "a kind of bird song"], "unwanted catch in fishing gear", 2),
  q("A keystone of kelp forests on the North American Pacific is often the…", ["camel", "sea otter (among others)", "lion", "penguin of the Arctic"], "sea otter (among others)", 2),
  q("Sea otters eat…", ["kelp as their main diet", "urchins, among other invertebrates", "only krill", "only fish as a cat would"], "urchins, among other invertebrates", 2),
  q("Urchins, unchecked, can…", ["plant kelp", "graze kelp to barrens", "build coral", "fix nitrogen on land"], "graze kelp to barrens", 3),
  q("Beavers are…", ["desert antelope", "ecosystem engineers of streams", "marine mammals of the open ocean", "flightless birds"], "ecosystem engineers of streams", 1),
  q("A lodge of a beaver is a…", ["nest in a tree cavity only", "house of sticks and mud", "hive", "burrow in dry sand only"], "house of sticks and mud", 1),
  q("Prairie dogs live in…", ["the deep sea", "colonies of burrows on grasslands", "the high canopy of rainforests", "Antarctica"], "colonies of burrows on grasslands", 1),
  q("Bison are native to…", ["Australia", "North American grasslands (and a European cousin)", "Antarctica", "Madagascar only"], "North American grasslands (and a European cousin)", 1),
  q("The passenger of the Great Plains' horse culture included the…", ["only whale hunt of the plains", "bison hunt", "only seal hunt", "only penguin hunt"], "bison hunt", 2),
  q("Fire on many prairies and pine savannas is…", ["always a disaster with no ecology", "a natural and cultural process that maintains the system", "impossible because grass cannot burn", "only from lightning in rainforests as the only fire ecology"], "a natural and cultural process that maintains the system", 3),
  q("Serotinous cones open with…", ["only frost", "heat / fire", "only moonlight", "only flood of the sea"], "heat / fire", 3),
  q("A nurse log is a…", ["living doctor of the forest as an animal", "fallen tree that seedlings grow on", "kind of fungus only", "kind of cloud"], "fallen tree that seedlings grow on", 2),
  q("Old-growth forest has…", ["only seedlings in rows", "large old trees, snags, and complex structure", "only grass", "only ice"], "large old trees, snags, and complex structure", 2),
  q("A snag is a…", ["fallen log only as this word", "standing dead tree", "seedling", "vine"], "standing dead tree", 2),
  q("The spotted owl is associated with…", ["the Sahara", "old forests of the Pacific Northwest (among other owls)", "Antarctic ice", "coral atolls"], "old forests of the Pacific Northwest (among other owls)", 3),
  q("The whooping crane was saved in part by…", ["introducing cats to nests", "captive breeding and habitat protection", "draining all wetlands", "banning all flyways of other birds only"], "captive breeding and habitat protection", 2),
  q("The California condor was brought back by…", ["only hope with no program", "captive breeding", "introducing DDT", "hunting bounties"], "captive breeding", 2),
  q("Island species often evolve…", ["faster wings always and no risk", "in isolation and are vulnerable to invaders", "only as fish", "only as whales"], "in isolation and are vulnerable to invaders", 2),
  q("Darwin's finches of the Galápagos show…", ["identical beaks on all islands", "beak shapes matching foods", "that birds cannot evolve", "that all finches eat only fish"], "beak shapes matching foods", 2),
  q("The Galápagos are in the…", ["Atlantic off Africa", "Pacific, off Ecuador", "Indian Ocean off India", "Arctic"], "Pacific, off Ecuador", 2),
  q("Madagascar is famed for…", ["kangaroos as natives", "lemurs and other endemic lineages", "polar bears", "penguins of the north"], "lemurs and other endemic lineages", 1),
  q("New Zealand had no native…", ["birds", "land mammals except bats (before humans)", "insects", "plants"], "land mammals except bats (before humans)", 3),
  q("Australia's native mammals are mostly…", ["only primates", "marsupials and monotremes (plus bats and rodents)", "only ungulates of Africa as natives", "only marine otters"], "marsupials and monotremes (plus bats and rodents)", 2),
  q("The duck-billed platypus is a…", ["marsupial kangaroo", "monotreme that lays eggs and hunts in water", "placental otter of Europe", "bird"], "monotreme that lays eggs and hunts in water", 2),
  q("Echidnas eat…", ["eucalyptus only", "ants and termites (chiefly)", "krill", "bamboo"], "ants and termites (chiefly)", 2),
];

