import { q } from "../quiz";
import type { TriviaQ } from "../types";

export const NATURE_LIFE: TriviaQ[] = [
  q("Tarantulas belong to which spider family?", ["Lycosidae", "Theraphosidae", "Salticidae", "Araneidae"], "Theraphosidae", 2),
  q("Tarantulas are in the infraorder…", ["Araneomorphae", "Mygalomorphae", "Opiliones", "Scorpiones"], "Mygalomorphae", 3),
  q("A tarantula is a…", ["insect", "spider (arachnid)", "crustacean", "myriapod"], "spider (arachnid)", 1),
  q("How many legs does a tarantula have?", ["6", "8", "10", "12"], "8", 1),
  q("A tarantula's two main body tagmata are the cephalothorax and the…", ["tail", "abdomen (opisthosoma)", "elytra", "mantle"], "abdomen (opisthosoma)", 1),
  q("The narrow waist joining a tarantula's body parts is the…", ["petiole of an ant", "pedicel", "scape", "telson"], "pedicel", 2),
  q("Tarantula fangs are on the…", ["pedipalps only", "chelicerae", "spinnerets", "book lungs"], "chelicerae", 2),
  q("Mygalomorph fangs strike…", ["sideways like a crab's claw always", "down and parallel (not pincer-style)", "backward only", "up through the cephalothorax"], "down and parallel (not pincer-style)", 3),
  q("A tarantula breathes with…", ["a tracheal tube like a beetle only", "book lungs", "gills", "a diaphragm"], "book lungs", 2),
  q("Most tarantulas have how many pairs of book lungs?", ["one pair", "two pairs", "three pairs", "none — they use spiracles only"], "two pairs", 3),
  q("Silk in a tarantula comes from…", ["the fangs", "spinnerets", "the book lungs", "the eyes"], "spinnerets", 1),
  q("A tarantula typically has how many eyes?", ["2", "4", "6", "8"], "8", 2),
  q("The 'hands' in front of a tarantula's legs are…", ["antennae", "pedipalps", "maxillae", "cerci"], "pedipalps", 2),
  q("Tarantulas grow by…", ["adding bone", "molting (ecdysis)", "budding", "shedding only hair"], "molting (ecdysis)", 1),
  q("A fresh molt leaves behind an…", ["egg sac only", "exuvium (shed skin)", "sperm web only", "book lung"], "exuvium (shed skin)", 2),
  q("Before a molt a tarantula often…", ["spins a bird nest", "goes off food and darkens", "loses all legs as a rule", "turns bright green always"], "goes off food and darkens", 2),
  q("A 'bald butt' on a New World tarantula usually means it has…", ["just drunk water", "kicked urticating hairs", "laid eggs", "lost its spinnerets"], "kicked urticating hairs", 1),
  q("Urticating hairs are…", ["venom crystals", "barbed defensive bristles, mostly on the abdomen", "silk strands", "book-lung plates"], "barbed defensive bristles, mostly on the abdomen", 2),
  q("Most New World tarantulas defend first by…", ["spraying acid", "kicking urticating hairs", "playing dead as the only trick", "ink like a squid"], "kicking urticating hairs", 1),
  q("Old World tarantulas generally…", ["kick the worst hairs", "lack urticating hairs", "have no venom", "have six legs"], "lack urticating hairs", 1),
  q("New World tarantulas are native to…", ["Africa and Asia only", "the Americas", "Australia only", "Europe only"], "the Americas", 1),
  q("Old World tarantulas are native to…", ["only the Amazon", "Africa, Asia, and Australia (among other eastern lands)", "only Mexico", "only the Caribbean"], "Africa, Asia, and Australia (among other eastern lands)", 1),
  q("Old World tarantulas are often…", ["slower and hair-kicking", "faster and more defensive", "unable to bite", "blind"], "faster and more defensive", 2),
  q("A threat pose in a tarantula is…", ["rolling into a ball only", "rearing and showing fangs", "flashing wings", "playing a silk drum only"], "rearing and showing fangs", 1),
  q("Stridulation in tarantulas is a…", ["bird call", "hiss or rasp from bristles", "color change", "light flash"], "hiss or rasp from bristles", 2),
  q("Hobby keepers call a baby tarantula a…", ["nymph", "sling (spiderling)", "pupa", "calf"], "sling (spiderling)", 1),
  q("The stage between molts is an…", ["imago only in spiders as this word", "instar", "chrysalis", "tadpole"], "instar", 2),
  q("An adult male tarantula often has…", ["wings", "bulbed pedipalps (emboli) and a shorter life", "no fangs", "a stinger"], "bulbed pedipalps (emboli) and a shorter life", 2),
  q("Tibial hooks on many male tarantulas help…", ["dig only", "hold the female during mating", "kick hairs", "spin silk"], "hold the female during mating", 3),
  q("A male tarantula charges his palps from a…", ["book lung", "sperm web", "egg sac", "water dish"], "sperm web", 3),
  q("Females store sperm in…", ["the spinnerets", "spermathecae", "the eyes", "the fangs"], "spermathecae", 3),
  q("Eggs are guarded in a…", ["mud nest of a wasp", "silken egg sac", "foam raft", "hollow bone"], "silken egg sac", 1),
  q("Female tarantulas typically live…", ["only weeks as a rule", "many years longer than males", "the same few months as males always", "one season like a mayfly"], "many years longer than males", 1),
  q("Some female terrestrial tarantulas can live…", ["about a year always", "20–30+ years in captivity", "a weekend", "as long as a mayfly"], "20–30+ years in captivity", 2),
  q("A fossorial tarantula is a…", ["tree-dweller only", "burrower", "swimmer", "parasite of mammals"], "burrower", 2),
  q("An arboreal tarantula lives…", ["only in deep desert burrows as the word", "in trees / off the ground, often in silk tubes", "only in the deep sea", "only in caves of ice"], "in trees / off the ground, often in silk tubes", 1),
  q("A terrestrial beginner tank should not be too…", ["dark", "tall (falls can split the abdomen)", "equipped with a water dish", "equipped with soil"], "tall (falls can split the abdomen)", 2),
  q("Keepers usually give a tarantula a…", ["salt block", "shallow water dish", "cuttlebone only", "UVB lamp as a must for all species"], "shallow water dish", 1),
  q("Tarantulas eat chiefly…", ["leaves", "invertebrates (crickets, roaches, worms…)", "nectar only", "blood of mammals as the only diet"], "invertebrates (crickets, roaches, worms…)", 1),
  q("Despite the name, 'bird-eating' tarantulas mostly eat…", ["only birds every day", "large invertebrates (vertebrates are rare treats)", "only fruit", "only fish"], "large invertebrates (vertebrates are rare treats)", 2),
  q("The largest tarantula by mass is generally…", ["a jumping spider", "Theraphosa blondi (Goliath birdeater)", "a harvestman", "a house spider"], "Theraphosa blondi (Goliath birdeater)", 2),
  q("Theraphosa blondi is native to…", ["the Kalahari", "northern South America (Amazonian rainforests)", "the Gobi", "Alaska"], "northern South America (Amazonian rainforests)", 2),
  q("The Goliath birdeater is famed for…", ["having no fangs", "huge size and strong urticating hairs", "living in the Arctic", "being an Old World species of Africa"], "huge size and strong urticating hairs", 2),
  q("Chromatopelma cyaneopubescens is the…", ["OBT", "green bottle blue (GBB)", "curly hair", "red knee"], "green bottle blue (GBB)", 1),
  q("The green bottle blue is native to…", ["Madagascar", "Venezuela (Paraguaná Peninsula)", "Japan", "New Zealand"], "Venezuela (Paraguaná Peninsula)", 2),
  q("A GBB is famous in the hobby for…", ["having no silk", "electric blue legs, orange abdomen, and heavy webbing", "living under ice", "being an Old World baboon"], "electric blue legs, orange abdomen, and heavy webbing", 2),
  q("Brachypelma hamorii is the classic…", ["pinktoe of Martinique", "Mexican red-knee of the pet trade", "Gooty ornamental", "Socotra blue"], "Mexican red-knee of the pet trade", 2),
  q("Brachypelma species are native to…", ["Australia", "Mexico (and nearby dry tropical lands)", "Congo only", "Siberia"], "Mexico (and nearby dry tropical lands)", 2),
  q("Many Brachypelma species are listed on…", ["only the U.S. flag code", "CITES (international trade rules)", "FIFA", "NATO"], "CITES (international trade rules)", 3),
  q("Tliltocatl albopilosus is the hobby…", ["GBB", "curly hair", "OBT", "sun tiger"], "curly hair", 2),
  q("The curly hair was moved out of Brachypelma into…", ["Poecilotheria", "Tliltocatl", "Theraphosa", "Pterinochilus"], "Tliltocatl", 3),
  q("Tliltocatl vagans is the…", ["Chilean rose", "Mexican red rump", "Togo starburst", "Gooty"], "Mexican red rump", 2),
  q("Grammostola pulchra is the…", ["pinktoe", "Brazilian black", "baboon", "ornamental of India"], "Brazilian black", 2),
  q("Grammostola pulchra is prized as a…", ["fast Old World arboreal", "slow, velvety-black beginner terrestrial", "fish-eating sea spider", "scorpion"], "slow, velvety-black beginner terrestrial", 2),
  q("The Chilean rose hair of the pet trade is a…", ["Poecilotheria", "Grammostola (rosea / porteri complex)", "Heteroscodra", "Ceratogyrus"], "Grammostola (rosea / porteri complex)", 3),
  q("Aphonopelma chalcodes is a tarantula of the…", ["Congo Basin", "U.S. Southwest / Sonoran region", "Siberia", "New Zealand"], "U.S. Southwest / Sonoran region", 2),
  q("Aphonopelma is the main native tarantula genus of the…", ["Madagascar only", "United States", "Japan only", "Ireland"], "United States", 2),
  q("Lasiodora parahybana is the…", ["curly hair", "salmon pink birdeater", "red knee", "sun tiger"], "salmon pink birdeater", 2),
  q("Lasiodora parahybana is native to…", ["India", "Brazil", "South Africa", "Spain"], "Brazil", 2),
  q("Caribena versicolor is the…", ["OBT", "Antilles / Martinique pinktoe", "horned baboon", "earth tiger"], "Antilles / Martinique pinktoe", 2),
  q("Caribena versicolor slings are famously…", ["bright red always", "metallic blue before they color up", "patterned like a wasp", "transparent"], "metallic blue before they color up", 3),
  q("Avicularia-group pinktoes are…", ["Old World burrowers", "New World arboreals", "African baboons", "desert blondes of Arizona only"], "New World arboreals", 2),
  q("Psalmopoeus irminia is the…", ["Brazilian black", "Venezuelan suntiger", "curly hair", "red knee"], "Venezuelan suntiger", 2),
  q("Psalmopoeus cambridgei is associated with…", ["Madagascar", "Trinidad", "Japan", "Alaska"], "Trinidad", 3),
  q("Psalmopoeus are New World arboreals that typically…", ["live only in the Gobi", "do not kick a cloud of abdominal hairs the way Theraphosinae do", "have no venom", "are fish"], "do not kick a cloud of abdominal hairs the way Theraphosinae do", 3),
  q("Ephebopus species are unusual New World tarantulas because some have…", ["wings", "urticating hairs on the palps", "a stinger", "only six legs"], "urticating hairs on the palps", 3),
  q("Type II urticating hairs (Avicularia group) are often…", ["used to build webs only", "transferred by contact rather than kicked as a cloud", "venom crystals", "found only on Old World species"], "transferred by contact rather than kicked as a cloud", 3),
  q("Poecilotheria are the…", ["pinktoes of Brazil", "ornamental tarantulas of India and Sri Lanka", "desert blondes of Arizona", "hornless harvestmen"], "ornamental tarantulas of India and Sri Lanka", 2),
  q("Poecilotheria are…", ["slow Mexican terrestrials", "Old World arboreals with strong venom and no kicking hairs", "sea spiders", "scorpions"], "Old World arboreals with strong venom and no kicking hairs", 2),
  q("Poecilotheria metallica is the…", ["red rump", "Gooty ornamental", "curly hair", "salmon pink"], "Gooty ornamental", 2),
  q("Pterinochilus murinus is the hobby…", ["GBB", "OBT (orange baboon tarantula)", "pinktoe", "red knee"], "OBT (orange baboon tarantula)", 2),
  q("Pterinochilus murinus is native to…", ["Mexico", "East Africa", "Chile", "Florida only as a native"], "East Africa", 2),
  q("An 'OBT' is widely treated as…", ["a perfect first-handling species", "an advanced, defensive Old World terrestrial", "a fish", "a millipede"], "an advanced, defensive Old World terrestrial", 2),
  q("Ceratogyrus species are African tarantulas nicknamed…", ["pinktoes", "horned baboons", "red knees", "curly hairs"], "horned baboons", 2),
  q("The 'horn' on some Ceratogyrus is on the…", ["spinnerets", "carapace (fovea)", "fangs only", "each tarsus"], "carapace (fovea)", 3),
  q("Heteroscodra maculata is the…", ["Chilean rose", "Togo starburst", "Brazilian black", "desert blonde"], "Togo starburst", 3),
  q("Heteroscodra maculata is a…", ["slow Mexican red-knee", "fast African arboreal", "Arizona desert blonde", "Martinique pinktoe"], "fast African arboreal", 3),
  q("Monocentropus balfouri is the…", ["Gooty ornamental", "Socotra Island blue", "OBT", "GBB"], "Socotra Island blue", 3),
  q("Socotra, home of M. balfouri, is in the…", ["Caribbean", "northwest Indian Ocean (Yemen)", "Great Lakes", "Baltic"], "northwest Indian Ocean (Yemen)", 3),
  q("Asian 'earth tiger' tarantulas are often in…", ["Aphonopelma", "Cyriopagopus / related Ornithoctoninae", "Grammostola", "Tliltocatl"], "Cyriopagopus / related Ornithoctoninae", 3),
  q("Haplopelma / Cyriopagopus are…", ["Arizona desert blondes", "Old World fossorials of Southeast Asia", "Martinique pinktoes", "Chilean roses"], "Old World fossorials of Southeast Asia", 3),
  q("A 'baboon' tarantula in hobby talk is usually…", ["a Mexican red-knee", "an African Old World theraphosid", "a GBB", "a curly hair"], "an African Old World theraphosid", 2),
  q("A 'pinktoe' in hobby talk is usually…", ["an OBT", "an arboreal Avicularia / Caribena type", "a horned baboon", "a Gooty"], "an arboreal Avicularia / Caribena type", 2),
  q("A 'birdeater' in hobby talk is often…", ["a jumping spider of a house", "a huge South American terrestrial (Theraphosa, Lasiodora…)", "a scorpion", "a millipede"], "a huge South American terrestrial (Theraphosa, Lasiodora…)", 2),
  q("The tarantula hawk is a…", ["bird that only eats silk", "wasp that hunts tarantulas", "beetle that farms aphids", "moth"], "wasp that hunts tarantulas", 1),
  q("A tarantula hawk wasp lays an egg on a…", ["leaf only", "paralyzed tarantula", "rotten log only", "pond"], "paralyzed tarantula", 2),
  q("Tarantulas are not…", ["arachnids", "insects", "spiders", "mygalomorphs"], "insects", 1),
  q("Unlike insects, spiders lack…", ["an exoskeleton", "antennae (and have eight legs)", "a brain of any kind", "eyes of any kind"], "antennae (and have eight legs)", 2),
  q("Scopulae on tarantula feet are…", ["stingers", "pads of fine hairs that help grip", "book lungs", "egg teeth"], "pads of fine hairs that help grip", 3),
  q("Trichobothria are…", ["venom ducts", "fine sensory hairs that detect air movement", "silk glands", "fangs"], "fine sensory hairs that detect air movement", 3),
  q("A tarantula's 'baldness' after kicking hairs will look better after…", ["drinking oil", "the next molt", "a salt bath", "losing a leg"], "the next molt", 1),
  q("Lost legs in tarantulas can be…", ["never replaced", "regrown over subsequent molts (especially in younger animals)", "replaced by silk props", "replaced by extra spinnerets"], "regrown over subsequent molts (especially in younger animals)", 2),
  q("A 'DLS' in hobby talk is a…", ["double-leg spinneret", "death curl that can actually be a dehydration pose — or a real decline", "dry leaf substrate", "dawn light spectrum"], "death curl that can actually be a dehydration pose — or a real decline", 3),
  q("Humidity for a rainforest sling is often kept up with…", ["a hair dryer", "a water dish plus a slightly damp hide, not a soaked swamp", "only ice cubes", "table salt"], "a water dish plus a slightly damp hide, not a soaked swamp", 2),
  q("An obligatory burrower wants…", ["only a tall empty tube", "deep substrate it can tunnel in", "open water like a fish", "no substrate at all"], "deep substrate it can tunnel in", 1),
  q("An arboreal wants…", ["only two inches of packed clay and no cork", "height, cork / bark, and a water dish", "a wheel", "UVB desert lamps as a must"], "height, cork / bark, and a water dish", 1),
  q("The World Spider Catalog is a standard reference for…", ["bird songs", "spider taxonomy", "rock types", "star names"], "spider taxonomy", 3),
  q("Theraphosidae was named in the 19th century by…", ["Linnaeus as this family name in 1758", "Thorell", "Darwin", "Wallace as the family author"], "Thorell", 3),
  q("A mature male's search is called…", ["estivation only", "roaming / a breeding ramble", "a bird migration", "a molt sack"], "roaming / a breeding ramble", 2),
  q("Keepers sex tarantulas by…", ["counting eyes", "ventral abdominal markings (and later by palps / tibiae)", "weighing silk", "listening to stridulation only"], "ventral abdominal markings (and later by palps / tibiae)", 3),
  q("A spermatheca molt confirms…", ["an Old World species only", "a female (in species that show them)", "dehydration", "a sling's instar as a number"], "a female (in species that show them)", 3),
  q("Rehousing a tarantula is safest with…", ["bare hands on the abdomen", "a catch cup and patience, not grabbing the abdomen", "a vacuum", "ice water dunking"], "a catch cup and patience, not grabbing the abdomen", 1),
  q("Handling is…", ["required daily", "optional and risky (falls, hairs, bites) — display is the usual joy", "the only way they eat", "how you sex them"], "optional and risky (falls, hairs, bites) — display is the usual joy", 1),
  q("New World bites are usually…", ["as a rule as deadly as a taipan", "locally painful, medically minor for healthy adults (species vary)", "impossible because they have no venom", "always painless"], "locally painful, medically minor for healthy adults (species vary)", 2),
  q("Some Old World bites can cause…", ["only a tickle", "severe pain and muscle cramps for hours to days", "instant silk blindness in all cases", "no symptoms ever"], "severe pain and muscle cramps for hours to days", 2),
  q("No tarantula venom is known to be…", ["painful", "routinely lethal to a healthy human the way some snakes are", "present at all", "delivered by fangs"], "routinely lethal to a healthy human the way some snakes are", 2),
  q("The 'tarantella' dance legend is tied to…", ["Mexican red-knees in the Alps", "wolf spiders / tarantism in southern Italy, not New World theraphosids", "GBBs in Venice", "OBTs in Rome as natives"], "wolf spiders / tarantism in southern Italy, not New World theraphosids", 3),
  q("A wolf spider is in family…", ["Theraphosidae", "Lycosidae", "Scorpionidae", "Ixodidae"], "Lycosidae", 3),
  q("A tarantula is not a…", ["spider", "scorpion, harvestman, or tick", "mygalomorph", "arachnid"], "scorpion, harvestman, or tick", 1),
  q("The pedipalp of a mature male carries the…", ["book lung", "embolus (sperm-transfer organ)", "egg sac", "urticating comb only"], "embolus (sperm-transfer organ)", 3),
  q("Urticating hairs can irritate…", ["only other spiders' silk", "skin, eyes, and airways", "only plants", "only steel"], "skin, eyes, and airways", 1),
  q("Hobby first-aid for hairs is often…", ["rubbing with sandpaper", "tape/peel and flush — not rubbing them in", "a salt pack as the only cure", "ignoring eye hairs"], "tape/peel and flush — not rubbing them in", 2),
  q("A just-molted tarantula is…", ["hungry for a mouse immediately", "soft and should not be fed until the fangs harden", "ready to be handled", "dead"], "soft and should not be fed until the fangs harden", 1),
  q("The fangs after a molt need time to…", ["grow feathers", "sclerotize (harden)", "turn into spinnerets", "fall out"], "sclerotize (harden)", 2),
  q("Overfeeding a tarantula can lead to…", ["wings", "a swollen abdomen and a riskier molt", "extra eyes", "no silk ever"], "a swollen abdomen and a riskier molt", 2),
  q("A water dish helps prevent…", ["molting", "dehydration (the 'death curl' look)", "silk", "color"], "dehydration (the 'death curl' look)", 1),
  q("Substrate in a terrestrial tank is often…", ["only gravel of an aquarium", "coco fiber, topsoil, or similar, deep enough to burrow", "only water", "only concrete"], "coco fiber, topsoil, or similar, deep enough to burrow", 1),
  q("Cross-ventilation in an enclosure helps…", ["cook the spider", "avoid stagnant, moldy air", "dry the book lungs to dust as a goal", "attract wasps"], "avoid stagnant, moldy air", 2),
  q("The Tarantula Collective is a…", ["NASCAR team", "husbandry and education channel / site for keepers", "airline", "bank"], "husbandry and education channel / site for keepers", 1),
  q("Captive-bred slings are preferred over wild-caught because…", ["wild animals always live longer in a cup", "wild collection can pressure populations and import pests/stress", "CB slings cannot molt", "WC animals have no venom"], "wild collection can pressure populations and import pests/stress", 2),
  q("A 'CB' sling means…", ["color-blind", "captive-bred", "cave-burrower", "Chilean-black"], "captive-bred", 1),
  q("A 'WC' animal is…", ["well-cared-for as a legal term", "wild-caught", "white-carapace morph", "water-cursorial"], "wild-caught", 2),
  q("Taxonomy in tarantulas moves often because…", ["they are insects some years", "genera get split with new DNA and morphology work", "they change kingdoms each molt", "hobby names are the scientific code"], "genera get split with new DNA and morphology work", 2),
  q("Tliltocatl was split from Brachypelma in…", ["1900", "1980", "2020", "1758"], "2020", 3),
  q("A 'red knee' in older guides may be labeled B. smithi; the common pet form is now usually…", ["Poecilotheria metallica", "Brachypelma hamorii", "Pterinochilus murinus", "Theraphosa blondi"], "Brachypelma hamorii", 3),
  q("Grammostola names in the pet trade (rosea / porteri) are…", ["perfectly one species since Linnaeus", "historically messy — several Chilean roses were mixed", "African baboons", "fish"], "historically messy — several Chilean roses were mixed", 3),
  q("A heavy webber like a GBB will often…", ["never silk", "coat cork and walls in silk", "build a paper wasp nest", "spin a round orb like an araneid as the usual sheet"], "coat cork and walls in silk", 1),
  q("Orb-weaving garden spiders are…", ["theraphosids", "araneomorphs, not tarantulas", "scorpions", "solifuges"], "araneomorphs, not tarantulas", 2),
  q("A solifuge (camel spider) is…", ["a Theraphosidae species", "not a tarantula and not a true spider in the same way", "a scorpion", "a harvestman"], "not a tarantula and not a true spider in the same way", 3),
  q("Harvestmen (daddy longlegs) are…", ["Theraphosidae", "Opiliones — not spiders, and not venomous tarantulas", "ticks", "insects"], "Opiliones — not spiders, and not venomous tarantulas", 2),
  q("Ticks are…", ["baby tarantulas", "parasitic mites (Acari), not tarantulas", "winged insects", "crustaceans of the land"], "parasitic mites (Acari), not tarantulas", 2),
  q("Scorpions are arachnids that…", ["are tarantulas with eight extra legs", "have a telson sting; tarantulas do not", "spin orb webs as a rule", "have six legs"], "have a telson sting; tarantulas do not", 1),
  q("Both scorpions and tarantulas are…", ["insects", "arachnids", "myriapods", "annelids"], "arachnids", 1),
  q("Amblypygi are…", ["true tarantulas of Africa", "tailless whip scorpions — relatives, not tarantulas", "millipedes", "beetles"], "tailless whip scorpions — relatives, not tarantulas", 3),
  q("Uropygids (vinegaroons) can spray…", ["silk as a spray", "acetic acid; tarantulas cannot", "ink", "hot wax"], "acetic acid; tarantulas cannot", 3),
  q("A tarantula's food is typically offered with…", ["the mouth", "tongs, not fingers, especially on Old World species", "a hook in the book lung", "glue"], "tongs, not fingers, especially on Old World species", 1),
  q("Uneaten prey should be…", ["left forever", "removed so it cannot bother a pre-molt spider", "always doubled", "salted"], "removed so it cannot bother a pre-molt spider", 1),
  q("A hide for a terrestrial can be…", ["a hamster wheel", "cork bark, a half log, or a burrow it digs", "an open lamp", "a deep pool"], "cork bark, a half log, or a burrow it digs", 1),
  q("Light for a tarantula should be…", ["full desert UV as a must for all", "ordinary room light — they are not sun-basking lizards", "total darkness forever with no day cue", "a heat lamp on the abdomen"], "ordinary room light — they are not sun-basking lizards", 2),
  q("Temperatures in the mid 20s °C suit…", ["all polar species as a must", "many common pet species; avoid cooking them", "only ice-box storage", "boiling"], "many common pet species; avoid cooking them", 2),
  q("A 'dry' species still usually needs…", ["no water ever", "a water dish; dry is not desiccated", "a swamp of standing water", "salt water"], "a water dish; dry is not desiccated", 1),
  q("The abdomen is fragile because it is…", ["made of bone", "soft compared with the carapace and can rupture in a fall", "solid steel", "a shell of turtle scute"], "soft compared with the carapace and can rupture in a fall", 2),
  q("The carapace is the…", ["egg sac", "hard dorsal plate of the cephalothorax", "book lung book", "silk mat"], "hard dorsal plate of the cephalothorax", 2),
  q("The fovea is a…", ["spinneret", "pit on the carapace (horns of Ceratogyrus rise near it)", "fang socket of the pedipalp", "eye of a sling only"], "pit on the carapace (horns of Ceratogyrus rise near it)", 3),
  q("Tarantulas do not have…", ["fangs", "antennae, wings, or a sting", "silk", "an exoskeleton"], "antennae, wings, or a sting", 1),
  q("Most tarantulas hunt as…", ["pack wolves", "ambush predators", "filter feeders", "grazers of grass"], "ambush predators", 1),
  q("A tarantula senses prey with…", ["echolocation clicks like a bat as the main trick", "vibration and air movement, not a sharp image like a hawk", "sonar of a submarine", "infrared pits of a pitviper as the spider design"], "vibration and air movement, not a sharp image like a hawk", 2),
  q("Molting frequency is highest in…", ["ancient females that never grow", "slings", "mature males after the last molt as a weekly habit", "egg sacs"], "slings", 1),
  q("A mature male's last molt is often his…", ["first instar", "ultimate molt — he is then on a short clock", "egg", "a second childhood of 20 years as a rule"], "ultimate molt — he is then on a short clock", 2),
  q("Display, not handling, is the point of a…", ["dog", "pet tarantula for most keepers", "horse", "falcon"], "pet tarantula for most keepers", 1),
  q("Chromatopelma cyaneopubescens is native to…", ["Colombia", "East Africa", "South America (Chaco region)", "Venezuela"], "Venezuela", 2),
  q("Brachypelma hamorii is native to…", ["southern Africa", "the south-central United States", "northern South America", "Mexico"], "Mexico", 2),
  q("Tliltocatl albopilosus is native to…", ["Costa Rica", "Central America", "northwestern South America", "Southeast Asia"], "Central America", 2),
  q("Grammostola pulchra is native to…", ["Central America", "Venezuela", "Brazil", "India"], "Brazil", 2),
  q("Aphonopelma chalcodes is native to…", ["Venezuela", "the U.S. Southwest", "southern Africa", "northwestern South America"], "the U.S. Southwest", 2),
  q("Poecilotheria metallica is native to…", ["South America (Chaco region)", "Venezuela", "Hispaniola", "India"], "India", 2),
  q("Caribena versicolor is native to…", ["West Africa", "Martinique", "Southeast Asia", "Trinidad"], "Martinique", 2),
  q("Psalmopoeus irminia is native to…", ["the south-central United States", "West Africa", "Venezuela", "Southeast Asia"], "Venezuela", 2),
  q("Monocentropus balfouri is native to…", ["Socotra", "Brazil", "Amazonian South America", "South Africa"], "Socotra", 2),
  q("Heteroscodra maculata is native to…", ["Mexico", "Central America", "West Africa", "the U.S. Southwest"], "West Africa", 2),
  q("Ceratogyrus darlingi is native to…", ["northwestern South America", "southern Africa", "Hispaniola", "Socotra"], "southern Africa", 2),
  q("Grammostola pulchripes is native to…", ["South America (Chaco region)", "Brazil", "northwestern South America", "the U.S. Southwest"], "South America (Chaco region)", 2),
  q("Nhandu chromatus is native to…", ["Venezuela", "Brazil", "South Africa", "Central America"], "Brazil", 2),
  q("Acanthoscurria geniculata is native to…", ["Trinidad", "northwestern South America", "Brazil", "Amazonian South America"], "Brazil", 2),
  q("Megaphobema mesomelas is native to…", ["the south-central United States", "the U.S. Southwest", "northern South America", "Costa Rica"], "Costa Rica", 2),
  q("Sericopelma sp. (typical) is native to…", ["Socotra", "Central America", "East Africa", "Brazil"], "Central America", 2),
  q("Eupalaestrus campestratus is native to…", ["southern Africa", "northwestern South America", "southern South America", "East Africa"], "southern South America", 2),
  q("Harpactira pulchripes is native to…", ["South Africa", "northwestern South America", "Amazonian South America", "South America (Chaco region)"], "South Africa", 2),
  q("Pelinobius muticus is native to…", ["South Africa", "Brazil", "northern South America", "East Africa"], "East Africa", 2),
  q("Stromatopelma calceatum is native to…", ["West Africa", "the south-central United States", "South Africa", "northern South America"], "West Africa", 2),
  q("Encyocratella olivacea is native to…", ["West Africa", "Tanzania / East Africa", "northwestern South America", "Central America"], "Tanzania / East Africa", 2),
  q("Omothymus violaceopes is native to…", ["Southeast Asia", "southern South America", "Socotra", "Tanzania / East Africa"], "Southeast Asia", 2),
  q("Aphonopelma hentzi is native to…", ["northwestern South America", "the south-central United States", "Central America", "West Africa"], "the south-central United States", 2),
  q("Brachypelma boehmei is native to…", ["Mexico", "Trinidad", "Hispaniola", "Southeast Asia"], "Mexico", 2),
  q("Brachypelma auratum is native to…", ["Central America", "Martinique", "Mexico", "the U.S. Southwest"], "Mexico", 2),
  q("Pterinopelma sazimai is native to…", ["West Africa", "the U.S. Southwest", "Brazil", "Costa Rica"], "Brazil", 2),
  q("Cyriopagopus lividus is native to…", ["Southeast Asia", "India", "Martinique", "South America (Chaco region)"], "Southeast Asia", 2),
  q("Avicularia avicularia is native to…", ["East Africa", "southern Africa", "northern South America", "southern South America"], "northern South America", 2),
  q("Davus fasciatus is native to…", ["West Africa", "Martinique", "Colombia", "Costa Rica"], "Costa Rica", 2),
  q("Poecilotheria regalis is native to…", ["Venezuela", "India", "southern Africa", "Southeast Asia"], "India", 2),
  q("Phormictopus cancerides is native to…", ["South America (Chaco region)", "Socotra", "southern South America", "Hispaniola"], "Hispaniola", 2),
  q("Hapalopus formosus is native to…", ["Colombia", "Hispaniola", "Socotra", "northwestern South America"], "Colombia", 2),
  q("Theraphosa stirmi is native to…", ["the south-central United States", "Amazonian South America", "northern South America", "the U.S. Southwest"], "northern South America", 2),
  q("Xenesthis immanis is native to…", ["East Africa", "northwestern South America", "Brazil", "Venezuela"], "northwestern South America", 2),
  q("Psalmopoeus cambridgei is native to…", ["South America (Chaco region)", "Socotra", "Trinidad", "the U.S. Southwest"], "Trinidad", 2),
  q("Sharks are in class…", ["Osteichthyes as the only class", "Chondrichthyes", "Mammalia", "Aves"], "Chondrichthyes", 1),
  q("A shark's skeleton is mostly…", ["bone", "cartilage", "chitin", "silica"], "cartilage", 1),
  q("Sharks and rays together are…", ["teleosts only", "elasmobranchs", "lampreys", "hagfish only"], "elasmobranchs", 2),
  q("Rays and skates are…", ["whales", "close relatives of sharks, not bony fish", "amphibians", "reptiles"], "close relatives of sharks, not bony fish", 1),
  q("The largest living fish is the…", ["great white", "whale shark", "bluefin tuna", "oarfish as the heaviest"], "whale shark", 1),
  q("The whale shark eats chiefly as a…", ["apex biter of seals only", "filter feeder", "coral grazer only", "kelp cutter"], "filter feeder", 1),
  q("The fastest shark is often listed as the…", ["nurse shark", "shortfin mako", "wobbegong", "angel shark"], "shortfin mako", 2),
  q("Great whites belong to the genus…", ["Galeocerdo", "Carcharodon", "Sphyrna", "Rhincodon"], "Carcharodon", 2),
  q("Tiger sharks belong to the genus…", ["Carcharodon", "Galeocerdo", "Rhincodon", "Cetorhinus"], "Galeocerdo", 3),
  q("Hammerheads belong to the genus…", ["Pristis", "Sphyrna (among related genera)", "Manta", "Lamna only"], "Sphyrna (among related genera)", 2),
  q("The basking shark is a…", ["freshwater stingray", "filter-feeding giant of cool seas", "reef-only goby", "parrotfish"], "filter-feeding giant of cool seas", 2),
  q("The megamouth shark is a…", ["river dolphin", "rare filter feeder", "penguin", "seal"], "rare filter feeder", 3),
  q("The goblin shark is known for…", ["armor plates like a sturgeon", "a protruding snout and slingshot jaws", "walking on land nightly as a rule", "freshwater only"], "a protruding snout and slingshot jaws", 3),
  q("The cookiecutter shark feeds by…", ["filtering krill only", "cutting round plugs of flesh", "grazing seagrass", "drilling wood"], "cutting round plugs of flesh", 2),
  q("The Greenland shark is famed for…", ["being the fastest fish", "extreme longevity (centuries)", "living only in coral atolls", "having bones like a tuna"], "extreme longevity (centuries)", 2),
  q("Bull sharks are notable for…", ["having no teeth", "entering fresh water", "being filter feeders only", "lacking a liver"], "entering fresh water", 2),
  q("Nurse sharks are typically…", ["open-ocean sprinters", "sluggish bottom-dwellers", "freshwater eels", "flying fish"], "sluggish bottom-dwellers", 1),
  q("Wobbegongs are…", ["hammerheads", "carpet sharks with camouflage tassels", "rays that are legally tuna", "lampreys"], "carpet sharks with camouflage tassels", 3),
  q("Angel sharks are…", ["true rays with stings", "flattened, ray-like ambush sharks", "eels", "chimaeras only"], "flattened, ray-like ambush sharks", 3),
  q("A sawshark is a…", ["ray called a sawfish", "shark with a toothed rostrum (gills on the sides)", "bony pike", "swordfish"], "shark with a toothed rostrum (gills on the sides)", 3),
  q("A sawfish is a…", ["true shark of the mako family", "ray (gills underneath), not a shark", "sturgeon", "paddlefish of the Mississippi"], "ray (gills underneath), not a shark", 3),
  q("Thresher sharks have a…", ["saw snout", "huge upper tail lobe used in hunting", "horn on the carapace", "beak like a parrotfish"], "huge upper tail lobe used in hunting", 2),
  q("Mako and great white are…", ["carpet sharks", "lamnid (mackerel) sharks", "rays", "chimaeras"], "lamnid (mackerel) sharks", 3),
  q("Chimaeras (ghost sharks) are…", ["bony tuna", "cartilaginous fishes related to sharks, not true sharks", "mammals", "amphibians"], "cartilaginous fishes related to sharks, not true sharks", 3),
  q("Sharks have no…", ["liver", "swim bladder", "liver oil", "teeth"], "swim bladder", 2),
  q("Buoyancy in many sharks comes from a…", ["swim bladder of bone", "oily liver", "feather coat", "hollow bones of birds"], "oily liver", 2),
  q("Ampullae of Lorenzini detect…", ["color only", "electric fields", "only air temperature", "only sound in air"], "electric fields", 2),
  q("The lateral line detects…", ["color", "water movement and pressure", "only magnetic north as a compass card", "only taste"], "water movement and pressure", 2),
  q("Shark skin denticles are…", ["mammal hair", "placoid scales", "bird feathers", "fish slime only with no structure"], "placoid scales", 3),
  q("Shark teeth are…", ["never replaced", "replaced in rows through life", "made of keratin only like hair", "absent in all species"], "replaced in rows through life", 1),
  q("Some sharks lay eggs in cases nicknamed…", ["bird nests", "mermaid's purses", "caddis tubes", "wasp paper"], "mermaid's purses", 2),
  q("Live-bearing sharks are…", ["all egg-layers as a rule", "viviparous or ovoviviparous (species vary)", "mammals that nurse with milk", "amphibians"], "viviparous or ovoviviparous (species vary)", 2),
  q("Ram ventilators must…", ["breathe air like whales always", "keep water flowing over the gills, often by swimming", "walk on land nightly", "close the gills forever"], "keep water flowing over the gills, often by swimming", 2),
  q("Buccal pumping lets some sharks…", ["fly", "breathe while still", "photosynthesize", "live in lava"], "breathe while still", 2),
  q("Overfishing and finning have…", ["made sharks more abundant than ever", "driven many shark populations down", "no effect", "turned sharks into bony fish"], "driven many shark populations down", 1),
  q("A shark fin soup demand problem is…", ["planting extra kelp", "killing sharks for fins and wasting the body", "a way to tag sharks safely", "a coral-restoration method"], "killing sharks for fins and wasting the body", 1),
  q("Manta rays are…", ["sharks with a sting always", "filter-feeding rays", "bony flatfish", "mammals"], "filter-feeding rays", 1),
  q("Stingrays have a…", ["dorsal fin like a sailfish only", "barbed spine on the tail", "blowhole", "feathers"], "barbed spine on the tail", 1),
  q("Electric rays can…", ["fly", "stun prey with electric organs", "make silk", "breathe only air"], "stun prey with electric organs", 2),
  q("Skates typically…", ["are mammals", "lay egg cases and lack a sting of the stingray type", "are sharks of the mako family", "live only in trees"], "lay egg cases and lack a sting of the stingray type", 3),
  q("Bony fish are classically…", ["Chondrichthyes", "Osteichthyes / ray-finned and lobe-finned", "Aves", "Amphibia only"], "Osteichthyes / ray-finned and lobe-finned", 2),
  q("Ray-finned fishes are…", ["only sharks", "actinopterygians, the bulk of living fish", "only lungfish", "only lampreys"], "actinopterygians, the bulk of living fish", 3),
  q("A swim bladder in bony fish is for…", ["electroreception only", "buoyancy (and sometimes sound)", "biting", "walking"], "buoyancy (and sometimes sound)", 1),
  q("The operculum of a bony fish is a…", ["tooth", "gill cover", "scale of a shark", "fin spine of a ray only"], "gill cover", 2),
  q("Lampreys and hagfish are…", ["sharks", "jawless fishes", "whales", "turtles"], "jawless fishes", 2),
  q("The coelacanth is a…", ["shark of the reef only", "lobe-finned fish once thought extinct", "dolphin", "penguin"], "lobe-finned fish once thought extinct", 2),
  q("Lungfish can…", ["only live in the deep trench", "breathe air with a lung-like organ", "fly", "photosynthesize"], "breathe air with a lung-like organ", 2),
  q("A seahorse is a…", ["crustacean", "bony fish", "mollusk", "amphibian"], "bony fish", 1),
  q("Male seahorses…", ["make milk like mammals", "carry the developing young", "lay eggs in a bird nest", "sting like rays"], "carry the developing young", 1),
  q("Clownfish live with…", ["only freshwater reeds", "sea anemones", "only ice", "only tarantulas"], "sea anemones", 1),
  q("A salmon that returns to fresh water to spawn is…", ["catadromous", "anadromous", "sessile", "terrestrial"], "anadromous", 2),
  q("Eels that spawn at sea and grow in fresh water are…", ["anadromous", "catadromous", "only marine always", "insects"], "catadromous", 3),
  q("Tuna are…", ["sharks", "fast, warm-bodied bony fishes of the open sea", "rays", "mammals"], "fast, warm-bodied bony fishes of the open sea", 2),
  q("A moray eel has a…", ["stingray spine", "second set of pharyngeal jaws", "blowhole", "book lungs"], "second set of pharyngeal jaws", 3),
  q("Parrotfish help reefs by…", ["building dams like beavers", "grazing algae and making sand from coral", "pollinating seagrass as bees", "hunting lions"], "grazing algae and making sand from coral", 2),
  q("A flounder is a…", ["shark", "flatfish that lies on one side", "mammal", "bird"], "flatfish that lies on one side", 1),
  q("The pufferfish's defense is…", ["kicking urticating hairs", "inflating (and often toxin)", "a tail sting only as a skate", "ink"], "inflating (and often toxin)", 2),
  q("Stonefish are famed for…", ["being sharks", "venomous dorsal spines and camouflage", "filter feeding like whale sharks", "living in deserts"], "venomous dorsal spines and camouflage", 2),
  q("Lionfish are…", ["freshwater carp", "venom-spined Pacific fishes, invasive in the Atlantic", "sharks", "lampreys"], "venom-spined Pacific fishes, invasive in the Atlantic", 2),
  q("A remora hitches with a…", ["hooked beak", "suction disc on the head", "silk line", "barbed stinger"], "suction disc on the head", 2),
  q("Pilot fish and remoras often travel with…", ["only desert tortoises", "large sharks or rays", "only eagles", "only tarantulas"], "large sharks or rays", 1),
  q("Coral trout and groupers are…", ["sharks of the open ocean only", "bony reef predators", "mammals", "birds"], "bony reef predators", 2),
  q("The arapaima is a…", ["reef shark", "huge Amazonian bony fish that can breathe air", "penguin", "ray of the North Sea"], "huge Amazonian bony fish that can breathe air", 3),
  q("Piranhas are…", ["Pacific sharks", "South American characins, not sharks", "eels of the Sargasso", "lampreys"], "South American characins, not sharks", 2),
  q("A paddlefish is a…", ["shark of California", "filter-feeding freshwater fish with a long snout", "dolphin", "tarpon of the reef only"], "filter-feeding freshwater fish with a long snout", 3),
  q("Sturgeons are…", ["rays", "ancient bony fishes prized for caviar, not sharks", "mammals", "amphibians"], "ancient bony fishes prized for caviar, not sharks", 2),
  q("A barracuda is a…", ["whale", "fast predatory bony fish", "sea star", "sponge"], "fast predatory bony fish", 1),
  q("Marlin and sailfish are…", ["sharks", "billfishes", "rays", "eels"], "billfishes", 2),
  q("The oarfish is a…", ["hammerhead", "long, ribbon-like bony fish of the deep", "seal", "crab"], "long, ribbon-like bony fish of the deep", 2),
  q("Lanternfish are…", ["desert pupfish only", "tiny, abundant deep-ocean fishes with photophores", "sharks of rivers", "birds"], "tiny, abundant deep-ocean fishes with photophores", 3),
  q("Photophores are…", ["ears", "light-producing organs", "lungs of a tarantula", "teeth of a ray"], "light-producing organs", 2),
  q("The anglerfish lure is a…", ["shark fin", "modified fin ray with a light organ in many deep species", "feather", "silk line"], "modified fin ray with a light organ in many deep species", 2),
  q("A goby is typically a…", ["whale", "small bony fish, often on reefs or in streams", "eagle", "tarantula"], "small bony fish, often on reefs or in streams", 1),
  q("Damselfish include the…", ["great whites", "clownfish group (among others)", "whale sharks", "mantas"], "clownfish group (among others)", 2),
  q("A wrasse is a…", ["cookiecutter shark", "reef bony fish; some clean parasites off others", "penguin", "kelp"], "reef bony fish; some clean parasites off others", 2),
  q("Cleaner wrasses eat…", ["only coral rock as stone", "parasites and dead tissue off client fish", "only birds", "only tarantula hairs"], "parasites and dead tissue off client fish", 2),
  q("A triggerfish has a…", ["silk gland", "locking dorsal spine", "book lung", "blowhole"], "locking dorsal spine", 3),
  q("Boxfish are often…", ["sharks", "toxic and boxy-plated bony fishes", "mammals", "insects"], "toxic and boxy-plated bony fishes", 3),
  q("Flying fish glide with…", ["feathered wings", "enlarged pectoral fins", "silk kites", "hot air"], "enlarged pectoral fins", 1),
  q("Mudskippers can…", ["live in the Himalaya snow only", "move and breathe on mudflats out of water", "fly to Africa each year as a bird", "photosynthesize"], "move and breathe on mudflats out of water", 2),
  q("Walking catfish and snakeheads are…", ["sharks of the Arctic", "air-breathing freshwater fishes that can travel over land", "eagles", "cacti"], "air-breathing freshwater fishes that can travel over land", 2),
  q("Tilapia are…", ["sharks", "widely farmed cichlids", "rays", "mollusks"], "widely farmed cichlids", 2),
  q("Cichlids are a…", ["shark order", "diverse family of freshwater bony fishes", "whale family", "coral genus"], "diverse family of freshwater bony fishes", 2),
  q("The Oscar and angelfish of aquaria are…", ["sharks", "cichlids (South American)", "eels of the Sargasso", "lampreys"], "cichlids (South American)", 2),
  q("A betta (Siamese fighting fish) is a…", ["shark", "labyrinth fish that can breathe air", "ray", "amphibian"], "labyrinth fish that can breathe air", 2),
  q("The labyrinth organ lets some fishes…", ["filter krill only", "gulp air", "spin silk", "kick hairs"], "gulp air", 2),
  q("Goldfish and koi are…", ["sharks", "domesticated carps", "salmon of the Pacific", "catfish of the Amazon only"], "domesticated carps", 1),
  q("A catfish typically has…", ["a saw snout of a sawshark", "barbels ('whiskers')", "a sting of a manta", "feathers"], "barbels ('whiskers')", 1),
  q("Electric eels are…", ["true morays", "South American knifefish, not true eels", "sharks", "lampreys"], "South American knifefish, not true eels", 3),
  q("The Sargasso Sea is the spawning area of…", ["salmon of Alaska only", "American and European eels", "whale sharks as the only nursery", "tarpon of Texas only"], "American and European eels", 3),
  q("Herring and sardines are…", ["apex sharks", "schooling forage fishes", "whales", "starfishes"], "schooling forage fishes", 1),
  q("Anchovies are…", ["filter-feeding sharks", "small schooling bony fishes", "rays", "crustaceans"], "small schooling bony fishes", 1),
  q("A food web of the open ocean often starts with…", ["lions", "phytoplankton then zooplankton then forage fish", "tarantulas", "cacti of the Atacama as the sea's base"], "phytoplankton then zooplankton then forage fish", 1),
  q("Sharks as apex predators help…", ["pollinate kelp flowers", "structure marine food webs", "build coral skeletons as the main mason", "fix nitrogen on land"], "structure marine food webs", 2),
  q("A marine protected area can help sharks by…", ["feeding them beef", "reducing fishing mortality in a zone", "draining the sea", "adding dams"], "reducing fishing mortality in a zone", 1),
  q("Bycatch of sharks happens in…", ["only catch-and-release fly rods of trout as the main gear", "nets and longlines aimed at other species", "only butterfly nets", "only lobster pots of the desert"], "nets and longlines aimed at other species", 2),
  q("A lek still is not how sharks…", ["breathe", "typically mate — they use claspers", "swim", "sense electricity"], "typically mate — they use claspers", 3),
  q("Male sharks have…", ["udder", "claspers", "antlers", "spinnerets"], "claspers", 2),
  q("The spiral valve is a…", ["dorsal fin", "shark intestine feature that increases surface area", "eye lid of a whale", "scale of a carp only"], "shark intestine feature that increases surface area", 3),
  q("Nictitating membranes in some sharks…", ["make electricity", "protect the eye during a bite", "filter plankton", "store oil"], "protect the eye during a bite", 2),
  q("The caudal fin of a shark is often…", ["missing", "heterocercal (upper lobe longer)", "feathered", "a sting always"], "heterocercal (upper lobe longer)", 3),
  q("Heterocercal tails provide…", ["only electricity", "lift as well as thrust", "silk", "sound of a songbird"], "lift as well as thrust", 3),
  q("A benthic shark lives…", ["only at the sea surface of the open gyre always", "on or near the bottom", "only in trees", "only in rivers of the Alps"], "on or near the bottom", 2),
  q("Pelagic means…", ["of the forest floor", "of the open water column", "of the desert pavement", "of a burrow"], "of the open water column", 1),
  q("The epipelagic zone is roughly the…", ["hadal trench only", "sunlit upper ocean", "inner Earth", "stratosphere"], "sunlit upper ocean", 2),
  q("The hadal zone is the…", ["beach swash", "deepest ocean trenches", "coral crest only", "kelp canopy"], "deepest ocean trenches", 2),
  q("A thermocline is a…", ["shark fin", "steep temperature gradient in the water column", "coral genus", "fish scale"], "steep temperature gradient in the water column", 3),
  q("Upwelling brings…", ["sharks onto land", "nutrient-rich water toward the surface", "only salt into the desert", "tarantulas to sea"], "nutrient-rich water toward the surface", 2),
  q("Kelp forests are dominated by…", ["only sharks as the plants", "large brown algae, not coral", "moss of the tundra", "cacti"], "large brown algae, not coral", 1),
  q("Seagrasses are…", ["algae that are sharks", "flowering plants in shallow seas", "moss of ice", "fungi"], "flowering plants in shallow seas", 2),
  q("Mangroves are…", ["open-ocean algae", "salt-tolerant trees of tropical shores, nurseries for fish", "deep-sea vents", "alpine meadows"], "salt-tolerant trees of tropical shores, nurseries for fish", 1),
  q("Estuaries are important as…", ["only ice shelves", "nurseries mixing river and sea", "only deserts", "only mountaintops"], "nurseries mixing river and sea", 1),
  q("A nursery ground for sharks is often…", ["the stratosphere", "shallow bays or mangroves", "Antarctic ice cap only for tropical reefs", "a freshwater spring in the Sahara always"], "shallow bays or mangroves", 2),
  q("Whale sharks are listed as…", ["invasive in every lake", "endangered on many conservation lists", "insects", "weeds"], "endangered on many conservation lists", 2),
  q("Sawfishes are among the…", ["most abundant tuna", "most threatened marine fishes", "birds of prey", "grasses"], "most threatened marine fishes", 2),
  q("A CITES listing for a shark or ray…", ["makes it a mammal", "restricts international trade in the species", "bans all swimming", "renames it a tarantula"], "restricts international trade in the species", 2),
  q("Pelinobius muticus is the hobby…", ["GBB", "king baboon", "pinktoe", "curly hair"], "king baboon", 2),
  q("Acanthoscurria geniculata is the…", ["Chilean rose", "Brazilian whiteknee", "Gooty ornamental", "desert blonde"], "Brazilian whiteknee", 2),
  q("Grammostola pulchripes is the…", ["OBT", "Chaco golden knee", "Martinique pinktoe", "Socotra blue"], "Chaco golden knee", 2),
  q("Brachypelma boehmei is the…", ["Gooty", "Mexican fireleg", "Togo starburst", "king baboon"], "Mexican fireleg", 2),
  q("Brachypelma auratum is the…", ["pinktoe", "Mexican flame knee", "OBT", "salmon pink birdeater"], "Mexican flame knee", 3),
  q("Aphonopelma hentzi is often called the…", ["Gooty ornamental", "Texas brown tarantula", "green bottle blue", "Antilles pinktoe"], "Texas brown tarantula", 2),
  q("Pterinopelma sazimai is the…", ["OBT", "Brazilian blue", "curly hair", "red rump"], "Brazilian blue", 3),
  q("Cyriopagopus lividus is the hobby…", ["Mexican red-knee", "cobalt blue (an Old World fossorial)", "Chilean rose", "Arizona blonde"], "cobalt blue (an Old World fossorial)", 2),
  q("Avicularia avicularia is a classic…", ["horned baboon", "pinktoe (New World arboreal)", "Gooty ornamental", "earth tiger"], "pinktoe (New World arboreal)", 2),
  q("Davus fasciatus is the…", ["Gooty", "Costa Rican tiger rump", "Socotra blue", "king baboon"], "Costa Rican tiger rump", 3),
  q("Phormictopus cancerides is the…", ["GBB", "Haitian brown", "Martinique pinktoe", "Togo starburst"], "Haitian brown", 3),
  q("Hapalopus (hobby 'pumpkin patch') are…", ["Old World arboreal pokies", "small, fast-growing New World terrestrials", "African horned baboons", "desert blondes of Arizona only"], "small, fast-growing New World terrestrials", 2),
  q("Cyriocosmus species are often kept as…", ["the largest birdeaters", "dwarf tarantulas", "only Old World baboons", "only pinktoes of Martinique"], "dwarf tarantulas", 2),
  q("Typhochlaena seladonia is famed for…", ["being an African baboon", "an iridescent dwarf arboreal from Brazil", "living in the Gobi", "having no silk"], "an iridescent dwarf arboreal from Brazil", 3),
  q("Theraphosa stirmi is a…", ["jumping spider of houses", "goliath tarantula species besides T. blondi", "scorpion", "harvestman"], "goliath tarantula species besides T. blondi", 3),
  q("Theraphosa apophysis is nicknamed the…", ["green bottle blue", "pinkfoot goliath", "curly hair", "Socotra blue"], "pinkfoot goliath", 3),
  q("Ybyrapora was split from…", ["Poecilotheria", "Avicularia", "Ceratogyrus", "Aphonopelma"], "Avicularia", 3),
  q("Poecilotheria in hobby slang are…", ["red knees", "pokies (ornamentals)", "GBBs", "curly hairs"], "pokies (ornamentals)", 2),
  q("Many keepers treat Poecilotheria as…", ["perfect first handling pets", "advanced Old World arboreals (medically significant bites)", "fish", "millipedes"], "advanced Old World arboreals (medically significant bites)", 2),
  q("Poecilotheria metallica is listed as…", ["invasive in every U.S. county", "critically endangered in the wild", "a bony fish", "a bird"], "critically endangered in the wild", 2),
  q("Monocentropus balfouri is unusual because keepers often house it…", ["only in pairs of mature males as a rule", "communally (more so than most tarantulas)", "in a reef tank", "with a tarantula hawk"], "communally (more so than most tarantulas)", 3),
  q("Most tarantula species should be housed…", ["in large breeding packs as the default", "one animal per enclosure", "with a scorpion roommate", "in open outdoor pits of a yard"], "one animal per enclosure", 1),
  q("A 'T-sel' in the hobby is a…", ["type of book lung", "captive-selected color form, not a new wild species by itself", "CITES appendix", "molt stage"], "captive-selected color form, not a new wild species by itself", 3),
  q("Springtails in a tarantula tank are used as a…", ["main prey of adult goliaths", "cleanup crew for mold and leftovers", "heat source", "UVB lamp"], "cleanup crew for mold and leftovers", 2),
  q("Isopods as cleanup can be a problem if they…", ["photosynthesize", "nibble a vulnerable tarantula in a damp, crowded setup", "turn into moths", "eat granite"], "nibble a vulnerable tarantula in a damp, crowded setup", 3),
  q("Stagnant, overly wet air is especially dangerous for…", ["desert stones", "New World arboreal pinktoes (they need cross-ventilation)", "dried gauge blocks", "cacti of the Atacama as spiders"], "New World arboreal pinktoes (they need cross-ventilation)", 2),
  q("A heat mat under a terrestrial tank can…", ["replace a water dish", "cook the animal if the substrate overheats", "sex the spider", "calibrate a micrometer"], "cook the animal if the substrate overheats", 1),
  q("For most pet tarantulas, a water dish beats…", ["never offering water", "soaking the whole enclosure into a swamp", "a salt lick", "a UVB desert array as a must"], "soaking the whole enclosure into a swamp", 1),
  q("A late pre-molt tarantula often…", ["needs a huge meal the night before", "refuses food and may seal a web hammock or burrow", "should be rehoused that hour", "should be handled for exercise"], "refuses food and may seal a web hammock or burrow", 1),
  q("Do not rehouse or feed a tarantula that is…", ["asleep as a mammal sleeps", "on its back in a molt", "sitting in a water dish", "sitting on cork"], "on its back in a molt", 1),
  q("An obligatory burrower is more likely to thrive with…", ["only a tall bare tube and no soil", "deep, compactable substrate it can tunnel", "open water like a goldfish", "a running wheel"], "deep, compactable substrate it can tunnel", 1),
  q("An opportunistic burrower may…", ["never sit still", "use a ready-made hide rather than digging a full warren", "require a reef anemone", "live only in the hadal zone"], "use a ready-made hide rather than digging a full warren", 2),
  q("Aromatic cedar or pine shavings are…", ["the gold-standard burrow mix", "a poor, potentially harmful substrate choice", "required by CITES", "the only legal bedding"], "a poor, potentially harmful substrate choice", 2),
  q("Coco fiber (coir) is a common…", ["prey insect", "terrestrial substrate", "venom crystal", "book-lung plate"], "terrestrial substrate", 1),
  q("A cork-bark tube is a classic hide for…", ["reef fish", "arboreal tarantulas", "baleen whales", "kelp"], "arboreal tarantulas", 1),
  q("The venom glands of a tarantula sit in the…", ["spinnerets only", "chelicerae", "book lungs", "eggs"], "chelicerae", 2),
  q("A tarantula typically shows how many spinnerets at the rear?", ["two only as a beetle", "four (two pairs)", "eight like the legs", "none"], "four (two pairs)", 3),
  q("The last segment of a tarantula leg is the…", ["abdomen", "tarsus", "carapace", "pedicel"], "tarsus", 3),
  q("Autotomy in a tarantula is…", ["kicking hairs only", "dropping a leg to escape", "laying eggs", "stridulating"], "dropping a leg to escape", 2),
  q("The ocular tubercle is the…", ["silk organ", "raised mound that bears the eyes", "book lung slit", "egg tooth"], "raised mound that bears the eyes", 3),
  q("Tarantula vision is generally…", ["as sharp as an eagle's as a rule", "poor — they hunt by vibration and touch more than a hawk's sight", "based on echolocation clicks", "based on infrared pits of a viper"], "poor — they hunt by vibration and touch more than a hawk's sight", 2),
  q("Pterinochilus murinus is famous for a loud…", ["bird song", "hiss (stridulation) when threatened", "whale click", "frog chorus"], "hiss (stridulation) when threatened", 2),
  q("OBT in hobby notes means…", ["old black terrestrial", "orange baboon tarantula", "optical bore tester", "Oregon brown tick"], "orange baboon tarantula", 1),
  q("GBB in hobby notes means…", ["giant black birdeater as this acronym", "green bottle blue", "Gooty baboon brown", "ground beetle of Brazil"], "green bottle blue", 1),
  q("LP in hobby notes often means…", ["lycosa pack", "Lasiodora parahybana", "long palpus", "lunar pinktoe"], "Lasiodora parahybana", 2),
  q("MM in a listing means…", ["metric molt", "mature male", "Mexican morph", "micro millipede"], "mature male", 1),
  q("An exuvium is sometimes nicknamed a…", ["egg only", "spider's molt skin / 'skeleton'", "water dish", "cork round"], "spider's molt skin / 'skeleton'", 1),
  q("Fresh-molt colors often look…", ["always darker forever", "washed or pale until the cuticle hardens", "feathered", "transparent like glass always"], "washed or pale until the cuticle hardens", 2),
  q("Dry-climate pet genera include many…", ["Theraphosa of the flooded forest as the dry set", "Brachypelma, Grammostola, and Aphonopelma", "Avicularia pinktoes as desert animals", "Poecilotheria of rain trees as desert animals"], "Brachypelma, Grammostola, and Aphonopelma", 2),
  q("Moist-forest fossorials include many…", ["Aphonopelma of Arizona as rainforest animals", "Theraphosa and some Pamphobeteus", "Grammostola of the Atacama as a swamp set", "desert blondes of the Sonoran as jungle animals"], "Theraphosa and some Pamphobeteus", 2),
  q("A 'pet hole' in a fossorial tank is the…", ["water dish", "open mouth of a burrow the spider uses", "heat mat", "UV lamp"], "open mouth of a burrow the spider uses", 2),
  q("Type I urticating hairs are typically…", ["on Old World palps only", "kicked from the abdomen in many Theraphosinae", "venom crystals", "silk glands"], "kicked from the abdomen in many Theraphosinae", 3),
  q("Type VI urticating hairs are the…", ["kicked cloud of a GBB only as Type VI", "palpal hairs of Ephebopus", "book-lung plates", "egg teeth"], "palpal hairs of Ephebopus", 3),
  q("Many Brachypelma are listed on CITES Appendix…", ["I only as every Brachypelma's only listing", "II (controlled international trade)", "none — they are insects", "the U.S. flag code"], "II (controlled international trade)", 3),
  q("A sling enclosure should be…", ["a tall empty room like a hallway", "escape-proof and not a long drop onto hard ground", "an open bowl on a windowsill", "a reef sump"], "escape-proof and not a long drop onto hard ground", 1),
  q("The Tarantula Collective's husbandry line is generally…", ["wild-caught only and daily handling", "captive-bred animals, species-appropriate setups, and respect, not handling as the goal", "heat mats for every desert and swamp alike", "no water dishes ever"], "captive-bred animals, species-appropriate setups, and respect, not handling as the goal", 1),
  q("A sperm web is not an egg sac; it is how a male…", ["lays eggs", "charges his palps with sperm", "kicks hairs", "molts"], "charges his palps with sperm", 3),
  q("Egg-sac size varies wildly; large terrestrials may guard…", ["exactly two eggs always", "hundreds of eggs", "live calves", "a bird nest of sticks"], "hundreds of eggs", 2),
  q("Neoholothele incei is a…", ["whale shark", "small, relatively active New World species kept in the hobby", "horned African baboon of the Kalahari only", "Gooty of India"], "small, relatively active New World species kept in the hobby", 3),
  q("Xenesthis immanis is a…", ["tiny dwarf of 1 cm", "large New World terrestrial", "Old World pokie of Sri Lanka", "desert blonde of Arizona"], "large New World terrestrial", 3),
  q("Pamphobeteus species are typically…", ["African horned baboons", "large South American terrestrials", "Arizona blondes", "Martinique pinktoes"], "large South American terrestrials", 3),
  q("A mature male's tibial apophysis is a…", ["book lung", "hook used in mating on some species", "spinneret", "egg sac"], "hook used in mating on some species", 3),
  q("Never use a vacuum to rehouse because you might…", ["calm it", "injure or suck up the spider", "help it molt", "sex it accurately"], "injure or suck up the spider", 1),
  q("A just-reboused tarantula needs…", ["daily handling to tame it", "time to settle, with a hide and water, not constant tapping", "a roommate tarantula as a rule", "a heat lamp on the abdomen"], "time to settle, with a hide and water, not constant tapping", 1),
  q("Great whites are the species…", ["Rhincodon typus", "Carcharodon carcharias", "Cetorhinus maximus", "Galeocerdo cuvier"], "Carcharodon carcharias", 2),
  q("The whale shark's scientific name is…", ["Carcharodon carcharias", "Rhincodon typus", "Sphyrna mokarran", "Prionace glauca"], "Rhincodon typus", 2),
  q("The basking shark's scientific name is…", ["Rhincodon typus", "Cetorhinus maximus", "Carcharodon carcharias", "Mitsukurina owstoni"], "Cetorhinus maximus", 3),
  q("Megalodon is…", ["a living reef shark of Florida keys as a common sight", "an extinct giant shark (Otodus megalodon)", "a bony tuna", "a dolphin"], "an extinct giant shark (Otodus megalodon)", 1),
  q("Dunkleosteus was a…", ["great white of today", "placoderm (armored jawed fish), not a modern shark", "whale", "tarantula"], "placoderm (armored jawed fish), not a modern shark", 3),
  q("A frilled shark has a…", ["hammer head", "long, eel-like body and ancient-looking gills", "sting of a manta", "feathers"], "long, eel-like body and ancient-looking gills", 2),
  q("Epaulette sharks can…", ["fly", "walk on their fins across shallow reef flats", "live only in rivers of the Alps", "spin silk"], "walk on their fins across shallow reef flats", 2),
  q("Bonnethead sharks are unusual in eating…", ["only krill as a whale shark", "seagrass as well as animal prey (they are omnivorous)", "only birds", "only tarantulas"], "seagrass as well as animal prey (they are omnivorous)", 3),
  q("Sand-tiger embryos are famed for…", ["photosynthesis", "eating sibling embryos in the uterus", "spinning cocoons of silk", "laying mermaid purses on land trees"], "eating sibling embryos in the uterus", 3),
  q("Spiny dogfish are famed for a…", ["one-day pregnancy", "very long gestation (about two years)", "life only in trees", "lack of fins"], "very long gestation (about two years)", 3),
  q("The oceanic whitetip is a…", ["freshwater stingray", "pelagic shark of the open ocean", "bony reef goby", "lamprey"], "pelagic shark of the open ocean", 2),
  q("The blue shark (Prionace glauca) is a…", ["bottom wobbegong", "slim open-ocean hunter", "river dolphin", "parrotfish"], "slim open-ocean hunter", 2),
  q("Lemon sharks often use…", ["the stratosphere", "mangrove shallows as nurseries", "only Arctic ice", "desert seeps of the Sahara"], "mangrove shallows as nurseries", 2),
  q("Blacktip reef sharks are typical of…", ["only the abyssal trench", "tropical lagoons and reef flats", "only Alpine lakes", "wheat fields"], "tropical lagoons and reef flats", 1),
  q("Whale-shark spot patterns are…", ["repainted each year as a rule", "unique to individuals, like a fingerprint", "identical in every ocean", "absent — they are plain grey always"], "unique to individuals, like a fingerprint", 2),
  q("A chimaera is also called a…", ["tuna", "ratfish or ghost shark (still not a true shark)", "dolphin", "cactus"], "ratfish or ghost shark (still not a true shark)", 2),
  q("The giant oceanic manta is…", ["Carcharodon carcharias", "Mobula birostris (formerly Manta)", "a whale", "a kelp"], "Mobula birostris (formerly Manta)", 3),
  q("Devil rays are in the genus…", ["Pristis", "Mobula", "Lamna", "Hippocampus"], "Mobula", 3),
  q("Potamotrygon are…", ["Pacific makos", "South American freshwater stingrays", "Arctic seals", "desert pupfish of Death Valley only"], "South American freshwater stingrays", 2),
  q("Smalltooth sawfish are…", ["the most abundant tuna", "among the most endangered marine fishes", "insects", "grasses"], "among the most endangered marine fishes", 2),
  q("The Greenland shark is…", ["Rhincodon typus", "Somniosus microcephalus", "Sphyrna lewini", "Carcharodon carcharias"], "Somniosus microcephalus", 3),
  q("The goblin shark is…", ["Galeocerdo cuvier", "Mitsukurina owstoni", "Prionace glauca", "Negaprion brevirostris"], "Mitsukurina owstoni", 3),
  q("The megamouth shark is…", ["Rhincodon typus", "Megachasma pelagios", "Carcharodon carcharias", "Cetorhinus maximus"], "Megachasma pelagios", 3),
  q("A hammerhead's wide head is a…", ["dorsal fin", "cephalofoil", "clasper", "spiracle only"], "cephalofoil", 3),
  q("The great hammerhead is…", ["Squalus acanthias", "Sphyrna mokarran", "Ginglymostoma cirratum", "Rhincodon typus"], "Sphyrna mokarran", 3),
  q("Great whites can keep parts of the body warmer than the water; they are…", ["fully cold as a snail always with no trick", "regionally endothermic", "mammals that nurse", "birds"], "regionally endothermic", 3),
  q("Countershading on a shark is…", ["striped like a tiger always as this word", "dark above, light below", "gold on both sides", "transparent"], "dark above, light below", 2),
  q("A tapetum lucidum in a shark eye…", ["makes electricity", "reflects light and aids vision in dim water", "filters plankton", "stores oil of the liver"], "reflects light and aids vision in dim water", 3),
  q("Spiracles in some sharks sit…", ["on the tail sting", "behind the eyes and can aid breathing", "inside the liver only", "on the dorsal fin always as gills"], "behind the eyes and can aid breathing", 2),
  q("Most sharks have how many gill slits per side?", ["one", "two like a mammal's lungs as slits", "five (some groups have six or seven)", "twenty"], "five (some groups have six or seven)", 2),
  q("Helicoprion is a fossil fish famous for a…", ["feathered wing", "spiral tooth whorl", "silk gland", "book lung"], "spiral tooth whorl", 3),
  q("A leafy seadragon is a…", ["shark of the Arctic", "Australian relative of seahorses", "dolphin", "kelp that hunts"], "Australian relative of seahorses", 2),
  q("The ocean sunfish (Mola mola) is a…", ["whale", "huge, odd-shaped bony fish", "shark of the mako family", "ray with a sting always"], "huge, odd-shaped bony fish", 2),
  q("Mahi-mahi (dolphinfish) is a…", ["toothed whale", "bony fish, not a dolphin", "shark", "crustacean"], "bony fish, not a dolphin", 1),
  q("An orca is a…", ["bony tuna", "toothed whale (mammal), not a fish", "cartilaginous shark", "ray"], "toothed whale (mammal), not a fish", 1),
  q("Clownfish can change sex; they are…", ["sharks", "sequential hermaphrodites", "mammals", "insects"], "sequential hermaphrodites", 3),
  q("Tiktaalik is a fossil that bridges…", ["sharks and birds", "lobe-finned fishes and early tetrapods", "tarantulas and scorpions", "kelp and coral"], "lobe-finned fishes and early tetrapods", 3),
  q("The coelacanth genus of living animals is…", ["Carcharodon", "Latimeria", "Rhincodon", "Hippocampus as the coelacanth"], "Latimeria", 3),
  q("Nurse sharks include…", ["shortfin mako as this sluggish name", "Ginglymostoma cirratum of the Atlantic", "great hammerhead as a nurse", "whale shark as a nurse"], "Ginglymostoma cirratum of the Atlantic", 3),
  q("The zebra shark (Stegostoma) is a…", ["mako of the open gyre", "carpet shark, also called leopard shark in some regions", "lamprey", "dolphin"], "carpet shark, also called leopard shark in some regions", 3),
  q("A swell shark can…", ["fly", "inflate its body when threatened", "kick urticating hairs", "spin a round orb web"], "inflate its body when threatened", 2),
  q("Sixgill sharks belong to…", ["Sphyrna", "Hexanchus (a primitive-looking lineage)", "Pristis", "Manta"], "Hexanchus (a primitive-looking lineage)", 3),
  q("The ocean sunfish's diet is often…", ["only krill of polar water as the only bite", "jellies (among other prey)", "only grasses of a prairie", "only tarantulas"], "jellies (among other prey)", 2),
  q("Pipefish are close relatives of…", ["great whites", "seahorses", "hammerheads", "goliath tarantulas"], "seahorses", 2),
  q("Frogfishes are…", ["open-ocean makos", "sit-and-wait anglers on reefs", "eagles", "kelp"], "sit-and-wait anglers on reefs", 2),
  q("Krill in a food web are…", ["baby sharks", "small crustaceans, not fish", "seagrasses", "tarantulas"], "small crustaceans, not fish", 1),
  q("A horseshoe crab is…", ["a bony reef fish", "an arthropod more related to spiders than to a true crab", "a shark", "a mammal"], "an arthropod more related to spiders than to a true crab", 2),
  q("Sea turtles are…", ["bony fish", "reptiles, not fish", "sharks", "mammals that gill-breathe"], "reptiles, not fish", 1),
  q("Manatees are…", ["sharks", "herbivorous marine mammals", "bony tuna", "rays"], "herbivorous marine mammals", 1),
  q("The Atlantic bluefin is a…", ["reef goby", "highly migratory tuna, heavily fished", "freshwater stingray of the Amazon", "lamprey"], "highly migratory tuna, heavily fished", 2),
  q("Swordfish belong to…", ["Carcharodon", "Xiphias (a billfish, not a shark)", "Sphyrna", "Rhincodon"], "Xiphias (a billfish, not a shark)", 2),
  q("A moray is a…", ["shark of the open gyre only", "bony eel-shaped fish of reefs and rocks", "mammal", "crustacean"], "bony eel-shaped fish of reefs and rocks", 1),
  q("Parrotfish teeth are fused into a…", ["silk comb", "beak for scraping algae and coral", "hammer cephalofoil", "sting of a ray always"], "beak for scraping algae and coral", 2),
  q("Coral bleaching is when corals…", ["turn into sharks", "expel their symbiotic algae under stress", "become tarantulas", "freeze into icebergs as a rule"], "expel their symbiotic algae under stress", 2),
  q("A cleaner station on a reef is where…", ["sharks go to molt silk", "small fishes or shrimp pick parasites off clients", "tarantulas nest", "cacti bloom"], "small fishes or shrimp pick parasites off clients", 2),
  q("The Sargasso Sea is named for…", ["a shark genus only", "floating sargassum seaweed", "a tarantula family", "a desert of Peru"], "floating sargassum seaweed", 2),
  q("An atoll, in the tropical ocean, is typically a…", ["mountain of granite only", "ring of coral around a lagoon", "shark tooth", "book lung"], "ring of coral around a lagoon", 1),
  q("A gyre is a…", ["type of dorsal fin", "large rotating ocean current system", "tarantula molt", "coral polyp"], "large rotating ocean current system", 2),
  q("The Gulf Stream is a…", ["cold Antarctic bottom current", "warm Atlantic current", "river of the Amazon", "wind of the Gobi"], "warm Atlantic current", 1),
  q("El Niño is a…", ["shark species", "Pacific climate swing that reshapes fisheries and weather", "tarantula genus", "moon of Jupiter"], "Pacific climate swing that reshapes fisheries and weather", 2),
  q("A fish ladder helps…", ["sharks climb trees", "migratory fish pass a dam", "tarantulas molt", "coral bleach on purpose"], "migratory fish pass a dam", 1),
  q("Bycatch reduction gear is meant to…", ["catch more sharks as the only goal", "let non-target species, including some sharks, escape nets", "drain estuaries", "plant kelp on land"], "let non-target species, including some sharks, escape nets", 2),
  q("Shark sanctuaries are…", ["airports", "national waters that restrict shark fishing", "desert parks of Arizona only as this phrase", "tarantula rooms"], "national waters that restrict shark fishing", 2),
  q("A tag-and-release study of sharks tracks…", ["only color of the tank", "movements and survival", "book-lung counts", "silk quality"], "movements and survival", 1),
  q("The IUCN Red List is used to…", ["set SI units", "score extinction risk, including for many sharks and rays", "name tarantula colors only", "time rocket burns"], "score extinction risk, including for many sharks and rays", 2),
];

