import { q } from "../quiz";
import type { TriviaQ } from "../types";

export const NATURE_MORE: TriviaQ[] = [
  q("A young cat is called a…", ["kitten", "chick", "lamb", "tadpole (then froglet)"], "kitten", 1),
  q("A young dog is called a…", ["duckling", "pup", "owlet", "puppy"], "puppy", 1),
  q("A young horse is called a…", ["cub", "tadpole (then froglet)", "foal", "cygnet"], "foal", 1),
  q("A young cow is called a…", ["kit", "caterpillar (then chrysalis)", "calf", "joey"], "calf", 1),
  q("A young sheep is called a…", ["fawn", "foal", "lamb", "kid"], "lamb", 1),
  q("A young goat is called a…", ["kid", "gosling", "foal", "kit"], "kid", 1),
  q("A young pig is called a…", ["kit", "piglet", "tadpole (then froglet)", "cygnet"], "piglet", 1),
  q("A young bear is called a…", ["cub", "pup", "owlet", "fry / parr / smolt (stages)"], "cub", 1),
  q("A young lion is called a…", ["piglet", "cub", "pup", "kit"], "cub", 1),
  q("A young tiger is called a…", ["gosling", "cub", "pup", "elver (after leptocephalus)"], "cub", 1),
  q("A young wolf is called a…", ["caterpillar (then chrysalis)", "puppy", "piglet", "pup"], "pup", 1),
  q("A young fox is called a…", ["chick", "kit", "elver (after leptocephalus)", "tadpole (then froglet)"], "kit", 1),
  q("A young deer is called a…", ["joey", "chick", "caterpillar (then chrysalis)", "fawn"], "fawn", 1),
  q("A young kangaroo is called a…", ["joey", "chick", "pup", "kitten"], "joey", 1),
  q("A young swan is called a…", ["joey", "elver (after leptocephalus)", "foal", "cygnet"], "cygnet", 1),
  q("A young goose is called a…", ["foal", "cygnet", "calf", "gosling"], "gosling", 1),
  q("A young duck is called a…", ["kit", "duckling", "elver (after leptocephalus)", "gosling"], "duckling", 1),
  q("A young hen is called a…", ["eaglet", "kid", "chick", "owlet"], "chick", 1),
  q("A young owl is called a…", ["fry / parr / smolt (stages)", "foal", "fawn", "owlet"], "owlet", 1),
  q("A young eagle is called a…", ["puppy", "duckling", "lamb", "eaglet"], "eaglet", 1),
  q("A young frog is called a…", ["tadpole", "kit", "cub", "chick"], "tadpole", 1),
  q("A young butterfly is called a…", ["tadpole (then froglet)", "lamb", "foal", "caterpillar (then chrysalis)"], "caterpillar (then chrysalis)", 1),
  q("A young eel is called a…", ["elver (after leptocephalus)", "foal", "cub", "tadpole (then froglet)"], "elver (after leptocephalus)", 1),
  q("A young salmon is called a…", ["fry / parr / smolt (stages)", "calf", "cub", "elver (after leptocephalus)"], "fry / parr / smolt (stages)", 1),
  q("A group of lions is called a…", ["pack", "pride", "smack", "pod"], "pride", 2),
  q("A group of wolves is called a…", ["pack", "pod", "smack", "skein / wedge"], "pack", 2),
  q("A group of crows is called a…", ["herd", "school / shoal", "murder", "flock"], "murder", 2),
  q("A group of geese (on the ground) is called a…", ["gaggle", "swarm / hive", "colony", "mob / troop"], "gaggle", 2),
  q("A group of geese (in flight) is called a…", ["skein / wedge", "pride / troop", "smack / bloom", "herd / drove"], "skein / wedge", 2),
  q("A group of fish is called a…", ["herd / drove", "pod / gam", "flock / murmuration", "school / shoal"], "school / shoal", 2),
  q("A group of whales is called a…", ["herd", "flock", "gaggle", "pod"], "pod", 2),
  q("A group of bees is called a…", ["flock", "parliament", "swarm / hive", "ostentation"], "swarm / hive", 2),
  q("A group of ants is called a…", ["flock", "pod", "pack", "colony"], "colony", 2),
  q("A group of cows is called a…", ["pod", "herd", "ostentation", "parliament"], "herd", 2),
  q("A group of sheep is called a…", ["ostentation", "pride", "flock", "parliament"], "flock", 2),
  q("A group of birds (general) is called a…", ["herd", "mob / troop", "murder", "flock"], "flock", 2),
  q("A group of ravens is called a…", ["parliament", "murmuration", "pod", "unkindness"], "unkindness", 2),
  q("A group of peacocks is called a…", ["ostentation", "herd", "flock", "romp / raft"], "ostentation", 2),
  q("A group of porpoises is called a…", ["swarm / hive", "unkindness", "flock", "pod"], "pod", 2),
  q("A group of kangaroos is called a…", ["mob / troop", "smack", "skein / wedge", "school / shoal"], "mob / troop", 2),
  q("A group of baboons is called a…", ["pride", "troop", "swarm / hive", "mob / troop"], "troop", 2),
  q("A group of otters is called a…", ["swarm / hive", "romp / raft", "pod", "skein / wedge"], "romp / raft", 2),
  q("A group of jellyfish is called a…", ["colony", "pack", "smack", "flock"], "smack", 2),
  q("The coast redwood is native chiefly to…", ["China (wild remnant)", "tropical coasts", "southeastern U.S. wetlands", "California"], "California", 2),
  q("The giant sequoia is native chiefly to…", ["the U.S. South / live-oak belt", "California (Sierra)", "Australia", "African savanna"], "California (Sierra)", 2),
  q("The baobab (African) is native chiefly to…", ["African savanna", "China (wild remnant)", "the U.S. South / live-oak belt", "the Great Basin / western U.S."], "African savanna", 2),
  q("The kauri is native chiefly to…", ["northeastern North America", "New Zealand", "western North America", "the Mediterranean"], "New Zealand", 2),
  q("The banyan is native chiefly to…", ["northern forests", "southeastern U.S. wetlands", "South Asia", "Pacific Northwest"], "South Asia", 2),
  q("The bristlecone pine is native chiefly to…", ["tropical coasts", "New Zealand", "the Great Basin / western U.S.", "northeastern North America"], "the Great Basin / western U.S.", 2),
  q("The Douglas fir is native chiefly to…", ["China", "Pacific Northwest", "western North America", "northeastern North America"], "western North America", 2),
  q("The Sitka spruce is native chiefly to…", ["China (wild remnant)", "Australia", "Pacific Northwest", "South Asia"], "Pacific Northwest", 2),
  q("The white birch is native chiefly to…", ["Pacific Northwest", "northern forests", "the U.S. South / live-oak belt", "southeastern U.S. wetlands"], "northern forests", 2),
  q("The sugar maple is native chiefly to…", ["the Pacific Northwest", "southeastern Australia", "the western Mediterranean", "northeastern North America"], "northeastern North America", 2),
  q("The live oak is native chiefly to…", ["northeastern North America", "China", "the U.S. South / live-oak belt", "southeastern U.S. wetlands"], "the U.S. South / live-oak belt", 2),
  q("The saguaro is native chiefly to…", ["the Sonoran Desert", "Pacific Northwest", "the U.S. South / live-oak belt", "northern forests"], "the Sonoran Desert", 2),
  q("The Joshua tree is native chiefly to…", ["western Mediterranean", "Australia", "the Mojave", "South Asia"], "the Mojave", 2),
  q("The mangrove (as a guild) is native chiefly to…", ["African savanna", "tropical coasts", "China (wild remnant)", "Australia"], "tropical coasts", 2),
  q("The cypress of the swamps is native chiefly to…", ["China (wild remnant)", "southeastern U.S. wetlands", "the Mediterranean", "Australia"], "southeastern U.S. wetlands", 2),
  q("The olive is native chiefly to…", ["China (wild remnant)", "Pacific Northwest", "western Mediterranean", "the Mediterranean"], "the Mediterranean", 2),
  q("The cork oak is native chiefly to…", ["western Mediterranean", "the Sonoran Desert", "Australia", "New Zealand"], "western Mediterranean", 2),
  q("The ginkgo is native chiefly to…", ["tropical coasts", "China (wild remnant)", "California (Sierra)", "northeastern North America"], "China (wild remnant)", 2),
  q("The dawn redwood is native chiefly to…", ["southeastern U.S. wetlands", "the Mojave", "China", "California"], "China", 2),
  q("The eucalyptus (many species) is native chiefly to…", ["western North America", "Australia", "the U.S. South / live-oak belt", "China (wild remnant)"], "Australia", 2),
  q("A carnivore eats…", ["only plants", "animals", "only wood", "only nectar"], "animals", 1),
  q("A herbivore eats…", ["only meat", "plants", "only fungi", "only clay"], "plants", 1),
  q("An omnivore eats…", ["plants but not animals", "animals but not plants", "plants and animals", "insects and nectar"], "plants and animals", 1),
  q("A detritivore eats…", ["only live prey", "dead organic matter", "only sunlight", "only stone"], "dead organic matter", 2),
  q("A parasite lives…", ["only as a mutual friend", "on or in a host, at the host's expense", "only on rocks with no host", "only as a predator that always kills at once"], "on or in a host, at the host's expense", 2),
  q("Mutualism is a relation that…", ["hurts both", "helps both partners", "helps one and hurts the other", "has no effect"], "helps both partners", 2),
  q("Commensalism helps one partner and…", ["kills the other", "does not much affect the other", "helps the other equally as mutualism's name", "is always predation"], "does not much affect the other", 3),
  q("A keystone predator can…", ["go a whole season without eating", "shape a whole community by what it eats", "survive only in zoos and preserves", "feed only on fruit and seeds"], "shape a whole community by what it eats", 3),
  q("An invasive species is…", ["native and harmless in its home range", "non-native and harmful in its new range", "extinct in its original range", "a pet kept outside its range"], "non-native and harmful in its new range", 1),
  q("An endemic species lives…", ["everywhere on Earth", "only in a particular place", "only in labs", "only in the ocean"], "only in a particular place", 2),
  q("Extinct means…", ["rare", "no living members", "only in zoos", "only nocturnal"], "no living members", 1),
  q("Endangered means…", ["already gone", "at high risk of extinction", "overabundant", "newly described only"], "at high risk of extinction", 1),
  q("A biome is a…", ["single organism and its habitat", "large ecological community type", "gene shared within a species", "cloud type over a region"], "large ecological community type", 1),
  q("Tundra is…", ["warm, wet, and thickly forested", "cold, treeless, often with permafrost", "hot, dry, and covered with dunes", "shallow, warm, and built of coral"], "cold, treeless, often with permafrost", 1),
  q("Taiga is…", ["tropical grassland", "boreal conifer forest", "mangrove", "chaparral only"], "boreal conifer forest", 2),
  q("Chaparral is a…", ["rainforest of equatorial climates", "shrubland of Mediterranean climates", "ice cap of polar climates", "mangrove swamp of tropical coasts"], "shrubland of Mediterranean climates", 3),
  q("Temperate deciduous forest drops leaves in…", ["only the dry season of the tropics as a rule of this biome", "autumn", "every full moon", "never"], "autumn", 1),
  q("A rainforest has…", ["almost no rain and few species", "high rainfall and high diversity", "permafrost and very short summers", "tall grass and almost no trees"], "high rainfall and high diversity", 1),
  q("The canopy is the…", ["layer of soil under a forest", "upper layer of a forest", "lowest layer of a forest", "type of high cloud"], "upper layer of a forest", 1),
  q("The understory is…", ["outer space", "the layer under the canopy", "the ocean floor always", "a desert pavement"], "the layer under the canopy", 2),
  q("Epiphytes grow…", ["as parasites tapping a host's roots", "on other plants, without being parasites", "underwater, anchored like kelp", "on bare ice in polar regions"], "on other plants, without being parasites", 3),
  q("A succulent plant stores…", ["only salt", "water in thick tissues", "only air in wood", "only light as sugar in the name"], "water in thick tissues", 1),
  q("C4 and CAM photosynthesis are adaptations to…", ["the dark depths of the deep sea", "hot, dry, or intensely sunny climates", "long, dark polar winter nights", "cool, dark, and damp cave floors"], "hot, dry, or intensely sunny climates", 3),
  q("Nitrogen-fixing bacteria often live with…", ["cacti only", "legumes", "conifers only", "ferns only"], "legumes", 2),
  q("Mycorrhizae are…", ["virus–leaf diseases only", "fungus–root partnerships", "insect galls only", "lichen of rock only"], "fungus–root partnerships", 3),
  q("A lichen is a partnership of…", ["two kinds of moss", "a fungus and an alga", "a fern and a moss", "a plant and a virus"], "a fungus and an alga", 2),
  q("Coral bleaching is often from…", ["too much extra coral growth", "heat stress expelling algae", "too many grazing reef fish", "too much bright moonlight"], "heat stress expelling algae", 2),
  q("Kelp forests grow in…", ["deserts", "cool coastal seas", "the high Himalaya", "freshwater ponds only"], "cool coastal seas", 2),
  q("Phytoplankton are…", ["whales", "tiny drifting photosynthesizers", "only corals", "only kelp as large trees"], "tiny drifting photosynthesizers", 2),
  q("Krill are…", ["tiny whales common in polar seas", "small crustaceans, key in polar seas", "seaweeds that float in polar seas", "small fish, key in tropical seas"], "small crustaceans, key in polar seas", 2),
  q("Baleen whales feed with…", ["rows of cone-shaped teeth", "comb-like baleen plates", "beaks like those of birds", "sucking mouthparts"], "comb-like baleen plates", 2),
  q("Toothed whales include…", ["blue whales", "dolphins, orcas, sperm whales", "humpbacks as toothed", "right whales as toothed"], "dolphins, orcas, sperm whales", 2),
  q("Echolocation is used by…", ["earthworms and moles", "bats and toothed whales", "birds of paradise", "snakes and lizards"], "bats and toothed whales", 2),
  q("A nocturnal animal is active at…", ["noon only", "night", "only dawn", "only winter"], "night", 1),
  q("A crepuscular animal is active at…", ["noon", "dawn and dusk", "midnight only", "only in hibernation"], "dawn and dusk", 2),
  q("Hibernation is a…", ["daily sleep of all mammals", "seasonal winter torpor", "seasonal migration", "seasonal molt"], "seasonal winter torpor", 1),
  q("Migration is a…", ["one afternoon nap", "seasonal long-distance movement", "changing color only", "growing a new shell only"], "seasonal long-distance movement", 1),
  q("Camouflage helps an animal…", ["stand out always", "blend in", "sing", "hibernate"], "blend in", 1),
  q("Mimicry is looking like…", ["your own parents more each year", "another species, often a dangerous one", "the surrounding weather", "the plants you happen to eat"], "another species, often a dangerous one", 2),
  q("Aposematic colors often…", ["hide it in leaves", "warn that an animal is toxic or fierce", "are only for attracting mates", "are always brown"], "warn that an animal is toxic or fierce", 3),
  q("The red-spotted newt's eft is…", ["a fish-like larva in ponds", "a toxic, bright juvenile on land", "an adult that lives in water", "an orange mushroom it eats"], "a toxic, bright juvenile on land", 3),
  q("Amphibians typically have…", ["feathers", "moist skin and a life tied to water", "hair and milk", "dry scales and eggs on land"], "moist skin and a life tied to water", 1),
  q("Reptile eggs on land are…", ["jelly masses only like frogs always", "amniotic", "never shelled in any reptile", "always laid in the sea"], "amniotic", 3),
  q("Monotremes lay eggs and include…", ["kangaroos and wallabies", "the platypus and echidnas", "koalas and wombats", "armadillos and anteaters"], "the platypus and echidnas", 2),
  q("Marsupials raise young in a…", ["nest of sticks only", "pouch (typically)", "hive", "shell"], "pouch (typically)", 1),
  q("The opossum is a…", ["monotreme of Australia", "marsupial of the Americas", "placental mammal of Africa", "small primate of the Americas"], "marsupial of the Americas", 2),
  q("The koala eats…", ["bamboo shoots", "eucalyptus leaves", "insect larvae", "flower nectar"], "eucalyptus leaves", 1),
  q("The giant panda eats…", ["eucalyptus", "bamboo", "krill", "ants only"], "bamboo", 1),
  q("The sloth lives in…", ["Arctic tundra", "Neotropical trees", "Saharan oases", "Antarctic coasts"], "Neotropical trees", 1),
  q("The capybara is the world's largest…", ["cat", "rodent", "bat", "marsupial"], "rodent", 2),
  q("The blue whale is the…", ["smallest cetacean", "largest animal known", "fastest fish", "tallest tree"], "largest animal known", 1),
  q("The cheetah is the…", ["largest living cat", "fastest land animal", "slowest wild cat", "only spotted cat"], "fastest land animal", 1),
  q("The peregrine falcon is famed as a…", ["flightless bird", "fast stooping bird", "largest eagle always", "penguin"], "fast stooping bird", 2),
  q("The ostrich is a…", ["flying hawk", "flightless bird of Africa", "penguin of the Arctic", "parrot of New Zealand only"], "flightless bird of Africa", 1),
  q("The kiwi is a…", ["parrot of Australia", "flightless bird of New Zealand", "eagle of North America", "penguin of Africa"], "flightless bird of New Zealand", 2),
  q("The dodo was a…", ["living eagle of Europe", "extinct flightless bird of Mauritius", "penguin of Antarctica", "parrot of New Zealand still living"], "extinct flightless bird of Mauritius", 1),
  q("Passenger pigeons were…", ["European garden birds still common", "North American birds, now extinct", "Antarctic seabirds, now endangered", "African ground birds, still common"], "North American birds, now extinct", 2),
  q("The ivory-billed woodpecker is…", ["a common backyard feeder bird of cities worldwide", "critically endangered or extinct (status debated)", "a penguin", "a European robin"], "critically endangered or extinct (status debated)", 3),
  q("Rachel Carson's Silent Spring warned about…", ["only nuclear war", "pesticides (especially DDT) and wildlife", "only overfishing of whales", "only climate models of the 2000s"], "pesticides (especially DDT) and wildlife", 2),
  q("DDT thinned the eggshells of…", ["earthworms", "birds of prey", "reef sharks", "sea turtles"], "birds of prey", 2),
  q("The Endangered Species Act is a law of the…", ["UN", "United States", "EU only", "Brazil only"], "United States", 2),
  q("CITES regulates…", ["local zoning near wildlife parks", "international trade in wildlife", "hunting seasons within each state", "coal mining on public lands"], "international trade in wildlife", 3),
  q("A watershed is the land that…", ["only sits above treeline", "drains to a river or lake", "is always a desert", "is the ocean floor"], "drains to a river or lake", 2),
  q("An aquifer is…", ["a cloud bank over a lake", "underground water-bearing rock", "a glacier high on a peak", "a tidal pool along the shore"], "underground water-bearing rock", 2),
  q("Permafrost is…", ["seasonal snow only", "ground frozen for years", "a kind of cloud", "warm sand"], "ground frozen for years", 1),
  q("A glacier is…", ["a frozen lake that never moves", "ice that moves under its weight", "only sea ice", "only frost on a window"], "ice that moves under its weight", 1),
  q("Calving of a glacier is…", ["growing trees on ice", "breaking off icebergs", "melting into rain only", "turning to permafrost"], "breaking off icebergs", 2),
  q("An iceberg is…", ["frozen seawater", "floating glacier ice", "low ice-crystal cloud", "buried salt dome"], "floating glacier ice", 1),
  q("Pack ice is…", ["glacier ice on a mountain", "sea ice", "river ice only", "frost"], "sea ice", 2),
  q("The timberline is…", ["the line where forest meets the sea", "the limit beyond which trees don't grow", "a border marked by planted trees", "the edge of a logging lease"], "the limit beyond which trees don't grow", 2),
  q("A riparian zone is…", ["on a glacier", "along a river", "in a desert far from water", "on a peak"], "along a river", 1),
  q("An estuary mixes…", ["only two glaciers", "fresh water and the sea", "only two deserts", "magma and air"], "fresh water and the sea", 1),
  q("A wetland might be a…", ["dune, mesa, or butte", "marsh, swamp, bog, or fen", "cliff, crag, or scree", "lava field or cinder cone"], "marsh, swamp, bog, or fen", 1),
  q("A bog is often…", ["a salt lagoon fed by the tide", "acid, peat-forming, fed by rain", "a coral atoll ringing a lagoon", "a geyser basin fed by hot springs"], "acid, peat-forming, fed by rain", 3),
  q("A fen is a peatland that is…", ["salty, fed by ocean tides", "less acid, fed by groundwater", "dry, fed only by rare storms", "frozen solid all year"], "less acid, fed by groundwater", 3),
  q("A swamp has…", ["grasses but no trees", "trees in standing water", "permafrost under moss", "shifting sand dunes"], "trees in standing water", 2),
  q("A marsh has…", ["a closed canopy of mahogany", "grasses and reeds, few trees", "only cacti", "only moss on peaks"], "grasses and reeds, few trees", 2),
  q("Peat is…", ["pure coal always as a synonym at the surface", "partly decayed plant matter", "lava", "pure sand"], "partly decayed plant matter", 2),
  q("Coal formed from…", ["dinosaur bones under heat and pressure", "ancient plants under heat and pressure", "evaporating seas that left salt", "cooled volcanic glass and ash"], "ancient plants under heat and pressure", 2),
  q("Petroleum formed chiefly from…", ["decayed dinosaur flesh and bones", "ancient plankton and organic muds", "melted granite deep underground", "rainwater trapped in rock"], "ancient plankton and organic muds", 2),
  q("Natural gas is often found with…", ["only glaciers", "oil", "only the ozone layer", "only granite plutons"], "oil", 1),
  q("The carbon cycle includes…", ["evaporation and precipitation", "photosynthesis and respiration", "nitrogen fixation by microbes", "ocean tides and currents"], "photosynthesis and respiration", 2),
  q("The nitrogen cycle depends on…", ["volcanoes venting nitrogen into the air", "microbes that fix, nitrify, and denitrify", "plants that absorb it from air", "weathering of granite bedrock"], "microbes that fix, nitrify, and denitrify", 3),
  q("Eutrophication is…", ["a drought that lowers lake levels", "nutrient over-enrichment of water", "a quake that shifts lake beds", "a fog that forms over lakes"], "nutrient over-enrichment of water", 3),
  q("A dead zone in the sea is often from…", ["too many coral reefs growing", "low oxygen after nutrient pollution", "too much sea ice in winter", "too many whales feeding there"], "low oxygen after nutrient pollution", 3),
  q("Bycatch is…", ["a kind of bait", "unwanted catch in fishing gear", "a kind of seaweed farm", "a kind of bird song"], "unwanted catch in fishing gear", 2),
  q("A keystone of kelp forests on the North American Pacific is often the…", ["camel", "sea otter (among others)", "lion", "penguin of the Arctic"], "sea otter (among others)", 2),
  q("Sea otters eat…", ["kelp fronds, their main food", "urchins, among other invertebrates", "krill, filtered like whales", "fish, caught like a cat would"], "urchins, among other invertebrates", 2),
  q("Urchins, unchecked, can…", ["plant kelp", "graze kelp to barrens", "build coral", "fix nitrogen on land"], "graze kelp to barrens", 3),
  q("Beavers are…", ["desert antelope", "ecosystem engineers of streams", "marine mammals of the open ocean", "flightless birds"], "ecosystem engineers of streams", 1),
  q("A lodge of a beaver is a…", ["nest in a tree cavity only", "house of sticks and mud", "hive", "burrow in dry sand only"], "house of sticks and mud", 1),
  q("Prairie dogs live in…", ["the deep sea", "colonies of burrows on grasslands", "the high canopy of rainforests", "Antarctica"], "colonies of burrows on grasslands", 1),
  q("Bison are native to…", ["Australian grasslands", "North American grasslands", "South American pampas", "African savannas"], "North American grasslands", 1),
  q("The passenger of the Great Plains' horse culture included the…", ["only whale hunt of the plains", "bison hunt", "only seal hunt", "only penguin hunt"], "bison hunt", 2),
  q("Fire on many prairies and pine savannas is…", ["always a disaster with no ecology", "a natural process that maintains them", "impossible because grass cannot burn", "only from lightning in rainforests"], "a natural process that maintains them", 3),
  q("Serotinous cones open with…", ["only frost", "heat / fire", "only moonlight", "only flood of the sea"], "heat / fire", 3),
  q("A nurse log is a…", ["living doctor of the forest as an animal", "fallen tree that seedlings grow on", "kind of fungus only", "kind of cloud"], "fallen tree that seedlings grow on", 2),
  q("Old-growth forest has…", ["young seedlings in neat rows", "large old trees and dead snags", "open grass with scattered shrubs", "bare rock and mosses"], "large old trees and dead snags", 2),
  q("A snag is a…", ["fallen log only", "standing dead tree", "seedling", "vine"], "standing dead tree", 2),
  q("The spotted owl is associated with…", ["dunes and oases of the Sahara", "old forests of the Pacific Northwest", "ice shelves of the Antarctic", "coral atolls of the South Pacific"], "old forests of the Pacific Northwest", 3),
  q("The whooping crane was saved in part by…", ["introducing cats to nests", "captive breeding and habitat protection", "draining all wetlands", "banning all flyways of other birds only"], "captive breeding and habitat protection", 2),
  q("The California condor was brought back by…", ["only hope with no program", "captive breeding", "introducing DDT", "hunting bounties"], "captive breeding", 2),
  q("Island species often evolve…", ["faster wings always and no risk", "in isolation and are vulnerable to invaders", "only as fish", "only as whales"], "in isolation and are vulnerable to invaders", 2),
  q("Darwin's finches of the Galápagos show…", ["identical beaks on all islands", "beak shapes matching foods", "that birds cannot evolve", "that all finches eat only fish"], "beak shapes matching foods", 2),
  q("The Galápagos are in the…", ["Atlantic off Africa", "Pacific, off Ecuador", "Indian Ocean off India", "Arctic"], "Pacific, off Ecuador", 2),
  q("Madagascar is famed for…", ["native kangaroos and wallabies", "lemurs and other endemic lineages", "polar bears and walruses", "native tigers and elephants"], "lemurs and other endemic lineages", 1),
  q("New Zealand had no native…", ["flightless birds", "land mammals except bats", "insects or spiders", "flowering plants"], "land mammals except bats", 3),
  q("Australia's native mammals are mostly…", ["primates and apes", "marsupials and monotremes", "hoofed grazers and big cats", "otters and seals"], "marsupials and monotremes", 2),
  q("The duck-billed platypus is a…", ["marsupial with a pouch", "monotreme that lays eggs", "placental otter relative", "bird with fur and a bill"], "monotreme that lays eggs", 2),
  q("Echidnas eat…", ["eucalyptus leaves", "ants and termites", "small fish", "bamboo shoots"], "ants and termites", 2),
];

