import { q } from "../quiz";
import type { TriviaQ } from "../types";

export const NATURE_LIFE: TriviaQ[] = [
  q("Tarantulas belong to which spider family?", ["Lycosidae", "Theraphosidae", "Salticidae", "Araneidae"], "Theraphosidae", 3),
  q("Tarantulas are in the infraorder…", ["Araneomorphae", "Mygalomorphae", "Opiliones", "Scorpiones"], "Mygalomorphae", 3),
  q("A tarantula is a…", ["insect (hexapod)", "spider (arachnid)", "crustacean (decapod)", "myriapod (centipede kin)"], "spider (arachnid)", 1),
  q("How many legs does a tarantula have?", ["6", "8", "10", "12"], "8", 1),
  q("A tarantula's body has two main parts: the front cephalothorax and the rear…", ["tail", "abdomen", "wing case", "mantle"], "abdomen", 1),
  q("The narrow waist joining a tarantula's body parts is the…", ["petiole of an ant", "pedicel", "scape", "telson"], "pedicel", 3),
  q("Tarantula fangs are on the…", ["pedipalps only", "chelicerae", "spinnerets", "book lungs"], "chelicerae", 3),
  q("Mygalomorph fangs strike…", ["sideways like a crab's claw always", "down and parallel (not pincer-style)", "backward only", "up through the cephalothorax"], "down and parallel (not pincer-style)", 3),
  q("A tarantula breathes with…", ["a tracheal tube like a beetle only", "book lungs", "gills", "a diaphragm"], "book lungs", 3),
  q("Most tarantulas have how many pairs of book lungs?", ["one pair", "two pairs", "three pairs", "none — they use spiracles only"], "two pairs", 3),
  q("Silk in a tarantula comes from…", ["the fangs", "spinnerets", "the book lungs", "the eyes"], "spinnerets", 1),
  q("A tarantula typically has how many eyes?", ["2", "4", "6", "8"], "8", 2),
  q("The 'hands' in front of a tarantula's legs are…", ["antennae", "pedipalps", "maxillae", "cerci"], "pedipalps", 3),
  q("Tarantulas grow by…", ["adding bone", "molting (ecdysis)", "budding", "shedding only hair"], "molting (ecdysis)", 1),
  q("A fresh molt leaves behind an…", ["egg sac only", "exuvium (shed skin)", "sperm web only", "book lung"], "exuvium (shed skin)", 3),
  q("Before a molt a tarantula often…", ["spins a bird nest", "goes off food and darkens", "loses all legs as a rule", "turns bright green always"], "goes off food and darkens", 3),
  q("A 'bald butt' on a New World tarantula usually means it has…", ["just drunk water", "kicked urticating hairs", "laid eggs", "lost its spinnerets"], "kicked urticating hairs", 3),
  q("Urticating hairs are…", ["venom crystals on the fangs", "barbed defensive bristles", "silk strands for webbing", "plates inside the book lungs"], "barbed defensive bristles", 3),
  q("Most New World tarantulas defend first by…", ["spraying acid from the rear", "kicking urticating hairs", "playing dead on their backs", "squirting ink like a squid"], "kicking urticating hairs", 3),
  q("Old World tarantulas generally…", ["kick the worst hairs", "lack urticating hairs", "have no venom", "have six legs"], "lack urticating hairs", 3),
  q("New World tarantulas are native to…", ["Africa and Asia only", "the Americas", "Australia only", "Europe only"], "the Americas", 1),
  q("Old World tarantulas are native to…", ["the Amazon and the Andes", "Africa, Asia, and Australia", "Mexico and Central America", "the Caribbean islands"], "Africa, Asia, and Australia", 1),
  q("Old World tarantulas are often…", ["slower and hair-kicking", "faster and more defensive", "unable to bite", "blind"], "faster and more defensive", 3),
  q("A threat pose in a tarantula is…", ["rolling into a ball only", "rearing and showing fangs", "flashing wings", "playing a silk drum only"], "rearing and showing fangs", 1),
  q("Stridulation in tarantulas is a…", ["chirping bird-like call", "hiss or rasp from bristles", "sudden change of color", "flash of light from the eyes"], "hiss or rasp from bristles", 3),
  q("A baby spider is called a…", ["fledgling", "spiderling", "caterpillar", "calf"], "spiderling", 1),
  q("The stage between molts is an…", ["imago only in spiders", "instar", "chrysalis", "tadpole"], "instar", 3),
  q("An adult male tarantula often has…", ["a pair of wings and a longer life", "bulbed pedipalps and a shorter life", "no fangs and a longer life", "a tail stinger like a scorpion's"], "bulbed pedipalps and a shorter life", 3),
  q("Tibial hooks on many male tarantulas help…", ["dig deeper burrows faster", "hold the female during mating", "kick hairs at predators", "spin silk for egg sacs"], "hold the female during mating", 3),
  q("A male tarantula charges his palps from a…", ["book lung", "sperm web", "egg sac", "water dish"], "sperm web", 3),
  q("Females store sperm in…", ["the spinnerets", "spermathecae", "the eyes", "the fangs"], "spermathecae", 3),
  q("Eggs are guarded in a…", ["mud nest of a wasp", "silken egg sac", "foam raft", "hollow bone"], "silken egg sac", 1),
  q("Female tarantulas typically live…", ["only weeks as a rule", "many years longer than males", "the same few months as males always", "one season like a mayfly"], "many years longer than males", 3),
  q("Some female terrestrial tarantulas can live…", ["about a year always", "20–30+ years in captivity", "a weekend", "as long as a mayfly"], "20–30+ years in captivity", 3),
  q("A fossorial tarantula is a…", ["tree-dweller only", "burrower", "swimmer", "parasite of mammals"], "burrower", 3),
  q("An arboreal tarantula lives…", ["in deep desert burrows", "in trees, often in silk tubes", "underwater in rainforest streams", "in ice caves of high mountains"], "in trees, often in silk tubes", 1),
  q("A terrestrial beginner tank should not be too…", ["dark", "tall (falls can split the abdomen)", "equipped with a water dish", "equipped with soil"], "tall (falls can split the abdomen)", 3),
  q("Keepers usually give a tarantula a…", ["salt block", "shallow water dish", "cuttlebone only", "UVB lamp as a must for all species"], "shallow water dish", 3),
  q("Tarantulas eat chiefly…", ["leaves and soft plant shoots", "invertebrates such as crickets", "nectar from night flowers", "blood from sleeping mammals"], "invertebrates such as crickets", 1),
  q("Despite the name, 'bird-eating' tarantulas mostly eat…", ["birds taken from nests", "large invertebrates", "fallen fruit", "fish from streams"], "large invertebrates", 2),
  q("The largest tarantula by mass is generally…", ["Lasiodora parahybana (salmon pink)", "Theraphosa blondi (Goliath birdeater)", "Brachypelma hamorii (red knee)", "Poecilotheria metallica (Gooty)"], "Theraphosa blondi (Goliath birdeater)", 2),
  q("The Goliath birdeater tarantula is native to…", ["southern Africa's Kalahari", "northern South America", "the Gobi of Mongolia", "Alaska's interior"], "northern South America", 2),
  q("The Goliath birdeater is famed for…", ["having no fangs", "huge size and strong urticating hairs", "living in the Arctic", "being an Old World species of Africa"], "huge size and strong urticating hairs", 2),
  q("Chromatopelma cyaneopubescens is the…", ["orange baboon (OBT)", "green bottle blue (GBB)", "curly hair (Tliltocatl)", "Mexican red knee"], "green bottle blue (GBB)", 3),
  q("The green bottle blue is native to…", ["Madagascar", "Venezuela", "Japan", "New Zealand"], "Venezuela", 3),
  q("A GBB is famous in the hobby for…", ["black legs, red abdomen, and no silk", "blue legs, orange abdomen, heavy webbing", "living under ice in mountain streams", "being an Old World baboon species"], "blue legs, orange abdomen, heavy webbing", 3),
  q("Brachypelma hamorii is the classic…", ["Martinique pinktoe of the pet trade", "Mexican red-knee of the pet trade", "Gooty ornamental of the pet trade", "Socotra blue baboon of the pet trade"], "Mexican red-knee of the pet trade", 3),
  q("Brachypelma species are native to…", ["Australia", "Mexico", "Congo", "Siberia"], "Mexico", 3),
  q("Many Brachypelma species are listed on…", ["the U.S. Flag Code", "CITES", "FIFA", "NATO"], "CITES", 3),
  q("Tliltocatl albopilosus is the hobby…", ["GBB", "curly hair", "OBT", "sun tiger"], "curly hair", 3),
  q("The curly hair was moved out of Brachypelma into…", ["Poecilotheria", "Tliltocatl", "Theraphosa", "Pterinochilus"], "Tliltocatl", 3),
  q("Tliltocatl vagans is the…", ["Chilean rose", "Mexican red rump", "Togo starburst", "Gooty"], "Mexican red rump", 3),
  q("Grammostola pulchra is the…", ["pinktoe", "Brazilian black", "baboon", "ornamental of India"], "Brazilian black", 3),
  q("Grammostola pulchra is prized as a…", ["fast, skittish Old World arboreal", "slow, velvety-black beginner terrestrial", "fish-eating, semi-aquatic spider", "small, venomous desert scorpion"], "slow, velvety-black beginner terrestrial", 3),
  q("The Chilean rose hair of the pet trade is a…", ["Poecilotheria", "Grammostola", "Heteroscodra", "Ceratogyrus"], "Grammostola", 3),
  q("Aphonopelma chalcodes is a tarantula of the…", ["Congo Basin / central Africa", "U.S. Southwest / Sonoran region", "Siberia / Russian Far East", "New Zealand / South Island"], "U.S. Southwest / Sonoran region", 3),
  q("Aphonopelma is the main native tarantula genus of the…", ["Madagascar only", "United States", "Japan only", "Ireland"], "United States", 3),
  q("Lasiodora parahybana is the…", ["Honduran curly hair", "salmon pink birdeater", "Mexican red knee", "Asian sun tiger"], "salmon pink birdeater", 3),
  q("Lasiodora parahybana is native to…", ["India", "Brazil", "South Africa", "Spain"], "Brazil", 3),
  q("Caribena versicolor is the…", ["orange baboon tarantula (OBT)", "Antilles / Martinique pinktoe", "East African horned baboon", "Thai black earth tiger"], "Antilles / Martinique pinktoe", 3),
  q("Caribena versicolor slings are famously…", ["bright red until their first molt", "metallic blue before they color up", "striped like a wasp to warn birds", "see-through until they color up"], "metallic blue before they color up", 3),
  q("Avicularia-group pinktoes are…", ["Old World burrowers", "New World arboreals", "African baboons", "desert blondes of Arizona only"], "New World arboreals", 3),
  q("Psalmopoeus irminia is the…", ["Brazilian black", "Venezuelan suntiger", "curly hair", "red knee"], "Venezuelan suntiger", 3),
  q("Psalmopoeus cambridgei is associated with…", ["Madagascar", "Trinidad", "Japan", "Alaska"], "Trinidad", 3),
  q("Psalmopoeus are New World arboreals that typically…", ["live in the deserts of the Gobi", "lack kickable urticating hairs", "have no venom glands at all", "hunt fish in tidal pools"], "lack kickable urticating hairs", 3),
  q("Ephebopus species are unusual New World tarantulas because some have…", ["wings folded under the carapace", "urticating hairs on the palps", "a stinger at the abdomen tip", "only six walking legs"], "urticating hairs on the palps", 3),
  q("Type II urticating hairs (Avicularia group) are often…", ["woven into webs to trap prey", "transferred by contact, not kicked", "tipped with venom crystals", "found on Old World species instead"], "transferred by contact, not kicked", 3),
  q("Poecilotheria are the…", ["pinktoe tarantulas of Brazil and Peru", "ornamental tarantulas of India and Sri Lanka", "desert blonde tarantulas of Arizona", "baboon tarantulas of East Africa"], "ornamental tarantulas of India and Sri Lanka", 3),
  q("Poecilotheria are…", ["slow Mexican terrestrials with mild venom", "Old World arboreals with strong venom", "sea spiders of cold coastal waters", "scorpions of the Indian subcontinent"], "Old World arboreals with strong venom", 3),
  q("Poecilotheria metallica is the…", ["Mexican red rump", "Gooty ornamental", "Honduran curly hair", "salmon pink birdeater"], "Gooty ornamental", 3),
  q("Pterinochilus murinus is the hobby…", ["GBB", "OBT", "pinktoe", "red knee"], "OBT", 3),
  q("Pterinochilus murinus is native to…", ["Central Mexico", "East Africa", "northern Chile", "South Florida"], "East Africa", 3),
  q("An 'OBT' is widely treated as…", ["a perfect first-handling species", "an advanced, defensive Old World terrestrial", "a fish", "a millipede"], "an advanced, defensive Old World terrestrial", 3),
  q("Ceratogyrus species are African tarantulas nicknamed…", ["pinktoes", "horned baboons", "red knees", "curly hairs"], "horned baboons", 3),
  q("The 'horn' on some Ceratogyrus is on the…", ["spinnerets (tip)", "carapace (fovea)", "fangs (chelicerae)", "each tarsus (foot)"], "carapace (fovea)", 3),
  q("Heteroscodra maculata is the…", ["Chilean rose", "Togo starburst", "Brazilian black", "desert blonde"], "Togo starburst", 3),
  q("Heteroscodra maculata is a…", ["slow Mexican red-knee", "fast African arboreal", "Arizona desert blonde", "Martinique pinktoe"], "fast African arboreal", 3),
  q("Monocentropus balfouri is the…", ["Gooty ornamental", "Socotra Island blue", "OBT", "GBB"], "Socotra Island blue", 3),
  q("Socotra, home of M. balfouri, is in the…", ["eastern Caribbean (Antilles)", "northwest Indian Ocean (Yemen)", "Great Lakes (Lake Superior)", "Baltic Sea (Gulf of Finland)"], "northwest Indian Ocean (Yemen)", 3),
  q("Asian 'earth tiger' tarantulas are often in…", ["Aphonopelma", "Cyriopagopus", "Grammostola", "Tliltocatl"], "Cyriopagopus", 3),
  q("Haplopelma / Cyriopagopus are…", ["New World desert blondes of Arizona", "Old World fossorials of Southeast Asia", "arboreal pinktoes of Martinique", "Chilean rose hairs of the Andes"], "Old World fossorials of Southeast Asia", 3),
  q("A 'baboon' tarantula in hobby talk is usually…", ["a Mexican New World terrestrial", "an African Old World theraphosid", "a Venezuelan green bottle blue", "a Central American curly hair"], "an African Old World theraphosid", 3),
  q("A 'pinktoe' in hobby talk is usually…", ["an orange baboon from Africa", "an arboreal Avicularia / Caribena type", "a horned baboon from East Africa", "a Gooty ornamental from India"], "an arboreal Avicularia / Caribena type", 3),
  q("A 'birdeater' in hobby talk is often…", ["a small jumping spider of houses", "a huge South American terrestrial", "a scorpion that eats nestlings", "a giant millipede of the forest"], "a huge South American terrestrial", 3),
  q("The tarantula hawk is a…", ["bird that only eats silk", "wasp that hunts tarantulas", "beetle that farms aphids", "moth"], "wasp that hunts tarantulas", 1),
  q("A tarantula hawk wasp lays an egg on a…", ["leaf only", "paralyzed tarantula", "rotten log only", "pond"], "paralyzed tarantula", 2),
  q("Tarantulas are not…", ["arachnids", "insects", "spiders", "mygalomorphs"], "insects", 1),
  q("Unlike insects, spiders lack…", ["an exoskeleton", "antennae", "a brain of any kind", "eyes of any kind"], "antennae", 2),
  q("Scopulae on tarantula feet are…", ["stingers that inject venom", "pads of fine hairs that help grip", "book lungs for breathing", "egg teeth for hatching"], "pads of fine hairs that help grip", 3),
  q("Trichobothria are…", ["ducts that carry venom to the fangs", "fine hairs that sense air movement", "glands that make silk", "fangs that fold under the head"], "fine hairs that sense air movement", 3),
  q("A tarantula's 'baldness' after kicking hairs will look better after…", ["drinking oil", "the next molt", "a salt bath", "losing a leg"], "the next molt", 3),
  q("Lost legs in tarantulas can be…", ["never replaced at all", "regrown over later molts", "replaced by silk props", "replaced by extra spinnerets"], "regrown over later molts", 3),
  q("A 'DLS' in hobby talk is a…", ["double-length spinneret", "death curl (legs drawn under)", "dry leaf-litter substrate", "daylight lamp spectrum"], "death curl (legs drawn under)", 3),
  q("Humidity for a rainforest sling is often kept up with…", ["a hair dryer on a low setting", "a water dish and slightly damp substrate", "ice cubes melting on the substrate", "table salt sprinkled to hold moisture"], "a water dish and slightly damp substrate", 3),
  q("An obligatory burrower wants…", ["a tall, empty enclosure to climb", "deep substrate it can tunnel in", "open water to swim in like a fish", "bare floor with no substrate at all"], "deep substrate it can tunnel in", 3),
  q("An arboreal wants…", ["only two inches of packed clay and no cork", "height, cork / bark, and a water dish", "a wheel", "UVB desert lamps as a must"], "height, cork / bark, and a water dish", 3),
  q("The World Spider Catalog is a standard reference for…", ["bird song recordings", "spider taxonomy", "rock and mineral types", "star names"], "spider taxonomy", 3),
  q("Theraphosidae was named in the 19th century by…", ["Linnaeus", "Thorell", "Darwin", "Wallace"], "Thorell", 3),
  q("A mature male's search is called…", ["estivation / a summer sleep", "roaming / a breeding ramble", "a bird migration south", "a molt sack / a premolt rest"], "roaming / a breeding ramble", 3),
  q("Keepers sex tarantulas by…", ["counting the eyes on the carapace", "examining a molt or the underside", "weighing the silk they spin", "listening for their stridulation"], "examining a molt or the underside", 3),
  q("A spermatheca molt confirms…", ["an Old World species only", "a female (in species that show them)", "dehydration", "a sling's instar as a number"], "a female (in species that show them)", 3),
  q("Rehousing a tarantula is safest with…", ["bare hands on the abdomen", "a catch cup and patience", "a handheld vacuum on low", "a dunk in ice water first"], "a catch cup and patience", 3),
  q("Handling is…", ["required daily to keep it tame", "optional and risky for the spider", "needed so that they will eat", "the usual way to sex them"], "optional and risky for the spider", 3),
  q("New World bites are usually…", ["as deadly as a taipan's bite", "painful but medically minor", "impossible, since they lack venom", "completely painless"], "painful but medically minor", 3),
  q("Some Old World bites can cause…", ["only a tickle", "severe pain and muscle cramps for hours to days", "instant silk blindness in all cases", "no symptoms ever"], "severe pain and muscle cramps for hours to days", 3),
  q("No tarantula venom is known to be…", ["painful to humans at all", "routinely lethal to healthy humans", "present in their fangs", "delivered through their fangs"], "routinely lethal to healthy humans", 2),
  q("The 'tarantella' dance legend is tied to…", ["Mexican red-knees brought to the Alps", "wolf spiders and tarantism in southern Italy", "green bottle blues traded in Venice", "baboon tarantulas native to Rome"], "wolf spiders and tarantism in southern Italy", 3),
  q("A wolf spider is in family…", ["Theraphosidae", "Lycosidae", "Scorpionidae", "Ixodidae"], "Lycosidae", 3),
  q("A tarantula is not a…", ["true spider (Araneae)", "scorpion, harvestman, or tick", "mygalomorph spider", "member of the Arachnida"], "scorpion, harvestman, or tick", 1),
  q("The pedipalp of a mature male carries the…", ["book lung", "embolus", "egg sac", "urticating comb"], "embolus", 3),
  q("The hairs a tarantula flicks in defense can irritate a person's…", ["only other spiders' silk", "skin, eyes, and airways", "only plants", "only steel"], "skin, eyes, and airways", 1),
  q("Hobby first-aid for hairs is often…", ["rubbing the skin with sandpaper", "tape to lift them, then flush", "a salt pack on the skin", "ignoring hairs in the eyes"], "tape to lift them, then flush", 3),
  q("A just-molted tarantula is…", ["hungry and should be fed a mouse at once", "soft; wait to feed until fangs harden", "ready to be handled straight away", "dead if it lies on its back"], "soft; wait to feed until fangs harden", 3),
  q("The fangs after a molt need time to…", ["grow feathers", "sclerotize (harden)", "turn into spinnerets", "fall out"], "sclerotize (harden)", 3),
  q("Overfeeding a tarantula can lead to…", ["a pair of wings at the next molt", "a swollen abdomen and a riskier molt", "extra eyes on the carapace", "a total loss of silk"], "a swollen abdomen and a riskier molt", 3),
  q("A water dish helps prevent…", ["molting", "dehydration", "spinning silk", "color"], "dehydration", 3),
  q("Substrate in a terrestrial tank is often…", ["aquarium gravel and sand", "coco fiber or topsoil", "standing water", "bare concrete"], "coco fiber or topsoil", 3),
  q("Cross-ventilation in an enclosure helps…", ["cook the spider", "avoid stagnant, moldy air", "dry the book lungs to dust as a goal", "attract wasps"], "avoid stagnant, moldy air", 3),
  q("The Tarantula Collective is a…", ["NASCAR team from North Carolina", "husbandry channel for keepers", "regional airline in Texas", "credit union for veterinarians"], "husbandry channel for keepers", 3),
  q("Captive-bred slings are preferred over wild-caught because…", ["wild-caught animals live longer in captivity", "wild collection can pressure populations", "captive-bred slings come with venom removed", "wild-caught animals carry no venom"], "wild collection can pressure populations", 3),
  q("A 'CB' sling means…", ["color-blind", "captive-bred", "cave-burrower", "Chilean-black"], "captive-bred", 3),
  q("A 'WC' animal is…", ["well-cared-for as a legal term", "wild-caught", "white-carapace morph", "water-cursorial"], "wild-caught", 3),
  q("Taxonomy in tarantulas moves often because…", ["they are reclassified as insects", "genera get split by new DNA studies", "their species change with each molt", "hobby names are the official code"], "genera get split by new DNA studies", 3),
  q("Tliltocatl was split from Brachypelma in…", ["1900", "1980", "2020", "1758"], "2020", 3),
  q("A 'red knee' in older guides may be labeled B. smithi; the common pet form is now usually…", ["Poecilotheria metallica", "Brachypelma hamorii", "Pterinochilus murinus", "Theraphosa blondi"], "Brachypelma hamorii", 3),
  q("Grammostola names in the pet trade (rosea / porteri) are…", ["perfectly one species since Linnaeus", "historically mixed up among species", "names for African baboon species", "names borrowed from tropical fish"], "historically mixed up among species", 3),
  q("A heavy webber like a GBB will often…", ["never silk", "coat cork and walls in silk", "build a paper wasp nest", "spin a round orb like an araneid"], "coat cork and walls in silk", 3),
  q("Orb-weaving garden spiders are…", ["theraphosid tarantulas", "araneomorphs, not tarantulas", "scorpions, not spiders", "solifuges, not spiders"], "araneomorphs, not tarantulas", 3),
  q("A solifuge (camel spider) is…", ["a member of the Theraphosidae", "an arachnid, but not a true spider", "a true scorpion with a stinger", "a harvestman (daddy longlegs)"], "an arachnid, but not a true spider", 3),
  q("Harvestmen (daddy longlegs) are…", ["Theraphosidae tarantulas", "Opiliones, not true spiders", "ticks and mites", "true insects"], "Opiliones, not true spiders", 3),
  q("Ticks are…", ["baby tarantulas before the first molt", "arachnids related to mites, not insects", "wingless insects related to lice", "land crustaceans related to woodlice"], "arachnids related to mites, not insects", 2),
  q("Scorpions are arachnids that…", ["are tarantulas with eight extra legs", "have a stinging tail; tarantulas do not", "spin orb webs as a rule", "have six legs"], "have a stinging tail; tarantulas do not", 1),
  q("Both scorpions and tarantulas are…", ["insects", "arachnids", "myriapods", "annelids"], "arachnids", 1),
  q("Amblypygi are…", ["true tarantulas of Africa", "tailless whip scorpions", "giant millipedes", "long-legged beetles"], "tailless whip scorpions", 3),
  q("Uropygids (vinegaroons) can spray…", ["silk as a spray", "acetic acid", "ink", "hot wax"], "acetic acid", 3),
  q("A tarantula's food is typically offered with…", ["bare fingers", "tongs, not fingers", "a fishing hook", "a dab of glue"], "tongs, not fingers", 3),
  q("Uneaten prey should be…", ["left in the enclosure", "removed after a day", "doubled the next feeding", "salted to preserve it"], "removed after a day", 3),
  q("A hide for a terrestrial can be…", ["a hamster wheel and tunnel set", "cork bark or a half log", "an open heat lamp over a rock", "a deep pool to soak and swim in"], "cork bark or a half log", 3),
  q("Light for a tarantula should be…", ["full desert UV lighting", "ordinary room light", "total darkness all day", "a heat lamp aimed down"], "ordinary room light", 3),
  q("Temperatures in the mid 20s °C suit…", ["polar species from the tundra", "many common pet species", "storage in an ice box", "eggs kept near freezing"], "many common pet species", 3),
  q("A 'dry' species still usually needs…", ["no water ever", "a water dish; dry is not desiccated", "a swamp of standing water", "salt water"], "a water dish; dry is not desiccated", 3),
  q("The abdomen is fragile because it is…", ["made of bone that can crack", "soft and can rupture in a fall", "hollow and filled with air", "covered in a turtle-like shell"], "soft and can rupture in a fall", 3),
  q("The carapace is the…", ["silk egg sac of the female", "hard dorsal plate of the cephalothorax", "folded book lung of the abdomen", "silk mat lining the burrow"], "hard dorsal plate of the cephalothorax", 3),
  q("The fovea is a…", ["spinneret", "pit on the carapace", "fang socket of the pedipalp", "eye of a young sling"], "pit on the carapace", 3),
  q("Tarantulas do not have…", ["fangs or venom glands", "antennae, wings, or a sting", "silk or spinnerets", "an exoskeleton or legs"], "antennae, wings, or a sting", 1),
  q("Most tarantulas hunt as…", ["pack wolves", "ambush predators", "filter feeders", "grazers of grass"], "ambush predators", 1),
  q("A tarantula senses prey with…", ["echolocation clicks like a bat", "vibration and air movement", "sonar pulses like a dolphin", "heat-sensing pits like a pit viper"], "vibration and air movement", 2),
  q("Molting frequency is highest in…", ["ancient females that never grow", "slings", "mature males after the last molt as a weekly habit", "egg sacs"], "slings", 3),
  q("A mature male's last molt is often his…", ["first instar", "ultimate molt — he is then on a short clock", "egg", "a second childhood of 20 years as a rule"], "ultimate molt — he is then on a short clock", 3),
  q("Display, not handling, is the point of a…", ["pet dog for most owners", "pet tarantula for most keepers", "show horse for most riders", "hunting falcon for falconers"], "pet tarantula for most keepers", 3),
  q("Chromatopelma cyaneopubescens is native to…", ["Colombia", "East Africa", "South America (Chaco region)", "Venezuela"], "Venezuela", 3),
  q("Brachypelma hamorii is native to…", ["southern Africa", "the south-central United States", "northern South America", "Mexico"], "Mexico", 3),
  q("Tliltocatl albopilosus is native to…", ["West Africa", "Central America", "northwestern South America", "Southeast Asia"], "Central America", 3),
  q("Grammostola pulchra is native to…", ["Central America", "Venezuela", "Brazil", "India"], "Brazil", 3),
  q("Aphonopelma chalcodes is native to…", ["Venezuela", "the U.S. Southwest", "southern Africa", "northwestern South America"], "the U.S. Southwest", 3),
  q("Poecilotheria metallica is native to…", ["South America (Chaco region)", "Venezuela", "Hispaniola", "India"], "India", 3),
  q("Caribena versicolor is native to…", ["West Africa", "Martinique", "Southeast Asia", "Trinidad"], "Martinique", 3),
  q("Psalmopoeus irminia is native to…", ["the south-central United States", "West Africa", "Venezuela", "Southeast Asia"], "Venezuela", 3),
  q("Monocentropus balfouri is native to…", ["Socotra", "Brazil", "Amazonian South America", "South Africa"], "Socotra", 3),
  q("Heteroscodra maculata is native to…", ["Mexico", "Central America", "West Africa", "the U.S. Southwest"], "West Africa", 3),
  q("Ceratogyrus darlingi is native to…", ["northwestern South America", "southern Africa", "Hispaniola", "Socotra"], "southern Africa", 3),
  q("Grammostola pulchripes is native to…", ["South America (Chaco region)", "Brazil", "northwestern South America", "the U.S. Southwest"], "South America (Chaco region)", 3),
  q("Nhandu chromatus is native to…", ["Venezuela", "Brazil", "South Africa", "Central America"], "Brazil", 3),
  q("Acanthoscurria geniculata is native to…", ["Trinidad", "East Africa", "Brazil", "India"], "Brazil", 3),
  q("Megaphobema mesomelas is native to…", ["the south-central United States", "the U.S. Southwest", "northern South America", "Costa Rica"], "Costa Rica", 3),
  q("Sericopelma sp. (typical) is native to…", ["Socotra", "Central America", "East Africa", "Brazil"], "Central America", 3),
  q("Eupalaestrus campestratus is native to…", ["southern Africa", "northwestern South America", "southern South America", "East Africa"], "southern South America", 3),
  q("Harpactira pulchripes is native to…", ["South Africa", "northwestern South America", "Amazonian South America", "South America (Chaco region)"], "South Africa", 3),
  q("Pelinobius muticus is native to…", ["South Africa", "Brazil", "northern South America", "East Africa"], "East Africa", 3),
  q("Stromatopelma calceatum is native to…", ["West Africa", "the south-central United States", "South Africa", "northern South America"], "West Africa", 3),
  q("Encyocratella olivacea is native to…", ["West Africa", "Tanzania / East Africa", "northwestern South America", "Central America"], "Tanzania / East Africa", 3),
  q("Omothymus violaceopes is native to…", ["Southeast Asia", "southern South America", "Socotra", "Tanzania / East Africa"], "Southeast Asia", 3),
  q("Aphonopelma hentzi is native to…", ["northwestern South America", "the south-central United States", "Central America", "West Africa"], "the south-central United States", 3),
  q("Brachypelma boehmei is native to…", ["Mexico", "Trinidad", "Hispaniola", "Southeast Asia"], "Mexico", 3),
  q("Brachypelma auratum is native to…", ["Central America", "Martinique", "Mexico", "the U.S. Southwest"], "Mexico", 3),
  q("Pterinopelma sazimai is native to…", ["West Africa", "the U.S. Southwest", "Brazil", "Costa Rica"], "Brazil", 3),
  q("Cyriopagopus lividus is native to…", ["Southeast Asia", "India", "Martinique", "South America (Chaco region)"], "Southeast Asia", 3),
  q("Avicularia avicularia is native to…", ["East Africa", "southern Africa", "northern South America", "southern South America"], "northern South America", 3),
  q("Davus fasciatus is native to…", ["West Africa", "Martinique", "Colombia", "Costa Rica"], "Costa Rica", 3),
  q("Poecilotheria regalis is native to…", ["Venezuela", "India", "southern Africa", "Southeast Asia"], "India", 3),
  q("Phormictopus cancerides is native to…", ["South America (Chaco region)", "Socotra", "southern South America", "Hispaniola"], "Hispaniola", 3),
  q("Hapalopus formosus is native to…", ["Colombia", "Hispaniola", "Socotra", "Southeast Asia"], "Colombia", 3),
  q("Theraphosa stirmi is native to…", ["the south-central United States", "India", "northern South America", "the U.S. Southwest"], "northern South America", 3),
  q("Xenesthis immanis is native to…", ["East Africa's coastal forests", "northwestern South America", "Socotra, off Yemen", "Southeast Asia's rainforests"], "northwestern South America", 3),
  q("Psalmopoeus cambridgei is native to…", ["South America (Chaco region)", "Socotra", "Trinidad", "the U.S. Southwest"], "Trinidad", 3),
  q("Sharks are in class…", ["Osteichthyes", "Chondrichthyes", "Mammalia", "Aves"], "Chondrichthyes", 1),
  q("A shark's skeleton is mostly…", ["bone", "cartilage", "chitin", "silica"], "cartilage", 1),
  q("Sharks and rays together are…", ["teleosts only", "elasmobranchs", "lampreys", "hagfish only"], "elasmobranchs", 2),
  q("Rays and skates are…", ["relatives of whales and dolphins", "close relatives of sharks, not bony fish", "amphibians that never leave water", "reptiles related to sea turtles"], "close relatives of sharks, not bony fish", 1),
  q("The largest living fish is the…", ["great white", "whale shark", "bluefin tuna", "oarfish"], "whale shark", 1),
  q("The whale shark eats chiefly as a…", ["apex biter of seals only", "filter feeder", "coral grazer only", "kelp cutter"], "filter feeder", 1),
  q("The fastest shark is often listed as the…", ["nurse shark", "shortfin mako", "wobbegong", "angel shark"], "shortfin mako", 2),
  q("Great whites belong to the genus…", ["Galeocerdo", "Carcharodon", "Sphyrna", "Rhincodon"], "Carcharodon", 2),
  q("Tiger sharks belong to the genus…", ["Carcharodon", "Galeocerdo", "Rhincodon", "Cetorhinus"], "Galeocerdo", 3),
  q("Hammerheads belong to the genus…", ["Pristis (sawfish)", "Sphyrna (and Eusphyra)", "Manta (manta rays)", "Lamna (porbeagles)"], "Sphyrna (and Eusphyra)", 2),
  q("The basking shark is a…", ["freshwater stingray of the Amazon", "filter-feeding giant of cool seas", "tiny goby of coral reefs", "reef parrotfish that eats coral"], "filter-feeding giant of cool seas", 2),
  q("The megamouth shark is a…", ["river dolphin", "rare filter feeder", "penguin", "seal"], "rare filter feeder", 3),
  q("The goblin shark is known for…", ["armor plates like a sturgeon", "a protruding snout and slingshot jaws", "walking on land nightly as a rule", "freshwater only"], "a protruding snout and slingshot jaws", 3),
  q("The cookiecutter shark feeds by…", ["filtering krill only", "cutting round plugs of flesh", "grazing seagrass", "drilling wood"], "cutting round plugs of flesh", 2),
  q("The Greenland shark is famed for…", ["being the fastest fish", "extreme longevity (centuries)", "living only in coral atolls", "having bones like a tuna"], "extreme longevity (centuries)", 2),
  q("Bull sharks are notable for…", ["having no teeth", "entering fresh water", "being filter feeders only", "lacking a liver"], "entering fresh water", 2),
  q("Nurse sharks are typically…", ["open-ocean sprinters", "sluggish bottom-dwellers", "freshwater eels", "flying fish"], "sluggish bottom-dwellers", 1),
  q("Wobbegongs are…", ["hammerheads with wide, flat heads", "carpet sharks with camouflage tassels", "stingrays with venomous tail spines", "lampreys with sucking disc mouths"], "carpet sharks with camouflage tassels", 3),
  q("Angel sharks are…", ["true rays with venomous stings", "flattened, ray-like ambush sharks", "eels that burrow in sand", "chimaeras of the deep sea"], "flattened, ray-like ambush sharks", 3),
  q("A sawshark is a…", ["ray that is also called a sawfish", "shark with a toothed snout", "bony pike of northern lakes", "swordfish with a flat bill"], "shark with a toothed snout", 3),
  q("A sawfish is a…", ["true shark of the mako family", "ray (gills underneath), not a shark", "sturgeon", "paddlefish of the Mississippi"], "ray (gills underneath), not a shark", 3),
  q("Thresher sharks have a…", ["saw-toothed snout used in hunting", "huge upper tail lobe used in hunting", "hammer-shaped head used in hunting", "beak like a parrotfish's"], "huge upper tail lobe used in hunting", 2),
  q("Mako and great white are…", ["carpet (wobbegong) sharks", "lamnid (mackerel) sharks", "requiem (whaler) sharks", "chimaeras (ghost sharks)"], "lamnid (mackerel) sharks", 3),
  q("Chimaeras (ghost sharks) are…", ["bony fishes related to tuna", "cartilaginous relatives of sharks", "deep-sea mammals related to seals", "amphibians that live in the deep sea"], "cartilaginous relatives of sharks", 3),
  q("Sharks have no…", ["liver", "swim bladder", "liver oil", "teeth"], "swim bladder", 2),
  q("Buoyancy in many sharks comes from a…", ["swim bladder of bone", "oily liver", "feather coat", "hollow bones of birds"], "oily liver", 2),
  q("Ampullae of Lorenzini detect…", ["color only", "electric fields", "only air temperature", "only sound in air"], "electric fields", 2),
  q("The lateral line detects…", ["color", "water movement and pressure", "only magnetic north as a compass card", "only taste"], "water movement and pressure", 2),
  q("Shark skin denticles are…", ["mammal hair", "placoid scales", "bird feathers", "fish slime only with no structure"], "placoid scales", 3),
  q("Shark teeth are…", ["never replaced", "replaced in rows through life", "made of keratin only like hair", "absent in all species"], "replaced in rows through life", 1),
  q("Some sharks lay eggs in cases nicknamed…", ["bird nests", "mermaid's purses", "caddis tubes", "wasp paper"], "mermaid's purses", 2),
  q("Live-bearing sharks are…", ["egg-layers with leathery cases", "viviparous or ovoviviparous", "mammals that nurse with milk", "amphibians with gilled young"], "viviparous or ovoviviparous", 2),
  q("Ram ventilators must…", ["surface to breathe air like whales", "keep water flowing over their gills", "rest on the bottom to pump water", "close their gills while they sleep"], "keep water flowing over their gills", 2),
  q("Buccal pumping lets some sharks…", ["fly", "breathe while still", "photosynthesize", "live in lava"], "breathe while still", 2),
  q("Overfishing and finning have…", ["made sharks more abundant than ever", "driven many shark populations down", "no effect", "turned sharks into bony fish"], "driven many shark populations down", 1),
  q("A shark fin soup demand problem is…", ["overplanting kelp along the coast", "killing sharks for fins and wasting the body", "tagging sharks to track their routes", "a coral-restoration method that fails"], "killing sharks for fins and wasting the body", 1),
  q("Manta rays are…", ["sharks with a sting always", "filter-feeding rays", "bony flatfish", "mammals"], "filter-feeding rays", 1),
  q("Stingrays have a…", ["dorsal fin like a sailfish only", "barbed spine on the tail", "blowhole", "feathers"], "barbed spine on the tail", 1),
  q("Electric rays can…", ["fly short distances over waves", "stun prey with electric organs", "spin silk to trap prey", "breathe air at the surface"], "stun prey with electric organs", 2),
  q("Skates typically…", ["give birth to live young, like mammals", "lay egg cases and lack a stinging spine", "are fast sharks of the mako family", "live in freshwater rivers inland"], "lay egg cases and lack a stinging spine", 3),
  q("Bony fish are classically…", ["Chondrichthyes", "Osteichthyes", "Aves", "Amphibia"], "Osteichthyes", 2),
  q("Ray-finned fishes are…", ["sharks and their relatives", "actinopterygians, most living fish", "lungfish and coelacanths", "lampreys and hagfish"], "actinopterygians, most living fish", 3),
  q("A swim bladder in bony fish is for…", ["electroreception", "buoyancy", "biting", "walking"], "buoyancy", 1),
  q("The operculum of a bony fish is a…", ["tooth", "gill cover", "scale of a shark", "fin spine of a ray only"], "gill cover", 2),
  q("Lampreys and hagfish are…", ["early sharks", "jawless fishes", "toothed whales", "sea turtles"], "jawless fishes", 2),
  q("The coelacanth is a…", ["reef shark of the Indian Ocean", "lobe-finned fish once thought extinct", "river dolphin of the Amazon", "flightless seabird of the Galápagos"], "lobe-finned fish once thought extinct", 2),
  q("Lungfish can…", ["only live in the deep trench", "breathe air with a lung-like organ", "fly", "photosynthesize"], "breathe air with a lung-like organ", 2),
  q("A seahorse is a…", ["crustacean", "bony fish", "mollusk", "amphibian"], "bony fish", 1),
  q("Male seahorses…", ["make milk like mammals", "carry the developing young", "lay eggs in a bird nest", "sting like rays"], "carry the developing young", 1),
  q("Clownfish live with…", ["only freshwater reeds", "sea anemones", "only ice", "only tarantulas"], "sea anemones", 1),
  q("A salmon that returns to fresh water to spawn is…", ["catadromous", "anadromous", "sessile", "terrestrial"], "anadromous", 2),
  q("Eels that spawn at sea and grow in fresh water are…", ["anadromous", "catadromous", "only marine always", "insects"], "catadromous", 3),
  q("Tuna are…", ["fast, cold-blooded sharks", "fast, warm-bodied bony fishes", "rays of the open sea", "small toothed whales"], "fast, warm-bodied bony fishes", 2),
  q("A moray eel has a…", ["venomous stingray-like spine", "second set of pharyngeal jaws", "blowhole on top of its head", "pair of book lungs"], "second set of pharyngeal jaws", 3),
  q("Parrotfish help reefs by…", ["building reef walls from rubble", "grazing algae and making sand from coral", "pollinating seagrass like bees", "hunting lionfish off the reef"], "grazing algae and making sand from coral", 2),
  q("A flounder is a…", ["small shark of the seafloor", "flatfish that lies on one side", "marine mammal of the seafloor", "wading bird of the tidal flats"], "flatfish that lies on one side", 1),
  q("The pufferfish's defense is…", ["kicking urticating hairs", "inflating (and often toxin)", "a tail sting", "ink"], "inflating (and often toxin)", 2),
  q("Stonefish are famed for…", ["being sharks", "venomous dorsal spines and camouflage", "filter feeding like whale sharks", "living in deserts"], "venomous dorsal spines and camouflage", 2),
  q("Lionfish are…", ["freshwater carp invasive in the Mississippi", "venomous fish invasive in the Atlantic", "small sharks native to the Caribbean", "lampreys invasive in the Great Lakes"], "venomous fish invasive in the Atlantic", 2),
  q("A remora hitches with a…", ["hooked beak and tongue", "suction disc on the head", "sticky silk line", "barbed tail stinger"], "suction disc on the head", 2),
  q("Pilot fish and remoras often travel with…", ["only desert tortoises", "large sharks or rays", "only eagles", "only tarantulas"], "large sharks or rays", 1),
  q("Coral trout and groupers are…", ["sharks of the open ocean only", "bony reef predators", "mammals", "birds"], "bony reef predators", 2),
  q("The arapaima is a…", ["reef shark of the Red Sea", "huge air-breathing Amazon fish", "penguin of the Patagonian coast", "ray of the cold North Sea"], "huge air-breathing Amazon fish", 3),
  q("Piranhas are…", ["small Pacific sharks of the reefs", "South American characins, not sharks", "eels born in the Sargasso Sea", "lampreys of the Amazon basin"], "South American characins, not sharks", 2),
  q("A paddlefish is a…", ["small shark of California's kelp beds", "freshwater filter feeder with a long snout", "river dolphin of the Mississippi", "tarpon that lives on coral reefs"], "freshwater filter feeder with a long snout", 3),
  q("Sturgeons are…", ["rays prized for their wing meat", "ancient bony fishes prized for caviar", "seals hunted in the Caspian Sea", "giant amphibians of Russian rivers"], "ancient bony fishes prized for caviar", 2),
  q("A barracuda is a…", ["small toothed whale", "fast predatory bony fish", "predatory sea star", "reef-building sponge"], "fast predatory bony fish", 1),
  q("Marlin and sailfish are…", ["mackerel sharks", "billfishes", "eagle rays", "moray eels"], "billfishes", 2),
  q("The oarfish is a…", ["hammerhead shark of the deep", "long, ribbon-like bony fish of the deep", "leopard seal of the Antarctic", "giant spider crab of Japan"], "long, ribbon-like bony fish of the deep", 2),
  q("Lanternfish are…", ["pupfish found only in desert springs", "tiny deep-sea fishes with light organs", "bull sharks that swim up rivers", "seabirds that hunt by night"], "tiny deep-sea fishes with light organs", 3),
  q("Photophores are…", ["ears", "light-producing organs", "lungs of a tarantula", "teeth of a ray"], "light-producing organs", 2),
  q("The anglerfish lure is a…", ["piece of shark fin it scavenged", "modified fin ray, often glowing", "feather snagged from a seabird", "silk line like a spider's"], "modified fin ray, often glowing", 2),
  q("A goby is typically a…", ["small toothed whale of rivers", "small bony fish of reefs and streams", "fish-eating eagle of the coast", "tarantula that hunts at the shore"], "small bony fish of reefs and streams", 1),
  q("Damselfish include the…", ["great whites", "clownfish", "whale sharks", "mantas"], "clownfish", 2),
  q("A wrasse is a…", ["cookiecutter shark of the deep sea", "reef fish, some of which clean others", "penguin of the Galápagos Islands", "giant kelp of the Pacific coast"], "reef fish, some of which clean others", 2),
  q("Cleaner wrasses eat…", ["coral rock ground into sand", "parasites and dead tissue off client fish", "small seabirds resting on the water", "eggs laid by their client fish"], "parasites and dead tissue off client fish", 2),
  q("A triggerfish has a…", ["silk gland for nests", "locking dorsal spine", "book lung for breathing", "blowhole like a dolphin"], "locking dorsal spine", 3),
  q("Boxfish are often…", ["small sharks with box-shaped heads", "toxic and boxy-plated bony fishes", "box-shaped marine mammals", "aquatic insects in a box shell"], "toxic and boxy-plated bony fishes", 3),
  q("Flying fish glide with…", ["feathered wing-like fins", "enlarged pectoral fins", "silk-like gliding membranes", "pockets of hot air"], "enlarged pectoral fins", 1),
  q("Mudskippers can…", ["live in the Himalaya snow only", "move and breathe on mudflats out of water", "fly to Africa each year as a bird", "photosynthesize"], "move and breathe on mudflats out of water", 2),
  q("Walking catfish and snakeheads are…", ["Arctic sharks that crawl on the ice", "air-breathing fish that can cross land", "wading birds that eat fish on land", "amphibians that spend years in mud"], "air-breathing fish that can cross land", 2),
  q("Tilapia are…", ["widely farmed sharks", "widely farmed cichlids", "widely farmed rays", "widely farmed mollusks"], "widely farmed cichlids", 2),
  q("Cichlids are a…", ["diverse order of freshwater sharks", "diverse family of freshwater bony fishes", "family of small toothed whales", "genus of reef-building corals"], "diverse family of freshwater bony fishes", 2),
  q("The Oscar and angelfish of aquaria are…", ["sharks", "cichlids (South American)", "eels of the Sargasso", "lampreys"], "cichlids (South American)", 2),
  q("A betta (Siamese fighting fish) is a…", ["small shark kept in aquariums", "labyrinth fish that can breathe air", "freshwater ray of Thai rivers", "amphibian that lives in rice paddies"], "labyrinth fish that can breathe air", 2),
  q("The labyrinth organ lets some fishes…", ["filter krill only", "gulp air", "spin silk", "kick hairs"], "gulp air", 2),
  q("Goldfish and koi are…", ["sharks", "domesticated carps", "salmon of the Pacific", "catfish of the Amazon only"], "domesticated carps", 1),
  q("A catfish typically has…", ["a saw snout of a sawshark", "barbels ('whiskers')", "a sting of a manta", "feathers"], "barbels ('whiskers')", 1),
  q("Electric eels are…", ["true morays of freshwater rivers", "South American knifefish, not true eels", "small sharks of the Amazon", "lampreys with electric organs"], "South American knifefish, not true eels", 3),
  q("The Sargasso Sea is the spawning area of…", ["salmon of Alaska only", "American and European eels", "whale sharks", "tarpon of Texas only"], "American and European eels", 3),
  q("Herring and sardines are…", ["apex predators like sharks", "schooling forage fishes", "small baleen whales", "bottom-dwelling starfishes"], "schooling forage fishes", 1),
  q("Anchovies are…", ["filter-feeding sharks", "small schooling bony fishes", "rays", "crustaceans"], "small schooling bony fishes", 1),
  q("A food web of the open ocean often starts with…", ["sharks then tuna then plankton", "phytoplankton, then zooplankton", "seabirds then fish then plankton", "whales then krill then algae"], "phytoplankton, then zooplankton", 1),
  q("Sharks as apex predators help…", ["pollinate kelp flowers", "structure marine food webs", "build coral skeletons", "fix nitrogen on land"], "structure marine food webs", 2),
  q("A marine protected area can help sharks by…", ["feeding them bait in a zone", "reducing fishing mortality in a zone", "draining shallow lagoons in a zone", "adding dams to river mouths"], "reducing fishing mortality in a zone", 1),
  q("Bycatch of sharks happens in…", ["only catch-and-release fly rods of trout", "nets and longlines aimed at other species", "only butterfly nets", "only lobster pots of the desert"], "nets and longlines aimed at other species", 2),
  q("Shark eggs are fertilized…", ["externally, in open water", "internally, inside the female", "externally, in a gravel nest", "inside a floating egg case"], "internally, inside the female", 3),
  q("Male sharks have…", ["udder", "claspers", "antlers", "spinnerets"], "claspers", 2),
  q("The spiral valve is a…", ["stiff fin on a shark's back", "coil inside a shark's intestine", "eyelid that protects a whale's eye", "spiral scale pattern on a carp"], "coil inside a shark's intestine", 3),
  q("Nictitating membranes in some sharks…", ["make electricity to stun prey", "protect the eye during a bite", "filter plankton from the water", "store oil for buoyancy"], "protect the eye during a bite", 2),
  q("The caudal fin of a shark is often…", ["missing", "heterocercal", "feathered", "a sting"], "heterocercal", 3),
  q("Heterocercal tails provide…", ["only electricity", "lift as well as thrust", "silk", "sound of a songbird"], "lift as well as thrust", 3),
  q("A benthic shark lives…", ["only at the sea surface of the open gyre always", "on or near the bottom", "only in trees", "only in rivers of the Alps"], "on or near the bottom", 2),
  q("Pelagic means…", ["of the forest floor", "of the open water column", "of the desert pavement", "of a burrow"], "of the open water column", 1),
  q("The epipelagic zone is roughly the…", ["hadal trench only", "sunlit upper ocean", "inner Earth", "stratosphere"], "sunlit upper ocean", 2),
  q("The hadal zone is the…", ["beach swash", "deepest ocean trenches", "coral crest only", "kelp canopy"], "deepest ocean trenches", 2),
  q("A thermocline is a…", ["type of shark fin used for steering", "sharp temperature change with depth", "genus of warm-water reef coral", "growth ring on a fish scale"], "sharp temperature change with depth", 3),
  q("Upwelling brings…", ["warm surface water down to the deep", "nutrient-rich water toward the surface", "salt from the sea into coastal deserts", "sand from the seafloor onto beaches"], "nutrient-rich water toward the surface", 2),
  q("Kelp forests are dominated by…", ["large sharks and their prey", "large brown algae, not coral", "mosses like those of the tundra", "flowering seagrasses"], "large brown algae, not coral", 1),
  q("Seagrasses are…", ["brown algae of the open ocean", "flowering plants in shallow seas", "mosses that grow under sea ice", "fungi that coat coral reefs"], "flowering plants in shallow seas", 2),
  q("Mangroves are…", ["floating algae of the open ocean", "salt-tolerant trees of tropical shores", "vent communities of the deep sea", "wildflower meadows of the Alps"], "salt-tolerant trees of tropical shores", 1),
  q("Estuaries are important as…", ["ice shelves where glaciers calve", "nurseries mixing river and sea", "dry salt flats in deserts", "high meadows on mountaintops"], "nurseries mixing river and sea", 1),
  q("A nursery ground for sharks is often…", ["the stratosphere", "shallow bays or mangroves", "Antarctic ice cap only for tropical reefs", "a freshwater spring in the Sahara always"], "shallow bays or mangroves", 2),
  q("Whale sharks are listed as…", ["invasive in many freshwater lakes", "endangered on many conservation lists", "abundant and of least concern", "extinct in the wild since 1990"], "endangered on many conservation lists", 2),
  q("Sawfishes are among the…", ["most abundant fishes in the sea", "most threatened marine fishes", "fastest fishes in the open ocean", "least threatened rays in the sea"], "most threatened marine fishes", 2),
  q("A CITES listing for a shark or ray…", ["makes fishing it legal everywhere", "restricts international trade in the species", "bans all swimming in its habitat", "renames it under a new genus"], "restricts international trade in the species", 2),
  q("Pelinobius muticus is the hobby…", ["GBB", "king baboon", "pinktoe", "curly hair"], "king baboon", 3),
  q("Acanthoscurria geniculata is the…", ["Chilean rose", "Brazilian whiteknee", "Gooty ornamental", "desert blonde"], "Brazilian whiteknee", 3),
  q("Grammostola pulchripes is the…", ["OBT", "Chaco golden knee", "Martinique pinktoe", "Socotra blue"], "Chaco golden knee", 3),
  q("Brachypelma boehmei is the…", ["Gooty", "Mexican fireleg", "Togo starburst", "king baboon"], "Mexican fireleg", 3),
  q("Brachypelma auratum is the…", ["pinktoe", "Mexican flame knee", "OBT", "salmon pink birdeater"], "Mexican flame knee", 3),
  q("Aphonopelma hentzi is often called the…", ["Gooty ornamental", "Texas brown tarantula", "green bottle blue", "Antilles pinktoe"], "Texas brown tarantula", 3),
  q("Pterinopelma sazimai is the…", ["OBT", "Brazilian blue", "curly hair", "red rump"], "Brazilian blue", 3),
  q("Cyriopagopus lividus is the hobby…", ["Mexican red-knee", "cobalt blue", "Chilean rose", "Arizona blonde"], "cobalt blue", 3),
  q("Avicularia avicularia is a classic…", ["horned baboon", "pinktoe", "Gooty ornamental", "earth tiger"], "pinktoe", 3),
  q("Davus fasciatus is the…", ["Gooty ornamental", "Costa Rican tiger rump", "Socotra blue baboon", "Tanzanian king baboon"], "Costa Rican tiger rump", 3),
  q("Phormictopus cancerides is the…", ["GBB", "Haitian brown", "Martinique pinktoe", "Togo starburst"], "Haitian brown", 3),
  q("Hapalopus (hobby 'pumpkin patch') are…", ["Old World arboreal pokies", "small, fast-growing New World terrestrials", "African horned baboons", "desert blondes of Arizona only"], "small, fast-growing New World terrestrials", 3),
  q("Cyriocosmus species are often kept as…", ["the largest birdeaters", "dwarf tarantulas", "only Old World baboons", "only pinktoes of Martinique"], "dwarf tarantulas", 3),
  q("Typhochlaena seladonia is famed for…", ["being a giant African baboon", "an iridescent dwarf arboreal from Brazil", "living in the dunes of the Gobi", "spinning no silk at all"], "an iridescent dwarf arboreal from Brazil", 3),
  q("Theraphosa stirmi is a…", ["small jumping spider of houses", "second goliath birdeater species", "giant scorpion of the rainforest", "harvestman (daddy longlegs)"], "second goliath birdeater species", 3),
  q("Theraphosa apophysis is nicknamed the…", ["green bottle blue", "pinkfoot goliath", "curly hair", "Socotra blue"], "pinkfoot goliath", 3),
  q("Ybyrapora was split from…", ["Poecilotheria", "Avicularia", "Ceratogyrus", "Aphonopelma"], "Avicularia", 3),
  q("Poecilotheria in hobby slang are…", ["red knees", "pokies", "GBBs", "curly hairs"], "pokies", 3),
  q("Many keepers treat Poecilotheria as…", ["perfect first pets for handling", "advanced species with potent bites", "beginner species for children", "harmless species with no venom"], "advanced species with potent bites", 3),
  q("Poecilotheria metallica is listed as…", ["invasive in every U.S. county", "critically endangered in the wild", "a bony fish", "a bird"], "critically endangered in the wild", 3),
  q("Monocentropus balfouri is unusual because keepers often house it…", ["only in pairs of mature males as a rule", "communally (more so than most tarantulas)", "in a reef tank", "with a tarantula hawk"], "communally (more so than most tarantulas)", 3),
  q("Most tarantula species should be housed…", ["in large breeding packs", "one animal per enclosure", "with a scorpion roommate", "in open outdoor pits of a yard"], "one animal per enclosure", 3),
  q("A 'T-sel' in the hobby is a…", ["type of book lung structure", "captive-selected color form", "CITES trade appendix", "stage in the molting cycle"], "captive-selected color form", 3),
  q("Springtails in a tarantula tank are used as a…", ["main prey of adult goliaths", "cleanup crew for mold and leftovers", "heat source", "UVB lamp"], "cleanup crew for mold and leftovers", 3),
  q("Isopods as cleanup can be a problem if they…", ["photosynthesize in bright light", "nibble a molting tarantula", "turn into moths overnight", "eat the cork bark hide"], "nibble a molting tarantula", 3),
  q("Stagnant, overly wet air is especially dangerous for…", ["desert-dwelling scorpions", "New World arboreal pinktoes", "dry-loving desert blondes", "cactus plants on a windowsill"], "New World arboreal pinktoes", 3),
  q("A heat mat under a terrestrial tank can…", ["replace the need for a water dish", "cook the animal if the substrate overheats", "make the spider molt on schedule", "keep crickets from escaping"], "cook the animal if the substrate overheats", 3),
  q("For most pet tarantulas, a water dish beats…", ["never offering any water at all", "soaking the whole enclosure into a swamp", "a salt lick hung from the lid", "a UVB desert lamp over the tank"], "soaking the whole enclosure into a swamp", 3),
  q("A late pre-molt tarantula often…", ["needs a huge meal the night before", "refuses food and may seal its burrow", "should be rehoused within the hour", "should be handled for exercise"], "refuses food and may seal its burrow", 3),
  q("Do not rehouse or feed a tarantula that is…", ["asleep as a mammal sleeps", "on its back in a molt", "sitting in a water dish", "sitting on cork"], "on its back in a molt", 3),
  q("An obligatory burrower is more likely to thrive with…", ["only a tall bare tube and no soil", "deep, compactable substrate it can tunnel", "open water like a goldfish", "a running wheel"], "deep, compactable substrate it can tunnel", 3),
  q("An opportunistic burrower may…", ["never sit still day or night", "use a ready-made hide instead of digging", "need a live reef anemone to hide in", "live deep in the ocean's hadal zone"], "use a ready-made hide instead of digging", 3),
  q("Aromatic cedar or pine shavings are…", ["the gold-standard mix for burrowers", "a poor, potentially harmful substrate choice", "required bedding under CITES rules", "the only legal bedding in the U.S."], "a poor, potentially harmful substrate choice", 3),
  q("Coco fiber (coir) is a common…", ["prey insect", "terrestrial substrate", "venom crystal", "book-lung plate"], "terrestrial substrate", 3),
  q("A cork-bark tube is a classic hide for…", ["reef fish in aquariums", "arboreal tarantulas", "baleen whales", "kelp"], "arboreal tarantulas", 3),
  q("The venom glands of a tarantula sit in the…", ["spinnerets only", "chelicerae", "book lungs", "eggs"], "chelicerae", 3),
  q("A tarantula typically shows how many spinnerets at the rear?", ["two", "four (two pairs)", "eight like the legs", "none"], "four (two pairs)", 3),
  q("The last segment of a tarantula leg is the…", ["abdomen", "tarsus", "carapace", "pedicel"], "tarsus", 3),
  q("Autotomy in a tarantula is…", ["kicking hairs only", "dropping a leg to escape", "laying eggs", "stridulating"], "dropping a leg to escape", 3),
  q("The ocular tubercle is the…", ["organ that spins the silk", "raised mound that bears the eyes", "slit opening to a book lung", "egg tooth used at hatching"], "raised mound that bears the eyes", 3),
  q("Tarantula vision is generally…", ["as sharp as an eagle's", "poor; they rely on vibration", "based on echolocation clicks", "based on heat-sensing pits"], "poor; they rely on vibration", 2),
  q("Pterinochilus murinus is famous for a loud…", ["bird-like song at dusk", "hiss when threatened", "click of its fangs", "chirp like a cricket"], "hiss when threatened", 3),
  q("OBT in hobby notes means…", ["old black terrestrial", "orange baboon tarantula", "optical bore tester", "Oregon brown tick"], "orange baboon tarantula", 3),
  q("GBB in hobby notes means…", ["giant black birdeater", "green bottle blue", "Gooty baboon brown", "ground beetle of Brazil"], "green bottle blue", 3),
  q("LP in hobby notes often means…", ["Lycosa pack (wolf spiders)", "Lasiodora parahybana", "long palpus (male sign)", "lunar pinktoe morph"], "Lasiodora parahybana", 3),
  q("MM in a listing means…", ["metric molt", "mature male", "Mexican morph", "micro millipede"], "mature male", 3),
  q("An exuvium is sometimes nicknamed a…", ["egg sac", "molt skin", "water dish", "cork round"], "molt skin", 3),
  q("Fresh-molt colors often look…", ["always darker forever", "washed or pale until the cuticle hardens", "feathered", "transparent like glass always"], "washed or pale until the cuticle hardens", 3),
  q("Dry-climate pet genera include many…", ["Theraphosa of the flooded forest", "Brachypelma, Grammostola, and Aphonopelma", "Avicularia pinktoes as desert animals", "Poecilotheria of rain trees as desert animals"], "Brachypelma, Grammostola, and Aphonopelma", 3),
  q("Moist-forest fossorials include many…", ["Aphonopelma of Arizona as rainforest animals", "Theraphosa and some Pamphobeteus", "Grammostola of the Atacama as a swamp set", "desert blondes of the Sonoran as jungle animals"], "Theraphosa and some Pamphobeteus", 3),
  q("A 'pet hole' in a fossorial tank is the…", ["shallow water dish in the corner", "open mouth of a burrow the spider uses", "heat mat stuck under the glass", "UV lamp hole in the lid"], "open mouth of a burrow the spider uses", 3),
  q("Type I urticating hairs are typically…", ["found on Old World palps", "kicked from the abdomen", "tipped with venom crystals", "part of the silk glands"], "kicked from the abdomen", 3),
  q("Type VI urticating hairs are the…", ["kicked cloud of a GBB", "palpal hairs of Ephebopus", "book-lung plates", "egg teeth"], "palpal hairs of Ephebopus", 3),
  q("Many Brachypelma are listed on CITES Appendix…", ["I", "II", "III", "none at all"], "II", 3),
  q("A sling enclosure should be…", ["a tall empty room like a hallway", "escape-proof, with no long drop", "an open bowl on a windowsill", "a reef sump with running water"], "escape-proof, with no long drop", 3),
  q("The Tarantula Collective's husbandry line is generally…", ["wild-caught only and daily handling", "captive-bred, species-appropriate care", "heat mats for every species alike", "no water dishes for any species"], "captive-bred, species-appropriate care", 3),
  q("A sperm web is not an egg sac; it is how a male…", ["lays and guards eggs", "charges his palps with sperm", "kicks hairs at rivals", "molts into maturity"], "charges his palps with sperm", 3),
  q("Egg-sac size varies wildly; large terrestrials may guard…", ["exactly two eggs always", "hundreds of eggs", "live calves", "a bird nest of sticks"], "hundreds of eggs", 2),
  q("Neoholothele incei is a…", ["whale shark of the Indian Ocean", "small, active New World species", "horned African baboon species", "Gooty ornamental of India"], "small, active New World species", 3),
  q("Xenesthis immanis is a…", ["tiny dwarf of 1 cm", "large New World terrestrial", "Old World pokie of Sri Lanka", "desert blonde of Arizona"], "large New World terrestrial", 3),
  q("Pamphobeteus species are typically…", ["African horned baboon species", "large South American terrestrials", "Arizona desert blonde species", "Martinique pinktoe arboreals"], "large South American terrestrials", 3),
  q("A mature male's tibial apophysis is a…", ["book lung used for breathing", "hook used in mating on some species", "spinneret used for silk", "egg sac carried by females"], "hook used in mating on some species", 3),
  q("Never use a vacuum to rehouse because you might…", ["calm it down too much", "injure or suck up the spider", "help it molt more easily", "sex it more accurately"], "injure or suck up the spider", 3),
  q("A just-rehoused tarantula needs…", ["daily handling to tame it quickly", "time to settle, with a hide and water", "a second tarantula for company", "a heat lamp aimed at its burrow"], "time to settle, with a hide and water", 3),
  q("Great whites are the species…", ["Rhincodon typus", "Carcharodon carcharias", "Cetorhinus maximus", "Galeocerdo cuvier"], "Carcharodon carcharias", 2),
  q("The whale shark's scientific name is…", ["Carcharodon carcharias", "Rhincodon typus", "Sphyrna mokarran", "Prionace glauca"], "Rhincodon typus", 2),
  q("The basking shark's scientific name is…", ["Rhincodon typus", "Cetorhinus maximus", "Carcharodon carcharias", "Mitsukurina owstoni"], "Cetorhinus maximus", 3),
  q("Megalodon is…", ["a living reef shark of Florida keys as a common sight", "an extinct giant shark (Otodus megalodon)", "a bony tuna", "a dolphin"], "an extinct giant shark (Otodus megalodon)", 1),
  q("Dunkleosteus was a…", ["modern great white shark", "placoderm (armored jawed fish)", "early toothed whale", "giant sea scorpion"], "placoderm (armored jawed fish)", 3),
  q("A frilled shark has a…", ["hammer-shaped head and wide eyes", "long, eel-like body and frilly gills", "venomous spine like a stingray", "feather-like fins along its back"], "long, eel-like body and frilly gills", 2),
  q("Epaulette sharks can…", ["glide above the waves like flying fish", "walk on their fins across reef flats", "live in cold rivers of the Alps", "spin silk nests among the coral"], "walk on their fins across reef flats", 2),
  q("Bonnethead sharks are unusual in eating…", ["krill filtered like a whale shark", "seagrass as well as animal prey", "seabirds resting on the water", "sea turtles and their eggs"], "seagrass as well as animal prey", 3),
  q("Sand-tiger embryos are famed for…", ["photosynthesis", "eating sibling embryos in the uterus", "spinning cocoons of silk", "laying mermaid purses on land trees"], "eating sibling embryos in the uterus", 3),
  q("Spiny dogfish are famed for a…", ["one-day pregnancy", "very long gestation", "life in freshwater lakes", "lack of any fins"], "very long gestation", 3),
  q("The oceanic whitetip is a…", ["freshwater stingray of the Amazon", "pelagic shark of the open ocean", "bony goby of coral reefs", "lamprey of the Great Lakes"], "pelagic shark of the open ocean", 2),
  q("The blue shark (Prionace glauca) is a…", ["bottom wobbegong", "slim open-ocean hunter", "river dolphin", "parrotfish"], "slim open-ocean hunter", 2),
  q("Lemon sharks often use…", ["the stratosphere", "mangrove shallows as nurseries", "only Arctic ice", "desert seeps of the Sahara"], "mangrove shallows as nurseries", 2),
  q("Blacktip reef sharks are typical of…", ["only the abyssal trench", "tropical lagoons and reef flats", "only Alpine lakes", "wheat fields"], "tropical lagoons and reef flats", 1),
  q("Whale-shark spot patterns are…", ["repainted each year as a rule", "unique to individuals, like a fingerprint", "identical in every ocean", "absent — they are plain grey always"], "unique to individuals, like a fingerprint", 2),
  q("A chimaera is also called a…", ["skipjack or bluefin tuna", "ratfish or ghost shark", "porpoise or dolphin", "sea cucumber"], "ratfish or ghost shark", 2),
  q("The giant oceanic manta is…", ["Carcharodon carcharias", "Mobula birostris", "Rhincodon typus", "Dasyatis pastinaca"], "Mobula birostris", 3),
  q("Devil rays are in the genus…", ["Pristis", "Mobula", "Lamna", "Hippocampus"], "Mobula", 3),
  q("Potamotrygon are…", ["Pacific makos", "South American freshwater stingrays", "Arctic seals", "desert pupfish of Death Valley only"], "South American freshwater stingrays", 2),
  q("Smalltooth sawfish are…", ["among the most common reef fishes", "among the most endangered marine fishes", "among the fastest open-ocean fishes", "among the least threatened rays"], "among the most endangered marine fishes", 2),
  q("The Greenland shark is…", ["Rhincodon typus", "Somniosus microcephalus", "Sphyrna lewini", "Carcharodon carcharias"], "Somniosus microcephalus", 3),
  q("The goblin shark is…", ["Galeocerdo cuvier", "Mitsukurina owstoni", "Prionace glauca", "Negaprion brevirostris"], "Mitsukurina owstoni", 3),
  q("The megamouth shark is…", ["Rhincodon typus", "Megachasma pelagios", "Carcharodon carcharias", "Cetorhinus maximus"], "Megachasma pelagios", 3),
  q("A hammerhead's wide head is a…", ["dorsal fin", "cephalofoil", "clasper", "spiracle only"], "cephalofoil", 3),
  q("The great hammerhead is…", ["Squalus acanthias", "Sphyrna mokarran", "Ginglymostoma cirratum", "Rhincodon typus"], "Sphyrna mokarran", 3),
  q("Great whites can keep parts of the body warmer than the water; they are…", ["fully cold as a snail always with no trick", "regionally endothermic", "mammals that nurse", "birds"], "regionally endothermic", 3),
  q("Countershading on a shark is…", ["striped like a tiger always", "dark above, light below", "gold on both sides", "transparent"], "dark above, light below", 2),
  q("A tapetum lucidum in a shark eye…", ["makes electricity to sense prey", "reflects light and aids vision in dim water", "filters plankton out of the water", "stores oil like the liver does"], "reflects light and aids vision in dim water", 3),
  q("Spiracles in some sharks sit…", ["on the tail sting", "behind the eyes and can aid breathing", "inside the liver only", "on the dorsal fin always as gills"], "behind the eyes and can aid breathing", 2),
  q("Most sharks have how many gill slits per side?", ["one", "two like a mammal's lungs as slits", "five (some groups have six or seven)", "twenty"], "five (some groups have six or seven)", 2),
  q("Helicoprion is a fossil fish famous for a…", ["feathered wing", "spiral tooth whorl", "silk gland", "book lung"], "spiral tooth whorl", 3),
  q("A leafy seadragon is a…", ["small shark of the Arctic", "Australian relative of seahorses", "dolphin of Australian bays", "kelp that traps small fish"], "Australian relative of seahorses", 2),
  q("The ocean sunfish (Mola mola) is a…", ["whale", "huge, odd-shaped bony fish", "shark of the mako family", "ray with a sting always"], "huge, odd-shaped bony fish", 2),
  q("Mahi-mahi (dolphinfish) is a…", ["toothed whale, not a fish", "bony fish, not a dolphin", "shark, not a bony fish", "crustacean, not a fish"], "bony fish, not a dolphin", 1),
  q("An orca is a…", ["bony fish related to tuna", "toothed whale (mammal), not a fish", "cartilaginous shark, not a mammal", "giant ray, not a mammal"], "toothed whale (mammal), not a fish", 1),
  q("Clownfish can change sex; they are…", ["simultaneous hermaphrodites", "sequential hermaphrodites", "parthenogenetic females", "fixed-sex livebearers"], "sequential hermaphrodites", 3),
  q("Tiktaalik is a fossil that bridges…", ["jawless fishes and early sharks", "lobe-finned fishes and early tetrapods", "early reptiles and the first birds", "sea scorpions and early spiders"], "lobe-finned fishes and early tetrapods", 3),
  q("The coelacanth genus of living animals is…", ["Carcharodon", "Latimeria", "Rhincodon", "Hippocampus"], "Latimeria", 3),
  q("Nurse sharks include…", ["Isurus oxyrinchus, the shortfin mako", "Ginglymostoma cirratum of the Atlantic", "Sphyrna mokarran, the great hammerhead", "Rhincodon typus, the whale shark"], "Ginglymostoma cirratum of the Atlantic", 3),
  q("The zebra shark (Stegostoma) is a…", ["mako of the open ocean gyres", "carpet shark of Indo-Pacific reefs", "lamprey of coastal rivers", "dolphin of shallow reefs"], "carpet shark of Indo-Pacific reefs", 3),
  q("A swell shark can…", ["leap and glide above the waves", "inflate its body when threatened", "kick urticating hairs at attackers", "spin a round orb web"], "inflate its body when threatened", 2),
  q("Sixgill sharks belong to…", ["Sphyrna", "Hexanchus", "Pristis", "Manta"], "Hexanchus", 3),
  q("The ocean sunfish's diet is often…", ["only krill of polar water", "jellies (among other prey)", "only grasses of a prairie", "only tarantulas"], "jellies (among other prey)", 2),
  q("Pipefish are close relatives of…", ["great whites", "seahorses", "hammerheads", "goliath tarantulas"], "seahorses", 2),
  q("Frogfishes are…", ["fast open-ocean hunters like makos", "sit-and-wait anglers on reefs", "fish-eating birds like eagles", "floating kelp of the coast"], "sit-and-wait anglers on reefs", 2),
  q("Krill in a food web are…", ["baby sharks, not crustaceans", "small crustaceans, not fish", "seagrasses, not animals", "tiny fish, not crustaceans"], "small crustaceans, not fish", 1),
  q("A horseshoe crab is…", ["a true crab closer to lobsters", "an arthropod closer to spiders than crabs", "a mollusk related to snails and clams", "a crustacean related to shrimp"], "an arthropod closer to spiders than crabs", 2),
  q("Sea turtles are…", ["bony fish", "reptiles, not fish", "sharks", "mammals that gill-breathe"], "reptiles, not fish", 1),
  q("Manatees are…", ["herbivorous marine reptiles", "herbivorous marine mammals", "large bony fish of the tropics", "rays that graze on seagrass"], "herbivorous marine mammals", 1),
  q("The Atlantic bluefin is a…", ["reef goby", "highly migratory tuna, heavily fished", "freshwater stingray of the Amazon", "lamprey"], "highly migratory tuna, heavily fished", 2),
  q("Swordfish belong to…", ["Carcharodon", "Xiphias", "Sphyrna", "Rhincodon"], "Xiphias", 2),
  q("A moray is a…", ["shark of the open ocean gyres", "bony eel-shaped fish of reefs and rocks", "marine mammal of rocky coasts", "crustacean of reefs and rocks"], "bony eel-shaped fish of reefs and rocks", 1),
  q("Parrotfish teeth are fused into a…", ["comb for spinning silk threads", "beak for scraping algae and coral", "hammer-shaped cephalofoil", "venomous sting like a ray's"], "beak for scraping algae and coral", 2),
  q("Coral bleaching is when corals…", ["turn into sharks", "expel their symbiotic algae under stress", "become tarantulas", "freeze into icebergs as a rule"], "expel their symbiotic algae under stress", 2),
  q("A cleaner station on a reef is where…", ["sharks gather to lay their eggs", "small fish or shrimp clean other fish", "sea turtles come ashore to nest", "corals spawn all at once"], "small fish or shrimp clean other fish", 2),
  q("The Sargasso Sea is named for…", ["a genus of Atlantic sharks", "floating sargassum seaweed", "a Portuguese navigator", "a desert coast of Peru"], "floating sargassum seaweed", 2),
  q("An atoll, in the tropical ocean, is typically a…", ["mountain of granite only", "ring of coral around a lagoon", "shark tooth", "book lung"], "ring of coral around a lagoon", 1),
  q("A gyre is a…", ["type of dorsal fin on a shark", "large rotating ocean current system", "stage in a tarantula's molt", "polyp at the base of a coral"], "large rotating ocean current system", 2),
  q("The Gulf Stream is a…", ["cold Antarctic bottom current", "warm Atlantic current", "river of the Amazon", "wind of the Gobi"], "warm Atlantic current", 1),
  q("El Niño is a…", ["shark species of the eastern Pacific", "Pacific climate swing that shifts weather", "tarantula genus of South America", "moon of Jupiter seen by Galileo"], "Pacific climate swing that shifts weather", 2),
  q("A fish ladder helps…", ["sharks climb trees", "migratory fish pass a dam", "tarantulas molt", "coral bleach on purpose"], "migratory fish pass a dam", 1),
  q("Bycatch reduction gear is meant to…", ["catch more sharks in the same nets", "let non-target species escape the nets", "drain estuaries before trawling", "plant kelp beds near the shore"], "let non-target species escape the nets", 2),
  q("Shark sanctuaries are…", ["zoos that breed sharks for release", "national waters that restrict shark fishing", "inland parks with shark aquariums", "harbors where sharks are farmed"], "national waters that restrict shark fishing", 2),
  q("A tag-and-release study of sharks tracks…", ["only color of the tank", "movements and survival", "book-lung counts", "silk quality"], "movements and survival", 1),
  q("The IUCN Red List is used to…", ["set international SI units", "score species' extinction risk", "name new tarantula color forms", "set global fishing quotas"], "score species' extinction risk", 2),
];

