import { q } from "../quiz";
import type { TriviaQ } from "../types";

export const SCIENCE_LIFE: TriviaQ[] = [
  q("Metrology is the science of…", ["weather only", "measurement", "insects", "poetry"], "measurement", 1),
  q("The SI is the…", ["U.S. customary system of units", "International System of Units", "stock index for science firms", "standard index of medical codes"], "International System of Units", 1),
  q("How many SI base units are there?", ["3", "5", "7", "10"], "7", 1),
  q("The SI base unit of length is the…", ["inch", "metre", "yard", "angstrom"], "metre", 1),
  q("The SI base unit of mass is the…", ["gram", "kilogram", "pound", "tonne"], "kilogram", 1),
  q("The SI base unit of time is the…", ["minute", "second", "hour", "day"], "second", 1),
  q("The SI base unit of electric current is the…", ["volt", "ohm", "ampere", "watt"], "ampere", 1),
  q("The SI base unit of thermodynamic temperature is the…", ["celsius", "kelvin", "fahrenheit", "rankine as SI"], "kelvin", 1),
  q("The SI base unit of amount of substance is the…", ["gram", "mole", "litre", "molecule"], "mole", 1),
  q("The SI base unit of luminous intensity is the…", ["lumen", "candela", "lux", "watt"], "candela", 2),
  q("The BIPM, keeper of the SI, is in…", ["Gaithersburg", "Sèvres, France", "Teddington", "Berlin as BIPM"], "Sèvres, France", 2),
  q("NIST is the U.S.…", ["national weather service", "national metrology institute", "federal patent court", "national census bureau"], "national metrology institute", 1),
  q("NPL is the national metrology institute of the…", ["Netherlands", "United Kingdom", "Switzerland", "South Africa"], "United Kingdom", 2),
  q("PTB is the national metrology institute of…", ["Italy", "Germany", "Spain", "Poland"], "Germany", 2),
  q("NRC (metrology) is associated with…", ["Mexico", "Canada", "Brazil", "India as NRC-metrology's only home"], "Canada", 3),
  q("A national metrology institute realizes…", ["traffic laws for a country", "measurement standards for a country", "sports records for a country", "postal codes for a country"], "measurement standards for a country", 1),
  q("The Metre Convention dates to…", ["1776", "1875", "1945", "1960"], "1875", 3),
  q("CIPM stands for the…", ["International Olympic Committee", "International Committee for Weights and Measures", "International Council of Physics Museums", "Committee for International Patent Matters"], "International Committee for Weights and Measures", 3),
  q("The 2019 SI overhaul redefined the kilogram using the…", ["International Prototype Kilogram only still", "Planck constant", "a liter of water", "Earth's mass"], "Planck constant", 2),
  q("Since 2019 the kelvin is tied to the…", ["triple point of water", "Boltzmann constant", "body temperature", "absolute zero as a counted unit"], "Boltzmann constant", 2),
  q("Since 2019 the ampere is tied to the…", ["a mercury column", "elementary charge", "a wet cell of Volta", "Earth's field"], "elementary charge", 2),
  q("Since 2019 the mole is tied to the…", ["a gram of hydrogen", "Avogadro constant", "a litre of ideal gas at STP", "carbon-12's old 12-gram artifact only"], "Avogadro constant", 2),
  q("The metre is defined via the…", ["a metal bar in Paris", "speed of light in vacuum", "Earth's equator", "a yardstick at NIST"], "speed of light in vacuum", 1),
  q("The second is defined via a…", ["swinging pendulum in London", "caesium-133 hyperfine transition", "fraction of the Earth's year", "quartz crystal in a wristwatch"], "caesium-133 hyperfine transition", 2),
  q("The candela involves the luminous efficacy of radiation at…", ["the sodium D line only", "540 THz", "radio 1 MHz", "X-rays"], "540 THz", 3),
  q("The old kilogram artifact IPK was a…", ["iron cube", "platinum-iridium cylinder", "gold brick", "silicon sphere as IPK"], "platinum-iridium cylinder", 2),
  q("Kibble (watt) balances help realize the…", ["second as a pendulum", "kilogram", "candela", "mole as a counting cup"], "kilogram", 3),
  q("A silicon sphere project (Avogadro / XRCD) helped count atoms for the…", ["second", "mole / kilogram connection", "candela", "ampere as a wire count"], "mole / kilogram connection", 3),
  q("Traceability (VIM) is a property of a…", ["measuring instrument", "measurement result", "calibration lab", "technician's skill"], "measurement result", 2),
  q("A calibration compares an instrument to a…", ["random guess", "reference standard", "customer's opinion", "paint color chart"], "reference standard", 1),
  q("Adjustment of an instrument is…", ["painting it to mark its status", "changing it to agree with a standard", "retiring it from service for good", "a legal seizure by an inspector"], "changing it to agree with a standard", 2),
  q("Verification often checks whether an instrument is…", ["brand new from the factory", "within specified limits", "painted red", "wireless"], "within specified limits", 2),
  q("ISO/IEC 17025 is the standard for…", ["food safety in restaurant kitchens", "testing and calibration lab competence", "timing equipment at the Olympics", "grading standards in public schools"], "testing and calibration lab competence", 2),
  q("Accreditation of a cal lab is typically to…", ["a city's parking code", "ISO/IEC 17025, by an accreditation body", "FIFA", "the Geneva Conventions as a lab rule"], "ISO/IEC 17025, by an accreditation body", 2),
  q("A CMC in the BIPM database is a…", ["Committee for Metrology Certification", "calibration and measurement capability", "calibration method checklist", "certified mass comparator"], "calibration and measurement capability", 3),
  q("The CIPM MRA lets NMIs…", ["share a common set of postage stamps", "recognize each other's certificates", "set each other's interest rates", "issue each other's passports"], "recognize each other's certificates", 3),
  q("The GUM is the…", ["General Uniform Manual for Measuring Instruments", "Guide to the Expression of Uncertainty in Measurement", "Guide to Units of Measure for Engineers", "Gauge Users' Manual of the U.S. Army"], "Guide to the Expression of Uncertainty in Measurement", 2),
  q("The VIM is the…", ["Visual Inspection Manual for metrology", "International Vocabulary of Metrology", "Volume and Impedance Measurement guide", "Vienna Index of Measures"], "International Vocabulary of Metrology", 2),
  q("A measurand is the…", ["person doing the measuring", "quantity intended to be measured", "room where it is measured", "gauge used to measure it"], "quantity intended to be measured", 2),
  q("Accuracy is closeness to the…", ["last digit's jitter only", "true / reference value", "room's paint color", "clock on the wall always"], "true / reference value", 1),
  q("Precision is about…", ["closeness to the true value", "scatter of repeated results", "the number of decimal places", "a sharp pencil"], "scatter of repeated results", 1),
  q("Resolution is the…", ["true error of every reading it gives", "smallest change the instrument indicates", "total mass of the instrument", "largest value the instrument shows"], "smallest change the instrument indicates", 1),
  q("Repeatability is under…", ["different labs always", "the same conditions, short term", "a year later in another country", "a new operator, new method always"], "the same conditions, short term", 2),
  q("Reproducibility allows…", ["only the identical setup in one minute", "changed conditions (operator, lab, day…)", "no measurements", "only a single reading"], "changed conditions (operator, lab, day…)", 2),
  q("Type A uncertainty is evaluated by…", ["only a manufacturer's brochure as Type A", "statistical analysis of series of observations", "only a coin flip", "only weather"], "statistical analysis of series of observations", 2),
  q("Type B uncertainty is evaluated by…", ["repeating a run 100 times", "specs, cal data, or judgment", "a vote of lab staff", "the color of the dial"], "specs, cal data, or judgment", 2),
  q("Standard uncertainty is often a…", ["full range of readings", "one-sigma estimate", "percent of GDP", "letter grade"], "one-sigma estimate", 2),
  q("Expanded uncertainty U is often…", ["the reading minus its error", "k × u, with k ≈ 2 for about 95%", "u divided by k, with k ≈ 2", "the sum of every reading"], "k × u, with k ≈ 2 for about 95%", 2),
  q("A coverage factor k = 2 commonly corresponds (normal) to about…", ["50%", "68%", "95%", "99.999% always"], "95%", 2),
  q("Degrees of freedom in uncertainty work affect the…", ["color of the calibration sticker", "coverage factor for small samples", "SI prefix used on the report", "number of decimal places shown"], "coverage factor for small samples", 3),
  q("A calibration certificate should include…", ["a sticker, a smiley, and a signature", "results, uncertainty, and traceability", "a price, a logo, and a sales pitch", "the lab's logo and a phone number"], "results, uncertainty, and traceability", 1),
  q("As-found data are…", ["after the next decade", "before adjustment", "the customer's guess", "the weather"], "before adjustment", 2),
  q("As-left data are…", ["before shipping from the factory always", "after adjustment (or as found, if not adjusted)", "a lost certificate", "a draft"], "after adjustment (or as found, if not adjusted)", 2),
  q("A calibration interval is a…", ["random day picked by the outside auditor", "scheduled time or usage between calibrations", "lunch break between calibrations", "time it takes to calibrate once"], "scheduled time or usage between calibrations", 1),
  q("Drift is…", ["slow movement of a fishing line", "change of indication with time", "a type of fine-pitch screw", "a random scatter between readings"], "change of indication with time", 1),
  q("Hysteresis is…", ["a slow change of reading over time", "direction-dependent difference in readings", "a random scatter between repeat readings", "a type of laser used in interferometry"], "direction-dependent difference in readings", 2),
  q("Dead band / backlash can make an instrument…", ["faster than light", "insensitive to small reversals", "a primary standard always", "dimensionless"], "insensitive to small reversals", 2),
  q("Linearity error is departure from a…", ["circle of latitude", "straight-line relation", "sine of time only", "log of color"], "straight-line relation", 2),
  q("The reference temperature for dimensional cal in the SI shop is typically…", ["0 °C", "20 °C", "37 °C", "100 °C"], "20 °C", 1),
  q("A steel part longer than its 20 °C length when hot shows…", ["shrink fit of ice only", "thermal expansion", "time dilation of special relativity", "magnetic hysteresis"], "thermal expansion", 1),
  q("CTE is the…", ["calibration test equipment", "coefficient of thermal expansion", "candela to energy", "coulomb thermal error"], "coefficient of thermal expansion", 2),
  q("A 1 °C error on a metre of steel (CTE ~11–12 ppm/K) is about…", ["1 metre", "11–12 micrometres", "1 millimetre on the nose always", "1 nanometre only"], "11–12 micrometres", 3),
  q("Gauge blocks (Jo blocks) are…", ["mass pieces of OIML class M1 for scales", "precision length blocks that wring together", "electrical resistors used as standards", "colored optical filters for photometry"], "precision length blocks that wring together", 1),
  q("Wringing gauge blocks uses…", ["spot welding at the corners", "flat faces, a thin film, and attraction", "a dab of thread-locking compound", "low-temperature solder joints"], "flat faces, a thin film, and attraction", 2),
  q("Grade K / 00 gauge blocks are typically for…", ["tape measures on a jobsite", "interferometric / primary lab use", "kitchen spoons", "school rulers"], "interferometric / primary lab use", 3),
  q("Mechanical comparison of gauge blocks uses a…", ["bathroom scale against a master", "comparator probe against a master", "kitchen timer and a ruler", "magnetic compass and a protractor"], "comparator probe against a master", 2),
  q("Interferometric calibration of gauge blocks uses…", ["a cloth measuring tape", "the wavelength of light", "a kitchen scale", "a stopwatch"], "the wavelength of light", 2),
  q("A helium-neon laser's vacuum wavelength is a classic…", ["mass standard in the lab", "length standard in the lab", "candela source for photometry", "mole counter for chemistry"], "length standard in the lab", 3),
  q("Air wavelength of a laser depends on…", ["the color of the lab's walls", "temperature, pressure, and humidity", "the operator's height and weight", "the day of the week and the hour"], "temperature, pressure, and humidity", 3),
  q("An optical flat tests…", ["mass by comparing weights", "flatness by interference fringes", "pH by color change", "radioactivity by counting clicks"], "flatness by interference fringes", 2),
  q("Newton's rings are an…", ["atomic nucleus model", "interference pattern", "gear tooth profile", "thread class symbol"], "interference pattern", 2),
  q("A surface plate is often…", ["rubber foam, for a soft base", "granite, for a reference plane", "cloth, for a clean surface", "ice, for a cold surface"], "granite, for a reference plane", 1),
  q("A height gauge sits on a…", ["pillow block", "surface plate", "lathe chuck", "workbench vise"], "surface plate", 1),
  q("A micrometer typically resolves…", ["1 inch or 1 cm", "0.01 mm or 0.001 mm", "1 mm or 0.5 mm", "1 metre or 1 foot"], "0.01 mm or 0.001 mm", 2),
  q("A caliper (vernier/dial/digital) is for…", ["temperature, humidity, and pressure", "outside, inside, and depth lengths", "pH, conductivity, and salinity", "mass, weight, and density"], "outside, inside, and depth lengths", 1),
  q("Parallax error happens when you…", ["use the wrong SI prefix", "read a scale off-axis", "calibrate too often", "ground a shield"], "read a scale off-axis", 1),
  q("Abbe error is a…", ["chemical contamination of the scale", "offset error from a scale out of line", "a type of laser used for alignment", "a mass class for fine balances"], "offset error from a scale out of line", 3),
  q("Cosine error in a length setup is from…", ["using kelvin instead of Celsius", "the axis misaligned with the length", "too much coffee for the operator", "rounding the final digit"], "the axis misaligned with the length", 2),
  q("A CMM is a…", ["centrifugal mass meter", "coordinate measuring machine", "coulomb multiplier", "camera of the Moon only"], "coordinate measuring machine", 2),
  q("CMM probes can be…", ["kitchen spoons, forks, or knives", "touch-trigger, scanning, or optical", "Geiger tubes or ion chambers", "pH bulbs or salt bridges"], "touch-trigger, scanning, or optical", 2),
  q("A laser tracker measures…", ["pH of a liquid", "3-D position of a target", "blood type of a sample", "wind speed only"], "3-D position of a target", 3),
  q("An autocollimator measures small…", ["masses of loaded trucks", "angular deviations of a mirror", "pH changes of a solution", "radioactivity of a sample"], "angular deviations of a mirror", 3),
  q("A theodolite / total station is for…", ["mass and weight", "angles and distances", "pH and acidity", "candela and lux"], "angles and distances", 2),
  q("GD&T flatness, straightness, roundness are…", ["SI base units", "form tolerances", "mass classes", "thread pitches of UN only"], "form tolerances", 2),
  q("Roundness can be measured on a…", ["bathroom scale platform", "roundness-tester spindle", "kitchen timer dial", "Geiger counter tube"], "roundness-tester spindle", 3),
  q("Surface roughness parameters include…", ["pH and pKa", "Ra, Rz (among others)", "F1 and E2 as roughness", "k and u"], "Ra, Rz (among others)", 3),
  q("A dial indicator amplifies…", ["mass into candela", "small displacements", "time into moles", "color into volts"], "small displacements", 1),
  q("An LVDT is a…", ["low-voltage direct transformer", "linear variable differential transformer", "light-vector displacement tester", "large vacuum deadweight tester"], "linear variable differential transformer", 3),
  q("A load cell measures…", ["time", "force", "pH", "candela"], "force", 1),
  q("Force's SI unit is the…", ["kilogram as force", "newton", "pound as SI", "dyne as SI"], "newton", 1),
  q("A deadweight tester for pressure uses…", ["a rubber balloon of known volume", "known masses on a piston of known area", "a kitchen clock and a spring", "a compass and a known magnet"], "known masses on a piston of known area", 2),
  q("Pressure's SI unit is the…", ["bar", "pascal (N/m²)", "torr as SI base", "psi as SI"], "pascal (N/m²)", 1),
  q("Gauge pressure is relative to…", ["absolute zero pressure always", "ambient atmosphere", "the triple point of water", "a vacuum of space"], "ambient atmosphere", 2),
  q("Absolute pressure is relative to…", ["the shop's floor", "vacuum (zero pressure)", "sea-level standard", "gauge of a tire"], "vacuum (zero pressure)", 2),
  q("A torque wrench is calibrated with a…", ["stopwatch and a known speed", "known arm and force, or a transducer", "pH buffer and a known volume", "optical flat and a monochromatic light"], "known arm and force, or a transducer", 2),
  q("Torque's SI unit is the…", ["joule as a synonym used for torque wrenches", "newton-metre", "watt", "pascal"], "newton-metre", 2),
  q("OIML weight classes include…", ["only A, B, C of batteries", "E1, E2, F1, F2, M1…", "only SAE grades of bolts", "letter grades of school"], "E1, E2, F1, F2, M1…", 3),
  q("E2 masses are for…", ["ballast in a ship's hull", "high-accuracy calibration work", "kitchen diet scales of ±50 g", "sandbags on a loading dock"], "high-accuracy calibration work", 3),
  q("Mass calibration needs…", ["a gusty loading dock and bare hands", "a draft-free balance and gloved handling", "a magnet attached to every piece", "oiled hands to prevent rust"], "a draft-free balance and gloved handling", 1),
  q("Buoyancy correction in mass work accounts for…", ["the Moon's gravity only", "air density acting on volumes", "color of the weight", "the serial number"], "air density acting on volumes", 3),
  q("An SPRT is a…", ["spring-loaded pressure relief tester", "standard platinum resistance thermometer", "surface plate reference tool", "silver-plated reference thermocouple"], "standard platinum resistance thermometer", 2),
  q("ITS-90 is the…", ["International Thread Standard of 1990", "International Temperature Scale of 1990", "International Tolerance Standard of 1990", "an ISO standard for test sieves"], "International Temperature Scale of 1990", 2),
  q("The triple point of water is a…", ["boiling point of water at 1 atm", "fixed point (0.01 °C) in thermometry", "standard room temperature (20 °C)", "body temperature (37 °C)"], "fixed point (0.01 °C) in thermometry", 2),
  q("A thermocouple measures temperature via a…", ["change of mass as it heats", "voltage from two dissimilar metals", "pH change in a probe gel", "radioactivity of a heated metal"], "voltage from two dissimilar metals", 2),
  q("Type K thermocouples are…", ["pure platinum only", "chromel–alumel, general purpose", "only tungsten of vacuum furnaces as Type K", "only gold–gold"], "chromel–alumel, general purpose", 3),
  q("Type S/R/B thermocouples are…", ["base-metal of HVAC only", "noble-metal, high temperature", "only Type T of food", "only infrared"], "noble-metal, high temperature", 3),
  q("An RTD's resistance…", ["is independent of temperature", "rises with temperature (typical metals)", "is a pH", "counts moles"], "rises with temperature (typical metals)", 2),
  q("A 4-wire RTD connection is used to…", ["heat the part", "cancel lead resistance", "add extra uncertainty on purpose", "measure candela"], "cancel lead resistance", 2),
  q("Cold-junction compensation is needed for…", ["gauge blocks", "thermocouples", "surface plates", "E2 masses"], "thermocouples", 2),
  q("A dry-well / block calibrator is for…", ["gauge blocks of length", "temperature sensors", "optical flats", "masses"], "temperature sensors", 2),
  q("A stirred liquid bath is a…", ["mass comparator for small weights", "uniform temperature medium for probes", "laser interferometer for length", "CMM for 3-D parts"], "uniform temperature medium for probes", 2),
  q("Humidity can be generated for cal with a…", ["gauge block stack in a dry box", "two-pressure generator or salt solutions", "optical flat and a light source", "deadweight tester and a sealed piston"], "two-pressure generator or salt solutions", 3),
  q("Dew point is the temperature at which…", ["steel melts", "air becomes saturated", "the SI second ticks", "a laser mode-locks"], "air becomes saturated", 2),
  q("RH is…", ["roughness height", "relative humidity", "a mass class", "a thread"], "relative humidity", 1),
  q("A hygrometer measures…", ["mass", "humidity", "length of gauge blocks", "candela"], "humidity", 1),
  q("Electrical cal uses standards of…", ["granite, steel, and glass", "voltage, resistance, and current", "coco fiber and cork bark", "length, mass, and angle"], "voltage, resistance, and current", 1),
  q("A Josephson junction array can realize a…", ["metre stick", "volt", "candela", "mole of water"], "volt", 3),
  q("A quantum Hall device can realize a…", ["second", "ohm (resistance)", "candela", "kelvin as a resistor of ice"], "ohm (resistance)", 3),
  q("A DMM is a…", ["dimensional mass machine", "digital multimeter", "dew-mass meter", "dial mass micrometer"], "digital multimeter", 1),
  q("A scope (oscilloscope) displays…", ["mass versus kelvin only", "voltage versus time (typically)", "only pH", "only candela"], "voltage versus time (typically)", 1),
  q("Frequency is traced to…", ["a drum", "atomic clocks / the SI second", "a granite plate", "a gauge block of 100 mm always"], "atomic clocks / the SI second", 2),
  q("A GPS-disciplined oscillator is a…", ["mass standard for field use", "field frequency / time reference", "optical flat for field use", "pH buffer for field use"], "field frequency / time reference", 3),
  q("The SI prefix micro (µ) means…", ["10⁻³", "10⁻⁶", "10⁻⁹", "10⁻²"], "10⁻⁶", 1),
  q("The SI prefix nano means…", ["10⁻⁶", "10⁻⁹", "10⁻¹²", "10⁻³"], "10⁻⁹", 1),
  q("The SI prefix pico means…", ["10⁻⁶", "10⁻⁹", "10⁻¹²", "10⁻¹⁵"], "10⁻¹²", 2),
  q("The SI prefix milli means…", ["10⁻⁶", "10⁻³", "10⁻²", "10⁻⁹"], "10⁻³", 1),
  q("The SI prefix kilo means…", ["10²", "10³", "10⁶", "10⁻³"], "10³", 1),
  q("The SI prefix mega means…", ["10³", "10⁶", "10⁹", "10²"], "10⁶", 1),
  q("The SI prefix giga means…", ["10⁶", "10⁹", "10¹²", "10³"], "10⁹", 1),
  q("A micrometre is also called a…", ["mile", "micron (informally)", "furlong", "fathom as a synonym"], "micron (informally)", 2),
  q("1 inch is exactly…", ["25 mm", "25.4 mm", "30 mm", "20 mm"], "25.4 mm", 1),
  q("Fiducial temperature 20 °C is 293.15…", ["fahrenheit", "kelvin", "rankine as SI", "celsius"], "kelvin", 2),
  q("A reference standard should be…", ["less accurate than the unit, on purpose", "more accurate than the unit under test", "untraceable, to save on costs", "unlabeled, to avoid any bias"], "more accurate than the unit under test", 2),
  q("TUR is the…", ["thermal under room", "test uncertainty ratio", "torque unit of radians", "type-unknown reading"], "test uncertainty ratio", 3),
  q("A 4:1 TUR means the standard's uncertainty is about…", ["four times worse than the UUT", "¼ of the UUT tolerance", "equal to the UUT", "unrelated"], "¼ of the UUT tolerance", 3),
  q("Measurement assurance is…", ["a one-time sticker on each instrument", "ongoing control checks on the cal system", "repainting the lab once a year", "an insurance policy for the lab"], "ongoing control checks on the cal system", 2),
  q("A check standard is run to…", ["replace the SI definitions", "watch for drift of the process", "set the color of the room", "name the lab for audits"], "watch for drift of the process", 2),
  q("Control charts in a cal lab plot…", ["employee birthdays only", "check-standard results over time", "stock prices", "the weather of Mars only"], "check-standard results over time", 2),
  q("Out-of-tolerance as-found may trigger…", ["a lab holiday until the next audit", "a review of parts measured since then", "renaming the instrument's model", "a new BIPM definition of the unit"], "a review of parts measured since then", 2),
  q("A limited cal might…", ["erase the serial number", "cover only part of the range", "void ISO forever", "change the SI"], "cover only part of the range", 2),
  q("A fixture error can dominate if you…", ["use kelvin on the report", "clamp or locate the part poorly", "write the certificate in ink", "wear gloves while handling masses"], "clamp or locate the part poorly", 1),
  q("Dirt on a gauge block will…", ["improve accuracy always", "ruin wring and add length", "change the SI second", "calibrate a thermocouple"], "ruin wring and add length", 1),
  q("Hand heat on a micrometer frame can…", ["cool it to absolute zero", "expand it and bias the reading", "change mass class", "fix hysteresis of a load cell"], "expand it and bias the reading", 2),
  q("Let parts soak so they reach…", ["boiling", "thermal equilibrium with the lab", "absolute zero", "the temperature of a welding arc"], "thermal equilibrium with the lab", 1),
  q("A metrology lab's environment is controlled for…", ["music volume and lighting color", "temperature, humidity, and vibration", "chair color and wall decorations", "coffee brand and snack supply"], "temperature, humidity, and vibration", 1),
  q("Vibration isolation helps…", ["hammers and chisels", "balances and interferometers", "sledgehammer demolition work", "forklifts on the loading dock"], "balances and interferometers", 2),
  q("Cleanliness in a dimensional lab prevents…", ["traceability", "particles from becoming 'length'", "the SI logo", "accreditation paperwork"], "particles from becoming 'length'", 2),
  q("A master (lab standard) is calibrated…", ["never, once it is certified", "more rarely, at a higher-level lab", "daily, by the technician on shift", "against the unit under test"], "more rarely, at a higher-level lab", 1),
  q("Working standards are calibrated against…", ["the customer's guess", "reference / master standards", "a newspaper", "Wikipedia"], "reference / master standards", 1),
  q("Field standards are…", ["BIPM artifacts stored in Sèvres only", "used in the field and calibrated more often", "untraceable to any national standard", "always E1-class kilogram masses"], "used in the field and calibrated more often", 2),
  q("An intrinsic standard (like a Josephson array) realizes a unit from…", ["a dusty artifact of unknown origin only", "a physical constant / quantum effect", "a vote", "a brand name"], "a physical constant / quantum effect", 3),
  q("The metre used to be a…", ["cup of water, then a pendulum, now c", "prototype bar, then krypton wavelength, now c", "pendulum length, then a yard, now c", "royal yard, then a foot, now a pendulum"], "prototype bar, then krypton wavelength, now c", 3),
  q("The second used to be a fraction of the…", ["lunar month, then quartz, now caesium", "mean solar day, then ephemeris, now caesium", "sidereal year, then a pendulum", "hour of a water clock"], "mean solar day, then ephemeris, now caesium", 3),
  q("UTC is…", ["Universal Torque Class", "Coordinated Universal Time", "Unified Test Calibration", "Universal Thermal Constant"], "Coordinated Universal Time", 1),
  q("Leap seconds (when used) keep UTC near…", ["the Planck constant", "Earth rotation / UT1", "the candela", "a gauge block"], "Earth rotation / UT1", 3),
  q("A primary standard of a quantity is…", ["the cheapest tape measure in the lab", "the top of the chain, realizing the unit", "a rusty ruler from the toolbox", "the instrument being calibrated"], "the top of the chain, realizing the unit", 2),
  q("A secondary standard is calibrated against a…", ["working standard", "primary standard", "field instrument", "calendar"], "primary standard", 2),
  q("Metrological confirmation (ISO 10012) is…", ["a signature on every report", "ensuring equipment is fit for its use", "a tax filing for the lab", "a certificate of the lab's accreditation"], "ensuring equipment is fit for its use", 3),
  q("MSA in quality talk is…", ["mass-standard artifact", "measurement system analysis", "metrology safety audit", "mean scatter average"], "measurement system analysis", 2),
  q("Gage R&R studies the…", ["range and resolution of a gauge", "repeatability and reproducibility", "rate of return of a lab", "reliability and repair records"], "repeatability and reproducibility", 2),
  q("Bias in MSA is…", ["random jitter between readings", "systematic offset from a reference", "the serial number of the gauge", "the lab's preferred supplier"], "systematic offset from a reference", 2),
  q("A gold-plating micrometer anvil is still…", ["a primary realization of the metre", "subject to wear, dirt, and cal", "untraceable by law", "a mass standard"], "subject to wear, dirt, and cal", 1),
  q("Never drop a gauge block because…", ["it improves the wring later", "a ding becomes a length error", "NIST requires a drop test", "steel hardens after shocks"], "a ding becomes a length error", 1),
  q("Deburr and clean before…", ["throwing the certificate out", "precision measurement", "the coffee run", "painting the CMM"], "precision measurement", 1),
  q("A '10:1' shop rule of thumb means the gage should resolve about…", ["ten times the tolerance as resolution", "a tenth of the tolerance (simple version)", "the same", "nothing"], "a tenth of the tolerance (simple version)", 2),
  q("Calliper jaws must be…", ["bent on purpose", "aligned and not over-forced", "magnetic on steel always as a must", "hot"], "aligned and not over-forced", 1),
  q("A thread mic has…", ["only flat faces of a length bar", "anvils shaped for pitch diameter", "a pH probe", "a Geiger tube"], "anvils shaped for pitch diameter", 3),
  q("Pitch diameter is a…", ["gear tooth count, not a diameter", "thread size, not the major diameter", "unit of mass used for threads", "thread's outermost diameter"], "thread size, not the major diameter", 2),
  q("A sine bar measures…", ["mass using blocks and a known lever", "angles using blocks and a known length", "pH using a probe and a known buffer", "flatness using a light and fringes"], "angles using blocks and a known length", 3),
  q("A granite square checks…", ["mass class of weights", "right angles / squareness", "dew point of the room", "the SI mole"], "right angles / squareness", 2),
  q("Parallelism of a part can be checked with a…", ["pH meter", "indicator on a plate, or a CMM", "Geiger counter", "candela photometer only"], "indicator on a plate, or a CMM", 2),
  q("A bore gauge measures…", ["outside diameter", "inside diameter", "surface roughness", "thread pitch"], "inside diameter", 1),
  q("An air gage uses…", ["a kitchen fan to cool the part", "nozzle back-pressure to sense gaps", "a thermocouple to sense heat", "a Geiger tube to count particles"], "nozzle back-pressure to sense gaps", 3),
  q("Optical comparators project a…", ["mass reading onto a screen", "magnified shadow of a profile", "pH chart onto a wall", "radio spectrum of the part"], "magnified shadow of a profile", 2),
  q("A laser interferometer can calibrate a…", ["pH electrode", "machine-tool axis or CMM scale", "kitchen scale of ±1 g", "wall clock of a kitchen"], "machine-tool axis or CMM scale", 2),
  q("Volumetric CMM compensation maps…", ["weather patterns across the county", "geometric errors in the measuring volume", "employee hours across the shift", "stock prices of the machine maker"], "geometric errors in the measuring volume", 3),
  q("21 parametric errors of a Cartesian CMM include…", ["color, gloss, and texture", "straightness, pitch, yaw, and roll", "pH, salinity, and turbidity", "mass, weight, and density only"], "straightness, pitch, yaw, and roll", 3),
  q("A step gauge is a…", ["series of pH buffers for meters", "multi-face length artifact for CMMs", "set of E2 masses for balances", "thermocouple array for furnaces"], "multi-face length artifact for CMMs", 3),
  q("A ball bar (on a CMM or machine) checks…", ["surface roughness", "circular-path errors", "coolant pH drift", "spindle temperature"], "circular-path errors", 3),
  q("Kinematic coupling locates a fixture with…", ["glue on every mating face", "three vees or similar contacts", "a random pile of shims", "a magnet of unknown force"], "three vees or similar contacts", 3),
  q("The SI brochure is published by the…", ["FIFA", "BIPM", "NATO", "the IOC"], "BIPM", 2),
  q("A newton is…", ["kg only", "kg·m/s²", "m/s", "A·s"], "kg·m/s²", 2),
  q("A joule is…", ["a torque wrench's only SI name used on food labels", "N·m (energy)", "a candela", "a mole"], "N·m (energy)", 2),
  q("A watt is…", ["a mass", "J/s (power)", "a length", "a mole"], "J/s (power)", 1),
  q("A pascal is…", ["kg", "N/m²", "s", "cd"], "N/m²", 2),
  q("A volt is…", ["a mass", "W/A (or J/C)", "a kelvin as a synonym", "a mole"], "W/A (or J/C)", 2),
  q("An ohm is…", ["a candela", "V/A", "a second", "a metre"], "V/A", 1),
  q("A hertz is…", ["a kg", "s⁻¹", "a mole", "a candela"], "s⁻¹", 1),
  q("A coulomb is…", ["a kelvin", "A·s", "a metre", "a candela"], "A·s", 2),
  q("A farad is…", ["a mass class", "C/V (capacitance)", "a gauge block grade", "a thread"], "C/V (capacitance)", 3),
  q("A henry is…", ["a unit of length", "V·s/A (inductance)", "a unit of light", "a unit of amount"], "V·s/A (inductance)", 3),
  q("A tesla is…", ["a unit of temperature", "Wb/m² (flux density)", "a unit of mass", "a unit of time"], "Wb/m² (flux density)", 3),
  q("The litre is a…", ["SI base unit for volume and capacity", "non-SI unit accepted for use with SI", "unit of mass for liquids", "derived SI unit with a special name"], "non-SI unit accepted for use with SI", 2),
  q("The tonne (t) is…", ["an SI base unit of mass", "10³ kg, accepted with SI", "2000 lb, a U.S. unit", "10² kg, accepted with SI"], "10³ kg, accepted with SI", 2),
  q("The electronvolt is…", ["an SI base unit of voltage", "a unit of energy accepted with SI", "a unit of charge accepted with SI", "a unit of power used in physics"], "a unit of energy accepted with SI", 2),
  q("A light-year is a unit of…", ["time, not distance", "distance, not time", "speed, not distance", "brightness"], "distance, not time", 1),
  q("An ångström is…", ["an SI base", "10⁻¹⁰ m", "a second", "a candela"], "10⁻¹⁰ m", 3),
  q("NASA stands for the…", ["North American Soccer Association", "National Aeronautics and Space Administration", "National Atomic Standards Agency", "Navy Air-Sea Arm"], "National Aeronautics and Space Administration", 1),
  q("ESA is the…", ["Egyptian Survey Authority", "European Space Agency", "Earth Science Alliance only", "a NASA center in Texas"], "European Space Agency", 1),
  q("JAXA is the space agency of…", ["China", "Japan", "India", "South Korea as JAXA"], "Japan", 2),
  q("CNSA is the space agency of…", ["Canada", "China", "Chile", "Czechia"], "China", 2),
  q("ISRO is the space agency of…", ["Indonesia", "India", "Iran", "Ireland"], "India", 2),
  q("Roscosmos is the space agency of…", ["Romania", "Russia", "Rwanda", "Serbia"], "Russia", 1),
  q("CSA (space) is the…", ["Chinese Space Administration", "Canadian Space Agency", "California Space Agency", "Chilean Space Agency as CSA"], "Canadian Space Agency", 2),
  q("The Kármán line, a common space boundary, is at…", ["10 km", "50 km", "100 km", "400 km"], "100 km", 2),
  q("LEO is…", ["lunar escape orbit", "low Earth orbit", "long elliptical ocean", "lagrange earth-outer"], "low Earth orbit", 1),
  q("GEO (geostationary) altitude is about…", ["400 km", "2000 km", "36 000 km", "1 AU"], "36 000 km", 2),
  q("A geostationary satellite hangs over…", ["a pole with a 90-minute period", "the equator, period one sidereal day", "the Moon", "Mars"], "the equator, period one sidereal day", 2),
  q("The ISS orbits in…", ["GEO", "low Earth orbit", "around the Moon as its home", "around L2"], "low Earth orbit", 1),
  q("The ISS flies about…", ["36 000 km up, one orbit a day", "400 km up, ~90 minutes per rev", "4000 km up, ~6 hours an orbit", "40 km up, ~9 minutes an orbit"], "400 km up, ~90 minutes per rev", 2),
  q("Microgravity on a station is mostly…", ["because Earth has no pull at 400 km", "free-fall, not the absence of Earth's gravity", "because mass is zero", "because time stops"], "free-fall, not the absence of Earth's gravity", 2),
  q("Delta-v is a…", ["type of delta-shaped airplane wing", "measure of the velocity change needed", "unit of mass for rocket fuel", "NASA center in Virginia"], "measure of the velocity change needed", 2),
  q("Specific impulse (Isp) measures…", ["how many crew a rocket can carry", "how efficiently a rocket uses propellant", "how thick the paint on a rocket is", "how much a rocket's payload weighs"], "how efficiently a rocket uses propellant", 2),
  q("A higher Isp means…", ["a heavier propellant tank, always", "more impulse per mass of propellant", "less impulse per mass of propellant", "a shorter nozzle, always"], "more impulse per mass of propellant", 2),
  q("Chemical rockets throw mass; the Tsiolkovsky equation relates…", ["only wing lift", "delta-v to mass ratio and exhaust speed", "only radio gain", "only battery watt-hours of a phone"], "delta-v to mass ratio and exhaust speed", 3),
  q("LOX is…", ["liquid ozone", "liquid oxygen", "low-orbit xenon", "a lithium oxide pellet"], "liquid oxygen", 1),
  q("RP-1 is a…", ["solid rubber-based propellant", "refined kerosene rocket fuel", "a hydrazine blend", "liquid hydrogen"], "refined kerosene rocket fuel", 2),
  q("Methalox is…", ["liquid methanol + liquid oxygen", "liquid methane + liquid oxygen", "hydrazine + nitrogen tetroxide", "liquid methane + liquid fluorine"], "liquid methane + liquid oxygen", 2),
  q("Hydrolox is…", ["kerosene + liquid oxygen", "liquid hydrogen + liquid oxygen", "liquid methane + liquid oxygen", "liquid hydrogen + liquid fluorine"], "liquid hydrogen + liquid oxygen", 2),
  q("Hypergolic propellants…", ["need a spark plug of a car always", "ignite on contact", "are always cryogenic hydrolox", "are solid only"], "ignite on contact", 2),
  q("A solid rocket motor's grain is the…", ["crew cabin insulation", "shaped solid propellant", "nozzle throat insert", "igniter at the top"], "shaped solid propellant", 2),
  q("Staging a rocket drops…", ["the payload always at liftoff", "empty tanks/engines to raise mass ratio", "the crew as a rule of staging", "the guidance computer always"], "empty tanks/engines to raise mass ratio", 1),
  q("Max-Q is the…", ["maximum crew size on ascent", "peak dynamic pressure on ascent", "minimum altitude for orbit", "max Isp on the pad"], "peak dynamic pressure on ascent", 3),
  q("MECO is…", ["a NASA center in Alabama", "main-engine cutoff", "a meteorite", "a spacesuit"], "main-engine cutoff", 2),
  q("SECO is…", ["solid-engine casing", "second-engine cutoff", "stage-engine checkout", "second-engine ignition"], "second-engine cutoff", 3),
  q("A payload fairing is the…", ["landing pad on the drone ship", "nose shroud that protects the cargo", "crew exercise module in orbit", "radioisotope power unit"], "nose shroud that protects the cargo", 1),
  q("RCS thrusters provide…", ["main liftoff thrust of a Falcon first stage as RCS", "small attitude/translation control", "life support oxygen", "landing legs"], "small attitude/translation control", 2),
  q("An IMU is an…", ["international moon unit", "inertial measurement unit", "a hatch", "a wrench"], "inertial measurement unit", 2),
  q("A star tracker finds…", ["mass of the vehicle", "attitude from star fields", "pH of coolant", "the SI second as a sundial"], "attitude from star fields", 2),
  q("A heat shield on reentry is often…", ["a thin paper blanket", "ablative or ceramic tiles", "bare aluminum skin", "a layer of water ice"], "ablative or ceramic tiles", 1),
  q("Reentry plasma can…", ["cool the vehicle below freezing", "block radio and heat the shield", "add oxygen to the cabin air", "make the capsule float"], "block radio and heat the shield", 2),
  q("Escape velocity from Earth's surface is about…", ["1 km/s", "7.8 km/s as escape (that's LEO speed)", "11 km/s", "30 km/s as Earth's escape"], "11 km/s", 2),
  q("LEO orbital speed is about…", ["1 km/s", "7.8 km/s", "11 km/s as circular LEO", "30 km/s"], "7.8 km/s", 2),
  q("The Oberth effect says a burn is more efficient when…", ["you are at rest on a pad", "you are already moving fast", "you use solid motors", "you coast with RCS only"], "you are already moving fast", 3),
  q("A Hohmann transfer is a…", ["straight line at constant speed", "two-burn ellipse between circular orbits", "aerobrake only", "ion hover"], "two-burn ellipse between circular orbits", 3),
  q("Lagrange points are…", ["NASA tracking stations in a network", "balance points in a three-body system", "craters on the Moon's far side", "booster landing zones in Texas"], "balance points in a three-body system", 2),
  q("JWST orbits near…", ["LEO like Hubble", "Sun–Earth L2", "GEO over Africa", "the lunar surface"], "Sun–Earth L2", 2),
  q("Hubble orbits in…", ["L2", "low Earth orbit", "GEO", "a polar lunar orbit as its home"], "low Earth orbit", 1),
  q("JWST's mirror is…", ["a single glass Hubble copy in LEO", "segmented, gold-coated beryllium", "a spinning pool of liquid mercury", "an inflatable silver balloon"], "segmented, gold-coated beryllium", 2),
  q("Hubble was serviced by…", ["Falcon 9", "Space Shuttle astronauts", "Apollo as Hubble's ride", "Soyuz spacewalks of the 1990s as Hubble's program"], "Space Shuttle astronauts", 2),
  q("Voyager 1 is in…", ["low Earth orbit", "interstellar space", "orbit around Saturn", "a garage in Pasadena"], "interstellar space", 2),
  q("Voyager's Golden Record is a…", ["heat shield for the probe's antenna", "message for whoever finds the probe", "main engine's fuel reserve", "data disk of its flight logs"], "message for whoever finds the probe", 1),
  q("Cassini orbited…", ["Jupiter as its long home", "Saturn", "Mars", "Pluto"], "Saturn", 1),
  q("New Horizons flew by…", ["Neptune and then Triton", "Pluto and then Arrokoth", "Saturn and then Titan", "Mars and then Phobos"], "Pluto and then Arrokoth", 2),
  q("Juno orbits…", ["Saturn", "Jupiter", "Neptune", "Uranus"], "Jupiter", 2),
  q("Curiosity and Perseverance are…", ["Venus balloons", "NASA Mars rovers", "Saturn orbiters", "lunar hoppers of Apollo"], "NASA Mars rovers", 1),
  q("Ingenuity was a…", ["submarine of Europa", "helicopter on Mars", "crew capsule", "ion tug"], "helicopter on Mars", 1),
  q("Apollo 11 landed in…", ["1961", "1965", "1969", "1975"], "1969", 1),
  q("The first human in space was…", ["Alan Shepard as first orbital", "Yuri Gagarin (1961)", "John Glenn as first human", "Neil Armstrong as first in space"], "Yuri Gagarin (1961)", 1),
  q("The first American to orbit was…", ["Gagarin", "John Glenn", "Armstrong as first U.S. orbit", "Shepard"], "John Glenn", 2),
  q("Sputnik 1 launched in…", ["1945", "1957", "1961", "1969"], "1957", 1),
  q("Valentina Tereshkova was the first…", ["American in orbit", "woman in space", "moonwalker", "space tourist of 2021"], "woman in space", 2),
  q("Sally Ride was the first…", ["woman of any country in space", "American woman in space", "moonwalker", "ISS commander of 1961"], "American woman in space", 2),
  q("The first spacewalk was by…", ["Armstrong", "Alexei Leonov", "White", "Gagarin as a walk"], "Alexei Leonov", 3),
  q("A CubeSat is a…", ["NASA's lunar lander of Apollo", "small satellite built in 10 cm units", "a booster stage of Falcon Heavy", "a spacesuit"], "small satellite built in 10 cm units", 2),
  q("Starlink is a…", ["GEO TV satellite of the 1960s", "LEO broadband satellite network", "GPS network for the Moon", "planned city on Mars"], "LEO broadband satellite network", 1),
  q("GPS satellites are in…", ["LEO like the ISS", "medium Earth orbit (not GEO)", "GEO as a hover over one city", "the Moon"], "medium Earth orbit (not GEO)", 2),
  q("A polar orbit is useful for…", ["hovering over one city like GEO", "observing the whole Earth", "always staying in Earth's shadow", "landing on Mars"], "observing the whole Earth", 2),
  q("Sun-synchronous orbits keep a…", ["fixed crew exercise schedule", "similar lighting time for imaging", "geostationary hover over one spot", "fixed spot at a Lagrange point"], "similar lighting time for imaging", 3),
  q("Van Allen belts are…", ["rings of asteroids around Earth", "zones of trapped radiation around Earth", "rings of ice like Saturn's", "auroras that occur only on Jupiter"], "zones of trapped radiation around Earth", 2),
  q("A Hohmann transfer to Mars takes on the order of…", ["hours (about 6–9)", "days (about 6–9)", "months (about 6–9)", "years (about 6–9)"], "months (about 6–9)", 2),
  q("Communications delay to Mars is…", ["zero, since radio is instant", "minutes, varying with distance", "years, varying with distance", "hours, varying with distance"], "minutes, varying with distance", 2),
  q("A light-second is about…", ["300 km", "3000 km", "300 000 km", "1 AU"], "300 000 km", 2),
  q("1 AU is the…", ["Earth–Moon distance", "Earth–Sun mean distance", "LEO altitude", "GEO altitude"], "Earth–Sun mean distance", 1),
  q("A parabolic escape trajectory has eccentricity…", ["0", "0.5", "1", "2 as parabola"], "1", 3),
  q("A circular orbit has eccentricity…", ["1", "0", "2", "0.5"], "0", 2),
  q("Payload mass fraction is…", ["always 90% of liftoff mass", "payload divided by total mass", "Isp divided by burn time", "crew mass divided by payload"], "payload divided by total mass", 2),
  q("Mass ratio in the rocket equation is…", ["payload / fuel", "initial mass / final mass", "thrust / weight of Earth always", "crew / cargo"], "initial mass / final mass", 3),
  q("Thrust-to-weight > 1 is needed to…", ["orbit without any horizontal speed", "lift off vertically from the pad", "reenter the atmosphere safely", "dock with a space station"], "lift off vertically from the pad", 1),
  q("Vacuum engines have…", ["no nozzles, just open combustion chambers", "larger nozzles than sea-level engines", "smaller bells than sea-level engines", "solid grains instead of liquid fuel"], "larger nozzles than sea-level engines", 2),
  q("Sea-level engines must avoid…", ["any regenerative cooling of the bell", "flow separation from an oversized bell", "any gimbaling of the engine at all", "any igniters inside the chamber"], "flow separation from an oversized bell", 3),
  q("Gimbaling an engine provides…", ["life support control", "thrust-vector control", "radio signal control", "landing radar"], "thrust-vector control", 2),
  q("Grid fins on a booster help…", ["start the turbopump as fins", "steer during reentry / landing", "dock to ISS", "radiate JWST heat"], "steer during reentry / landing", 2),
  q("A suicide burn / hoverslam is a…", ["slow docking burn at the ISS", "late, high-thrust landing burn", "fairing deployment sequence", "early stage-separation burn"], "late, high-thrust landing burn", 3),
  q("Falcon 9 is a…", ["three-stage solid ICBM of the 1960s", "two-stage rocket with a reusable booster", "crew capsule with a reusable heat shield", "single-stage rocket that is fully reusable"], "two-stage rocket with a reusable booster", 1),
  q("Falcon Heavy has…", ["one core and two solid boosters", "three Falcon first-stage cores", "two Falcon first-stage cores", "a nuclear upper stage"], "three Falcon first-stage cores", 2),
  q("Starship (as flown in tests) is a…", ["Apollo-style capsule on a booster", "fully reusable two-stage steel vehicle", "single-stage carbon-fiber spaceplane", "expendable three-stage moon rocket"], "fully reusable two-stage steel vehicle", 2),
  q("Merlin engines burn…", ["hydrolox", "LOX and RP-1", "ion xenon as Merlin", "solid APCP as Merlin"], "LOX and RP-1", 2),
  q("Raptor engines burn…", ["RP-1 / LOX as Raptor", "methalox", "hypergolics as Raptor", "solid fuel"], "methalox", 2),
  q("RS-25 engines (SLS core / Shuttle main) burn…", ["RP-1", "hydrolox", "methane as RS-25", "solid"], "hydrolox", 3),
  q("SRBs are…", ["station robotic bases", "solid rocket boosters", "star-tracker boxes", "spacesuit backpacks"], "solid rocket boosters", 1),
  q("SLS is NASA's…", ["SpaceX's tanker", "Space Launch System", "a Cubesat class", "a rover"], "Space Launch System", 2),
  q("Orion is a…", ["SpaceX tanker", "NASA crew capsule for Artemis", "a rover of Mars of 2020s crew", "an ISS module of 1998 as Orion"], "NASA crew capsule for Artemis", 2),
  q("Dragon is a…", ["core stage of NASA's SLS rocket", "SpaceX capsule for cargo and crew", "Soviet space station of the 1970s", "Chinese rover on the Moon's far side"], "SpaceX capsule for cargo and crew", 1),
  q("Starliner is a…", ["SpaceX tanker ship", "Boeing crew capsule", "Chinese Mars rover", "solid rocket motor"], "Boeing crew capsule", 2),
  q("Soyuz is a…", ["retired NASA space shuttle", "long-running Russian crew vehicle", "deployer for small Cubesats", "European rover bound for Mars"], "long-running Russian crew vehicle", 1),
  q("The Apollo LM was the…", ["command module that stayed in lunar orbit", "lunar module that landed two astronauts", "Saturn V first stage", "a rover of 2021"], "lunar module that landed two astronauts", 1),
  q("The Saturn V was a…", ["two-stage Falcon", "three-stage Moon rocket", "solid ICBM of Minuteman", "capsule"], "three-stage Moon rocket", 1),
  q("A cleanroom for spacecraft is about…", ["noise control", "contamination control", "temperature boost", "light blocking"], "contamination control", 2),
  q("A TVAC test is…", ["a road test of a rover's wheels", "a space-like heat and vacuum test", "a pH test of the coolant loop", "a mass check of the spacecraft"], "a space-like heat and vacuum test", 2),
  q("Vibe testing a spacecraft uses a…", ["CMM", "shaker table to mimic launch", "optical flat", "deadweight tester of pressure"], "shaker table to mimic launch", 2),
  q("An anechoic chamber can test…", ["gauge block flatness", "antenna radiation patterns", "pH of rocket fuel", "mass of a payload"], "antenna radiation patterns", 3),
  q("MLI is…", ["a mission launch interface", "multi-layer insulation", "a methane-LOX ignition", "a mechanical lift interface"], "multi-layer insulation", 2),
  q("A reaction wheel stores…", ["propellant to point a spacecraft", "angular momentum to point a spacecraft", "electric charge for the solar arrays", "heat absorbed during reentry"], "angular momentum to point a spacecraft", 2),
  q("A control-moment gyro is a…", ["main engine of the Falcon 9", "high-torque attitude actuator", "heat shield for reentry", "docking hatch latch"], "high-torque attitude actuator", 3),
  q("Passivation of a spent stage is…", ["painting it gold to reflect sunlight", "venting leftover energy so it won't explode", "restarting it to boost it into GEO", "turning it into a crewed station"], "venting leftover energy so it won't explode", 3),
  q("Kessler syndrome is a…", ["type of staged-combustion rocket engine", "runaway collision cascade of orbital debris", "lunar dust storm seen during Apollo", "a slow leak in a spacesuit's seals"], "runaway collision cascade of orbital debris", 3),
  q("Space situational awareness tracks…", ["only weather of Earth", "satellites and debris", "only fish", "only tarantulas"], "satellites and debris", 2),
  q("A cubesat 1U is…", ["1 metre on a side", "10 × 10 × 10 cm", "1 km", "a Falcon fairing"], "10 × 10 × 10 cm", 2),
  q("Ion thrusters offer…", ["high thrust for liftoff", "high Isp but very low thrust", "thrust with no power needed", "low Isp but very high thrust"], "high Isp but very low thrust", 2),
  q("Hall thrusters are a type of…", ["solid rocket booster", "electric propulsion", "ablative heat shield", "drogue parachute"], "electric propulsion", 3),
  q("Xenon is a common…", ["solid grain", "ion-thruster propellant", "heat-shield tile", "spacesuit gas of 100%"], "ion-thruster propellant", 2),
  q("A RTG makes electricity from…", ["sunlight on thin solar panels", "heat of decaying plutonium-238", "a small diesel generator", "a fuel cell burning RP-1"], "heat of decaying plutonium-238", 2),
  q("Solar arrays do not help much…", ["in low Earth orbit", "in the outer solar system", "at 1 AU from the Sun", "on the ISS"], "in the outer solar system", 2),
  q("A sunshade on JWST keeps the telescope…", ["warm like a greenhouse", "cold in infrared", "spinning", "in LEO"], "cold in infrared", 1),
  q("Infrared telescopes need to be cold because…", ["infrared cannot be focused", "the telescope's own heat would swamp the sky", "CCDs cannot work cold as a rule of Hubble", "L2 is hot"], "the telescope's own heat would swamp the sky", 2),
  q("A clean FOD walkdown is about…", ["rainwater on the pad", "foreign-object debris", "radio interference", "mass calibration"], "foreign-object debris", 2),
  q("Torque-stripe / witness paint shows if a…", ["tank has fuel", "fastener has moved", "clock is right", "orbit is polar"], "fastener has moved", 2),
  q("A connector saver is a…", ["spare heat shield tile for the hatch", "wear item that spares flight connectors", "main engine igniter backup", "backup parachute for the capsule"], "wear item that spares flight connectors", 3),
  q("Red-tag / green-tag in aerospace config control marks…", ["mass class of each calibration weight", "items to remove or that are flight-ready", "pH of each propellant batch", "pages of the SI brochure to reread"], "items to remove or that are flight-ready", 3),
  q("A flight article is the…", ["poster of a vehicle, not a model", "vehicle meant to fly, not a mockup", "textbook article on flight", "test mockup, not a vehicle"], "vehicle meant to fly, not a mockup", 1),
  q("GSE is…", ["Goddard Space Exhibit", "ground support equipment", "gaseous staged engine", "geostationary survey"], "ground support equipment", 2),
  q("LOX loading on the pad is a…", ["room-temperature water fill as LOX", "cryogenic hazardous operation", "paint job", "software flash only"], "cryogenic hazardous operation", 1),
  q("A hold-down / release mechanism keeps a rocket…", ["in GEO until the payload deploys", "on the pad until thrust is healthy", "cold until the propellant loads", "radio silent until it clears the tower"], "on the pad until thrust is healthy", 2),
  q("A range safety system can…", ["only take photos", "destroy or halt a failing rocket", "only measure pH", "only cal a torque wrench"], "destroy or halt a failing rocket", 1),
  q("Telemetry is…", ["fuel sent from the ground to the vehicle", "data sent from the vehicle to the ground", "a heat shield on the vehicle's nose", "commands sent from the ground"], "data sent from the vehicle to the ground", 1),
  q("A transponder helps the range…", ["load LOX", "track the vehicle", "wring gauge blocks", "sex a tarantula"], "track the vehicle", 1),
  q("The Tsiolkovsky rocket equation assumes…", ["wings that generate lift", "no external forces acting", "a runway for takeoff", "constant air drag"], "no external forces acting", 3),
  q("Fairing recovery (when done) happens…", ["before liftoff, by crane", "after payload deploy, by ship", "on the Moon, by rover", "in GEO, by a tug"], "after payload deploy, by ship", 2),
  q("A rideshare launch carries…", ["one astronaut and no cargo", "many small payloads on one rocket", "cargo to the ISS and nothing else", "tanks of water for the crew"], "many small payloads on one rocket", 1),
  q("The Van Allen belts matter for…", ["fish in the upper ocean", "electronics and crew passing through", "gauge blocks on a granite plate", "pH of a liquid bath in a lab"], "electronics and crew passing through", 2),
  q("SEUs (single-event upsets) are…", ["engine outages of RP-1", "bit flips from radiation", "a kind of fairing", "a mass class"], "bit flips from radiation", 3),
  q("EDAC / TMR in avionics fights…", ["ice on the pad only", "radiation-induced errors", "pH drift", "gauge-block wring"], "radiation-induced errors", 3),
  q("A cleanroom class (ISO 14644) limits…", ["mass of E2 weights", "particles per volume", "seconds of exposure", "candela of lighting"], "particles per volume", 2),
  q("Outgassing in vacuum can…", ["help wring gauge blocks", "contaminate optics and sensors", "calibrate a deadweight tester", "sex a tarantula"], "contaminate optics and sensors", 2),
  q("Bakeout of hardware is to…", ["add oil", "drive off volatiles before flight", "paint it", "load RP-1 into an avionics box"], "drive off volatiles before flight", 2),
  q("A MLI blanket looks gold because of…", ["solid gold foil from a vault", "vapor-deposited metal on Kapton", "brass sheeting like a gauge block", "yellow school-bus paint"], "vapor-deposited metal on Kapton", 3),
  q("The dark side of a spacecraft can be…", ["always room temperature without design", "very cold; the Sun side very hot — hence thermal design", "always 20 °C like a metrology lab with no effort", "molten on both sides always"], "very cold; the Sun side very hot — hence thermal design", 1),
  q("Heat pipes move heat by…", ["conduction through a granite core", "evaporating and condensing a working fluid", "beaming radio waves to a radiator", "spinning a reaction wheel inside"], "evaporating and condensing a working fluid", 3),
  q("A louvre or variable-emittance device helps…", ["steer a booster as fins", "regulate radiator heat rejection", "measure pH", "wring blocks"], "regulate radiator heat rejection", 3),
  q("The solar constant at 1 AU is about…", ["1 W/m²", "1360 W/m²", "10 W/m²", "136 000 W/m²"], "1360 W/m²", 3),
  q("Albedo of a planet is the…", ["fraction of its mass in iron", "fraction of sunlight it reflects", "rate at which it spins", "strength of its magnetic field"], "fraction of sunlight it reflects", 2),
  q("A terminator orbit imaging pass is near the…", ["equator always", "day/night line", "Lagrange point", "core of the Earth"], "day/night line", 3),
  q("Ground sample distance in remote sensing is…", ["the SI metre's definition", "how large a pixel is on the Earth", "a mass of a rock", "a pH"], "how large a pixel is on the Earth", 2),
  q("Synthetic aperture radar can image…", ["only in sunlight like a phone camera as SAR's limit", "through clouds, day or night", "only under the sea as a camera", "only stars"], "through clouds, day or night", 2),
  q("A cubesat deployer (P-POD and kin) is a…", ["heat shield for small reentry pods", "spring-loaded box that ejects small sats", "main engine for small upper stages", "crew hatch on the Orion capsule"], "spring-loaded box that ejects small sats", 3),
  q("The tyranny of the rocket equation is that…", ["engines cannot gimbal in a vacuum", "fuel must lift fuel, so mass grows fast", "Isp is always exactly one second", "staging is banned by treaty"], "fuel must lift fuel, so mass grows fast", 2),
];

