import { q } from "../quiz";
import type { TriviaQ } from "../types";

/** Deep-cut science trivia cards (metrology, SI, launch hardware). v0.0.16 k16a. Wired via weekly_20260922. */
export const SCIENCE_LIFE_PART_A: TriviaQ[] = [
  q("The luminous efficacy constant K_cd that anchors the candela is exactly…", ["540 lm/W", "683 lm/W", "555 lm/W", "1000 lm/W"], "683 lm/W", 3),
  q("The caesium frequency ΔνCs that defines the SI second is exactly…", ["1 420 405 752 Hz", "6 834 682 611 Hz", "9 192 631 770 Hz", "32 768 Hz"], "9 192 631 770 Hz", 3),
  q("Since 2019 the Planck constant h is fixed at exactly…", ["6.626 070 15 × 10⁻³⁴ J·s", "6.674 30 × 10⁻³⁴ J·s", "1.054 571 817 × 10⁻³⁴ J·s", "6.022 140 76 × 10⁻³⁴ J·s"], "6.626 070 15 × 10⁻³⁴ J·s", 3),
  q("Since 2019 the Boltzmann constant k is fixed at exactly…", ["1.380 649 × 10⁻²³ J/K", "8.314 462 618 × 10⁻²³ J/K", "5.670 374 × 10⁻²³ J/K", "1.602 176 634 × 10⁻²³ J/K"], "1.380 649 × 10⁻²³ J/K", 3),
  q("Since 2019 the elementary charge e is fixed at exactly…", ["1.602 176 634 × 10⁻¹⁹ C", "1.660 539 × 10⁻¹⁹ C", "9.109 383 7 × 10⁻¹⁹ C", "1.380 649 × 10⁻¹⁹ C"], "1.602 176 634 × 10⁻¹⁹ C", 3),
  q("Since 2019 the Avogadro constant is fixed at exactly…", ["6.022 140 76 × 10²³ mol⁻¹", "6.022 140 76 × 10²⁶ mol⁻¹", "6.626 070 15 × 10²³ mol⁻¹", "9.648 533 × 10²³ mol⁻¹"], "6.022 140 76 × 10²³ mol⁻¹", 3),
  q("The treaty body of member states that votes on changes to the SI is the…", ["CIPM", "CGPM", "BIPM", "ILAC"], "CGPM", 3),
  q("The 2019 SI redefinition was adopted by the…", ["24th CGPM in 2011", "25th CGPM in 2014", "26th CGPM in 2018", "27th CGPM in 2022"], "26th CGPM in 2018", 3),
  q("The revised SI took effect on…", ["1 January 2019", "20 May 2019", "16 November 2018", "1 July 2020"], "20 May 2019", 3),
  q("World Metrology Day on 20 May marks the anniversary of the…", ["first caesium atomic clock", "signing of the Metre Convention", "founding of NIST", "retirement of the kilogram artifact"], "signing of the Metre Convention", 3),
  q("The Josephson constant K_J is defined as…", ["h/e²", "2e/h", "e/2h", "h/2e"], "2e/h", 3),
  q("The von Klitzing constant R_K, used with quantum Hall resistance standards, equals…", ["2e/h", "h/e²", "e²/h", "h/2e"], "h/e²", 3),
  q("Which ITS-90 fixed point sits at 29.7646 °C?", ["mercury triple point", "gallium melting point", "indium freezing point", "water triple point"], "gallium melting point", 3),
  q("The ITS-90 zinc freezing point is…", ["231.928 °C", "419.527 °C", "660.323 °C", "961.78 °C"], "419.527 °C", 3),
  q("From the triple point of hydrogen up to the silver point, ITS-90 is interpolated with…", ["thermocouples", "standard platinum resistance thermometers", "mercury-in-glass thermometers", "optical pyrometers"], "standard platinum resistance thermometers", 3),
  q("Above the silver point (961.78 °C), ITS-90 temperatures are defined by…", ["SPRTs", "Planck's radiation law (radiation thermometry)", "type K thermocouples", "constant-volume gas thermometers"], "Planck's radiation law (radiation thermometry)", 3),
  q("Gauge blocks ('Jo blocks') were invented by…", ["Joseph Whitworth", "Carl Edvard Johansson", "Henry Maudslay", "Ernst Abbe"], "Carl Edvard Johansson", 3),
  q("The international standard for length gauge blocks is…", ["ISO 9001", "ISO 3650", "ISO 14644", "ISO 286"], "ISO 3650", 3),
  q("The British Standard Whitworth thread has a flank angle of…", ["55°", "60°", "29°", "47.5°"], "55°", 3),
  q("ISO metric and Unified screw threads share a flank angle of…", ["55°", "60°", "29°", "30°"], "60°", 3),
  q("The Welch–Satterthwaite formula estimates…", ["the coverage probability of a CMM", "the effective degrees of freedom of a combined uncertainty", "the thermal expansion of steel", "gauge-block wringing force"], "the effective degrees of freedom of a combined uncertainty", 3),
  q("Propagating distributions by Monte Carlo simulation is covered by GUM…", ["Supplement 1 (JCGM 101)", "Annex J only", "JCGM 200 (the VIM)", "ISO 9001 clause 7.1.5"], "Supplement 1 (JCGM 101)", 3),
  q("JCGM 200 is the document number of the…", ["GUM", "VIM (International Vocabulary of Metrology)", "SI Brochure", "ISO/IEC 17025"], "VIM (International Vocabulary of Metrology)", 3),
  q("A rectangular distribution of half-width a has standard uncertainty…", ["a/2", "a/√3", "a/√6", "a√2"], "a/√3", 3),
  q("A triangular distribution of half-width a has standard uncertainty…", ["a/√3", "a/√6", "a/3", "a/2"], "a/√6", 3),
  q("Cleanroom class ISO 5 (ISO 14644-1) roughly matches old FED-STD-209E class…", ["1", "100", "10 000", "100 000"], "100", 3),
  q("How many F-1 engines powered the Saturn V first stage (S-IC)?", ["3", "5", "9", "30"], "5", 3),
  q("The Saturn V's F-1 engines burned…", ["liquid hydrogen and LOX", "RP-1 and LOX", "UDMH and N₂O₄", "solid APCP"], "RP-1 and LOX", 3),
  q("The Saturn V third stage (S-IVB) flew on a single…", ["F-1", "J-2", "RL10", "RS-25"], "J-2", 3),
  q("The Soviet N1 Moon rocket's first stage carried how many NK-15 engines?", ["5", "9", "30", "33"], "30", 3),
  q("A Super Heavy booster is built around how many Raptor engines?", ["9", "27", "30", "33"], "33", 3),
  q("Aerozine 50 is a 50:50 blend of hydrazine and…", ["kerosene", "UDMH", "nitrogen tetroxide", "hydrogen peroxide"], "UDMH", 3),
  q("SpaceX's Raptor uses which engine cycle?", ["gas generator", "full-flow staged combustion", "expander", "pressure-fed"], "full-flow staged combustion", 3),
  q("Merlin 1D uses which engine cycle?", ["gas generator", "full-flow staged combustion", "expander", "electric pump-fed"], "gas generator", 3),
  q("The RL10 upper-stage engine runs on which cycle?", ["gas generator", "staged combustion", "expander", "pressure-fed"], "expander", 3),
  q("A de Laval rocket nozzle is shaped…", ["straight-walled", "convergent–divergent", "divergent only", "convergent only"], "convergent–divergent", 3),
  q("In a de Laval nozzle, the flow reaches Mach 1 at the…", ["injector plate", "throat", "nozzle exit", "combustion chamber wall"], "throat", 3),
  q("Liquid oxygen boils at 1 atm at about…", ["−162 °C", "−183 °C", "−196 °C", "−253 °C"], "−183 °C", 3),
  q("Liquid hydrogen boils at 1 atm at about…", ["−183 °C", "−196 °C", "−253 °C", "−269 °C"], "−253 °C", 3),
  q("Sputnik 1 beeped on roughly…", ["20 and 40 MHz", "137 MHz", "1420 MHz", "2.4 GHz"], "20 and 40 MHz", 3),
  q("The oldest human-made object still in orbit is…", ["Sputnik 1", "Explorer 1", "Vanguard 1", "Telstar 1"], "Vanguard 1", 3),
  q("Explorer 1's cosmic-ray detector led to the discovery of the…", ["ozone hole", "Van Allen radiation belts", "solar wind", "cosmic microwave background"], "Van Allen radiation belts", 3),
  q("The Outer Space Treaty was opened for signature in…", ["1957", "1963", "1967", "1979"], "1967", 3),
  q("Retired geostationary satellites are boosted into a graveyard orbit…", ["a few hundred km above GEO", "a few hundred km below GEO", "down to 400 km LEO", "out to Sun–Earth L2"], "a few hundred km above GEO", 3),
  q("Apollo 11's '1202' program alarm meant the guidance computer was…", ["out of fuel data", "overloaded (executive overflow) but still running priority tasks", "off by one degree in pitch", "losing radio contact"], "overloaded (executive overflow) but still running priority tasks", 3),
  q("The Apollo Guidance Computer's fixed program was stored in…", ["floppy disks", "core rope memory", "magnetic tape", "EPROM chips"], "core rope memory", 3),
  q("The gal, a unit used in gravimetry, equals…", ["1 cm/s²", "1 m/s²", "9.81 m/s²", "1 mm/s²"], "1 cm/s²", 3),
  q("Since 1959 the international inch has been defined as exactly…", ["25 mm", "25.4 mm", "25.40005 mm", "2.54 mm"], "25.4 mm", 3),
  q("Since 1959 the international avoirdupois pound has been defined as exactly…", ["0.45359237 kg", "0.4536 kg", "0.5 kg", "0.4530 kg"], "0.45359237 kg", 3),
  q("NIST and NOAA deprecated the U.S. survey foot at the end of…", ["2000", "2012", "2022", "2025"], "2022", 3),
  q("The ITS-90 triple point of mercury is…", ["−38.8344 °C", "−56.558 °C", "0.01 °C", "−189.3442 °C"], "−38.8344 °C", 3),
  q("ITS-90's lowest defined temperature is…", ["0.65 K", "4.2 K", "13.8 K", "1 mK"], "0.65 K", 3),
  q("The Callendar–Van Dusen equation relates…", ["thermocouple voltage to temperature", "platinum RTD resistance to temperature", "gas pressure to temperature", "spectral radiance to temperature"], "platinum RTD resistance to temperature", 3),
  q("A Pt100 sensor has a resistance at 0 °C of…", ["10 Ω", "100 Ω", "1000 Ω", "138.5 Ω"], "100 Ω", 3),
  q("The IEC 60751 alpha coefficient for industrial platinum RTDs is about…", ["0.00385 /°C", "0.00500 /°C", "0.0043 /°C", "0.0068 /°C"], "0.00385 /°C", 3),
  q("A type J thermocouple pairs…", ["iron and constantan", "chromel and alumel", "copper and constantan", "nicrosil and nisil"], "iron and constantan", 3),
  q("The Seebeck effect is…", ["a voltage from a temperature difference across dissimilar conductors", "heating or cooling at a junction when current flows", "resistance change with strain", "light emitted under an electric field"], "a voltage from a temperature difference across dissimilar conductors", 3),
  q("The Space Shuttle's solid rocket boosters burned…", ["hydrolox", "APCP (ammonium perchlorate composite propellant)", "RP-1 and LOX", "hydrazine"], "APCP (ammonium perchlorate composite propellant)", 3),
  q("The Shuttle's orange external tank held…", ["RP-1 and LOX", "liquid hydrogen and liquid oxygen", "hypergolic propellants", "solid propellant"], "liquid hydrogen and liquid oxygen", 3),
  q("How many Merlin engines power a Falcon 9 first stage?", ["5", "7", "9", "27"], "9", 3),
  q("Voyager 1 crossed the heliopause into interstellar space in…", ["1998", "2004", "2012", "2018"], "2012", 3),
  q("Voyager 2 crossed the heliopause in…", ["2007", "2012", "2018", "2021"], "2018", 3),
  q("Pioneer 10 was the first spacecraft to…", ["land on Mars", "cross the asteroid belt and fly past Jupiter", "orbit Saturn", "cross the heliopause"], "cross the asteroid belt and fly past Jupiter", 3),
  q("Cassini ended its mission in 2017 by…", ["landing on Titan", "plunging into Saturn's atmosphere", "leaving for interstellar space", "crashing on Enceladus"], "plunging into Saturn's atmosphere", 3),
  q("The first spacecraft to orbit Mercury was…", ["Mariner 10", "MESSENGER", "BepiColombo", "Pioneer Venus"], "MESSENGER", 3),
  q("The first spacecraft to orbit an asteroid was…", ["NEAR Shoemaker", "Dawn", "Hayabusa", "OSIRIS-REx"], "NEAR Shoemaker", 3),
  q("NASA's Dawn orbited Vesta and then…", ["Ceres", "Eros", "Pallas", "Bennu"], "Ceres", 3),
];
