import { q } from "../quiz";
import type { TriviaQ } from "../types";

export const SCIENCE_LIFE: TriviaQ[] = [
  q("Metrology is the science of…", ["weather only", "measurement", "insects", "poetry"], "measurement", 1),
  q("The SI is the…", ["U.S. customary only", "International System of Units", "stock index", "medical code"], "International System of Units", 1),
  q("How many SI base units are there?", ["3", "5", "7", "10"], "7", 1),
  q("The SI base unit of length is the…", ["inch", "metre", "yard", "angstrom as the SI base"], "metre", 1),
  q("The SI base unit of mass is the…", ["gram as the base", "kilogram", "pound", "tonne as the base"], "kilogram", 1),
  q("The SI base unit of time is the…", ["minute", "second", "hour", "day"], "second", 1),
  q("The SI base unit of electric current is the…", ["volt", "ohm", "ampere", "watt"], "ampere", 1),
  q("The SI base unit of thermodynamic temperature is the…", ["celsius as the SI base", "kelvin", "fahrenheit", "rankine as SI"], "kelvin", 1),
  q("The SI base unit of amount of substance is the…", ["gram", "mole", "litre", "molecule as the unit name"], "mole", 1),
  q("The SI base unit of luminous intensity is the…", ["lumen as the base", "candela", "lux as the base", "watt"], "candela", 2),
  q("The BIPM, keeper of the SI, is in…", ["Gaithersburg", "Sèvres, France", "Teddington only as BIPM", "Berlin as BIPM"], "Sèvres, France", 2),
  q("NIST is the U.S.…", ["weather service", "national metrology institute", "patent court only", "census only"], "national metrology institute", 1),
  q("NPL is the national metrology institute of the…", ["France as this acronym", "United Kingdom", "Japan as this acronym", "Canada as this acronym"], "United Kingdom", 2),
  q("PTB is the national metrology institute of…", ["Italy", "Germany", "Spain", "Poland as this acronym"], "Germany", 2),
  q("NRC (metrology) is associated with…", ["Mexico as this lab's nation", "Canada", "Brazil as this acronym", "India as NRC-metrology's only home"], "Canada", 3),
  q("A national metrology institute realizes…", ["traffic laws", "measurement standards for a country", "sports records only", "postal codes"], "measurement standards for a country", 1),
  q("The Metre Convention dates to…", ["1776", "1875", "1945", "1960 as the treaty"], "1875", 3),
  q("CIPM stands for the…", ["International Olympic Committee", "International Committee for Weights and Measures", "a U.S. Army lab only", "a bank"], "International Committee for Weights and Measures", 3),
  q("The 2019 SI overhaul redefined the kilogram using the…", ["International Prototype Kilogram only still", "Planck constant", "a liter of water as the definition", "Earth's mass"], "Planck constant", 2),
  q("Since 2019 the kelvin is tied to the…", ["triple point of water as the only definition still", "Boltzmann constant", "body temperature", "absolute zero as a counted unit"], "Boltzmann constant", 2),
  q("Since 2019 the ampere is tied to the…", ["a mercury column", "elementary charge", "a wet cell of Volta as the definition", "Earth's field"], "elementary charge", 2),
  q("Since 2019 the mole is tied to the…", ["a gram of hydrogen as the definition", "Avogadro constant", "a litre of ideal gas at STP as the definition", "carbon-12's old 12-gram artifact only"], "Avogadro constant", 2),
  q("The metre is defined via the…", ["a metal bar in Paris as the current definition", "speed of light in vacuum", "Earth's equator", "a yardstick at NIST as the definition"], "speed of light in vacuum", 1),
  q("The second is defined via a…", ["pendulum in London as the definition", "caesium-133 hyperfine transition", "Earth year as the SI second", "quartz wristwatch"], "caesium-133 hyperfine transition", 2),
  q("The candela involves the luminous efficacy of radiation at…", ["the sodium D line only as the SI", "540 THz", "radio 1 MHz", "X-rays"], "540 THz", 3),
  q("The old kilogram artifact IPK was a…", ["iron cube", "platinum-iridium cylinder", "gold brick", "silicon sphere as IPK"], "platinum-iridium cylinder", 2),
  q("Kibble (watt) balances help realize the…", ["second as a pendulum", "kilogram", "candela", "mole as a counting cup"], "kilogram", 3),
  q("A silicon sphere project (Avogadro / XRCD) helped count atoms for the…", ["second", "mole / kilogram connection", "candela", "ampere as a wire count"], "mole / kilogram connection", 3),
  q("Traceability (VIM) is a property of a…", ["screwdriver", "measurement result, via an unbroken calibration chain with uncertainties", "brand of caliper only", "lab coat"], "measurement result, via an unbroken calibration chain with uncertainties", 2),
  q("A calibration compares an instrument to a…", ["random guess", "reference standard (and reports the relation, often with uncertainty)", "customer's opinion only", "color chart of paint only"], "reference standard (and reports the relation, often with uncertainty)", 1),
  q("Adjustment of an instrument is…", ["painting it", "changing it to agree better with a standard — not the same word as calibration", "throwing it away", "a legal seizure"], "changing it to agree better with a standard — not the same word as calibration", 2),
  q("Verification often checks whether an instrument is…", ["brand new", "within specified limits (pass/fail)", "painted red", "wireless"], "within specified limits (pass/fail)", 2),
  q("ISO/IEC 17025 is the standard for…", ["food menus", "competence of testing and calibration laboratories", "olympic timing only", "school grades"], "competence of testing and calibration laboratories", 2),
  q("Accreditation of a cal lab is typically to…", ["a city's parking code", "ISO/IEC 17025, by an accreditation body", "FIFA", "the Geneva Conventions as a lab rule"], "ISO/IEC 17025, by an accreditation body", 2),
  q("A CMC in the BIPM database is a…", ["car club", "calibration and measurement capability", "movie credit", "stock ticker"], "calibration and measurement capability", 3),
  q("The CIPM MRA lets NMIs…", ["share postage stamps", "mutually recognize certain calibration certificates", "set interest rates", "issue passports"], "mutually recognize certain calibration certificates", 3),
  q("The GUM is the…", ["U.S. Army field manual of rifles", "Guide to the Expression of Uncertainty in Measurement", "a cookbook", "a highway atlas"], "Guide to the Expression of Uncertainty in Measurement", 2),
  q("The VIM is the…", ["U.S. tax code", "International Vocabulary of Metrology", "a viscometer brand", "a virus index"], "International Vocabulary of Metrology", 2),
  q("A measurand is the…", ["person measuring", "quantity intended to be measured", "lab building", "brand of gauge"], "quantity intended to be measured", 2),
  q("Accuracy is closeness to the…", ["last digit's jitter only", "true / reference value", "room's paint color", "clock on the wall always"], "true / reference value", 1),
  q("Precision is about…", ["always being true", "scatter of repeated results (not automatically truth)", "the SI logo", "a sharp pencil only"], "scatter of repeated results (not automatically truth)", 1),
  q("Resolution is the…", ["true error always", "smallest change the instrument indicates", "mass of the instrument", "color"], "smallest change the instrument indicates", 1),
  q("Repeatability is under…", ["different labs always as this word", "the same conditions, short term", "a year later in another country as the definition", "a new operator, new method always"], "the same conditions, short term", 2),
  q("Reproducibility allows…", ["only the identical setup in one minute", "changed conditions (operator, lab, day…)", "no measurements", "only a single reading"], "changed conditions (operator, lab, day…)", 2),
  q("Type A uncertainty is evaluated by…", ["only a manufacturer's brochure as Type A", "statistical analysis of series of observations", "only a coin flip", "only weather"], "statistical analysis of series of observations", 2),
  q("Type B uncertainty is evaluated by…", ["only repeating a run 100 times as the definition", "means other than a Type A statistical series (specs, cal data, judgment…)", "only a vote", "only color"], "means other than a Type A statistical series (specs, cal data, judgment…)", 2),
  q("Standard uncertainty is often a…", ["range of the universe", "one-sigma (standard deviation) estimate", "percent of GDP", "letter grade"], "one-sigma (standard deviation) estimate", 2),
  q("Expanded uncertainty U is often…", ["the reading itself", "k × u, with k≈2 for ~95% (normal assumption)", "always zero", "the serial number"], "k × u, with k≈2 for ~95% (normal assumption)", 2),
  q("A coverage factor k = 2 commonly corresponds (normal) to about…", ["50%", "68%", "95%", "99.999% always"], "95%", 2),
  q("Degrees of freedom in uncertainty work affect the…", ["color of the sticker", "t-factor / coverage for small samples", "SI prefix only", "lab's zip code"], "t-factor / coverage for small samples", 3),
  q("A calibration certificate should include…", ["only a smiley sticker", "results, uncertainty, traceability, conditions, and identity of the item", "only a price", "only a logo"], "results, uncertainty, traceability, conditions, and identity of the item", 1),
  q("As-found data are…", ["after the next decade", "before adjustment", "the customer's guess", "the weather"], "before adjustment", 2),
  q("As-left data are…", ["before shipping from the factory always as this word", "after adjustment (or as found, if not adjusted)", "a lost certificate", "a draft"], "after adjustment (or as found, if not adjusted)", 2),
  q("A calibration interval is a…", ["random day", "scheduled time or usage between calibrations", "lunch break", "SI second as a synonym"], "scheduled time or usage between calibrations", 1),
  q("Drift is…", ["a fishing term only", "change of indication with time", "a type of screw", "a cloud"], "change of indication with time", 1),
  q("Hysteresis is…", ["a brand of caliper", "difference in indication depending on the direction of approach", "a unit of mass", "a type of laser color"], "difference in indication depending on the direction of approach", 2),
  q("Dead band / backlash can make an instrument…", ["faster than light", "insensitive to small reversals", "a primary standard always", "dimensionless"], "insensitive to small reversals", 2),
  q("Linearity error is departure from a…", ["circle of latitude", "straight-line relation", "sine of time only", "log of color"], "straight-line relation", 2),
  q("The reference temperature for dimensional cal in the SI shop is typically…", ["0 °C", "20 °C", "37 °C", "100 °C"], "20 °C", 1),
  q("A steel part longer than its 20 °C length when hot shows…", ["shrink fit of ice only", "thermal expansion", "time dilation of special relativity as the shop error", "magnetic hysteresis as the usual length change"], "thermal expansion", 1),
  q("CTE is the…", ["calibration test equipment as the only meaning", "coefficient of thermal expansion", "candela to energy", "coulomb thermal error"], "coefficient of thermal expansion", 2),
  q("A 1 °C error on a metre of steel (CTE ~11–12 ppm/K) is about…", ["1 metre", "11–12 micrometres", "1 millimetre on the nose always", "1 nanometre only"], "11–12 micrometres", 3),
  q("Gauge blocks (Jo blocks) are…", ["mass pieces of OIML M1 only", "precision length artifacts that can be wrung together", "electrical resistors", "optical filters of color"], "precision length artifacts that can be wrung together", 1),
  q("Wringing gauge blocks uses…", ["welding", "flatness, film, and molecular attraction — not glue as the main story", "thread locker", "solder"], "flatness, film, and molecular attraction — not glue as the main story", 2),
  q("Grade K / 00 gauge blocks are typically for…", ["tape measures on a jobsite as the usual grade", "interferometric / primary lab use", "kitchen spoons", "school rulers"], "interferometric / primary lab use", 3),
  q("Mechanical comparison of gauge blocks uses a…", ["bathroom scale", "high-resolution comparator / probe against a master", "kitchen timer", "compass"], "high-resolution comparator / probe against a master", 2),
  q("Interferometric calibration of gauge blocks uses…", ["a cloth tape", "light wavelength as the length scale", "a kitchen scale", "a stopwatch"], "light wavelength as the length scale", 2),
  q("A helium-neon laser's vacuum wavelength is a classic…", ["mass standard", "length standard in the lab (stabilized lasers)", "candela source of the SI base", "mole counter"], "length standard in the lab (stabilized lasers)", 3),
  q("Air wavelength of a laser depends on…", ["only the color of the walls", "temperature, pressure, and humidity (Edlén-type corrections)", "the operator's height", "the day of the week only"], "temperature, pressure, and humidity (Edlén-type corrections)", 3),
  q("An optical flat tests…", ["mass", "flatness by interference fringes", "pH", "radioactivity"], "flatness by interference fringes", 2),
  q("Newton's rings are an…", ["atomic nucleus", "interference pattern", "gear tooth", "thread class"], "interference pattern", 2),
  q("A surface plate is often…", ["rubber foam", "granite, for a reference plane", "cloth", "ice"], "granite, for a reference plane", 1),
  q("A height gauge sits on a…", ["pillow", "surface plate", "boat", "cloud"], "surface plate", 1),
  q("A micrometer typically resolves…", ["1 inch as the usual resolution", "0.01 mm or 0.001 mm (model-dependent), far finer than a tape", "1 metre", "1 kilometre"], "0.01 mm or 0.001 mm (model-dependent), far finer than a tape", 2),
  q("A caliper (vernier/dial/digital) is for…", ["only temperature", "outside, inside, and often depth lengths", "only pH", "only mass"], "outside, inside, and often depth lengths", 1),
  q("Parallax error happens when you…", ["use the wrong SI prefix", "read a scale off-axis", "calibrate too often", "ground a shield"], "read a scale off-axis", 1),
  q("Abbe error is a…", ["chemical contamination", "cosine / offset error when the scale is not in line with the measurand", "a type of laser", "a mass class"], "cosine / offset error when the scale is not in line with the measurand", 3),
  q("Cosine error in a length setup is from…", ["using kelvin", "the instrument axis not along the true length", "too much coffee", "the SI logo"], "the instrument axis not along the true length", 2),
  q("A CMM is a…", ["centrifugal mass meter as the usual shop word", "coordinate measuring machine", "coulomb multiplier", "camera of the Moon only"], "coordinate measuring machine", 2),
  q("CMM probes can be…", ["only kitchen spoons", "touch-trigger, scanning, or optical (among types)", "only Geiger tubes", "only pH bulbs"], "touch-trigger, scanning, or optical (among types)", 2),
  q("A laser tracker measures…", ["pH", "3-D position with a tracking interferometer / ADM", "blood type", "wind only"], "3-D position with a tracking interferometer / ADM", 3),
  q("An autocollimator measures small…", ["masses of trucks", "angular deviations of a mirror", "pH", "radioactivity"], "angular deviations of a mirror", 3),
  q("A theodolite / total station is for…", ["only mass", "angles (and distances, in a total station)", "only pH", "only candela"], "angles (and distances, in a total station)", 2),
  q("GD&T flatness, straightness, roundness are…", ["SI base units", "form tolerances", "mass classes", "thread pitches of UN only"], "form tolerances", 2),
  q("Roundness can be measured on a…", ["bathroom scale", "roundness tester / Talyrond-type spindle", "kitchen timer", "Geiger counter"], "roundness tester / Talyrond-type spindle", 3),
  q("Surface roughness parameters include…", ["pH and pKa", "Ra, Rz (among others)", "F1 and E2 as roughness", "k and u as the only texture names"], "Ra, Rz (among others)", 3),
  q("A dial indicator amplifies…", ["mass into candela", "small displacements", "time into moles", "color into volts"], "small displacements", 1),
  q("An LVDT is a…", ["mass piece", "linear variable differential transformer (displacement sensor)", "optical flat", "deadweight tester"], "linear variable differential transformer (displacement sensor)", 3),
  q("A load cell measures…", ["only time", "force (via strain, typically)", "only pH", "only candela"], "force (via strain, typically)", 1),
  q("Force's SI unit is the…", ["kilogram as force", "newton", "pound as SI", "dyne as SI"], "newton", 1),
  q("A deadweight tester for pressure uses…", ["a rubber balloon only", "known masses on a piston of known area", "a kitchen clock", "a compass"], "known masses on a piston of known area", 2),
  q("Pressure's SI unit is the…", ["bar as the SI base", "pascal (N/m²)", "torr as SI base", "psi as SI"], "pascal (N/m²)", 1),
  q("Gauge pressure is relative to…", ["absolute zero pressure always", "ambient atmosphere", "the triple point of water", "a vacuum of space as the only zero"], "ambient atmosphere", 2),
  q("Absolute pressure is relative to…", ["the shop's floor", "vacuum (zero pressure)", "sea-level standard only as a must of the word", "gauge of a tire as the zero"], "vacuum (zero pressure)", 2),
  q("A torque wrench is calibrated with a…", ["stopwatch", "known moment (arm × force) or a torque transducer", "pH buffer", "optical flat"], "known moment (arm × force) or a torque transducer", 2),
  q("Torque's SI unit is the…", ["joule as a synonym used for torque wrenches as the name of the unit on the handle always", "newton-metre", "watt", "pascal"], "newton-metre", 2),
  q("OIML weight classes include…", ["only A, B, C of batteries", "E1, E2, F1, F2, M1…", "only SAE grades of bolts as the mass code", "letter grades of school"], "E1, E2, F1, F2, M1…", 3),
  q("E2 masses are for…", ["ballast of a ship as the usual class", "high-accuracy calibration work, not shop floor gravel", "kitchen diet scales of ±50 g as the design class", "sandbags"], "high-accuracy calibration work, not shop floor gravel", 3),
  q("Mass calibration needs…", ["a gusty loading dock as ideal", "a stable, draft-free balance and handling with tweezers / gloves", "a magnet on every piece", "oil on the hands"], "a stable, draft-free balance and handling with tweezers / gloves", 1),
  q("Buoyancy correction in mass work accounts for…", ["the Moon's gravity only", "air density acting on volumes", "color of the weight", "the serial number"], "air density acting on volumes", 3),
  q("An SPRT is a…", ["spring scale", "standard platinum resistance thermometer", "surface plate", "gauge block"], "standard platinum resistance thermometer", 2),
  q("ITS-90 is the…", ["a thread standard", "International Temperature Scale of 1990", "a mass class", "an ISO of coffee"], "International Temperature Scale of 1990", 2),
  q("The triple point of water is a…", ["boiling point at 1 atm", "fixed point (0.01 °C) used in thermometry", "room temperature", "body temperature"], "fixed point (0.01 °C) used in thermometry", 2),
  q("A thermocouple measures temperature via a…", ["change of mass", "voltage from a junction of dissimilar metals", "pH", "radioactivity"], "voltage from a junction of dissimilar metals", 2),
  q("Type K thermocouples are…", ["pure platinum only", "chromel–alumel, general purpose", "only tungsten of vacuum furnaces as Type K", "only gold–gold"], "chromel–alumel, general purpose", 3),
  q("Type S/R/B thermocouples are…", ["base-metal of HVAC only", "noble-metal, high temperature", "only Type T of food", "only infrared"], "noble-metal, high temperature", 3),
  q("An RTD's resistance…", ["is independent of temperature", "rises with temperature (typical metals)", "is a pH", "counts moles"], "rises with temperature (typical metals)", 2),
  q("A 4-wire RTD connection is used to…", ["heat the part", "cancel lead resistance", "add extra uncertainty on purpose", "measure candela"], "cancel lead resistance", 2),
  q("Cold-junction compensation is needed for…", ["gauge blocks", "thermocouples", "surface plates", "E2 masses"], "thermocouples", 2),
  q("A dry-well / block calibrator is for…", ["gauge blocks of length as the usual block", "temperature sensors", "optical flats", "masses"], "temperature sensors", 2),
  q("A stirred liquid bath is a…", ["mass comparator", "uniform temperature medium for probes", "laser interferometer", "CMM"], "uniform temperature medium for probes", 2),
  q("Humidity can be generated for cal with a…", ["gauge block stack", "two-pressure or two-temperature generator, or salt solutions (among methods)", "optical flat", "deadweight on a CMM"], "two-pressure or two-temperature generator, or salt solutions (among methods)", 3),
  q("Dew point is the temperature at which…", ["steel melts", "air becomes saturated", "the SI second ticks", "a laser mode-locks"], "air becomes saturated", 2),
  q("RH is…", ["roughness height as this acronym in a cal lab's RH chart of the room", "relative humidity (how close to saturation)", "a mass class", "a thread"], "relative humidity (how close to saturation)", 1),
  q("A hygrometer measures…", ["mass", "humidity", "length of gauge blocks as the usual tool", "candela"], "humidity", 1),
  q("Electrical cal uses standards of…", ["only granite", "voltage, resistance, current, time/frequency (among others)", "only coco fiber", "only granite and silk"], "voltage, resistance, current, time/frequency (among others)", 1),
  q("A Josephson junction array can realize a…", ["metre stick", "volt", "candela", "mole of water"], "volt", 3),
  q("A quantum Hall device can realize a…", ["second", "ohm (resistance)", "candela", "kelvin as a resistor of ice"], "ohm (resistance)", 3),
  q("A DMM is a…", ["dimensional mass machine as the shop's usual DMM", "digital multimeter", "dew-mass meter", "dial mass micrometer"], "digital multimeter", 1),
  q("A scope (oscilloscope) displays…", ["mass versus kelvin only", "voltage versus time (typically)", "only pH", "only candela"], "voltage versus time (typically)", 1),
  q("Frequency is traced to…", ["a drum", "atomic clocks / the SI second", "a granite plate", "a gauge block of 100 mm always"], "atomic clocks / the SI second", 2),
  q("A GPS-disciplined oscillator is a…", ["mass standard", "field frequency / time reference", "optical flat", "pH buffer"], "field frequency / time reference", 3),
  q("The SI prefix micro (µ) means…", ["10⁻³", "10⁻⁶", "10⁻⁹", "10⁻²"], "10⁻⁶", 1),
  q("The SI prefix nano means…", ["10⁻⁶", "10⁻⁹", "10⁻¹²", "10⁻³"], "10⁻⁹", 1),
  q("The SI prefix pico means…", ["10⁻⁶", "10⁻⁹", "10⁻¹²", "10⁻¹⁵"], "10⁻¹²", 2),
  q("The SI prefix milli means…", ["10⁻⁶", "10⁻³", "10⁻²", "10⁻⁹"], "10⁻³", 1),
  q("The SI prefix kilo means…", ["10²", "10³", "10⁶", "10⁻³"], "10³", 1),
  q("The SI prefix mega means…", ["10³", "10⁶", "10⁹", "10²"], "10⁶", 1),
  q("The SI prefix giga means…", ["10⁶", "10⁹", "10¹²", "10³"], "10⁹", 1),
  q("A micrometre is also called a…", ["mile", "micron (informally)", "furlong", "fathom as a synonym"], "micron (informally)", 2),
  q("1 inch is exactly…", ["25 mm", "25.4 mm", "30 mm", "20 mm"], "25.4 mm", 1),
  q("Fiducial temperature 20 °C is 293.15…", ["fahrenheit", "kelvin", "rankine as SI", "celsius as the kelvin number"], "kelvin", 2),
  q("A reference standard should be…", ["less accurate on purpose", "more accurate than the unit under test (rule of thumb: 4:1 TUR, among policies)", "untraceable", "unlabeled"], "more accurate than the unit under test (rule of thumb: 4:1 TUR, among policies)", 2),
  q("TUR is the…", ["thermal under room", "test uncertainty ratio", "torque unit of radians", "type-unknown reading"], "test uncertainty ratio", 3),
  q("A 4:1 TUR means the standard's uncertainty is about…", ["four times worse than the UUT", "¼ of the UUT tolerance (in the simple ratio)", "equal to the UUT", "unrelated"], "¼ of the UUT tolerance (in the simple ratio)", 3),
  q("Measurement assurance is…", ["a one-time sticker", "ongoing checks that the cal system stays in control (check standards, charts…)", "painting the lab", "a coffee fund"], "ongoing checks that the cal system stays in control (check standards, charts…)", 2),
  q("A check standard is run to…", ["replace SI", "watch for drift of the process", "set the room color", "name the lab"], "watch for drift of the process", 2),
  q("Control charts in a cal lab plot…", ["employee birthdays only", "check-standard results over time", "stock prices", "the weather of Mars only"], "check-standard results over time", 2),
  q("Out-of-tolerance as-found may trigger…", ["a holiday", "impact analysis of product measured since last cal", "renaming the SI", "a new BIPM"], "impact analysis of product measured since last cal", 2),
  q("A limited cal might…", ["erase the serial number", "cover only part of the range", "void ISO forever", "change the SI"], "cover only part of the range", 2),
  q("A fixture error can dominate if you…", ["use kelvin", "clamp or locate the part poorly", "write the certificate", "wear gloves on masses"], "clamp or locate the part poorly", 1),
  q("Dirt on a gauge block will…", ["improve accuracy always", "ruin wring and add length", "change the SI second", "calibrate a thermocouple"], "ruin wring and add length", 1),
  q("Hand heat on a micrometer frame can…", ["cool it to absolute zero", "expand it and bias the reading", "change mass class", "fix hysteresis of a load cell"], "expand it and bias the reading", 2),
  q("Let parts soak so they reach…", ["boiling", "thermal equilibrium with the lab", "absolute zero", "the temperature of a welding arc"], "thermal equilibrium with the lab", 1),
  q("A metrology lab's environment is controlled for…", ["only loud music", "temperature (and often humidity, vibration, cleanliness)", "only the color of chairs", "only the brand of coffee"], "temperature (and often humidity, vibration, cleanliness)", 1),
  q("Vibration isolation helps…", ["hammers", "balances, interferometers, and roundness spindles", "sledge work", "forklifts"], "balances, interferometers, and roundness spindles", 2),
  q("Cleanliness in a dimensional lab prevents…", ["traceability", "particles from becoming 'length'", "the SI logo", "accreditation paperwork"], "particles from becoming 'length'", 2),
  q("A master (lab standard) is calibrated…", ["never", "more rarely, at a higher-level lab", "by a coin flip", "against the UUT"], "more rarely, at a higher-level lab", 1),
  q("Working standards are calibrated against…", ["the customer's guess", "reference / master standards", "a newspaper", "Wikipedia as the artifact"], "reference / master standards", 1),
  q("Field standards are…", ["BIPM artifacts stored in Sèvres only", "used on the floor or in the field, cal'd more often", "untraceable by definition", "always E1 kilograms"], "used on the floor or in the field, cal'd more often", 2),
  q("An intrinsic standard (like a Josephson array) realizes a unit from…", ["a dusty artifact of unknown origin only", "a physical constant / quantum effect", "a vote", "a brand name"], "a physical constant / quantum effect", 3),
  q("The metre used to be a…", ["cup of water", "prototype bar, then krypton wavelength, now c", "pendulum of London only still", "yard of Henry I still as SI"], "prototype bar, then krypton wavelength, now c", 3),
  q("The second used to be a fraction of the…", ["inch", "mean solar day, then ephemeris, now caesium", "metre", "candela"], "mean solar day, then ephemeris, now caesium", 3),
  q("UTC is…", ["a torque class", "Coordinated Universal Time", "a mass standard", "a CMM brand"], "Coordinated Universal Time", 1),
  q("Leap seconds (when used) keep UTC near…", ["the Planck constant", "Earth rotation / UT1", "the candela", "a gauge block"], "Earth rotation / UT1", 3),
  q("A primary standard of a quantity is…", ["the cheapest tape", "highest quality in a given chain, realizing the unit", "a rusty ruler", "a bathroom scale"], "highest quality in a given chain, realizing the unit", 2),
  q("A secondary standard is calibrated against a…", ["guess", "primary (or higher) standard", "coin", "calendar"], "primary (or higher) standard", 2),
  q("Metrological confirmation (ISO 10012) is…", ["a wedding", "ensuring measuring equipment is fit for the quality requirements", "a tax filing", "a sports win"], "ensuring measuring equipment is fit for the quality requirements", 3),
  q("MSA in quality talk is…", ["mass-standard artifact as the only meaning", "measurement system analysis (gage R&R, bias, linearity…)", "a NASA booster", "a fish"], "measurement system analysis (gage R&R, bias, linearity…)", 2),
  q("Gage R&R studies the…", ["recipe of a restaurant", "repeatability and reproducibility of a measuring system", "orbit of the Moon", "pH of the ocean only"], "repeatability and reproducibility of a measuring system", 2),
  q("Bias in MSA is…", ["random jitter only as this word", "systematic offset from a reference", "the serial number", "the lab's name"], "systematic offset from a reference", 2),
  q("A gold-plating micrometer anvil is still…", ["a primary realization of the metre", "subject to wear, dirt, and cal", "untraceable by law", "a mass standard"], "subject to wear, dirt, and cal", 1),
  q("Never drop a gauge block because…", ["it improves wring", "a ding is a length error (and a wring killer)", "NIST requires drops", "steel likes shocks"], "a ding is a length error (and a wring killer)", 1),
  q("Deburr and clean before…", ["throwing the certificate out", "precision measurement", "the coffee run as the only prep", "painting the CMM"], "precision measurement", 1),
  q("A '10:1' shop rule of thumb means the gage should resolve about…", ["ten times the tolerance as resolution", "a tenth of the tolerance (simple version)", "the same as the tolerance", "nothing"], "a tenth of the tolerance (simple version)", 2),
  q("Calliper jaws must be…", ["bent on purpose", "aligned and not over-forced", "magnetic on steel always as a must", "hot"], "aligned and not over-forced", 1),
  q("A thread mic has…", ["only flat faces of a length bar", "anvils shaped for pitch diameter", "a pH probe", "a Geiger tube"], "anvils shaped for pitch diameter", 3),
  q("Pitch diameter is a…", ["mass", "thread size, not the major diameter only", "candela", "second"], "thread size, not the major diameter only", 2),
  q("A sine bar measures…", ["mass", "angles via a stack of blocks and a known length", "pH", "radioactivity"], "angles via a stack of blocks and a known length", 3),
  q("A granite square checks…", ["mass class", "right angles / squareness", "dew point", "the SI mole"], "right angles / squareness", 2),
  q("Parallelism of a part can be checked with a…", ["pH meter", "indicator on a plate, or a CMM", "Geiger counter", "candela photometer only"], "indicator on a plate, or a CMM", 2),
  q("A bore gauge measures…", ["mass", "inside diameter", "candela", "seconds"], "inside diameter", 1),
  q("An air gage uses…", ["a kitchen fan", "back-pressure of a nozzle to sense small gaps", "a thermocouple only", "a Geiger tube"], "back-pressure of a nozzle to sense small gaps", 3),
  q("Optical comparators project a…", ["mass reading", "magnified shadow / image of a profile", "pH", "radio spectrum"], "magnified shadow / image of a profile", 2),
  q("A laser interferometer can calibrate a…", ["pH electrode as the usual job", "machine-tool axis or CMM scale", "kitchen scale of ±1 g as the usual job", "wall clock of a kitchen"], "machine-tool axis or CMM scale", 2),
  q("Volumetric CMM compensation maps…", ["the weather of the county", "geometric errors in the measuring volume", "employee hours", "stock prices"], "geometric errors in the measuring volume", 3),
  q("21 parametric errors of a Cartesian CMM include…", ["only color", "position, straightness, pitch, yaw, roll, squareness…", "only pH", "only mass"], "position, straightness, pitch, yaw, roll, squareness…", 3),
  q("A step gauge is a…", ["pH buffer series", "length artifact with many faces for CMM checks", "mass set of E2 only", "thermocouple"], "length artifact with many faces for CMM checks", 3),
  q("A ball bar (on a CMM or machine) checks…", ["pH", "dynamic / volumetric circularity errors", "candela", "the SI mole"], "dynamic / volumetric circularity errors", 3),
  q("Kinematic coupling locates a fixture with…", ["glue only", "a determinate set of contacts (e.g. three vees)", "a random pile", "a magnet of unknown force only"], "a determinate set of contacts (e.g. three vees)", 3),
  q("The SI brochure is published by the…", ["FIFA", "BIPM", "NATO", "the IOC"], "BIPM", 2),
  q("A newton is…", ["kg only", "kg·m/s²", "m/s", "A·s"], "kg·m/s²", 2),
  q("A joule is…", ["a torque wrench's only SI name used on food labels", "N·m (energy)", "a candela", "a mole"], "N·m (energy)", 2),
  q("A watt is…", ["a mass", "J/s (power)", "a length", "a mole"], "J/s (power)", 1),
  q("A pascal is…", ["kg", "N/m²", "s", "cd"], "N/m²", 2),
  q("A volt is…", ["a mass", "W/A (or J/C)", "a kelvin as a synonym", "a mole"], "W/A (or J/C)", 2),
  q("An ohm is…", ["a candela", "V/A", "a second", "a metre"], "V/A", 1),
  q("A hertz is…", ["a kg", "s⁻¹", "a mole", "a candela"], "s⁻¹", 1),
  q("A coulomb is…", ["a kelvin", "A·s", "a metre", "a candela"], "A·s", 2),
  q("A farad is…", ["a mass class", "C/V (capacitance)", "a gauge block grade", "a thread"], "C/V (capacitance)", 3),
  q("A henry is…", ["a length", "V·s/A (inductance)", "a candela", "a mole"], "V·s/A (inductance)", 3),
  q("A tesla is…", ["a temperature", "Wb/m² (magnetic flux density)", "a mass", "a time"], "Wb/m² (magnetic flux density)", 3),
  q("The litre is a…", ["SI base unit", "non-SI unit accepted for use with SI (1 L = 10⁻³ m³)", "mass class", "thread"], "non-SI unit accepted for use with SI (1 L = 10⁻³ m³)", 2),
  q("The tonne (t) is…", ["an SI base", "10³ kg, accepted with SI", "a candela", "a second"], "10³ kg, accepted with SI", 2),
  q("The electronvolt is…", ["an SI base unit", "accepted with SI for energy in physics", "a mass of E2", "a gauge block"], "accepted with SI for energy in physics", 2),
  q("A light-year is a unit of…", ["time only", "distance, not time", "mass", "candela"], "distance, not time", 1),
  q("An ångström is…", ["an SI base", "10⁻¹⁰ m", "a second", "a candela"], "10⁻¹⁰ m", 3),
  q("NASA stands for the…", ["North American Soccer Association as the space agency", "National Aeronautics and Space Administration", "National Atomic Standards Agency", "Navy Air-Sea Arm"], "National Aeronautics and Space Administration", 1),
  q("ESA is the…", ["Egyptian Survey Authority as this space body", "European Space Agency", "Earth Science Alliance only", "a NASA center in Texas as this acronym"], "European Space Agency", 1),
  q("JAXA is the space agency of…", ["China as this acronym", "Japan", "India as this acronym", "South Korea as JAXA"], "Japan", 2),
  q("CNSA is the space agency of…", ["Canada", "China", "Chile", "Czechia"], "China", 2),
  q("ISRO is the space agency of…", ["Indonesia", "India", "Iran as this acronym", "Ireland"], "India", 2),
  q("Roscosmos is the space agency of…", ["Romania", "Russia", "Rwanda", "Serbia"], "Russia", 1),
  q("CSA (space) is the…", ["Chinese Space Administration as this English short", "Canadian Space Agency", "California Space Agency", "Chilean Space Agency as CSA"], "Canadian Space Agency", 2),
  q("The Kármán line, a common space boundary, is at…", ["10 km", "50 km", "100 km", "400 km as this line"], "100 km", 2),
  q("LEO is…", ["lunar escape orbit as the usual NASA LEO", "low Earth orbit", "long elliptical ocean", "lagrange earth-outer"], "low Earth orbit", 1),
  q("GEO (geostationary) altitude is about…", ["400 km", "2000 km", "36 000 km", "1 AU"], "36 000 km", 2),
  q("A geostationary satellite hangs over…", ["a pole with a 90-minute period", "the equator, period one sidereal day", "the Moon", "Mars"], "the equator, period one sidereal day", 2),
  q("The ISS orbits in…", ["GEO", "low Earth orbit", "around the Moon as its home", "around L2 as the station"], "low Earth orbit", 1),
  q("The ISS flies about…", ["36 000 km up", "400 km up, ~90 minutes per rev", "on the lunar surface", "in GEO over Texas"], "400 km up, ~90 minutes per rev", 2),
  q("Microgravity on a station is mostly…", ["because Earth has no pull at 400 km", "free-fall, not the absence of Earth's gravity", "because mass is zero", "because time stops"], "free-fall, not the absence of Earth's gravity", 2),
  q("Delta-v is a…", ["type of airplane wing only", "measure of the impulse needed to change velocity", "unit of mass", "NASA center"], "measure of the impulse needed to change velocity", 2),
  q("Specific impulse (Isp) measures…", ["crew size", "how efficiently a rocket uses propellant", "paint thickness", "the SI mole of the vehicle"], "how efficiently a rocket uses propellant", 2),
  q("A higher Isp means…", ["a heavier tank always as the definition", "more impulse per mass of propellant", "worse efficiency", "a shorter nozzle always"], "more impulse per mass of propellant", 2),
  q("Chemical rockets throw mass; the Tsiolkovsky equation relates…", ["only wing lift", "delta-v to mass ratio and exhaust speed", "only radio gain", "only battery watt-hours of a phone"], "delta-v to mass ratio and exhaust speed", 3),
  q("LOX is…", ["liquid ozone as the usual rocket name", "liquid oxygen", "low-orbit xenon", "a lithium oxide pellet"], "liquid oxygen", 1),
  q("RP-1 is a…", ["solid rubber", "refined kerosene rocket fuel", "a hydrazine blend only as RP-1", "liquid hydrogen"], "refined kerosene rocket fuel", 2),
  q("Methalox is…", ["solid sugar + air", "liquid methane + liquid oxygen", "hydrazine only", "xenon only"], "liquid methane + liquid oxygen", 2),
  q("Hydrolox is…", ["kerosene + air", "liquid hydrogen + liquid oxygen", "methane + nitrogen", "solid APCP only"], "liquid hydrogen + liquid oxygen", 2),
  q("Hypergolic propellants…", ["need a spark plug of a car always", "ignite on contact", "are always cryogenic hydrolox", "are solid only"], "ignite on contact", 2),
  q("A solid rocket motor's grain is the…", ["crew cabin", "shaped solid propellant", "radio dish", "landing leg"], "shaped solid propellant", 2),
  q("Staging a rocket drops…", ["the payload always at liftoff", "empty tanks/engines to raise mass ratio", "the crew as a rule of staging", "the guidance computer always"], "empty tanks/engines to raise mass ratio", 1),
  q("Max-Q is the…", ["maximum crew size", "peak dynamic pressure on ascent", "minimum orbit", "max Isp on the pad"], "peak dynamic pressure on ascent", 3),
  q("MECO is…", ["a NASA center in Alabama as this acronym's only meaning", "main-engine cutoff", "a meteorite", "a spacesuit"], "main-engine cutoff", 2),
  q("SECO is…", ["a salad", "second-engine (or second-stage) cutoff, in some timelines", "a moon", "a wrench"], "second-engine (or second-stage) cutoff, in some timelines", 3),
  q("A payload fairing is the…", ["landing pad", "nose shroud that protects the cargo at ascent", "crew gym", "radio isotope"], "nose shroud that protects the cargo at ascent", 1),
  q("RCS thrusters provide…", ["main liftoff thrust of a Falcon first stage as RCS", "small attitude/translation control", "life support oxygen as the only job", "landing legs"], "small attitude/translation control", 2),
  q("An IMU is an…", ["international moon unit", "inertial measurement unit (gyros/accels)", "a hatch", "a wrench"], "inertial measurement unit (gyros/accels)", 2),
  q("A star tracker finds…", ["mass of the vehicle", "attitude from star fields", "pH of coolant", "the SI second as a sundial"], "attitude from star fields", 2),
  q("A heat shield on reentry is often…", ["a paper blanket", "ablative or tiled / ceramic", "open steel only", "ice"], "ablative or tiled / ceramic", 1),
  q("Reentry plasma can…", ["cool the vehicle below freezing as the main effect", "block radio ('blackout') and heat the shield", "add oxygen", "create a swim bladder"], "block radio ('blackout') and heat the shield", 2),
  q("Escape velocity from Earth's surface is about…", ["1 km/s", "7.8 km/s as escape (that's LEO speed)", "11 km/s", "30 km/s as Earth's escape"], "11 km/s", 2),
  q("LEO orbital speed is about…", ["1 km/s", "7.8 km/s", "11 km/s as circular LEO", "30 km/s"], "7.8 km/s", 2),
  q("The Oberth effect says a burn is more efficient when…", ["you are at rest on a pad as the most efficient place", "you are already going fast / deep in a gravity well", "you use solid motors only", "you coast with RCS only"], "you are already going fast / deep in a gravity well", 3),
  q("A Hohmann transfer is a…", ["straight line at constant speed", "two-burn ellipse between circular orbits", "aerobrake only", "ion hover"], "two-burn ellipse between circular orbits", 3),
  q("Lagrange points are…", ["NASA HQs", "locations of balanced gravity/centrifugal force in a three-body setup", "craters of the Moon only", "booster landing zones of Texas only"], "locations of balanced gravity/centrifugal force in a three-body setup", 2),
  q("JWST orbits near…", ["LEO like Hubble", "Sun–Earth L2", "GEO over Africa", "the lunar surface"], "Sun–Earth L2", 2),
  q("Hubble orbits in…", ["L2", "low Earth orbit", "GEO", "a polar lunar orbit as its home"], "low Earth orbit", 1),
  q("JWST's mirror is…", ["a single glass Hubble copy in LEO", "segmented beryllium, gold-coated, and sunshaded", "liquid mercury on Earth", "an inflatable beach ball"], "segmented beryllium, gold-coated, and sunshaded", 2),
  q("Hubble was serviced by…", ["Falcon 9 as the service vehicle of the 1990s", "Space Shuttle astronauts", "Apollo as Hubble's ride", "Soyuz spacewalks of the 1990s as Hubble's program"], "Space Shuttle astronauts", 2),
  q("Voyager 1 is in…", ["LEO", "interstellar space (beyond the heliopause)", "GEO", "a garage in Pasadena"], "interstellar space (beyond the heliopause)", 2),
  q("Voyager's Golden Record is a…", ["heat shield", "message to whoever might find the probes", "main engine", "crew meal"], "message to whoever might find the probes", 1),
  q("Cassini orbited…", ["Jupiter as its long home", "Saturn", "Mars", "Pluto"], "Saturn", 1),
  q("New Horizons flew by…", ["only the Moon", "Pluto and then Arrokoth", "only Venus", "only Mercury"], "Pluto and then Arrokoth", 2),
  q("Juno orbits…", ["Saturn", "Jupiter", "Neptune", "Uranus"], "Jupiter", 2),
  q("Curiosity and Perseverance are…", ["Venus balloons", "NASA Mars rovers", "Saturn orbiters as this pair", "lunar hoppers of Apollo as this pair"], "NASA Mars rovers", 1),
  q("Ingenuity was a…", ["submarine of Europa", "helicopter on Mars", "crew capsule", "ion tug"], "helicopter on Mars", 1),
  q("Apollo 11 landed in…", ["1961", "1965", "1969", "1975"], "1969", 1),
  q("The first human in space was…", ["Alan Shepard as first orbital", "Yuri Gagarin (1961)", "John Glenn as first human", "Neil Armstrong as first in space"], "Yuri Gagarin (1961)", 1),
  q("The first American to orbit was…", ["Gagarin", "John Glenn", "Armstrong as first U.S. orbit", "Shepard as the first U.S. orbit"], "John Glenn", 2),
  q("Sputnik 1 launched in…", ["1945", "1957", "1961", "1969"], "1957", 1),
  q("Valentina Tereshkova was the first…", ["American in orbit", "woman in space", "moonwalker", "space tourist of 2021"], "woman in space", 2),
  q("Sally Ride was the first…", ["woman of any country in space", "American woman in space", "moonwalker", "ISS commander of 1961"], "American woman in space", 2),
  q("The first spacewalk was by…", ["Armstrong as the first EVA", "Alexei Leonov", "White as the world's first", "Gagarin as a walk"], "Alexei Leonov", 3),
  q("A CubeSat is a…", ["NASA's lunar lander of Apollo", "small satellite built in 10 cm units", "a booster stage of Falcon Heavy", "a spacesuit"], "small satellite built in 10 cm units", 2),
  q("Starlink is a…", ["GEO TV of the 1960s", "LEO broadband satellite constellation", "lunar GPS", "a Mars city"], "LEO broadband satellite constellation", 1),
  q("GPS satellites are in…", ["LEO like the ISS as the GPS home", "medium Earth orbit (not GEO)", "GEO as a hover over one city", "the Moon"], "medium Earth orbit (not GEO)", 2),
  q("A polar orbit is useful for…", ["hovering over one city like GEO", "Earth observing (whole globe under the ground track)", "always staying in Earth's shadow", "landing on Mars as the definition"], "Earth observing (whole globe under the ground track)", 2),
  q("Sun-synchronous orbits keep a…", ["crew gym schedule", "similar lighting time for imaging", "geostationary hover", "Lagrange sit as the definition of SSO"], "similar lighting time for imaging", 3),
  q("Van Allen belts are…", ["asteroid rings", "zones of trapped radiation around Earth", "Saturn's rings as Earth's", "aurora only of Jupiter"], "zones of trapped radiation around Earth", 2),
  q("A Hohmann transfer to Mars takes on the order of…", ["hours", "days as a typical Hohmann", "months (about 6–9 in the classic two-burn)", "centuries"], "months (about 6–9 in the classic two-burn)", 2),
  q("Communications delay to Mars is…", ["zero", "minutes (varies with distance), not instant", "years as light-time", "hours as the usual one-way light time"], "minutes (varies with distance), not instant", 2),
  q("A light-second is about…", ["300 km", "3000 km", "300 000 km", "1 AU"], "300 000 km", 2),
  q("1 AU is the…", ["Earth–Moon distance", "Earth–Sun mean distance (about 150 million km)", "LEO altitude", "GEO altitude"], "Earth–Sun mean distance (about 150 million km)", 1),
  q("A parabolic escape trajectory has eccentricity…", ["0", "0.5", "1", "2 as parabola"], "1", 3),
  q("A circular orbit has eccentricity…", ["1", "0", "2", "0.5 as the circle"], "0", 2),
  q("Payload mass fraction is…", ["always 90%", "payload divided by total mass", "Isp in seconds", "crew size"], "payload divided by total mass", 2),
  q("Mass ratio in the rocket equation is…", ["payload / fuel only as a synonym of Isp", "initial mass / final mass", "thrust / weight of Earth always", "crew / cargo"], "initial mass / final mass", 3),
  q("Thrust-to-weight > 1 is needed to…", ["orbit without any speed", "lift off from the pad (in the simple vertical sense)", "reenter", "dock"], "lift off from the pad (in the simple vertical sense)", 1),
  q("Vacuum engines have…", ["no nozzles", "larger nozzles than sea-level engines, typically", "smaller bells always in vacuum", "solid grains only"], "larger nozzles than sea-level engines, typically", 2),
  q("Sea-level engines must avoid…", ["all cooling", "over-expansion / flow separation in a huge vacuum bell at 1 atm", "all gimbals", "all igniters"], "over-expansion / flow separation in a huge vacuum bell at 1 atm", 3),
  q("Gimbaling an engine provides…", ["life support", "thrust-vector control", "radio", "landing radar as the gimbal's only job"], "thrust-vector control", 2),
  q("Grid fins on a booster help…", ["start the turbopump as fins", "steer during reentry / landing", "dock to ISS", "radiate JWST heat"], "steer during reentry / landing", 2),
  q("A suicide burn / hoverslam is a…", ["docking at ISS", "late, high-thrust landing burn", "fairing deploy", "stage sep"], "late, high-thrust landing burn", 3),
  q("Falcon 9 is a…", ["solid ICBM of the 1960s", "two-stage orbital rocket with a reusable first stage", "capsule only", "space station"], "two-stage orbital rocket with a reusable first stage", 1),
  q("Falcon Heavy has…", ["one solid motor", "three Falcon first-stage cores", "no engines", "a nuclear stage"], "three Falcon first-stage cores", 2),
  q("Starship (as flown in tests) is a…", ["Apollo CSM", "stainless-steel fully reusable two-stage vehicle (Ship + Super Heavy)", "a CubeSat", "a rover"], "stainless-steel fully reusable two-stage vehicle (Ship + Super Heavy)", 2),
  q("Merlin engines burn…", ["hydrolox", "LOX and RP-1", "ion xenon as Merlin", "solid APCP as Merlin"], "LOX and RP-1", 2),
  q("Raptor engines burn…", ["RP-1 / LOX as Raptor", "methalox", "hypergolics as Raptor", "solid fuel"], "methalox", 2),
  q("RS-25 engines (SLS core / Shuttle main) burn…", ["RP-1", "hydrolox", "methane as RS-25", "solid"], "hydrolox", 3),
  q("SRBs are…", ["station robotic bases", "solid rocket boosters", "star-tracker boxes", "spacesuit backpacks as this acronym's only meaning"], "solid rocket boosters", 1),
  q("SLS is NASA's…", ["SpaceX's tanker", "Space Launch System (Artemis heavy lift)", "a Cubesat class", "a rover"], "Space Launch System (Artemis heavy lift)", 2),
  q("Orion is a…", ["SpaceX tanker", "NASA crew capsule for Artemis", "a rover of Mars of 2020s crew", "an ISS module of 1998 as Orion"], "NASA crew capsule for Artemis", 2),
  q("Dragon is a…", ["NASA SLS core", "SpaceX capsule (cargo and crew versions)", "a Soviet station", "a Chinese rover"], "SpaceX capsule (cargo and crew versions)", 1),
  q("Starliner is a…", ["SpaceX tanker", "Boeing crew capsule", "a rover", "a solid motor"], "Boeing crew capsule", 2),
  q("Soyuz is a…", ["NASA shuttle", "long-running Russian crew vehicle", "a Cubesat deployer only", "an ESA rover of Mars"], "long-running Russian crew vehicle", 1),
  q("The Apollo LM was the…", ["command module that stayed in lunar orbit as the lander", "lunar module that landed two astronauts", "Saturn V first stage", "a rover of 2021"], "lunar module that landed two astronauts", 1),
  q("The Saturn V was a…", ["two-stage Falcon", "three-stage Moon rocket", "solid ICBM of Minuteman", "capsule"], "three-stage Moon rocket", 1),
  q("A cleanroom for spacecraft is about…", ["louder fans only", "particle (and often molecular) contamination control", "warmer air only", "darkness only"], "particle (and often molecular) contamination control", 2),
  q("A TVAC test is…", ["a road test of a car", "thermal-vacuum: space-like heat and vacuum", "a pH test", "a mass cal of E2"], "thermal-vacuum: space-like heat and vacuum", 2),
  q("Vibe testing a spacecraft uses a…", ["CMM", "shaker table to mimic launch", "optical flat", "deadweight tester of pressure as the usual vibe"], "shaker table to mimic launch", 2),
  q("An anechoic chamber can test…", ["gauge blocks", "RF / antenna patterns (and sometimes acoustics)", "pH", "the SI mole"], "RF / antenna patterns (and sometimes acoustics)", 3),
  q("MLI is…", ["a NASA center", "multi-layer insulation (gold/aluminized blankets)", "a fuel", "a wrench"], "multi-layer insulation (gold/aluminized blankets)", 2),
  q("A reaction wheel stores…", ["propellant", "angular momentum to point a spacecraft", "crew water as the wheel's job", "heat of reentry"], "angular momentum to point a spacecraft", 2),
  q("A control-moment gyro is a…", ["main engine of Falcon", "high-torque attitude actuator (ISS uses CMGs)", "heat shield", "hatch"], "high-torque attitude actuator (ISS uses CMGs)", 3),
  q("Passivation of a spent stage is…", ["painting it gold", "venting leftover energy so it is less likely to explode as debris", "restarting it to GEO", "turning it into a station"], "venting leftover energy so it is less likely to explode as debris", 3),
  q("Kessler syndrome is a…", ["type of rocket engine", "runaway collision cascade of orbital debris", "lunar dust storm of Apollo", "a spacesuit leak"], "runaway collision cascade of orbital debris", 3),
  q("Space situational awareness tracks…", ["only weather of Earth as this phrase's space meaning", "satellites and debris", "only fish", "only tarantulas"], "satellites and debris", 2),
  q("A cubesat 1U is…", ["1 metre on a side", "10 × 10 × 10 cm", "1 km", "a Falcon fairing"], "10 × 10 × 10 cm", 2),
  q("Ion thrusters offer…", ["solid-rocket punch of liftoff as the usual ion job", "high Isp, low thrust, using electric acceleration of ions", "no power need", "crew taxi from the pad"], "high Isp, low thrust, using electric acceleration of ions", 2),
  q("Hall thrusters are a type of…", ["solid booster", "electric propulsion", "heat shield", "parachute"], "electric propulsion", 3),
  q("Xenon is a common…", ["solid grain", "ion-thruster propellant", "heat-shield tile", "spacesuit gas of 100% as the only use"], "ion-thruster propellant", 2),
  q("A RTG makes electricity from…", ["solar panels of LEO as this acronym", "heat of decaying plutonium-238 (typical deep-space)", "a diesel of the pad", "a fuel cell of RP-1"], "heat of decaying plutonium-238 (typical deep-space)", 2),
  q("Solar arrays do not help much…", ["in LEO ever", "in the outer solar system compared with an RTG", "at 1 AU as a rule of no-arrays", "on the ISS as a rule"], "in the outer solar system compared with an RTG", 2),
  q("A sunshade on JWST keeps the telescope…", ["warm like a greenhouse as the goal", "cold in infrared", "spinning", "in LEO"], "cold in infrared", 1),
  q("Infrared telescopes need to be cold because…", ["infrared cannot be focused", "the telescope's own heat would swamp the sky", "CCDs cannot work cold as a rule of Hubble", "L2 is hot"], "the telescope's own heat would swamp the sky", 2),
  q("A clean FOD walkdown is about…", ["only rain", "foreign-object debris that could damage a vehicle", "only radio", "only mass cal"], "foreign-object debris that could damage a vehicle", 2),
  q("Torque-stripe / witness paint shows if a…", ["tank has fuel", "fastener has moved", "clock is right", "orbit is polar"], "fastener has moved", 2),
  q("A connector saver is a…", ["heat shield tile", "wear item so flight connectors are not mated to death in test", "main engine", "parachute"], "wear item so flight connectors are not mated to death in test", 3),
  q("Red-tag / green-tag in aerospace config control marks…", ["only mass class", "items that must be removed or are flight-ready", "only pH", "only the SI brochure"], "items that must be removed or are flight-ready", 3),
  q("A flight article is the…", ["poster", "vehicle that is meant to fly, not a mockup", "a textbook", "a cal weight of E2"], "vehicle that is meant to fly, not a mockup", 1),
  q("GSE is…", ["a NASA center", "ground support equipment", "a fuel of Raptor", "a moon"], "ground support equipment", 2),
  q("LOX loading on the pad is a…", ["room-temperature water fill as LOX", "cryogenic hazardous operation", "paint job", "software flash only"], "cryogenic hazardous operation", 1),
  q("A hold-down / release mechanism keeps a rocket…", ["in GEO", "on the pad until thrust is healthy", "cold", "radio silent"], "on the pad until thrust is healthy", 2),
  q("A range safety system can…", ["only take photos", "destroy or halt a failing rocket", "only measure pH", "only cal a torque wrench"], "destroy or halt a failing rocket", 1),
  q("Telemetry is…", ["fuel", "data sent from the vehicle to the ground", "a heat shield", "a wrench"], "data sent from the vehicle to the ground", 1),
  q("A transponder helps the range…", ["load LOX", "track the vehicle", "wring gauge blocks", "sex a tarantula"], "track the vehicle", 1),
  q("The Tsiolkovsky rocket equation assumes…", ["wings always", "no external forces in the simple form (thrust in free space)", "a runway", "a heat shield"], "no external forces in the simple form (thrust in free space)", 3),
  q("Fairing recovery (when done) happens…", ["before liftoff", "after payload deploy, on parachutes or with a ship", "on the Moon", "in GEO"], "after payload deploy, on parachutes or with a ship", 2),
  q("A rideshare launch carries…", ["only one astronaut as the definition", "many small payloads on one rocket", "only cargo to ISS as the word", "only tanks of water"], "many small payloads on one rocket", 1),
  q("The Van Allen belts matter for…", ["fish", "electronics and crew on high orbits / transits", "gauge blocks on a plate", "pH of a bath"], "electronics and crew on high orbits / transits", 2),
  q("SEUs (single-event upsets) are…", ["engine outages of RP-1 as this acronym", "bit flips from radiation", "a kind of fairing", "a mass class"], "bit flips from radiation", 3),
  q("EDAC / TMR in avionics fights…", ["ice on the pad only", "radiation-induced errors", "pH drift", "gauge-block wring"], "radiation-induced errors", 3),
  q("A cleanroom class (ISO 14644) limits…", ["mass of E2", "particles per volume", "the SI second", "candela"], "particles per volume", 2),
  q("Outgassing in vacuum can…", ["help wring gauge blocks", "contaminate optics and sensors", "calibrate a deadweight tester", "sex a tarantula"], "contaminate optics and sensors", 2),
  q("Bakeout of hardware is to…", ["add oil", "drive off volatiles before flight", "paint it", "load RP-1 into an avionics box"], "drive off volatiles before flight", 2),
  q("A MLI blanket looks gold because of…", ["solid gold foil of a vault as the usual flight MLI", "vapor-deposited metal (often aluminum; gold Kapton in photos)", "brass of a gauge block", "paint of a school bus"], "vapor-deposited metal (often aluminum; gold Kapton in photos)", 3),
  q("The dark side of a spacecraft can be…", ["always room temperature without design", "very cold; the Sun side very hot — hence thermal design", "always 20 °C like a metrology lab with no effort", "molten on both sides always"], "very cold; the Sun side very hot — hence thermal design", 1),
  q("Heat pipes move heat by…", ["conduction of granite only", "evaporating and condensing a working fluid", "radio waves", "spin of a reaction wheel as the heat path"], "evaporating and condensing a working fluid", 3),
  q("A louvre or variable-emittance device helps…", ["steer a booster as fins", "regulate radiator heat rejection", "measure pH", "wring blocks"], "regulate radiator heat rejection", 3),
  q("The solar constant at 1 AU is about…", ["1 W/m²", "1360 W/m²", "10 W/m²", "136 000 W/m²"], "1360 W/m²", 3),
  q("Albedo of a planet is the…", ["mass", "fraction of sunlight it reflects", "spin rate", "magnetic field as this word"], "fraction of sunlight it reflects", 2),
  q("A terminator orbit imaging pass is near the…", ["equator always as this word in imaging", "day/night line", "Lagrange point as the line", "core of the Earth"], "day/night line", 3),
  q("Ground sample distance in remote sensing is…", ["the SI metre's definition", "how large a pixel is on the Earth", "a mass of a rock", "a pH"], "how large a pixel is on the Earth", 2),
  q("Synthetic aperture radar can image…", ["only in sunlight like a phone camera as SAR's limit", "through clouds, day or night", "only under the sea as a camera", "only stars"], "through clouds, day or night", 2),
  q("A cubesat deployer (P-POD and kin) is a…", ["heat shield", "spring-loaded box that ejects small sats", "main engine", "crew hatch of Orion"], "spring-loaded box that ejects small sats", 3),
  q("The tyranny of the rocket equation is that…", ["engines cannot gimbal", "fuel must lift fuel, so mass ratio explodes with delta-v", "Isp is always 1 s", "staging is illegal"], "fuel must lift fuel, so mass ratio explodes with delta-v", 2),
];

