import { q } from "../quiz";
import type { TriviaQ } from "../types";

export const SCIENCE_BANK: TriviaQ[] = [
  q("Water freezes at what temperature on the Celsius scale?", ["0\u00b0C", "32\u00b0C", "100\u00b0C", "\u221210\u00b0C"], "0\u00b0C", 1),
  q("Water boils at sea level at\u2026", ["0\u00b0C", "50\u00b0C", "100\u00b0C", "212\u00b0C"], "100\u00b0C", 1),
  q("The chemical formula for water is\u2026", ["HO", "H2O", "O2", "CO2"], "H2O", 1),
  q("Humans breathe in oxygen and breathe out mostly\u2026", ["ozone", "carbon dioxide", "helium", "nitrogen only"], "carbon dioxide", 1),
  q("The Earth orbits the\u2026", ["Moon", "Sun", "Mars", "Polaris"], "Sun", 1),
  q("The Moon orbits the\u2026", ["Sun only", "Earth", "Jupiter", "Mars"], "Earth", 1),
  q("How many planets in the Solar System (current count)?", ["8", "9", "10", "12"], "8", 1),
  q("The closest planet to the Sun is\u2026", ["Venus", "Mercury", "Earth", "Mars"], "Mercury", 1),
  q("The largest planet in the Solar System is\u2026", ["Saturn", "Jupiter", "Neptune", "Earth"], "Jupiter", 1),
  q("Plants make food using\u2026", ["photosynthesis", "fermentation only", "rust", "magnetism"], "photosynthesis", 1),
  q("The gas plants take in for photosynthesis is\u2026", ["oxygen", "carbon dioxide", "helium", "ozone"], "carbon dioxide", 1),
  q("Blood is pumped by the\u2026", ["liver", "heart", "lung only", "kidney"], "heart", 1),
  q("Bones are part of the\u2026", ["nervous system", "skeletal system", "endocrine only", "integument only"], "skeletal system", 1),
  q("The organ that filters blood and makes urine is the\u2026", ["liver", "kidney", "spleen", "pancreas"], "kidney", 1),
  q("Insects have how many legs?", ["4", "6", "8", "10"], "6", 1),
  q("Spiders have how many legs?", ["6", "8", "10", "12"], "8", 1),
  q("A compass needle points roughly toward magnetic\u2026", ["east", "west", "north", "the equator"], "north", 1),
  q("Sound cannot travel through\u2026", ["air", "water", "steel", "a vacuum"], "a vacuum", 1),
  q("Light travels faster than\u2026", ["nothing \u2014 it's slow", "sound", "radio never", "heat never"], "sound", 1),
  q("The center of an atom is the\u2026", ["electron cloud only", "nucleus", "orbit", "shell"], "nucleus", 1),
  q("Electrons have what charge?", ["positive", "negative", "neutral", "changing"], "negative", 1),
  q("Protons have what charge?", ["positive", "negative", "neutral", "none"], "positive", 1),
  q("Table salt is mostly\u2026", ["sodium chloride", "sugar", "calcium", "iron oxide"], "sodium chloride", 1),
  q("Rust is a form of\u2026", ["iron oxide", "pure iron", "carbon", "gold"], "iron oxide", 1),
  q("The hardest natural mineral on Mohs scale is\u2026", ["quartz", "diamond", "talc", "gold"], "diamond", 1),
  q("Talc sits where on the Mohs hardness scale?", ["1 \u2014 the softest", "5", "7", "10"], "1 \u2014 the softest", 2),
  q("DNA carries\u2026", ["blood type only", "genetic information", "only proteins", "only fats"], "genetic information", 1),
  q("The process of cell division that makes two identical cells is\u2026", ["meiosis only", "mitosis", "osmosis", "fusion"], "mitosis", 2),
  q("Meiosis is involved in making\u2026", ["skin cells only", "sex cells / gametes", "bone only", "blood plasma"], "sex cells / gametes", 2),
  q("The speed of light in vacuum is about\u2026", ["3 \u00d7 10\u2078 m/s", "3 \u00d7 10\u00b3 m/s", "300 m/s", "3 m/s"], "3 \u00d7 10\u2078 m/s", 2),
  q("Earth's atmosphere is mostly\u2026", ["oxygen", "nitrogen", "carbon dioxide", "argon"], "nitrogen", 2),
  q("Ozone in the stratosphere absorbs much of the Sun's\u2026", ["visible light", "ultraviolet radiation", "radio", "infrared only"], "ultraviolet radiation", 2),
  q("A year is the time Earth takes to\u2026", ["spin once", "orbit the Sun once", "orbit the Moon", "stop"], "orbit the Sun once", 1),
  q("A day is the time Earth takes to\u2026", ["orbit the Sun", "rotate once on its axis", "orbit the Moon", "precess"], "rotate once on its axis", 1),
  q("Seasons are caused mainly by Earth's\u2026", ["distance changing a lot", "axial tilt", "moon's color", "sunspots only"], "axial tilt", 2),
  q("Tides are caused primarily by the gravity of the\u2026", ["Sun only", "Moon", "Jupiter", "Earth's core"], "Moon", 2),
  q("The pH of a neutral solution is\u2026", ["0", "1", "7", "14"], "7", 2),
  q("Acids have pH\u2026", ["above 7", "below 7", "exactly 14", "exactly 10"], "below 7", 2),
  q("The SI unit of force is the\u2026", ["watt", "newton", "joule", "pascal"], "newton", 2),
  q("The SI unit of energy is the\u2026", ["newton", "watt", "joule", "ampere"], "joule", 2),
  q("The SI unit of power is the\u2026", ["joule", "watt", "volt", "ohm"], "watt", 2),
  q("Voltage is measured in\u2026", ["amps", "volts", "ohms", "watts"], "volts", 1),
  q("Current is measured in\u2026", ["volts", "amperes", "ohms", "joules"], "amperes", 2),
  q("Resistance is measured in\u2026", ["volts", "amps", "ohms", "farads"], "ohms", 2),
  q("Ohm's law is\u2026", ["V = IR", "P = mv", "F = d/t", "E = mc"], "V = IR", 2),
  q("E = mc\u00b2 is associated with\u2026", ["Newton", "Einstein", "Faraday", "Curie"], "Einstein", 1),
  q("Gravity on the Moon compared to Earth is about\u2026", ["the same", "1/6", "twice", "zero"], "1/6", 2),
  q("The red planet is\u2026", ["Venus", "Mars", "Jupiter", "Mercury"], "Mars", 1),
  q("Saturn is famous for its\u2026", ["one moon", "rings", "solid surface you can walk", "green color"], "rings", 1),
  q("A light-year measures\u2026", ["time", "distance", "mass", "temperature"], "distance", 2),
  q("The galaxy that contains the Solar System is the\u2026", ["Andromeda", "Milky Way", "Whirlpool", "Sombrero"], "Milky Way", 1),
  q("The nearest star to the Sun is\u2026", ["Sirius", "Proxima Centauri / Alpha Centauri system", "Betelgeuse", "Polaris"], "Proxima Centauri / Alpha Centauri system", 3),
  q("Atomic number is the number of\u2026", ["neutrons", "protons", "electrons in ions always", "nuclei in a mole"], "protons", 2),
  q("Isotopes of an element differ in\u2026", ["proton count", "neutron count", "element name", "atomic number"], "neutron count", 3),
  q("The most abundant gas in Earth's air is\u2026", ["oxygen", "nitrogen", "CO2", "hydrogen"], "nitrogen", 2),
  q("Chlorophyll makes plants look\u2026", ["red", "green", "blue", "white"], "green", 1),
  q("Mammals typically\u2026", ["lay eggs always", "produce milk for young", "have gills", "lack backbones"], "produce milk for young", 1),
  q("Birds are the living relatives of\u2026", ["sharks", "dinosaurs (theropods)", "insects", "amphibians only"], "dinosaurs (theropods)", 2),
  q("The theory of evolution by natural selection is tied to\u2026", ["Newton", "Darwin", "Mendel only", "Pasteur only"], "Darwin", 2),
  q("Mendel is associated with\u2026", ["gravity", "heredity in peas", "relativity", "antibiotics"], "heredity in peas", 2),
  q("Penicillin was famously isolated by\u2026", ["Pasteur", "Fleming", "Jenner", "Salk"], "Fleming", 2),
  q("Vaccination as a practice is associated early with\u2026", ["Jenner (smallpox)", "Newton", "Bohr", "Hawking"], "Jenner (smallpox)", 2),
  q("The periodic table is arranged by\u2026", ["alphabetical names", "atomic number", "discovery date", "density only"], "atomic number", 2),
  q("Noble gases are generally\u2026", ["highly reactive", "unreactive", "metals", "solids at room temp always"], "unreactive", 2),
  q("The first element on the periodic table is\u2026", ["helium", "hydrogen", "lithium", "carbon"], "hydrogen", 1),
  q("Diamond and graphite are both forms of\u2026", ["iron", "carbon", "silicon", "oxygen"], "carbon", 2),
  q("The greenhouse gas humans have increased most by burning fuel is\u2026", ["oxygen", "nitrogen", "carbon dioxide", "argon"], "carbon dioxide", 2),
  q("A black hole is a region where\u2026", ["nothing special happens", "gravity is so strong light cannot escape", "time stops for sure in all frames", "stars are born"], "gravity is so strong light cannot escape", 2),
  q("Tectonic plates move because of\u2026", ["the Moon only", "convection in Earth's mantle", "solar wind", "human mining"], "convection in Earth's mantle", 3),
  q("The Richter scale (and successors) measure\u2026", ["wind", "earthquake magnitude", "rainfall", "tides"], "earthquake magnitude", 2),
  q("Igneous rock forms from\u2026", ["compressed mud only", "cooled magma or lava", "only wind", "only ice"], "cooled magma or lava", 2),
  q("Fossils are most often found in which rock type?", ["igneous", "sedimentary", "pure metal", "obsidian only"], "sedimentary", 2),
  q("The speed of sound in air at room temperature is about\u2026", ["3 m/s", "34 m/s", "340 m/s", "3400 m/s"], "340 m/s", 3),
  q("Absolute zero is\u2026", ["0\u00b0C", "0\u00b0F", "0 K", "100 K"], "0 K", 2),
  q("Absolute zero in Celsius is about\u2026", ["0", "\u2212100", "\u2212273", "\u2212459"], "\u2212273", 3),
  q("The human adult body has roughly how many bones?", ["106", "206", "306", "506"], "206", 2),
  q("Red blood cells carry\u2026", ["only water", "oxygen (via hemoglobin)", "only fat", "DNA to the skin"], "oxygen (via hemoglobin)", 2),
  q("The largest organ of the human body is the\u2026", ["liver", "skin", "brain", "lung"], "skin", 2),
  q("Neurons transmit signals using\u2026", ["only heat", "electrical and chemical means", "only sound", "only light"], "electrical and chemical means", 2),
  q("The Hubble Space Telescope observes from\u2026", ["the Moon", "low Earth orbit", "the seafloor", "Antarctica only"], "low Earth orbit", 2),
  q("CRISPR is a tool for\u2026", ["weather", "gene editing", "fusion power", "mapping the seafloor"], "gene editing", 3),
  q("The half-life of a radioisotope is the time for\u2026", ["it to vanish", "half the nuclei to decay", "it to freeze", "orbit once"], "half the nuclei to decay", 3),
  q("Newton's second law is often written\u2026", ["E = mc\u00b2", "F = ma", "V = IR", "P = IV only"], "F = ma", 2),
  q("Work in physics is\u2026", ["force times distance (along the force)", "mass times time", "only heat", "voltage times charge always"], "force times distance (along the force)", 3),
];
