import { q } from "../quiz";
import type { TriviaQ } from "../types";

export const SCIENCE_MORE: TriviaQ[] = [
  q("The chemical symbol H stands for…", ["Nitrogen", "Hydrogen", "Iron", "Oxygen"], "Hydrogen", 1),
  q("The chemical symbol He stands for…", ["Neon", "Cobalt", "Copper", "Helium"], "Helium", 1),
  q("Helium's atomic number is…", ["2", "8", "3", "1"], "2", 1),
  q("The chemical symbol Li stands for…", ["Platinum", "Calcium", "Lithium", "Mercury"], "Lithium", 1),
  q("Lithium's atomic number is…", ["2", "3", "9", "4"], "3", 1),
  q("The chemical symbol Be stands for…", ["Beryllium", "Silicon", "Mercury", "Uranium"], "Beryllium", 1),
  q("Beryllium's atomic number is…", ["5", "10", "3", "4"], "4", 1),
  q("The chemical symbol B stands for…", ["Tin", "Magnesium", "Argon", "Boron"], "Boron", 1),
  q("Boron's atomic number is…", ["11", "5", "6", "4"], "5", 1),
  q("The chemical symbol C stands for…", ["Carbon", "Zinc", "Chromium", "Calcium"], "Carbon", 1),
  q("Carbon's atomic number is…", ["5", "7", "12", "6"], "6", 1),
  q("The chemical symbol N stands for…", ["Platinum", "Lithium", "Neon", "Nitrogen"], "Nitrogen", 1),
  q("Nitrogen's atomic number is…", ["13", "7", "8", "6"], "7", 1),
  q("The chemical symbol O stands for…", ["Oxygen", "Iodine", "Hydrogen", "Platinum"], "Oxygen", 1),
  q("Oxygen's atomic number is…", ["14", "8", "9", "7"], "8", 1),
  q("The chemical symbol F stands for…", ["Titanium", "Iodine", "Fluorine", "Tin"], "Fluorine", 1),
  q("Fluorine's atomic number is…", ["8", "15", "10", "9"], "9", 1),
  q("The chemical symbol Ne stands for…", ["Mercury", "Neon", "Manganese", "Cobalt"], "Neon", 1),
  q("Neon's atomic number is…", ["10", "11", "16", "9"], "10", 1),
  q("The chemical symbol Na stands for…", ["Potassium", "Hydrogen", "Sodium", "Platinum"], "Sodium", 1),
  q("Sodium's atomic number is…", ["11", "17", "12", "10"], "11", 2),
  q("The chemical symbol Mg stands for…", ["Argon", "Magnesium", "Hydrogen", "Platinum"], "Magnesium", 1),
  q("Magnesium's atomic number is…", ["12", "11", "13", "18"], "12", 2),
  q("The chemical symbol Al stands for…", ["Aluminum", "Copper", "Zinc", "Potassium"], "Aluminum", 1),
  q("Aluminum's atomic number is…", ["12", "13", "19", "14"], "13", 2),
  q("The chemical symbol Si stands for…", ["Gold", "Tungsten", "Silicon", "Lead"], "Silicon", 1),
  q("Silicon's atomic number is…", ["15", "14", "13", "20"], "14", 2),
  q("The chemical symbol P stands for…", ["Cobalt", "Lithium", "Phosphorus", "Carbon"], "Phosphorus", 1),
  q("Phosphorus's atomic number is…", ["15", "16", "21", "14"], "15", 2),
  q("The chemical symbol S stands for…", ["Iron", "Sulfur", "Potassium", "Silicon"], "Sulfur", 1),
  q("Sulfur's atomic number is…", ["15", "16", "17", "22"], "16", 2),
  q("The chemical symbol Cl stands for…", ["Copper", "Chlorine", "Tungsten", "Phosphorus"], "Chlorine", 1),
  q("Chlorine's atomic number is…", ["16", "18", "17", "23"], "17", 2),
  q("The chemical symbol Ar stands for…", ["Silver", "Argon", "Copper", "Calcium"], "Argon", 1),
  q("Argon's atomic number is…", ["24", "17", "18", "19"], "18", 2),
  q("The chemical symbol K stands for…", ["Mercury", "Nitrogen", "Neon", "Potassium"], "Potassium", 1),
  q("Potassium's atomic number is…", ["19", "25", "18", "20"], "19", 2),
  q("The chemical symbol Ca stands for…", ["Fluorine", "Chromium", "Calcium", "Titanium"], "Calcium", 1),
  q("Calcium's atomic number is…", ["19", "21", "26", "20"], "20", 2),
  q("The chemical symbol Fe stands for…", ["Nitrogen", "Mercury", "Tin", "Iron"], "Iron", 2),
  q("Iron's atomic number is…", ["25", "32", "26", "27"], "26", 2),
  q("The chemical symbol Cu stands for…", ["Nitrogen", "Potassium", "Sulfur", "Copper"], "Copper", 2),
  q("Copper's atomic number is…", ["29", "35", "28", "30"], "29", 2),
  q("The chemical symbol Zn stands for…", ["Argon", "Zinc", "Mercury", "Oxygen"], "Zinc", 2),
  q("Zinc's atomic number is…", ["30", "31", "29", "36"], "30", 2),
  q("The chemical symbol Ag stands for…", ["Silver", "Iron", "Uranium", "Lithium"], "Silver", 2),
  q("Silver's atomic number is…", ["53", "48", "46", "47"], "47", 2),
  q("The chemical symbol Au stands for…", ["Gold", "Carbon", "Iron", "Oxygen"], "Gold", 2),
  q("Gold's atomic number is…", ["80", "85", "79", "78"], "79", 2),
  q("The chemical symbol Hg stands for…", ["Platinum", "Manganese", "Mercury", "Beryllium"], "Mercury", 2),
  q("Mercury's atomic number is…", ["80", "79", "86", "81"], "80", 2),
  q("The chemical symbol Pb stands for…", ["Lead", "Lithium", "Oxygen", "Copper"], "Lead", 2),
  q("Lead's atomic number is…", ["88", "82", "81", "83"], "82", 2),
  q("The chemical symbol U stands for…", ["Uranium", "Nitrogen", "Titanium", "Mercury"], "Uranium", 2),
  q("Uranium's atomic number is…", ["91", "98", "92", "93"], "92", 2),
  q("The chemical symbol Sn stands for…", ["Tungsten", "Beryllium", "Tin", "Gold"], "Tin", 2),
  q("Tin's atomic number is…", ["56", "51", "49", "50"], "50", 2),
  q("The chemical symbol I stands for…", ["Iodine", "Chromium", "Lithium", "Beryllium"], "Iodine", 2),
  q("Iodine's atomic number is…", ["59", "53", "54", "52"], "53", 2),
  q("The chemical symbol W stands for…", ["Gold", "Silver", "Tungsten", "Sulfur"], "Tungsten", 2),
  q("Tungsten's atomic number is…", ["75", "80", "74", "73"], "74", 2),
  q("The chemical symbol Pt stands for…", ["Boron", "Zinc", "Platinum", "Sulfur"], "Platinum", 2),
  q("Platinum's atomic number is…", ["78", "77", "79", "84"], "78", 2),
  q("The chemical symbol Ni stands for…", ["Platinum", "Magnesium", "Nickel", "Silver"], "Nickel", 2),
  q("Nickel's atomic number is…", ["29", "34", "27", "28"], "28", 2),
  q("The chemical symbol Co stands for…", ["Phosphorus", "Cobalt", "Oxygen", "Silver"], "Cobalt", 2),
  q("Cobalt's atomic number is…", ["28", "33", "27", "26"], "27", 2),
  q("The chemical symbol Mn stands for…", ["Sulfur", "Aluminum", "Manganese", "Gold"], "Manganese", 2),
  q("Manganese's atomic number is…", ["25", "26", "31", "24"], "25", 2),
  q("The chemical symbol Cr stands for…", ["Chromium", "Oxygen", "Beryllium", "Tin"], "Chromium", 2),
  q("Chromium's atomic number is…", ["25", "30", "24", "23"], "24", 2),
  q("The chemical symbol Ti stands for…", ["Oxygen", "Boron", "Titanium", "Carbon"], "Titanium", 2),
  q("Titanium's atomic number is…", ["21", "23", "22", "28"], "22", 2),
  q("Which planet is closest to the Sun?", ["Mercury", "Saturn", "Earth", "Neptune"], "Mercury", 1),
  q("Which planet is second from the Sun?", ["Earth", "Venus", "Jupiter", "Saturn"], "Venus", 1),
  q("Which planet is third from the Sun?", ["Earth", "Mars", "Uranus", "Saturn"], "Earth", 1),
  q("Which planet is fourth from the Sun?", ["Uranus", "Mars", "Mercury", "Saturn"], "Mars", 1),
  q("Which planet is fifth from the Sun?", ["Neptune", "Mercury", "Saturn", "Jupiter"], "Jupiter", 2),
  q("Which planet is sixth from the Sun?", ["Saturn", "Jupiter", "Mars", "Venus"], "Saturn", 2),
  q("Which planet is seventh from the Sun?", ["Venus", "Saturn", "Earth", "Uranus"], "Uranus", 2),
  q("Which planet is eighth from the Sun?", ["Saturn", "Neptune", "Mercury", "Earth"], "Neptune", 2),
  q("The SI unit of force is the…", ["joule", "watt", "newton", "pascal"], "newton", 2),
  q("The SI unit of energy is the…", ["newton", "joule", "pascal", "ampere"], "joule", 2),
  q("The SI unit of power is the…", ["joule", "watt", "volt", "ohm"], "watt", 2),
  q("The SI unit of electric current is the…", ["volt", "ohm", "ampere", "watt"], "ampere", 2),
  q("The SI unit of electric potential is the…", ["ampere", "volt", "ohm", "coulomb"], "volt", 2),
  q("The SI unit of resistance is the…", ["volt", "ampere", "ohm", "farad"], "ohm", 2),
  q("The SI unit of frequency is the…", ["watt", "hertz", "lux", "becquerel"], "hertz", 2),
  q("The SI unit of pressure is the…", ["bar only", "pascal", "torr only", "atmosphere only"], "pascal", 2),
  q("The SI unit of temperature is the…", ["celsius only", "kelvin", "fahrenheit", "rankine"], "kelvin", 2),
  q("Ohm's law is often written…", ["F = ma", "V = IR", "E = mc²", "P = ρgh"], "V = IR", 2),
  q("Kinetic energy of a mass m at speed v is…", ["mv", "½mv²", "mgh only", "Fd only"], "½mv²", 3),
  q("Gravitational potential energy near Earth is approximately…", ["½mv²", "mgh", "mc²", "qV"], "mgh", 2),
  q("Momentum is…", ["mass × acceleration", "mass × velocity", "force × time only always", "energy / time"], "mass × velocity", 2),
  q("Acceleration is change of…", ["distance only", "velocity per time", "mass", "charge"], "velocity per time", 1),
  q("Velocity has both speed and…", ["color", "direction", "temperature", "charge"], "direction", 1),
  q("A vector has magnitude and…", ["only size", "direction", "only unit", "only sign of charge"], "direction", 1),
  q("A scalar has…", ["only direction", "magnitude only (no direction)", "always a unit vector", "always two axes"], "magnitude only (no direction)", 2),
  q("Newton's first law is about…", ["action-reaction only", "inertia", "F = ma as a slogan only of the second", "gravity only"], "inertia", 2),
  q("Newton's third law says forces come in…", ["triples", "equal and opposite pairs", "random sets", "only attractions"], "equal and opposite pairs", 1),
  q("Universal gravitation says the force goes as…", ["1/r", "1/r²", "r²", "r"], "1/r²", 3),
  q("In E = mc², c is the…", ["speed of sound", "speed of light", "charge of an electron", "a heat capacity"], "speed of light", 1),
  q("A photon is a…", ["nucleus", "quantum of light", "type of rock", "cell"], "quantum of light", 2),
  q("An isotope has the same number of protons and a different number of…", ["electrons always as the definition", "neutrons", "photons", "quarks of the atom's name"], "neutrons", 2),
  q("Atomic number is the number of…", ["neutrons", "protons", "nucleons always as a synonym", "electrons in ions always"], "protons", 1),
  q("Mass number is protons plus…", ["electrons", "neutrons", "photons", "neutrinos"], "neutrons", 2),
  q("A covalent bond shares…", ["protons", "electrons", "neutrons", "photons"], "electrons", 1),
  q("An ionic bond is attraction of…", ["two nuclei only", "oppositely charged ions", "two photons", "two neutrons"], "oppositely charged ions", 2),
  q("A pH of 7 is…", ["strongly acid", "neutral (in water at standard)", "strongly base", "undefined"], "neutral (in water at standard)", 1),
  q("A pH of 1 is…", ["neutral", "strongly acidic", "strongly basic", "a salt only"], "strongly acidic", 1),
  q("A pH of 13 is…", ["strongly acidic", "neutral", "strongly basic", "pure water"], "strongly basic", 1),
  q("Acids donate…", ["electrons only always", "protons (H⁺) in the Brønsted sense", "neutrons", "photons"], "protons (H⁺) in the Brønsted sense", 3),
  q("Oxidation is…", ["gain of electrons", "loss of electrons (in the simple redox sense)", "gain of neutrons", "loss of protons only as a name"], "loss of electrons (in the simple redox sense)", 3),
  q("The most abundant gas in dry air is…", ["oxygen", "nitrogen", "carbon dioxide", "argon"], "nitrogen", 1),
  q("Argon is a…", ["halogen", "noble gas", "alkali metal", "metalloid"], "noble gas", 2),
  q("Helium was first noticed in the…", ["Earth's core first", "Sun's spectrum", "Moon rocks first", "ocean vents first"], "Sun's spectrum", 3),
  q("Ozone's formula is…", ["O₂", "O₃", "CO₂", "NO₂"], "O₃", 2),
  q("Dry ice is…", ["solid oxygen", "solid carbon dioxide", "solid nitrogen", "frozen water"], "solid carbon dioxide", 2),
  q("Sublimation is…", ["liquid to solid", "solid to gas", "gas to liquid", "liquid to gas only"], "solid to gas", 2),
  q("Condensation is…", ["liquid to gas", "gas to liquid", "solid to gas", "solid to liquid"], "gas to liquid", 1),
  q("Evaporation is…", ["gas to liquid", "liquid to gas", "solid to liquid", "gas to solid"], "liquid to gas", 1),
  q("Melting is…", ["liquid to solid", "solid to liquid", "gas to solid", "liquid to gas"], "solid to liquid", 1),
  q("Freezing is…", ["solid to liquid", "liquid to solid", "gas to liquid", "solid to gas"], "liquid to solid", 1),
  q("A catalyst…", ["is always used up", "speeds a reaction without being consumed", "always slows a reaction", "changes the equilibrium constant in elementary teaching as a must"], "speeds a reaction without being consumed", 2),
  q("Enzymes are…", ["lipids only", "biological catalysts", "only salts", "only metals"], "biological catalysts", 1),
  q("Proteins are chains of…", ["sugars only", "amino acids", "fatty acids only", "nucleotides only"], "amino acids", 1),
  q("DNA's bases pair A with…", ["C", "G", "T", "U in DNA"], "T", 2),
  q("In RNA, adenine pairs with…", ["thymine only", "uracil", "guanine", "cytosine"], "uracil", 2),
  q("Mitochondria are the cell's…", ["libraries", "powerhouses (ATP)", "walls", "vacuoles only"], "powerhouses (ATP)", 1),
  q("The nucleus of a cell holds…", ["only ATP", "most of the DNA", "only fat", "only water"], "most of the DNA", 1),
  q("Ribosomes make…", ["DNA only", "proteins", "lipids only", "ATP only"], "proteins", 2),
  q("Chlorophyll is green because it…", ["emits only green photons as a laser", "reflects green light (absorbs other wavelengths)", "is rust", "is gold leaf"], "reflects green light (absorbs other wavelengths)", 2),
  q("Stomata on leaves are for…", ["only climbing", "gas exchange", "only storing starch always", "only color"], "gas exchange", 2),
  q("Xylem transports…", ["sugars only down", "water (and minerals) up from roots", "only oxygen to flowers", "only pollen"], "water (and minerals) up from roots", 3),
  q("Phloem transports…", ["only water up", "sugars", "only minerals from soil as a one-way xylem job", "only air"], "sugars", 3),
  q("A vertebrate has a…", ["exoskeleton of chitin always", "backbone", "shell of calcium always", "no skeleton"], "backbone", 1),
  q("Mammals are distinguished in part by…", ["feathers", "hair and milk", "scales only", "gills as adults always"], "hair and milk", 1),
  q("Birds are the living dinosaurs in the…", ["amphibian line", "theropod line, with feathers", "fish line only", "mammal line"], "theropod line, with feathers", 3),
  q("Amphibians typically…", ["live only in deserts as eggs on sand", "start in water and often live on land as adults", "fly as a rule", "have hair"], "start in water and often live on land as adults", 1),
  q("Reptiles are…", ["feathered as a rule", "amniotes with typically scaly skin", "always aquatic as larvae like tadpoles", "mammals"], "amniotes with typically scaly skin", 2),
  q("Insects are…", ["arachnids", "hexapod arthropods", "crustaceans only", "mollusks"], "hexapod arthropods", 2),
  q("Arachnids include…", ["beetles", "spiders, scorpions, mites, ticks", "snails", "starfish"], "spiders, scorpions, mites, ticks", 1),
  q("Crustaceans include…", ["spiders", "crabs, lobsters, shrimp (among others)", "beetles", "snails"], "crabs, lobsters, shrimp (among others)", 1),
  q("Mollusks include…", ["insects", "snails, clams, squid", "starfish", "sponges only"], "snails, clams, squid", 2),
  q("Echinoderms include…", ["insects", "starfish and sea urchins", "snails", "jellies only"], "starfish and sea urchins", 3),
  q("Fungi are more closely related to…", ["plants than to animals", "animals than to plants", "bacteria than to either", "viruses"], "animals than to plants", 3),
  q("A virus is…", ["a bacterium always", "an obligate infectious particle, not a cell", "a fungus", "a plant"], "an obligate infectious particle, not a cell", 2),
  q("Antibiotics target…", ["viruses", "bacteria", "broken bones", "only cancer"], "bacteria", 2),
  q("Vaccines train the…", ["liver to make insulin only", "immune system", "bones to grow only", "hair"], "immune system", 1),
  q("Insulin is made in the…", ["liver as the only source", "pancreas", "spleen", "thyroid"], "pancreas", 2),
  q("The thyroid sits in the…", ["abdomen", "neck", "foot", "skull only as a gland of the brain"], "neck", 1),
  q("Adrenaline is produced by the…", ["thyroid", "adrenal glands", "pineal only", "thymus only"], "adrenal glands", 2),
  q("The cerebrum is the…", ["heart", "large thinking part of the brain", "liver", "kidney"], "large thinking part of the brain", 1),
  q("The cerebellum helps…", ["filter blood", "coordinate movement", "make insulin", "pump blood"], "coordinate movement", 2),
  q("The femur is the…", ["shin", "thigh bone", "upper arm", "collarbone"], "thigh bone", 1),
  q("The tibia is a bone of the…", ["upper arm", "lower leg", "hand", "skull"], "lower leg", 2),
  q("The humerus is a bone of the…", ["thigh", "upper arm", "foot", "jaw"], "upper arm", 2),
  q("The mandible is the…", ["upper jaw only as maxilla", "lower jaw", "collarbone", "kneecap"], "lower jaw", 2),
  q("The patella is the…", ["elbow", "kneecap", "heel", "wrist"], "kneecap", 1),
  q("Red marrow makes…", ["only fat", "blood cells", "only keratin", "only enamel"], "blood cells", 2),
  q("Plasma is the…", ["cell only", "liquid part of blood", "bone only", "nerve only"], "liquid part of blood", 2),
  q("Platelets help…", ["seeing", "clotting", "hearing", "tasting"], "clotting", 1),
  q("The cornea is at the…", ["back of the eye as the retina", "front of the eye", "inner ear", "tongue"], "front of the eye", 2),
  q("The retina is at the…", ["front as the cornea", "back of the eye", "eardrum", "nostril"], "back of the eye", 2),
  q("The cochlea is in the…", ["eye", "inner ear", "nose", "throat"], "inner ear", 2),
  q("Taste buds are on the…", ["only the inner ear", "tongue (and some nearby tissue)", "only the retina", "only bone"], "tongue (and some nearby tissue)", 1),
  q("The largest internal organ is the…", ["heart", "liver", "spleen", "pancreas"], "liver", 2),
  q("Bile is made in the…", ["pancreas", "liver", "spleen", "kidney"], "liver", 2),
  q("Bile is stored in the…", ["spleen", "gallbladder", "appendix", "bladder of urine"], "gallbladder", 2),
  q("The appendix is attached to the…", ["stomach", "cecum / large intestine", "liver", "lung"], "cecum / large intestine", 3),
  q("Alveoli are tiny sacs in the…", ["kidneys", "lungs", "liver", "brain"], "lungs", 2),
  q("Nephrons are the working units of the…", ["lung", "kidney", "heart", "spleen"], "kidney", 3),
  q("A light-year measures…", ["time only", "distance", "mass", "temperature"], "distance", 2),
  q("A parsec is a unit of…", ["time", "distance", "luminosity only", "mass"], "distance", 3),
  q("Polaris is a star near the…", ["south celestial pole", "north celestial pole", "Sun as a planet", "Moon"], "north celestial pole", 2),
  q("A constellation is a…", ["planet", "pattern of stars in a region of sky", "galaxy as a synonym", "comet"], "pattern of stars in a region of sky", 1),
  q("The Milky Way is a…", ["planet", "galaxy", "star", "comet"], "galaxy", 1),
  q("Andromeda is the nearest large…", ["star", "spiral galaxy to us", "planet", "moon of Jupiter"], "spiral galaxy to us", 2),
  q("A nebula is a…", ["black hole always", "cloud of gas and dust", "planet", "asteroid only"], "cloud of gas and dust", 2),
  q("A supernova is a…", ["quiet star", "exploding star", "planet forming always", "comet"], "exploding star", 1),
  q("A comet is a…", ["rocky planet", "icy small body that can grow a tail near the Sun", "star", "galaxy"], "icy small body that can grow a tail near the Sun", 1),
  q("An asteroid is a…", ["star", "rocky small body, mostly in the belt", "galaxy", "cloud of gas only"], "rocky small body, mostly in the belt", 1),
  q("The asteroid belt lies between…", ["Earth and Mars", "Mars and Jupiter", "Jupiter and Saturn", "Neptune and Pluto"], "Mars and Jupiter", 2),
  q("Io, Europa, Ganymede, and Callisto are moons of…", ["Saturn", "Jupiter", "Uranus", "Neptune"], "Jupiter", 2),
  q("Titan is a moon of…", ["Jupiter", "Saturn", "Mars", "Earth"], "Saturn", 2),
  q("Triton is a moon of…", ["Uranus", "Neptune", "Saturn", "Pluto"], "Neptune", 3),
  q("Phobos and Deimos are moons of…", ["Earth", "Mars", "Venus", "Mercury"], "Mars", 2),
  q("Mercury and Venus have how many moons?", ["0", "1", "2", "many"], "0", 2),
  q("Saturn is famous for its…", ["red spot only as Jupiter's", "rings", "life", "solid rock surface like Earth's"], "rings", 1),
  q("Jupiter's Great Red Spot is a…", ["ocean", "storm", "volcano", "ring gap"], "storm", 1),
  q("Olympus Mons is a volcano on…", ["Earth", "Mars", "the Moon", "Venus as a name of a mountain there too but the famous tallest is Mars"], "Mars", 2),
  q("Mare on the Moon are…", ["seas of water", "dark plains of old lava", "polar ice only", "forests"], "dark plains of old lava", 2),
  q("Tides on Earth are raised chiefly by the…", ["Jupiter", "Moon", "Polaris", "asteroid belt"], "Moon", 1),
  q("Auroras are caused by…", ["only earthquakes", "charged particles and the magnetic field", "only volcanoes", "only the Moon's shadow"], "charged particles and the magnetic field", 2),
  q("Earth's magnetic field is generated in the…", ["crust only", "outer core", "atmosphere only", "Moon"], "outer core", 3),
  q("P waves are…", ["only ocean waves", "primary earthquake waves, faster", "only sound in air", "only light"], "primary earthquake waves, faster", 3),
  q("The Mohorovičić discontinuity is the boundary of the…", ["core and mantle as the Gutenberg", "crust and mantle", "inner and outer core", "lithosphere and space"], "crust and mantle", 3),
  q("Basalt is a common…", ["sedimentary sandstone", "extrusive igneous rock", "metamorphic marble", "mineral oil"], "extrusive igneous rock", 3),
  q("Granite is a common…", ["lava glass", "intrusive igneous rock", "evaporite", "coal"], "intrusive igneous rock", 2),
  q("Marble is metamorphosed…", ["sandstone", "limestone", "shale only as slate", "basalt"], "limestone", 2),
  q("Slate is metamorphosed…", ["limestone", "shale", "granite", "coal"], "shale", 3),
  q("Sandstone is a…", ["lava", "sedimentary rock of sand grains", "pure metal", "ice"], "sedimentary rock of sand grains", 1),
  q("Limestone is often made of…", ["pure silica glass", "calcium carbonate (shells, reefs, precipitates)", "iron only", "salt only as halite"], "calcium carbonate (shells, reefs, precipitates)", 2),
  q("Halite is…", ["fool's gold", "rock salt", "mica", "quartz"], "rock salt", 2),
  q("Pyrite is nicknamed…", ["fool's gold", "black lead", "heavy spar", "iceland spar"], "fool's gold", 1),
  q("Quartz is…", ["carbon", "silicon dioxide", "iron oxide", "calcium carbonate"], "silicon dioxide", 2),
  q("Mica splits in…", ["cubes only", "sheets", "needles only", "grains of sand only"], "sheets", 2),
  q("The water cycle includes evaporation, condensation, and…", ["only melting", "precipitation", "only sublimation of iron", "only photosynthesis"], "precipitation", 1),
  q("A cirrus cloud is…", ["low and dark always", "high and wispy", "a thunderstorm's anvil only as a name", "fog on the ground only"], "high and wispy", 2),
  q("A cumulonimbus is a…", ["fog", "tall storm cloud", "high ice veil only as cirrostratus", "streak of jet exhaust"], "tall storm cloud", 2),
  q("Lightning is a…", ["only a sound", "giant spark", "only rain", "only wind"], "giant spark", 1),
  q("Thunder is the…", ["light of the bolt", "sound of the lightning channel expanding", "rain", "hail only"], "sound of the lightning channel expanding", 2),
  q("A hurricane in the NW Pacific is often called a…", ["tornado", "typhoon", "blizzard", "chinook"], "typhoon", 2),
  q("A tornado is a…", ["ocean cyclone always", "violent rotating column from a thunderstorm", "snowstorm", "fog bank"], "violent rotating column from a thunderstorm", 1),
  q("The Fujita / Enhanced Fujita scale rates…", ["hurricanes", "tornado intensity", "earthquakes", "snow"], "tornado intensity", 2),
  q("The Saffir–Simpson scale rates…", ["tornadoes", "hurricanes", "earthquakes", "volcanoes"], "hurricanes", 2),
  q("The Beaufort scale rates…", ["rain", "wind", "snow depth", "earthquakes"], "wind", 3),
  q("A monsoon is a…", ["one thunderstorm", "seasonal wind (and the rain it often brings)", "one tornado", "a desert only"], "seasonal wind (and the rain it often brings)", 2),
  q("Dew point is the temperature at which…", ["water always boils", "air becomes saturated", "iron melts", "the Sun sets"], "air becomes saturated", 3),
  q("Relative humidity is…", ["the absolute grams always as a percent of 100 g", "how close the air is to saturation", "rainfall in inches", "cloud height"], "how close the air is to saturation", 2),
  q("The greenhouse effect is…", ["only the ozone hole", "trapping of outgoing infrared by gases", "only volcanic ash", "only city lights"], "trapping of outgoing infrared by gases", 2),
  q("Photosynthesis stores sunlight as…", ["only heat in the soil", "chemical energy in sugars", "only sound", "only magnetism"], "chemical energy in sugars", 1),
  q("Respiration in cells releases energy from…", ["only sunlight on the skin as the only source", "food (sugars, etc.)", "only metals", "only nitrogen gas"], "food (sugars, etc.)", 1),
  q("The food chain's base is usually…", ["lions", "producers (plants / phytoplankton)", "fungi only as the base of every chain", "humans"], "producers (plants / phytoplankton)", 1),
  q("A decomposer is typically a…", ["hawk", "fungus or bacterium", "deer", "whale"], "fungus or bacterium", 1),
  q("Carbon-14 dating works on…", ["all rocks of any age", "once-living things of the right age", "stars", "pure metals of any age"], "once-living things of the right age", 3),
  q("Half-life does not depend on…", ["the isotope", "how much you start with (for a given isotope, in the simple law)", "the decay constant", "time"], "how much you start with (for a given isotope, in the simple law)", 3),
  q("A Geiger counter detects…", ["wind", "ionizing radiation", "pH", "mass only"], "ionizing radiation", 2),
  q("X-rays were discovered by…", ["Curie as the only name", "Röntgen", "Einstein as a lab discovery", "Faraday"], "Röntgen", 3),
  q("Penicillin was noticed by…", ["Pasteur as the mold plate", "Fleming", "Salk", "Jenner as the mold"], "Fleming", 2),
  q("Vaccination against smallpox is associated with…", ["Fleming", "Jenner", "Salk as smallpox", "Pasteur as the first smallpox"], "Jenner", 2),
  q("Polio vaccine is associated with…", ["Jenner", "Salk (and Sabin)", "Fleming as a virus killer pill", "Röntgen"], "Salk (and Sabin)", 2),
  q("The structure of DNA was described in 1953 by…", ["Darwin and Wallace", "Watson and Crick (using Franklin's data, and Wilkins)", "Mendel only", "Pasteur and Koch"], "Watson and Crick (using Franklin's data, and Wilkins)", 2),
  q("Mendel studied inheritance in…", ["fruit flies only as the first", "pea plants", "mice only", "humans in a monastery hospital"], "pea plants", 2),
  q("Darwin and Wallace proposed…", ["the atom", "evolution by natural selection", "the germ theory as a first", "relativity"], "evolution by natural selection", 1),
  q("The germ theory of disease is associated with…", ["Newton", "Pasteur and Koch (among others)", "Galileo", "Kepler"], "Pasteur and Koch (among others)", 2),
  q("Heliocentrism in the modern era is associated with…", ["Ptolemy as the modern", "Copernicus (and Galileo's advocacy)", "Aristotle as the modern", "Pliny"], "Copernicus (and Galileo's advocacy)", 2),
  q("Galileo used a telescope to see…", ["bacteria", "moons of Jupiter (among other sights)", "DNA", "X-rays"], "moons of Jupiter (among other sights)", 2),
  q("Kepler's laws describe…", ["falling apples only", "planetary orbits", "electric circuits", "genetics"], "planetary orbits", 2),
  q("Faraday linked…", ["only chemistry of gases", "electricity and magnetism in experiments", "only stars", "only peas"], "electricity and magnetism in experiments", 3),
  q("Maxwell's equations describe…", ["only gravity", "electric and magnetic fields", "only evolution", "only geology"], "electric and magnetic fields", 3),
  q("The first programmable electronic computers were built in the…", ["1840s as electronic", "1940s", "1990s as the first", "2000s"], "1940s", 3),
  q("The World Wide Web was proposed by…", ["Bill Gates as the web", "Tim Berners-Lee", "Steve Jobs as the web", "Elon Musk"], "Tim Berners-Lee", 2),
  q("GPS relies on…", ["only compass needles", "timing signals from satellites", "only barometers", "only star charts on paper"], "timing signals from satellites", 2),
];

