// Night markets (0.0.46): bake each city's market-eligible streets into src/game/marketStreets.ts.
//   node --experimental-strip-types scripts/bake-market-streets.mts [city …]
// Pulls every highway way within BAKE_R of spawn from Overpass (cached in /tmp/keyline-market-osm),
// then keeps the streets eligibleStreets() allows: named, walkable (walkable.ts), never a freeway,
// reachable on foot from spawn, inside the radius, with a lamp on them. Street data: OpenStreetMap
// contributors (ODbL).
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { CITIES } from "../src/game/data.ts";
import { eligibleStreets, type MarketStreet, type OsmWay } from "../src/game/nightMarket.ts";

const BAKE_R = 2300; // fetch a margin past MARKET_RADIUS_M so reachability sees the streets that join up outside it
const CACHE = "/tmp/keyline-market-osm";
const URLS = ["https://overpass.openstreetmap.fr/api/interpreter", "https://overpass-api.de/api/interpreter", "https://overpass.kumi.systems/api/interpreter"];
const KEEP = ["highway", "name", "foot", "access", "motorroad", "area", "sidewalk", "tunnel", "layer"];
const only = new Set(process.argv.slice(2));

async function fetchWays(id: string, lat: number, lng: number): Promise<OsmWay[]> {
  mkdirSync(CACHE, { recursive: true });
  const file = `${CACHE}/${id}.json`;
  if (existsSync(file)) return JSON.parse(readFileSync(file, "utf8")) as OsmWay[];
  const q = `[out:json][timeout:120];way["highway"](around:${BAKE_R},${lat},${lng});out tags geom;`;
  for (const u of URLS) {
    try {
      const res = await fetch(u, {
        method: "POST",
        body: "data=" + encodeURIComponent(q),
        headers: { "Content-Type": "application/x-www-form-urlencoded", "User-Agent": "keyline-market-bake/1.0 (github.com/xlockeddown-glitch/keyline)" },
        signal: AbortSignal.timeout(180_000),
      });
      if (!res.ok) {
        console.error(id, u, res.status);
        continue;
      }
      const json = (await res.json()) as { elements?: { id: number; tags?: Record<string, string>; geometry?: { lat: number; lon: number }[] }[] };
      const ways: OsmWay[] = [];
      for (const el of json.elements ?? []) {
        if (!el.geometry || el.geometry.length < 2) continue;
        const tags: Record<string, string> = {};
        for (const k of KEEP) if (el.tags?.[k] != null) tags[k] = el.tags[k]!;
        const line: number[] = [];
        for (const p of el.geometry) line.push(Math.round(p.lat * 1e6) / 1e6, Math.round(p.lon * 1e6) / 1e6);
        ways.push({ id: el.id, tags, line });
      }
      writeFileSync(file, JSON.stringify(ways));
      return ways;
    } catch (e) {
      console.error(id, u, (e as Error).message);
    }
  }
  throw new Error(`${id}: overpass failed`);
}

const out: Record<string, MarketStreet[]> = {};
const prevFile = "src/game/marketStreets.ts";
for (const city of Object.values(CITIES)) {
  if (only.size && !only.has(city.id)) continue;
  const ways = await fetchWays(city.id, city.spawn.lat, city.spawn.lng);
  const { streets } = eligibleStreets(ways, city.spawn, city.pois);
  out[city.id] = streets;
  console.log(city.id, "ways", ways.length, "market streets", streets.length, streets.map((s) => `${s.name}(${s.lamps.length})`).join(", "));
}
if (only.size && existsSync(prevFile)) {
  const m = readFileSync(prevFile, "utf8").match(/= (\{[\s\S]*\});\s*$/);
  if (m) for (const [k, v] of Object.entries(JSON.parse(m[1]!) as Record<string, MarketStreet[]>)) if (!(k in out)) out[k] = v;
}
const ordered = Object.fromEntries(Object.keys(CITIES).filter((k) => out[k]).map((k) => [k, out[k]]));
writeFileSync(
  prevFile,
  `// Generated by scripts/bake-market-streets.mts — do not edit by hand. Street data © OpenStreetMap contributors (ODbL), Overpass snapshot ${new Date().toISOString().slice(0, 10)}.\n` +
    `import type { MarketStreet } from "./nightMarket.ts";\nimport type { CityId } from "./types";\n\n` +
    `export const MARKET_STREETS: Partial<Record<CityId, MarketStreet[]>> = ${JSON.stringify(ordered)};\n`,
);
