"""Extra factual plates for gen-trivia-bank.py. Confirmed textbook / official facts."""
from __future__ import annotations


def ordn(n: int) -> str:
    if 10 <= n % 100 <= 20:
        suf = "th"
    else:
        suf = {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return f"{n}{suf}"


def apply(B) -> None:
    # --- Sports: stadiums (team not in prompt; stadium not in reverse if it names the city) ---
    NFL_STADIA = [
        ("Arizona Cardinals", "State Farm Stadium"),
        ("Atlanta Falcons", "Mercedes-Benz Stadium"),
        ("Baltimore Ravens", "M&T Bank Stadium"),
        ("Buffalo Bills", "Highmark Stadium"),
        ("Carolina Panthers", "Bank of America Stadium"),
        ("Chicago Bears", "Soldier Field"),
        ("Cincinnati Bengals", "Paycor Stadium"),
        ("Cleveland Browns", "Huntington Bank Field"),
        ("Dallas Cowboys", "AT&T Stadium"),
        ("Denver Broncos", "Empower Field at Mile High"),
        ("Detroit Lions", "Ford Field"),
        ("Green Bay Packers", "Lambeau Field"),
        ("Houston Texans", "NRG Stadium"),
        ("Indianapolis Colts", "Lucas Oil Stadium"),
        ("Jacksonville Jaguars", "EverBank Stadium"),
        ("Kansas City Chiefs", "Arrowhead Stadium"),
        ("Las Vegas Raiders", "Allegiant Stadium"),
        ("Los Angeles Chargers", "SoFi Stadium"),
        ("Los Angeles Rams", "SoFi Stadium"),
        ("Miami Dolphins", "Hard Rock Stadium"),
        ("Minnesota Vikings", "U.S. Bank Stadium"),
        ("New England Patriots", "Gillette Stadium"),
        ("New Orleans Saints", "Caesars Superdome"),
        ("New York Giants", "MetLife Stadium"),
        ("New York Jets", "MetLife Stadium"),
        ("Philadelphia Eagles", "Lincoln Financial Field"),
        ("Pittsburgh Steelers", "Acrisure Stadium"),
        ("San Francisco 49ers", "Levi's Stadium"),
        ("Seattle Seahawks", "Lumen Field"),
        ("Tampa Bay Buccaneers", "Raymond James Stadium"),
        ("Tennessee Titans", "Nissan Stadium"),
        ("Washington Commanders", "Northwest Stadium"),
    ]
    stadia = list(dict.fromkeys(s for _, s in NFL_STADIA))
    teams = [t for t, _ in NFL_STADIA]
    for team, stad in NFL_STADIA:
        B.mc("sports", f"Which NFL team plays at {stad}?", team, teams, 2)
        homes = [t for t, s in NFL_STADIA if s == stad]
        if len(homes) == 1:
            B.mc("sports", f"Where do the {team} play their home games?", stad, stadia, 2)

    NBA_ARENA = [
        ("Atlanta Hawks", "State Farm Arena"),
        ("Boston Celtics", "TD Garden"),
        ("Brooklyn Nets", "Barclays Center"),
        ("Chicago Bulls", "United Center"),
        ("Cleveland Cavaliers", "Rocket Arena"),
        ("Dallas Mavericks", "American Airlines Center"),
        ("Denver Nuggets", "Ball Arena"),
        ("Detroit Pistons", "Little Caesars Arena"),
        ("Golden State Warriors", "Chase Center"),
        ("Houston Rockets", "Toyota Center"),
        ("Indiana Pacers", "Gainbridge Fieldhouse"),
        ("Los Angeles Lakers", "Crypto.com Arena"),
        ("LA Clippers", "Intuit Dome"),
        ("Memphis Grizzlies", "FedExForum"),
        ("Miami Heat", "Kaseya Center"),
        ("Milwaukee Bucks", "Fiserv Forum"),
        ("Minnesota Timberwolves", "Target Center"),
        ("New York Knicks", "Madison Square Garden"),
        ("Oklahoma City Thunder", "Paycom Center"),
        ("Orlando Magic", "Kia Center"),
        ("Philadelphia 76ers", "Wells Fargo Center"),
        ("Phoenix Suns", "Mortgage Matchup Center"),
        ("Portland Trail Blazers", "Moda Center"),
        ("Sacramento Kings", "Golden 1 Center"),
        ("San Antonio Spurs", "Frost Bank Center"),
        ("Toronto Raptors", "Scotiabank Arena"),
        ("Utah Jazz", "Delta Center"),
        ("Washington Wizards", "Capital One Arena"),
    ]
    arenas = list(dict.fromkeys(a for _, a in NBA_ARENA))
    nba = [t for t, _ in NBA_ARENA]
    for team, ar in NBA_ARENA:
        B.mc("sports", f"Which NBA team plays at {ar}?", team, nba, 2)

    MLB_PARK = [
        ("Boston Red Sox", "Fenway Park"),
        ("Chicago Cubs", "Wrigley Field"),
        ("New York Yankees", "Yankee Stadium"),
        ("Los Angeles Dodgers", "Dodger Stadium"),
        ("San Francisco Giants", "Oracle Park"),
        ("St. Louis Cardinals", "Busch Stadium"),
        ("Baltimore Orioles", "Camden Yards"),
        ("Pittsburgh Pirates", "PNC Park"),
        ("Seattle Mariners", "T-Mobile Park"),
        ("Houston Astros", "Minute Maid Park"),
        ("Texas Rangers", "Globe Life Field"),
        ("Atlanta Braves", "Truist Park"),
        ("Philadelphia Phillies", "Citizens Bank Park"),
        ("Detroit Tigers", "Comerica Park"),
        ("Minnesota Twins", "Target Field"),
        ("Milwaukee Brewers", "American Family Field"),
        ("Cleveland Guardians", "Progressive Field"),
        ("Cincinnati Reds", "Great American Ball Park"),
        ("Kansas City Royals", "Kauffman Stadium"),
        ("Colorado Rockies", "Coors Field"),
        ("Arizona Diamondbacks", "Chase Field"),
        ("San Diego Padres", "Petco Park"),
        ("Miami Marlins", "loanDepot park"),
        ("Tampa Bay Rays", "Tropicana Field"),
        ("Toronto Blue Jays", "Rogers Centre"),
        ("New York Mets", "Citi Field"),
        ("Washington Nationals", "Nationals Park"),
        ("Chicago White Sox", "Rate Field"),
        ("Los Angeles Angels", "Angel Stadium"),
        ("Oakland Athletics", "Sutter Health Park"),
    ]
    parks = list(dict.fromkeys(p for _, p in MLB_PARK))
    mlb = [t for t, _ in MLB_PARK]
    for team, park in MLB_PARK:
        B.mc("sports", f"Which MLB team plays at {park}?", team, mlb, 2)

    SOCCER_CLUB = [
        ("Manchester United", "England"),
        ("Manchester City", "England"),
        ("Liverpool", "England"),
        ("Arsenal", "England"),
        ("Chelsea", "England"),
        ("Tottenham Hotspur", "England"),
        ("Real Madrid", "Spain"),
        ("FC Barcelona", "Spain"),
        ("Atlético Madrid", "Spain"),
        ("Juventus", "Italy"),
        ("AC Milan", "Italy"),
        ("Inter Milan", "Italy"),
        ("Bayern Munich", "Germany"),
        ("Borussia Dortmund", "Germany"),
        ("Paris Saint-Germain", "France"),
        ("Ajax", "the Netherlands"),
        ("Benfica", "Portugal"),
        ("Porto", "Portugal"),
        ("Celtic", "Scotland"),
        ("Rangers", "Scotland"),
        ("Boca Juniors", "Argentina"),
        ("River Plate", "Argentina"),
        ("Flamengo", "Brazil"),
        ("LAFC", "the United States"),
        ("Atlanta United", "the United States"),
        ("Inter Miami", "the United States"),
        ("Toronto FC", "Canada"),
        ("CF Montréal", "Canada"),
    ]
    nations = list(dict.fromkeys(n for _, n in SOCCER_CLUB))
    clubs = [c for c, _ in SOCCER_CLUB]
    for club, nation in SOCCER_CLUB:
        B.mc("sports", f"{club} is a soccer club based in which country?", nation, nations, 1)

    SPORTS_MORE = [
        ("A safety in American football is worth how many points?", "2", ["1", "2", "3", "6"], 1),
        ("An extra-point kick after a touchdown is worth how many points?", "1", ["1", "2", "3", "6"], 1),
        ("A two-point conversion in American football is worth…", "2", ["1", "2", "3", "6"], 1),
        ("A grand slam in baseball scores how many runs?", "4", ["2", "3", "4", "5"], 1),
        ("A triple-double in basketball means double figures in…", "three statistical categories", ["two categories", "three statistical categories", "only points", "four quarters"], 2),
        ("Icing in hockey is a stoppage for shooting the puck…", "the length of the ice from behind your own half, untouched", ["into the net", "the length of the ice from behind your own half, untouched", "at the goalie from the slot", "off the glass"], 3),
        ("A hat trick in soccer is…", "three goals by one player in a match", ["three assists", "three goals by one player in a match", "three yellow cards", "a bicycle kick"], 1),
        ("Offsides in soccer is judged from the…", "second-last defender (typically)", ["goalkeeper only", "second-last defender (typically)", "midfield line always", "corner flag"], 2),
        ("A red card in soccer means the player is…", "Sent off", ["Warned", "Sent off", "Substituted later", "Fined only"], 1),
        ("A yellow card in soccer is a…", "Caution", ["Send-off", "Caution", "Goal", "Penalty kick"], 1),
        ("Penalty kicks in soccer are taken from how many yards, in the Laws?", "12", ["6", "10", "12", "18"], 2),
        ("A cricket over is how many legal balls?", "6", ["4", "5", "6", "8"], 2),
        ("A rugby union scrum typically involves how many forwards per side?", "8", ["5", "6", "8", "15"], 3),
        ("The Davis Cup is a team event in…", "Tennis", ["Golf", "Tennis", "Cricket", "Rugby"], 2),
        ("The Fed Cup / Billie Jean King Cup is a team event in…", "Tennis", ["Soccer", "Tennis", "Hockey", "Swimming"], 2),
        ("The Walker Cup is a team event in…", "Amateur golf", ["Tennis", "Amateur golf", "Polo", "Sailing"], 3),
        ("NASCAR's most famous race is the…", "Daytona 500", ["Indy 500", "Daytona 500", "Monaco Grand Prix", "Le Mans only"], 1),
        ("The 24 Hours of Le Mans is a race of…", "Sports cars / endurance", ["Sprint horses", "Sports cars / endurance", "Motorcycles only", "Sailboats"], 2),
        ("MotoGP is a championship in…", "Motorcycle racing", ["Open-wheel cars", "Motorcycle racing", "Rally only", "Truck racing"], 2),
        ("The America's Cup boats race on…", "Water (sailing)", ["Snow", "Water (sailing)", "Tarmac only", "Ice tracks"], 1),
        ("A marathon's 26.2 miles come from the 1908 Olympic route to…", "the White City stadium in London", ["Athens only", "the White City stadium in London", "Boston", "Rome"], 3),
        ("The Boston Marathon is traditionally run on…", "Patriots' Day", ["New Year's Day", "Patriots' Day", "July 4", "Thanksgiving"], 2),
        ("A triathlon typically combines swim, bike, and…", "Run", ["Row", "Run", "Climb", "Shoot"], 1),
        ("An Ironman swim is…", "2.4 miles", ["400 meters", "2.4 miles", "10 miles", "a 50-meter pool sprint"], 3),
        ("The Tour de France is decided chiefly by…", "Time (general classification)", ["Sprint wins only", "Time (general classification)", "Team size", "Fan votes"], 2),
        ("A clean and jerk is a lift in…", "Weightlifting", ["Wrestling", "Weightlifting", "Archery", "Rowing"], 2),
        ("Judo and taekwondo are sports of…", "the Olympic program (combat)", ["motor racing", "the Olympic program (combat)", "equestrian only", "sailing"], 1),
        ("A perfect 10 was a famous score in…", "Artistic gymnastics", ["Diving only", "Artistic gymnastics", "Archery", "Shooting"], 2),
        ("The pentathlon's riding discipline is…", "Show jumping (in the modern event)", ["Dressage only", "Show jumping (in the modern event)", "Polo", "Steeplechase only"], 3),
        ("Lacrosse's historic roots are among…", "Indigenous peoples of North America", ["the Maori only", "Indigenous peoples of North America", "the Celts only", "the Polynesians only"], 2),
        ("Hurling is played with a stick called a…", "Hurley", ["Bat", "Hurley", "Crosse", "Mallet"], 3),
        ("Gaelic football is a sport of…", "Ireland", ["Scotland only", "Ireland", "Wales only", "Cornwall"], 2),
        ("Sepak takraw is a kick-volleyball sport of…", "Southeast Asia", ["the Andes", "Southeast Asia", "West Africa", "Scandinavia"], 3),
        ("Kabaddi is associated especially with…", "South Asia", ["the Alps", "South Asia", "the Caribbean", "Polynesia"], 2),
        ("The Heineken Cup / Champions Cup is a club competition in…", "Rugby union", ["Soccer only", "Rugby union", "Cricket", "Handball"], 3),
        ("Six Nations rugby includes England, France, Ireland, Italy, Scotland, and…", "Wales", ["Spain", "Wales", "Germany", "Portugal"], 2),
        ("The All Blacks are the national rugby team of…", "New Zealand", ["Australia", "New Zealand", "South Africa", "Samoa"], 1),
        ("The Springboks are the national rugby team of…", "South Africa", ["New Zealand", "South Africa", "Argentina", "Australia"], 2),
        ("The Wallabies are the national rugby team of…", "Australia", ["New Zealand", "Australia", "Fiji", "Tonga"], 2),
        ("Formula 1's Monaco Grand Prix is run in…", "Monte Carlo / Monaco", ["Nice", "Monte Carlo / Monaco", "Cannes", "Marseille"], 1),
        ("A pit stop in motorsport is for…", "Service, tires, fuel (as allowed)", ["a penalty only", "Service, tires, fuel (as allowed)", "the podium", "qualifying only"], 1),
        ("The yellow flag in motorsport generally means…", "Caution / no overtaking in that zone", ["Race over", "Caution / no overtaking in that zone", "Pit now", "False start"], 2),
        ("A checkered flag means…", "the race is finished", ["a caution", "the race is finished", "a penalty", "rain"], 1),
        ("The Stanley Cup is made of…", "Silver (with bands for winners)", ["Gold only", "Silver (with bands for winners)", "Bronze", "Crystal"], 2),
        ("How many teams make the NFL playoffs under the current 14-team format?", "14", ["12", "14", "16", "8"], 2),
        ("An MLB roster typically bats how many players in order, not counting the DH debate?", "9", ["7", "8", "9", "11"], 1),
        ("A shot clock in the NBA is how many seconds?", "24", ["12", "24", "30", "35"], 2),
        ("College basketball's shot clock is how many seconds (men's, current)?", "30", ["24", "30", "35", "45"], 3),
        ("A tennis set is typically first to how many games, win by two, with a tiebreak at 6–6?", "6", ["4", "6", "8", "10"], 1),
        ("Table tennis (ping-pong) games are typically first to…", "11", ["11", "15", "21 still always", "25"], 2),
        ("Badminton's shuttlecock is also called a…", "Birdie", ["Puck", "Birdie", "Wicket", "Quoit"], 1),
        ("A cricket 'duck' means a batter scored…", "0", ["0", "50", "100", "a six"], 2),
        ("A century in cricket is…", "100 runs by a batter", ["100 wickets", "100 runs by a batter", "100 overs", "100 sixes"], 2),
        ("The Invictus Games are for…", "Wounded, injured, and sick service personnel", ["only children", "Wounded, injured, and sick service personnel", "only horses", "only F1 drivers"], 3),
        ("The Paralympics are for…", "Athletes with disabilities", ["only winter sports", "Athletes with disabilities", "only youth", "only veterans of one country"], 1),
        ("Special Olympics is a movement for…", "Athletes with intellectual disabilities", ["only Olympians", "Athletes with intellectual disabilities", "only coaches", "only referees"], 2),
        ("The Ryder Cup pits the U.S. against…", "Europe", ["Asia", "Europe", "Australia", "Africa"], 1),
        ("The Presidents Cup in golf pits the U.S. against…", "an International team (non-Europe)", ["only Europe", "an International team (non-Europe)", "only Japan", "only Canada"], 3),
        ("A hole-in-one is most common on which kind of golf hole?", "Par 3", ["Par 3", "Par 4", "Par 5", "Par 6"], 1),
        ("Scramble is a format in…", "Golf", ["Boxing", "Golf", "Swimming", "Fencing"], 2),
        ("A scrum-half plays in…", "Rugby", ["Soccer", "Rugby", "Cricket", "Hockey"], 2),
        ("A libero is a specialist in…", "Volleyball", ["Tennis", "Volleyball", "Golf", "Baseball"], 2),
        ("A closer in baseball is usually a…", "Relief pitcher for the end of the game", ["Starting catcher", "Relief pitcher for the end of the game", "Utility infielder only", "Pinch-running coach"], 2),
        ("The Cy Young Award honors…", "Pitching", ["Hitting", "Pitching", "Fielding only", "Managing"], 2),
        ("The Hart Trophy is NHL…", "MVP", ["best goalie", "MVP", "best defenseman only", "rookie only"], 2),
        ("The Heisman is a bust of a…", "Football player in a pose", ["Horse", "Football player in a pose", "Basketball", "Boat"], 2),
        ("March Madness's Final Four is the last four teams in…", "the NCAA men's (and women's) basketball tournaments", ["the Super Bowl", "the NCAA men's (and women's) basketball tournaments", "the World Cup", "the Ryder Cup"], 1),
        ("A buzzer-beater is a shot…", "as time expires", ["in warmups", "as time expires", "from the bench", "before tip-off"], 1),
        ("A walk-off in baseball is a hit (or play) that…", "ends the game in the home half of the last inning", ["starts the 1st", "ends the game in the home half of the last inning", "is always a bunt", "is a rain delay"], 2),
        ("The saltire flag of Scotland is associated with which sport's Six Nations side?", "Scotland's rugby team (among others)", ["only curling", "Scotland's rugby team (among others)", "only shinty", "only F1"], 3),
    ]
    for prompt, ans, ch, d in SPORTS_MORE:
        B.add("sports", prompt, ch, ans, d)

    # --- Local / maps ---
    MORE_COUNTRIES = [
        ("Ghana", "Accra"), ("Ethiopia", "Addis Ababa"), ("Tanzania", "Dodoma"),
        ("Senegal", "Dakar"), ("Ivory Coast", "Yamoussoukro"), ("Uganda", "Kampala"),
        ("Tanzania's historic port city often named as the commercial capital", "Dar es Salaam"),
        ("Algeria", "Algiers"), ("Tunisia", "Tunis"), ("Libya", "Tripoli"),
        ("Sudan", "Khartoum"), ("Angola", "Luanda"), ("Mozambique", "Maputo"),
        ("Zimbabwe", "Harare"), ("Zambia", "Lusaka"), ("Botswana", "Gaborone"),
        ("Namibia", "Windhoek"), ("Madagascar", "Antananarivo"), ("Rwanda", "Kigali"),
        ("Cameroon", "Yaoundé"), ("DR Congo", "Kinshasa"), ("Republic of the Congo", "Brazzaville"),
        ("Cuba", "Havana"), ("Jamaica", "Kingston"), ("Haiti", "Port-au-Prince"),
        ("Dominican Republic", "Santo Domingo"), ("Puerto Rico (U.S. territory)", "San Juan"),
        ("Panama", "Panama City"), ("Costa Rica", "San José"), ("Guatemala", "Guatemala City"),
        ("Honduras", "Tegucigalpa"), ("Nicaragua", "Managua"), ("El Salvador", "San Salvador"),
        ("Bolivia (constitutional)", "Sucre"), ("Bolivia (administrative)", "La Paz"),
        ("Ecuador", "Quito"), ("Paraguay", "Asunción"), ("Uruguay", "Montevideo"),
        ("Venezuela", "Caracas"), ("Guyana", "Georgetown"),
        ("Bangladesh", "Dhaka"), ("Sri Lanka", "Sri Jayawardenepura Kotte"),
        ("Nepal", "Kathmandu"), ("Myanmar", "Naypyidaw"), ("Cambodia", "Phnom Penh"),
        ("Laos", "Vientiane"), ("Mongolia", "Ulaanbaatar"), ("Kazakhstan", "Astana"),
        ("Uzbekistan", "Tashkent"), ("Afghanistan", "Kabul"), ("Jordan", "Amman"),
        ("Lebanon", "Beirut"), ("Syria", "Damascus"), ("Qatar", "Doha"),
        ("United Arab Emirates", "Abu Dhabi"), ("Oman", "Muscat"), ("Kuwait", "Kuwait City"),
        ("Yemen", "Sana'a"), ("Bahrain", "Manama"),
        ("Iceland", "Reykjavík"), ("Luxembourg", "Luxembourg City"),
        ("Slovakia", "Bratislava"), ("Slovenia", "Ljubljana"), ("Croatia", "Zagreb"),
        ("Serbia", "Belgrade"), ("Romania", "Bucharest"), ("Bulgaria", "Sofia"),
        ("Lithuania", "Vilnius"), ("Latvia", "Riga"), ("Estonia", "Tallinn"),
        ("Belarus", "Minsk"), ("Georgia (the country)", "Tbilisi"), ("Armenia", "Yerevan"),
        ("Azerbaijan", "Baku"), ("Cyprus", "Nicosia"), ("Malta", "Valletta"),
        ("Papua New Guinea", "Port Moresby"), ("Fiji", "Suva"), ("Samoa", "Apia"),
    ]
    # filter the meta ones for mc
    simple = [(n, c) for n, c in MORE_COUNTRIES if "historic" not in n.lower() and "constitutional" not in n.lower() and "administrative" not in n.lower() and "territory" not in n.lower()]
    ccaps = [c for _, c in simple]
    cnames = [n for n, _ in simple]
    for n, c in simple:
        B.mc("local", f"What is the capital of {n}?", c, ccaps, 2)
        B.mc("local", f"{c} is the capital of which country?", n, cnames, 2)

    BIG_CITY = [
        ("Alabama", "Birmingham"), ("Alaska", "Anchorage"), ("Arizona", "Phoenix"),
        ("Arkansas", "Little Rock"), ("California", "Los Angeles"), ("Colorado", "Denver"),
        ("Connecticut", "Bridgeport"), ("Delaware", "Wilmington"), ("Florida", "Jacksonville"),
        ("Georgia", "Atlanta"), ("Hawaii", "Honolulu"), ("Idaho", "Boise"),
        ("Illinois", "Chicago"), ("Indiana", "Indianapolis"), ("Iowa", "Des Moines"),
        ("Kansas", "Wichita"), ("Kentucky", "Louisville"), ("Louisiana", "New Orleans"),
        ("Maine", "Portland"), ("Maryland", "Baltimore"), ("Massachusetts", "Boston"),
        ("Michigan", "Detroit"), ("Minnesota", "Minneapolis"), ("Mississippi", "Jackson"),
        ("Missouri", "Kansas City"), ("Montana", "Billings"), ("Nebraska", "Omaha"),
        ("Nevada", "Las Vegas"), ("New Hampshire", "Manchester"), ("New Jersey", "Newark"),
        ("New Mexico", "Albuquerque"), ("New York", "New York City"), ("North Carolina", "Charlotte"),
        ("North Dakota", "Fargo"), ("Ohio", "Columbus"), ("Oklahoma", "Oklahoma City"),
        ("Oregon", "Portland"), ("Pennsylvania", "Philadelphia"), ("Rhode Island", "Providence"),
        ("South Carolina", "Charleston"), ("South Dakota", "Sioux Falls"), ("Tennessee", "Nashville"),
        ("Texas", "Houston"), ("Utah", "Salt Lake City"), ("Vermont", "Burlington"),
        ("Virginia", "Virginia Beach"), ("Washington", "Seattle"), ("West Virginia", "Charleston"),
        ("Wisconsin", "Milwaukee"), ("Wyoming", "Cheyenne"),
    ]
    cities = [c for _, c in BIG_CITY]
    states = [s for s, _ in BIG_CITY]
    for st, city in BIG_CITY:
        B.mc("local", f"What is the most populous city in {st}?", city, cities, 2)

    NICK = [
        ("Alabama", "the Yellowhammer State"), ("Alaska", "the Last Frontier"),
        ("Arizona", "the Grand Canyon State"), ("Arkansas", "the Natural State"),
        ("California", "the Golden State"), ("Colorado", "the Centennial State"),
        ("Connecticut", "the Constitution State"), ("Delaware", "the First State"),
        ("Florida", "the Sunshine State"), ("Georgia", "the Peach State"),
        ("Hawaii", "the Aloha State"), ("Idaho", "the Gem State"),
        ("Illinois", "the Prairie State"), ("Indiana", "the Hoosier State"),
        ("Iowa", "the Hawkeye State"), ("Kansas", "the Sunflower State"),
        ("Kentucky", "the Bluegrass State"), ("Louisiana", "the Pelican State"),
        ("Maine", "the Pine Tree State"), ("Maryland", "the Old Line State"),
        ("Massachusetts", "the Bay State"), ("Michigan", "the Great Lakes State"),
        ("Minnesota", "the North Star State"), ("Mississippi", "the Magnolia State"),
        ("Missouri", "the Show-Me State"), ("Montana", "the Treasure State"),
        ("Nebraska", "the Cornhusker State"), ("Nevada", "the Silver State"),
        ("New Hampshire", "the Granite State"), ("New Jersey", "the Garden State"),
        ("New Mexico", "the Land of Enchantment"), ("New York", "the Empire State"),
        ("North Carolina", "the Tar Heel State"), ("North Dakota", "the Peace Garden State"),
        ("Ohio", "the Buckeye State"), ("Oklahoma", "the Sooner State"),
        ("Oregon", "the Beaver State"), ("Pennsylvania", "the Keystone State"),
        ("Rhode Island", "the Ocean State"), ("South Carolina", "the Palmetto State"),
        ("South Dakota", "the Mount Rushmore State"), ("Tennessee", "the Volunteer State"),
        ("Texas", "the Lone Star State"), ("Utah", "the Beehive State"),
        ("Vermont", "the Green Mountain State"), ("Virginia", "the Old Dominion"),
        ("Washington", "the Evergreen State"), ("West Virginia", "the Mountain State"),
        ("Wisconsin", "the Badger State"), ("Wyoming", "the Equality State"),
    ]
    nicks = [n for _, n in NICK]
    for st, nick in NICK:
        B.mc("local", f"{nick[0].upper() + nick[1:]} is the nickname of which U.S. state?", st, states, 1)
        B.mc("local", f"What is a traditional nickname of {st}?", nick, nicks, 2)

    RIVERS = [
        ("Nile", "Africa"), ("Amazon", "South America"), ("Yangtze", "Asia"),
        ("Mississippi", "North America"), ("Missouri", "North America"),
        ("Danube", "Europe"), ("Rhine", "Europe"), ("Volga", "Europe"),
        ("Ganges", "Asia"), ("Mekong", "Asia"), ("Congo", "Africa"),
        ("Niger", "Africa"), ("Murray", "Australia"), ("Darling", "Australia"),
        ("Colorado (the canyon one)", "North America"), ("Columbia", "North America"),
        ("Rio Grande", "North America"), ("Yukon", "North America"),
        ("Thames", "Europe"), ("Seine", "Europe"), ("Loire", "Europe"),
        ("Po", "Europe"), ("Tagus", "Europe"), ("Ebro", "Europe"),
        ("Tigris", "Asia"), ("Euphrates", "Asia"), ("Indus", "Asia"),
        ("Yellow (Huang He)", "Asia"), ("Brahmaputra", "Asia"),
        ("Orinoco", "South America"), ("Paraná", "South America"),
        ("Zambezi", "Africa"), ("Orange (in southern Africa)", "Africa"),
    ]
    continents = list(dict.fromkeys(c for _, c in RIVERS))
    for river, cont in RIVERS:
        B.mc("local", f"The {river} River is primarily in which continent?", cont, continents, 1)

    MOUNTAINS = [
        ("Everest", "Asia"), ("K2", "Asia"), ("Kangchenjunga", "Asia"),
        ("Denali", "North America"), ("Aconcagua", "South America"),
        ("Kilimanjaro", "Africa"), ("Elbrus", "Europe"), ("Mont Blanc", "Europe"),
        ("Matterhorn", "Europe"), ("Fuji", "Asia"), ("Rainier", "North America"),
        ("Whitney", "North America"), ("McKinley is another name historically used for", "Denali"),
        ("Vinson", "Antarctica"), ("Kosciuszko", "Australia"),
        ("Cook / Aoraki", "Oceania"), ("Erebus", "Antarctica"),
        ("Etna", "Europe"), ("Vesuvius", "Europe"), ("St. Helens", "North America"),
        ("Hood", "North America"), ("Shasta", "North America"),
        ("Pikes Peak", "North America"), ("Mitchell (highest of the U.S. East)", "North America"),
    ]
    # skip the McKinley meta
    for name, where in MOUNTAINS:
        if "another name" in name:
            continue
        B.mc("local", f"Mount {name} is in which continent?", where, ["Asia", "Africa", "Europe", "North America", "South America", "Antarctica", "Australia", "Oceania"], 2)

    LAKES = [
        ("Superior", "North America"), ("Michigan", "North America"),
        ("Huron", "North America"), ("Erie", "North America"), ("Ontario", "North America"),
        ("Baikal", "Asia"), ("Victoria", "Africa"), ("Tanganyika", "Africa"),
        ("Malawi / Nyasa", "Africa"), ("Caspian (a lake in all but name)", "Asia / Europe"),
        ("Titicaca", "South America"), ("Maracaibo", "South America"),
        ("Great Bear", "North America"), ("Great Slave", "North America"),
        ("Winnipeg", "North America"), ("Tahoe", "North America"),
        ("Crater (Oregon)", "North America"), ("Loch Ness", "Europe"),
        ("Como", "Europe"), ("Geneva / Léman", "Europe"),
        ("Dead Sea", "Asia"), ("Eyre", "Australia"),
    ]
    for lake, where in LAKES:
        B.mc("local", f"Lake {lake} is in which region?", where, [w for _, w in LAKES], 2)

    PARKS = [
        ("Yellowstone", "Wyoming (mostly)"), ("Yosemite", "California"),
        ("Grand Canyon", "Arizona"), ("Zion", "Utah"), ("Arches", "Utah"),
        ("Acadia", "Maine"), ("Everglades", "Florida"), ("Olympic", "Washington"),
        ("Glacier", "Montana"), ("Rocky Mountain", "Colorado"),
        ("Great Smoky Mountains", "Tennessee / North Carolina"),
        ("Denali (the park)", "Alaska"), ("Hawaii Volcanoes", "Hawaii"),
        ("Death Valley", "California / Nevada"), ("Joshua Tree", "California"),
        ("Sequoia", "California"), ("Redwood", "California"),
        ("Badlands", "South Dakota"), ("Theodore Roosevelt", "North Dakota"),
        ("Shenandoah", "Virginia"), ("Hot Springs", "Arkansas"),
        ("Mammoth Cave", "Kentucky"), ("Carlsbad Caverns", "New Mexico"),
        ("Big Bend", "Texas"), ("Saguaro", "Arizona"),
        ("Crater Lake", "Oregon"), ("Mount Rainier", "Washington"),
        ("Canyonlands", "Utah"), ("Bryce Canyon", "Utah"),
        ("Mesa Verde", "Colorado"), ("Petrified Forest", "Arizona"),
    ]
    wheres = list(dict.fromkeys(w for _, w in PARKS))
    for park, where in PARKS:
        B.mc("local", f"{park} National Park is chiefly in which U.S. state or pair of states?", where, wheres, 2)

    CA_PROV = [
        ("Ontario", "Toronto"), ("Quebec", "Quebec City"), ("British Columbia", "Victoria"),
        ("Alberta", "Edmonton"), ("Manitoba", "Winnipeg"), ("Saskatchewan", "Regina"),
        ("Nova Scotia", "Halifax"), ("New Brunswick", "Fredericton"),
        ("Newfoundland and Labrador", "St. John's"), ("Prince Edward Island", "Charlottetown"),
        ("Northwest Territories", "Yellowknife"), ("Yukon", "Whitehorse"), ("Nunavut", "Iqaluit"),
    ]
    pcaps = [c for _, c in CA_PROV]
    pnames = [n for n, _ in CA_PROV]
    for n, c in CA_PROV:
        B.mc("local", f"What is the capital of {n} (Canada)?", c, pcaps, 2)
        B.mc("political", f"{c} is the capital of which Canadian province or territory?", n, pnames, 2)

    AU = [
        ("New South Wales", "Sydney"), ("Victoria", "Melbourne"), ("Queensland", "Brisbane"),
        ("Western Australia", "Perth"), ("South Australia", "Adelaide"),
        ("Tasmania", "Hobart"), ("Australian Capital Territory", "Canberra"),
        ("Northern Territory", "Darwin"),
    ]
    acaps = [c for _, c in AU]
    anames = [n for n, _ in AU]
    for n, c in AU:
        B.mc("local", f"What is the capital of {n} (Australia)?", c, acaps, 2)

    GEO_MORE = [
        ("Which is the largest continent by land area?", "Asia", ["Africa", "Asia", "North America", "Antarctica"], 1),
        ("Which is the smallest continent by land area?", "Australia", ["Europe", "Australia", "Antarctica", "South America"], 1),
        ("Which continent has the most countries?", "Africa", ["Asia", "Africa", "Europe", "South America"], 2),
        ("The Prime Meridian is at how many degrees longitude?", "0", ["0", "90", "180", "23.5"], 1),
        ("A knot as a speed is…", "one nautical mile per hour", ["one mile per hour", "one nautical mile per hour", "one kilometer per hour", "one fathom per second"], 2),
        ("A fathom measures…", "Depth of water (about 6 feet)", ["Height of mountains", "Depth of water (about 6 feet)", "Wind", "Latitude only"], 2),
        ("A league, in old usage, was a measure of…", "Distance", ["Weight", "Distance", "Time", "Temperature"], 2),
        ("The Tropic of Capricorn is in which hemisphere?", "Southern", ["Northern", "Southern", "Only the Arctic", "Only the equator"], 2),
        ("Which desert is the largest hot desert?", "the Sahara", ["the Gobi", "the Sahara", "the Mojave", "the Kalahari"], 1),
        ("The largest desert including polar ice is…", "Antarctica", ["the Sahara", "Antarctica", "the Gobi", "the Arabian"], 2),
        ("The Atacama Desert is in…", "South America", ["Africa", "South America", "Australia", "Asia"], 2),
        ("The Kalahari is in…", "southern Africa", ["Australia", "southern Africa", "Mexico", "China"], 2),
        ("Patagonia is a region of…", "southern South America", ["Canada", "southern South America", "Siberia", "Alaska"], 2),
        ("Siberia is a vast region of…", "Russia", ["China", "Russia", "Canada", "Mongolia only"], 1),
        ("Scandinavia typically includes Norway, Sweden, and…", "Denmark", ["Finland only as a must", "Denmark", "Poland", "Germany"], 2),
        ("The Iberian Peninsula is Spain and…", "Portugal", ["Italy", "Portugal", "Greece", "Ireland"], 1),
        ("The Balkan Peninsula is in…", "southeastern Europe", ["western Europe", "southeastern Europe", "North Africa", "Central Asia"], 2),
        ("The Horn of Africa includes Ethiopia, Eritrea, Djibouti, and…", "Somalia", ["Morocco", "Somalia", "South Africa", "Sudan only"], 3),
        ("The Maghreb is a region of…", "Northwest Africa", ["East Africa", "Northwest Africa", "Southern Africa", "the Sahel only"], 3),
        ("The Sahel is a belt on the south edge of the…", "Sahara", ["Gobi", "Sahara", "Atacama", "Kalahari only"], 2),
        ("Oceania as a region includes Australia, New Zealand, and the…", "Pacific islands", ["Caribbean", "Pacific islands", "Indian Ocean only", "Arctic"], 1),
        ("Micronesia, Melanesia, and Polynesia are divisions of…", "the Pacific islands", ["the Caribbean", "the Pacific islands", "the Mediterranean", "the North Sea"], 2),
        ("The Coral Triangle is a marine region of…", "Southeast Asia / western Pacific", ["the Caribbean", "Southeast Asia / western Pacific", "the Mediterranean", "the Arctic"], 3),
        ("The Ring of Fire is a belt of…", "Volcanoes and earthquakes around the Pacific", ["tornadoes in the U.S. only", "Volcanoes and earthquakes around the Pacific", "hurricanes in the Atlantic only", "glaciers in Europe"], 2),
        ("A fjord is a…", "Glacially carved sea inlet", ["Desert wash", "Glacially carved sea inlet", "Coral atoll", "Lava tube"], 2),
        ("An atoll is a…", "Ring-shaped coral island", ["Mountain pass", "Ring-shaped coral island", "River island", "Sandbar in a lake only"], 2),
        ("A mesa is a…", "Flat-topped upland", ["Sinkhole", "Flat-topped upland", "Glacier", "Tide pool"], 2),
        ("A butte is similar to a mesa but…", "Narrower", ["Taller than Everest", "Narrower", "Always coastal", "Made of ice"], 2),
        ("Karst landscapes are shaped by…", "Dissolving of limestone (caves, sinkholes)", ["only wind", "Dissolving of limestone (caves, sinkholes)", "only lava", "only tides"], 3),
        ("A wadi is a…", "Usually dry watercourse, in arid lands", ["Glacial valley in Norway", "Usually dry watercourse, in arid lands", "Coral shelf", "Tundra pond"], 3),
        ("The rain shadow of a mountain is the…", "Drier side", ["Wetter side always", "Drier side", "Peak", "Foothill forest always"], 2),
        ("Trade winds in the tropics blow generally from the…", "East", ["West", "East", "North Pole only", "South Pole only"], 3),
        ("The jet stream is a…", "Fast high-altitude wind", ["Ocean current only", "Fast high-altitude wind", "Lava river", "Groundwater flow"], 2),
        ("El Niño is a climate pattern of the…", "tropical Pacific", ["North Atlantic only", "tropical Pacific", "Arctic only", "Mediterranean only"], 2),
        ("The Gulf Stream is a…", "Warm Atlantic current", ["Cold Pacific current", "Warm Atlantic current", "Desert wind", "Glacier"], 2),
        ("The Humboldt Current is a cold current off…", "western South America", ["eastern Australia", "western South America", "Norway", "Japan only"], 3),
        ("Which U.S. state has the most coastline, including islands?", "Alaska", ["Florida", "Alaska", "California", "Hawaii"], 2),
        ("Which Great Lake is the largest by surface area?", "Superior", ["Michigan", "Superior", "Erie", "Ontario"], 1),
        ("The Four Corners point is where Arizona, New Mexico, Colorado, and which state meet?", "Utah", ["Nevada", "Utah", "Texas", "Wyoming"], 2),
        ("Which U.S. state is the only one made of islands as its main land?", "Hawaii", ["Florida", "Hawaii", "Rhode Island", "Alaska"], 1),
        ("Which U.S. state touches the most other states?", "Tennessee (and Missouri, tied at 8)", ["Texas", "Tennessee (and Missouri, tied at 8)", "California", "New York"], 3),
        ("The Mason–Dixon line is associated with the border of…", "Pennsylvania and Maryland (historically)", ["Texas and Mexico", "Pennsylvania and Maryland (historically)", "Oregon and California", "Maine and Canada only"], 3),
        ("The 49th parallel is much of the border between the U.S. and…", "Canada", ["Mexico", "Canada", "Russia", "Greenland"], 1),
        ("The Rio Grande forms much of the border between Texas and…", "Mexico", ["New Mexico only", "Mexico", "Louisiana", "Oklahoma"], 1),
        ("The Continental Divide in the U.S. runs chiefly through the…", "Rockies", ["Appalachians", "Rockies", "Sierra only", "Cascades only"], 2),
        ("Appalachia is a region of which mountains?", "the Appalachians", ["the Rockies", "the Appalachians", "the Sierra Nevada", "the Cascades"], 1),
        ("The Piedmont is the plateau between the Appalachians and the…", "Atlantic coastal plain", ["Pacific", "Atlantic coastal plain", "Gulf only in Texas", "Great Lakes only"], 3),
        ("The Great Plains lie east of the…", "Rockies", ["Appalachians", "Rockies", "Sierra Nevada", "Cascades"], 1),
        ("The Midwest of the U.S. is often defined around…", "the Great Lakes and the prairie states", ["only New England", "the Great Lakes and the prairie states", "only the Deep South", "only the Pacific Coast"], 1),
        ("New England comprises Maine, New Hampshire, Vermont, Massachusetts, Rhode Island, and…", "Connecticut", ["New York", "Connecticut", "New Jersey", "Pennsylvania"], 2),
        ("The Deep South classically includes states such as…", "Mississippi, Alabama, Georgia, Louisiana, and South Carolina (among lists)", ["Oregon and Washington", "Mississippi, Alabama, Georgia, Louisiana, and South Carolina (among lists)", "only Alaska", "only Hawaii"], 2),
        ("The Sun Belt is a nickname for…", "the warm southern tier of the U.S.", ["the Arctic slope", "the warm southern tier of the U.S.", "New England winters", "the Great Lakes rust only"], 1),
        ("The Rust Belt is a nickname for…", "former industrial cities of the Great Lakes / Midwest", ["the desert Southwest", "former industrial cities of the Great Lakes / Midwest", "the Pacific Northwest timber only", "Florida tourism"], 2),
    ]
    for prompt, ans, ch, d in GEO_MORE:
        B.add("local", prompt, ch, ans, d)

    # --- Political ---
    PRESIDENTS = [
        "George Washington", "John Adams", "Thomas Jefferson", "James Madison", "James Monroe",
        "John Quincy Adams", "Andrew Jackson", "Martin Van Buren", "William Henry Harrison",
        "John Tyler", "James K. Polk", "Zachary Taylor", "Millard Fillmore", "Franklin Pierce",
        "James Buchanan", "Abraham Lincoln", "Andrew Johnson", "Ulysses S. Grant",
        "Rutherford B. Hayes", "James A. Garfield", "Chester A. Arthur", "Grover Cleveland",
        "Benjamin Harrison", "Grover Cleveland", "William McKinley", "Theodore Roosevelt",
        "William Howard Taft", "Woodrow Wilson", "Warren G. Harding", "Calvin Coolidge",
        "Herbert Hoover", "Franklin D. Roosevelt", "Harry S. Truman", "Dwight D. Eisenhower",
        "John F. Kennedy", "Lyndon B. Johnson", "Richard Nixon", "Gerald Ford",
        "Jimmy Carter", "Ronald Reagan", "George H. W. Bush", "Bill Clinton",
        "George W. Bush", "Barack Obama", "Donald Trump", "Joe Biden", "Donald Trump",
    ]
    # unique names for choices
    uniq = list(dict.fromkeys(PRESIDENTS))
    # number questions for first 45 unique slots - Grover Cleveland is 22 and 24
    # Ask "Who was the Nth U.S. President?" for 1-20, 25-45 carefully
    numbered = [
        (1, "George Washington"), (2, "John Adams"), (3, "Thomas Jefferson"),
        (4, "James Madison"), (5, "James Monroe"), (6, "John Quincy Adams"),
        (7, "Andrew Jackson"), (16, "Abraham Lincoln"), (18, "Ulysses S. Grant"),
        (26, "Theodore Roosevelt"), (28, "Woodrow Wilson"), (32, "Franklin D. Roosevelt"),
        (33, "Harry S. Truman"), (34, "Dwight D. Eisenhower"), (35, "John F. Kennedy"),
        (36, "Lyndon B. Johnson"), (37, "Richard Nixon"), (38, "Gerald Ford"),
        (39, "Jimmy Carter"), (40, "Ronald Reagan"), (41, "George H. W. Bush"),
        (42, "Bill Clinton"), (43, "George W. Bush"), (44, "Barack Obama"),
        (46, "Joe Biden"),
    ]
    for n, name in numbered:
        B.mc("political", f"Who was the {ordn(n)} U.S. President?", name, uniq, 1 if n <= 16 else 2)

    CIVICS_MORE = [
        ("The U.S. national anthem is…", "The Star-Spangled Banner", ["America the Beautiful", "The Star-Spangled Banner", "God Save the King", "Hail to the Chief"], 1),
        ("The U.S. motto on coins includes…", "In God We Trust", ["E Pluribus Unum only always", "In God We Trust", "Liberté, égalité", "Dieu et mon droit"], 1),
        ("E Pluribus Unum means…", "Out of many, one", ["In God we trust", "Out of many, one", "Always faithful", "To the stars"], 2),
        ("The U.S. national bird is the…", "Bald eagle", ["Turkey", "Bald eagle", "Hawk", "Owl"], 1),
        ("Washington, D.C. is not a…", "State", ["Capital", "State", "District", "Seat of government"], 1),
        ("How many voting members does Washington, D.C. have in the Senate?", "0", ["0", "1", "2", "3"], 2),
        ("Puerto Rico is a…", "U.S. territory", ["U.S. state", "U.S. territory", "independent country", "Canadian province"], 1),
        ("The U.S. has how many states?", "50", ["48", "49", "50", "52"], 1),
        ("Alaska and Hawaii became states in…", "1959", ["1867", "1898", "1959", "1976"], 2),
        ("The U.S. bought Alaska from…", "Russia", ["Britain", "Russia", "Canada", "Spain"], 2),
        ("The Louisiana Purchase was bought from…", "France", ["Spain", "France", "Britain", "Mexico"], 1),
        ("The Louisiana Purchase was completed under which president?", "Thomas Jefferson", ["Washington", "Thomas Jefferson", "Madison", "Monroe"], 2),
        ("Texas joined the Union in…", "1845", ["1836", "1845", "1861", "1876"], 2),
        ("California joined the Union in…", "1850", ["1846", "1848", "1850", "1860"], 2),
        ("The Missouri Compromise concerned…", "Slavery in new states / territories", ["tariffs only", "Slavery in new states / territories", "the navy only", "Indian removal only"], 2),
        ("The Three-Fifths Compromise counted enslaved people as three-fifths for…", "Representation and taxation", ["the draft only", "Representation and taxation", "the Senate only", "treaties"], 3),
        ("The Great Compromise created…", "a House by population and a Senate with equal states", ["the Electoral College only", "a House by population and a Senate with equal states", "judicial review", "the Cabinet"], 2),
        ("Checks and balances means…", "each branch can limit the others", ["the president is unchecked", "each branch can limit the others", "states cannot legislate", "courts cannot hear cases"], 1),
        ("A pocket veto is when a president…", "lets a bill die by not signing as Congress adjourns", ["signs with a note", "lets a bill die by not signing as Congress adjourns", "asks the Court first", "calls a referendum"], 3),
        ("Cloture is a vote to…", "end a filibuster", ["start a war", "end a filibuster", "confirm a judge only", "impeach"], 3),
        ("The elastic clause is also called the…", "Necessary and Proper Clause", ["Commerce Clause only", "Necessary and Proper Clause", "Supremacy Clause only", "Emoluments Clause"], 3),
        ("The Supremacy Clause says…", "federal law outranks conflicting state law", ["states outrank treaties", "federal law outranks conflicting state law", "cities outrank Congress", "the Court outranks the Constitution"], 2),
        ("Posse comitatus, in U.S. law, limits…", "using the army as domestic police", ["free speech", "using the army as domestic police", "taxes", "immigration courts"], 3),
        ("Habeas corpus is the right to…", "challenge unlawful detention in court", ["bear arms", "challenge unlawful detention in court", "a free press only", "vote in primaries"], 2),
        ("Double jeopardy means you generally cannot be…", "tried twice for the same offense by the same sovereign", ["taxed twice", "tried twice for the same offense by the same sovereign", "drafted twice", "impeached twice"], 2),
        ("Eminent domain is the power to…", "take private property for public use with just compensation", ["ban speech", "take private property for public use with just compensation", "draft only", "print money only"], 2),
        ("A grand jury decides whether to…", "indict", ["convict at trial", "indict", "sentence", "pardon"], 2),
        ("A petit jury is the…", "trial jury", ["grand jury", "trial jury", "Senate", "Cabinet"], 3),
        ("The Solicitor General argues for the U.S. before the…", "Supreme Court", ["House", "Supreme Court", "UN only", "state houses"], 3),
        ("NASA is an agency of the…", "U.S. federal government", ["UN", "U.S. federal government", "EU", "NATO command"], 1),
        ("The EPA's job is chiefly…", "environmental protection", ["tax collection", "environmental protection", "foreign treaties", "the census"], 1),
        ("The FDA regulates…", "food and drugs (among other products)", ["only cars", "food and drugs (among other products)", "only parks", "only schools"], 1),
        ("The CDC is concerned with…", "public health", ["the mint", "public health", "national forests", "passports"], 1),
        ("The Federal Reserve is the U.S.…", "central bank", ["tax court", "central bank", "post office", "park service"], 1),
        ("FOMC meetings set…", "U.S. monetary-policy rates (chiefly)", ["the income-tax brackets", "U.S. monetary-policy rates (chiefly)", "the minimum wage directly", "tariffs"], 2),
        ("NATO was founded in…", "1949", ["1918", "1945", "1949", "1991"], 2),
        ("The Warsaw Pact was a counterpart to NATO led by…", "the Soviet Union", ["China", "the Soviet Union", "Yugoslavia only", "France"], 2),
        ("The Security Council's five permanent members are China, France, Russia, the U.K., and…", "the United States", ["Germany", "the United States", "Japan", "India"], 2),
        ("The International Criminal Court sits in…", "The Hague", ["New York", "The Hague", "Geneva", "Brussels"], 3),
        ("The World Health Organization is a…", "UN specialized agency", ["NATO command", "UN specialized agency", "EU parliament", "U.S. Cabinet department"], 2),
        ("UNESCO is concerned with…", "education, science, and culture", ["only war crimes", "education, science, and culture", "only banking", "only fisheries"], 2),
        ("The World Bank and IMF are based in…", "Washington, D.C.", ["New York", "Washington, D.C.", "London", "Paris"], 3),
        ("OPEC is an organization of…", "oil-exporting countries", ["wheat exporters", "oil-exporting countries", "nuclear states only", "island nations only"], 2),
        ("The G7 is a group of…", "large advanced economies", ["all UN members", "large advanced economies", "only African states", "only city-states"], 2),
        ("The Commonwealth realm shares a…", "monarch (in those that remain realms)", ["single parliament", "monarch (in those that remain realms)", "single currency always", "single army"], 3),
        ("The UK Parliament sits in…", "Westminster, London", ["Edinburgh only", "Westminster, London", "Cardiff only", "Belfast only"], 1),
        ("Scotland's devolved parliament sits in…", "Edinburgh", ["Glasgow", "Edinburgh", "Aberdeen", "London only"], 2),
        ("The Good Friday Agreement concerns peace in…", "Northern Ireland", ["the Falklands", "Northern Ireland", "Gibraltar", "Wales"], 2),
        ("Brexit was the U.K.'s withdrawal from…", "the European Union", ["NATO", "the European Union", "the UN", "the Commonwealth"], 1),
        ("Mexico is a…", "federal republic", ["commonwealth of the U.K.", "federal republic", "U.S. state", "absolute monarchy"], 1),
        ("The head of government in the U.K. is the…", "Prime Minister", ["President", "Prime Minister", "Speaker only", "Lord Mayor of London"], 1),
        ("The head of state in the U.K. is the…", "Monarch", ["Prime Minister", "Monarch", "Lord Chancellor", "Archbishop of Canterbury"], 1),
        ("A coalition government is formed when…", "no single party has a majority and parties share power", ["one party wins all seats", "no single party has a majority and parties share power", "the army rules", "courts write laws"], 2),
        ("Proportional representation awards seats roughly by…", "share of the vote", ["first past the post only", "share of the vote", "lot", "age"], 2),
        ("First-past-the-post means the winner is…", "whoever has the most votes in the district, even without a majority", ["whoever has 50%+1 always", "whoever has the most votes in the district, even without a majority", "whoever the court picks", "whoever is oldest"], 2),
        ("A referendum is a…", "direct popular vote on a question", ["cabinet meeting", "direct popular vote on a question", "court order", "treaty only"], 1),
        ("An autocracy concentrates power in…", "one person", ["many parties", "one person", "a free press", "local juries"], 1),
        ("An oligarchy is rule by…", "a small group", ["all adults equally", "a small group", "lot from the whole people", "a single year-king"], 2),
        ("The Universal Declaration of Human Rights was adopted in…", "1948", ["1919", "1945", "1948", "1966"], 3),
        ("Amnesty International is an organization that campaigns for…", "human rights", ["tariffs", "human rights", "sports scores", "currency"], 1),
        ("The Red Cross / Red Crescent is known for…", "humanitarian aid and the laws of war", ["banking", "humanitarian aid and the laws of war", "oil", "spaceflight"], 1),
    ]
    for prompt, ans, ch, d in CIVICS_MORE:
        B.add("political", prompt, ch, ans, d)

    # --- Food ---
    DISHES_MORE = [
        ("bánh xèo", "Vietnam"), ("larb", "Laos / Isan"), ("khao soi", "northern Thailand / Myanmar"),
        ("rendang", "Indonesia / Minangkabau"), ("adobo", "the Philippines"),
        ("leche flan", "the Philippines / Spain's flan family"), ("halo-halo", "the Philippines"),
        ("okonomiyaki", "Japan"), ("takoyaki", "Japan"), ("tonkatsu", "Japan"),
        ("bibimbap", "Korea"), ("tteokbokki", "Korea"), ("samgyeopsal", "Korea"),
        ("hot pot", "China"), ("xiaolongbao", "China"), ("char siu", "China"),
        ("congee", "China and neighbors"), ("roti canai", "Malaysia"),
        ("bak kut teh", "Malaysia / Singapore"), ("chili crab", "Singapore"),
        ("kottu", "Sri Lanka"), ("hoppers", "Sri Lanka"), ("dal bhat", "Nepal"),
        ("momos", "Tibet / Nepal / the Himalaya"), ("thukpa", "Tibet / the Himalaya"),
        ("plov", "Central Asia"), ("laghman", "Central Asia"), ("khachapuri", "Georgia"),
        ("khinkali", "Georgia"), ("borscht with pampushky", "Ukraine"),
        ("bigos", "Poland"), ("żurek", "Poland"), ("svíčková", "Czechia"),
        ("goulash soup", "Hungary"), ("palatschinken", "Central Europe"),
        ("wiener schnitzel", "Austria"), ("käsespätzle", "Germany / Austria"),
        ("currywurst", "Germany"), (" moules-frites", "Belgium"),
        ("carbonara", "Italy"), ("cacio e pepe", "Italy"), ("osso buco", "Italy"),
        ("saltimbocca", "Italy"), ("pesto alla genovese", "Italy"),
        ("bouillabaisse", "France"), ("cassoulet", "France"), ("coq au vin", "France"),
        ("ratatouille", "France"), ("quiche Lorraine", "France"),
        ("gazpacho", "Spain"), ("jamón ibérico", "Spain"), ("pintxos", "the Basque Country"),
        ("pastéis de nata", "Portugal"), ("bacalhau", "Portugal"),
        ("moussaka", "Greece"), ("souvlaki", "Greece"), ("spanakopita", "Greece"),
        ("shakshuka", "North Africa / the Levant"), ("couscous royal", "the Maghreb"),
        ("harira", "Morocco"), ("brik", "Tunisia"), ("koshari", "Egypt"),
        ("ful medames", "Egypt / Sudan"), ("injera with doro wat", "Ethiopia / Eritrea"),
        ("jollof", "West Africa"), ("egusi soup", "West Africa"), ("bunny chow", "South Africa"),
        ("bobotie", "South Africa"), ("bunny-style curry bread", "South Africa"),
        ("pão de queijo", "Brazil"), ("brigadeiro", "Brazil"), ("feijoada", "Brazil"),
        ("churrasco", "southern Brazil / Uruguay"), ("choripán", "Argentina"),
        ("humita", "the Andes"), ("lomo saltado", "Peru"), ("ajiaco", "Colombia"),
        ("bandeja paisa", "Colombia"), ("pabellón criollo", "Venezuela"),
        ("ropa vieja", "Cuba"), ("mofongo", "Puerto Rico"), ("mains of jerk", "Jamaica"),
        ("ackee and saltfish", "Jamaica"), ("bake and shark", "Trinidad"),
        ("poutine with foie", "Quebec (a fancy take)"), ("tourtière", "Quebec"),
        ("butter tarts", "Canada"), (" Nanaimo bars", "Canada"),
        ("cioppino", "San Francisco"), ("Hangtown fry", "California Gold Country"),
        ("Dungeness crab", "the West Coast"), ("Olympia oyster", "the Pacific Northwest"),
        ("green chile stew", "New Mexico"), ("Navajo taco / frybread", "the Southwest"),
        (" Cincinnati chili", "Cincinnati"), ("goetta", "Cincinnati"),
        ("St. Louis gooey butter cake", "St. Louis"), ("toasted ravioli", "St. Louis"),
        ("Detroit-style pizza", "Detroit"), ("buffalo wings", "Buffalo"),
        ("beef on weck", "Buffalo"), ("whoopie pie", "New England / Pennsylvania"),
        ("lobster roll", "New England"), ("clam cake", "Rhode Island"),
        ("split-top hot dog", "New England"), ("Italian beef", "Chicago"),
        ("jibarito", "Chicago"), ("tamale trail", "the Mississippi Delta"),
        ("hot chicken", "Nashville"), ("meat-and-three", "the South"),
        ("shrimp and grits", "the Lowcountry"), ("she-crab soup", "Charleston"),
        ("boiled peanuts", "the South"), ("hushpuppies", "the South"),
        ("chess pie", "the South"), ("banana pudding", "the South"),
        ("king cake", "the Gulf / Carnival belt"), ("beignets", "New Orleans"),
        ("muffuletta", "New Orleans"), ("po' boy", "New Orleans"),
        ("crawfish étouffée", "Louisiana"), ("boudin", "Louisiana"),
        ("kolaches", "Texas Czech country"), ("fajitas", "Texas / the border"),
        ("breakfast tacos", "Texas"), ("Whataburger lore", "Texas"),
    ]
    origins = list(dict.fromkeys(o.strip() for _, o in DISHES_MORE))
    for dish, origin in DISHES_MORE:
        d = dish.strip()
        B.mc("food", f"{d[0].upper() + d[1:]} is most associated with which place?", origin.strip(), origins, 2)

    FOOD_MORE = [
        ("A Roux's fat is classically…", "Butter or oil (or other fat)", ["only water", "Butter or oil (or other fat)", "only vinegar", "only soy"], 1),
        ("Béchamel is milk thickened with…", "a white roux", ["cornstarch only always", "a white roux", "egg yolks only", "gelatin only"], 2),
        ("Velouté is stock thickened with…", "a blond roux", ["chocolate", "a blond roux", "fruit", "coffee"], 2),
        ("Espagnole is a brown…", "mother sauce", ["cheese", "mother sauce", "pastry", "tea"], 3),
        ("A gastrique is…", "caramelized sugar deglazed with vinegar", ["a raw salad", "caramelized sugar deglazed with vinegar", "a smoked fish", "a dumpling"], 3),
        ("Deglazing uses liquid to lift…", "browned bits from a pan", ["only steam", "browned bits from a pan", "only ice", "only salt crust"], 2),
        ("A mirepoix is classically…", "onion, carrot, and celery", ["garlic only", "onion, carrot, and celery", "tomato only", "ginger and scallion only"], 2),
        ("The Cajun 'holy trinity' is…", "onion, celery, and bell pepper", ["onion, carrot, celery", "onion, celery, and bell pepper", "garlic, ginger, chile", "leek and fennel"], 2),
        ("Sofrito, in many Spanish and Latin kitchens, starts with…", "aromatics fried in oil", ["only raw herbs", "aromatics fried in oil", "only sugar", "only cream"], 2),
        ("Dashi is a stock of…", "kelp and often bonito", ["beef bones only", "kelp and often bonito", "chicken only", "lamb only"], 2),
        ("Fish sauce is a staple of…", "Southeast Asian cooking", ["only Iceland", "Southeast Asian cooking", "only Peru", "only Scotland"], 1),
        ("Gochujang is a…", "Korean chile paste", ["Japanese soy", "Korean chile paste", "Thai curry powder", "Chinese vinegar"], 2),
        ("Miso soup's base is often…", "dashi with miso", ["cream", "dashi with miso", "tomato", "beer"], 1),
        ("A croissant is a…", "laminated Viennoiserie", ["choux puff only", "laminated Viennoiserie", "phyllo only", "brioche doughnut only"], 2),
        ("Choux pastry is used for…", "éclairs and cream puffs", ["baguettes", "éclairs and cream puffs", "pizza", "tortillas"], 2),
        ("Puff pastry's lift comes from…", "steam between butter layers", ["yeast only", "steam between butter layers", "baking soda only", "eggs only"], 2),
        ("A pie's lattice is a…", "woven pastry top", ["meringue only", "woven pastry top", "crumb only", "fondant only"], 1),
        ("Blind baking means…", "pre-baking a crust, often with weights", ["baking in the dark", "pre-baking a crust, often with weights", "not using an oven", "frying a crust"], 2),
        ("A water bath (bain-marie) is used to…", "cook gently and evenly, often custards", ["deep-fry", "cook gently and evenly, often custards", "smoke meat", "freeze"], 2),
        ("Tempering chocolate means…", "controlling crystal form for snap and shine", ["adding water", "controlling crystal form for snap and shine", "boiling it", "freezing it first always"], 3),
        ("Blooming gelatin means…", "soaking it in liquid before melting", ["burning it", "soaking it in liquid before melting", "whipping it dry", "freezing it"], 3),
        ("Proofing dough is…", "letting yeast dough rise", ["cutting it", "letting yeast dough rise", "freezing it", "frying it"], 1),
        ("Autolyse is a rest of flour and water…", "before salt and yeast are fully mixed in (in some breads)", ["after baking", "before salt and yeast are fully mixed in (in some breads)", "only for fried dough", "only for pastry cream"], 3),
        ("A preferment such as poolish is…", "a yeasted starter dough", ["a cheese", "a yeasted starter dough", "a glaze", "a cut of beef"], 3),
        ("Kosher salt is often preferred in kitchens because…", "its flakes are easy to pinch and it lacks iodine's bite (in many brands)", ["it is sweeter", "its flakes are easy to pinch and it lacks iodine's bite (in many brands)", "it is MSG", "it is sugar"], 2),
        ("Iodized table salt was iodized to prevent…", "goiter / iodine deficiency", ["scurvy", "goiter / iodine deficiency", "rickets only", "beriberi"], 3),
        ("Scurvy is a lack of…", "vitamin C", ["vitamin D", "vitamin C", "iron only", "calcium only"], 2),
        ("Rickets is associated with a lack of…", "vitamin D (and calcium/phosphate)", ["vitamin C", "vitamin D (and calcium/phosphate)", "vitamin K only", "B12 only"], 3),
        ("Fortified milk in the U.S. often has added…", "vitamin D", ["vitamin C only", "vitamin D", "iodine only", "fluoride only"], 2),
        ("A calorie-free on a U.S. label can still mean up to…", "fewer than 5 calories per serving", ["exactly 0 always", "fewer than 5 calories per serving", "50 calories", "100 calories"], 3),
        ("USDA organic on food means…", "certified production rules were followed", ["it was grown on the Moon", "certified production rules were followed", "it has no calories", "it is always raw"], 2),
        ("A DOP or AOP label on European food marks…", "a protected place of origin", ["a calorie count", "a protected place of origin", "a kosher seal only", "a vegan seal only"], 3),
        ("Champagne can legally use that name, in the EU sense, only if it is from…", "Champagne, France", ["any sparkling wine", "Champagne, France", "California only", "Catalonia"], 1),
        ("Cognac is a brandy from…", "the Cognac region of France", ["Scotland", "the Cognac region of France", "Kentucky", "Jerez"], 2),
        ("Bourbon is a whiskey associated with…", "the United States (especially Kentucky)", ["Scotland only", "the United States (especially Kentucky)", "Ireland only", "Japan only"], 1),
        ("Scotch whisky must be made in…", "Scotland", ["Ireland", "Scotland", "Canada", "Kentucky"], 1),
        ("Irish whiskey is typically distilled in…", "Ireland", ["Scotland only", "Ireland", "Wales only", "Brittany"], 1),
        ("Sake is a brew of…", "rice", ["barley only", "rice", "agave", "grapes"], 1),
        ("Soju is a spirit associated with…", "Korea", ["Japan only", "Korea", "China only", "Vietnam only"], 2),
        ("Baijiu is a spirit of…", "China", ["Japan", "China", "Korea", "Mongolia only"], 2),
        ("Mezcal is made from…", "agave (often smoked)", ["wheat", "agave (often smoked)", "potatoes", "honey only"], 2),
        ("Rum is typically distilled from…", "sugarcane products", ["agave", "sugarcane products", "barley only", "juniper"], 1),
        ("Gin is flavored with…", "juniper (and other botanicals)", ["only orange", "juniper (and other botanicals)", "only peat", "only honey"], 1),
        ("Absinthe's historic botanicals include…", "wormwood, anise, and fennel", ["only hops", "wormwood, anise, and fennel", "only cacao", "only chile"], 3),
        ("Hops bitter and preserve…", "Beer", ["Wine", "Beer", "Milk", "Oil"], 1),
        ("Lager yeast ferments…", "cooler, often at the bottom", ["only in bottles of wine", "cooler, often at the bottom", "only in whiskey barrels", "only in yogurt"], 2),
        ("Ale yeast ferments…", "warmer, often at the top", ["only in the Arctic", "warmer, often at the top", "only in soy", "only in vinegar"], 2),
        ("A stout is a…", "dark beer style", ["white wine", "dark beer style", "cider", "sake"], 1),
        ("IPA stands for…", "India Pale Ale", ["Irish Pilsner Ale", "India Pale Ale", "Italian Pale Amaro", "Iced Pale Apéritif"], 2),
        ("A pilsner originated in…", "Plzeň (Pilsen), Bohemia", ["Dublin", "Plzeň (Pilsen), Bohemia", "Munich only", "London"], 3),
        ("Lambic beers are fermented with…", "wild yeasts, in the Brussels region tradition", ["only lager yeast in a lab always", "wild yeasts, in the Brussels region tradition", "only bacteria in yogurt", "no microbes"], 3),
        ("Kombucha is fermented…", "tea", ["milk only", "tea", "meat", "oil"], 1),
        ("Kefir is a fermented…", "milk (or water kefir from sugar water)", ["soy sauce", "milk (or water kefir from sugar water)", "wine must only", "coffee only"], 2),
        ("Yogurt is milk fermented by…", "bacteria", ["only mold", "bacteria", "only yeast in hops", "only enzymes in pineapple"], 1),
        ("A blue cheese is inoculated with…", "Penicillium molds", ["only salt", "Penicillium molds", "only smoke", "only honey"], 2),
        ("Swiss-style holes in cheese come from…", "gas from bacteria (e.g. Propionibacterium)", ["mice", "gas from bacteria (e.g. Propionibacterium)", "needles only", "aging in space"], 3),
        ("Halloumi is a cheese that…", "squeaks and can be grilled", ["melts like mozzarella always", "squeaks and can be grilled", "is always blue", "is a nut cheese only"], 2),
        ("Burrata is mozzarella with a…", "cream-stracciatella heart", ["blue vein", "cream-stracciatella heart", "smoked rind only", "holey interior only"], 2),
        ("Ricotta is traditionally made from…", "whey", ["only aged cheddar rinds", "whey", "only soy", "only almond milk"], 2),
        ("Paneer is a…", "fresh acid-set cheese of South Asia", ["blue French cheese", "fresh acid-set cheese of South Asia", "Swiss mountain cheese", "Dutch Gouda"], 2),
        ("Halloumi is associated with…", "Cyprus", ["Scotland", "Cyprus", "Denmark", "Vermont"], 2),
        ("Manchego is a cheese of…", "Spain", ["Italy", "Spain", "Greece", "France"], 2),
        ("Gouda is a cheese of…", "the Netherlands", ["Belgium", "the Netherlands", "Germany only", "Austria"], 1),
        ("Emmental is a cheese of…", "Switzerland", ["France only", "Switzerland", "Italy", "the U.K."], 2),
        ("Stilton is a blue cheese of…", "England", ["Scotland only", "England", "Ireland only", "Wales only"], 2),
        ("A tasting menu is…", "a sequence of small courses", ["an all-you-can-eat buffet", "a sequence of small courses", "a single sandwich", "a grocery list"], 1),
        ("Mise en place means…", "everything in its place (prep ready)", ["table for two", "everything in its place (prep ready)", "check please", "on the house"], 2),
        ("A sommelier specializes in…", "wine (and often beverages)", ["pastry only", "wine (and often beverages)", "butchery only", "coffee roasting only"], 1),
        ("A barista specializes in…", "coffee drinks", ["wine only", "coffee drinks", "cheese only", "bread only"], 1),
        ("A patissier is a…", "pastry cook", ["grill cook", "pastry cook", "fishmonger", "sommelier"], 1),
        ("A saucier is the station for…", "sauces (in a classical brigade)", ["only salads", "sauces (in a classical brigade)", "only ice cream", "only bread"], 3),
        ("The brigade de cuisine was codified by…", "Escoffier (after hotel practice)", ["Careme only as a baker", "Escoffier (after hotel practice)", "Child only", "Pepin only"], 3),
    ]
    for prompt, ans, ch, d in FOOD_MORE:
        B.add("food", prompt, ch, ans, d)

    # --- Arts ---
    BOOKS_MORE = [
        ("The Canterbury Tales", "Chaucer"),
        ("Beowulf", "an anonymous Old English poet"),
        ("Paradise Lost", "Milton"),
        ("Gulliver's Travels", "Swift"),
        ("Robinson Crusoe", "Defoe"),
        ("Emma", "Jane Austen"),
        ("Sense and Sensibility", "Jane Austen"),
        ("Great Expectations", "Dickens"),
        ("A Tale of Two Cities", "Dickens"),
        ("Oliver Twist", "Dickens"),
        ("Jane Eyre", "Charlotte Brontë"),
        ("The Picture of Dorian Gray", "Oscar Wilde"),
        ("Dr. Jekyll and Mr. Hyde", "Stevenson"),
        ("Treasure Island", "Stevenson"),
        ("Heart of Darkness", "Conrad"),
        ("Mrs Dalloway", "Woolf"),
        ("To the Lighthouse", "Woolf"),
        ("Ulysses", "Joyce"),
        ("Dubliners", "Joyce"),
        ("The Waste Land", "T. S. Eliot"),
        ("Leaves of Grass", "Whitman"),
        ("The Scarlet Letter", "Hawthorne"),
        ("Walden", "Thoreau"),
        ("Little Women", "Alcott"),
        ("The Call of the Wild", "London"),
        ("The Grapes of Wrath", "Steinbeck"),
        ("Of Mice and Men", "Steinbeck"),
        ("East of Eden", "Steinbeck"),
        ("As I Lay Dying", "Faulkner"),
        ("The Sound and the Fury", "Faulkner"),
        ("Beloved", "Toni Morrison"),
        ("Song of Solomon", "Toni Morrison"),
        ("The Color Purple", "Alice Walker"),
        ("Go Tell It on the Mountain", "James Baldwin"),
        ("Native Son", "Richard Wright"),
        ("The Autobiography of Malcolm X", "Haley / Malcolm X"),
        ("Slaughterhouse-Five", "Vonnegut"),
        ("Catch-22", "Heller"),
        ("On the Road", "Kerouac"),
        ("Howl", "Ginsberg"),
        ("The Bell Jar", "Plath"),
        ("A Visit from the Goon Squad", "Jennifer Egan"),
        ("The Brief Wondrous Life of Oscar Wao", "Díaz"),
        ("Never Let Me Go", "Ishiguro"),
        ("The Remains of the Day", "Ishiguro"),
        ("Midnight's Children", "Rushdie"),
        ("The God of Small Things", "Arundhati Roy"),
        ("White Teeth", "Zadie Smith"),
        ("Americanah", "Adichie"),
        ("Half of a Yellow Sun", "Adichie"),
        ("The Kite Runner", "Hosseini"),
        ("Life of Pi", "Martel"),
        ("The Handmaid's Tale", "Atwood"),
        ("Oryx and Crake", "Atwood"),
        ("The Road", "McCarthy"),
        ("Blood Meridian", "McCarthy"),
        ("No Country for Old Men", "McCarthy"),
        ("The Overstory", "Powers"),
        ("Station Eleven", "Mandel"),
        ("The Left Hand of Darkness", "Le Guin"),
        ("A Wizard of Earthsea", "Le Guin"),
        ("Dune", "Herbert"),
        ("Foundation", "Asimov"),
        ("Neuromancer", "Gibson"),
        ("The Hitchhiker's Guide to the Galaxy", "Adams"),
        ("Good Omens", "Pratchett and Gaiman"),
        ("American Gods", "Gaiman"),
        ("The Name of the Rose", "Eco"),
        ("Foucault's Pendulum", "Eco"),
        ("The Master and Margarita", "Bulgakov"),
        ("Doctor Zhivago", "Pasternak"),
        ("The Gulag Archipelago", "Solzhenitsyn"),
        ("One Day in the Life of Ivan Denisovich", "Solzhenitsyn"),
        ("The Unbearable Lightness of Being", "Kundera"),
        ("The Tin Drum", "Grass"),
        ("All Quiet on the Western Front", "Remarque"),
        ("The Trial", "Kafka"),
        ("The Metamorphosis", "Kafka"),
        ("The Stranger", "Camus"),
        ("The Plague", "Camus"),
        ("Nausea", "Sartre"),
        ("Waiting for Godot", "Beckett"),
        ("No Exit", "Sartre"),
        ("A Doll's House", "Ibsen"),
        ("Hedda Gabler", "Ibsen"),
        ("The Cherry Orchard", "Chekhov"),
        ("Uncle Vanya", "Chekhov"),
        ("Long Day's Journey into Night", "O'Neill"),
        ("A Streetcar Named Desire", "Tennessee Williams"),
        ("Death of a Salesman", "Arthur Miller"),
        ("The Crucible", "Arthur Miller"),
        ("Fences", "August Wilson"),
        ("A Raisin in the Sun", "Lorraine Hansberry"),
        ("Our Town", "Thornton Wilder"),
        ("Hamilton (the book of the musical)", "Miranda / Chernow as source"),
    ]
    authors = list(dict.fromkeys(a for _, a in BOOKS_MORE))
    for book, author in BOOKS_MORE:
        B.mc("arts", f"Who wrote {book}?", author, authors, 2)

    FILMS = [
        ("Casablanca", "Michael Curtiz"),
        ("Citizen Kane", "Orson Welles"),
        ("Vertigo", "Alfred Hitchcock"),
        ("Psycho", "Alfred Hitchcock"),
        ("Rear Window", "Alfred Hitchcock"),
        ("2001: A Space Odyssey", "Stanley Kubrick"),
        ("Dr. Strangelove", "Stanley Kubrick"),
        ("The Shining", "Stanley Kubrick"),
        ("The Godfather", "Francis Ford Coppola"),
        ("Apocalypse Now", "Francis Ford Coppola"),
        ("Taxi Driver", "Martin Scorsese"),
        ("Goodfellas", "Martin Scorsese"),
        ("Raging Bull", "Martin Scorsese"),
        ("Jaws", "Steven Spielberg"),
        ("E.T.", "Steven Spielberg"),
        ("Schindler's List", "Steven Spielberg"),
        ("Jurassic Park", "Steven Spielberg"),
        ("Star Wars (1977)", "George Lucas"),
        ("The Empire Strikes Back", "Irvin Kershner"),
        ("Blade Runner", "Ridley Scott"),
        ("Alien", "Ridley Scott"),
        ("Thelma & Louise", "Ridley Scott"),
        ("Pulp Fiction", "Quentin Tarantino"),
        ("Reservoir Dogs", "Quentin Tarantino"),
        ("Do the Right Thing", "Spike Lee"),
        ("Malcolm X (1992 film)", "Spike Lee"),
        ("Moonlight", "Barry Jenkins"),
        ("Get Out", "Jordan Peele"),
        ("Parasite", "Bong Joon-ho"),
        ("Memories of Murder", "Bong Joon-ho"),
        ("Spirited Away", "Hayao Miyazaki"),
        ("My Neighbor Totoro", "Hayao Miyazaki"),
        ("Princess Mononoke", "Hayao Miyazaki"),
        ("Seven Samurai", "Akira Kurosawa"),
        ("Rashomon", "Akira Kurosawa"),
        ("Yojimbo", "Akira Kurosawa"),
        ("Tokyo Story", "Yasujirō Ozu"),
        ("In the Mood for Love", "Wong Kar-wai"),
        ("Chungking Express", "Wong Kar-wai"),
        ("Crouching Tiger, Hidden Dragon", "Ang Lee"),
        ("Brokeback Mountain", "Ang Lee"),
        ("Amélie", "Jean-Pierre Jeunet"),
        ("The 400 Blows", "François Truffaut"),
        ("Breathless", "Jean-Luc Godard"),
        ("Persona", "Ingmar Bergman"),
        ("The Seventh Seal", "Ingmar Bergman"),
        ("8½", "Federico Fellini"),
        ("La Dolce Vita", "Federico Fellini"),
        ("Bicycle Thieves", "Vittorio De Sica"),
        ("The Battle of Algiers", "Gillo Pontecorvo"),
        ("Pan's Labyrinth", "Guillermo del Toro"),
        ("The Shape of Water", "Guillermo del Toro"),
        ("Roma (2018)", "Alfonso Cuarón"),
        ("Y Tu Mamá También", "Alfonso Cuarón"),
        ("Amores Perros", "Alejandro G. Iñárritu"),
        ("The Revenant", "Alejandro G. Iñárritu"),
        ("City of God", "Fernando Meirelles / Kátia Lund"),
        ("Mad Max: Fury Road", "George Miller"),
        ("The Piano", "Jane Campion"),
        ("Portrait of a Lady on Fire", "Céline Sciamma"),
        ("Lady Bird", "Greta Gerwig"),
        ("Little Women (2019)", "Greta Gerwig"),
        ("Nomadland", "Chloé Zhao"),
        ("The Hurt Locker", "Kathryn Bigelow"),
        ("Zero Dark Thirty", "Kathryn Bigelow"),
        ("Cléo from 5 to 7", "Agnès Varda"),
        ("The Gleaners and I", "Agnès Varda"),
        ("Wings of Desire", "Wim Wenders"),
        ("Paris, Texas", "Wim Wenders"),
        ("Run Lola Run", "Tom Tykwer"),
        ("The Lives of Others", "Florian Henckel von Donnersmarck"),
        ("Fargo", "Joel and Ethan Coen"),
        ("No Country for Old Men (film)", "Joel and Ethan Coen"),
        ("The Big Lebowski", "Joel and Ethan Coen"),
        ("There Will Be Blood", "Paul Thomas Anderson"),
        ("Boogie Nights", "Paul Thomas Anderson"),
        ("Magnolia", "Paul Thomas Anderson"),
        ("The Social Network", "David Fincher"),
        ("Fight Club", "David Fincher"),
        ("Se7en", "David Fincher"),
        ("Inception", "Christopher Nolan"),
        ("The Dark Knight", "Christopher Nolan"),
        ("Dunkirk", "Christopher Nolan"),
        ("Arrival", "Denis Villeneuve"),
        ("Blade Runner 2049", "Denis Villeneuve"),
        ("Dune (2021)", "Denis Villeneuve"),
        ("The Lord of the Rings: The Fellowship of the Ring", "Peter Jackson"),
        ("The Shawshank Redemption", "Frank Darabont"),
        ("Forrest Gump", "Robert Zemeckis"),
        ("Back to the Future", "Robert Zemeckis"),
        ("Titanic", "James Cameron"),
        ("Aliens", "James Cameron"),
        ("The Terminator", "James Cameron"),
        ("Avatar", "James Cameron"),
    ]
    dirs = list(dict.fromkeys(d for _, d in FILMS))
    for film, director in FILMS:
        B.mc("arts", f"Who directed {film}?", director, dirs, 2)

    ARTS_MORE = [
        ("A triptych is a work in how many panels, typically?", "Three", ["Two", "Three", "Five", "Seven"], 2),
        ("An etude is a…", "study piece, often for technique", ["folk dance", "study piece, often for technique", "stage fight", "camera move"], 2),
        ("A nocturne is a piece suggesting…", "night", ["war", "night", "a march only", "a fanfare only"], 2),
        ("A requiem is a mass for the…", "dead", ["harvest", "dead", "coronation only", "wedding only"], 2),
        ("An oratorio is like an opera but…", "typically unstaged / sacred concert", ["always comic", "typically unstaged / sacred concert", "only for bagpipes", "silent"], 3),
        ("A madrigal is a…", "Renaissance secular vocal piece", ["Baroque trumpet call", "Renaissance secular vocal piece", "jazz standard always", "film cue"], 3),
        ("Gregorian chant is…", "unaccompanied sacred song of the Latin church", ["a rock genre", "unaccompanied sacred song of the Latin church", "a dance of Spain", "a brass fanfare"], 2),
        ("A toccata is a virtuoso piece, often for…", "keyboard", ["choir only", "keyboard", "bagpipes only", "spoken word"], 3),
        ("The well-tempered system lets a keyboard play in…", "all keys", ["only C major", "all keys", "only pentatonic", "only one mode"], 3),
        ("A fugue is a…", "contrapuntal form with imitative entries", ["waltz only", "contrapuntal form with imitative entries", "12-bar blues only", "sonnet"], 3),
        ("Sonata form typically has exposition, development, and…", "recapitulation", ["coda only always", "recapitulation", "minuet only", "fade-out"], 3),
        ("A cadenza is a…", "virtuoso passage, often near the end of a movement", ["tuning note", "virtuoso passage, often near the end of a movement", "wrong note", "page turn"], 3),
        ("Pianissimo means…", "very soft", ["very loud", "very soft", "very fast", "very slow"], 1),
        ("Fortissimo means…", "very loud", ["very soft", "very loud", "very slow", "held"], 1),
        ("Allegro means…", "fast / cheerful tempo", ["slow", "fast / cheerful tempo", "silent", "out of tune"], 1),
        ("Adagio means…", "slow", ["very fast", "slow", "plucked", "muted"], 1),
        ("Crescendo means…", "getting louder", ["getting quieter", "getting louder", "stopping", "repeating"], 1),
        ("A rest in music is a…", "measured silence", ["wrong note", "measured silence", "new key always", "new instrument"], 1),
        ("A scale of seven notes from do to do is…", "diatonic (major or minor, typically)", ["chromatic only", "diatonic (major or minor, typically)", "only pentatonic", "only blues"], 2),
        ("A pentatonic scale has how many tones?", "5", ["3", "5", "7", "12"], 2),
        ("The chromatic scale has how many pitch classes in equal temperament?", "12", ["7", "8", "12", "24"], 2),
        ("Syncopation accents…", "off-beats / unexpected beats", ["only downbeats", "off-beats / unexpected beats", "only the tonic", "only the conductor"], 2),
        ("Polyrhythm is…", "more than one rhythm at once", ["one rhythm always", "more than one rhythm at once", "no rhythm", "only silence"], 2),
        ("A leitmotif is a…", "recurring theme tied to a person or idea", ["wrong note", "recurring theme tied to a person or idea", "page number", "bowing mark only"], 2),
        ("Wagner's Ring is a cycle of how many operas?", "4", ["2", "3", "4", "5"], 3),
        ("Arias are…", "solo songs in opera (typically)", ["only choruses", "solo songs in opera (typically)", "only overtures", "only ballets"], 1),
        ("Recitative is singing that…", "follows speech rhythm, to advance plot", ["is always a waltz", "follows speech rhythm, to advance plot", "is only hummed", "is instrumental only"], 3),
        ("A pas de deux is a dance for…", "two", ["one", "two", "the whole corps only", "four always"], 2),
        ("The corps de ballet is the…", "ensemble of dancers", ["orchestra", "ensemble of dancers", "stage crew only", "audience"], 2),
        ("Pointe work in ballet is dancing…", "on the tips of the toes", ["in boots", "on the tips of the toes", "only seated", "only with a partner's lift always"], 1),
        ("Martha Graham is a figure of…", "modern dance", ["Baroque opera", "modern dance", "serial music only", "cubist painting only"], 2),
        ("Merce Cunningham is a figure of…", "modern / postmodern dance", ["Renaissance polyphony", "modern / postmodern dance", "only tap", "only flamenco"], 3),
        ("Alvin Ailey's company is based in…", "New York", ["Chicago only", "New York", "Los Angeles only", "London only"], 2),
        ("Savion Glover is a virtuoso of…", "tap dance", ["ballet only", "tap dance", "ice dance only", "ballroom only"], 2),
        ("The Foxtote, waltz, and tango are…", "ballroom / social dances", ["only ballets", "ballroom / social dances", "only operas", "only marches"], 1),
        ("Lindy Hop grew from…", "Harlem / swing-era social dance", ["the minuet at Versailles", "Harlem / swing-era social dance", "court ballet in Russia", "kabuki"], 2),
        ("Breakin' / b-boying is an element of…", "hip-hop", ["waltz", "hip-hop", "minuet", "gavotte"], 1),
        ("Graffiti writing, DJing, MCing, and breaking are classic…", "hip-hop elements", ["opera trades", "hip-hop elements", "Baroque dances", "Greek chorus roles"], 2),
        ("A cypher is a…", "circle where people take turns rapping or dancing", ["film splice", "circle where people take turns rapping or dancing", "sonnet form", "key signature"], 2),
        ("Sampling in music is…", "reusing a recorded snippet in a new work", ["only live orchestra", "reusing a recorded snippet in a new work", "only sheet-music copying by hand", "only humming"], 1),
        ("A concept album is organized around…", "a theme or story", ["only singles with no link", "a theme or story", "only live noise", "only covers of ads"], 2),
        ("Motown was a record label in…", "Detroit", ["Memphis only", "Detroit", "Nashville only", "New Orleans only"], 1),
        ("Stax was a soul label in…", "Memphis", ["Chicago", "Memphis", "New York only", "Los Angeles only"], 2),
        ("Sun Records in Memphis recorded early…", "rock and roll / Elvis among others", ["only disco", "rock and roll / Elvis among others", "only grunge", "only techno"], 2),
        ("The Grand Ole Opry is in…", "Nashville", ["Austin", "Nashville", "Memphis only", "Atlanta"], 1),
        ("Preservation Hall is in…", "New Orleans", ["Chicago", "New Orleans", "Kansas City", "St. Louis"], 1),
        ("The Cotton Club was a famous club in…", "Harlem", ["the French Quarter only", "Harlem", "Storyville only", "Beale Street only"], 2),
        ("Birdland was named for…", "Charlie Parker", ["Duke Ellington", "Charlie Parker", "Benny Goodman", "John Coltrane only"], 3),
        ("Kind of Blue is an album by…", "Miles Davis", ["John Coltrane as leader only", "Miles Davis", "Thelonious Monk as leader only", "Duke Ellington as a suite only"], 2),
        ("A Love Supreme is an album by…", "John Coltrane", ["Miles Davis", "John Coltrane", "Bill Evans as leader", "Ornette Coleman"], 2),
        ("What's Going On is an album by…", "Marvin Gaye", ["Stevie Wonder only", "Marvin Gaye", "The Temptations only", "Aretha as a live set only"], 2),
        ("Songs in the Key of Life is an album by…", "Stevie Wonder", ["Marvin Gaye", "Stevie Wonder", "Prince only", "Michael Jackson only"], 2),
        ("Thriller is an album by…", "Michael Jackson", ["Prince", "Michael Jackson", "Madonna", "Whitney Houston"], 1),
        ("Purple Rain is associated with…", "Prince", ["Michael Jackson", "Prince", "Madonna", "David Bowie"], 1),
        ("The Rise and Fall of Ziggy Stardust is an album by…", "David Bowie", ["Elton John", "David Bowie", "Freddie Mercury as a solo", "Iggy Pop only"], 2),
        ("Nevermind is an album by…", "Nirvana", ["Pearl Jam", "Nirvana", "Soundgarden", "Alice in Chains"], 1),
        ("The Beatles were from…", "Liverpool", ["London only", "Liverpool", "Manchester only", "Hamburg as home"], 1),
        ("Abbey Road is both an album and a…", "studio / street in London", ["stadium in Liverpool", "studio / street in London", "club in Hamburg only", "label in New York only"], 2),
        ("Sgt. Pepper's Lonely Hearts Club Band is an album by…", "the Beatles", ["the Rolling Stones", "the Beatles", "the Who", "the Kinks"], 1),
        ("The Rolling Stones are from…", "London", ["Liverpool", "London", "Manchester", "Birmingham"], 2),
        ("A riff is a…", "short repeated musical figure", ["whole symphony", "short repeated musical figure", "lighting cue", "costume"], 1),
        ("A hook is a…", "catchy musical or lyrical bit", ["wrong note", "catchy musical or lyrical bit", "page turn", "rest"], 1),
        ("Call and response is a pattern from…", "work song, church, and many African diasporic musics (among others)", ["only serialism", "work song, church, and many African diasporic musics (among others)", "only court minuet", "only plainchant always"], 2),
        ("A spiritual in the U.S. is a…", "sacred song from Black American tradition", ["minuet", "sacred song from Black American tradition", "sonnet", "fresco"], 1),
        ("Gospel music in the U.S. grew from…", "Black church traditions (and related white gospel)", ["only sea shanties", "Black church traditions (and related white gospel)", "only opera", "only rags of Scott Joplin as scores"], 2),
        ("Scott Joplin is a master of…", "ragtime", ["bebop only", "ragtime", "disco", "grunge"], 2),
        ("Louis Armstrong was a virtuoso of the…", "trumpet (and voice)", ["violin", "trumpet (and voice)", "organ only", "harp"], 1),
        ("Duke Ellington was a…", "composer and bandleader", ["only a tap dancer", "composer and bandleader", "only a painter", "only a poet of the Beat scene"], 1),
        ("Billie Holiday was a…", "jazz singer", ["opera soprano of La Scala only", "jazz singer", "ballet dancer", "film editor"], 1),
        ("Ella Fitzgerald was famed for…", "jazz singing and scat", ["only composing serial rows", "jazz singing and scat", "only conducting Wagner", "only playing tabla"], 1),
        ("Aretha Franklin was called the…", "Queen of Soul", ["King of Pop", "Queen of Soul", "Empress of Blues only as a title of Bessie", "First Lady of Song only as Ella's epithet"], 1),
        ("Bessie Smith was a star of…", "classic blues", ["disco", "classic blues", "grunge", "techno"], 2),
        ("Robert Johnson is a legend of…", "Delta blues", ["Motown pop", "Delta blues", "West Coast jazz only", "Broadway"], 2),
        ("Muddy Waters helped electrify the blues in…", "Chicago", ["New Orleans only", "Chicago", "Nashville only as country", "Seattle"], 2),
        ("B.B. King was a…", "blues guitarist", ["opera tenor", "blues guitarist", "ballet dancer", "film composer of Herrmann's school only"], 1),
        ("Jimi Hendrix was a virtuoso of…", "electric guitar", ["piano only", "electric guitar", "clarinet", "pedal steel only"], 1),
        ("The Apollo Theater is in…", "Harlem", ["Brooklyn Heights", "Harlem", "the Village only as the Village Gate", "Queens only"], 2),
        ("Carnegie Hall is in…", "New York", ["Boston", "New York", "Philadelphia", "Chicago"], 1),
        ("Symphony Hall is in…", "Boston", ["New York only", "Boston", "Philadelphia as the Academy only", "Chicago as Orchestra Hall only"], 2),
        ("The Met, as an opera house, is in…", "New York", ["Chicago", "New York", "San Francisco only", "Los Angeles only"], 1),
        ("La Scala is in…", "Milan", ["Rome", "Milan", "Naples", "Venice"], 2),
        ("The Paris Opera's palatial house is the…", "Palais Garnier (and the Bastille as a later house)", ["La Scala", "Palais Garnier (and the Bastille as a later house)", "Covent Garden only", "the Bolshoi"], 2),
        ("Covent Garden is an opera house in…", "London", ["Manchester", "London", "Edinburgh", "Dublin"], 1),
        ("The Bolshoi is in…", "Moscow", ["St. Petersburg only as the Mariinsky", "Moscow", "Kiev", "Warsaw"], 2),
        ("The Mariinsky is in…", "St. Petersburg", ["Moscow", "St. Petersburg", "Novosibirsk", "Helsinki"], 3),
        ("The Sydney Opera House was designed by…", "Jørn Utzon", ["Frank Gehry", "Jørn Utzon", "I. M. Pei", "Zaha Hadid"], 3),
        ("Fallingwater was designed by…", "Frank Lloyd Wright", ["Mies van der Rohe", "Frank Lloyd Wright", "Le Corbusier", "Gropius"], 2),
        ("The Guggenheim Museum's spiral in New York is by…", "Frank Lloyd Wright", ["Gehry", "Frank Lloyd Wright", "Piano", "Foster"], 2),
        ("The Guggenheim Museum in Bilbao is by…", "Frank Gehry", ["Wright", "Frank Gehry", "Utzon", "Pei"], 2),
        ("The Louvre Pyramid was designed by…", "I. M. Pei", ["Gehry", "I. M. Pei", "Piano", "Hadid"], 2),
        ("The Centre Pompidou was designed by…", "Piano and Rogers", ["Wright and Sullivan", "Piano and Rogers", "Mies and Johnson", "Scott and Lutyens"], 3),
        ("A flying buttress takes the thrust of a…", "vaulted wall, out to a pier", ["steel frame", "vaulted wall, out to a pier", "glass curtain only", "mud brick"], 2),
        ("A keystone is the…", "central stone of an arch", ["foundation pile", "central stone of an arch", "window mullion", "door sill"], 2),
        ("A column's top is the…", "capital", ["base", "capital", "shaft only as a name for the top", "entablature as the top of the column itself"], 2),
        ("Doric, Ionic, and Corinthian are…", "classical orders", ["jazz forms", "classical orders", "poetic meters", "camera lenses"], 2),
        ("The Ionic order is known for…", "volute (scroll) capitals", ["acanthus leaves only", "volute (scroll) capitals", "no base and the stoutest shaft as Doric's story", "statues as caryatids only"], 3),
        ("A caryatid is a…", "sculpted female figure used as a support", ["water spout", "sculpted female figure used as a support", "stained-glass scene", "mosaic floor"], 3),
        ("A gargoyle is a…", "carved spout, often grotesque", ["column capital", "carved spout, often grotesque", "dome lantern", "floor mosaic"], 2),
        ("A rose window is a…", "circular stained-glass window", ["door", "circular stained-glass window", "crypt", "cloister walk"], 1),
        ("A cloister is a…", "covered walk around a courtyard, often in a monastery", ["bell tower only", "covered walk around a courtyard, often in a monastery", "crypt only", "nave only"], 2),
        ("A nave is the…", "central hall of a church", ["bell", "central hall of a church", "graveyard", "refectory only"], 2),
        ("A minaret is a…", "tower of a mosque", ["spire of a pagoda only", "tower of a mosque", "torii of a shrine", "stupa's dome only"], 1),
        ("A torii is a gate of a…", "Shinto shrine", ["mosque", "Shinto shrine", "synagogue only", "gurdwara only"], 2),
        ("A stupa is a…", "Buddhist monument, often a mound or dome", ["Christian font", "Buddhist monument, often a mound or dome", "Islamic mihrab only", "Hindu gopuram only"], 2),
        ("A mandala is a…", "geometric cosmic diagram, in Buddhist and Hindu art (among uses)", ["sonnet", "geometric cosmic diagram, in Buddhist and Hindu art (among uses)", "sonata", "colonnade"], 2),
        ("Ukiyo-e are…", "Japanese woodblock prints of the 'floating world'", ["Chinese bronzes", "Japanese woodblock prints of the 'floating world'", "Korean celadons only", "Thai murals only"], 2),
        ("Hokusai and Hiroshige are masters of…", "ukiyo-e", ["oil portraiture of the Dutch golden age", "ukiyo-e", "Cubism", "Abstract Expressionism"], 2),
        ("Calligraphy is central to the arts of…", "China, Japan, the Islamic world, and others", ["only graffiti of the 1980s", "China, Japan, the Islamic world, and others", "only runes of the Vikings as a fine-art school", "only type of the Bauhaus"], 2),
        ("Iznik ware is a…", "Ottoman ceramic", ["Ming vase only", "Ottoman ceramic", "Delft only", "Wedgwood only"], 3),
        ("Delftware is a…", "Dutch tin-glazed pottery, often blue and white", ["Chinese celadon", "Dutch tin-glazed pottery, often blue and white", "Greek krater", "Etruscan bucchero"], 2),
        ("A krater in Greek pottery was for…", "mixing wine and water", ["storing grain only", "mixing wine and water", "only oil in the gymnasium as a lekythos", "only perfume"], 3),
        ("A mosaic of tesserae is associated especially with…", "Rome, Byzantium, and Islamic architecture (among others)", ["only Polaroid collage", "Rome, Byzantium, and Islamic architecture (among others)", "only quilts of Gee's Bend as the sole mosaic art", "only LED screens"], 2),
        ("Icon painting in the Orthodox tradition often uses…", "egg tempera on wood", ["oil on canvas only as a rule", "egg tempera on wood", "acrylic on aluminum only", "spray enamel only"], 3),
        ("Illuminated manuscripts are books with…", "painted decoration, often gold", ["only printed type", "painted decoration, often gold", "only blank vellum", "only maps"], 1),
        ("The Book of Kells is an illuminated gospel book of…", "Insular / Irish-British art", ["Ottoman court painting", "Insular / Irish-British art", "Mughal miniatures", "Aztec codices"], 2),
        ("A palimpsest is a…", "reused writing surface with traces of the old text", ["first draft always", "reused writing surface with traces of the old text", "printed broadside", "stone rubbing only"], 3),
        ("An incunabulum is a book printed…", "in Europe before 1501", ["after 1800 only", "in Europe before 1501", "only in China in the 20th century", "only as an ebook"], 3),
        ("Movable type in Europe is credited to…", "Gutenberg", ["Caxton only as the inventor", "Gutenberg", "Aldus as the inventor of type", "Plantin as the inventor"], 2),
        ("The first printed European Bible with movable type is associated with…", "Mainz / Gutenberg", ["Venice / Aldus as the first Bible", "Mainz / Gutenberg", "London / Caxton as the first Bible", "Paris / Estienne as the first Bible"], 2),
    ]
    for prompt, ans, ch, d in ARTS_MORE:
        B.add("arts", prompt, ch, ans, d)
