/** Bump ZZ by 1 on each publish: 0.0.01 → 0.0.02 → … → 0.0.99 → 0.1.00. Keep in sync with package.json "version". */
export const APP_VERSION = "0.0.55";
/** Cache-bust token for hashed /assets JS. */
export const PUBLISH_STAMP = "k55a";
/** Stylesheet outside /assets — that prefix caches 404s for a year. Smoke asserts this path 200. */
export const SHEET_HREF = "/sheet-k07d.css";

// Weekly trivia ship 2026-09-22: cities_weekly + weekly_20260922 wired; Detroit RenCen HQ fix.

// 0.0.12: HQ tab labels (Atlas/Print/Ledger/Standings) high-contrast chips — were invisible on elevated panel.
// 0.0.13: Lantern glass art pass — soot rim, warm wick, short bloom; street + vault hero share layered glass (brass/soot).
// 0.0.13 facade: shop brass awning + CSS hanging lamp; HQ panel brass edge + wick (still k13a, no bump).
// 0.0.13 title folio: white-tier lamp (cap/frame/glass/post) on map block (still k13a, no bump).
// 0.0.14: trivia quota rebalance — trim excess math; deepen specialty red/violet (k14a).
// 0.0.15: Friday weekly trivia audit + growth (k15a).
// 0.0.16: trivia quota fix — cut 37 exact-duplicate math cards (math.ts copies of math_more prompts); +193 deep-cut specialty cards in science/nature/history_life_part_a (wired via weekly_20260922); science_life_part_a placeholder filled (k16a).
// 0.0.17: vault tier contrast — lantern glass/wick/bloom carry the tier hue at full strength (lit palette), brass stays shared; rank pips 1–6 + bloom ramp for colorblind; white vs amber split (k17a).
// 0.0.18: street marker tier fix — The Run marker was hard-coded tier-amber but costs a blue match (map showed amber, toast said "Need a Blue match"); Run/Stack/lamp markup now built in game/pins.ts from series.cost / poi.tier; Run halo ring follows tier; pre-hydration title lamp gets tier-white (k18a).
// 0.0.19: vault ingredients — green+ drops the city's press stock; amber+ at a named ward drops that cut; Print spends one (k19a).
// 0.0.20: ledger quests, lantern cloth, red scrap and violet pattern (k20a).
// 0.0.21: New York walks stay on the curb; map zoom no longer stacks street names (k21a).
// 0.0.22: mystery wheel every 25 of a color; four violet night marks, six-hour dark (k22a).
// 0.0.23: math follows the lamp; more street keys that drift rarer; Video games and Celebrity; Run holds sprint; walks use paths and roads; matchbook matches fill the box (k23a).
// 0.0.24: ride mini-games slice 1 — Play while you ride (Lamplighter), one best-outcome ride payout (idle/played/won), ride white pocket 15; station-sign fare desk; Journal/Places/Supplies/Progress/Leaderboard, Goals, train tickets (k24a). Briefed as "0.0.19 k19a"; main had already shipped 0.0.19–0.0.23.
// 0.0.25: ride games + Lamplighter, train station, Journal renames, trivia QA + anti-repeat, character art fixes (k25a).
// 0.0.25 k25b: Vercel function runtime nodejs20.x → nodejs22.x (Node 20 runtime discontinued; k25a publish failed). Still 0.0.25 — k25a never went live.
// 0.0.26: +358 local trivia cards for Chicago/NYC/SF; easy city cards can be white (k26a).
// 0.0.26 (k26b): upgrade @tanstack/react-start to 1.168.60 (start-server-core 1.169.39) for CVE-2026-102989 / GHSA-qx66-fv34-fjm8.
// 0.0.27: +374 local cards Detroit/London/Austin/Temple/Tucson; +297 local cards Toronto/New Orleans/Boston/LA (k27a).
// 0.0.28: +140 video game and +140 celebrity trivia cards; +141 history cards; Cary Grant fix; duplicate/odd-distractor cleanup (k28a).
// 0.0.29: Where am I? ride game for 2–6 min rides (clues from shipped city lore); history cleanup — 17 duplicate cards dropped (history and general.ts), odd only/as distractors fixed in 164 cards (k29a).
// 0.0.30: Where am I? perfect-round bonus (+1 white flat on 5/5); Temple and Tucson clue pools rebuilt from verified places (28 and 32 clues, real coordinates, unverified marks kept out of clues); 69 weak or dated clues rewritten across cities (k30a).
// 0.0.31: Fix Leaflet appendChild crash (aborted routes no longer draw a stale path on a removed map); Temple map: 7 nonexistent marks retired (3 replaced by real Jones Park and Santa Fe Plaza), Woodson Field fixed; saves migrate retired ids (k31a).
// 0.0.32: Walk pathing — foot-only routing (the car-profile OSRM fallback sent walks down the Lodge Freeway), one walkable-way rule (no motorways, trunks, ramps, foot=no) for the street graph, server fetch and match placement; Detroit street bake redone off the freeways; matches collect from the closest curb (k32a).
// 0.0.33: Match sorter ride game shares the 2–6 min band with Where am I? (picked per ride, ~50/50) — sort tumbling matches into the six tier boxes, colors plus rank pips, tap/drag/keys 1–6, +1 white on 26/26; Tucson: Congress/Granada stop and Five Points moved to their real spots, Sosa Avenue retired for the real Sosa–Carrillo–Frémont House (k33a).
// 0.0.34: Friday weekly trivia audit + 24 new cards (Temple/Austin/Tucson/London gaps + thin political/non-math topics); bank weekly_20261002 (k34a).
// 0.0.35: ride game variety — 2–6 min rides deal Where am I? or Match sorter at random, weighted against this save's recent rides (never 3 in a row); the dealt game is stored on the ride (k35a).
// 0.0.36: Route puzzle ride game for 6 min+ rides (fares cap at 14:00, so that's every long ride) — a little map of real places in the city ahead, tap the stops in the shortest order from S to F, three maps a round, letters/shapes/dashes so colour is never the only cue, tap or keys; 3/3 shortest pays the perfect +1 white (k36a).
// 0.0.37: character art — the Lynx is its own animal (ear tufts, bobbed black-tipped tail, cheek ruff, stockier build, spotted tawny fur) instead of a recoloured fox; the Tabby's walk coat was olive green while it idled in brown, now brown throughout; every character keeps facing left/right when it stops (side idle sheets); qa:sprites fails shared silhouettes, walk/idle coat mismatches and missing side idles (k37a).
// 0.0.38: the Turtle walks in the brown hooded coat it idles in (it walked as a bare green shell); qa:sprites checks the coat on every walk facing and the shop icon at a tighter 3.2 limit (raccoon 5.5), so a shell-vs-coat mismatch fails (k38a).
// 0.0.39: trivia answers no longer give themselves away by length — 1302 cards where the correct answer was clearly the longest choice (40%+ or 12+ characters longer than every wrong choice) got parallel, plausible wrong choices or a trimmed answer; trivia:lint flags any new one and a test keeps the answer-is-longest rate near chance (42.5% → 32.3%, cap 35%) (k39a).
// 0.0.40: trivia duplicates cleared — 3 unwired copy banks (133 cards) removed, the remaining duplicate groups kept-best or rewritten into new verified cards; 129 absolute-tell cards (every wrong choice said only/always/never) given plain distractors; +55 verified Temple cards (Santa Fe depot and Harvey House, Scott & White, Belton Lake, McLane, local sports and notables) across history/sports/arts/nature/science, Temple 90 → 145; trivia:lint 324 → 0 warnings (k40a).
// 0.0.41: ride game picker — on a train ride the player picks the mini-game: every game whose minimum round fits the time left (Lamplighter 15 s, Where am I? and Match sorter ~34 s, Route puzzle 2 min) is listed with an icon and a one-liner, the varied 0.0.35 deal is pre-selected as Suggested, the pick is stored on the ride, and after a round the player can go again or switch games (the ride pays its best round; pay never depends on the game; Lamplighter's all-lit no-stray round now earns the same +1 perfect bonus as the others). Reverses the 0.0.35 'no swap button' call. City-local card check: no Austin cards in Detroit's block; a test guards cards naming another city (k41a).
// 0.0.42: polish — Stop mid-round on a ride says the round was stopped (tab-closed wording only after a real tab close); math cap: math is 25.7% of trivia cards, so trivia:quotas and the weekly/bulk generators block new math while it is over 20%, and lamps offer Math on ~19% of visits (was ~44%), so even an always-Math player gets under 20% math (no cards removed); ride result no longer says "Pocket's full" when a round simply paid the seat's rate; "too close for another round" shown after a late finish (k42a).
// 0.0.43: Daily Lantern Run — one shared five-lamp route per city per UTC day (seeded by UTC date + city; named marks within 1.6 km of spawn, no outfitter/station, every pair 400 m+ apart, walked nearest-next from spawn), drawn on the map as a dashed foot route (foot router, walk-graph fallback, never freeways) with numbered lamps; route lamps light on foot within 80 m (or at the curb nearest a set-back lamp), the clock runs lamp 1 → lamp 5; per-city daily board (First L. names) on the existing Postgres + sign-in, one run per walker per UTC day (lamp 1 locks the day and city, no restarts), the server times every leg on its own clock and refuses legs faster than a straight-line full sprint by the fastest coat (3 strikes voids the day), 2 h limit; finishing pays 2 white + 1 blue once a day (150 coin on the ladder; a full pocket pays coin); guests run on the local clock and post nothing (k43a).
// 0.0.44: Daily Lantern Run is one run per walker per city per UTC day (was one a day across all cities) — migration 0007 widens the daily_runs key to day + user + city (0.0.43 rows stay valid); the server looks up, starts, lights, strikes and voids each city's entry on its own, and the client keeps a run per city (no more 'under way in another city' block); each city's finish pays its own 2 white + 1 blue, once per city per day; every other anti-abuse rule unchanged (lamps in order, server clock, impossible-leg refusal, 170 m position check, 2 h limit, 3 refused legs void that city's entry) (k44a).
// 0.0.45: print shop — spend white and blue matches at the outfitter's new Print shop counter on four cosmetic coats (Oilskin Slicker 15w, Bottle-Green Duster 10w+4b, Oxblood Greatcoat 8w+6b, Plum Frock Coat 4w+10b) and four lantern skins (Copper Lamp 10w, Wrought Iron 8w+2b, Verdigris 6w+4b, Nickel Plate 8b); paid in instalments (the shop keeps what's paid against each item), the last match prints it and puts it on; wear / take off from the counter or Journal · Supplies · Wardrobe; purely visual. Coats are scripted recolours of every character's own coat on walk, idle and side-idle sheets (96 sheets, alpha byte-identical to the base); lantern skins re-case cap, rim and post only — glass, wick, bloom and pips keep the tier colour. Signed-in wardrobes sync to Postgres (migration 0008 wardrobes; ownership unions, newest equip wins), guests keep theirs in the local save. qa:sprites checks every coat variant: same silhouette, coat shown in every pose, on its catalogue hue, one coat per outfit (k45a).
// 0.0.46: Night markets — in each city one street is a night market for one UTC hour and rewards earned on it pay ×2. Shared and serverless: the street is drawn from the city's baked list (src/game/marketStreets.ts, bake: scripts/bake-market-streets.mts, OSM snapshot 2026-10-03) with an FNV-1a seed of city + UTC hour label (e.g. detroit|2026-10-03T10), so every walker sees the same market without the server; even hours take their draw, odd hours step past both even neighbours' streets, so it never sits on the same street two hours running and any hour is worked out from its own and its neighbours' seeds (no chain back to the epoch). Eligible streets: a named pedestrian/living/residential/unclassified/tertiary/secondary/primary street that passes isWalkableWay (walkable.ts), above ground (no tunnels or lower decks), never a freeway (no motorway/trunk/ramp stretch under that name and no freeway/expressway/service-drive name), in the walk component reachable on foot from spawn (largest walk next to spawn, so a plaza island can't strand it), at least 150 m within 1.6 km of spawn (the Lantern Run reach, clipped there), and with at least one named lamp (any mark but the outfitter) within 60 m — matches are per-walker and random, so they can't decide a shared street; instead, while a market is open every other new street match drops along it. Doubled: a lamp's trivia-card coin and its bonus matches (lucky charm, perfect blue) for named lamps on the street and blank lamps within 60 m; a spark's match; The Run / The Stack coin and matches when its lamp stands within 30 m; street matches picked up within 30 m (two). The pocket caps still hold: a market match that won't fit pays its ladder value in coin (white 30, blue 90, green 270) and a full-pocket spark pays 24 coin instead of 12. The market that counts is the one open (wall clock, UTC hour) when the trivia card was dealt or the match picked up. Not doubled: the Daily Lantern Run finish (server-checked 2 white + 1 blue), print shop prices, the bank exchange, ride payouts, boost cards, cloth tips, goals, contracts, train tickets, the mystery wheel, materials (brass/ink/vellum/schematics/ingredients); leaderboard clears still count one per trivia card, so the server's tallies are unchanged (matches live in the local save; no server pays a market reward). Map: an orange breathing glow + dotted core along the street and a lantern sign at its middle ('Night market ×2', street, time left); HUD line 'Night market · <street> · N min left · ×2' (tap to walk to its nearest stretch); Journal · Places leads with the market row (until when, its lamps, next hour's street) and tags its lamps; the lamp sight and the reward pop say 'Night market ×2' with the coin it added (k46a).
// 0.0.47: phone HUD — under 640 px wide the top button row (music, sound, Daily, Help, Satchel, Journal) sat beside the status plate and squeezed it to ~30 px (80 px before the 0.0.43 Daily button), so city/ticket/Next/Goals/Train/Daily/night-market lines were an unreadable sliver and the coin count spilled out; now the buttons sit on top as 40 px squares and the plate stacks under them at full width (288–358 px at 360–430 px), 640–1023 px keeps them side by side with icon-only buttons and a non-shrinking button row, desktop (1024 px+) unchanged; qa:hud-mobile checks the plate is 200 px+ at phone, landscape, tablet sizes. Reward pop shows the boost line ('Perfect timing · Category charm') once — it was also repeated in the toast line (k47a).
// 0.0.48: three new cities — Seattle, Denver and Nashville, each with OSM-checked places, an outfitter/print shop, a train station, goals, its own Daily Lantern Run, baked foot streets and night-market streets, and city-local trivia cards (Seattle 157, Denver 151, Nashville 160, sourced); city picker says Fifteen cities. Phone HUD: the bottom-right lamp card (place name / 'At the lamp · E or tap') stays fully on screen at 360–430 px — at 390x844 a long name ran it off the right edge; long names now wrap to two lines inside the card and the match belt is tighter; qa:hud-mobile checks the lamp card and E button on portrait phones (k48a).
// 0.0.49: The Penguin replaces the lynx — the Super Legendary is now a round painted penguin (black cap, white heart face, small eyes, rosy cheeks, orange beak and feet) in a cornflower pea coat and red scarf, carrying the lantern, with a waddle walk; drawn from scratch by scripts/draw-penguin.py (walk, idle, side idle, icon, and the four print-shop coats via make-coat-variants.py); internal id stays `lynx` so saves keep the hire, the worn scout and its coats; sprite stamps k49p (k49a).
// 0.0.50: Friend tickets — after answering a trivia card a signed-in walker can tap 'Send as a friend ticket' to share that exact card as a link (/t/<token>, native share sheet or copy link); the friend signs in (guests are prompted), gets the same card on the same 25 s wick timed by the server clock, and a right answer pays both of them +1 White match (a full pocket pays 30 coin); the sender's next load or 45 s poll lands it with a small toast naming the friend First L. Server-authoritative (migration 0009 friend_tickets / friend_ticket_days / rate_hits): the card and its answer are copied from the server's own bank and the answer never reaches the friend before they answer; no self-redemption, one redemption per ticket (the first friend to open claims it), 48 h expiry, 5 tickets and 3 rewarded redemptions per sender per UTC day, a friend pair (either direction) rewards once per UTC day (unique index), 144-bit random tokens, guests can't send, every endpoint rate-limited (k50a).
// 0.0.51: The Giraffe joins the cast — a new hire (42,000 coins, between the Sloth and the Fox), painted from scratch in the Penguin's soft-shaded style (scripts/draw-giraffe.py, v2 art k51h): a cute chibi giraffe with a big round head, honey fur and caramel patches, cream muzzle, small dot eyes, rosy cheeks, short ossicones and a short neck rising from the collar of a teal duffle coat, carrying the lantern with a gentle lope; all four print-shop coats; perk 'Names places from a little farther' (sight 1.2: the atlas naming radius only — no coin, lamp time, pace or reach change); its own bed 'Over the rooftops' (k51a).
// 0.0.52: phone lamp-card polish — under 640 px the map's +/- zoom hides while the lamp card is open (it sat on the card's top-left corner, over the lamp); the card's Leave lamp / Forfeit button lives in a footer that never scrolls, and on short phones (height 880 px or less) the six fields are a 2x3 grid of names (blurb on hover/title), so at 360x780 and 390x844 the lamp, the fields and Leave lamp all fit without scrolling; the bottom-right lamp card's kicker wraps to two lines on phones instead of cutting to 'WHITE · …'; Nashville walks start on Broadway in front of Robert's Western World (new City.start; spawn still anchors the Daily Lantern Run, night-market and street bakes), so a new walker's first card is a lamp, not the Lower Broad Tailor. Trivia choices on iPhone: one answer button could look lit (lighter fill and border) before any tap — not an answer leak (every choice had the same markup; the lit one was whichever sat under the last tap, right or wrong) but iOS Safari's sticky :hover from the field tap; choice/field/ride-game hover styles now only apply under @media (hover: hover), choices render through game/choiceMarkup.ts (same class for all, keyed per card so each card mounts fresh buttons), any focused button is blurred when a card opens, and choiceMarkup.test.ts checks the choices differ only by text before the answer. Desktop unchanged (k52a).
// 0.0.53: trivia answers live on the server — the bank (banks/*, trivia.ts) and the 62 door quizzes (moved out of data.ts into server-only doorQuizzes.ts) are no longer in the browser bundle. A lamp asks the server for a card (triviaApi.dealTrivia): the server picks it with the same picker (the save's seen ids for anti-repeat, tier/rarity ladder and weekly retune, place topics and door quizzes, city-tagged cards, Run/Stack difficulty steps) and returns the prompt and server-shuffled choices with a public card id (sha256 of prompt + sorted choices — the old fnv1a(prompt + answer) id could be brute-forced to the answer) and a signed pending-card token (HMAC, stateless, no migration). The answer goes back as the chosen text (gradeTrivia); the server grades it on its own clock (the client's stopwatch, never more than 1.2 s faster than the server saw, so perfect timing can't be faked; past the wick + 2.5 s is a timeout), and only then reveals the answer and fact. For a signed-in walker the server writes the plate event and, on a right answer, the +1 rolls clear itself — the client-callable reportCorrect/reportPlate are gone; a token grades once (replays get the first result and credit nothing). Guests play on an anonymous token; the wick starts when the card arrives; nothing is spent if the card office can't be reached. Friend tickets resolve public ids. qa:no-answers fails the gate if a card prompt, a known answer or an answer key is in the built client (k53a).
// 0.0.53 (k53a, cont.): the "Send as a friend ticket" chip nudges less — it came back after every answered card (15 s each, X only hid it until the next); now X ("Not now") hides it for 24 h (localStorage, survives reload) and a session gets at most one unused nudge (sessionStorage) — sending a ticket does not use it up (game/friendOffer.ts).
// 0.0.53 (k53a, cont.): Not now no longer blocks sending — the Journal (Progress tab) has a quiet "Send a friend ticket" row listing the last 3 answered cards (localStorage, kept even while the chip is snoozed), each opening the same send sheet; it ignores the chip's snooze and session cap, the server's 5-a-day cap still applies.
// 0.0.53 (k53a, merge of 0.0.52b): freeway pathing fix — a baked per-city freeway no-walk layer (public/streets/*-fw.json); walk starts, cut-building walks, stuck nudges, cab exits and placeOnStreet slide clear of freeway centerlines, online routes that ride a freeway are refused, so Chicago's Ohio Street feeder no longer carries the walker. Plus the friend-ticket pop-up cooldown (Not now = 24 h, one unused nudge a session) and the Journal's always-there "Send a friend ticket" row.
// 0.0.54: a gift for Halish — The Giraffe, free, with a one-time note ("Hope you get out of the hospital soon - Love Grok") and Wear it now / Close. Generic gifts table (migration 0010: gifts + gift_claims, one seeded row keyed by user id with a first-name fallback); the scout lands in the save on every device he signs into, the server claim keeps the note to once (k54a). City unlocks move to 0.0.55.
// 0.0.55: standings duplicates — one walker, several sign-ins, one row. Signing in another way (X on a phone) made new users, so Ryan showed 3 times. Player links (migration 0011: player_links + link_codes, same-email auto-link, *_by_player views folding vault_clears / plate_events / daily_runs to the oldest user id), a "On the board twice?" link-by-code row on the Leaderboard, a deterministic broker email for X sign-ins without one (provider + account id) plus a new-identity log line, and Ryan's confirmed merge (0012: his two X users fold into MXKB…, their X identities re-pointed to it, alias sessions ended) (k55a). City unlocks move to 0.0.56.
