/** Bump ZZ by 1 on each publish: 0.0.01 → 0.0.02 → … → 0.0.99 → 0.1.00. Keep in sync with package.json "version". */
export const APP_VERSION = "0.0.46";
/** Cache-bust token for hashed /assets JS. */
export const PUBLISH_STAMP = "k46a";
/** Stylesheet outside /assets — that prefix caches 404s for a year. Smoke asserts this path 200. */
export const SHEET_HREF = "/sheet-k07d.css";

// Weekly trivia ship 2026-09-22: cities_weekly + weekly_20260922 wired; Detroit RenCen HQ fix.

// 0.0.12: HQ tab labels (Atlas/Print/Ledger/Standings) high-contrast chips — were invisible on elevated panel.
// 0.0.13: Lantern glass art pass — soot rim, warm wick, short bloom; street + vault hero share layered glass (brass/soot).
// 0.0.13 facade: shop brass awning + CSS hanging lamp; HQ panel brass edge + wick (still k13a, no bump).
// 0.0.13 title folio: white-tier lamp (cap/frame/glass/post) on map block (still k13a, no bump).
// 0.0.14: trivia quota rebalance — trim excess math; deepen specialty red/violet (k14a).
// 0.0.15: Friday weekly trivia audit + growth (k15a).
// 0.0.16: trivia quota fix — cut 37 exact-duplicate math cards (math.ts copies of math_more prompts); +193 deep-cut specialty cards in science/nature/history_life_part_a (wired via weekly_20260922); science_life_part_a placeholder filled (k16a).
// 0.0.17: vault tier contrast — lantern glass/wick/bloom carry the tier hue at full strength (lit palette), brass stays shared; rank pips 1–6 + bloom ramp for colorblind; white vs amber split (k17a).
// 0.0.18: street marker tier fix — The Run marker was hard-coded tier-amber but costs a blue match (map showed amber, toast said "Need a Blue match"); Run/Stack/lamp markup now built in game/pins.ts from series.cost / poi.tier; Run halo ring follows tier; pre-hydration title lamp gets tier-white (k18a).
// 0.0.19: vault ingredients — green+ drops the city's press stock; amber+ at a named ward drops that cut; Print spends one (k19a).
// 0.0.20: ledger quests, lantern cloth, red scrap and violet pattern (k20a).
// 0.0.21: New York walks stay on the curb; map zoom no longer stacks street names (k21a).
// 0.0.22: mystery wheel every 25 of a color; four violet night marks, six-hour dark (k22a).
// 0.0.23: math follows the lamp; more street keys that drift rarer; Video games and Celebrity; Run holds sprint; walks use paths and roads; matchbook matches fill the box (k23a).
// 0.0.24: ride mini-games slice 1 — Play while you ride (Lamplighter), one best-outcome ride payout (idle/played/won), ride white pocket 15; station-sign fare desk; Journal/Places/Supplies/Progress/Leaderboard, Goals, train tickets (k24a). Briefed as "0.0.19 k19a"; main had already shipped 0.0.19–0.0.23.
// 0.0.25: ride games + Lamplighter, train station, Journal renames, trivia QA + anti-repeat, character art fixes (k25a).
// 0.0.25 k25b: Vercel function runtime nodejs20.x → nodejs22.x (Node 20 runtime discontinued; k25a publish failed). Still 0.0.25 — k25a never went live.
// 0.0.26: +358 local trivia cards for Chicago/NYC/SF; easy city cards can be white (k26a).
// 0.0.26 (k26b): upgrade @tanstack/react-start to 1.168.60 (start-server-core 1.169.39) for CVE-2026-102989 / GHSA-qx66-fv34-fjm8.
// 0.0.27: +374 local cards Detroit/London/Austin/Temple/Tucson; +297 local cards Toronto/New Orleans/Boston/LA (k27a).
// 0.0.28: +140 video game and +140 celebrity trivia cards; +141 history cards; Cary Grant fix; duplicate/odd-distractor cleanup (k28a).
// 0.0.29: Where am I? ride game for 2–6 min rides (clues from shipped city lore); history cleanup — 17 duplicate cards dropped (history and general.ts), odd only/as distractors fixed in 164 cards (k29a).
// 0.0.30: Where am I? perfect-round bonus (+1 white flat on 5/5); Temple and Tucson clue pools rebuilt from verified places (28 and 32 clues, real coordinates, unverified marks kept out of clues); 69 weak or dated clues rewritten across cities (k30a).
// 0.0.31: Fix Leaflet appendChild crash (aborted routes no longer draw a stale path on a removed map); Temple map: 7 nonexistent marks retired (3 replaced by real Jones Park and Santa Fe Plaza), Woodson Field fixed; saves migrate retired ids (k31a).
// 0.0.32: Walk pathing — foot-only routing (the car-profile OSRM fallback sent walks down the Lodge Freeway), one walkable-way rule (no motorways, trunks, ramps, foot=no) for the street graph, server fetch and match placement; Detroit street bake redone off the freeways; matches collect from the closest curb (k32a).
// 0.0.33: Match sorter ride game shares the 2–6 min band with Where am I? (picked per ride, ~50/50) — sort tumbling matches into the six tier boxes, colors plus rank pips, tap/drag/keys 1–6, +1 white on 26/26; Tucson: Congress/Granada stop and Five Points moved to their real spots, Sosa Avenue retired for the real Sosa–Carrillo–Frémont House (k33a).
// 0.0.34: Friday weekly trivia audit + 24 new cards (Temple/Austin/Tucson/London gaps + thin political/non-math topics); bank weekly_20261002 (k34a).
// 0.0.35: ride game variety — 2–6 min rides deal Where am I? or Match sorter at random, weighted against this save's recent rides (never 3 in a row); the dealt game is stored on the ride (k35a).
// 0.0.36: Route puzzle ride game for 6 min+ rides (fares cap at 14:00, so that's every long ride) — a little map of real places in the city ahead, tap the stops in the shortest order from S to F, three maps a round, letters/shapes/dashes so colour is never the only cue, tap or keys; 3/3 shortest pays the perfect +1 white (k36a).
// 0.0.37: character art — the Lynx is its own animal (ear tufts, bobbed black-tipped tail, cheek ruff, stockier build, spotted tawny fur) instead of a recoloured fox; the Tabby's walk coat was olive green while it idled in brown, now brown throughout; every character keeps facing left/right when it stops (side idle sheets); qa:sprites fails shared silhouettes, walk/idle coat mismatches and missing side idles (k37a).
// 0.0.38: the Turtle walks in the brown hooded coat it idles in (it walked as a bare green shell); qa:sprites checks the coat on every walk facing and the shop icon at a tighter 3.2 limit (raccoon 5.5), so a shell-vs-coat mismatch fails (k38a).
// 0.0.39: trivia answers no longer give themselves away by length — 1302 cards where the correct answer was clearly the longest choice (40%+ or 12+ characters longer than every wrong choice) got parallel, plausible wrong choices or a trimmed answer; trivia:lint flags any new one and a test keeps the answer-is-longest rate near chance (42.5% → 32.3%, cap 35%) (k39a).
// 0.0.40: trivia duplicates cleared — 3 unwired copy banks (133 cards) removed, the remaining duplicate groups kept-best or rewritten into new verified cards; 129 absolute-tell cards (every wrong choice said only/always/never) given plain distractors; +55 verified Temple cards (Santa Fe depot and Harvey House, Scott & White, Belton Lake, McLane, local sports and notables) across history/sports/arts/nature/science, Temple 90 → 145; trivia:lint 324 → 0 warnings (k40a).
// 0.0.41: ride game picker — on a train ride the player picks the mini-game: every game whose minimum round fits the time left (Lamplighter 15 s, Where am I? and Match sorter ~34 s, Route puzzle 2 min) is listed with an icon and a one-liner, the varied 0.0.35 deal is pre-selected as Suggested, the pick is stored on the ride, and after a round the player can go again or switch games (the ride pays its best round; pay never depends on the game; Lamplighter's all-lit no-stray round now earns the same +1 perfect bonus as the others). Reverses the 0.0.35 'no swap button' call. City-local card check: no Austin cards in Detroit's block; a test guards cards naming another city (k41a).
// 0.0.42: polish — Stop mid-round on a ride says the round was stopped (tab-closed wording only after a real tab close); math cap: math is 25.7% of trivia cards, so trivia:quotas and the weekly/bulk generators block new math while it is over 20%, and lamps offer Math on ~19% of visits (was ~44%), so even an always-Math player gets under 20% math (no cards removed); ride result no longer says "Pocket's full" when a round simply paid the seat's rate; "too close for another round" shown after a late finish (k42a).
// 0.0.43: Daily Lantern Run — one shared five-lamp route per city per UTC day (seeded by UTC date + city; named marks within 1.6 km of spawn, no outfitter/station, every pair 400 m+ apart, walked nearest-next from spawn), drawn on the map as a dashed foot route (foot router, walk-graph fallback, never freeways) with numbered lamps; route lamps light on foot within 80 m (or at the curb nearest a set-back lamp), the clock runs lamp 1 → lamp 5; per-city daily board (First L. names) on the existing Postgres + sign-in, one run per walker per UTC day (lamp 1 locks the day and city, no restarts), the server times every leg on its own clock and refuses legs faster than a straight-line full sprint by the fastest coat (3 strikes voids the day), 2 h limit; finishing pays 2 white + 1 blue once a day (150 coin on the ladder; a full pocket pays coin); guests run on the local clock and post nothing (k43a).
// 0.0.44: Daily Lantern Run is one run per walker per city per UTC day (was one a day across all cities) — migration 0007 widens the daily_runs key to day + user + city (0.0.43 rows stay valid); the server looks up, starts, lights, strikes and voids each city's entry on its own, and the client keeps a run per city (no more 'under way in another city' block); each city's finish pays its own 2 white + 1 blue, once per city per day; every other anti-abuse rule unchanged (lamps in order, server clock, impossible-leg refusal, 170 m position check, 2 h limit, 3 refused legs void that city's entry) (k44a).
// 0.0.45: print shop — spend white and blue matches at the outfitter's new Print shop counter on four cosmetic coats (Oilskin Slicker 15w, Bottle-Green Duster 10w+4b, Oxblood Greatcoat 8w+6b, Plum Frock Coat 4w+10b) and four lantern skins (Copper Lamp 10w, Wrought Iron 8w+2b, Verdigris 6w+4b, Nickel Plate 8b); paid in instalments (the shop keeps what's paid against each item), the last match prints it and puts it on; wear / take off from the counter or Journal · Supplies · Wardrobe; purely visual. Coats are scripted recolours of every character's own coat on walk, idle and side-idle sheets (96 sheets, alpha byte-identical to the base); lantern skins re-case cap, rim and post only — glass, wick, bloom and pips keep the tier colour. Signed-in wardrobes sync to Postgres (migration 0008 wardrobes; ownership unions, newest equip wins), guests keep theirs in the local save. qa:sprites checks every coat variant: same silhouette, coat shown in every pose, on its catalogue hue, one coat per outfit (k45a).
// 0.0.46: Night markets — in each city one street is a night market for one UTC hour and rewards earned on it pay ×2. Shared and serverless: the street is drawn from the city's baked list (src/game/marketStreets.ts, bake: scripts/bake-market-streets.mts, OSM snapshot 2026-10-03) with an FNV-1a seed of city + UTC hour label (e.g. detroit|2026-10-03T10), so every walker sees the same market without the server; even hours take their draw, odd hours step past both even neighbours' streets, so it never sits on the same street two hours running and any hour is worked out from its own and its neighbours' seeds (no chain back to the epoch). Eligible streets: a named pedestrian/living/residential/unclassified/tertiary/secondary/primary street that passes isWalkableWay (walkable.ts), above ground (no tunnels or lower decks), never a freeway (no motorway/trunk/ramp stretch under that name and no freeway/expressway/service-drive name), in the walk component reachable on foot from spawn (largest walk next to spawn, so a plaza island can't strand it), at least 150 m within 1.6 km of spawn (the Lantern Run reach, clipped there), and with at least one named lamp (any mark but the outfitter) within 60 m — matches are per-walker and random, so they can't decide a shared street; instead, while a market is open every other new street match drops along it. Doubled: a lamp's trivia-card coin and its bonus matches (lucky charm, perfect blue) for named lamps on the street and blank lamps within 60 m; a spark's match; The Run / The Stack coin and matches when its lamp stands within 30 m; street matches picked up within 30 m (two). The pocket caps still hold: a market match that won't fit pays its ladder value in coin (white 30, blue 90, green 270) and a full-pocket spark pays 24 coin instead of 12. The market that counts is the one open (wall clock, UTC hour) when the trivia card was dealt or the match picked up. Not doubled: the Daily Lantern Run finish (server-checked 2 white + 1 blue), print shop prices, the bank exchange, ride payouts, boost cards, cloth tips, goals, contracts, train tickets, the mystery wheel, materials (brass/ink/vellum/schematics/ingredients); leaderboard clears still count one per trivia card, so the server's tallies are unchanged (matches live in the local save; no server pays a market reward). Map: an orange breathing glow + dotted core along the street and a lantern sign at its middle ('Night market ×2', street, time left); HUD line 'Night market · <street> · N min left · ×2' (tap to walk to its nearest stretch); Journal · Places leads with the market row (until when, its lamps, next hour's street) and tags its lamps; the lamp sight and the reward pop say 'Night market ×2' with the coin it added (k46a).
